### ISSUE TITLE
Collections Redesign Implementation

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#13660]
Tracking work for an update to collections to make it much easier to browse through collections. This update also includes some UI tweaks to collection content lists to make them easier to use.

**Links**
- [Product doc](https://docs.google.com/document/d/1LGLyhnCeAVzQ4wuaqgTKmOdkR4Gxb2nTge750N-XonA/edit)
- Feature branch: `0.38-collections-redesign`

**Implementation Plan**

**ETA**: 11/20/2020

- [x] Mock out new UI and components 
- [X] Update / add endpoint to return all collections a user can see in a nested structure (https://github.com/metabase/metabase/commit/8303be7675f3dffd760554de55481c76c98997b1)
- [x] Wire up endpoint and new collections sidebar (https://github.com/metabase/metabase/pull/13684)
- [x] Update collection page to use new components / integrate with sidebar (https://github.com/metabase/metabase/pull/13684)
- [x] Add expand / collapse actions (https://github.com/metabase/metabase/pull/13684)
- [x] Update visual design for collection content (pins, items)
- [x] Update visual design for collection sidebar 
- [x] Update admin personal collection browsing.
- [x] Fix issue where `ItemPicker` relies on old list endpoint structure for the collections entity api https://github.com/metabase/metabase/pull/13765/commits/e909deeb0f9361b9d2c4de6b0e432b2afee00cda
- [x] Visual design tweaks based on feedback https://github.com/metabase/metabase/pull/13822
- [x] Need to be able to move pinned items
- [x] Open ancestral collections in the sidebar when deep linking https://github.com/metabase/metabase/pull/13765/commits/5ed274e99a1a2df2bcfdd66577170bd4330710c3
- [x] Update sidebar drag and drop hover styles

**Tests**
- [x] Update test fixture data to have a few deeply nested collections with long names. -https://github.com/metabase/metabase/pull/13846
- [x] Fix up basic drag and drop between collection content and the sidebar
- [x] Update and expand collection related cypress tests.  https://github.com/metabase/metabase/pull/13846

**Comment by kdoh** [comment]
### Status - Feels on track to merge 11/13

**Here's where we are:**
We have things hooked up and working end to end. The new endpoint and the tree browsing for collections on real data is all put together.

**What we need to do this week:**
- The goal for this week should be to get things into a state where we can see if things are working or not as early as possible. To me that means - **get the visual design to a level of polish that doesn't distract from the new behavior**. The main things there are the collection sidebar itself and the new styling for the collection content. I hope to put up a pair of PRs for both today that should tackle those and get things to about 90% fidelity so we can move on to other bits and bobs. I expect this to take most of Monday and part of Tuesday and take up the bulk of my day both days.

- Stress test the tree structure with long names and nesting. I'll need to update the fixture db to have some longer collection names and deeper nesting. This should help us see where the design falls down and make sure we can address it with a couple strategies I researched last week.

- Admin personal collection browsing shouldn't need too much of an update behavior wise, but we do need to address it still.

- Write new tests to reflect the new behavior.
We should add a series of cypress tests that address the nesting behavior and also make sure that we account for edge cases. We'll likely need to update the cypress test db seeding to have a nested collection structure. Will likely need some help from @nemanjaglumac and @camsaul on this part in particular.

### Milestones for the week

1. Have the main feature branch in a reviewable state by 11/10 (Tues). Hopefully no major new work is needed after Tuesday, 
2. Get feedback from on the branch from our team on 11/11.
3. New test writing and code review 11/11 - 11/12
4. Merge on 11/13, ideally by mid afternoon EST.

**Comment by camsaul** [comment]
Hey @kdoh anything I can help with to get this merged in today?

**Comment by rlotun** [comment]
**Status**: As of the pod planning meeting today this looks like it's almost complete, though some help with testing is needed. I'm tentatively updating the ETA to EOW (Nov 20).

**Comment by kdoh** [comment]
@rlotun That sounds about right to me. I was waiting to add more explicit todos and update the ETA until I heard back from @salsakran and @mazameli to get a sense of any other outstanding issues or thoughts after using things further. But until I hear more there I think we're more in housekeeping mode.
