### ISSUE TITLE
Waterfall Chart Implementation

### ISSUE THREAD

**Issue by paulrosenzweig** [metabase/metabase#13661]
We're adding a new visualization type. Waterfall charts are similar to bar charts but the bars represent a delta and don't start on the x-axis.

**Links**
- [product doc](https://docs.google.com/document/d/1xjt7sMjeebB42lRsEuVBzaLaA-XuCceDe1CfeC1ymhM/edit)
- feature branch: [`0.38-waterfall-charts`](https://github.com/metabase/metabase/tree/0.38-waterfall-charts)
- Issue links: #11904

**Implementation Plan**

**ETA**: 12/1/2020

- [x] Basic visualization (PR #13812)
- [x] Chart value labels (PR #13824)
- [x] Total bar (PR #13862)
- [x] Corner cases of negative values (PR #13893)
- [x] Settings (PR #13931 #13951)
  Colors for the bars, axes/labels settings, toggle for total bar
- [x] Tooltips, default click behavior, dashboard click behavior (PR #13907)
  Hopefully this is just connecting things to LineAreaBar's code.
- [x] Unit tests (PR #13909)
- [x] Ensure the waterfall charts work with non-categorical X axis (PR #13965 #13985) 
- [x] Ensure the waterfall charts work with non-quantitative X values (PR #13997)
- [x] Design polish
  * [x] Tweak the position of value labels (PR #14000)
  * [x] Display negative value inside parentheses, `(4)` instead of `-4` (PR #14039)
  * [x] Ignore mouse hover on the invisible bars (PR #14021)
- [x] Bugfixes
  * [x] Timezone problem (PR #14038)
  * [x] Another incorrect label for total (PR #14048)
* [x] Cypress tests (PR #14065)

**Comment by mazameli** [comment]
Re: "Reorder columns," we were talking about that in the design planning meeting this morning and Sameer rightly asked that that be pulled out into its own feature so that it A) doesn't block waterfall charts and B) can be done across waterfall, bar, funnel, and dashboard scalar cards together. I'll work on pulling that out into its own product doc + design files.

**Comment by countrodrigo** [comment]
Super excited about this feature! Is the expected release date Dec 16, 2020?

**Comment by rlotun** [comment]
**Status**: updated ETA for merge is Nov 30th (as Ariya has started to help). This feature is still targeted for 38 which is planned to be released on December 16th, 2020.

**Comment by mazameli** [comment]
This is coming along nicely! Here are some items @kdoh and I found while going through this feature today:

- Ideally, the display values should be above/below the bars rather than inside them.
- I shouldn't be able to hover over or click on the hidden/invisible portion of bars. Adding something like "pointer-events: none" might work, though hovering over that invisible bar also should not trigger the fading out effect on the visualization.

![image](https://user-images.githubusercontent.com/2223916/101421060-5b28e500-38a8-11eb-8ade-5bd6f232a0ea.gif)

- A bit of an edge case, but it looks like if your total ends up as a negative value, the Total bar isn't correctly touching the x-axis:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/2223916/101421284-d4c0d300-38a8-11eb-929d-84a8b1f3078c.png">

**Comment by ariya** [comment]
> This is coming along nicely! Here are some items @kdoh and I found while going through this feature today:

Thanks! I've added them to the tasks list.

**Comment by mazameli** [comment]
@ariya, still seeing one thing to fix on waterfall charts:

- While I can no longer click on the invisible part of the bars (yay!), I can still hover over them causing the tooltip to appear (boo).

Just for my own notes, there are some polish follow-ons I and/or Kyle are going to address as well:
- Color pickers are too small and too rounded.
- Tweak the default color of the Total bar.

**Comment by countrodrigo** [comment]
🎆 🍾
