### ISSUE TITLE
Dashboard Subscriptions

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#13671]
## Introduction
Pulses are okay, but operate on a question-by-question basis. Frequently questions have already been grouped into dashboards and users would like to send notifications about the all of those questions at once. The goal of this feature is to support sending out notifications (by Slack or email) for the entire contents of a dashboard at once.d

### Do first
- [x] Apply dashboard filters to pulses - https://github.com/metabase/metabase/issues/14291 [PR up]

### Finally / follow up
These feel like they could slip to follow up point releases if we don't get to them.
- [x] Subscription titles should link back to dashboard - https://github.com/metabase/metabase/issues/14211
- [ ] Pull the toggle out of the `EmailAttachmentPicker` component

### Punted to a future release
- Change popover text - https://github.com/metabase/metabase/issues/14118) [might not make it to 38.0
- Non-admins shouldn't see the email/slack boxes if email/slack is not configured - https://github.com/metabase/metabase/pull/14331

## ETA
~~Nov 17~~ (biggest sources of delay: optimism about learning Redux; not realizing the build was as broken as it was) 
~~**PRs up:** Hopefully Nov 25 because I want to enjoy Thanksgiving~~
~~**Polishing (appearance, bugfixes):** 12/4~~
~~1/8 - almost got done but not quite after scope increased to include default filters ~~
- 1/11

---

## Links
- Product doc: [link](https://docs.google.com/document/d/1CmXQKvz30iFGRfA0HFzF9f2KI9mFKo8wzWO6YjP_2SE/edit?usp=sharing)
- Eng doc: [original issue by Sameer, with some technical notes from Cam](https://github.com/metabase/metabase-enterprise/issues/518)
- Feature branch: [`subscribe-to-dashboards-oss`](https://github.com/metabase/metabase/pull/13390)
- Issue links: https://github.com/metabase/metabase/issues/10022

### Deferred features
<details>
  <summary>View items</summary>
- [ ] set filter values for EE on email
- [ ] set filter values for EE on slack
- [ ] filter list (... and 2 more filters)
- [ ] Write a migration
</details>

### Tech debt
-  `getDashboardActions` (or, ideally, use non-deprecated refs)

## Archive

<details>
  <summary>Full stack - completed</summary>
- [x] Clicking the undo button after a delete requires a refresh for the correct state - fixed by #14283  
- [x] Add email address validation - #14257
  - [x] send test email now
  - [x] Selection of attachments
  - [x] Send all cards in dashboard at send time, not subscription creation time
  - [x] Don't show the "pulse" term in emails https://github.com/metabase/metabase/pull/14260 [PR up]
 
</details>

<details>
<summary>Appearance - completed</summary>

- [x] implement updated schedule card design
- [x] Sidebar should be the full height of the viewport, not the height of the dashboard's content, so that the Cancel and Done buttons are visible.
- [x] Fix positioning of create/close icons
</details>

<details>
  <summary>UX tweaks - completed</summary>
- [x] Don't return dashboard subscription "pulses" in API responses - https://github.com/metabase/metabase/issues/14190 / https://github.com/metabase/metabase/pull/14300
- [x] Race condition: when clicking Create, the Delete button populates before the sidebar closes ([link](https://github.com/metabase/metabase/issues/13671#issuecomment-742734820))
- [x] Persist attachment settings correctly - https://github.com/metabase/metabase/issues/14117 [[PR up](https://github.com/metabase/metabase/pull/14290)]
- [x]  The race condition [described here](https://metaboat.slack.com/archives/C505ZNNH4/p1608313584003900) - https://github.com/metabase/metabase/pull/14283 [[Draft PR up](https://github.com/metabase/metabase/pull/14283)]
- [x] Cancel button should go to the subscription list, not close sidebar https://github.com/metabase/metabase/pull/14261
- [x] Only show subscriptions option if there's at least 1 card on a dashboard https://github.com/metabase/metabase/issues/14264 / #14266
  - [x] X to the right of "create a dashboard subscription" on first pane closes sidebar
  - [x] cancel button on email (should close sidebar)
  - [x] cancel button on slack (should close sidebar)
  - [x] After clicking "Create a dashboard subscription," the popover should close
  - [x] Don't render duplicate pulses
  - [x] Move public sharing into popover menu; avoid duplicate buttons in the header; re-enable Cypress tests in `public/public.cy.spec.js`
  - [x] Fix sidebar height (cc @kdoh ) https://github.com/metabase/metabase/pull/14182
  - [x] Close the sidebar when editing the dashboard itself - https://github.com/metabase/metabase/issues/14258 / https://github.com/metabase/metabase/pull/14259
</details>

<details>
  <summary>Old implementation steps</summary>

- [x] UX tweaks
  - [Cancel button PR](https://github.com/metabase/metabase/pull/13741)
  - [Sharing/embedding PR](https://github.com/metabase/metabase/pull/13928)
- [x] Fix the build and the bugs it found ((PR)[https://github.com/metabase/metabase/pull/13859]))
- [x] Test email button ((PR)[https://github.com/metabase/metabase/pull/13886])
- [x] The Full-stack features in order. TBD how to break them up into PRs
  - [Attachment question selection PR](https://github.com/metabase/metabase/pull/13950)
- [x] Styling/design
</details>

**Comment by rlotun** [comment]
**Status**: as of the pod planning meeting today we have an updated ETA of 11/30.

**Comment by mazameli** [comment]
Here are some fresh things @kdoh and I found while going through this today:

- Bug: there seems to be a race condition where when creating a new subscription, when you click Create, the Delete button populates before the sidebar closes, which looks weird.
- If a dashboard has a least one subscription, when you start creating another subscription, if you cancel, the sidebar should go back to displaying the list of subscriptions instead of closing the sidebar.
- Clicking the Undo button in the toast notification after you've deleted a subscription does seem to successfully restore the subscription, but it seems you have to hard refresh for the subscription to show up in the list again.
- I think this is known, but there should be a different state for the Share menu when a dashboard has at least 1 subscriptions vs. when it has none.

**Comment by mazameli** [comment]
Could more things we found:

- Bug: if the sharing sidebar is open and then you click Edit to enter dashboard edit mode, the sidebar should close.
- Bug: deleted subscriptions shouldn't show up in the collections Archive.

**Comment by tsmacdonald** [comment]
Current buglist. Not going to bother breaking out separate Github issues for now.

```
| Description                                                                                                                         | type        | required for release | status          |
|-------------------------------------------------------------------------------------------------------------------------------------+-------------+----------------------+-----------------|
| non-admins shouldn't see email/slack boxes if email/slack not configured                                                            | enhancement | yes                  |                 |
| Pulses should send dashboard's card, not necessarily the pulse_cards                                                                | bugfix      | YES                  |                 |
| race condition where when creating a new subscription, when you click Create, the Delete button populates before the sidebar closes | enhancement | no                   | can't reproduce |
| cancel should go to subscription list, not close sidebar                                                                            | enhancement | no                   |                 |
| clicking undo button after delete requires a refresh for un-deleted pulse to show back up                                           | bugfix      | maybe                |                 |
| share menu should have different copy if a subscription exists                                                                      | enhancement | yes                  |                 |
| if the sidebar is open and dashboard-edit is clicked, sidebar should close                                                          | enhancement | no                   |                 |
| deleted subscriptions shouldn't show up in the collections archive                                                                  | bugfix      | yes                  |                 |

```

**Comment by tsmacdonald** [comment]
Hey @mazameli I can't reproduce

> Bug: there seems to be a race condition where when creating a new subscription, when you click Create, the Delete button populates before the sidebar closes, which looks weird.

Probably I'm doing the steps wrong, but there's a chance it got fixed during a refactor that got merged yesterday afternoon. Would you please give me more details?

**Comment by mazameli** [comment]
@tsmacdonald, if you watch this gif carefully, you can see that the "Delete this subscription" text appears directly below the attachment settings toggle, right before the sidebar closes:

![quick-blip](https://user-images.githubusercontent.com/2223916/101818261-77ab6400-3ad8-11eb-87dd-745e96fcb574.gif)

**Comment by mazameli** [comment]
Here are some of the more obvious design/ux problems remaining from my perspective.

## Sidebar height

The sidebars should be the full height of the viewport. If the sidebar is open and the dashboard's contents need to scroll, then the dashboard should scroll independently of the sidebar and independently of the navbar and dashboard title bar. I see that this seems to be crossed off in the to-dos in the issue description ("Sidebar should be the full height of the viewport, not the height of the dashboard's content, so that the Cancel and Done buttons are visible."), but it does not appear correct to me.

The sidebar's height should extend to the bottom of my viewport here:

<img width="1569" alt="image" src="https://user-images.githubusercontent.com/2223916/101819630-61060c80-3ada-11eb-92dd-4b93891db596.png">

I should be able to see Cancel and Done here in the sidebar without having to scroll: 

<img width="1600" alt="image" src="https://user-images.githubusercontent.com/2223916/101819705-7b3fea80-3ada-11eb-8a91-ab047d51faa1.png">

## Popover menu state

When a dashboard has at least one subscription, there's supposed to be a different state for the sharing popover menu:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/2223916/101820190-1c2ea580-3adb-11eb-9ae2-41fc203f112e.png">

Right now, because that's not implemented, in order to see your existing subscriptions, you confusingly have to click the option that says "Create a dashboard subscription."

![create-popover](https://user-images.githubusercontent.com/2223916/101820069-ee496100-3ada-11eb-97dc-faababf545fd.gif)

**Comment by mazameli** [comment]
Just saw this — subscription emails shouldn't have the word "Pulse:" in the subject line:

<img width="387" alt="image" src="https://user-images.githubusercontent.com/2223916/102259108-8c666e00-3ec3-11eb-891f-4f1f915b52fd.png">

**Comment by mazameli** [comment]
With emails, a nicety would be if the title in the email content, i.e. the dashboard's name, was a hyperlink that would take you to that dashboard. In fact, I'm even thinking that all of the _questions_ should link to the dashboard, rather than the question detail view.

**Comment by mazameli** [comment]
We should change this to "email sent" here. I can do that.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/2223916/102292409-f26de800-3ef9-11eb-9af1-c16c7a5376dc.png">

**Comment by kdoh** [comment]
@tsmacdonald All done here?

**Comment by tsmacdonald** [comment]
Yep! Shall we close it?

**Comment by mazameli** [comment]
Closing this as I've opened an issue for the last unchecked item in the description: https://github.com/metabase/metabase/issues/14575
