### ISSUE TITLE
Quarantine and investigate flaky tests

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#13682]
To keep CI green, let's quarantine the following, and then in parallel, investigate each and every one of them:

#### Whole spec quarantined
- [ ] frontend/test/metabase/scenarios/public/public.cy.spec.js
- [ ] frontend/test/metabase/scenarios/admin/datamodel/editor.cy.spec.js
    - CY dashboard stats for [`editor on master, last 30 days`](https://dashboard.cypress.io/projects/a394u1/analytics/top-failures?branches=%5B%7B%22label%22%3A%22master%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22master%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%7B%22label%22%3A%22frontend%2Ftest%2Fmetabase%2Fscenarios%2Fadmin%2Fdatamodel%2Feditor.cy.spec.js%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22dbdafa0e-bdef-4136-3470-4af5a5f17b9a%22%7D%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222020-10-08%22%2C%22endDate%22%3A%222020-11-07%22%7D&viewBy=TEST_CASE)
    - CY dashboard stats for [`editor on all branches, last 30 days`](https://dashboard.cypress.io/projects/a394u1/analytics/top-failures?branches=%5B%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%7B%22label%22%3A%22frontend%2Ftest%2Fmetabase%2Fscenarios%2Fadmin%2Fdatamodel%2Feditor.cy.spec.js%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22dbdafa0e-bdef-4136-3470-4af5a5f17b9a%22%7D%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222020-10-08%22%2C%22endDate%22%3A%222020-11-07%22%7D&viewBy=TEST_CASE)
    - stress-testing [did not reveal any flakes](https://github.com/nemanjaglumac/metabase-tests/actions/runs/353985984)
- [ ] `frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js` (2020-11-25)

#### Narrowed down to a specific failing test
- [x] frontend/test/metabase/scenarios/visualizations/drillthroughs/chart_drill.cy.spec.js (39e6e6ec48dc1c5e3e793cb15d6be346045a1a05)

#### WIP
- [x] frontend/test/metabase/scenarios/visualizations/drillthroughs/dash_drill.cy.spec.js (5d071daafd6deb6d8f572c0d6aa0edcf2a29780a) - waiting for a review in #13852

#### Unquarantined
- [x] frontend/test/metabase/scenarios/pulse/pulse.cy.spec.js (b88056a12a0e5778dff68d0303116be60d3a3f9e)

#### Fixed
- [x] frontend/test/metabase/scenarios/admin/settings/settings.cy.spec.js (c97869d08ea1033bbe4f59ae541a8d40e7813ed2)
- [x] frontend/test/metabase/scenarios/dashboard/dashboard.cy.spec.js (35f89e04f40d6a987eb55c70860f94345676a334)
- [x] frontend/test/metabase/scenarios/admin/datamodel/metrics.cy.spec.js (94381351c99c66fbde31f2e84f79900c9c45c81e)
- [x] frontend/test/metabase/scenarios/admin/datamodel/segments.cy.spec.js (927c40840fefd126deb2a82a3b4e24c104117723)
- [x] frontend/test/metabase/scenarios/question/nested.cy.spec.js (#13733)
    - no reported failures in CY Dashboard for any branch in the last 30 days
    - stress test x20 [20/20 passed ✅](https://github.com/nemanjaglumac/metabase-tests/actions/runs/353809928)
- [x] enterprise/frontend/test/metabase-enterprise/custom_drill_through/drill_through.cy.spec.js (#13734)
    - no reported failures in CY Dashboard for any branch in the last 30 days (see [comment](https://github.com/metabase/metabase/issues/13682#issuecomment-723454999))

**Comment by nemanjaglumac** [comment]
Let's keep an eye on `frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js`. It started appearing recently. Here's the latest occurrence: https://app.circleci.com/pipelines/github/metabase/metabase/10127/workflows/fb3054ae-52ba-44e7-943c-f37ce385e8ab/jobs/358479

**Comment by ariya** [comment]
Found [another problem](https://app.circleci.com/pipelines/github/metabase/metabase/10169/workflows/b16fceab-016b-4688-b11e-0bfe1331fbe7/jobs/359878) at `frontend/test/metabase/scenarios/dashboard/parameters.cy.spec.js:

```
scenarios > dashboard > parameters should allow linked question to be changed without breaking (metabase#9299) - should allow linked question to be changed without breaking (metabase#9299)
CypressError: Timed out retrying: Unable to find an element with the text: Orders in a dashboard. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
    at Object.cypressErr (http://localhost:4000/__cypress/runner/cypress_runner.js:86206:11)
    at Object.throwErr (http://localhost:4000/__cypress/runner/cypress_runner.js:86161:18)
    at Object.throwErrByPath (http://localhost:4000/__cypress/runner/cypress_runner.js:86193:17)
    at retry (http://localhost:4000/__cypress/runner/cypress_runner.js:76849:16)
    at onFailFn (http://localhost:4000/__cypress/runner/cypress_runner.js:65634:16)
    at tryCatcher (http://localhost:4000/__cypress/runner/cypress_runner.js:120669:23)
    at Promise._settlePromiseFromHandler (http://localhost:4000/__cypress/runner/cypress_runner.js:118605:31)
    at Promise._settlePromise (http://localhost:4000/__cypress/runner/cypress_runner.js:118662:18)
    at Promise._settlePromise0 (http://localhost:4000/__cypress/runner/cypress_runner.js:118707:10)
    at Promise._settlePromises (http://localhost:4000/__cypress/runner/cypress_runner.js:118782:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:4000/__cypress/runner/cypress_runner.js:115394:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4000/__cypress/runner/cypress_runner.js:115404:10)
    at Async.drainQueues (http://localhost:4000/__cypress/runner/cypress_runner.js:115278:14)
```

**Comment by nemanjaglumac** [comment]
I am looking at it right now. Here's the [video](https://dashboard.cypress.io/projects/a394u1/runs/2706/failures/00fca783-7672-439e-987f-19ae1c29bc70/video) . Another Cypress typing issue.

**Comment by nemanjaglumac** [comment]
There are no stats for `enterprise/frontend/test/metabase-enterprise/custom_drill_through/drill_through.cy.spec.js` neither for `master` or any other branch. We are still not running EE tests in CI, I think.

**Comment by dacort** [comment]
> We are still not running EE tests in CI, I think.

Correct, I was thinking of making a PR next week to enable EE tests.

**Comment by nemanjaglumac** [comment]
`field.cy.spec.js` failed in [this](https://app.circleci.com/pipelines/github/metabase/metabase/10205/workflows/23418ea8-483f-440d-92ed-2ae9a1e1d90f/jobs/361700/tests) run. I'll subject it to stress-testing but it's probably going to be quarantined.

**Comment by nemanjaglumac** [comment]
> > Let's keep an eye on `frontend/test/metabase/scenarios/admin/datamodel/field.cy.spec.js`. It started appearing recently. Here's the latest occurrence: https://app.circleci.com/pipelines/github/metabase/metabase/10127/workflows/fb3054ae-52ba-44e7-943c-f37ce385e8ab/jobs/358479
> 
> `field.cy.spec.js` failed in [this](https://app.circleci.com/pipelines/github/metabase/metabase/10205/workflows/23418ea8-483f-440d-92ed-2ae9a1e1d90f/jobs/361700/tests) run. I'll subject it to stress-testing but it's probably going to be quarantined.
> 
> Hm, interesting. [20x stress-test](https://github.com/nemanjaglumac/metabase-tests/actions/runs/353714671) didn't reveal any flakes. I don't know what to make of this.

I subjected this file to another 20x stress-test and again - it didn't reveal any flakes. [20/20 passed](https://github.com/nemanjaglumac/metabase-tests/actions/runs/374460121).

However, it failed [8 times](https://dashboard.cypress.io/projects/a394u1/analytics/top-failures?branches=%5B%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%7B%22label%22%3A%22frontend%2Ftest%2Fmetabase%2Fscenarios%2Fadmin%2Fdatamodel%2Ffield.cy.spec.js%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%2246476094-8f5b-52a8-057b-c6b01376c569%22%7D%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222020-10-21%22%2C%22endDate%22%3A%222020-11-20%22%7D&viewBy=TEST_CASE) in CircleCI in the last 30 days. 😳

**Comment by nemanjaglumac** [comment]
Definitely putting `field` into quarantine. It's too unstable.
Just failed for me even locally. Not sure how or why it's reliably passing in GitHub CI.

**Comment by ariya** [comment]
Let's close this for once. Thanks to the heroic effort from @nemanjaglumac, we're already in a much better state!
