### ISSUE TITLE
Sandboxing and Nested Queries Revamp

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#13702]
Fix feature disparity and classes of issues around data sandboxing and nested queries with the end goal of getting data sandboxes to feature parity with tables and fixing a list of known bugs.

**Links**
- product doc: https://docs.google.com/document/d/1hhYSAxWMW97kNwXzzrKh-Gp6ceTx8aBCaAjKPffclZ8/edit
- eng doc: https://docs.google.com/document/d/1Cds5LRI5HT7fccUtPr1aqIpNLrQgk8ugu3oCWmJKwIk/edit#heading=h.aiy793d9xxqb
- feature branch: [sandboxing-and-nested-questions-revamp-13702](https://github.com/metabase/metabase/tree/sandboxing-and-nested-questions-revamp-13702)
#### Filters
- [ ] #12839: Filtering Custom Expression from aggregated result fails with column not found (`.Reproduced`)

#### Nested
- [ ] #12507: Nested queries using metric got wrong SQL (`.Reproduced`)
- [ ] #13186: Not all columns of nested question available for Dashboard filter (`.Reproduced`)
- [ ] #13764: Cannot select granularity of aggregated fields in nested question (`.Reproduced`)

#### Notebook
- [ ] #13649: Query builder - join saved questions-custom column not found (`.Reproduced`)
- [ ] #12928: Cannot join Saved Questions that themselves contains joins (`.Reproduced`)

#### Sandboxes
- [x] https://github.com/metabase/metabase-enterprise/issues/548 (`.Reproduced`)

#### Features
- [ ] #8272: Add query builder support for nested query FK groupings
- [ ] #8856: Nested queries using metrics need to include all columns used in metric filters
- [ ] #5595: Pass through FK and PK type information from nested SQL subqueries 
- [ ] #5594 (partially): We should scan the results of a saved question and pull out information like FieldValues, etc

*_Note: I have not verified enough each of these to be certain the changes outlined here will fix it, but they are all adjacent and at the very least after we're done with the work here we should have a good understanding of any additional fixes needed._

---

#### Obsolete/Limitation
- ~https://github.com/metabase/metabase-enterprise/issues/524~
    - This issue was closed and the PR deleted because it's not possible to use tables with more columns than the sandboxed table as the base for sandboxing. New an updated issue that tracks this is #14612

#### In progress?
- [ ] #12985: Dashboard filter dropdown/search not shown for nested questions (Saved Questions and aggregated) (`.Reproduced`)
    - Reproduction v1: fixed
    - Reproduction v2: 

#### Fixed (confirmed, Cypress was unskipped and is passing):
- [x] #10511: Nested queries with duplicate column names fail (`.Reproduced`)
- [x] #12649: Table joins and Custom Column returns same results for columns with the same name (`.Reproduced`)
- [x] #12762: Custom Column after aggregation creates wrong query and fails (`.Reproduced`)
- [x] ~#12872: Between Dates filter behaves inconsistently based on whether the column is from a joined table or not (`.Reproduced`)~ Fixed by #13991
- [x] https://github.com/metabase/metabase-enterprise/issues/154 (`.Reproduced`) 
- [x] #10474: Cannot use Saved Question, when original question uses "Display values"="Use foreign key" (`.Reproduced`)
- [x] #13641: Drill-through not working on implicit joined tables with sandboxes (`.Reproduced`) (being worked on in #14717)
    - ~being worked on~ fixed in #14719
- [x] #13642: Drill-through not working on questions with joins, where target table is sandboxed, and target fields cannot be filtered (`.Reproduced`)
    - ~being worked on~ fixed in #14717
- [x] https://github.com/metabase/metabase-enterprise/issues/520 (`.Reproduced`)
    - [x] Advanced sandboxing using QB saved questions (fixed in #14695)
    - [x] "normal" SQL version of the test
    - [x] "workaround" SQL version of the test
- [x] #14724: Cannot use Saved Questions that contains joins as base in new questions (`.Reproduced`)
    - originally fixed in #14719 
    - [reopened](https://github.com/metabase/metabase/issues/14724#issuecomment-776769686) because we found 2 edge cases
        - single-level nesting doesn't work with remapped values (being worked on in #14745)
        - multi-level nesting doesn't work at all (being worked on in... TBD)
- [x] #14612: Advanced Sandboxing using questions that return more/other columns than the sandboxed table is not possible anymore, but the errors are not helpful (`.Reproduced`)
    - partially? fixed in #14673
- [x] #11439: Cannot choose grouping of dates on Summarize with Simple question from nested (`.Reproduced`)
    - fixed in https://github.com/metabase/metabase/pull/14695

---
**Implementation Plan**

**ETA**: ~~11/30/2020~~ 12/3/2020

- [x] Use `field-id` where possible and flow metadata better [11/30] #13712
  * [x] switch to `field-id` where possible
  * [x] add middleware to update old style MBQL to new
  * [x] go through the list of bugs in #13702 and add them as tests (where applicable. ie. where the hypothesis is that this work should fix it) 
  * [x] pass along more metadata about source query
  * [x] tidy up MBQL->native compiler
  * [ ] cleanup tests
- [ ] Refactor query processing pipeline such that we factor out the MBQL compilation part [12/1] #13713
   * [x] pull MBQL middleware into new namespace
   * [x] split toplevel API into an MBQL preprocessing function and a transducer 
   * [ ] refactor tests to take advantage 
   * [ ] refactor places where we now manually apply MBQL middleware to take advantage
- [ ] Recursively process source queries [12/1] #13714
    * [x] basic version
    * [ ] make it work with MBQL middleware that adds postprocessing 
- [ ] Enforce (and take advantage of) the constraint that sandboxes can only remove fields, and that col aliases must match original field names. [12/2] #13715
  * [x] validate the shape of sandboxing query
  * [ ] take advantage of tighter constraints 
  * [ ] communicate the error to the user 
- [x] Peek at metadata for native SQL sandboxing queries by running them as a test user [12/3] #13716

**Needs to happen**

- [ ] Enforcing sandboxing constraints will need a UI component (and the accompanying translations).

**Comment by sbelak** [comment]
I think the natural split for this work is that one person does 1-3 & the other 4-5

**Comment by camsaul** [comment]
Are there any PRs for this ready to review?

**Comment by rlotun** [comment]
**Status**: As of the pod planning meeting today we're going to assume worst-case single person sequenced work and have an updated ETA of 11/30/2020.

**Comment by alekseyp** [comment]
Is there a new ETA?

**Comment by rlotun** [comment]
This project has been delayed and faced a number of bumps along the way. It will be partially delivered (a batch of 5 bugs fixed) as part of the 38 release, tentatively scheduled for the week of Jan 25th. Apologies for the delay.

**Comment by nemanjaglumac** [comment]
If it helps to prioritize or to tackle issues in a batch, here are 2 variations of grouping them:

### By component (test file name):
| Filter      | Nested | Notebook| New     | Sandboxes |
|---------|---------|---------|---------|------------|
| #12839 | #12507 |  #13649 |  #11439 |   https://github.com/metabase/metabase-enterprise/issues/520              |
| #12985 | #13764 | #12928  |                |  https://github.com/metabase/metabase-enterprise/issues/154  |
|               | #13186 |                |                |  https://github.com/metabase/metabase-enterprise/issues/548 |
|               | #12507 |                |                |  ~https://github.com/metabase/metabase-enterprise/issues/524~* |

> * Please note that EE524 is not possible to reproduce anymore due to the changes implemented/introduced with this overhaul. "It is now a limitation" cc @flamber 

### By the similarity of error message (indicating that one fix could potentially solve multiple issues)
| `Column "source.FOO" not found;` | Missing granularity options | Missing dropdown options |
|----------------------------------|-----------------------------|--------------------------|
| #12839                           | #13764                      | #13186                   |
| #12507                           | #11439                      | #12985                   |
| #13649                           |                             |                          |
| https://github.com/metabase/metabase-enterprise/issues/548 | | | |

**Comment by rlotun** [comment]
Moved remaining work to: https://github.com/metabase/metabase/issues/15575
