### ISSUE TITLE
We should run all (Cypress) tests in complete isolation

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#13989]
**Describe the bug**
We're currently resetting our data set once for all tests within a `describe()` group. That leads to pollution and undesirable (sometimes even unpredictable) scenarios.

That is presented in great detail in https://github.com/metabase/metabase/pull/13973.

**Expected behavior**
Each test should start in complete isolation.
We should move `restore()` into `beforeEach()` and update any test that is relying on external data/other tests.

**Severity**
This leads to unmaintainable tests and failed CI runs (especially since we introduced test retries - again, see: https://github.com/metabase/metabase/pull/13973).

### Related PRs
- [x] Refactor `collections.cy.spec.js` directly on `master` (#14383)
- [x] EE tests on `release` branch (#14372)
- [x] EE tests immediately merged into `master` (#14377)
- [x] OSS tests on `release` branch (#14372)
- [ ] OSS tests immediately merged into `master` (#14394)
