### ISSUE TITLE
Split Field special_type into effective type/coercion strategy/semantic type/relation type

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14054]
### Milestone 1
- [x] merge release-x.38.x so following changes will be comprehensive: [merge release-x.38.x](https://github.com/metabase/metabase/pull/14792)
- [x] rename special_type -> semantic_type. no changes to how things work as this gets rather nasty. its about 150 files changed here [part 1](https://github.com/metabase/metabase/pull/14780)
- [x] add effective type and copy over base type and case the unixtimestamps and isodatetimes into effective type. add coercion strategies: [Issue #14818](https://github.com/metabase/metabase/issues/14818) [PR #15022](https://github.com/metabase/metabase/pull/15022)
- [x] update UI so these are editable in the admin schema page [same PR #15022](https://github.com/metabase/metabase/pull/15022)
- [x] update UI to understand these new changes [PR 15213](https://github.com/metabase/metabase/pull/15213)
- [x] bugfixes in migration: [PR #15218](https://github.com/metabase/metabase/pull/15218) 
### Milestone 2
- [ ] add relation_type and migrate type/FK and type/PK over to this. this gets into a lot of front end stuff.
- [ ] change almost all usages of base_type to effective_type. Only the query processors really need to know about when these don't match and everything else just uses the effective_type, ie, the type that will come out of the qp.

Right now we record 3 type related columns for a Field:

*  `database type` - native type name in the DB, e.g. `INTEGER`. Not user editable. Never null.
*  `base type` - Metabase type mapping of `database_type`, e.g. `type/Integer`. Not user editable. Never null.
* `special type` - semantic information, such as whether this is a PK, FK, or "CreatedAtTimestamp"; coercion information, such as `type/UnixTimestampSeconds`, which indicates that this is a Unix timestamp column and we should coerce it appropriately and treat it as `:type/Temporal` field of some sort. Stuff like `PK` or `FK` is inferred automatically, but other options are user-settable.

There are two things I think we should do here:

### 2)  Split `special_type` into four new columns:

`special_type` is used for many different purposes that aren't mutually exclusive. It's totally possible to have a Unix timestamp that is a PK that serves as a "CreatedAtTimestamp". We can't store three pieces of info in one slot.

* `effective type`: The Metabase type we should treat and display this column as, which may or may not be the same as the `actual type`. For something like a Unix timestamp, this would probably be `:type/DateTimeWithLocalTZ`, This should be user-settable, but should be restricted to types for which we have an appropriate `coercion strategy` that could convert from out `actual type` to this type. e.g. no setting `effective type` to `type/Date` for a `type/Boolean` column. This should never be null

*  `coercion strategy`: strategy to coerce the column from its actual type (e.g. `type/Integer`) to the `effective type` -- for a Unix timestamp, this would be either `UnixTimestampSeconds` or `UnixTimestampMilliseconds`.  This would be user-settable in combination with setting `effective type`. If there is no coercion needed, this should be `NULL`
   * We should also let people define their own coercion strategies -- perhaps as a native query snippets e.g. 
      ```
      CONVERT(date, FORMAT({{field}}, '####-##-##') , 102)
      ``` 
      to support `20190109` _Integer_ dates (this is a real-world example). 
      * Maybe we'd want to store these in a separate `coercion_strategy` Table so you can reuse them between Fields. 

`semantic type`: The semantic purpose of this column, e.g. `CreatedAtTimestamp` or `AvatarURL` or `PostalCode`. User-settable. Nullable.

* `relation type`: Whether this column is a PK or FK, if applicable. This is a separate dimension from `effective type` and `semantic type`. I think this would be set automatically 99% of the time during sync, but we can go in and let people set FK relationships for columns that we didn't pick up during sync (e.g. if they don't have an actual FK constraint in the DB, but are still effectively FK columns). Nullable.

### 3) Use `effective type` everywhere for stuff like deciding which UI to show or doing stuff on the backend.

We'd only need to use `actual type` in a handful of places e.g. when generating native queries to generate the appropriate coercion stuff. Almost everywhere else should pretend it doesn't exist.

Right now to determine if something should be treated as a temporal column we have to check both `base_type` *and* `special_type` (in case it's something like `:type/UnixTimestampSeconds`. This is hairy and error-prone.

### 4) Move coercion strategies and semantic types to their own type hierarchy

`:type/UnixTimestampSeconds` should become `:strategy/UnixTimestampSeconds` or something like that. `:type/AvatarURL` should become `:semantic/AvatarURL` or something like that. `:type/` should be only for actual and effective types e.g. `:type/Integer` or `:type/DateTimeWithTZ`

**Comment by camsaul** [comment]
I don't really think this would be that hard to implement -- we can split the column up with a handful of migrations that would copy values over into the new columns where appropriate. Then all we'd need to do is rework code to use the new columns -- we could grep for `special_type` and rework anything that refers to it.

**Comment by dpsutton** [comment]
I'm very in favor of this proposal. I think we should keep a changelog of these values in mind when this feature gets built. It can be built either at the same time, or just contemplated in the design of this.

The reason a changelog would be helpful is to make the analysis phase of sync more robust. We almost never want to override a user's choice of a column type. Having a change log of the way these values change can help us in the analysis phase to determine the following:
- the current settings were set by the analysis phase, but the current analysis has a better way to classify the data due to more values, better analysis tools, more fingerprinters, etc. and it can safely mark the field with new types
- the user manually set the column types and we shouldn't override it
- the user manually set a column type but we recognize it as a workaround and have a better way now

Keeping a history of these values would be helpful in this kind of conflict resolution. It could also help in serving as a way to keep track of _why_ these things are inferred. In the history values we could keep track of the reason something was marked as such. Eg, The column was marked as a datetime column because all of the integers in the column when viewed as unix timestamps were around "now"; this column was marked as a category because it has 500 items, etc.

**Comment by camsaul** [comment]
Would let us implement things like #1324

**Comment by sbelak** [comment]
Big +1 from my side as well. I'd only suggest replacing `relation_type` with a more generic `traits` (a vector of keywords) in which we could also explicitly encode some of the things we currently infer and/or have scattered around such as whether the field has autocomplete, and things where we're somewhat abusing ~~`special_type`~~ nee `semantic_type`, like `:type/Category`.

I've wrote some more on this ages ago, but not as comprehensive as this proposal:
https://docs.google.com/document/d/13bw7XzHreHCVNeWMMpQHUQc75gzxCxjVmULJjHwiwLI/edit#

**Comment by rlotun** [comment]
remaining work is in https://github.com/metabase/metabase/issues/15486
