### ISSUE TITLE
Improve Custom Expression Experience

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#14214]
Revamp the internals (parser, compiler, etc) of custom expressions, used among others in custom column, filter, aggregation.

This finally allows us to address some deficiencies in the query builder/notebook experience, such as:

* #13175: Can't do arithmetic in filter expressions, countif, sumif, or case conditions
* #12268: Filter "Custom Expression" could provide more guidance and helpful errors
* #12375: `case` not offered as suggestion for custom fields & expressions
* #12225: New filter expressions does not support `null`
* #14880: Negative filter can not be converted to custom expression

### Links

* feature branch: [0.39-improve-custom-expression](https://github.com/metabase/metabase/commits/0.39-improve-custom-expression)

### Implementation Plan

**Status**: Merged to master on March 3, 2021.

* [x] Decouple syntax analysis and semantics analysis
  * [x] Formalize syntax tree visitor (PR #14219)
  * [x] Add a barebone type checker (PR #14226)
  * [x] Dynamically infer segments vs dimensions (PR #14232)
  * [x] Dynamically infer metrics in aggregation (PR #14234)
  * [x] Delegate the resolving of metrics/dimensions/segments (PR #14427)
  * [x] Rename dimensionExpression to identifierExpression (PR #14656)
* [x] Enhance the internals (parser, compiler, etc)
  * [x] Modify the grammar to account for proper Boolean expressions (PR #14235, PR #14295)
  * [x] New functions: `ISNULL` and `ISEMPTY` (PR #14866)
  * [x] Convert negative filters (PR #14938)
* [x] Trim the syntax tree to have a compact version (PR #14579)
  * [x] Switch the type checker to use the compact tree, constrains the type for function/case (PR #14693)
  * [x] Constrain the type of boolean nodes/sub-expressions (PR #15159)
* [x] Improve suggestion and feedback to the user
  * [x] Check for the correct number of function arguments (PR #14310, PR #14325, PR #14342)
  * [x] Give feedback on CASE arguments (PR #15179)
  * [x] Suggest CASE when editing a custom column (PR #14721)

### [Functional Specifications](#spec)

(_ICE_ is a shorthand for Improved Custom Expression)

<details><summary>ICE-01 Support arithmetic operations inside a filter (or any logical operations)</summary>
<p>
  
Previous report: issue #13175 (Can't do arithmetic in filter expressions, countif, sumif, or case conditions)

**Step to verify**:

1. Ask a question, Custom question.
2. Pick Sample Dataset, Orders table
3. Summarize, Pick the metric you want to see, Custom Expression
4. Type `COUNTIF([Total]-[Tax]>42)` for the expression input

**Before**: An error is displayed: "Expected closing parenthesis but found  '-'"

![image](https://user-images.githubusercontent.com/7288/103432277-6a424080-4b91-11eb-8086-fb7f9e60fd6c.png)

**After**: The expression is treated as a valid aggregation.

![image](https://user-images.githubusercontent.com/7288/103432275-5d255180-4b91-11eb-85e8-e9e587500b3e.png)

</p></details>

<details><summary>ICE-02 Give feedback upon an incorrect amount of function arguments</summary>
<p>

Related report: issue #12268 (Filter "Custom Expression" could provide more guidance and helpful errors)

**Step to verify**:
1. Ask a question, Custom question.
2. Pick Sample Dataset, Products table
3. Filter, Add filters to narrow your answer
4. Custom Expression
5. Type `contains([Category])` for the expression input

**Before**:

(There's *not* any feedback at all, and yet it's not possible to click on the _Done_ button)

![image](https://user-images.githubusercontent.com/7288/103951284-3916c280-50f3-11eb-8a68-7a1176ae371b.png)

**After**:

![image](https://user-images.githubusercontent.com/7288/103951473-96ab0f00-50f3-11eb-99b2-1a7145f195c8.png)

**Note**: It works with a CASE expression as well:

![image](https://user-images.githubusercontent.com/7288/107835294-d21da680-6d4d-11eb-9c03-581b9cea53fe.png)

</p></details>

<details><summary>ICE-03 Suggest CASE when editing an expression</summary>
<p>

Previous report: issue #12375 (case not offered as suggestion for custom fields & expressions)

**Step to verify**:
1. Ask a question, Custom question
2. Sample Databaset, Products table
3. Custom column

**Before**:

`case` isn't in the popup list of suggestions.

![image](https://user-images.githubusercontent.com/7288/107394472-c6fa1a80-6ab0-11eb-99a3-b58e9e0b51d0.png)

**After**:

`case` **is** in the popup list of suggestions.

![image](https://user-images.githubusercontent.com/7288/107394488-cceffb80-6ab0-11eb-97e9-54d4676c5ec9.png)

</p></details>

<details><summary>ICE-04 Use ISEMPTY to check for empty (string)</summary>
<p>

Previous report: #12225 (New filter expressions does not support `null`)

**Step to verify**:

1. Ask a question, Custom question
2. Sample Dataset, Reviews table
3. Filter, Add filters to narrow your answer, Custom Expression
4. Type `NOT isempty([Reviewer])`, click Done
5. Visualize
6. Click on the "NOT isempty(Reviewer)" filter
7. Change to `isempty(Reviewer)`, click Done
8. Clik on the "Reviewer is empty" filter
9. It should show the simple filter popover

**Before**:
Not possible, since `ISEMPTY` function did not exist.

**After**:

![image](https://user-images.githubusercontent.com/7288/108615391-793ab780-73b8-11eb-9598-b588d2c0a11e.png)

![image](https://user-images.githubusercontent.com/7288/108615413-ae470a00-73b8-11eb-948b-bcf6b6a8e749.png)

![image](https://user-images.githubusercontent.com/7288/108615420-bc952600-73b8-11eb-8806-a8c7f2020d23.png)

</p></details>

<details><summary>ICE-05 Use ISNULL to check for null</summary>
<p>

Previous report: #12225 (New filter expressions does not support `null`)

**Step to verify**:

1. Ask a question, Custom question
2. Sample Dataset, Orders table
3. Filter, Add filters to narrow your answer, Custom Expression
4. Type `NOT isnull([Discount])`, click Done
5. Visualize
6. Click on the filter
7. Change to `isnull(Discount)`, click Done
8. Clik on the "Discount is empty" filter
9. It should show the simple filter popover

**Before**:
Not possible, since `ISNULL` function did not exist.

**After**:

![image](https://user-images.githubusercontent.com/7288/108949578-84405280-7619-11eb-8ad3-f67e73bb025c.png)

</p></details>

<details><summary>ICE-06 Convert a negative filter into its custom expression form</summary>
<p>

Previous report: #14880 (Negative filter can not be converted to custom expression)

**Step to verify**:

1. Ask a question, Simple question
2. Sample Dataset, Products
3. Filter, Filter by Title
4. Choose "Does not contain", type `Wallet`, press _Add Filter_
5. Click on the new filter "Title does not contain Wallet"
6. Press the left chevron icon, choose _Custom Expression_

**Actual**

Nothing happens, but the JavaScript console shows an error:

```
Unknown MBQL clause ["does-not-contain",["field-id",12],"Wallet",{"case-sensitive":false}]
```

![image](https://user-images.githubusercontent.com/7288/108426336-8016ce00-71f0-11eb-8245-d22030d45e53.png)

**Expected**

![image](https://user-images.githubusercontent.com/7288/108787112-e91c7f80-7529-11eb-9151-6c0c7439010f.png)

**Note**: Another negative filter, such as "Is not empty" should also work the same way.

</p></details>
