### ISSUE TITLE
Search Improvements

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#14548]
Search 0.39 feature milestones

###  ✔️ Add type ahead to help with UX and  feedback about what’s available.
<details>
   <summary>Show completed</summary>

- [x] [Initial cut of type ahead search](https://github.com/metabase/metabase/pull/14229)
- [x] Fuzzy search (issue #14337)
- [x] Fix no results case.
- [x] Fix loading state
- [x] Show human-friendly database name in search results · Issue #14553 [[Open PR](https://github.com/metabase/metabase/pull/14730)]
- [x] Prevent long names from scrolling the type ahead popover horizontally.
- [x] Improve basic usability of type ahead search.
</details>

### ✔️ Add contextual info about items to help influence ordering
<details>
<summary>Show completed</summary>

- Whether the item is pinned (collection_position)
- If a question matches the term, is the question is used in many dashboards
- If the item that matches the term was made or updated in the last 3 months
- [x] Search for tables by display_name - (issue #10665)
- [x] Return results if they match in other fields, like the item’s description or the query itself for questions (useful for SQL). 
#4227, parts of #7019 - we’re explicitly not trying to solve every use case mentioned in #7019 however. [[Open PR](https://github.com/metabase/metabase/pull/14583)]
- [x] First pass at blended score 
- [x] Add more criteria to the scoring (occurrence in dashboards, recency, whether it's pinned)
- [x] Include the collection something is saved in on the item (match results page)
</details>

### 🔖  Tweak the weights for our first set of additional context influences. (We're here currently)
If I do 5 searches are the top 5 results for 4 out of 5 of my terms understandable?

- [x] https://github.com/metabase/metabase/pull/15009
- [x] Treat all pinned items the same [PR](https://github.com/metabase/metabase/pull/15121/)
- [x] search dashboard descriptions
- [x] Adjust SQL query so that n-gram matches don't get dropped on the floor [PR](https://github.com/metabase/metabase/pull/15214)
- [x] Don't penalize non-questions for having a null dashboard-count score
- [x] Don't penalize un-pinnable items for having a null pinned score
- [x] Don't give full text-score credit to results that are a superset of the query (when searching for "rasta the toucan", the result "Toucan stats for Rasta the toucan and Crowberto the crow" should have a high but imperfect score. Currently it's 1.0)

### 🔧 We’ve tested the performance on an application db with a large number of items 
- [x] Results should come back in less than 3-5s max on an instance with 200,000 questions.
- [x] Obviously you shouldn’t be able to break the instance with any search terms

c.f. the perf testing doc

### Nice to haves
- Add keyboard navigation for type ahead result items
- Add a link to the full search results page

**Comment by camsaul** [comment]
@tsmacdonald can this be closed? Looks like everything is finished

**Comment by tsmacdonald** [comment]
@camsaul added the pending items that @kdoh and I had talked about but not transferred over
