### ISSUE TITLE
Foundation for Documenting Internal FE Components

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#14806]
We have [/_internal](stats.metabase.com), which is meant to be a way to document internal FE components to help improve and accelerate frontend development velocity. It is only partially completed. The scope of this issue is to move to a third party framework (such as storybook) and move the existing component documentation over. We will follow up with fleshing it out over time.

**Implementation Plan**

***ETA***: 03/07/2021 (basically when 39 lands)

***Milestone 1: Choose framework***
- [x] Spend an afternoon researching frameworks (e.g. [Storybook](https://storybook.js.org/), [Styleguidist](https://react-styleguidist.js.org/), [bit.dev](https://bit.dev/))
- [x] Write a 1-2 pager comparing and contrasting 3 of these (with pros / cons). Circulate for feedback for a few days for feedback from @daltojohnso @ariya @kdoh @paulrosenzweig 
- [ ] @kdoh decides what we use

***Milestone 2: Migrate existing components***
- [ ] Migrate each existing component over (you might want to break this down to a few phases?)

***Milestone 3: Flesh out documentation for some undocumented components***
- [ ] Choose a few that we want to push forward on <tbd>

**How to Test This Feature Out**

Should be able to go to /_internal and have useful documentation of internal components that gets referenced often in the course of developing on the frontend.

**Comment by rlotun** [comment]
superseded by https://github.com/metabase/metabase/issues/18410
