### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#14801]
To improve frontend development velocity we need to upgrade to React 16 (and fast follow with React 17, which shouldn't be much work)

**Implementation Plan**

***ETA***: 03/07/2021 (roughly when we launch 39)
***Project branch***: [`upgrade-react`](https://github.com/metabase/metabase/tree/upgrade-react)
**Status**: Merged to master as of 03/01/2021 (PR #14391)

- [x] move popovers to portals
- [x] move tooltips to portals
- [x] move modals to portals
- [x] replace usage of synchronous `ReactDOM.render` in custom expression inputs
- [x] migrate lifecycle functions
- [x] merge to master
- [x] add eslint-plugin-react-hooks

Future follow-up will be tracked in #15306.

**How to Test This Feature Out**

As this is an upgrade and migration things should Just Work. Pay special attention to stats.metabase.com to make sure things behave correctly. We need plenty of time for this to bake to suss out any issues.
