### ISSUE TITLE
MongoDB & temporal filter query optimizations

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#14829]
Optimizing the SQL/native queries we generate when using MBQL relative-datetimes e.g. `"last month"` or `"this week"`

**Implementation Plan**

~~1. Fix #11837~~
2. Fix #9934
3. Investigate fixing some of the stretch goals issues.

***ETA***: 03/08/2021 (ETA of merged feature when we start work)

- [x] Optimize relative datetime filter clauses (#11837)
- [x] Non-optimal conversion of custom questions to queries for SQL Server DBs (#9934) 

#### Stretch Goals

These weren't part of the original schedule for 0.39, but they are thematically related, so I might fix them if time permits.

- [x] Presto non-optimal timestamp column queries (#13361)
- [x] Don't need to cast DATE columns with `date()`  (#11502)
- [x] MongoDB shouldn't do an initial projection for :default date bucketing (#14838)
- [x] Mongo DB queries - execute $match before $project (#4216)
- [x] Multiple metrics with count distinct with MongoDB returns the same result (#13097) 
- [x] Extra ; in filters when using Date Between filter with Google Analytics Source (#12791) 
- [x] Google Analytics - Filter escaping causing issues (#8626)
- [x] MBQL Refactor: Combine various Field clauses into one new clause (#14897)

**How to Test This Feature Out**

These fixes will all be under-the-hood, so things will continue to work the same as before, but performance will be improved. You can convert an MBQL question to a native query to manually verify that the improved SQL is now being generated
