### ISSUE TITLE
SSH Connectivity Improvements

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#14929]
A series of improvements to allow maintaining robust SSH connections

**Implementation Plan**

***ETA***: 02/28/2021

***Milestone 1***
- [x] [make SSH heartbeat interval configurable](https://github.com/metabase/metabase/issues/13399): https://github.com/metabase/metabase/pull/14679
- [x] [restart SSH tunnel if connection goes away](https://github.com/metabase/metabase/issues/10081): https://github.com/metabase/metabase/pull/14563

pulling this issue out for 40:
- [x] [SSH tunnel timeout on docker](https://github.com/metabase/metabase/issues/6114)

**How to Test This Feature Out**

TBA: some stress test scenarios that we used to trip on before, to also inform how we might want to set up automated tests
