### ISSUE TITLE
0.39.0/0.40.0 Security Improvements

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15116]
General security improvements and new notification emails.

Issues: 
- [x] Maintain login history; make this visible to users in an “My Account” page (#14311)
- [x] Notification Emails - Logging into new device (#14313) 
- [ ] Notification Emails - Sensitive Actions (#14314)
- [x] Use deny list for known dumb passwords (#14316)
- [x] Log auth failures and situations where rate-limiting is applied (#14317)
- [ ] Expose password complexity requirement setting in admin UI (#5992)

***ETA***: 03/25/2021 (ETA of merged feature when we start work)

**Comment by andreychirikba** [comment]
Would be great if notification mails could be turned on or off. Our self-made SSO logs the user in through the API on the backend and then redirects him to Metabase (so the login is from 1 IP and the further interaction from a different one, hope this won't be a problem in itself). User doesn't expect any authentication-related mails from Metabase itself.

**Comment by camsaul** [comment]
Closing this epic out since the key stuff we wanted to get done in here has been done, and there open issues tracking the other stuff
