### ISSUE TITLE
0.39 Docs

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#15259]
New features:

- [x] Search: suggestions as you type; we now search through descriptions, sql query contents, and metadata; and we use “fuzzy” search https://github.com/metabase/metabase/pull/15419
- [x] New Number dashboard filter widget, and new options for Category/Location widgets https://github.com/metabase/metabase/pull/15422
- [x] You can now duplicate saved questions from the question detail page. https://github.com/metabase/metabase/pull/15421
- [x] Ability in data model field settings to manually cast a field to a different type
- [x] (EE-only) per-subscription filter values for dashboard subscriptions https://github.com/metabase/metabase/pull/15525
- [X] New "explore results" button on SQL queries https://github.com/metabase/metabase/pull/15010. NOTE: REVERTED. This change will not be in 0.39. See https://github.com/metabase/metabase/pull/15377. 

Notable changes to existing features:
- [x] Redesigned picker for using saved questions as starting data (No need to document).
- [x] Dashboard filter widgets now use “contains” instead of “starts with” for filtering/searching through options (I suspect this is more of a release notes item than something we need to explicitly document) (No need to document, covered in https://github.com/metabase/metabase/pull/15422).
- [X] can now connect to oracle databases over SSL (https://github.com/metabase/metabase/pull/15078)
- [x] can now connect to MySQL DBs with SSL certificate via PEM file (No need to document, should just work)
- [x] can now configure heartbeat intervals for DB connections over SSH tunnels. https://github.com/metabase/metabase/pull/14679

Unsure if these will be implemented in 0.39, but are currently present in the milestone:
- [ ] Add-data for dashboard cards will be in a sidebar rather than a modal 
- [x] Various security enhancements, like getting an email when you've changed your password, see your login history

**Comment by mazameli** [comment]
Gonna change this one to just documentation and create epics for the other efforts separately.
