### ISSUE TITLE
0.39 string translations

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#15265]
- [x] Push new strings to POEditor
- [x] Ping translators
- [x] Translate any remaining strings
- [ ] Pull new translations into the release branch (https://github.com/metabase/metabase/pull/15630)

**Comment by mazameli** [comment]
Closed by #15630
