### ISSUE TITLE
React 16 Polishes Follow-up

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#15306]
This is a follow-up to the migration to React 16 as covered in #14801.

**Implementation Plan**

***ETA***: TBD, likely for v40.
***Project branch***: TBD.

- [ ] update eslint-plugin-react + fix all new errors
- [ ] investigate usage of non-unique keys (behavior changes from hard error to duplication/omission of component)
- [ ] investigate effect of DOM manipulation done outside of react in various components
- [ ] use fragment in `Triggerable` to potentially remove the need for `SandboxedPortal`
- [ ] other things as we find them <tbd>

**How to Test This Feature Out**

As this is an upgrade and migration things should Just Work. Pay special attention to stats.metabase.com to make sure things behave correctly. We need plenty of time for this to bake to suss out any issues.

**Comment by nemanjaglumac** [comment]
> Project branch: TBD.

There is already an ongoing branch/project going on trying to handle all react errors:
https://github.com/metabase/metabase/tree/handle-react-errors

**Comment by ariya** [comment]
Closing this one for good.
