### ISSUE TITLE
Nested Queries & Data Sandboxing Pt. 2

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#15575]
This represents the parts of #13702 we haven't yet got to. Fix feature disparity and classes of issues around data sandboxing and nested queries with the end goal of getting data sandboxes to feature parity with tables and fixing a list of known bugs.

**Links**
- product doc: https://docs.google.com/document/d/1hhYSAxWMW97kNwXzzrKh-Gp6ceTx8aBCaAjKPffclZ8/edit
- eng doc: https://docs.google.com/document/d/1Cds5LRI5HT7fccUtPr1aqIpNLrQgk8ugu3oCWmJKwIk/edit#heading=h.aiy793d9xxqb
- feature branch: TBD

#### Filters
- [ ] #12839: Filtering Custom Expression from aggregated result fails with column not found (`.Reproduced`)

#### Nested
- [ ] #12507: Nested queries using metric got wrong SQL (`.Reproduced`)
- [ ] #13186: Not all columns of nested question available for Dashboard filter (`.Reproduced`)
- [ ] #13764: Cannot select granularity of aggregated fields in nested question (`.Reproduced`)

#### Notebook
- [ ] #13649: Query builder - join saved questions-custom column not found (`.Reproduced`)
- [ ] #12928: Cannot join Saved Questions that themselves contains joins (`.Reproduced`)

#### Sandboxes
- [x] https://github.com/metabase/metabase-enterprise/issues/548 (`.Reproduced`)

#### Features
- [ ] #8272: Add query builder support for nested query FK groupings
- [ ] #8856: Nested queries using metrics need to include all columns used in metric filters
- [ ] #5595: Pass through FK and PK type information from nested SQL subqueries 
- [ ] #5594 (partially): We should scan the results of a saved question and pull out information like FieldValues, etc

**Implementation Plan**

***ETA***: MM/DD/YYYY

- [x] Use `field-id` where possible and flow metadata better [11/30] #13712
  * [x] switch to `field-id` where possible
  * [x] add middleware to update old style MBQL to new
  * [x] go through the list of bugs in #13702 and add them as tests (where applicable. ie. where the hypothesis is that this work should fix it) 
  * [x] pass along more metadata about source query
  * [x] tidy up MBQL->native compiler
  * [ ] cleanup tests
- [ ] Refactor query processing pipeline such that we factor out the MBQL compilation part [12/1] #13713
   * [x] pull MBQL middleware into new namespace
   * [x] split toplevel API into an MBQL preprocessing function and a transducer 
   * [ ] refactor tests to take advantage 
   * [ ] refactor places where we now manually apply MBQL middleware to take advantage
- [ ] Recursively process source queries [12/1] #13714
    * [x] basic version
    * [ ] make it work with MBQL middleware that adds postprocessing 
- [ ] Enforce (and take advantage of) the constraint that sandboxes can only remove fields, and that col aliases must match original field names. [12/2] #13715
  * [x] validate the shape of sandboxing query
  * [ ] take advantage of tighter constraints 
  * [ ] communicate the error to the user 
- [x] Peek at metadata for native SQL sandboxing queries by running them as a test user [12/3] #13716

**How to Test This Feature Out**

_(include steps on how to test this project feature out, for someone unfamiliar with this work. please try to use the sample dataset when possible. this will serve as the basis for automated e2e tests, as well as the acceptance test to showcase the essence of this feature for bug bashes, etc)_
