### ISSUE TITLE
Improve Feedback on Custom Expression Error

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#15658]
Tweak the editor internals to give a more meaningful error message for a class of custom expression errors.

In some cases (e.g. #15246), the displayed error message is too technical, it is both terrifying and not helpful. Also, many error messages are not translated at all (i.e. not supporting i18n).

**Implementation Plan**

***ETA***: MM/DD/YYYY (part of 0.40 release)

* [ ] Custom expression tokenizer
* [ ] Revisit error conditions
  * [ ] Mismatched parentheses
  * [ ] Invalid characters
  * [ ] Unterminated string literals
  * [ ] Incorrect field reference

**Comment by camsaul** [comment]
Additional context from Notion:

When the user enters an invalid custom expression, the editor often gives a horrifying (and not useful) feedback:

![image](https://user-images.githubusercontent.com/1455846/115777722-83524580-a36a-11eb-9141-d7b3f3d75d75.png)

Note that this message is also not translateable (no i18n support).

This task is to catch a small amount of common mistakes like the above (mismatched parentheses, etc) and to present a friendlier message.

**Comment by jeff303** [comment]
I thought I had opened an issue for this one, but I can't find it now, so I'll just mention it here.  It would be nice to have an error message like "forgot comma" if there weren't enough args specified to the function.  As of now, the error message is confusing.  This might require more parsing than we want to do, though?

<img width="494" alt="custom_expression_error_missing_comma" src="https://user-images.githubusercontent.com/3521562/118169813-fccfd780-b3ee-11eb-8ae8-03fa6d71e8ec.png">

**Comment by ariya** [comment]
> It would be nice to have an error message like "forgot comma" if there weren't enough args specified to the function.

Absolutely! Though this requires the syntax information (beyond just tokenization), probably suitable for the family of future improvements filed as #15894.
