### ISSUE TITLE
0.40.0 Search and Pagination

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15767]
Pursuant to #5504. Specific tasks scheduled for 0.40.0 are:

- [ ] Add pagination to Search (#15768)
- [ ] Add search and pagination to Collections (#15769)
- [x] Add Search and Pagination to Admin People List (#15770)
- [ ] Add pagination to Admin Permissions Graph Edit pages (#15771)

(Please feel free to break these up into smaller sub-issues if appropriate, e.g. search and pagination can be tackled separately)
