### ISSUE TITLE
Improve dashboard subscription visualizations

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15776]
Saved Questions that are shared via Pulses and Dashboard Subscriptions do not look the same in emails or Slack as they do in the frontend client (in the browser); most visualization settings are ignored entirely when rendered on the backend, and we only offer a fraction of the visualization types we offer on the frontend client. We want Saved Questions to look the same on both the frontend client and when rendered by the backend for Pulses/Dashboard Subscriptions.

### Tasks:

- [x] Initial investigation/proof of concept/action plan (@camsaul, @kdoh)
- [x] Switch from Nashorn to GraalVM JS Engine (#13881)
- [x] Implement proposed plan (@dpsutton, @ariya)

### Related GH issues this will close:

- [ ] Support unicode (emoji, Chinese characters, etc.) in pulses #2342
