### ISSUE TITLE
Add metadata to collection entities

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15773]
**Issues this would close:**

- [ ] Ability to find questions by date created - filter and/or sort #4624
- [ ] Display last update date on question and dashboard lists #6750
- [ ] Ability to sort and filter questions #13435

# **The problem**

It's really hard to know in Metabase right now who made or has been recently working with a given dashboard, question, or collection. It's also annoying and inconsistent to try and find the revision history for dashboards and collections — the button is in different places, buried in a hard-to-find menu.

# **The proposal in a nutshell**

Let's add some simple metadata to show **who** last edited a thing and **when**.

# **Why do this now?**

It should take relatively little front-end work, and a modest amount of BE working, fitting in with the theme of 0.39, and is a pain point that many users and customers have proactively told us about, and which we've validated with Revolut, Convoy, and Color.

# **Proposed scope and sequence**

## 1. In collection lists, add metadata for Last Edited By and Last Edited On.

- *Note: we'd previously talked about adding Popularity or Fre-cency, but it turns out that'd be nontrivial to add since we'd have to look at the query execution log.*

    ![image](https://user-images.githubusercontent.com/1455846/115781177-e1812780-a36e-11eb-8deb-08c4897cef30.png)

## 2. Allow collection content lists to be sorted by these properties, as well as by Name or Type (dashboard/question/pulse).

- The list of pinned items should be separately sortable.
- The default sort should remain alphabetical order.

## 3. On question and dashboard detail views:

- Add metadata for "Last edited on" and "last edited by."
- Clicking on this should open revision history.

On a dashboard:

![image](https://user-images.githubusercontent.com/1455846/115781185-e6de7200-a36e-11eb-855b-3bcf1fd0035a.png)

On a saved question:

![image](https://user-images.githubusercontent.com/1455846/115781228-f493f780-a36e-11eb-8cc0-f4d52849799b.png)

## Lastly, see if we want to add any of this metadata to the search typeahead box or to the search results page.

In the search suggestions, we could e.g. perhaps find a place for the Last Edited By and Last Edited On metadata. Maybe we use recency as an input to the search weighting?

On the search results page, we could considering adding the ability to either sort or filter by Last Edited On (last 30 days, etc.).

**Comment by kulyk** [comment]
Not sure we can close #4624 (Ability to find questions by date created) here, as we're going to display _last edit_ date, and not the _creation date_
