### ISSUE TITLE
0.40.0 Bottom-Up Content Moderation (BUCM)

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#15797]
This is an XL project and thus will be split into several separate milestones partially mirroring what is found in https://www.notion.so/Prototyping-BUCM-f04f479980ea445fb5ffec0d07237da2. Please note -- the title of this Notion document is "**Prototyping** BUCM" meaning the list and make-up of the milestones listed here will likely change. Accordingly, any ETAs mentioned here should be treated with a decent amount of uncertainty.

- [x] **Milestone 1** -- enable an admin to flag a saved question with one of the given moderation issue types

- - [x] add empty details left sidebar + clickable saved question header
- - [x] add moderation issue menu to the info sidebar
- - [x] add moderation issue creation panel that appears in the sidebar when an admin clicks on an issue in the moderation issue menu
- - [x] finish wiring up the creation process for a new `moderation_review`
- - [x] show moderation issue icon in saved question header after it has been reviewed
- - [x] add timeline to details sidebar to see evidence of `moderation_reviews`

- [x] **Milestone 2** -- fully replace saved question header functionality with the details left sidebar
- - [x] add clamped text UI component
- - [x] add timeline UI component
- - [x] add action icon buttons to details sidebar (to mostly replace actions in pencil icon menu)
- - [x] add editable description to details sidebar
- - [x] add "Edited [relative time]" button to saved question header
- - [x] merge revision history into activity timeline in details sidebar

- [x] **Milestone 3** -- add the ability for non-admins to create (unresolved) moderation issues and for admins to resolve unresolved moderation issues
- - [x] add "open issues" panel
- - [x] update moderation components in sidebar to have non-admin-specific strings
- - [x] add a resolve action menu to the details sidebar timeline
- - [x] add comment action
- - [x] add comment panel to details sidebar

- [ ] **Milestone 4** -- add a request queue for admins to see unresolved moderation issues
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder

- [ ] **Milestone 5** -- add a notification view for non-admin users to see updates to their moderation issues
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder

- [ ] **Milestone 6** -- add a new permissions level, "Moderator"
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder

- [ ] **Milestone 7** -- add moderation issues to the audit log
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder

- [ ] **Milestone 8** -- add a details left sidebar to dashboards
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder

- [ ] **Milestone 9** -- add moderation to dashboards
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder
- - [ ] placeholder

- [ ] **Milestone X** -- write tests
- - [ ] write tests for milestone 1
- - [ ] write tests for milestone 2
- - [ ] write tests for milestone 3
- - [ ] write tests for milestone 4
- - [ ] write tests for milestone 5
- - [ ] write tests for milestone 6
- - [ ] write tests for milestone 7
- - [ ] write tests for milestone 8
- - [ ] write tests for milestone 9

**Comment by tsmacdonald** [comment]
Code at #15618

**Comment by daltojohnso** [comment]
The product design for this feature changed fairly significant and this epic no longer really reflects all the work that landed in `master` and is currently slated for 0.41. I think during our product "pivot" I dropped the ball on updating this document, but the work was done in the following PRs:

https://github.com/metabase/metabase/pull/16803
https://github.com/metabase/metabase/pull/17030
https://github.com/metabase/metabase/pull/17401
https://github.com/metabase/metabase/pull/17426
https://github.com/metabase/metabase/pull/17997
https://github.com/metabase/metabase/pull/17482
https://github.com/metabase/metabase/pull/17340
https://github.com/metabase/metabase/pull/17329
https://github.com/metabase/metabase/pull/17311

**Comment by daltojohnso** [comment]
Besides one bug that is in-flight (https://github.com/metabase/metabase/pull/17997), this project is completed, so I am closing this epic.
