### ISSUE TITLE
Fix Dashboard Filters for Users without Data Permissions [meta issue]

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#15926]
It seems like we have a bunch of issues that are all pretty much exactly the same. I'm opening this meta issue to keep track of them all so I can figure out what to do about them.

- [x] Allow field filtering for users without access to the database #8472 (Historic)
- [ ] Field Filter dropdown not working for users without data permissions in some cases #12654
- [ ] 0.37.0-RC3: chained filter endpoints fail without data permissions #13537
- [ ] Difficult to use some filters, when user has no data permissions #15119

This is not a simple fix because of potential security implications. I brought this up in #8472:

> 1. I have a database with a `user` Table and I want to give some of my employees restricted access to it. I create a few questions that filter out sensitive columns like `password` and `salary` and stick them in a Dashboard. I give my employees access to a Collection containing those questions, but no data access
> 2.  Bad Actor Billy can add a `salary` filter to the Dashboard even though he doesn't have data access permissions
> 3.  Oops! `salary` only has a few distinct values making it a category. Billy can click the various salaries and determine which employees have which salary respectively. 

And again in #13537:

> So a bad actor could of course have put parameters entries in there that reference arbitrary Field IDs. The backend permissions checks happen around the Field IDs themselves, so that sort of stuff wouldn't matter -- the FE could try to fetch info/values for the Fields referenced by those parameters, but if the current user didn't have read perms for the Field(s), the request would return a 403.
> 
> Bypassing Field perms checks in the parameters endpoints would only be something we should be comfortable doing if we're confident that the `:parameters` saved in a Dashboard were validated, which they're not. `:parameters` is still essentially treated as untrusted input by the backend.
> 
> So to change this (assuming we wanted to) I think we'd need to rename `parameters` to `legacy_untrusted_parameters` or something like that and create a new trusted `parameters` column that we'll use for all new Dashboards or when you re-save existing ones. And only for the new trusted `parameters` could we even consider bypassing normal Field permissions checks 

See those issues for more context.

I'm not really clear how we should validate the dashboard parameters going forward. It seems like letting people add filters on arbitrary columns is a huge security loophole. But how to decide which columns to allow is an open question.
 
1.  Should we only allow you to create a filter on a Field returned by one of the Cards in a dashboard? e.g. in the example above, you couldn't add a filter on `salary` because it doesn't come back in the results. But what about something like a scalar column, like `Count of Sales` -- why couldn't I add a filter on `Product Category` or something like that?

Once we figure out how this should work, we can migrate Dashboard parameters to `legacy_untrusted_parameters` and validate all params going forward after that.

**Comment by camsaul** [comment]
See Slack thread https://metaboat.slack.com/archives/C01NT034X2B/p1650486974835959 as well

**Comment by camsaul** [comment]
Closed as solved by the transition to Lib v2
