### ISSUE TITLE
Infer the data type for Expression Dimension (custom column)

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#15952]
Right now, any custom column is hardcoded to a number ("type/float"), see #13122.

In order to properly infer the right data type, a type inference needs to be implemented for custom expression.

**Implementation Plan**

*Status*: Merged to master as of May 11. Will be part of 0.40 release.

* [x] Basic type inference (PR #15940)
* [x] Use inferred type in Expression Dimension (PR #15965)
* [x] Get env access (for resolving external fields) (PR #15982)
* [x] Improve type inference for `CASE` and `COALESCE` (PR #15996)
