### ISSUE TITLE
[E2E] Version Upgrade Testing

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#16232]
- [x] PoC mechanism for cross-version testing (https://github.com/metabase/metabase/pull/24617)
- [ ] Minimal "dataset" needed for tests
    - should include a few questions, models, dashboards
    - remapped data model
    - a few collections
    - metrics/segments (created via API)
- [ ] additional users and advanced permissions
- [ ] tbd

**Comment by nemanjaglumac** [comment]
Will be replaced by some other, newer initiative.
