### ISSUE TITLE
Collections Metadata FE Implementation

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#16356]
It's really hard to know in Metabase right now who made or has been recently working with a given dashboard, question, or collection. This project is focused on adding some simple metadata to show **who** last edited a thing and **when**.

**Links**
- [product doc](https://www.notion.so/Add-metadata-to-collection-entities-27d755443de344d48d6c43e0a45af720)
- feature branch: [`0.40-collections-metadata`](https://github.com/metabase/metabase/tree/0.40-collections-metadata)
- issue links: #15773 #4624 #6750 #13435
 
**Note**
The project was implemented in a single huge PR #16295. We then decided to split them into a set of smaller PRs, so it's easier to manage and review. Still, the review contains important discussions, so I'm linking it here.

**Implementation Plan**
- [x] Switch the collection page to table-based layout, displaying last edit info (#16357)
- [x] Update collection items drag-n-drop (#16360)
- [x] Add collection items sorting with the new backend API #16275  (#16385)
- [x] Fix UI flashes when sorting or switching collection items pages (#16511)
- [x] Display last edit info in Question and Dashboard headers (#16354)
- [x] Add tooltip displaying last edit time like "June 3, 12:10 PM" (#16492)
- [x] Add E2E tests for last edit info in Question and Dashboard headers (#16538)
