### ISSUE TITLE
[E2E] Binning

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16387]
## Proposal
We've seen increasing number of bugs related to the different types of data binning. Even when we issue a fix for one bug, some other pops up.

Instead of reproducing every single issue with a lot of smaller (and similar) repros, create one larger test matrix of all possible scenarios/contexts to prevent new bugs and regressions.

---
- [x] Make sure all binning options render correctly
    - [x] for regular table #16622
    - [x] for implicit joins #16698
    - [x] for explicit joins #16703 
- [x] Group existing binning repros together #16629
---
- [x] Make sure longitude binning renders correct results for _each_ of its options #16630
- [ ] Make sure number binning renders correct results for _each_ of its options #16640
- [x] Make sure time binning renders correct results for _each_ of its options #16643
---
- [x] Make sure all binning options work for a regular table #16712
- [x] Make sure all binning options work for all entry points on a saved SQL question #16660
- [x] Make sure all binning options work for simple and custom question modes on a saved QB question using implicit joins #16662
- [x] Make sure all binning options work for all entry points on a saved QB question with explicit joins #16661
---

### Scenarios:
- regular table / saved question GUI,
- implicit joins,
- explicit joins,
- saved question SQL

### Assertions
- make sure binning options don't render two times
- make sure the default option in the popover is highlighted by default (see [this comment](https://github.com/metabase/metabase/pull/16373#pullrequestreview-676776901))
- make sure binning works for:
    - numbers
    - latitude / longitude
    - dates (timestamps)
    
### Entry points
- simple question
- custom question
- column popover (choosing "distribution" from the column heading)

### Related issues raised so far
- #16379 (`.Reproduced`)
- #15446 (`.Reproduced`)
- #16327 (`.Reproduced`)
- #15574 (`.Reproduced`)
- #14787 (`.Reproduced`)
- #12004
- #9321
- #13914 (not possible to test with the current Sample Dataset)

### Binning issues discovered and filed while working on this expanded coverage

- #16693 (`.Reproduced`)
- https://github.com/metabase/metabase/issues/16679
- https://github.com/metabase/metabase/issues/16675 (`.Reproduced`)
- https://github.com/metabase/metabase/issues/16674 (`.Reproduced`)

`result_metadata` issues
- https://github.com/metabase/metabase/issues/16672 (`.Reproduced`)
- https://github.com/metabase/metabase/issues/16671 (`.Reproduced`)
- https://github.com/metabase/metabase/issues/16670 (`.Reproduced`)

### Ongoing PR that attempts to fix most of these issues

*  #16707
* #16755 (previously: #16373, unsuccessful targeting `release-x.39.x`)
* #16768

### Past PRs which fixed related issues (for more context)

* #15530
* #15605
* #15582
* #16140
* #16478
