### ISSUE TITLE
Update front-end dependencies

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#16398]
## Goals of this epic:

1. to bring visibility to the universe of libs outdated
2. to bring visibility to the extent of the outdates in some cases
3. to encourage teammates to go for high ROI issues below

Even if you do not plan to tackle an update immediately, but see good reasons for an update to be attempted, please:

1. add the justification to the corresponding issue's description
2. move the corresponding checkbox line to the list of issues that have a practical justification

### The following issues have a stated practical justification for updating

* - [x] Update js lib styled-components - https://github.com/metabase/metabase/issues/16468
* - [x] Update js lib webpack - https://github.com/metabase/metabase/issues/16473
* - [ ] Update js lib babel - https://github.com/metabase/metabase/issues/16487
  * - [ ] Update js lib jest - https://github.com/metabase/metabase/issues/16431

### The following issues do not have a stated practical justification for updating

- [ ] Update js lib @babel/standalone - https://github.com/metabase/metabase/issues/16395
- [ ] Update js lib @cypress/webpack-preprocessor - https://github.com/metabase/metabase/issues/16396
- [x] Update js lib @slack/client - https://github.com/metabase/metabase/issues/16397
- [ ] Update js lib @testing-library/cypress - https://github.com/metabase/metabase/issues/16399
- [ ] Update js lib @testing-library/dom - https://github.com/metabase/metabase/issues/16400
- [ ] Update js lib @testing-library/jest-dom - https://github.com/metabase/metabase/issues/16401
- [ ] Update js lib @testing-library/react - https://github.com/metabase/metabase/issues/16402
- [ ] Update js lib @testing-library/user-event - https://github.com/metabase/metabase/issues/16403
- [ ] Update js lib babel-loader - https://github.com/metabase/metabase/issues/16404
- [ ] Update js lib babel-plugin-styled-components - https://github.com/metabase/metabase/issues/16405
- [ ] Update js lib babel-plugin-ttag - https://github.com/metabase/metabase/issues/16406
- [x] Update js lib chevrotain - https://github.com/metabase/metabase/issues/16407
- [ ] Update js lib classnames - https://github.com/metabase/metabase/issues/16408
- [ ] Update js lib concurrently - https://github.com/metabase/metabase/issues/16409
- [ ] Update js lib core-js - https://github.com/metabase/metabase/issues/16410
- [ ] Update js lib css-loader - https://github.com/metabase/metabase/issues/16411
- [x] Update js lib cypress - https://github.com/metabase/metabase/issues/16412
- [ ] Update js lib cypress-real-events - https://github.com/metabase/metabase/issues/16413
- [ ] Update js lib d3 - https://github.com/metabase/metabase/issues/16414
- [ ] Update js lib d3-scale - https://github.com/metabase/metabase/issues/16415
- [ ] Update js lib dc - https://github.com/metabase/metabase/issues/16416
- [ ] Update js lib diff - https://github.com/metabase/metabase/issues/16417
- [ ] Update js lib documentation - https://github.com/metabase/metabase/issues/16418
- [ ] Update js lib eslint - https://github.com/metabase/metabase/issues/16420
- [ ] Update js lib eslint-import-resolver-webpack - https://github.com/metabase/metabase/issues/16421
- [ ] Update js lib file-loader - https://github.com/metabase/metabase/issues/16422
- [x] Update js lib grid-styled - https://github.com/metabase/metabase/issues/16423
- [ ] Update js lib history - https://github.com/metabase/metabase/issues/16424
- [ ] Update js lib html-webpack-harddisk-plugin - https://github.com/metabase/metabase/issues/16425
- [ ] Update js lib html-webpack-plugin - https://github.com/metabase/metabase/issues/16427
- [x] Update js lib iframe-resizer - https://github.com/metabase/metabase/issues/16428
- [ ] Update js lib image-diff - https://github.com/metabase/metabase/issues/16429
- [ ] Update js lib isomorphic-fetch - https://github.com/metabase/metabase/issues/16430
- [ ] Update js lib jest-localstorage-mock - https://github.com/metabase/metabase/issues/16432
- [ ] Update js lib jsonwebtoken - https://github.com/metabase/metabase/issues/16433
- [ ] Update js lib leaflet-draw  - https://github.com/metabase/metabase/issues/16434
- [ ] Update js lib lint-staged - https://github.com/metabase/metabase/issues/16435
- [ ] Update js lib mockdate - https://github.com/metabase/metabase/issues/16436
- [ ] Update js lib moment - https://github.com/metabase/metabase/issues/16437
- [ ] Update js lib mustache - https://github.com/metabase/metabase/issues/16438
- [x] Update js lib postcss-cssnext - https://github.com/metabase/metabase/issues/16439
- [x] Update js lib postcss-import - https://github.com/metabase/metabase/issues/16440
- [x] Update js lib postcss-loader - https://github.com/metabase/metabase/issues/16441
- [x] Update js lib postcss-url - https://github.com/metabase/metabase/issues/16442
- [ ] Update js lib prettier - https://github.com/metabase/metabase/issues/16443
- [ ] Update js lib re-reselect - https://github.com/metabase/metabase/issues/16444
- [ ] Update js lib react - https://github.com/metabase/metabase/issues/16445
- [ ] Update js lib react-collapse - https://github.com/metabase/metabase/issues/16446
- [ ] Update js lib react-dnd - https://github.com/metabase/metabase/issues/16447
- [ ] Update js lib react-dnd-html5-backend  - https://github.com/metabase/metabase/issues/16448
- [ ] Update js lib react-dom - https://github.com/metabase/metabase/issues/16449
- [ ] Update js lib react-draggable - https://github.com/metabase/metabase/issues/16450
- [ ] Update js lib style-loader - https://github.com/metabase/metabase/issues/16467
- [ ] Update js lib react-element-to-jsx-string - https://github.com/metabase/metabase/issues/16451
- [x] Update js lib react-markdown - https://github.com/metabase/metabase/issues/16452
- [ ] Update js lib react-redux - https://github.com/metabase/metabase/issues/16453
- [ ] Update js lib react-resizable - https://github.com/metabase/metabase/issues/16454
- [ ] Update js lib react-router - https://github.com/metabase/metabase/issues/16455
- [ ] Update js lib react-sortable-hoc - https://github.com/metabase/metabase/issues/16456
- [ ] Update js lib react-textarea-autosize - https://github.com/metabase/metabase/issues/16457
- [ ] Update js lib react-transition-group - https://github.com/metabase/metabase/issues/16458
- [ ] Update js lib redux - https://github.com/metabase/metabase/issues/16459
- [ ] Update js lib redux-auth-wrapper - https://github.com/metabase/metabase/issues/16460
- [x] Update js lib redux-form - https://github.com/metabase/metabase/issues/16461
- [ ] Update js lib redux-promise - https://github.com/metabase/metabase/issues/16462
- [ ] Update js lib reselect - https://github.com/metabase/metabase/issues/16463
- [ ] Update js lib screenfull - https://github.com/metabase/metabase/issues/16464
- [ ] Update js lib shadow-cljs - https://github.com/metabase/metabase/issues/16465
- [ ] Update js lib simple-statistics - https://github.com/metabase/metabase/issues/16466
- [ ] Update js lib styled-system - https://github.com/metabase/metabase/issues/16469
- [ ] Update js lib tether - https://github.com/metabase/metabase/issues/16470
- [x] Update js lib uglifyjs-webpack-plugin - https://github.com/metabase/metabase/issues/16471
- [x] Update js lib underscore - https://github.com/metabase/metabase/issues/16472
- [x] Update js lib webpack-dev-server - https://github.com/metabase/metabase/issues/16474
- [ ] Update js lib webpack-notifier - https://github.com/metabase/metabase/issues/16475

**Comment by kulyk** [comment]
Huge thank you for putting those into issues @gusaiani

Agreeing with @ariya that we should sort them by a clear ROI, as updating some dependencies can result in a few days-long projects.

My two cents on the possible benefits:

* upgrading `jest` would allow us to write more unit tests for UI to offload the E2E test suite a little bit. I tried to cover a component talking to the API and using Redux, and it [didn't go well](https://github.com/metabase/metabase/pull/16156#issuecomment-845167164). @daltojohnso has tried to upgrade `jest`, but it looks like our current version of Babel blocks it (see [PR](https://github.com/metabase/metabase/pull/16179))
* `redux` and `redux-form` (as I remember @daltojohnso said it's hard to upgrade them independently now). The newer versions contain hooks API, and it can help make our entity loaders framework a bit more flexible. I can't say I faced some problems that are impossible to solve without hooks cleanly, but I feel some areas of the codebase could be simplified with hooks. I'll have a good example of that in a couple of days. Overall, I guess it's closer to the "nice to have" right now but please correct me if you see it could be a breath of fresh air in a different area of the codebase.

**Comment by gusaiani** [comment]
You're most welcome, @kulyk.

I've updated the description above from your input.

A couple of weeks ago I played with upgrading `redux` and, to my surprise, I did not see any breakage at all after an obvious one-line change. So we may have a good surprise there.

As far as I can say, please feel free to lead the updates that make sense to you.

**Comment by iethree** [comment]
closed all these issues since they're so stale
