### ISSUE TITLE
Create Extensive e2e coverage for SQL filters [WIP]

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16759]
## Proposal
We have pretty low coverage on the SQL filters. The number of possible combinations got even more complicated and grew significantly with the introduction of the filter feature flag. We've also seen a P1 regression (#16739) from #15981 in just under a month.

Instead of reproducing every single issue with a lot of smaller (and similar) repros, create one larger test matrix of all possible scenarios/contexts to prevent new bugs and regressions.

Read more about [SQL parameters](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html).

### Filter Types
- [x] Basic (#16813)
    - Text
    - Number
    - Date
- [x] Field Filter and all of its syb-types
    - [x] None (#16928)
        - Should be covered just once and not for each of the sub-types since it has the same meaning for everything - no filter applied
        - Also, see [this comment](https://github.com/metabase/metabase/issues/13825#issuecomment-872172237) and the response for more context

    - [x] ID (#16926)

    - [x] String (#16851)
      - string?
      - is not
      - contains
      - does not contain
      - starts with
      - ends with

    - [x] Number (#16852)
      - Equal to
      - Not equal to
      - Between
      - Greater than or equal to
      - Less than or equal to

    - [x] Date (#16854)
      - Month and Year
      - Quarter and Year
      - Single Date
      - Date Range
      - Relative Date
      - Date filter

### Misc

- [ ] Tests around basic UI flow, labels, etc.
- [ ] Tests for multiple filters set and how they play together
- [ ] Tests for [optional clauses](https://www.metabase.com/docs/latest/users-guide/13-sql-parameters.html#optional-clauses)

---
### Housekeeping Log
- [x] Extract helper functions and data into separate files (scoped to this folder, according to [this doc](https://www.notion.so/Proposal-Folder-level-Helper-Functions-e923ea2ea7ab4746bd67c24f06eb0494))
    - [x] Basic SQL filter helpers (#16887)
    - [x] Field filter helpers (#16891)
    - [x] Date filter helpers (#16892)
    - [x] Data needed for test matrix (#16893)

- [x] Group SQL filter reproductions together under the same folder (simplify and refactor them by applying previously created helper functions) (#16898)

---
Note: This list is not exhaustive and the final scope of the project is yet TBD.
