### ISSUE TITLE
(Re)organize Cypress helper functions

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#16883]
## What?
We currently store Cypress helper functions in `frontend/test/__support__/e2e/cypress.js`.
We should organize it better in a similar fashion that we used for Cypress custom commands.

In the end, the `cypress.js` file should just contain the necessary imports and should re-export the helpers from the individual files that we create.

## Why?
The file is getting larger by the day and it starts to feel cluttered/disorganized. I've seen devs not even being aware some of the helper functions exist.

## How?
1. Extract the logical helper functions into individual files grouped under the `./helpers` folder.
2. Annotate every single helper function using JSDoc
3. Re-export all helpers from `cypress.js`
```javascript
// cypress.js

export * from "./helpers/e2e-foo-helpers.js;
```
---
## Tracking progress
- [x] Extract helpers into separate files (#16884)
- [ ] Annotate helpers using JSDoc
- [x] Deal with deprecated helpers

### Assorted tasks
- [x] Refactor Cypress to use `VisitQuest` (#20671)
- [x] #20775
- [x] #20777

**Comment by nemanjaglumac** [comment]
Closing this because the only left task on the list is "Annotate helpers using JSDoc", which might easily be deprecated soon if we move to using TypeScript.
