### ISSUE TITLE
[Internal] Refactor and improve our custom Cypress runner using official Cypress' APIs

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#17005]
### Status
FINISHED

### What is the plan?
- [x] Move logic for enterprise token config out of the Cypress runner (#17006)
- [x] Move helpers/utils out of the Cypress runner (partially implemented in #17008)
- [x] Extract the logic for for version checking into a separate file (#17015)
- [x] Extract the logic that generates Cypress snapshots out of the Cypress runner and use Module API for this (#17010)
- [x] Extract the logic that runs Cypress tests out of the Cypress runner and use Module API for this (#17099)

### Why this change?
Our old Cypress runner was based on a completely custom implementation. It was spawning Node processes for both snapshots and for the actual tests. We had to return Promises and were missing on an incredibly rich results object - both of which come for free with the Cypress Module API.

Custom runner was a file with close to 200 loc. Both helpers and the main logic lived together and it was extremely hard to read it, let alone understand what's going on under the hood, unless one spent a good amount of time dealing with that file. 

With the modular approach, it's much easier to read it and to reason about the logic, not to mention debugging it.

#### Fail as early as possible
Sometimes there is something wrong with the Snapshot generation process (that is crucial for the actual Cypress tests to run successfully). Before implementing #17010, that step would fail but the Cypress would actually start running tests. That was time wasted (both in the CI and locally) because if only one snapshot failed, there is no way all Cypress tests will come back green.
Now as soon as one task in this chain fails, the whole `process` is terminated and the backend gets cleaned.

#### CI TImeouts
We experience timeouts in CircleCI periodically. I cannot guarantee that this change will fix that, but there is a good chance those timeouts were caused by some flaw in the previous custom logic.

#### GitHub Actions
It is close to impossible to run the official [Cypress GitHub Action](https://github.com/cypress-io/github-action) because of the way we parse cli arguments.
```javascript
const userArgs = process.argv.slice(2);
```
I realized that while working on enabling the Cypress grep plugin (which is set through the `env`, or the `--env` flag). Long story short, because we already opted in to using our own custom logic and custom parsing logic, we couldn't even add officially supported flags without having to basically re-implement them. Just take a look at the `--spec`.
```javascript
const isSpecFlag = userArgs.includes("--spec");
const sourceFolderLocation = userArgs[userArgs.indexOf("--folder") + 1];
const specs = userArgs[userArgs.indexOf("--spec") + 1];
const isSingleSpec = !specs || !specs.match(/,/);
const testFiles = isSingleSpec ? specs : specs.split(",");
// then later in the file
const specsConfig = isSpecFlag && { testFiles };
```
All of this for something that's already provided by Cypress and available by default. Just take a look at the [number of supported flags](https://docs.cypress.io/guides/guides/command-line#cypress-run) for the cli and it's immediately clear why this approach is not scalable.

### Possible next steps (out of scope of this PR)
- Rewrite  `frontend/test/__runner__/backend.js` as a Node module, or use Babel to help transpile it.
    - It is currently not possible to `require` `BackendResource` from that file because of the ES6 syntax.
- After that, set `baseUrl`directly through the plugins file (also cannot require `BackendResource`)
- Extract `cleanup()` together with the rest of the helpers
- Move `metabase-db` files from their own separate folder together with the rest of the "normal" specs
    - That'd greatly simplify the logic behind the `ignoreTestFiles` and setting the "source folder"
    - It would also simplify CircleCI config file

### Related links:
- https://docs.cypress.io/api/plugins/configuration-api
- https://docs.cypress.io/guides/guides/module-api
