### ISSUE TITLE
0.41 Collection Types FE Implementation

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#17072]
Adding 'official' collection types to distinguish 'canonical' items

**Links**
- [product doc](https://www.notion.so/metabase/Add-Types-to-Collections-2bf7aa8117db4dbc8b0318b2ca5f9902)
- feature branch: [`0.41-collection-types-fe`](https://github.com/metabase/metabase/tree/0.41-collection-types-fe)
- backend PR: #16191

**Implementation Plan**

- [x] Create collections plugin that can be patched from `metabase-enterprise` (#17071)
- [x] Add "collection type" form field (#17071)
- [x] Display "collection type" form field only to admin users (#17170)
- [x] Don't display "collection type" form field for personal sub-collections (#17170)
- [x] Allow updating collection type for all the collection's children at once (#17168)
- [x] Display official collection badge in collection tree sidebar, in search results, saved questions picker and question and dashboard pages (#17125)
- [x] Display official question's badge when it's in a regular dashboard (#17167)
