### ISSUE TITLE
Create Extensive e2e coverage for Dashboard filters [WIP]

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#17078]
https://www.metabase.com/docs/latest/users-guide/08-dashboard-filters.html

- [x] Extract reproductions into a separate folder
- [x] Create new e2e group in the CI
- [x] Move over some of the existing tests

### QB filters
- [x] Date (#17173)
    - Month and Year, Quarter and Year, Single Date, Date Range, Relative Date, All Options
- [x] Location (#17191)
    - Dropdown, Is not, Contains, Does not contain, Starts with, Ends with
- [x] Number (#17188)
    - Equal to, Not equal to, Between, Greater than or equal to, Less than or equal to
- [x] Text or Category (#17192)
    - Dropdown, Is not, Contains, Does not contain, Starts with, Ends with
- [x] ID (#17190)

---
### SQL Filters
- [x] Date (#17483)
    - Month and Year, Quarter and Year, Single Date, Date Range, Relative Date, All Options
- [x] Location (#17423)
    - Dropdown, Is not, Contains, Does not contain, Starts with, Ends with
- [x] Number (#17395)
    - Equal to, Not equal to, Between, Greater than or equal to, Less than or equal to
- [x] Text or Category (#17382)
    - Dropdown, Is not, Contains, Does not contain, Starts with, Ends with
- [x] ID ()

---
- [x] Simple QB question in a dashboard
- [x] Simple QB question in a dashboard (add filters on implicit joins)
- [x] Joined QB question in a dashboard (add filters on explicit joins)

- [x] SQL question with field filters in a dashboard with filters

- [x] Required filters
- [x] Filters with default values (both on question and on the dashboard)

- [ ] Test basic UI flow by adding each of the question types manually to the dashboard and try adding filter while still in edit mode
- [ ] Extract common helpers
