### ISSUE TITLE
Implement secret management in Metabase

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#18036]
This work will introduce support for handling secret database configuration parameters as first class entities in Metabase.  In the short term, this will provide a set of consistent behaviors for specifying any type of secret (including simple passwords or complex binary files, like Java keystores) in a way that is appropriate for each deployment type (self-hosted and cloud).  In milestone 1, this will be exposed only in a select few places (i.e. #18035) to vet out the concept and implementation before expanding it.

In the medium term, if milestone 1 is successful, we can convert some of the existing driver parameters over to the secret config type, including

- MongoDB SSL Server certificate chain (currently a textarea type field)
- BigQuery service account JSON
- any place where a password is entered

In the long term, it also sets the stage for more sophisticated features, including (but not limited to)
- bulk rotation/audit capabilities of passwords/certificates for admins, either through the UI or a CLI
- ability to reference the same secret instance from multiple databases (ex: one truststore to be used for multiple connections)
- adding support for other sources of secret values (ex: Vault, AWS Secrets Manager, etc.), and enabling that capability on every place where a secret is configured across all drivers

**Implementation Plan**

- [x] #17646 Support encryption of binary data
- [x] #17649 Add secret model
- [x] #17677 Integrate secret handling with db-details
- [x] #17756 Add backend support for keystore type secrets
- [x] #18236 Translate secret connection-properties into existing types understood by frontend
- [x] #18320 Update Oracle properties
- [x] #18968 Support SSL certificates for Postgres
- [x] #18714 Prevent secret records from being orphaned

**Links**
- [product doc](https://www.notion.so/metabase/Add-Support-for-Complex-Database-Auth-Modes-in-the-UI-c34689eb8ad440088f8287a00d94812d)
- [eng project planning doc](https://www.notion.so/metabase/Standardized-handling-for-secret-blobs-ea833d9c2c9b45a5a1047929a843a457)
- feature branch: none yet (all stacked, with the top one targeting `master`)
- Issue links: #18035

**Acceptance Criteria**

For milestone 1, users should be able to provide keystores and/or truststores to Oracle in the UI, regardless of deployment environment (#18035), and should be able to use all auth modes and enter certificates for Postgres (#18939).

**Comment by paoliniluis** [comment]
leaving this one here as well for the next phase https://github.com/metabase/metabase/issues/19514
