### ISSUE TITLE
Consolidate Metabase QA DB e2e tests

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#18118]
Unify `metabase-db` e2e tests with the rest of e2e tests: Notes - We currently keep all e2e tests that depend on the external DB (supported are mysql, mongo and postgres) in a separate folder. We also run them in a separate process in CI. It makes more sense to run those tests along with the rest. Benefits are numerous:
- reduced number of total e2e groups in CI
- the possibility to run a single test agains different databases (matrix style)
- slightly faster running time (after the snapshot implementation)

**Links**
- https://github.com/metabase/metabase-qa

**Implementation Plan**
- [x] Introduce a mechanism that makes sure external DB metadata synced and is ready for use (https://github.com/metabase/metabase/pull/18116)
- [x] Start QA DB images together with the main executor (https://github.com/metabase/metabase/pull/18129)
- [x] Reutilize `QA_DB_ENABLED` env and use it to conditionally create/skip creating QA DB snapshots (https://github.com/metabase/metabase/pull/18179)
- [x] Make Postgres app db snapshot and use it in tests instead of manually adding the database every single time (https://github.com/metabase/metabase/pull/18106)
- [x] Make Mongo app db snapshot and use it in tests instead of manually adding the database every single time (https://github.com/metabase/metabase/pull/18184)
- [x] Make MySQL app db snapshot and use it in tests instead of manually adding the database every single time (https://github.com/metabase/metabase/pull/18193)
- [x] Clean CircleCi config and Cypress runner
- [x] Update dev documentation

**How to Test This Feature Out**
As explained in https://github.com/metabase/metabase/pull/18179
