### ISSUE TITLE
Typescript migration

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#18345]
### Description

We needed Typescript to eliminate an entire class of bugs, improve our DX, document code better, etc. This epic contains the Typescript setup, conversion of most frequently used files to TS, and Flow removal that blocks migration to Typescript.

**Links**
RFC: https://www.notion.so/metabase/14-Typescript-migration-dfe7f1f17bfe463bb536cf2ef15703d5

#### Allow using Typescript for new code
- [x] https://github.com/metabase/metabase/pull/18284
- [x] https://github.com/metabase/metabase/pull/18332
- [x] https://github.com/metabase/metabase/pull/18528
- [x] https://github.com/metabase/metabase/pull/19390
- [x] https://github.com/metabase/metabase/pull/18778
- [x] https://github.com/metabase/metabase/pull/18329
- [x] https://github.com/metabase/metabase/pull/19204
- [x] https://github.com/metabase/metabase/pull/19222
- [x] https://github.com/metabase/metabase/pull/19224
- [x] https://github.com/metabase/metabase/pull/19237

#### Remove flow
- [x] https://github.com/metabase/metabase/pull/19205
- [x] https://github.com/metabase/metabase/pull/19208
- [x] https://github.com/metabase/metabase/pull/19209
- [x] https://github.com/metabase/metabase/pull/19210
- [x] https://github.com/metabase/metabase/pull/19211
- [x] https://github.com/metabase/metabase/pull/19212
- [x] https://github.com/metabase/metabase/pull/19213
- [x] https://github.com/metabase/metabase/pull/19214
- [x] https://github.com/metabase/metabase/pull/19215
- [x] https://github.com/metabase/metabase/pull/19216
- [x] https://github.com/metabase/metabase/pull/19217
- [x] https://github.com/metabase/metabase/pull/19218
- [x] https://github.com/metabase/metabase/pull/19219
- [x] https://github.com/metabase/metabase/pull/19220
- [x] https://github.com/metabase/metabase/pull/19221
