### ISSUE TITLE
Remove usage of deprecated React lifecycle methods

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#18408]
This epic is to track work on refactoring class components to not use deprecated `UNSAFE_` methods. The plan is to split the work based on top-level folders:

- [x] admin - 16 usages https://github.com/metabase/metabase/pull/18409
- [x] auth - 2 usages https://github.com/metabase/metabase/pull/18459
- [ ] components - 10 usages https://github.com/metabase/metabase/pull/18460
- [ ] containers - 8 usages
- [ ] dashboard - 8 usages
- [ ] entities - 5 usages
- [ ] hoc - 9 usages
- [ ] home - 2 usages
- [ ] modes - 3 usages
- [ ] nav - 2 usages
- [ ] new_query - 1 usages
- [ ] parameters - 3 usages
- [ ] public - 5 usages
- [ ] pulse - 2 usages
- [ ] query_builder - 33 usages
- [ ] reference - 34 usages
- [ ] setup - 1 usage
- [ ] visualizations - 14 usages
