### ISSUE TITLE
Parameters Refactor/Cleanup

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#18404]
The FE implementation of parameters is overly complex and could use some rethinking to reduce incidental and accidental complexity. Currently, there are 103 open and 259 closed issues with the "Querying/Parameters & Variables" label. Looking at the parameters bugs that have been fixed over the past year or two, you will see a common pattern -- that the relation between parameters and the fields/dimensions a parameter is associated with is frequently deficient and/or broken. This project will focus on clarifying this relation and simplifying surrounding code to make parameters a simpler part of the codebase.

**Links**
https://github.com/metabase/metabase/issues?q=is%3Aopen+is%3Aissue+label%3A%22Querying%2FParameters+%26+Variables%22

**Implementation Plan**

***Reorganize parameters code*** 
- [x] Split `metabase/meta/*` files into smaller, more focused utility modules

***UI Refactor***
- [x] `Parameters` component refactor
- ~[nice-to-have] Split parameter edit state into separate components~ will tackle in future work
- [x] Remove `parameterValue` normalization code from parameters UI components  (partially done by #18683)
- ~Refactor operator logic in `ParameterFieldWidget` to look more like `Filter` logic in query builder~ will tackle in future work

***Biz logic***
- [x] match dashboard & card parameter data structures (#18721)
- [x] access parameter targets via Dimensions (#18431)
- ~Make `parameters` first class in dashboard/query_builder redux stores~ edit: punting for now

**Comment by daltojohnso** [comment]
Removing "Make `parameters` first class in redux" for now as solidifying the data structure building functions in `metabase/parameters/utils/cards` and `metabase/parameters/utils/dashboards` seems adequate for now, and I think focusing on logic around using `Filter` would be a better use of time.

**Comment by camsaul** [comment]
#15456 is relevant here too
