### ISSUE TITLE
Add storybook

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#18410]
This epic is to track work on adding Storybook to Metabase. The plan:

- [x] Add empty Storybook
- [x] Deploy storybook to chromatic
- [x] Migrate a demo from our internal page to Storybook
