### ISSUE TITLE
Revamp custom expression editor

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#18647]
Relevant previous work (for context):

* [x] #15839
* [x] #15897

User-facing improvements:
* [x] #15688
* [x] #18744
  * [x] #19024 
* [x] #18919
* [x] #19129 
  * [x] Ctrl+Arrow to move between words
  * [x] Shift+Arrow to select characters
  * [x] Undo and Redo 
* [x] #19520

Behind the scene:

* [x] #18482
* [x] #18720
* [x] Switch to lexical-based completion (covered in #15688)
* [x] #18773
* [x] #19100
* [x] #19187
  * [x] #19305
  * [x] #19320
  * [x] #19395
* [x] #19335
  * [x] #19438 
* [x] #19408
* [x] #19557

Quality improvements and hardening:

* [x] #18586
* [x] #18841
* [x] #18969
  * [x] ##19033 
* [x] #18942
* [x] #19068

Other related issues being addressed:

* [x] #16094
* [x] #12121
* [x] #13469
* [x] #14776
* [x] #14791
* [x] #15741
