### ISSUE TITLE
Data Modeling: Datasets

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#18659]
## Data Modeling: Datasets

Ability to used saved datasets as the source of a query. Initial deliverable is to use the saved-questions functionality and create a UX that promotes and eases their use.

**Links**
- [product doc](https://www.notion.so/metabase/Allow-for-the-creation-and-usage-of-models-7090fa371e4d49d4a6f3260fcb0b4ab2)

### Milestone 1

**Backend**

- [x] Model and add in collection items API: Issue: #18655  PR: #18629 
- [x] Add to query source API: Issue #18656 PR: #18704
- [x] Search: Issue #18657 PR: #18715
- [x] Cleanup of changing to a dataset: revision history and verification issues. See https://github.com/metabase/metabase/pull/18702#pullrequestreview-790937417
- [x] Ensure tree view only contains parents of datasets: Issue #18672 PR: #18833
- [x] mark metadata as from a dataset query PR: #18900 

**Frontend**

- [x] Turn a saved question into a dataset and display it in collections (#18702)
- [x] Add "Datasets" section to query builder's data picker (#18764)

### Milestone 2

**Frontend**

- [x] Distinct UI for dataset page (#18993)
- [x] Ability to undo turning a question into a dataset (#18855)
- [x] New UI for creating things inside a collection (plus icon) (#19009)
- [x] Turn a dataset back into a saved question (#18873)
- [x] Distinct URLs for dataset pages (#19032)
- [x] Ensure dataset picker only shows collections with datasets (#19153)

**Backend**

- [x] Audit and correct analytics. Things like card-read, card-edit.
- [x] dismissed modal state: Issue #18658, PR: #18926
- [x] datasets in activity admin page: #18967 

### Milestone 3

**Frontend**
- [x] Implement basic query editor (#19103)
- [x] Implement metadata editor (#19774)

**Backend**
- [x] datasets preserve metadata (https://github.com/metabase/metabase/pull/19158)

### Misc / Polish

- [x] Fix revision history messages when a question is turned into a dataset and vice-versa (#18875)
- [x] Display datasets correctly in recent searches (#18987)
- [ ] Data selector: skip raw data step when there is only one database when navigating back from a selected table
- [x] Data selector: when opening the selector with a dataset selected, "Saved Questions" opens instead of "Datasets"
- [ ] Show if a dataset is in an official collection (maybe also show if a question is based on an official dataset)
- [x] Disallow creating datasets based on native questions using variables
- [x] Add a warning icon to questions built on archived datasets
- [x] List datasets together with questions when adding things to dashboards
- [ ] Cleanup data selector UI (comments from Maz)
- [x] Verify dataset UI
- [x] Handle databases without nested queries support
- [x] Should be possible to pick a Dataset as a target when configuring click behavior on a dashboard card ([Slack converation](https://metaboat.slack.com/archives/C0228TSGC1X/p1641420280002300))

**Comment by rcronin** [comment]
I noticed that the datasets essentially turn the underlying query into a subselect when adding filters, joins, etc. to it. How is it going to be handled when the query for a dataset needs to be filtered from a variable? Specific scenario would be when the base of a dataset is a native sql question and there's a variable for a date filter?

**Comment by flamber** [comment]
@rcronin It's currently not supported to pass-thru variables: #6449

**Comment by rcronin** [comment]
> @rcronin It's currently not supported to pass-thru variables: #6449

Will it be supported at some point? This would be extremely valuable feature and seems to be noted that way in the issue referenced.

**Comment by flamber** [comment]
@rcronin I cannot tell you if or when, but upvote the issue by clicking :+1: on the first post. And follow the roadmap: https://www.metabase.com/roadmap/
