### ISSUE TITLE
Static visualizations for 42

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#18676]
[Product doc](https://www.notion.so/metabase/Iterate-on-Improved-Static-Viz-from-41-d99ea3a5c068466eb8fa694e95f80ef4)

It is the epic for improvements and new visualization types. In the current iteration, we want to fix issues with existing static visualizations and add multiple new ones.

### Polishing
- [x] https://github.com/metabase/metabase/issues/18677 — FE
- [x] https://github.com/metabase/metabase/issues/18678 — BE
- [x] https://github.com/metabase/metabase/issues/18679 — BE
- [x] https://github.com/metabase/metabase/issues/18755 — BE (backport)
- [x] https://github.com/metabase/metabase/issues/19025 — BE
- [x] https://github.com/metabase/metabase/issues/19248 — BE
- [x] https://github.com/metabase/metabase/pull/19249 — FE
- [x] Funnels are not rendering — BE (https://github.com/metabase/metabase/pull/19983)
- [x] https://github.com/metabase/metabase/pull/19702 — FE
- [x] Choose Y-axis position from visual settings or based on series data — BE
- [x] Fix bar charts are not rendering in our `pod-cloud` channel — BE
- [x] Waterfall chart does not support "Show Total" setting — BE
- [x] Waterfall chart does not support changing colors of bars — BE

### Fix limitations of already implemented charts
- [x] https://github.com/metabase/metabase/issues/18782 (https://github.com/metabase/metabase/pull/19151) — BE
- [x] https://github.com/metabase/metabase/issues/18783 — FE

#### Area
- [x] https://github.com/metabase/metabase/issues/18687 (https://github.com/metabase/metabase/pull/19306) — BE
#### Combo
- [x] https://github.com/metabase/metabase/issues/18688 — FE
- [x] https://github.com/metabase/metabase/issues/18689 — BE
#### Waterfall
- [x] https://github.com/metabase/metabase/pull/18885 — FE
- [x] Support waterfall chart renderer (https://github.com/metabase/metabase/pull/18915) — BE
#### Progress
- [x] https://github.com/metabase/metabase/pull/18884 — FE
- [x] Support progress chart renderer (https://github.com/metabase/metabase/pull/18945) — BE
#### Funnel
- [x] https://github.com/metabase/metabase/pull/19106 — FE
- [x] Support funnel chart renderer (https://github.com/metabase/metabase/pull/19172) — BE

#### Future Work / Bug fixes if time
 - https://github.com/metabase/metabase/issues/2342 — BE

**Comment by howonlee** [comment]
I think the bar charts are not showing in `#pod-cloud` channel in MB internal slack because the queries are borked because the underlying DB's changed or something, or at least I can't get the queries to show on our stats metabase instance, and without that I can't do much in static viz-land

**Comment by howonlee** [comment]
I've wailed at the "funnels are not rendering" thing and I can't repro for love nor money, so unless there's a coherent tix with an actual series of repro steps I don't even know if this problem exists or not

**Comment by rlotun** [comment]
> I've wailed at the "funnels are not rendering" thing and I can't repro for love nor money, so unless there's a coherent tix with an actual series of repro steps I don't even know if this problem exists or not

Fwiw I did a 5 min double check of the funnel stuff and it's a mixed bag. I created https://stats.metabase.com/dashboard/527-test-funnel which looks like:

![Screen Shot 2022-01-25 at 2 25 17 PM](https://user-images.githubusercontent.com/65313/151069962-bddecc2b-b2d3-42a2-9736-e28a0e8e3b97.png)

and then sent myself a dashboard subscription over email and I got this:
![Screen Shot 2022-01-25 at 2 25 47 PM](https://user-images.githubusercontent.com/65313/151070021-2f85d828-4626-4d15-8648-94a4079c902f.png)

**Comment by alxnddr** [comment]
@howonlee from Reza's screenshot, it also looks like we static viz rendering environment does not include font Lato with font-weight=700

**Comment by rlotun** [comment]
I tried this again on stats (running commit f326f53 which should contain https://github.com/metabase/metabase/pull/19983) using the dashboard https://stats.metabase.com/dashboard/527-test-funnel and I still don't get the second funnel rendered in the email:

<img width="606" alt="Screen Shot 2022-01-31 at 9 53 21 PM" src="https://user-images.githubusercontent.com/65313/151919503-434aa02b-6a9e-4b07-819e-3f972f6f127d.png">

**Comment by rlotun** [comment]
FWIW noticed this in stats logs - hopefully this helps!

```
[0814fbd7-4156-4c36-94df-8fcd86ac84eb] 2022-01-31T21:48:53-08:00 DEBUG metabase.server.middleware.log POST /api/dashboard/527/card/532/query 202 [ASYNC: completed] 456.1 ms (21 DB calls) App DB connections: 2/4 Jetty threads: 2/50 (4 idle, 0 queued) (137 total active threads) Queries in flight: 0 (0 queued)
[cc85076c-76c6-4d11-9124-21faac8482eb] 2022-01-31T21:49:55-08:00 DEBUG metabase.server.middleware.log GET /api/pulse 200 4.7 ms (1 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (99 total active threads) Queries in flight: 0 (0 queued)
[cc85076c-76c6-4d11-9124-21faac8482eb] 2022-01-31T21:49:55-08:00 DEBUG metabase.server.middleware.log GET /api/user 200 45.4 ms (4 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (99 total active threads) Queries in flight: 0 (0 queued)
[0814fbd7-4156-4c36-94df-8fcd86ac84eb] 2022-01-31T21:49:55-08:00 DEBUG metabase.server.middleware.log GET /api/pulse/form_input 200 186.2 ms (0 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (135 total active threads) Queries in flight: 0 (0 queued)
[cc85076c-76c6-4d11-9124-21faac8482eb] 2022-01-31T21:50:01-08:00 INFO metabase.query-processor.card Question's average execution duration is 1.2 s; using 'magic' TTL of 2.1 mins 💾
[cc85076c-76c6-4d11-9124-21faac8482eb] 2022-01-31T21:50:02-08:00 INFO metabase.query-processor.middleware.cache Query took 618.0 ms to run; minimum for cache eligibility is 10.0 s
[cc85076c-76c6-4d11-9124-21faac8482eb] 2022-01-31T21:50:04-08:00 INFO metabase.query-processor.card Question's average execution duration is 2.2 s; using 'magic' TTL of 3.6 mins 💾
[cc85076c-76c6-4d11-9124-21faac8482eb] 2022-01-31T21:50:04-08:00 INFO metabase.query-processor.middleware.cache Query took 326.0 ms to run; minimum for cache eligibility is 10.0 s
[cc85076c-76c6-4d11-9124-21faac8482eb] 2022-01-31T21:50:04-08:00 ERROR metabase.pulse.render Pulse card render error
org.apache.batik.transcoder.TranscoderException: null
Enclosed Exception:
file:///fake.svg:-1
The attribute "points" of the element <polygon> is invalid
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:228)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:158)
	at metabase.pulse.render.js_svg$render_svg.invokeStatic(js_svg.clj:97)
	at metabase.pulse.render.js_svg$render_svg.invoke(js_svg.clj:87)
	at metabase.pulse.render.js_svg$svg_string__GT_bytes.invokeStatic(js_svg.clj:101)
	at metabase.pulse.render.js_svg$svg_string__GT_bytes.invoke(js_svg.clj:100)
	at metabase.pulse.render.js_svg$funnel.invokeStatic(js_svg.clj:127)
	at metabase.pulse.render.js_svg$funnel.invoke(js_svg.clj:121)
	at metabase.pulse.render.body$fn__55296$render__55285__55301$fn__55305.invoke(body.clj:811)
	at metabase.pulse.render.body$fn__55296$render__55285__55301.invoke(body.clj:800)
	at clojure.lang.AFn.applyToHelper(AFn.java:178)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at clojure.lang.MultiFn.invoke(MultiFn.java:261)
	at metabase.pulse.render$fn__55571$render_pulse_card_body__55576$fn__55580.invoke(render.clj:142)
	at metabase.pulse.render$fn__55571$render_pulse_card_body__55576.invoke(render.clj:132)
	at metabase.pulse.render$fn__55610$render_pulse_card__55615$fn__55616.invoke(render.clj:168)
	at metabase.pulse.render$fn__55610$render_pulse_card__55615.invoke(render.clj:156)
	at metabase.pulse.render$fn__55639$render_pulse_section__55644$fn__55648$fn__55651.invoke(render.clj:200)
	at metabase.pulse.render$fn__55639$render_pulse_section__55644$fn__55648.invoke(render.clj:198)
	at metabase.pulse.render$fn__55639$render_pulse_section__55644.invoke(render.clj:195)
	at metabase.email.messages$render_result_card.invokeStatic(messages.clj:411)
	at metabase.email.messages$render_result_card.invoke(messages.clj:408)
	at metabase.email.messages$render_message_body$fn__56850$fn__56851.invoke(messages.clj:459)
	at clojure.core$mapv$fn__8468.invoke(core.clj:6914)
	at clojure.core.protocols$fn__8181.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8181.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8136$G__8131__8145.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8168.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8168.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6830)
	at clojure.core$mapv.invokeStatic(core.clj:6905)
	at clojure.core$mapv.invoke(core.clj:6905)
	at metabase.email.messages$render_message_body$fn__56850.invoke(messages.clj:459)
	at metabase.email.messages$render_message_body.invokeStatic(messages.clj:458)
	at metabase.email.messages$render_message_body.invoke(messages.clj:456)
	at metabase.email.messages$render_pulse_email.invokeStatic(messages.clj:485)
	at metabase.email.messages$render_pulse_email.invoke(messages.clj:482)
	at metabase.pulse$fn__75288.invokeStatic(pulse.clj:279)
	at metabase.pulse$fn__75288.invoke(pulse.clj:268)
	at clojure.lang.MultiFn.invoke(MultiFn.java:239)
	at metabase.pulse$results__GT_notifications$iter__75318__75322$fn__75323.invoke(pulse.clj:331)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5419.invokeStatic(core.clj:139)
	at clojure.core$seq__5419.invoke(core.clj:139)
	at metabase.pulse$send_notifications_BANG_.invokeStatic(pulse.clj:373)
	at metabase.pulse$send_notifications_BANG_.invoke(pulse.clj:372)
	at metabase.pulse$send_pulse_BANG_.invokeStatic(pulse.clj:401)
	at metabase.pulse$send_pulse_BANG_.doInvoke(pulse.clj:381)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at metabase.api.pulse$fn__76260.invokeStatic(pulse.clj:211)
	at metabase.api.pulse$fn__76260.invoke(pulse.clj:197)
	at compojure.core$wrap_response$fn__32309.invoke(core.clj:160)
	at compojure.core$wrap_route_middleware$fn__32293.invoke(core.clj:132)
	at compojure.core$wrap_route_info$fn__32298.invoke(core.clj:139)
	at compojure.core$wrap_route_matches$fn__32302.invoke(core.clj:151)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32302.invoke(core.clj:153)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32302.invoke(core.clj:153)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32302.invoke(core.clj:153)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32302.invoke(core.clj:152)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321.invoke(core.clj:200)
	at metabase.server.middleware.auth$enforce_authentication$fn__65807.invoke(auth.clj:14)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321.invoke(core.clj:200)
	at compojure.core$make_context$handler__32349.invoke(core.clj:289)
	at compojure.core$make_context$fn__32353.invoke(core.clj:299)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:199)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:199)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321.invoke(core.clj:200)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:199)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321.invoke(core.clj:200)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321.invoke(core.clj:200)
	at metabase.api.routes$fn__76818$fn__76819.invoke(routes.clj:54)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321.invoke(core.clj:200)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at metabase.server.routes$fn__76963$fn__76964.doInvoke(routes.clj:57)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321.invoke(core.clj:200)
	at compojure.core$make_context$handler__32349.invoke(core.clj:289)
	at compojure.core$make_context$fn__32353.invoke(core.clj:299)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32302.invoke(core.clj:153)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32302.invoke(core.clj:153)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$wrap_route_matches$fn__32302.invoke(core.clj:153)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:199)
	at compojure.core$routes$fn__32321$f__32322$respond_SINGLEQUOTE___32323.invoke(core.clj:197)
	at compojure.core$make_context$fn__32353.invoke(core.clj:300)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321.invoke(core.clj:200)
	at compojure.core$routes$fn__32321$f__32322.invoke(core.clj:198)
	at compojure.core$routes$fn__32321.invoke(core.clj:200)
	at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__73984.invoke(exceptions.clj:98)
	at metabase.server.middleware.exceptions$catch_api_exceptions$fn__73981.invoke(exceptions.clj:86)
	at metabase.server.middleware.log$log_api_call$fn__79027$fn__79028$fn__79029.invoke(log.clj:209)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:15)
	at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:9)
	at metabase.server.middleware.log$log_api_call$fn__79027$fn__79028.invoke(log.clj:201)
	at toucan.db$_do_with_call_counting.invokeStatic(db.clj:216)
	at toucan.db$_do_with_call_counting.invoke(db.clj:209)
	at metabase.server.middleware.log$log_api_call$fn__79027.invoke(log.clj:200)
	at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__84418.invoke(browser_cookie.clj:38)
	at metabase.server.middleware.security$add_security_headers$fn__59645.invoke(security.clj:148)
	at metabase.server.middleware.json$wrap_json_body$fn__81729.invoke(json.clj:62)
	at metabase.server.middleware.json$wrap_streamed_json_response$fn__81747.invoke(json.clj:98)
	at metabase.server.middleware.offset_paging$handle_paging$fn__59669.invoke(offset_paging.clj:42)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__84685.invoke(keyword_params.clj:55)
	at ring.middleware.params$wrap_params$fn__84701.invoke(params.clj:69)
	at metabase.server.middleware.misc$maybe_set_site_url$fn__34402.invoke(misc.clj:59)
	at metabase.server.middleware.session$bind_current_user$fn__45738$fn__45739.invoke(session.clj:262)
	at metabase.server.middleware.session$do_with_current_user.invokeStatic(session.clj:243)
	at metabase.server.middleware.session$do_with_current_user.invoke(session.clj:235)
	at metabase.server.middleware.session$bind_current_user$fn__45738.invoke(session.clj:261)
	at metabase.server.middleware.session$wrap_current_user_info$fn__45725.invoke(session.clj:221)
	at metabase.server.middleware.session$wrap_session_id$fn__45711.invoke(session.clj:167)
	at metabase.server.middleware.auth$wrap_api_key$fn__65815.invoke(auth.clj:27)
	at ring.middleware.cookies$wrap_cookies$fn__84605.invoke(cookies.clj:216)
	at metabase.server.middleware.misc$add_content_type$fn__34385.invoke(misc.clj:27)
	at metabase.server.middleware.misc$disable_streaming_buffering$fn__34410.invoke(misc.clj:76)
	at ring.middleware.gzip$wrap_gzip$fn__84647.invoke(gzip.clj:86)
	at metabase.server.middleware.misc$bind_request$fn__34413.invoke(misc.clj:93)
	at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__84434.invoke(ssl.clj:48)
	at metabase.server$async_proxy_handler$fn__78800.invoke(server.clj:73)
	at metabase.server.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.batik.bridge.BridgeException: file:///fake.svg:-1
The attribute "points" of the element <polygon> is invalid
	at org.apache.batik.bridge.SVGPolygonElementBridge.buildShape(SVGPolygonElementBridge.java:100)
	at org.apache.batik.bridge.SVGShapeElementBridge.createGraphicsNode(SVGShapeElementBridge.java:60)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:213)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
	at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
	at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:210)
	... 248 more
[cc85076c-76c6-4d11-9124-21faac8482eb] 2022-01-31T21:50:05-08:00 DEBUG metabase.server.middleware.log POST /api/pulse/test 200 4.9 s (52 DB calls) App DB connections: 0/4 Jetty threads: 3/50 (4 idle, 0 queued) (103 total active threads) Queries in flight: 0 (0 queued); redshift DB 48 connections: 0/1 (0 threads blocked)


```

**Comment by howonlee** [comment]
Yeah, I noted this this afternoon and am working on it

**Comment by rlotun** [comment]
moving some of the tricky bugfixes here to 42.1
