### ISSUE TITLE
Surface table and column metadata in question creation and consumption

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#18738]
This epic adds "hovercards" to lists of things like fields and tables found through the application.

**Links**
- product doc: https://www.notion.so/metabase/Surface-table-and-column-metadata-in-question-creation-and-consumption-84d9afae4a70499a8839712927c5bd03
- eng doc: https://www.notion.so/metabase/Surface-table-and-column-metadata-in-question-creation-and-consumption-2d91c9d6765648db9b3978cda725eaa7

**Implementation Plan**

***Milestone 1 -- build basic UI components*** 
- [x] build field/dimension hover card  (https://github.com/metabase/metabase/pull/18819)
- [x] build table hover card (https://github.com/metabase/metabase/pull/18940) 
- [x] Get a basic `tippy.js` popover in the app that can support interactive hover popovers (see https://github.com/metabase/metabase/issues/18951)

***Milestone 2 -- fully flesh out metadata UI components***
- [x] add "fingerprint" metadata to info cards #19280

***Milestone 2.1 -- add Table metadata card***
- [x] Add table metadata hovercard #19322  

***Milestone 2 -- implement hovercards throughout the application***
- [x] add ability to wrap `AccordionList` items in popovers #19279 
- [x] add `DimensionInfoPopover` to table column headers in query builder #19350 
- [x] add `DimensionInfoPopover` to the lists of fields/dimensions found in the query builder (the summarize & filter side bars for simple questions, and the filter, summarize, and group by popovers in custom questions) #19286 #19288 #19287 
- [x] add `DimensionInfoPopover` to native query builder template tag field filter field picker component #19284
- [x] add table info popover to table cards found on the `/browse` route #19322 
- [x] add table info popover to the data selector dropdowns found on `/question/new` and the field filter picker in the template tag sidebar in the native query editor #19468 
- [x] add table info popover to data selector search #19468
- [x] add table info popover to the table references in the query builder header (saved and unsaved) #19468
- [x] replace the UI in the native query editor reference UI with `DimensionInfo` & `TableInfo` UI #19468 #19455 

~***Milestone 3 -- edit metadata through hovercard***~
~tbd; implementation depends on dataset metadata editing, I think.~

**How to Test This Feature Out**
Navigate to one of the many places referenced above and hover your mouse over the specified component.
