### ISSUE TITLE
Replace our Popover with tippy.js and @tippyjs/react

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#18951]
The "surface metadata" project (linked below) describes popover functionality (interactivity on hover, specifically) that our current `Popover.jsx` does not support. Instead of adding more to our home-baked Popover implementation, this seems like a good opportunity to introduce a more robust third party popover library, tippy.js.

**Links**
https://www.notion.so/metabase/Surface-table-and-column-metadata-in-question-creation-and-consumption-84d9afae4a70499a8839712927c5bd03
https://www.notion.so/metabase/17-Reimplement-Popover-using-tippy-js-41f4714c6c7d49108141c47e0e4586ed
https://github.com/metabase/metabase/issues/18738

**Implementation Plan**

***Milestone 1*** get tippyjs into the codebase
- [ ] reimplement tooltips using tippyjs
- [ ] implement a popover component that is usable by the "surface metadata" project

***Milestone 2*** fully replace popover
- [ ] fully reimplement `Popover` functionality using tippyjs
- [ ] remove `Tether` from the codebase
- [ ] product tweaks?

**How to Test This Feature Out**
todo

**Comment by daltojohnso** [comment]
### PopoverWithTrigger migration notes

NOTE: this is a work in progress. In addition, this will likely be expanded on as we work through the migration

**PopoverWithTrigger has been replaced by two components**
In nearly all scenarios you should use the `TippyPopoverWithTrigger` component, as it takes care of handling the visibility state of the popover for you, and you can still, if needed, control the closing of the popover by passing a function with the args `{ closePopover: () => void; }` to the `popoverContent` prop of `TippyPopoverWithTrigger`.

There a few (maybe one) instances of a parent component directly controlling the state of its child PopoverWithTrigger, so I've created a `ControlledPopoverWithTrigger` (that TippyPopoverWithTrigger depends upon internally) to handle those few scenarios.

**triggerElement has been replaced by two props, renderTrigger and triggerContent**
`renderTrigger` for full control over the trigger element
`triggerContent` which excepts a `ReactNode` and wraps it in a `Button`

**The children prop has been replaced by popoverContent**

**Has a ref been added to the `PopoverWithTrigger` instance?**
I think in most scenarios where a ref has been added to an old popover it will be on a `PopoverWithTrigger` so that the parent component can access the `close` method that exists in the `PopoverWithTrigger` component. As a replacement for this, the `popoverContent` prop of `TippyPopoverWithContent` accepts a function with the args `{ closePopover: () => void; }`. You can then use the `closePopover` function within the content of your popover to close itself.

**The placement prop**
The new `TippyPopoverWithTrigger` defaults to a `placement` prop of `"bottom-start"` but this might not make sense in all scenarios. If the popover is opened from a **right** sidebar or is near the right edge of the screen, you probably want to change the `placement` to `"bottom-end"`

**The `pinInitialAttachment` prop**
This prop has been removed from the new TippyPopover. If you find a need for it, please let @daltojohnso know. Otherwise, remove the prop when migrating.

**The `autoWidth` prop**
This prop is no longer implemented directly. Instead, you should be able to use tippy's `maxWidth` prop. Read more here: https://atomiks.github.io/tippyjs/v6/all-props/#maxwidth

**The `hasArrow` prop**
Feel free to remove. It wasn't ever actually set to `true` in our codebase.

**`targetOffsetY` and `targetOffsetX`**
Replace these props with the `offset` prop.

**Comment by daltojohnso** [comment]
### Popover migration notes

todo :)
