### ISSUE TITLE
Migrate shared components to TypeScript

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#19268]
This epic is to track work for migrating our shared components. When you start migrating a component, add a (draft) PR to the list so none would start migrating it in parallel.

- [x] Button https://github.com/metabase/metabase/pull/19237
- [x] Link https://github.com/metabase/metabase/pull/19237
- [x] ExternalLink https://github.com/metabase/metabase/pull/19237
- [x] LoadingSpinner https://github.com/metabase/metabase/pull/19237
- [ ] ...

Important: do not migrate `Popover` as it will be replaced by `TippyPopover`.
