### ISSUE TITLE
Implement advanced date/time/timezone manipulation

### ISSUE THREAD

**Issue by jeff303** [metabase/metabase#19274]
This is an epic to track implementation of advanced date/time/timezone manipulation.

**Links**
- [product doc](https://www.notion.so/metabase/Unlock-advanced-date-time-manipulation-038f5cf80f364d7cb93341784169743c)
- eng doc: N/A
- feature branch: N/A (to be stacked on `master`)
- Issue links: TBD

**Implementation Plan**

1. Add extraction (`day`, `quarter`, etc.) MBQL functions and tests 
2. Add `dateDiff` MBQL function and tests
3. Add `dateAdd` and `dateSubtract` MBQL functions and tests
4. Add `convertTimezone` MBQL function and tests
5. Add `now` MBQL function and tests
6. Ensure "litmus tests" from the product doc are covered by integration tests (preferably Cypress)

***Milestone 1*** )
- [x] step 1: add `get-xyz` MBQL function/tests https://github.com/metabase/metabase/pull/25277
  - [x] get-week: https://github.com/metabase/metabase/pull/25778
- [x] step 2: add `dateDiff` MBQL function/tests https://github.com/metabase/metabase/issues/26999
- [x] step 3: https://github.com/metabase/metabase/pull/25414
- [ ] step 4: Convert timezone
  - [x] https://github.com/metabase/metabase/pull/25698
  - [x] https://github.com/metabase/metabase/pull/25790
  - [x] https://github.com/metabase/metabase/pull/26633
  - [ ] Accepts "instance" and "user" as timezone argument
  - [ ] Accepts a column as timezone argument
- [ ] step 5: add litmus integration tests

**How to Test This Feature Out**

TBD

Related to #16870 and #7614

**Comment by mazameli** [comment]
@qnkhuat mentioned today that there may be some work to do around making years render without commas, but @dpsutton thinks it may be a bit wider in scope than it seems.

Maz asked how we do this for IDs that are stored as ints, since we don't have separators there.

**Comment by dpsutton** [comment]
a quick note about the wider scope: excel, csv, json downloads.

**Comment by qnkhuat** [comment]
Note for drivers support for convert-timezone:
- sqlite, mongo, doesn’t have timestamptz,
   maybe we could figure out a way to make it works for 3 args version where it takes a `timestamp with out time zone` column
- h2: it only has support for `timestamp with time zone` for h2 v1.4.200, and we were using v1.4.199 at the time of implementation. now we upgraded to v2.1 so it should be easy to implement.
- gganalytics doesn’t have datetime type.
- sparksql: [slack thread](https://metaboat.slack.com/archives/C03TJGCQGJ0/p1669184333065819?thread_ts=1669134358.095319&cid=C03TJGCQGJ0)
- athena: could support, but didn't add support for it at the time because it's added in 45 as well.
- presto: can’t remember exactly but there is some problem with how convert-tz works in presto and I couldn’t make it work nicely with how we format DateTime and report-tz. 
- druid: I remember researching about it and IIRC it doesn’t have function to convert tz.

**Comment by e-gaulue** [comment]
Is the addtion of TODAY(), NOW() or whatever name in custom expression is covered by this issue?

**Comment by calherries** [comment]
Yes, the `now()` function was missing from this issue's description. It will be included in the next major release (46). I'm closing this issue as completed.
