### ISSUE TITLE
Clean Up Settings Navigation

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#19348]
Clean up settings navigation

**Links**
- product doc: https://www.notion.so/metabase/Clean-up-settings-navigation-a85a0aff236d419c8681a03e6dbcaec2

**Implementation Plan**

- [x] change navbar UI: https://github.com/metabase/metabase/pull/19304
- [x] https://github.com/metabase/harbormaster/issues/2412
- [x] remove enterprise page: https://github.com/metabase/metabase/pull/19343

This epic should also close the following 'bug':
- https://github.com/metabase/metabase/issues/18153

**How to Test This Feature Out**

TBD
