### ISSUE TITLE
Improve Filters for 42

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#19354]
There are many ways to improve and make the basics of filtering amazing on Metabase. That cuts across a couple main axes:
 - The absence of bugs
 - The fluidity of the UI
 - The expressivity of the widgets

This project aims to group and tackle many of the shortcoming and opportunities we see around filtering specifically, because it's one of the most important and frequent parts of querying and it's overwhelmingly focused on the GUI query builder, with some attention paid to Dashboard filters, but little to SQL Editor filter variables.

**Links**
- product doc: https://www.notion.so/metabase/Bring-joy-to-filtering-50531005d4584c19bcb2a531c6771aa8

**Implementation Plan**
- [x] Clean up the Boolean filter widget https://github.com/metabase/metabase/pull/18950
- [x] prevent un-necessary requests across filter interactions: https://github.com/metabase/metabase/pull/19479
- [x] Add support expression for time-interval clause: https://github.com/metabase/metabase/pull/19054
- [x] Support Quarters as a Filter Unit https://github.com/metabase/metabase/pull/18970
- [x] Ensure all strings in filters are localized https://github.com/metabase/metabase/pull/18943
- [x] Make dashboard single-filter use the calendar date selector https://github.com/metabase/metabase/pull/19360
- [x] Re-flow the between picker layout https://github.com/metabase/metabase/pull/19365
- [x] Prevent unnecessary requests across filter interactions #16103 PR: 
- [x] Use checkboxes for category filtering #17383 PR: https://github.com/metabase/metabase/pull/19467
- ~Support keyboard navigation in filter widgets~ -> punting to 43 considering size of change

**How to Test This Feature Out**

TBD
