### ISSUE TITLE
[Epic] Clean up LDAP and Google auth set-up experience

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#19428]
### Links
Product doc: https://www.notion.so/metabase/Clean-up-LDAP-and-Google-auth-set-up-experience-7499d138cf9845f9ab0b8fa459c1a7e1

### Fixes
- https://github.com/metabase/metabase/issues/5555
- https://github.com/metabase/metabase/issues/16225
- https://github.com/metabase/metabase/issues/16363

#### Milestone 1 - LDAP
- [x] BE - https://github.com/metabase/metabase/pull/25421
- [x] FE - https://github.com/metabase/metabase/pull/25439

#### Milestone 2 - Google Auth
- [x] https://github.com/metabase/metabase/pull/25519
- [x] FE - Add the Google Auth toggle to the card

#### Milestone 3 - JWT/SAML
- [x] BE - Add `-enabled` settings for these auth methods
- [x] FE - Change these forms to have `Save and enable` / `Save and don't enable` submit methods

### API changes

Expose the following settings:
- `ldap-configured` - readonly setting; set to true when ldap settings have been validated and saved
- `ldap-enabled` - can be changed only when `ldap-configured` is `true`
- `google-auth-configured` - readonly setting; set to true when google auth settings have been validated and saved
- `google-auth-enabled` -  can be changed only when `google-auth-configured` is `true`

Change `POST /api/ldap/settings`
- Remove `ldap-enabled` check, settings should be always validated
- Set `ldap-configured` to true when saved successfully
- Set `ldap-enabled` to true as well when previously `ldap-configured` was false

Add `POST /api/google_auth/settings`
- Accept `google-auth-client-id` and `google-auth-auto-create-accounts-domain`
- Perform the same validation when these settings are changed with `/api/setting`
- Set `google-auth-configured` to true when saved successfully
- Set `google-auth-enabled` to true as well when previously `google-auth-configured` was false
