### ISSUE TITLE
[Epic] Migrate Slack implementation from Bot to App

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#19435]
**Links**
- Product doc: https://www.notion.so/metabase/Migrate-Slack-implementation-from-Bot-to-App-04c9742e05074b7a84146e4c81b69c7f
- Issue links: 
  - https://github.com/metabase/metabase/issues/12383
  - https://github.com/metabase/metabase/issues/5380
  - https://github.com/metabase/metabase/issues/5236
  - https://github.com/metabase/metabase/issues/18774

**Implementation Plan**
* [ ] Remove Metabot functionality 
* [x] Switch new Slack connections to using apps instead of bots
* [x] [TBD] Update Slack connection form on the frontend
* [ ] [Optional for 42 release] Switch to a 1-click Slack connection flow for hosted instances

**Comment by GJMcClintock** [comment]
Thanks for working on this - I've been banging my head against the wall trying to get it set up with the bot that just was not cooperating.

**Comment by GJMcClintock** [comment]
@ranquild - was this changed bot included in the latest release?

**Comment by flamber** [comment]
@GJMcClintock No, milestone 0.42 - see the sidebar of the issue to get a quick overview.
