### ISSUE TITLE
Update `datasets` references to `models`

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#19668]
The product and the design teams have decided to officially use the term `models` instead of a slightly broader term `datasets`. Since the implementation of this feature is already half-way through, we need to update those references in many different places.

- [x] GitHub label
- [x] e2e tests (#19703)
- [x] Copy (#19675)
    - [x] Part of this is #19630
- [x] Assets (icons, illustrations) (#19676)

TBD
- [ ] Code
    - [x] IMPORTANT feature - route `/dataset/${id}`! (#19730)
    - [ ] question methods
    - [ ] helper functions
    - [ ] file names
    - [ ] unit tests
    - [ ] ...

**Comment by nemanjaglumac** [comment]
Speaking with @kulyk and @ranquild about this and any further renaming is out of scope and will probably never be updated because of contracts between FE and BE. It's safe to close this issue now.
