### ISSUE TITLE
New pinned collection overview section

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#19758]
This project adds a beefier UI for pinned items in our collection view so that models can stand out more. Replaces the UI that current exists for pinned items, a separate table for the pinned items situated above other items in the collection, with a section of the page containing a distinct card for each pinned item.

**Links**
- product doc: https://www.notion.so/metabase/Make-it-easier-to-discover-understand-and-explore-models-from-a-collection-a9d35738fc85452cb17d78fd674c912b
- eng doc: https://www.notion.so/metabase/New-pinned-collection-overview-section-d96591c868324343bdd1892e8978c9f2

**Implementation Plan**

***Milestone 1*** _Replace current UI for pinned items with the new card section_
- [x] create a card component (#19765)
- [x] replace the pinned items table with a pinned items overview section (#19787)
- [x] tests/storybook components

***Milestone 2*** _UI polish_
- [x] misc collections page changes
- [x] add the empty pinned section banner
- [x] add the empty collection UI
- [x] tests/storybook components

***Milestone 3*** _Add card visualizations to the overview_
- [x] add new card viz component for the collection overview
- [x] replace the card card added in milestone 1
- [x] tests

***Milestone 4*** _Additional really-should-haves_
- [ ] automatically pin _new_ dashboards and questions converted to models
- [x] separate button for the pin action in unpinned collection items
- [x] other minor collection viz tweaks per mocks/product doc
- [x] tests

***Milestone 5*** _drag and drop reordering_
- [x] add ability to reorder pinned items via drag and drop

**Testing**
- create a new collection. The empty state should show a new banner informing the user that they can pin items. 
- add questions and dashboards and models to the collection. The banner should persist until the user has pinned an item.
- pin a dashboard. A card for the dashboard should show up. The card should be draggable to the left sidebar to move it to a different folder. Clicking the card should take the user to the dashboard. Hovering over the card should show an action menu in the top right corner of the card. Test all the various actions, unpinning, duplicating, archiving, and moving. 
- pin a model. It should look very similar to the dashboard card except that it is separated by some label text. Should work the same. Clicking should take user to the model in the query builder. 
- test long descriptions and names for dashboards and models
- Pin a question. The visualization for the question should show sorta like if we were on a dashboard. The entire viz should be clickable to take the user to the saved question. An action menu should show in the top right corner like the dashboard and model cards. Dragging the visualization should show a card for performance reasons 
- the above items should be ordered alphabetically

**Comment by mazameli** [comment]
Should we close this, @daltojohnso?

**Comment by daltojohnso** [comment]
Yep, I'll close it
