### ISSUE TITLE
UI Kit first steps

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#19781]
**Links**
- RFC: [UI Kit](https://www.notion.so/metabase/23-UI-Kit-1e6bfb549c634cea92d0dc58a61cf969)
- Figma: [Core components](https://www.figma.com/file/6QeBS0fOQDF27MXt68oeXe/Core-Components?node-id=789%3A1291)
- Core components A11y epic: https://github.com/metabase/metabase/issues/19696

**Implementation Plan**

- [ ] Move core components into a separate UI Kit folder and create stories for them https://github.com/metabase/metabase/issues/19696
- [ ] Create structural components such as Box, Stack, Flex with spacing from core components Figma
- [ ] Create reusable typography components
- [ ] Mark old duplicated components as deprecated

**Comment by linuws** [comment]
> Great work on the Figma file! It's helping me create Metabase mock-ups for my client to show them what's possible.

This is exactly what I want as well. Fast prototyping before you get started building questions and dashboards. I have requested access to the file. I don't know if that is the correct way to start using the UI Kit, please advise otherwise.

**Comment by MS-CGA** [comment]
As above, also exactly what we want. Have requested access, hope this is still active?
