### ISSUE TITLE
Further revamp of custom expression editor

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#19805]
These are tasks which didn't make it into 42 release, migrated from Epic #18647.

User-facing improvements:
* [x] #42623
* [ ] One-liner function description in the suggestion list
* [x] Position-aware help text for function parameter
* [ ] Auto-generated initial name for custom column/summary
* [x] #20477
* [x] #20485
* [x] #20533

Other related issues being addressed:

* [x] #15894

Behind the scene:

* [x] #20480
