### ISSUE TITLE
Visual Design Cleanup for Headers

### ISSUE THREAD

**Issue by akiselev** [metabase/metabase#19909]
This epic tracks the implementation of the [**Visual Design Cleanup for Headers** (notion doc)](https://www.notion.so/metabase/Visual-Design-Cleanup-for-Headers-3475a1338cb840f28904063553b8ed87)

**Requirements**
* [ ] Filters - #19912
  * Reposition applied filters button to the right side
  * Add filter bar to header toggle by button
  * Update "Filter" and "Summarize" buttons
* [ ] Saved Question Header - #19911
  * Path breadcrumb
  * Move information to side bar
* [ ] Saved Question Sidebar - #19911
  * Show links to backing Data
  * Add Last edit info link that opens timeline
* [ ] Filter header bar animation 
* [ ] Draw circular border w/ connecting line around badges
* [ ] Official collection icon
* [ ] Verified question badge
* [ ] Unsaved Question Header
  * [ ] Data source breadcrumb
* [ ] Dashboard Header
  * [ ] Path breadcrumb
  * [ ] Last edit info text
  * [ ] Update share icon
  * [ ] Break subscriptions out into their own icon
* [ ] Table and datasett header
  * [ ] Remove subtitle
  * [ ] Path breadcrumb in title

**Miscellaneous todo**
* [ ] [Center text vertically in secondary buttons](https://github.com/metabase/metabase/pull/19912#pullrequestreview-865152274)

**Pull Requests**
#19912 
#19911

**Comment by rlotun** [comment]
The original project doc was canceled: https://www.notion.so/metabase/Visual-Design-Cleanup-for-Headers-3475a1338cb840f28904063553b8ed87
