### ISSUE TITLE
Metabase 43 Query Processor Middleware Pattern Overhaul

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#19959]
Related Issues

- [x] #13713 (sort of a similar issue but this is a bit larger in scope)

### Background

Currently all of our Query Processor Middleware has the pattern

```clj
(f (f query rff context)) -> (f query rff context)
```

`query` of course is the MBQL query that we eventually compile to a native query language such as SQL and execute.

`rff` or "reducing-function function" is a function that takes `metadata` and returns a reducing function, e.g.

```clj
(f metadata) -> rf
```

`metadata` is information about the columns in the results (name, type, etc.). This reducing function is used to transduce the result rows that come back when executing the query.  We're using a reducing-function function instead of a plain reducing function here because which columns come back is important in determining which transforms we apply to the reducing function; e.g. a `OffsetDateTime` column means we need to apply a transform to the reducing function to convert that to a string in the `format-rows` middleware. Also this gives middleware the chance to augment the result metadata itself.

`context` contains a handful of callback handlers and `core.async` channels that are used to glue everything together. There are a few pieces of "special" middleware the do "special" things with these, like catch uncaught exceptions and forward them to the async results channel, or listen for cancelation messages and cancel the query execution, etc. But these are outside the scope of this project.

Effectively no-op middleware looks like

```clj
(defn my-middleware [qp]
  (fn [query rff context]
    (qp query rff context)))
```

#### Hackiness

Because all middleware is currently bundled into one massive group, executing just one part of it requires a bit of hackiness. For example, `query->preprocessed` actually overrides the `preprocessedf` function in `context` (basically a callback that gets called right before we call `mbql->native`) to pass a special "quit early exception" to `raisef` (the async exception handler for the QP) whihc immediately terminates the rest of the QP pipeline and return the preprocessed query as-is. It works, but it's hard to explain and I'm not sure anyone else beside me understands it.

### Proposal

Now it just so happens that 95% of our QP middleware either only transforms `query` ("pre-processing middleware") or only transforms `rff` ("post-processing middleware"). We should split out these pieces of common middleware into their own groups so they can be called independently and adopt simpler patterns for them:

1. Pre-proccessing and compilation middleware should have the pattern `(f query) -> query`
2. Post-processing middleware should have the pattern `(f query rff) -> rff`

This will make the most common types of middleware **much** easier to write, test, and use, also allow us to combine all the pre-processing/post-processing functions into single functions via `comp`. In turn, this will shave off ~40 frames from query error stacktraces and allow us to eliminate various hacks like the "quit early exception" entirely, `mt/test-qp-middleware`, and simplify the QP context a bit.

It's actually about ~50% faster too, since it no longer has to set up all the async `context` stuff like the `result-chan` and `canceled-chan` that it ultimately doesn't need.

### Steps

- [x] Split middleware that does **both** pre- and post- processing into separate functions (PR https://github.com/metabase/metabase/pull/19931)
- [x] Split QP middleware into different groups e.g. pre-processing and post-processing (PR https://github.com/metabase/metabase/pull/19935)
- [x] Convert all pre-processing middleware to the new `(f query) -> query` pattern; use an adapter to make them continue to work like the old pattern for now (PR https://github.com/metabase/metabase/pull/19937)
- [x] Remove adapter code from previous step and use new pre-processing middleware directly; rework `query->preprocessed` to just use a `comp`osed version of all the pre-processing functions; remove `preprocessedf` (PR https://github.com/metabase/metabase/pull/19938)
- [x] Rework `query->native` to use a new version of `query->preprocessed` composed with `mbql->native`; remove `nativef`; remove "quit early exception" (PR #20095)
- [x] Convert all post-processing middleware to the new `(f query rff) -> rff` pattern; and use the new post-processing middleware directly; remove `forty-three` adapter code (PR #20096)
- [ ] Update `dev.debug-qp/process-query-debug` to work with the new middleware setup

#### Follow-ons

- https://github.com/metabase/metabase/issues/14386
- https://github.com/metabase/metabase/issues/14373
- https://github.com/metabase/metabase/issues/13714 (this would require another big refactor but is my long term goal)

**Comment by camsaul** [comment]
All the PRs are merged in now so closing this out
