### ISSUE TITLE
[Epic] Allow users to annotate (and use) meaningful events

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#20289]
Let users annotate and manage remarkable events in the product.

**Links**
Product doc https://www.notion.so/metabase/Allow-users-to-annotate-and-use-meaningful-events-b06ba695b07541d09fc3ac23ea1852b8?d=2e87ad5af17742cda647def8dfea0761#99fef92c00b54c428e1bceb8f0ad15cb
Fixes https://github.com/metabase/metabase/issues/4838

**Implementation Plan**

***Milestone 1*** 
- [x] Add CRUD for events and timelines within a collection @ranquild 
- [x] Display events in timeseries charts without the sidebar for now (#20701)
- [x] allow for more api endpoints to include start and end for events
- [x] permissions check on `GET /api/timelines`. This could be a little tricky because permissions in bulk are not optimized. For each it would lookup the containing collection and check those permissions, and it does not lookup all collections at once, but would look up one at a time, including the same collections repeatedly.

***Milestone 2*** 
- [x] UI changes to allow CRUD for events and timelines from a question
- [x] Add the timeline sidebar in the query builder and allow to toggle timeline visibility for saved questions (#20944)

***Milestone 3*** 
- [x] Handle default timeline's naming
- [x] Allow creating events from the QB events sidebar
- [x] Allow editing events from the QB events sidebar
- [x] Allow archiving events from the QB events sidebar
- [x] Support events display in time-series charts for ad-hoc questions based on models
- [x] Support events display in time-series charts for ad-hoc questions based on raw data

**Entities**

***Event - new***
```
- id: number
- timeline_id: number
- name: string
- description: string, optional
- icon: string
- date: string, iso string with a timezone
- archived: boolean
- creator: User, set by the backend
- created_at: string, set by the backend
```

***Timeline - new***
```
id: number
collection_id: number
name: string
description: string, optional
default_icon: string
archived: boolean
events: Event[], set by the backend
```

**API changes**
## API Endpoints (So far)

***timeline***
- [x] POST /api/timeline
- [x] GET /api/timeline/:id
- [x] GET /api/timeline/:id?include=events
- [x] GET /api/timeline/:id?include=events&archived=true
- [x] PUT /api/timeline/:id
- [x] DELETE /api/timeline/:id 

***timeline-event***
- [x] POST /api/timeline-event
- [x] GET /api/timeline-event/:id
- [x] PUT /api/timeline-event/:id
- [x] DELETE /api/timeline-event/:id 

***timelines via collection***
- [x] GET /api/collection/root/timelines
- [x] GET /api/collection/root/timelines?include=events
- [x] GET /api/collection/root/timelines?include=events&archived=true
- [x] GET /api/collection/:id/timelines
- [x] GET /api/collection/:id/timelines?include=events
- [x] GET /api/collection/:id/timelines?include=events&archived=true

***timelines via card***
- [x] GET /api/card/:id/timelines
- [x] GET /api/card/:id/timelines?include=events
- [x] GET /api/card/:id/timelines?include=events&archived=true

***Endpoint for Getting Events within a Range***
- [x] GET /api/card/:id/timelines?include=events&start=X&end=Y
- [x] GET /api/timeline/:id?include=events&start=X&end=Y

***Comments***

1. The idea is to call `GET /api/event-timeline?collection_id={collection-id}` for a saved question/model and `GET /api/timeline` for an unsaved question.
2. For now let's always include `events` with `event-timelines`. We could switch to `include` param later.

***Backend TODOs***
- [x] `GET /api/timeline/:id?include='events'&start='time'&end='time'`
- [x] Icons schema pre-insert (handled on the routes) post-select deemed unnecessary

**Comment by adam-james-v** [comment]
Tracking a few Backend TODOs:

- [ ] `GET /api/timeline/:id?include='events'&start='time'&end='time'`
