### ISSUE TITLE
[Epic] Favorite items

### ISSUE THREAD

**Issue by gusaiani** [metabase/metabase#20318]
Let users pick and quickly access their favorite items

**Links**
[Product doc](https://www.notion.so/metabase/Let-users-pick-and-quickly-access-their-favorite-items-0a0881569bf34836bdef6cedc536f5fe)

⚠️ Everything below will be changed in a few moments.

**Implementation Plan**

***Milestone 1*** 
- [ ] Add CRUD for events and timelines within a collection @ranquild 
- [ ] Display events in timeseries charts without the sidebar for now

***Milestone 2*** 
- [ ] UI changes to allow CRUD for events and timelines from a question
- [ ] Add the timeline sidebar in the query builder and allow to toggle timeline visibility

***Milestone 3*** 
- [ ] Handle default timeline's naming

**Entities**

***Event - new***
```
- id: number
- timeline_id: number
- name: string
- description: string, optional
- icon: string
- date: string, iso string with a timezone
- archived: boolean
- creator: User, set by the backend
- created_at: string, set by the backend
```

***Timeline - new***
```
id: number
collection_id: number
name: string
description: string, optional
default_icon: string
archived: boolean
events: Event[], set by the backend
```

**API changes**

***Endpoints***

```
GET /api/timeline, optional archived=true and collection_id={collection_id}
GET /api/timeline/{timeline_id}
GET /api/timeline/{timeline_id}/event/{event_id}

POST /api/timeline
POST /api/timeline/{timeline_id}/event

PUT /api/timeline/{timeline_id}
PUT /api/timeline/{timeline_id}/event/{event_id}

DELETE /api/timeline/{timeline_id}
DELETE /api/timeline/{timeline_id}/event/{event_id}
```

***Comments***

1. The idea is to call `GET /api/timeline?collection_id={collection-id}` for a saved question/model and `GET /api/timeline` for an unsaved question.
2. For now let's always include `events` with `timelines`. We could switch to `include` param later.

**Comment by mazameli** [comment]
This is feature-complete.
