### ISSUE TITLE
[Epic] Add feature level data permissions 

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#20380]
**Links**
- [Product doc](https://www.notion.so/metabase/Add-feature-level-permissions-to-groups-8027685681774932ac7221131f061295)
- eng doc: TBD

### Groundwork

- [x] FE: https://github.com/metabase/metabase/pull/20433
- [x] FE & BE: https://github.com/metabase/metabase/pull/20564
- [x] FE: https://github.com/metabase/metabase/pull/20979

### Downloaded results permission 

Permission management

- [x] BE: Add new permission to permissions graph
- [x] BE: Write migrations to grant download permissions for existing groups & DBs
- [x] https://github.com/metabase/metabase/pull/20883

Limit access

- [x] BE: Apply limits based on the permission to the export handle
- [x] BE: Add permissions info to the dataset API handler
- [x] https://github.com/metabase/metabase/pull/20931

### Manage data model 

Permission management

- [x] BE: Add new permission to permissions graph
- [x] https://github.com/metabase/metabase/pull/20952

Limit access

- [x] BE: Restrict data model api fetch/update handlers based on permissions
- [x] BE: Add the permission data to database/table handlers 
- [x] https://github.com/metabase/metabase/pull/20952

### Manage databases 

Permission management

- [x] BE: Add new permission to permissions graph
- [x] https://github.com/metabase/metabase/pull/20953

Limit access

- [x] BE: https://github.com/metabase/metabase/pull/21531
- [x] https://github.com/metabase/metabase/pull/20953

### Tech debt

- [-]  FE: Cover existing permissions with unit tests — split selectors covered with tests but it could be even better. I will follow-up with more
