### ISSUE TITLE
Add feature level collection permissions

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#20382]
**Links**
- [Product doc](https://www.notion.so/metabase/Add-feature-level-permissions-to-groups-8027685681774932ac7221131f061295)
- eng doc: TBD

### Manage models — `feature/models-permission`

Permission management

- [ ] BE: Add new permission to permissions graph
- [ ] FE: Support new permission in the permission editor UI

Limit access

- [ ] BE: Restrict models API handlers
- [ ] BE: Add the permission data to the collection entity
- [ ] FE: Make models UI read-only, disallow converting questions to models

### Tech debt

- [ ]  FE: Cover existing collection permissions with unit tests
