### ISSUE TITLE
[Epic] General permissions

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#20397]
**Links**
- [Product doc](https://www.notion.so/metabase/Add-feature-level-permissions-to-groups-8027685681774932ac7221131f061295)
- eng doc: TBD

### Subscriptions and alerts 

Permission management

- [x] BE: Add new permission to permissions graph
- [x] FE: Support new permission in the permission editor UI

Limit access

- [x] BE: Restrict subscriptions/alerts API handlers
- [x] BE: Add the permission data to the collection entity
- [x] FE: Update dashboard subscriptions UI for users with restricted access 
- [x] FE: Update question alerts UI for users with restricted access including warnings for unsaved questions

### General settings access permission

Permission management

- [x] BE: Add new permission to permissions graph
- [x] https://github.com/metabase/metabase/pull/21460

Access

- [x] BE: Allows users with the permission to change settings (multiple API handlers)
- [x] BE: Add permission flag to the user entity
- [x] https://github.com/metabase/metabase/pull/21460

### Monitoring access 

Permission management

- [x] BE: Add new permission to permissions graph
- [x] FE: Support new permission in the permission editor UI

Access

- [x] BE: Allows users to query audit/tools queries
- [x] BE: Add permission flag to the user entity
- [x] FE: Let users with the permission use Audit and Tools tabs
- [x] FE, BE: Restrict adding recipients
