### ISSUE TITLE
[Epic] Group managers

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#20396]
**Links**
- [Product doc](https://www.notion.so/metabase/Add-feature-level-permissions-to-groups-8027685681774932ac7221131f061295)
- eng doc: TBD

### Group managers

- [x] BE: Add a type field to users (memberships) as well as endpoints to change it
- [x] BE: Check for permission in add/remove member handlers
- [x] FE: Group managers UI
