### ISSUE TITLE
[E2E] Embedding

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#20718]
# Metabase Documentation
https://www.metabase.com/docs/latest/administration-guide/13-embedding.html
---

Related Issues: https://github.com/metabase/metabase/labels/Embedding%2FSigned

## Tasks
- [x] Create a new e2e group in the CI (#20721)
- [x] Move over some of the existing tests (#20721)
- [x] Enable embedding premium token tests (#20753)
    - [x] Remove hard coded version (#20746)
- [ ] Extract commonly used functions into a separate file (helpers)
- [x] Create a helper for `jwt` signing and obtaining the token, rather than using the UI (#20853)

### Smoke tests
- [x] Scenario: embedding disabled (#20761)
- [x] Scenario: embedding enabled (#20764)

## Types of embeddable objects
- [x] Questions
    - [x] GUI (#20812)
    - [x] Native
        - #20909
        - #21185
    - [x] Models (should not be embeddable) (#20819)
- [x] Dashboards (https://github.com/metabase/metabase/pull/21292)
- [x] Editions (#20764)
    - [x] OSS
    - [x] EE
- [x] Filters on an embeddable object and their combo
     - [x] Question filters
       - [x] Filters on a GUI question (only possible if question is part of the dashboard)
       - [x] Filters on a native question (#21185)
         - [x] “simple”
         - [x] With the field filter connected to a specific field
       - [x] Dashboard filters (https://github.com/metabase/metabase/pull/21529)
         - [x] With or without the default value
         - [x] All filter types (id, time, string, number)
         - [x] Linked filters (https://github.com/metabase/metabase/pull/21520)
- [x] Publish status
  - [x] Published
  - [x] Unpublished (and switched from published to unpublished)
- [x] Parameters
    - [x] Disabled
    - [x] Editable
    - [x] Locked
    - [x] (Hidden)
    - [x] Make sure parameter can be set to disabled after it was previously either enabled or locked (https://github.com/metabase/metabase/pull/21292)

### Out of Scope
- Visual tests
    - Bordered
    - Titled
    - Dark vs light 
    - Fullscreen
    - Embedding preview
