### ISSUE TITLE
Understand and solve recent E2E failures on `master`

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#20792]
Detailed description TBD...

### Tasks
- [x] Separate and examine the "auditing" group of tests in CI (#20793)
    - We've seen an increasing number of `admin-ee` failures in CircleCi lately
    - Most of those failures seem to be happening in the auditing tests, although they aren't related to auditing per se
    - Tests fail to restore from a snapshot
- [x] Increase the randomness in caching tests (#20801)
    - [x] Disable caching tests completely! (#20984)
- [x] Inspect `sharing-ee` failures (https://github.com/metabase/metabase/pull/21324)
- [x] https://github.com/metabase/metabase/pull/21085
- [x] https://github.com/metabase/metabase/pull/21092

## Note
Unfortunately, in the middle of solving the previous flakes we decided to upgrade Cypress to the latest version. That brought a new set of flakes and/or failures with it that should be dealt with separately. You can track the progress here: https://github.com/metabase/metabase/issues/21028

**Comment by nemanjaglumac** [comment]
I'm seeing the error `90035` in the Cypress screenshots when it tries to restore from a snapshot. Searching online, I found this for H2:
http://www.h2database.com/javadoc/org/h2/api/ErrorCode.html#SEQUENCE_ALREADY_EXISTS_1

```java
SEQUENCE_ALREADY_EXISTS_1
public static final int SEQUENCE_ALREADY_EXISTS_1
// The error with code 90035 is thrown when trying to create a sequence if a sequence with this name already exists. Example:
 CREATE SEQUENCE TEST_SEQ;
 CREATE SEQUENCE TEST_SEQ;
 ```

**Comment by nemanjaglumac** [comment]
Another type of error I'm seeing for `auditing` is clearly rendered on the page in the middle of the test o.O

`Timeout trying to lock table "SYS"`

![image](https://user-images.githubusercontent.com/31325167/156234840-4f4e0a70-5c61-4cb3-86d6-8e5dc5e9a734.png)
