### ISSUE TITLE
Support `:median`, `:var`(iance), and `:percentile` aggregation types for more databases

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#20929]
In https://github.com/metabase/metabase/pull/12096 (original issue https://github.com/metabase/metabase/issues/1660) we added support for Postgres, Redshift, Oracle, Snowflake, Presto, BigQuery, and maybe some others I forgot. Other databases probably can be added: 

- [ ] It seems like Vertica supports this as well but we haven't added it to our driver yet -- see #12845 
- [ ] IIRC newer H2 supports it but we can't add support yet because of #20599 
- [ ] It seems like SQL Server supports it based on https://docs.microsoft.com/en-us/sql/mdx/median-mdx?view=sql-server-2016 -- see #12222
- [ ] Not sure about other DBs but we should go thru everything and check to be sure

**Comment by camsaul** [comment]
We should look at the [Database Tiers for Feature Development](https://www.notion.so/metabase/Database-Tiers-for-Feature-Development-fabba4d2bbfb4c729029f5e77d585f61) list to determine how much time to spend for each driver. If adding support for the new features to Vertica is very quick (just a few lines of code), for example, let's do it, but since it's one of our lower-priority drivers we shouldn't spend significant time on it.

**Comment by camsaul** [comment]
variance actually is feature flagged by `:standard-deviation-aggregations`, so that should probably already be in place. We should look at the stuff feature flagged by `:percentile-aggregations` and maybe `:advanced-math-expressions` tho.

**Comment by camsaul** [comment]
After looking at SQL Server a bit I think the first step here might be just to try to research what things are even feasible to add support for and which ones aren't
