### ISSUE TITLE
Upgrade Cypress and its dependencies

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#21028]
This `.Epic` serves the purpose of tracking the related PRs to the Cypress upgrade.

- [x] https://github.com/metabase/metabase/pull/20483
- [x] https://github.com/metabase/metabase/pull/21019
---
- [x] https://github.com/metabase/metabase/pull/21011
- [x] https://github.com/metabase/metabase/pull/21029
- [x] https://github.com/metabase/metabase/pull/21016
- [x] https://github.com/metabase/metabase/pull/21010
- [x] https://github.com/metabase/metabase/pull/21053
- [x] https://github.com/metabase/metabase/pull/21067
- [x] https://github.com/metabase/metabase/pull/21062
