### ISSUE TITLE
[E2E] Migrate all e2e tests from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#21100]
Now when we finally have the ability to rerun only a failed job in GHA, nothing's stopping us anymore from migrating all E2E tests from CircleCI.

## Run test groups in master with GitHub Actions

- [x] admin (https://github.com/metabase/metabase/pull/21266)
- [x] binning (https://github.com/metabase/metabase/pull/21122)
- [x] collections (https://github.com/metabase/metabase/pull/21159)
- [x] custom-column (https://github.com/metabase/metabase/pull/20266)
- [x] dashboard (https://github.com/metabase/metabase/pull/20302)
- [x] downloads (https://github.com/metabase/metabase/pull/20266)
- [x] embedding (https://github.com/metabase/metabase/pull/21295)
- [x] filters (#22131) 
- [x] joins (https://github.com/metabase/metabase/pull/21122)
- [x] models (https://github.com/metabase/metabase/pull/21272)
- [x] moderation (https://github.com/metabase/metabase/pull/20266)
- [x] native (https://github.com/metabase/metabase/pull/21251)
- [x] native-filters (https://github.com/metabase/metabase/pull/21251)
- [x] onboarding (https://github.com/metabase/metabase/pull/21422)
- [x] Permissions (https://github.com/metabase/metabase/pull/20566)
- [x] questions (https://github.com/metabase/metabase/pull/21099)
- [x] sharing (https://github.com/metabase/metabase/pull/21274)
- [x] visualizations (https://github.com/metabase/metabase/pull/21122)
- smoketest (not going to be ported for now)

**Also**

- [x] #21319
- [x] Percy (see PR #17747 for context)
- [x] #23429

## Migrate test groups for PR checks to GitHub Actions (Only EE)

- [x] #21480
- [x] #21676
- [x] #21563
- [X] #23553
- [X] #21681
- [x] #23169
- [X] #22393
- [X] #22405
- [x] #21809
- [x] #21898
- Deleted after all in favor of: #21987
- [x] #21492
- [x] #22439
- [x] #23442
- [x] #22075
- [x] #22787
- [x] #21538
- Deleted in favor of: #22132
- [x] #23309
- [x] #23364
- [x] #23438
- [x] organization: #22924
- [x] permissions: #22924
    - previously: (#21561, but then we had to remove it in #21663)
- [x] #23042
- [x] #23015
- [X] #23553

## Remove test groups from CircleCI

- [X] #23553
- [X] #21785
- [X] #23308
- [X] #22440
- [x] #22907
- [x] #21991
- [x] #21680
- [x] #23014
- [X] #23517
- [X] #22410
- [x] #22893
- [x] #21680
- [x] #23405
- [x] #23426
- [X] #23517
- [x] #23307
- [x] #23307
- [x] #23164
- [x] #23117
- [X] #23553

**Also**

Full description with links and dependencies... TBD.

**Comment by nemanjaglumac** [comment]
I ran every single test in `embedding` 10x in this run:
https://github.com/metabase/metabase/actions/runs/2047942170

All green.

**Comment by ariya** [comment]
Example failures which start to show up on master: https://github.com/metabase/metabase/actions/runs/2048683350

**Comment by nemanjaglumac** [comment]
> Example failures which start to show up on master: https://github.com/metabase/metabase/actions/runs/2048683350

Saw that.
- `question` group: the failure is related to new tests related to timeline events
- `sharing` group: snapshot/restore failure
