### ISSUE TITLE
[Epic] Give users a chill and useful starting page

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#21322]
Product doc https://www.notion.so/metabase/Give-users-a-chill-and-useful-starting-page-41fce022e6c448bd8036d4facec7eb51#1e39bc3549a547b4802654fda2fb1e09

#### BE changes

- [x] improve popular_items response. Remove any duplicates, elegantly handle 0 view situations
- [x] Add `is_installer` field to `/api/user/current`. It's basically the user with `id = 1`. Make sure to update `add-has-invited-second-user` check.
- [x] Add `has_question_and_dashboard` to `/api/user/current`. Should be `true` if the current user has access to at least one question *and* dashboard.
- [x] Modify `/api/activity/recent_views` to count only direct executions. More details in [the product doc](https://www.notion.so/metabase/Give-users-a-chill-and-useful-starting-page-41fce022e6c448bd8036d4facec7eb51#81883e5e172a4d2dadd51ed0fa56436e).
- [x] Add `/api/activity/popular_views` using the logic outlined in [the product doc](https://www.notion.so/metabase/Give-users-a-chill-and-useful-starting-page-41fce022e6c448bd8036d4facec7eb51#1e39bc3549a547b4802654fda2fb1e09). Could return the same data as from `/api/activity/recent_views`.
- [x] (Optional) Add `first_login` to `/api/user/current`. If not present in the db, this field can be substituted with `date_joined` for existing users. The field mirrors `last_login` field.

#### FE branching

if:
- `user.is_installer` is false
- `user.first_login` is within last 7 days
- `user.has_question_and_dashboard` is true

then:
- load and show `popular_views`

else if:
- `user.has_question_and_dashboard` is true
- `recent_views` are not empty

then:
- load and show `recent_views`

else if:
- `databases` have a database with `is_sample = false` and `initial_sync_status = completed`

then:
- load and show x-rays for the database

else if:
- `databases` have a database with `is_sample = true` and `initial_sync_status = completed`

then:
- load and show x-rays for the sample database

else:
- show empty state
