### ISSUE TITLE
[E2E] CI optimization

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#21325]
Full list TBD. This is just a sketch for now.

- [x] Output backend logs to the file and store that file as an artifact (https://github.com/metabase/metabase/pull/21360)
- [ ] Start using the official Cypress GitHub Action
- [x] Switch to using Chrome for E2E tests instead of the default Electron
- [ ] Decide what to do with Mongo snapshot
    - Possible solution is to NOT create mongo snapshots, and to rather add mongo db via API for every test that needs it
    - We have to weigh pros and cons

**Comment by nemanjaglumac** [comment]
Outdated
