### ISSUE TITLE
[Epic] JSON Field Support for 43

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#21534]
Project Doc: https://www.notion.so/metabase/Add-support-to-records-in-JSON-fields-8333f4db842a4bcfa449a09dbdcdab0c

Relevant Feature Requests:
 - https://github.com/metabase/metabase/issues/708
 - https://github.com/metabase/metabase/issues/2974
 - https://github.com/metabase/metabase/issues/2974

Tasks:
 - [x] Posgres JSON Nested field columns (https://github.com/metabase/metabase/pull/21007)
 - [x] Nested column enrichment (https://github.com/metabase/metabase/pull/20778)
 - [x] JSON API column changes (https://github.com/metabase/metabase/pull/21175)
 - [x] type backoff and limits (https://github.com/metabase/metabase/pull/21461)
 - [x] Type hierarchy fixes - make the stuff that's on master more sophisticated
 - [x] Specifically, null resolutions in particular.
 - [x] Elaborate on generated nested fields, `database_type` fill in correctly, visibility of parsed field.
 - [x] Array `contains` selections
 - [x] Field values
 - [x] General refactor in preparation for MySQL implementation, give it a 50% chance of being able to finish up MySQL implementation by 43 full release. Worst case, it goes in 43.1

**Comment by howonlee** [comment]
Remaining tasks for 43:
- [ ] Type hierarchy fixes - make the stuff that's on master more sophisticated
- [ ] Specifically, null resolutions in particular.
- [ ] Elaborate on generated nested fields, `database_type` fill in correctly, visibility of parsed field.
- [ ] Array `contains` selections
- [ ] Field values
- [ ] General refactor in preparation for MySQL implementation, give it a 50% chance of being able to finish up MySQL implementation by 43 full release. Worst case, it goes in 43.1

**Comment by luizarakaki** [comment]
#21934

**Comment by luizarakaki** [comment]
This epic is completed.

With the exception of Array Contains (should ship in 43.1), everything is merged to master.
