### ISSUE TITLE
[Epic] Reduce Waiting Cost of Slow Dashboards

### ISSUE THREAD

**Issue by rlotun** [metabase/metabase#21620]
Project Doc: https://www.notion.so/metabase/Reduce-the-waiting-cost-in-slow-dashboards-15e704be95904504a750949a474fb145

Feature request / bug issues:
 - https://github.com/metabase/metabase/issues/10690

Steps:
 - [x] document title and favicon updates for loading questions (https://github.com/metabase/metabase/pull/21425)
 - [x] Dashboard/question toaster and web notifications (https://github.com/metabase/metabase/pull/21414)
 - [x] Updating page title as dashboard loads (https://github.com/metabase/metabase/pull/21259)
 - [ ] web notifications
