### ISSUE TITLE
[Epic] Object Detail Modal Updates

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#22119]
This is an effort to fix existing limitations (like the fact that not everything can be viewed in object detail view) around the object detail modal as well as enhance functionality and usablity (like previewing and formatting data better).

## Links
- [Make it easier to get to and navigate through individual record view](https://www.notion.so/metabase/Make-it-easier-to-get-to-and-navigate-through-individual-record-view-e475d6a016794b1cbdee0334058802e5)
- [Clean up and add view-details action](https://www.notion.so/metabase/Clean-up-and-add-view-details-action-to-drill-through-menus-on-unaggregated-rows-63cd958ec5884127a991b7af1d9435b3?d=1aaec0a0bcee4a948a30b79f64f9728e)

### Milestone 1: Easier Navigation
- [x] Refactor existing object detail into typescript + functional components (https://github.com/metabase/metabase/pull/21621)
- [x] Add object detail view button to table view (https://github.com/metabase/metabase/pull/21592)
- [x] Turn object detail view into a modal (https://github.com/metabase/metabase/pull/21683)
- [x] Allow any table item to be viewed in object detail view (https://github.com/metabase/metabase/pull/22398)
- [x] Don't default to object detail view for single-result questions (https://github.com/metabase/metabase/pull/21895)
- [ ] Add View-Details Action to cell context menu
- [x] Allow full-page view of object details
- [ ] Allow view of foreign-table items over current table in object detail view
- [ ] _Allow object detail entry from non-table views (not in product doc but may be an easy bonus win)_

### Milestone 2: Enhanced Details
- [ ] Use entity names as titles wherever possible
- [ ] Richer Foreign Key Display: show entity name if present
- [ ] Richer Foreign Key Display: preview linked records
- [ ] Comment and Description fields in scrollable textareas
- [ ] Lat/Lng map display
- [ ] Email Addresses as mailto links
- [ ] Avatar image display
- [ ] image url display
- [ ] URLs: support opengraph previews
- [ ] JSON: easier to read nested table format

### How to Test This Feature Out

- navigate to any table, and either click that table's primary key, or the expand button to see details
- a few things to check out
  - tables with foreign keys
  - tables with long text content in fields
  - tables with lat/lng coordinates
  - tables with links and image links
