### ISSUE TITLE
Replace redux-form

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#22372]
**Implementation Plan**

***Milestone 1: clean up***

Isolate as much code as possible from `redux-form`, add some type-safety before switching form libraries

- [x] Extract form types (#22373)
- [x] Clean up `CustomForm` and `StandardForm` (#22373)
- [x] Clean up `FormField` component (#22375)

***Milestone 2: migrate entity forms***

- [x] #22583
- [x] #22586
- [x] #22585
- [x] #24637

***Milestone 3: migrate forms explicitly using `redux-form`***

- [x] https://github.com/metabase/metabase/pull/24682
- [x] https://github.com/metabase/metabase/pull/24713
- [x] https://github.com/metabase/metabase/pull/24722

***Milestone 4: migrate database forms***
- [x] Migrate setup database form
- [x] Migrate admin database form
