### ISSUE TITLE
[Epic] Persisted model cleanup

### ISSUE THREAD

**Issue by snoe** [metabase/metabase#22538]
Now that https://github.com/metabase/metabase/pull/21109 has merged in, there's still a number of cleanup tasks that need to be done. This is a mini-epic to track the remaining work. 

### Tasks

- [ ] Do not query the cache when sandboxed - PR https://github.com/metabase/metabase/pull/22501
- [ ] Double check state of models inside the inner loops of refresh/prune
- [ ] Add remarks (database comment logs) to persist job queries
- [ ] save original db type in model metadata instead of round tripping which is lossy. (see description in https://github.com/metabase/metabase/pull/21109)
- [ ] Enterprise/OSS changes. Have all models persisted on enabling in oss, allow for a la carte in EE ( still under discussion )

**Comment by rlotun** [comment]
should this be closed @kulyk and @snoe ?
