### ISSUE TITLE
[Epic] Allow Admins to define a reply-to header

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#22540]
Let's allow customers to customize the reply-to header for emails sent by their instance.

**Links**
- [product doc](https://www.notion.so/metabase/Allow-Admins-to-define-a-reply-to-header-6d6d216a633f4a5bbe6408f6875b7afc)

**Implementation Plan**

On the backend side this is relatively trivial. There are two principal features:
- allow for a reply-to header
- allow for friendly names of email addresses

```clojure
  (send-email! (smtp-settings)
               {:from "Metabase Install <ops@metabase.com>"
                :to ["john@company.com"]
                :reply-to ["Company Metabase <susie_admin@company.com>"]
                :subject "test email"
                :body  "This is but a simple test email"})
```
We add a `:reply-to` vector of email addresses and change the from to be `friendly name <email>`. the rest is bookkeeping for these two bits of information.

### Ways to solve
- [x] The reply-to needs to just be another text setting. It will split on the `,` delimiter and use those email addresses in the `:reply-to` part of `send-message-or-throw!`
  - [x]  of course the hard part of these features are the error conditions. I don't see where we validate the existing `from` email address on the backend. We should probably extend this to validate the from address as well as the repl-to addresses
- [x] store the name used for the sending address and concat them together as `"new friendly name <existing from address>"` It is tempting to open up the email input boxes and allow for this more complicated structure but this doesn't help us in Cloud which cannot edit its `from` email address. So we simply make a new setting `(email-from-name)` and form the string as described.
- [x] Add this new setting into `mb-to-smtp-settings` map in `mb.api.email` so we can receive the setting from the FE
- [ ] update FE to have the two new text boxes: one for the friendly name, one for a comma delimited list of reply-to addresses. Friendly name should not be an empty string: either nil or has characters. reply-to addresses should be nil or a  comma delimited list of valid email addresses, allowing for arbitrary whitespace between them (no spaces, one space, two spaces, tabs, etc)

**How to Test This Feature Out**

- [x] e2e tests are most likely the best. we run maildev so it would be nice to have confirmation of a well-formed email in a separate system. I'm not sure what the options are for getting that information from maildev
- [x] in memory tests on the backend. We have some nice utils to send emails and then inspect the in memory store.

**Comment by howonlee** [comment]
looks like it does need to start w/ BE bits, which I can do unless sasha wants to learn clojure real fast.

**Comment by calherries** [comment]
This is a duplicate of https://github.com/metabase/metabase/issues/18682
And will also fix [Sending mail with Site Name alias](https://github.com/metabase/metabase/issues/5812)

**Comment by paoliniluis** [comment]
This was closed
