### ISSUE TITLE
[Epic] Parameters Overhaul

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#22548]
We are refactoring the parameters feature to support the building of new features going forward. More detailed goals of this project are described in the technical design doc listed below.

**Links**
- [Product doc](https://www.notion.so/metabase/Refactor-Parameterization-8a1a8abebcd5449cabe3ea78a0518706)
- [Parameter refactor background material](https://www.notion.so/metabase/Parameter-Refactor-Background-Material-deab8e783a964693aaa99501d65b67e8
)
- [Parameter Overhaul Technical Design Doc (WIP)](https://github.com/metabase/eng-tech-designs/pull/3
)

**Implementation Plan**

Note that this section is incomplete and will continue to expand as we navigate the course we've charted in the technical design document.

***Milestone 1: make parameters more independent of fields*** 
- [x] ~[remove the "category" parameter type](https://github.com/metabase/metabase/issues/22552)~
- [x] [remove dependence on fields/dashboard in parameter widget UI code](https://github.com/metabase/metabase/issues/22554)

***Milestone 2: make parameters chainable***
- [x] [add parameters to cards](https://github.com/metabase/metabase/issues/22786)
- [ ] [make parameters chainable](https://github.com/metabase/metabase/issues/22869)

**How to Test This Feature Out**
This epic is an epic of epics. Testing details will be found within individual epics and their child issues/pull requests.

**Comment by rlotun** [comment]
@daltojohnso can we close this? (i assume we're canceling/punting on the chainable param stuff)
