### ISSUE TITLE
[Epic] Actions 

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#22542]
Notion design doc: https://www.notion.so/metabase/Enable-actions-on-individual-records-0956ae8664fe4eda8aa38311974fd639

Tech design docs: 
- https://github.com/metabase/eng-tech-designs/pull/7
- https://github.com/metabase/eng-tech-designs/pull/9

# Week 1-2

## Backend

- [x] #22543
- [x] #22544
- [x] #22546
- [x] #22551
- [x] #22553
- [x] #22557
- [x] #22555
- [x] #22556
- [x] #19409
- [x] #22693

## Frontend

- [x] #22545
- [x] #22547
- [x] #22549

# Week 2-3

## Backend 

- [x] #22844
- [x] #22905
- [x] #22845
- [x] #22848
- [x] #22851
- [x] #22849
- [x] #22854
- [x] #22853
- [x] #22852
- [x] #22855 

## Frontend

- [x] #22856
- [ ] #22857
- [ ] #22858

# Week 4-5

## Backend

- [x] #23125
- [x] #23126

# Week 5

## Backend 

- [x] Tech design for API endpoint custom actions
- [x] #23230
- [x] #23173
- [ ] optional/default values for parameters (?)
- [ ] #23275
- [x] #24079
- [x] #23288

## Frontend

- [x] #23174

# Week 6

## Backend
- [x] #23447
- [x] #23519

## Frontend
- [x] UI to manage http actions
- [x] A way to build HTTP actions and create template_tags for the various template fields
- [ ] Handle API responses and errors after action execution

# Bulk Work

## Backend

- [x] #23848
- [x] #23849
- [x] #23852

## Frontend
TBD

# Misc backend bugs

- [x] #23927
- [x] #23930
- [x] #23931
- [x] #24285
- [x] #23933
- [x] #24529
- [x] #23935
- [x] #23936
- [x] #24115 
- [x] #24116 
- [ ] #24228

# Future

## Backend 

- [x] #22846
- [ ] #22847
- [ ] #22934
- [x] #24284
- [ ] [Actions] Join table for emitter/action to dashboardcard
- [ ] #24529 

## Open Questions

- [ ] New permissions for Actions?
- [ ] Conditional logic for detail view Dashboards e.g. Admins see one Dashboard when clicking User ID and non-admins see a different one
