### ISSUE TITLE
[Epic] Parameters Overhaul - decouple FE parameters code from fields

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#22554]
Related to [Parameters Overhaul](https://github.com/metabase/metabase/issues/22548)

Parameter widgets should work with only whatever is in a given `parameter` object and an associated parameter value (if one exists). We need to remove the dependence on/references to fields and dashboards in parameter widget code.

**Links**
- [Product doc](https://www.notion.so/metabase/Refactor-Parameterization-8a1a8abebcd5449cabe3ea78a0518706)
- [Parameter refactor background material](https://www.notion.so/metabase/Parameter-Refactor-Background-Material-deab8e783a964693aaa99501d65b67e8
)
- [Parameter Overhaul Technical Design Doc (WIP)](https://github.com/metabase/eng-tech-designs/pull/3
)

**Implementation Plan**

- [x] Update [getDashboardParametersWithFieldMetadata](https://github.com/metabase/metabase/blob/a1073631950520817f1d2570a0925b0e3c4a5d5e/frontend/src/metabase/parameters/utils/dashboards.js#L120) to support a scenario where a parameter might not have fields. https://github.com/metabase/metabase/pull/22964
- [x] Make sure [getValueAndFieldIdPopulatedParametersFromCard](https://github.com/metabase/metabase/blob/a1073631950520817f1d2570a0925b0e3c4a5d5e/frontend/src/metabase/parameters/utils/cards.js#L72) also supports building parameter objects without fields (seems like it does or almost does already). https://github.com/metabase/metabase/pull/23063
- [x] Correct the usage of `fields` in [this function](https://github.com/metabase/metabase/blob/a1073631950520817f1d2570a0925b0e3c4a5d5e/frontend/src/metabase/parameters/utils/fields.js#L1) so that it isn't guaranteed to exist. (https://github.com/metabase/metabase/pull/22656)
- [x] Make FE parameters --> mbql code more generic. https://github.com/metabase/metabase/pull/22658
- [x] Make the logic in the [ParametersSidebar](https://github.com/metabase/metabase/blob/a1073631950520817f1d2570a0925b0e3c4a5d5e/frontend/src/metabase/parameters/components/ParameterSidebar.jsx#L127) exclusive to field filter parameters(https://github.com/metabase/metabase/pull/22657)
- [x] We should add additional logic to [getParameterValueFromQueryParams](https://github.com/metabase/metabase/blob/a1073631950520817f1d2570a0925b0e3c4a5d5e/frontend/src/metabase/parameters/utils/parameter-values.js#L25) to support parsing via parameter `type` when no fields exist. https://github.com/metabase/metabase/pull/22659
- [x] Remove `ParameterValueWidget` field-fetching logic. See if we need it at all. If we do, move it to the QB. (partial https://github.com/metabase/metabase/pull/22656)
- [x] create a widget for number parameters, uncoupled from fields https://github.com/metabase/metabase/pull/23247
- [x] create a widget for string parameters, uncoupled from fields
- [x] Create generic React hooks to support future generic widget components (https://github.com/metabase/metabase/pull/22718)
- [ ] ~~Create generic widgets that show lists of values, support searching, etc. -- basically, anything a `FieldValuesWidget` does for field values.~~
- [ ] ~~add a string `TokenField` component for `string/*`, `category`, and `id` parameters that is configurable to search or display values, similar to `FieldValuesWidget`, except that it should use generic function props for fetching (partial https://github.com/metabase/metabase/pull/22675)~~
- [x] Consider introducing types to parameter utils https://github.com/metabase/metabase/pull/22675 https://github.com/metabase/metabase/pull/22803

**How to Test This Feature Out**
Follow test instructions in individual PRs. Behavior of Parameters should remain the same, unless explicitly called out and listed here. More detailed testing instructions TBD.

**Comment by rlotun** [comment]
@daltojohnso should we close this?
