### ISSUE TITLE
[Epic] Parameters Overhaul - remove the "category" parameter type

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#22552]
Related to [Parameters Overhaul](https://github.com/metabase/metabase/issues/22548)

We are moving toward parameters being fully self-descriptive without mapped field, so we need parameter "types" that are primitive enough to determine which UI widget we show to users. Most types are fine (e.g. `"date/single"`, `"string/="`, `"number/between"`, but the `"category"` parameter type is too inclusive, as we use it for strings and booleans (and numbers, too, maybe?). 

**Links**
- [Product doc](https://www.notion.so/metabase/Refactor-Parameterization-8a1a8abebcd5449cabe3ea78a0518706)
- [Parameter refactor background material](https://www.notion.so/metabase/Parameter-Refactor-Background-Material-deab8e783a964693aaa99501d65b67e8
)
- [Parameter Overhaul Technical Design Doc (WIP)](https://github.com/metabase/eng-tech-designs/pull/3
)

**Implementation Plan**

***Milestone 1: add a "boolean" parameter type*** 
- [ ] [BE] add "boolean" as a usable parameter type
- [ ] [FE] add widget support for "boolean" parameter

***Milestone 2: stop using the "category" parameter***
- [ ] [BE + FE] stop defaulting template tags to the "category" type
- [ ] investigate if there are any other uses of the "category" type

***Milestone 3: migrations***
- [ ] [BE] migrate "category" parameters mapped to boolean fields to this new parameter type
- [ ] [BE] migrate other "category" parameters to `"string/="`
- [ ] investigate if we need to deal with number fields, etc., that have been used with category parameters

**How to Test This Feature Out**
TBD

**Comment by daltojohnso** [comment]
We're shifting our focus to https://github.com/metabase/metabase/issues/22786 as we've decided this epic does not help us toward our primary goal, as defined in #22548 and the parameters overhaul technical design document.
