### ISSUE TITLE
[Epic] Better handle language setting in embedding cases

### ISSUE THREAD

**Issue by metamben** [metabase/metabase#22561]
Customers need a way to match the language of their embedded Metabase with that of their end-users.

We should enable both ***full-app*** and ***public / signed*** embeds to receive a URL parameter ~similar to `#theme=night`~ (`#theme=night` is handled client side) that tells Metabase what language to render the iFrame in. This is optional and should be surfaced through documentation.

Example: `?locale=de-DE`

**Links**
- [product doc](https://www.notion.so/metabase/Better-handle-language-setting-in-embedding-cases-7bc1de1fefc14419a89d3d4e08f75281)

**Implementation Plan**

- [x] Make the backend provide the right locale information based on the URL.
  - [Explore how locale is chosen in the BE](https://github.com/orgs/metabase/projects/42/views/3#)
  - [Select the right locale based on query param](https://github.com/orgs/metabase/projects/42/views/3#)
  - [Add backend test for locale selection](https://github.com/orgs/metabase/projects/42/views/3#) 
- [x] Send the `locale` parameter (Not code this is up to the person using embed to add locale themselves)
- [x] Testing (https://github.com/metabase/metabase/pull/22618)
- [x] Documentation

**How to Test This Feature Out**
1. Run Metabase EE ([Follows step 1+2 in this guide](https://www.notion.so/metabase/Cypress-How-To-4d1c70bb0ce94a60b3688fd7acba8471#eec1d3fd0f0d4116ba3d96e654e1c5b7))
1. Set up full app embedding (https://www.metabase.com/docs/latest/enterprise-guide/full-app-embedding.html)
    1. Set up `Embedding in other Applications`
        1. set`http://localhost:3001` as an origin URL.
    1. Set up `Authentication > JWT`
        1. set whatever in `JWT IDENTITY PROVIDER URI`
        2. ensure `STRING USED BY THE JWT SIGNING KEY` matches what's set in here https://github.com/metabase/sso-examples/blob/afa3f3c407b0f4b432b72de995be0e24c25dd2b6/app-embed-example/server.js#L10
1. Set up [our embedding example app](https://github.com/metabase/sso-examples/tree/master/app-embed-example)
    1. Copy `.env.example` to `.env`
    1. Set `MB_PREMIUM_EMBEDDING_TOKEN` using the value from `ENTERPRISE_TOKEN` in https://www.notion.so/metabase/Cypress-How-To-4d1c70bb0ce94a60b3688fd7acba8471#eec1d3fd0f0d4116ba3d96e654e1c5b7
1. Run `yarn dev` to start web app and server
1. Go to `http://localhost:3001/analytics?locale=de-DE` or via `Analytics` tab in the nav bar and append `?locale=de-DE` or whatever locale you want to test
1. See that the language is set to the specified locale

**Comment by mazameli** [comment]
Pardon the ignorance, @metamben, but would you say that the two checkboxes here are broken down as small as is reasonable, and each represent no more than ~a day of work?

**Comment by mazameli** [comment]
Cool cool, sorry if I jumped the gun 😅

**Comment by WiNloSt** [comment]
Closing this since it's already marked done in 44 Cycle Epic Board
