### ISSUE TITLE
[EPIC] Let whitelabeling users set a font family

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#22582]
Font customization is a useful feature for users who wish to customize their Metabase instance's appearance, which prior to this feature can only be done by modifying source code. This feature will allow whitelabeling users to do exactly that as a site-wide setting.

- product doc: https://www.notion.so/metabase/Let-whitelabeling-users-set-a-font-family-2813c8fa4d0a40b9b503a66f7a218ce3
- feature branch: [whitelabelling-users-font-family-font-setting](https://github.com/metabase/metabase/tree/whitelabelling-users-font-family-font-setting)

**Implementation Plan**
Should be a fairly straightforward implementation with independent FE and BE streams. Will start with the global settings, and move on to signed embedding afterwards.

***Contract***
The contract between the Frontend and Backend is as follows:
`GET /api/settings/available-fonts` -> `("Lato", "Merriweather", "Montserrat", "Noto Sans JP", ...)`
`PUT /api/settings/application-font` -> expects a String
`PUT /api/settings/application-font` -> returns currently set Font's display name eg. `Noto Sans JP`

***Milestone 1: Allow Font Selection in Admin Section***

- [x] Rename "whitelabel" to "Appearance" in Admin Panel

*Frontend*
- [x] Update settings page, send language on settings update: 
- [x] Apply correct font settings on page load
- [x] Add applicable E2E and Unit tests

*Backend*
- [x] create new _application-font_ setting using the setting API
- [x] Ensure feature is Enterprise only
- [x] find best way to create the list of fonts (TBD if backend or frontend is best)
- [x] Unit Tests

***Milestone 2: Signed Embedding Wizard***

*Frontend*
- [x] Update wizdard form to include language selection, As well as general appearance cleanup
- [x] Add applicable E2E and Unit tests

***Milestone 3: Custom fonts***

*Frontend*
- [x] Add custom fonts widget in Admin settings https://github.com/metabase/metabase/pull/23659
- [x] Set custom font in global styles https://github.com/metabase/metabase/pull/23659
- [x] Support custom fonts in signed embedding widgets https://github.com/metabase/metabase/pull/23697 

***Milestone N*** _(we can put stuff like translations, docs, testing, etc)_
- [ ] Ensure that OSS build does not bundle unused fonts

**How to Test This Feature Out**

As this is purely presentation, and not related to any sample dataset, automated testing can likely be done by setting the desired default font, then inspecting various elements to view their computed `font-family` attribute, ensuring that it set to whatever was selected. In manual testing, it will be very apparent that the font has changed, but we will need to ensure that it is truely applied globally.

**Comment by mazameli** [comment]
@adam-james-v told me the backend is done on this, so I'm closing this as done.

**Comment by mazameli** [comment]
Reopening due to addition of milestone 3
