### ISSUE TITLE
[Epic] Bulk filtering modal

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#22629]
Add a modal to the query builder to apply multiple filters at once.

**Links**
Product doc https://www.notion.so/metabase/Bulk-filtering-modal-d8dca207ddcf43428f3814da2839d914

**Implementation Plan**

***Milestone 1: Getting the Party Started***
- [x] Add basic modal with filters CRUD https://github.com/metabase/metabase/pull/22701
- [x] Add tests and fix bugs https://github.com/metabase/metabase/pull/22808
- [x] Add support for segment filters https://github.com/metabase/metabase/pull/22899
- [x] save filter changes on blur https://github.com/metabase/metabase/pull/22903

***Milestone 2: Getting the Party Sorted***
- [x] Sort fields in the modal https://github.com/metabase/metabase/pull/22963

***Milesone 3: Chilling Out***
- [x] Refactor BooleanPicker to Typescript https://github.com/metabase/metabase/pull/22993
- [x] Modify boolean filters for the modal https://github.com/metabase/metabase/pull/23011
- [x] Create Dual slider component for number range input (https://github.com/metabase/metabase/pull/23085)
- [x] Modify category filters for the modal https://github.com/metabase/metabase/pull/23341
- [x] Add Key picker component https://github.com/metabase/metabase/pull/23374
- [x] Add Text filters for the modal https://github.com/metabase/metabase/pull/23374
- [x] Modify date filters for the modal https://github.com/metabase/metabase/pull/23464
- [x] Allow text filters to have suggestions in popover https://github.com/metabase/metabase/pull/23516
~~Modify number filters for the modal https://github.com/metabase/metabase/pull/23238~~

***Milestone 4: Make it Great***
- [x] Hide filter sidebar https://github.com/metabase/metabase/pull/23546
- [x] Tweaks to date button colors https://github.com/metabase/metabase/pull/23547
- [x] Number filters inline https://github.com/metabase/metabase/pull/23582
- [x] make checkboxes blue https://github.com/metabase/metabase/pull/23583
- [x] Show incompatible category filters from notebook mode https://github.com/metabase/metabase/pull/23597
- [x] Improve Tab UI https://github.com/metabase/metabase/pull/23620
- [x] Redesign column arrangment and operator selector  https://github.com/metabase/metabase/pull/23746 
- [x] Update colors to improve clarity https://github.com/metabase/metabase/pull/23740
- [x] Redesign v3 https://github.com/metabase/metabase/pull/23911
- [x] responsive spacing and text https://github.com/metabase/metabase/pull/24173
- [x] more padding/width adjustments: https://github.com/metabase/metabase/pull/24322
- [x] update default text filter operators https://github.com/metabase/metabase/pull/24328
- [x] dont use error color for token removal https://github.com/metabase/metabase/pull/24362
- [x] lighter input styling https://github.com/metabase/metabase/pull/24365
- [x] dont tokenize single inputs https://github.com/metabase/metabase/pull/24367
- [x] segment select text changes https://github.com/metabase/metabase/pull/24368
- [x] large category picker https://github.com/metabase/metabase/pull/24378
- [x] dont use list icon https://github.com/metabase/metabase/pull/24379
- [x] use light input borders https://github.com/metabase/metabase/pull/24435
- [x] v4 redsign fields: https://github.com/metabase/metabase/pull/24492
- [x] v4 redesign nav: https://github.com/metabase/metabase/pull/24493
- [x] Remove filter sidebar completely  https://github.com/metabase/metabase/pull/24164

***Maybe***
- [x] Make fields searchable https://github.com/metabase/metabase/pull/23813
~~Easy shortcut to notebook mode~~
~~Modal height transition~~

***Bugs***
- [x] nested questions don't show base table properly https://github.com/metabase/metabase/issues/22992
- [x] model names do not appear https://github.com/metabase/metabase/issues/23079 https://github.com/metabase/metabase/pull/23216
- [x] fix component hierarchy https://github.com/metabase/metabase/pull/23199
- [x] update "metrics" tab name and order https://github.com/metabase/metabase/pull/23215
- [x] date filter shortcuts aren't preserved https://github.com/metabase/metabase/pull/23289
- [x] date filter shortcuts add empty filter on blur (present elsewhere with date filter shortcuts as well) https://github.com/metabase/metabase/pull/23492
- [x] down arrow doesn't open bulkfilterselect https://github.com/metabase/metabase/pull/23343
- [x] inline value picker needs to change the `multi` prop of the text box based on the operator (e.g can't have multiple "starts with" values) https://github.com/metabase/metabase/pull/23520
- [x] need 2 inputs for between filters https://github.com/metabase/metabase/pull/23520
- [x] handle null categories in category picker https://github.com/metabase/metabase/pull/23577
- [x] case sensitivity not handled correctly https://github.com/metabase/metabase/pull/23671
- [x] category fields with no values look empty https://github.com/metabase/metabase/pull/23669
- [x] dates without times don't receive a date picker https://github.com/metabase/metabase/pull/23668
- [x] date shortcuts are duplicated https://github.com/metabase/metabase/pull/23646
- [x] cannot select `empty` (null) category option https://github.com/metabase/metabase/pull/23745
- [x] move category picker to single column to work better with long text https://github.com/metabase/metabase/pull/23745
- [x] make input borders uniform color https://github.com/metabase/metabase/pull/23740
- [ ] cannot remove filter by clicking X in a `BulkFilterSelect` when the popover is open
- [x] `FieldValuesWidget` field sometimes causes horizontal scroll
- [x] datepicker disappears https://github.com/metabase/metabase/pull/24033
- [x] horizontal scroll https://github.com/metabase/metabase/pull/24081
- [x] remove purple border for blue button https://github.com/metabase/metabase/pull/24374
- [x] show table names in saved questions with custom expressions https://github.com/metabase/metabase/pull/24439
- [x] hide popovers suggestions when removing items https://github.com/metabase/metabase/pull/24442
- [x] align prefix container https://github.com/metabase/metabase/pull/24448

**Comment by iethree** [comment]
I'm sure there will be more bugfixing and iteration on this after 44 releases, but I think we can call this epic "done" for now.
