### ISSUE TITLE
[Epic] Improve Startup Speed

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#22647]
We are having issues with startup duration. A particularly bad example is found in https://github.com/metabase/metabase/issues/19604 with 8+ hour startup times.

**Implementation Plan**
- [x] Log startup times, collect for analysis and tracking
  - Issue: https://github.com/metabase/metabase/issues/22706
  - PR: https://github.com/metabase/metabase/pull/22707
  - PR against release: https://github.com/metabase/metabase/pull/22711
- [x] Delay task running until initialization is complete 
  - Issue https://github.com/metabase/metabase/issues/22648
  - PR against master https://github.com/metabase/metabase/pull/22649
  - PR backported to `release-x.43.x`: https://github.com/metabase/metabase/pull/22666
- [x] improve database sync scheduling (we delete all and reschedule all at startup) 
  - Issue https://github.com/metabase/metabase/issues/22650
  - PR: https://github.com/metabase/metabase/pull/22680
  - backport for 43.x: https://github.com/metabase/metabase/pull/22708
- [ ] improve documentation around vacuuming? (related https://github.com/metabase/metabase/issues/1762)

**Comment by camsaul** [comment]
Also https://github.com/metabase/metabase/issues/10175

**Comment by rlotun** [comment]
@dpsutton might it be worth also looking into JVM warmup? not 100% sure it makes as much sense for analytical applications but if we called a hot path (maybe an API endpoint that hit a critical section in the query processor) a hundred times that would cause the JIT to optimize that path.

**Comment by rlotun** [comment]
this can be closed, right @dpsutton ?

**Comment by dpsutton** [comment]
Yeah. This epic was about issues that caused startup times on the order of 8 hours. We should open a different issue aimed at improving the startup time when it does not have pathological issues.
