### ISSUE TITLE
[Epic] Serialization overhaul

### ISSUE THREAD

**Issue by bshepherdson** [metabase/metabase#22641]
## Summary

Improve serialization to make the dumps consistent across runs, and include all present and future entities.

Improve deserialization with reliable de-duplication and smart conflict handling, and make loads idempotent.

**Purely backend changes.**

## Links
- [Product doc: Entity IDs](https://www.notion.so/metabase/Ensure-entities-have-stable-IDs-for-serialization-8917ea71233c422caa87d6cefc628731)
- [Product doc: Serialization](https://www.notion.so/metabase/Make-serialization-consistent-with-new-entities-properties-and-dependencies-10e852346a6d48faa6699b6218aaeb62)
- [WIP design doc](https://github.com/metabase/eng-tech-designs/pull/4)

### Milestone 1: Entity IDs
- [x] Add a Liquibase migration to put `entity_id` columns on all the internal entities.
- [x] Write the Toucan property `:entity_id` to automatically populate it on insert.
- [x] Add the property to all non-exempt models
- [x] Write a test to enforce that new ones don't get missed
- [x] Define a protocol for computing identity hashes; implement them all; test them all.

### Milestone 2: Serialization prototype
- [x] Prototype serialization and deserialization for a few models to prove the concept.
    - #23204 
- [x] EDN <-> YAML file conversion on either end
    - #23491 
- [x] Complete serialization to disk for those few models, with tests.
- [x] Complete deserialization for those few models, with tests.

### Milestone 3: Full coverage
- [x] Expand the coverage to all serialized models, possibly in several PRs.
    - #23622
    - #23803
    - #23804
    - #23842
    - #23868
    - #23961
    - #24122
    - #24146
    - #24200
- [x] Add a `--v2 true` flag to the serialization `dump` and `load` commands
    - #24230
- [x] Tests for comprehensive serialization (like for `identity-hash`).
- [x] Tests for dependency tracking - check that adding a new question inside a collection works.

### Milestone 3.5: Correctness

- [x] Certain fields contain JSON-encoded MBQL or similar, which have foreign keys (eg. `Table` and `Field` IDs) in them. Dive into these and replace them with portable references.
    - #24356 
    - #24537
    - #24606

### Milestone 4: Future-proofing
- [ ] Find as many possible conflicts as I can think of; write tests for each and work with product to find and implement the right resolution.
- [ ] Generative testing - for each entity, generate random instances and round-trip them. (With and without entity IDs set.)
- [ ] Have a solid story for encryption, database secrets, etc., possibly with different `MB_ENCRYPTION_SECRET_KEY` on each end.
- [ ] Better story for `creator_id` and users under serialization. Eg. it may be that everything imported (or everything whose original owner can't be found) should be adopted by the importing user, or a `nobody@mycompany.com` user, or something like that.

**Comment by rlotun** [comment]
@bshepherdson  perhaps we split out a separate epic of remaining follow-up work for 45, and then close this?

**Comment by bshepherdson** [comment]
I've split those trailing tasks into the new epic, #24608.
