### ISSUE TITLE
[Epic] Make database errors indicate which field they are associated with

### ISSUE THREAD

**Issue by metamben** [metabase/metabase#22714]
Right now, all database configuration errors during the sign up step show up next to the "Save" button rather than the appropriate field. 

This makes it more difficult for users to determine what's wrong and fix it in order to successfully connect their data. This is true for both set up and Admin → Databases.

**Links**
- [Product doc](https://www.notion.so/metabase/Make-database-errors-indicate-which-field-they-are-associated-with-67a50db019414cb6926f6393d423e463)
- Issue links:
  - #935
  -  https://github.com/metabase/metabase/issues/10646#issuecomment-864055492

**Implementation Plan**

***Milestone 1 - Implement field highlighting in the backend*** 
- [x] step 1: Clarify FE-BE interface (currently different endpoints e.g., `POST /api/database` and `POST  /api/setup/validate` report errors in different ways and we want to unify them)
  - We are going to use the data structure [documented](https://www.notion.so/metabase/Rough-initial-planning-for-Joypleteness-e129dfe45c664403bcee4bc8a09173c4#249c96a7fc1f4a40bd41ef0492adc858) by @ranquild:
     ```json
    {
      "message": "<error description>",
      "errors": {
        "host": "check your host settings",
        "fieldN": "<instruction for fieldN>"
      }
    }
     ```
     The `errors` field is optional.
  - We are going to use HTTP status codes to distinguish between success and failure. Status code 400 will be used to report errors.
  - The following API endpoints are involved:
    - `POST /api/database`
    - `PUT /api/database/:id`
    - `POST /api/setup/validate`
- [x] step 2: Implement BE

***Milestone 2 - Implement field highlighting in the frontend + persist error until the save button is hit again*** 

This milestone is skipped due to how persisting the form error involves modifying the form code which makes the code more complex than what we originally planned. It would take more time for a proper implementation + reviews so we decided to skip this as of now. See more at https://github.com/metabase/metabase/pull/22938#issuecomment-1143138423

- [ ] ~step 1: Implement FE~
- [ ] ~step 2: Add end-to-end tests~

**How to Test This Feature Out**
#### Account creation
- Spinup new Metabase instance.
- Follow the setup wizard until the database step.
#### Admin database go to `/admin/databases`
- Test adding a new database
- Test editing existing databases
- Test that the submit button is disabled as expected, and when there is an error the submit button will be enabled after any field is modified.
- Test that the inline error message will go away once the field with the error is visited.
- Test that the error message banner persists until the form is submitted again.

### Per database type 
  - Inject error into different fields
  - Compare error display with the Figma design
    - 2 different pages with 10 different error types
    - test instance language other than English
    - test user language other than English

**Comment by WiNloSt** [comment]
@ranquild @metamben based on [this product doc](https://www.notion.so/metabase/Make-database-errors-indicate-which-field-they-are-associated-with-67a50db019414cb6926f6393d423e463#b443c273c06f492295e801cbcaefc6ad) I just realize the main error messages also have bold fields e.g.
- Hmm, we couldn't connect to the database. Make sure your **Host** and **Port** settings are correct
- We couldn't connect to the SSH tunnel host. Check the **Username** and **Password**.

I thought of some approaches.
1. BE sends the error message as a markdown e.g. `Hmm, we couldn't connect to the database. Make sure your **Host** and **Port** settings are correct`. So FE would know which part of the message should be bold. Pros: Easy on the FE. Cons: Not really, but just need BE to change the error message.
2. FE maps field names inside and makes them bold. i.e. we know which database has which fields we could start to look for those field names in the error message. Pros: No BE change required. Cons: Field name in the error message has to be the exact same one sent from BE (See a screenshot below). And FE change is a lot more complicated
  ![image](https://user-images.githubusercontent.com/1937582/169216497-6edf5655-c342-468f-afed-5c6596c897f9.png)
3. Do nothing and there will be no bold field in the error message.

I think the first approach is the simplest of the two if we want bold field names, otherwise, I'd pick the 3rd option. Is there anything missing? What do you guys think?

**Comment by metamben** [comment]
The only complication I see with solution 1. is that the markup has to be preserved in translations. If we already have translations with markup then this is the way to go (and we should use the existing markup syntax). If we don't have messages with markup, then we should ask around if it's OK to introduce them now.

**Comment by metamben** [comment]
Update: as explained by @ranquild, the standard solution for such problems is that the message is updated in the front end. Since the desired effect is that the fields get highlighted, the frontend can take the localized field names, search for them in the error message and update each occurrence to the highlighted version.

**Comment by WiNloSt** [comment]
@mazameli According to [the Slack thread](https://metaboat.slack.com/archives/C03E8MQJZBM/p1654012858833919), we would put off the new error message component and persisting the error message. Should we close this epic for now or leave it open as the 2nd milestone is not finished.

**Comment by mazameli** [comment]
@WiNloSt, I think we can close this epic and open a different one if and when we decide to do milestone 2.

One question for you and @metamben, though — did the work thus far on this epic resolve the two issues in the description? https://github.com/metabase/metabase/issues/935
https://github.com/metabase/metabase/issues/10646#issuecomment-864055492

**Comment by metamben** [comment]
@mazameli As to #935, the problem statement there is very generic and it seems to me that it's scope is larger than that of this project. The concrete problem shown in  the screenshot of the bug ticket is solved in this project: the error message _above_ the save button says `Looks like your Username is incorrect.` and the `Username` field is highlighted with the label `Username: check your username`.
As for https://github.com/metabase/metabase/issues/10646#issuecomment-864055492, The error message appears right above the save button, so I think this comment can be ticked off.

**Comment by WiNloSt** [comment]
As per #935
> it would be more helpful for the user to highlight and mark the relevant fields they need to fix to connect to their data.

I think that's what we delivered in this project. So, it's done IMO.

And for https://github.com/metabase/metabase/issues/10646#issuecomment-864055492 that's also, from my interpretation, the same as #935. So, both should be closed. But as for the main #10646 itself, which was about displaying error on wrong fields. Alexander indicated it's a BE issue https://github.com/metabase/metabase/issues/10646#issuecomment-1101386127, which I supposed would already have been superseded by the work in this PR am I right @metamben ?

**Comment by metamben** [comment]
> Alexander indicated it's a BE issue [#10646 (comment)](https://github.com/metabase/metabase/issues/10646#issuecomment-1101386127), which I supposed would already have been superseded by the work in this PR am I right @metamben ?

Yes.

**Comment by mazameli** [comment]
Cool, I've closed those issues as fixed, marked them with the 0.44 milestone, and I'm closing this epic as done! 💪🏼
