### ISSUE TITLE
[Epic] Improve handling for user name null cases and syncs

### ISSUE THREAD

**Issue by adam-james-v** [metabase/metabase#22754]
There are some important gaps in how we handle SSO login names at the moment. This project aims to tackle two semi-related issues: 
- We sync new SSO user details and attributes for users on the initial and subsequent logins. For the user’s name specifically (not an issue for other attributes), we sync on initial login but then we don’t update it in subsequent logins. This causes any name-related changes made from the SSO provider to not be updated in Metabase.
- If a Metabase user's SSO provider does not supply us with a first/last name, we auto-fill `Unknown` in these cases. This causes weird cases in the product where we refer to people by their first name.

This project will fix the syncing bug and improve the implementation and UI regarding first and last names.

**Links**
- [product doc](https://www.notion.so/metabase/Improve-handling-for-user-name-null-cases-and-syncs-fa25e8e890de43b3b4892879695d33d5) (Notion)
- feature branch: TBD
- Issue links:
  - #15484
  - #16158

**Implementation Plan**
The linked issues can be handled independently, even though they are related. So, we'll tackle each as a separate milestone.

***Milestone 1: Proper user name sync***
This milestone is backend only
- [x] fix the syncing bug
- [x] unit tests to check that SSO details are synced

***Milestone 2: Better Handling for unknown user names***
backend:
- [x] allow `nil` first and last names in backend
- [x] fix logic for `:common_name`
- [x] appropriate unit tests

frontend:
- [x] List places where `null` user names need to be handled.
  - [x] `user.common_name`
  - [x] `user.first_name`
  - [x] `user.last_name`
  - [x] `user.getName()`
- [x] Create special cases in the frontend handling `null` user name. And use user email in places that require value.
  - [x] `user.common_name`
  - [x] `user.first_name`
  - [x] `user.last_name`
  - [x] `user.getName()`

***Milestone 3: Relax first/last name requirements on manual account creation***
We should relax naming requirements in general. If we allow `nil` appropriately on the backend, this may be a frontend only milestone.
- [x] Make first/last name fields optional on account creation #23327 
    - [x] Modify type constraint https://github.com/metabase/metabase/blob/9f41e1d2ef51e648a05f5edb188a1f430ea70f77/frontend/src/metabase-types/api/user.ts#L5-L6
    - [x] Make user form name fields optional https://github.com/metabase/metabase/blob/9f41e1d2ef51e648a05f5edb188a1f430ea70f77/frontend/src/metabase/entities/users/forms.js#L16-L22
- [x] Fix admin audit doesn't fall back name to email. #23393
- [ ] ~change the LDAP enterprise enhancement impl to re-use the JWT/SAML `fetch-and-update-user!` function~ — to be completed in https://github.com/metabase/metabase/issues/16158

**How to Test This Feature Out**
Follow the instruction here https://www.notion.so/metabase/Improve-handling-for-user-name-null-cases-and-syncs-9b6b3f93500c42d4b3dd019e7389e865
