### ISSUE TITLE
[Epic] Give users an expanded palette of colors to choose from

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#22816]
Expand the color picker within question and table visualization settings. Update the Whitelabel interface to reflect these changes and offer auto-fill capabilities. 

**Links**
- Product doc https://www.notion.so/metabase/Give-users-an-expanded-palette-of-colors-to-choose-from-50934e990e44410394b339a5fbff3d88

**Implementation plan**

***Milestone 1 - UI changes without changing the color palette***
- [x] Update single color pickers to support the extended palette
- [x] Update range color pickers to support the extended palette
- [x] Add basic admin UI with new layout
- [x] Replace deprecated color picker usages in settings
- [x] Replace deprecated color picker usages in forms

***Milestone 2 - extending the color palette***
- [x] Add new interface colors
- [x] Add new chart colors

***Milestone 3 - Admin UI leftovers***
- [x] Add color palette preview
- [x] Add main color generation
- [x] Add support for small screens
- [x] Add confirmation modal

***Milestone 4 - EE color settings migration***
- [x] BE - Migrate existing `application-colors` setting

***Milestone 5 - Static viz (optional)***
- [x] BE - Pass colors that are manually set by the user to the frontend

**Migration details**
Update `application-colors` setting value. It looks like this:
```
{ "brand": "#ababab", "accent2": "#bcbcbc" }
```

Set new color values based on existing ones (pseudocode):
```
{
  "accent0": values["brand"],
  "summarize": values["accent1"],
  "filter": values["accent7"],
  ...values
}
```

If a value for the key is not set, do not set the corresponding value in `application-colors`. **This code should run once**.
