### ISSUE TITLE
[Epic] - Cleanup for common actions of entities

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#22826]
Currently we have different workflows across our various entities on the platform. Common actions (such as editing names) are different places depending on if you're looking at a question, dashboard, modal or collection. This project aims to unify the UX across these 3 entities, while also making some quality of life improvements (no more double left panel issue) and add some joy for our users (eg: information transitioning in on hover).

**Links**
- product doc: [Notion link](https://www.notion.so/metabase/Cleanup-common-actions-across-entities-4f00c1a0934249c68048d21ad949d7fa)

**Implementation Plan**
As this is a large project that spans multiple pages, The initial milestone will be fairly fluid and involve a fair amount of discovery. However, subsequent milestones should progress quicker and use the patterns and components developed for the initial page. Since the Questions page has many changes, that will be milestone one. Each step will be done in sequence, and should represent work that can be reviewed and shipped to master (without losing any functionality)

***Milestone 1*** ) Saved Questions and Models
- [x] step 1: Move Breadcrumb to top navigation. https://github.com/metabase/metabase/pull/22910
- [x] step 2: Set up action button and move actions from left panel to new location. https://github.com/metabase/metabase/pull/23004
- [x] step 3: Build info panel. Move description, history, verification and cache config. https://github.com/metabase/metabase/pull/23197
- [x] step 4: Updated Title and backing component with the show/hide, as well as inline name editing. https://github.com/metabase/metabase/pull/23330
- [ ] step 5: Clean up Mobile Experience and review tests 
- - ModerationReviewButton, QuestionActions

***Milestone 2*** ) Unsaved Questions 
- [x] step 1: Collection Breadcrumb update https://github.com/metabase/metabase/pull/23576
- [x] step 2: Clicking on title prompts save https://github.com/metabase/metabase/pull/23470
- [x] step 3: Hide Bookmark, info, and action buttons https://github.com/metabase/metabase/pull/23004
- [x] step 5: Clean up Mobile Experience and add tests https://github.com/metabase/metabase/pull/23595

***Mileston 3***) Dashboards
- [x] step 1: Top nav breadcrumbs https://github.com/metabase/metabase/pull/23489
- [x] step 2: Action Button and Info Panel
- [x] step 3: Add updated title from Questions/models https://github.com/metabase/metabase/pull/23565
- [x] step 5: Clean up Mobile Experience and add tests https://github.com/metabase/metabase/pull/23814
- [x] step 6: Edit Dashboard name while in "edit mode" https://github.com/metabase/metabase/pull/23770

***Mileston 4***) Collections
- [x] step 1: Inline editing for Title and Description https://github.com/metabase/metabase/pull/23518
- [x] step 2: Remove + button and add Action button https://github.com/metabase/metabase/pull/23484
- [x] step 3: Updated modal for Move action https://github.com/metabase/metabase/pull/23484
- [x] step 5: Clean up Mobile Experience and add tests https://github.com/metabase/metabase/pull/23484
- [x] step 6: Edit authority level for a collection https://github.com/metabase/metabase/pull/23535
- [x] step 7: Remove `Edit this collection` menu option and fix tests https://github.com/metabase/metabase/pull/23537
- [x] step 8: Remove `update_collection_tree_authority_level` from the backend https://github.com/metabase/metabase/pull/23718

**How to Test This Feature Out**
Changes will be very apparent. Since we aren't adding much in terms of functionality, but in terms of layout, we should be sure to test this on a range of device sizes.
