### ISSUE TITLE
[Epic] Parameters Overhaul - make parameters chainable

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#22869]
Make parameters chainable.

**Links**
[Technical Design Doc](https://github.com/metabase/eng-tech-designs/blob/master/docs/parameters_overhaul_44.md)

**Implementation Plan**

***Milestone 1: make parameters targetable***
- [ ] [BE] support parameter_mapping targets of `["parameter", :parameter-id]`
- [ ] [FE] add explicit parameters to mapping UI

***Milestone 2: make parameter values fetchable via generic endpoint***
- [ ] [BE] implement `/api/parameter/:parameterId/values` endpoint
- [ ] [BE] support linked filters via parameter value endpoint without needing to POST list of filtering parameters
- [ ] [FE] reimplement parameter value fetching using new endpoint

***Milestone 3: polish***
- [ ] [BE] migrate parameters to separate table
- [ ] [BE/FE] migrate parameter_mappings to different structure for consistency across parameterizable objects
- [ ] [FE] introduce explicit abstractions around "parameterizable object" / aim to share more code

**How to Test This Feature Out**
TBD
