### ISSUE TITLE
[Epic] Bring client-side SSL certs to Mongo

### ISSUE THREAD

**Issue by metamben** [metabase/metabase#22889]
It is a common requirement for companies to create secure connections between clients and database servers.
With #18036, we have the necessary infrastructure to store secrets (passwords, keys, certificates). We use this mechanism to support client-side certificates for Postgres and Oracle.
In this project we want to add support for client-side SSL certificates for Mongo.

**Scope**
- Enable client-side certificates for Mongo database.
- Build the necessary Mongo infrastructure to test TLS support.

**Links**
- [product doc](https://www.notion.so/metabase/Bring-client-side-SSL-certs-to-Mongo-33ff830e71364f7dac5eba17d5ff6807)
- TLS support for other database types
  - #18320
  - #18968

**Implementation Plan**

- [x] Figure out how to configure MongoDB to use SSL and generate some public and private keys for that
- [x] Generate keys and certificates for the CA, Mongo (the server) and Metabase (the client)
- [x] Create/configure a Mongo Docker image requiring client-side TLS certificate
- [x] Implement getting the client-side TLS configuration from the Metabase UI
- [x] Implement getting the client-side TLS configuration from Metabase secret store
- [x] Add tests for client-side SSL and get them pass locally
- [x] Check in keys and certificates for the Mongo server so that CircleCI can access them
- [x] Check in keys and certificates for Metabase so that they are available during testing
- [x] Adjust `.circleci/config.yaml` to use the new image or new config options
- [x] Configure the frontend to allow client-side SSL configuration for Mongo
- [x] ~Add end-to-end test~

**How to Test This Feature Out**

_(include steps on how to test this project feature out, for someone unfamiliar with this work. please try to use the sample dataset when possible. this will serve as the basis for automated e2e tests, as well as the acceptance test to showcase the essence of this feature for bug bashes, etc)_

**Comment by mazameli** [comment]
It would be great if the steps in this plan were checkboxes so that it's easy for anyone to see what's done and what's left.
