### ISSUE TITLE
[Epic] Iterate on collections and sidebar

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#23222]
**Links**
- Product doc https://www.notion.so/metabase/Iterate-on-collections-and-sidebar-ca62a597c72e498bbc8702ad2f2a7179

**Implementation plan**

***Milestone 1: Improvements to pinned saved questions***
- [x] Show the title and improve the appearance of pinned questions while they’re loading https://github.com/metabase/metabase/pull/23240
- [x] Change the icon for the case when a user doesn’t have permission to see a pinned saved question
- [x] Allow users to prevent pinned questions from loading their visualization https://github.com/metabase/metabase/pull/23317
- [x] Show a nice icon instead of an error for pinned SQL questions with variables that don’t have default values https://github.com/metabase/metabase/pull/23339
- [x] Simplify visualizations for pinned questions https://github.com/metabase/metabase/pull/23352
- [x] Improve loading states for questions to match their visualizations https://github.com/metabase/metabase/pull/23352
- [x] BE - Allow users to disable previewing questions in collections (per question)
- [ ] FE - E2E tests for showing/hiding the visualization https://github.com/metabase/metabase/pull/23465

***Milestone 2: Improvements to collection content lists***
- [x] Improve the empty state for collections, and keep it from being a dead-end https://github.com/metabase/metabase/pull/23406
- [x] Add a “Dashboards” section heading above the pinned dashboards section https://github.com/metabase/metabase/pull/23457
- [x] Show descriptions for unpinned items in a tooltip https://github.com/metabase/metabase/pull/23444
- [x] Users should be able to pin and add a question to a dashboard using the “…” menu https://github.com/metabase/metabase/pull/23408
- [x] Clean up iconography of collection list items https://github.com/metabase/metabase/pull/23413
- [x] Get rid of checkbox animation https://github.com/metabase/metabase/pull/23413

***Milestone 3: Drag-and-drop improvements***
- [x] Get rid of this gross gray pancake state for collections when you’re dragging an item https://github.com/metabase/metabase/pull/23459
- [ ] ~Allow users to drag-to-move items in the sidebar and collection~
- [ ] ~Allow dragging an item to the Bookmarks section to add it to bookmarks~

***Milestone 4: Displaying and pinning sub-collections***
- [ ] ~Display sub-collections in the main content area of a parent collection, and allow them to be pinned (BE required)~

**API changes**

Add new `collection_preview` field on `Card`, `true` by default:

```
GET /api/card/:id // ideally other endpoints that return cards should also be affected
{
  ...,
  collection_preview: true // should be true by default
}

PUT /api/card/:id // should check that the question's collection is writeable by the current user
{
  collection_preview: false,
}

GET /api/collection/root/items?pinned_state=is_pinned
{
  data: [{
    ...,
    collection_preview: true // should return whatever was passed on PUT /api/card/:id, with true by default
  }]
}

GET /api/collection/:id/items?pinned_state=is_pinned
same as above

```

Add readonly `has_required_parameters` field to collection items (only):

```
GET /api/collection/root/items?pinned_state=is_pinned
{
  data: [{
    ...,
    // from the corresponding Card
    description: "...",
    // if structured query -> true
    // if native -> true if all required parameters have default values
    has_required_parameters: true 
  }]
}
```
