### ISSUE TITLE
[Epic] Remove ability for users to edit SSO created user info

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#23298]
It doesn't make much sense for users who logged in with SSO to be able to change their account information e.g. names, email since their information will already be synced each time users log in (correct me if I'm wrong, but basically SSO data will be syncing to Metabase). Being able to change their own account info makes the data out of sync with SSO providers.

**Links**
- product doc: https://www.notion.so/metabase/Remove-ability-for-users-to-edit-SSO-created-user-info-983a23b1f4654309a448fd6d90f8ac8f
- Issue links:
    - https://github.com/metabase/metabase/issues/15483
    - https://github.com/metabase/metabase/issues/16315

**Implementation Plan**

This is most likely a 99% FE-only project. But depending on how we currently determine SSO users this could involve BE.

***Milestone 1 - Implement FE***
- [x] Hide first name, last name, and email field on the account page when logged in with SSO
- [ ] Fix JWT, SAML users can still edit their info https://github.com/metabase/metabase/pull/23476

**How to Test This Feature Out**
#### SSO user
- [ ] Setup SSO, currently only supposedly supports Google auth and LDAP.
- [ ] Login with SSO
- [ ] Go to the account page, should not see first name, last name, and email field anymore.

#### email + password user
- [ ] Login with email + password
- [ ] Go to the account page, should still see first name, last name, and email field and edit them.
