### ISSUE TITLE
Improve schema/metadata sync and analysis

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2341]
* [ ] Provide status/progress of sync #649
* [ ] Sync more frequently #2329
* [ ] Prevent multiple simultaneous syncs #2337
* [ ] Perform quick schema sync before slower in-depth analysis
