### ISSUE TITLE
Refactor and completely remove legacy smoke tests

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#23429]
We have three remaining specs in `frontend/test/metabase/scenarios/smoketest/` folder. Those tests are legacy code and are mostly tech debt because they are:
1. Tightly coupled
2. Hard to refactor and hard to reason about
3. Most of the functionality covered there is already tested in other files

In the future, we can tag individual tests with `@smoke` and then run them all together.

### Definition of done
- all legacy smoke tests are either removed or moved to the appropriate folders
    - if we have to keep some of those tests, refactor them first and employ the best practices
- `frontend/test/metabase/scenarios/smoketest/` doesn't exist anymore
- remove `smoketest` group from CircleCI

### Tasks
Remove specs from `/smoketest` folder:
- [x] admin_setup.cy.spec.js
- [x] admin.cy.spec.js
- [x] user.cy.spec.js

**Comment by nemanjaglumac** [comment]
Instead of backporting every single PRs related to this epic, it makes more sense to finish everything first and then do a manual backport with all PRs.
