### ISSUE TITLE
[EPIC] Offer background and data download customization in public embeds

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#23477]
Public embedding customization is fairly limited in its current state. This is disappointing for customers that don’t need all the full-app embedding bells and whistles: namely exposing the query builder or offering drill-downs.

**Links**
- product doc: https://www.notion.so/metabase/Offer-background-and-data-download-customization-in-public-embeds-fa692c341fd54308b27180d523280997
- Issue links:
  - https://github.com/metabase/metabase/issues/9856
  - https://github.com/metabase/metabase/issues/6369

**Implementation Plan**

***Milestone 1*** Implement download data button visibility (PR: https://github.com/metabase/metabase/pull/23479)
- [x] Add a new toggle for download button visibility. [Ref](https://github.com/metabase/metabase/blob/fee02d34bba8fc5171340363302e8f78c64cfbac/frontend/src/metabase/public/components/widgets/DisplayOptionsPane.jsx#L71-L87)
- [x] Hide the button. [Ref](https://github.com/metabase/metabase/blob/947491320f6e35796c7901da6c61c3169c91f581/frontend/src/metabase/public/components/EmbedFrame.jsx#L102-L106)

***Milestone 2*** Implement transparent background color (PR: https://github.com/metabase/metabase/pull/23482)
- [x] Add a `tranparent` background option in embedding screen
- [x] Work on some CSS to propagate theme throughout the components

***Milestone 3*** Touchup (PR: https://github.com/metabase/metabase/pull/23561)
- [x] Remove **Download data** option from dashboard embedding screen. [Context](https://metaboat.slack.com/archives/CKZEMT1MJ/p1655908678259929?thread_ts=1655856289.399469&cid=CKZEMT1MJ)

**How to Test This Feature Out**
#### Embedding questions
1. Sign in as an admin
1. Enable [*Embedding in other applications*](http://localhost:3000/admin/settings/embedding_in_other_applications)
1. Open a saved question
1. Click the sharing icon and select **Embed this question in an application**
1. Select **Appearance** > **Transparent**: You should see a checkerboard pattern in the preview panel.
  ![image](https://user-images.githubusercontent.com/1937582/175908271-6578e560-32f5-4e2b-be72-6cefeea5271e.png)
1. *On OSS*, ensure that you still see the download button on the preview and there's no option to disable that.
1. *On Pro/Enterprise*, ensure you can see **Download data** toggle and toggle that will alter the download button visibility.
  ![image](https://user-images.githubusercontent.com/1937582/175908299-a4316b75-557a-4614-8aaf-cc41d3a964bc.png)

#### Embedding dashboards
1. Sign in as an admin
1. Enable [*Embedding in other applications*](http://localhost:3000/admin/settings/embedding_in_other_applications)
1. Open a dashboard
1. Click the sharing icon and select **Embed this dashboard in an application**
1. Select **Appearance** > **Transparent**: You should see a checkerboard pattern in the preview panel.
  ![image](https://user-images.githubusercontent.com/1937582/175908271-6578e560-32f5-4e2b-be72-6cefeea5271e.png)
1. *On both OSS and Pro/Enterprise*, ensure that there's no **Download data** option. Context: [We only show the download button on questions, but not dashboards](https://metaboat.slack.com/archives/CKZEMT1MJ/p1655908678259929?thread_ts=1655856289.399469&cid=CKZEMT1MJ).
