### ISSUE TITLE
[Epic] Better communicate embedding options in Admin settings

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#23498]
It’s not clear to customers what options are available for embedding and the best path to proceed to get value out of them. We get asked questions all the time along the lines: 

- “What is the difference between full-app and public embedding?”
- “How do I get started embedding in Metabase?”

Some of these questions are inevitable because embedding can be complex at times, but nonetheless, we can do a better job communicating our embedding offerings. This is especially true within Admin settings — which will be the focus of this particular project.

**Links**
- product doc: https://www.notion.so/metabase/Better-communicate-embedding-options-in-Admin-settings-cfb603f942f9402db1c7876d87574f25
- Issue links:
  - https://github.com/metabase/metabase/issues/4592

**Implementation Plan**

***Milestone 1: Sharing widget dead-end + Public sharing https://github.com/metabase/metabase/pull/23514***
- [x] https://github.com/metabase/metabase/issues/4592
- [x] Update admin embedding copy and layout
- [ ] ~Update copy layout in Public sharing~

***Milestone 2: Embedding***
- [x] Standalone embeds
  - [x] Update copy and layout
  - [x] OSS: mention about paid plan
- [x] Full-app embedding
  - [x] OSS: mention about paid plans
  - [x] EE: update copy and layout

***Milestone 3: New table design*** [(Cut from the scope)](https://metaboat.slack.com/archives/C03E8MQJZBM/p1656349072933959)
- [ ] Implement the new table design
  - [ ] Pagination
  - [ ] Sortable
  - [ ] Searchable
- [ ] Replace Public sharing with the new table
- [ ] Replace Embedding with the new table

***Milestone 4: Design touchup*** [(Cut from the scope)](https://metaboat.slack.com/archives/C03E8MQJZBM/p1656349072933959)
- [ ] Inline toggle: Needs either modify the existing component for handling settings or create a new component to handle this. (The first option seems easier)
- [ ] Make client-side navigation on sharing modal working. Context: [Slack thread](https://metaboat.slack.com/archives/C03E8MQJZBM/p1655994541648839)

**How to Test This Feature Out**
Follow the steps in [this integration tracker entry](https://www.notion.so/metabase/Better-communicate-embedding-options-in-Admin-settings-1c6070dfda644050bdf54f42855822f3)

**Comment by mazameli** [comment]
Looks like all the in-scope milestones and to-dos are done so I'm closing this as completed.
