### ISSUE TITLE
[Epic] Parameters in text cards

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#23543]
We want to allow dashboard parameter values to be interpolated in text cards, using the `{{}}` syntax already used for SQL template tags. Values should be substituted before Markdown is rendered, both on the frontend when displaying a dashboard and on the backend when rendering a dashboard subscription.

**Links**
- product doc: https://www.notion.so/metabase/Allow-putting-parameter-values-in-text-cards-eb291f6f411749a1b72f75e8a19a623d?showMoveTo=true
- Issue links: #6991

**Implementation Plan**

***Milestone 1 - Dashboards***
- [x] [FE/BE] Parse a text card to find template tags, and pull out the list of unique template tag names. (cljs?)
- [x] [FE] When in parameter-editing mode on a dashboard, display a dropdown with the list of template tag names, and allow them to be selected. (potentially need design?)
- [x] [FE/BE] Save mappings to the DB in the `parameter_mappings` field on a text card.
- [x] [FE/BE] Build a utility to format parameter values appropriately. (cljs?)
- [x] [FE] When displaying a text card, substitute parameter values prior to MD rendering.
- [x] [FE/design] UI to instruct users that they can add parameters to text cards (NEED DESIGN)
- [ ] Full formatting for the `date/all-options` parameter type

***Milestone 2 - Dashboard subscriptions/other backend work***
- [x] [BE] Before rendering a text card for a dashboard subscription, substitute parameters, using the same parameter-detection and formatting algorithms used by the frontend.
- [x] [BE] Fix interpolation of locked parameters on embedded dashboards (needs to be done on the BE)

***Milestone 3 - optional syntax***
- [x] [BE/FE] Allow text to be marked as optional using the `[[ ]]` syntax
