### ISSUE TITLE
[Tech] Remove whitelabel CSS colors

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#23954]
RFC https://www.notion.so/metabase/28-Remove-CSS-classes-with-brand-colors-22a83045ca144f12bd01ac8856a48de9

**Accent color migration**
- [x] Night mode colors https://github.com/metabase/metabase/pull/23958
- [x] Query builder and expression editor colors https://github.com/metabase/metabase/pull/23996
- [x] `accent1` https://github.com/metabase/metabase/pull/24220
- [x] `accent2` https://github.com/metabase/metabase/pull/24215
- [x] `accent3` https://github.com/metabase/metabase/pull/24002
- [x] `accent4` https://github.com/metabase/metabase/pull/24004
- [x] `accent7` https://github.com/metabase/metabase/pull/24058

**Brand utility classes migration**
- [x] `bg-brand-hover` https://github.com/metabase/metabase/pull/24427
- [x] `bg-brand-dark-hover` https://github.com/metabase/metabase/pull/24431
- [ ] `text-brand-hover` https://github.com/metabase/metabase/pull/24548 https://github.com/metabase/metabase/pull/24594
- [ ] `brand-hover`
- [ ] `border-brand-hover`
- [ ] `border-brand`
- [ ] `bg-brand-dark`
- [ ] `bg-brand-light`
- [ ] `text-brand-light`
- [ ] `bg-brand`
- [ ] `text-brand`

**Component classes migration**
- [ ] `Button--primary`
- [ ] `Button-group--blue`
- [ ] `Button-group--brand`

**Color deprecation**
- [ ] `text-white`
- [ ] `bg-white`

...
