### ISSUE TITLE
[Epic] Support template tags in sql snippets

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#23966]
When a snippet used in a native query includes a template tag, it should be added to the native query as though it were written in the query itself.

**Implementation Plan**
- [x] add `template_tags` to snippet entities
- [x] check for existence of snippet template tags when running a query that includes a parameter value for a snippet template tag 
- [ ] parse template tags in snippets and show them as parameters
- [ ] allow snippet template tags to be mapped to fields to create field filters
- [ ] handle mismatch between existing template tags in query and snippet template tags

**How to Test This Feature Out**
Will be described within individual PRs.
