### ISSUE TITLE
[INTERNAL] [E2E] Optimize `dashboard-filters` group execution time

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#24259]
### Tasks
- [x] Date (#24262)
- [x] Number (#24411)
- [x] Text / Category (#24428)
- [x] Location (#24433)
- [x] `parameters.cy.spec.js` (#24449)
- [x] Nested questions (#24457)
- [x] Consolidate all specs (#24472)
- [x] Misc (#24556)
- [x] Backport all changes in one PR (#24558)

### Results
|   | 1  | 2  | 3  | Average |
|---|---|---|---|---|
| Before  | [26:00](https://github.com/metabase/metabase/actions/runs/2749378196)  | [21:02](https://github.com/metabase/metabase/actions/runs/2719905582) | [29:33](https://github.com/metabase/metabase/actions/runs/2735322658)  | 25:32  |
| After | [13:08](https://github.com/metabase/metabase/actions/runs/2784910883)  | [15:44](https://github.com/metabase/metabase/actions/runs/2789353792)  | [12:52](https://github.com/metabase/metabase/actions/runs/2784841730)  | 13:55  |
|  Diff |   |   |   | **11:37**  |

Total number of Cypress files:
- Before: 37 (out of which 22 were reproductions)
- After: 28 (out of which 12 are reproductions)
