### ISSUE TITLE
[Epic] Serialization Enhancements in 45

### ISSUE THREAD

**Issue by bshepherdson** [metabase/metabase#24608]
# Serialization Enhancements

The previous Serialization epic #22641 built a new, more extensible, more principled foundation for (de)serialization of Metabase appdbs. Next we want to build several new features and enhancements on top of the foundation.

**To be expanded**

Here are some leftover tasks from the previous epic that should probably be solved here:
- [ ] Have a solid story for encryption, database secrets, etc., possibly with different `MB_ENCRYPTION_SECRET_KEY` on each end.
- [ ] Better story for `creator_id` and users under serialization. Eg. it may be that everything imported (or everything whose original owner can't be found) should be adopted by the importing user, or a `nobody@mycompany.com` user, or something like that.

And some testing notes:
- [ ] Find as many possible conflicts as I can think of; write tests for each and work with product to find and implement the right resolution.
- [ ] Generative testing - for each entity, generate random instances and round-trip them. (With and without entity IDs set.)

**Links**
- product doc: _link to product doc_
- eng doc: _link to technical design doc_
- feature branch: `branch-name` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_
- Issue links: _list of issues this should close when this is delivered_

**Implementation Plan**

***Milestone 1*** 
- [x] step 1
- [ ] step 2
- [ ] step 3

***Milestone 2***
- [ ] etc

**How to Test This Feature Out**

_(include steps on how to test this project feature out, for someone unfamiliar with this work. please try to use the sample dataset when possible. this will serve as the basis for automated e2e tests, as well as the acceptance test to showcase the essence of this feature for bug bashes, etc)_
