### ISSUE TITLE
[Epic] Static viz improvements

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#24759]
In the 45 release cycle we are going to:
1. Address open bugfixes related to static viz inconsistencies
2. Incorporate features to further polish supported chart types
3. Add support for new chart types

**Links**
- [product doc](https://www.notion.so/metabase/Further-polish-static-viz-and-add-support-for-new-charts-29e3a1d2c55a4bf39dc0b1e5a0b2d67f)
- [breakdown doc](https://www.notion.so/metabase/Static-charts-work-decomposition-f323ba1f264144a0baa1f085b706dfd8)
- Issue links: _list of issues this should close when this is delivered_

**Implementation Plan**

***Milestone 1: Blocking technical debt***
- https://github.com/metabase/metabase/issues/24671
- https://github.com/metabase/metabase/issues/24672

***Milestone 1: Existing charts improvements***
- [ ] [BE] https://github.com/metabase/metabase/issues/21503
- [ ] [FE] https://github.com/metabase/metabase/issues/20554
- [ ] [BE] https://github.com/metabase/metabase/issues/5433
- [ ] ...

***Milestone 2: Add new chart types***
- [ ] [BE] Support static row chart type
- [ ] [FE] Create a renderer for the static row chart

- [ ] [BE] Support static gauge chart type
- [ ] [FE] Create a renderer for the static gauge chart

**How to Test This Feature Out**

TBD
