### ISSUE TITLE
[Epic] Saved Question/Dashboard SerDes for Version Control

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#24766]
Design doc: https://www.notion.so/metabase/Serialization-pull-and-push-processes-metabase-cli-39e1aad815db404bad0aa5f589b7ff20

## Improved Saved Question/Dashboard SerDes

We want to make it possible to version control Saved Questions and Dashboards with something like Git, and moderate changes before they go live with something like GitHub or GitLab. 

### Offline Full-Instance Saved Question/Dashboard SerDes

This is what we *actually* want to implement in the short term

- [x] #24799
- [ ] For a specific collection
- [ ] Support serializing an object and its descendants
- [ ] CLI for "selective serialization" -- ask for ID or name or ?

### Stretch Goal: Individual Saved Question/Dashboard Live SerDes

Not strictly needed to support what we want here but I think it would make testing the new SerDes stuff a lot easier and be a potential killer feature

#### Preliminary work

- [ ] #24798

- Saved Questions
  - Live serialization
      - [x] #24773
      - [x] #24774
      - [x] #24775
   - Live deserialization 
      - Creating new Saved Questions
         - [x] #24776
         - [x] #24777
         - [x] #24778
      - Updating existing Saved Questions (upsert)
         - [x] #24779
         - [x] #24780
         - [x] #24781
- Dashboards
  - Live serialization
      - [x] #24782
      - [x] #24783
      - [x] #24785
   - Live deserialization 
      - Creating new Dashboards
         - [x] #24786
         - [x] #24787
         - [x] #24788
      - Updating existing Dashboards (upsert)
         - [x] #24789
         - [x] #24790
         - [x] #24791

   
### Open questions

- Do we need to add some sort of new permissions that would let people run ad-hoc queries for the purpose of getting their YAML, but not allow them to save them as Saved Questions? This way they'd have to go thru the post-YAML-as-PR process to get their changes in. 
- Do we need to support this for entire Collections as well? 
- Should there be an admin setting to enable/disable  the new SerDes buttons like "download YAML for this Saved Question"? Even if you aren't using SerDes it's still handy to be able to download and share the YAML for bug repro purposes for example.

Neat possibilities to consider when we get further along in the process

- Support buttons like "open a PR with this Saved Question" or "open a PR with these changes" to open a PR directly in GitHub instead of asking you to manually download and copy a YAML file to open a PR with it. Perms get tricky tho -- would it be a bot opening the PR?

## Related Epics

- #24792
- #24794
- #24795

**Comment by camsaul** [comment]
Closing as no longer relevant -- we decided to go a different route with the SerDes work as part of the 45 cycle.
