### ISSUE TITLE
[Epic] Allow users to manually reorder things in select chart types

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#24840]
This project involves updating the interface for chart settings options, Making chart breakouts more user friendly, and adding the ability to reorder breakouts in certain charts (something that currently needs to be done by modifying the SQL). Much of this work is purely visual and can be delivered independent of each other, which should be reflected by the implementation plan below.

**Links**
- product doc: https://www.notion.so/metabase/Allow-users-to-manually-reorder-things-in-select-chart-types-045b8c4c58054940a6ce8d7aab969f3b?d=ad3e00ba62af4babb31779a95f0ab390
- Issue Links: 
  - #2339 
  - #5401 
  - #7625
  - #19346
  - #13669

**Implementation Plan**

***Funnel Charts*** 
- [x] Update design for `<ChartSettingFieldPicker>` component and change steps label (I know the PR says funnel, but it affects this too) - https://github.com/metabase/metabase/pull/25035
- [x] Move Settings for Chart Fields into popover - https://github.com/metabase/metabase/pull/25125
- [x] Show a orderable list of column steps - https://github.com/metabase/metabase/pull/24948

***Bar Charts Row Charts, and Area Charts*** 
- [x] Update style of the add series breakout button and field picker - https://github.com/metabase/metabase/pull/25318
- [x] Show an orderable list for breakouts if the number of breakouts is below 20 - https://github.com/metabase/metabase/pull/25318
- [x] Drag and Drop x-axis and y-axis fields - https://github.com/metabase/metabase/pull/25563

***Tables***
- [x] Update style for Pivot Table toggel and Columns list - https://github.com/metabase/metabase/pull/24867
- [x] Move column settings to a popover - https://github.com/metabase/metabase/pull/25125
- [x] Update style for cell column select

***Pivot Tables***
- [x] Update styling - https://github.com/metabase/metabase/pull/25406
- [x] Move field settings to popover - https://github.com/metabase/metabase/pull/25125
- [x] Update styling for empty field section - https://github.com/metabase/metabase/pull/25406

**Comment by antoine-lizee** [comment]
Just noting that #25318 is great and will solve the problem of ordering series breakout manually, one by one. Yet it would be amazing to be able to **order by** the name of the series label themselves:
 - Very often, the series label are already ordered (because other graphs will have them in main dimensions, ordered by the query)
 - Series can be quite big and it will make it annoying to re-order by hand
 - [Optional, not sure] We could have a default sorting for all questions so that there is no need for additional tuning in most cases.
 - [Note / reminder:] This is not possible today with standard table ordering
