### ISSUE TITLE
[Epic] Basic Metric

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#24858]
Epic for basic Metric 

**Links**
- product doc: https://www.notion.so/metabase/Create-the-new-Metric-entity-6539b2977d764948b46ee7b629969bbd
- eng doc: tbd
- feature branch: `newmetric-schema`

**Implementation Plan**

***Milestone 1*** )
- [x] schema
- [x] model and api namespace (very scaffoldy so can be used by FE)
- [ ] temp UI for CRUD (having all team members able to create/edit/delete allows parallelization)
- [x] querying
- [ ] revision infra
- [ ] serdes infra (don't leave this until week before shipping)
- [ ] make sure we're compatible with toucan2
- [x] add to collections
- [x] pinned in collections (collection_preview, requires migration)
- [x] collection_preview (honestly not sure how this is different from pinned)
- [x] add time-interval support: (ability to filter the data based on the primary dimension's time range: ie, primary dimension is on created_at, be able to filter to rows created_at between X and Y). Would reuse the date parsing stuff we use for filters.
- [x] default time range
- [ ] widget in collections
- [ ] search
- [ ] proper UI
- [x] query validation
  - [x] granularity choice is allowed
  - [x] dimensions chosen are in the metric definition
  - [x] time-range is parseable
- [ ] better validation
  - [ ] granularities make sense
  - [ ] default granularities are in the set of granularities
  - [ ] dimension and measure belong to the underlying card
  - [ ] only one dimension is time? (or at least only one when querying), or really that granularity updates the default metric. (think primary dimension is created_at, but maybe a secondary dimension or ship date? could see orders in a month and then spread out orders shipped per week?) So if someone sent `granularity: month` that should update the primary dimension of `created_by` and not the `shipped_at` dimension)
  - [ ] replace the granularity in the query better (i'm using a crude walk)
  - [ ] validate time-range in query choices and default_time_range in db for metric

**Comment by dpsutton** [comment]
My test setup:

#### Additive Model
I have two questions that serve as suitable "raw data" for the metrics: Orders joined to people and products. Select the fewest columns you can to declutter everything. Ensure you _do_ select total (for the measure), created_at (primary dimension), products.category (secondary measure), products.vendor (secondary measure), user.state, user.source

This gives a nice flat table of things to see and a rich amount of groupings (category, vendor, state, source)

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/6377293/185696197-8d6a7b1c-1a29-4b64-b054-5ae687b383b0.png">

#### Non-additive Model
This is a query based on the reviews table joined to products. Again, select the fewest columns for clarity but do select: `rating`: this is the source for the primary measure, `created_at`, `products.vendor`, `products.category` and any others you might want:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/6377293/185696585-34df1e86-6dd8-4c7c-8471-759c27d851a8.png">


## Creating metrics
If there is no UI yet, you can use the api to create the metrics. You'll need to know field ids at the moment. An example metric is below: (using the excellent [https://httpie.io/](httpie)):

```bash
❯ http POST localhost:3000/api/newmetric Cookie:$COOKIE \
     name=revenue display_name="Revenue Metric" \
     description="Metric revenue groupable by category, vendor, and created_at" \
     measure:='["sum",["field",7,null]]' \
     dimensions:='[["created_at",["field",4,{"temporal-unit":"year"}]],["category",["field",26,null]],["vendor",["field",25,null]]]' \
     granularities:='["year","quarter","month","week"]' \
     default_granularity=year \
     card_id:=1 -pb
```

Some explanation:
- Cookie:$COOKIE Auth is easy in httpie. Just do `COOKIE=metabase.SESSION=a20ca6f7-5585-4669-9dec-88fecdb46780` (get this value from the network tab by finding a request to the app and checking the headers)
- ignore display_name. It's gonna go away
- measure: an aggregation clause. Simple ones are `["sum",["field",<created_at_id>,null]]'
- dimensions: a list of tuples of `[dimension-name dimension-clause]`. Dimension names are simple strings. Easier to not use spaces. Dimension clauses are field clauses (these will become literal `group by created_at`, `group by category`, etc. So just specifying a field is enough
- granularities: a list of the allowable granularities
- default_granularity: which granularity to use by default
- card_id: specify the source data (must be a saved question or model for now)
- -pb: instructs httpie not to print the response headers, just print the body

then you can query like so:

```shell
❯ http post http://localhost:3000/api/newmetric/1/query granularity=year Cookie:$COOKIE -pb
{
...
        "rows": [
            [
                "2016-01-01T00:00:00Z",
                42156.86924641866
            ],
            [
                "2017-01-01T00:00:00Z",
                205256.02167971394
            ],
            [
                "2018-01-01T00:00:00Z",
                510045.03417774575
            ],
            [
                "2019-01-01T00:00:00Z",
                577067.0478896814
            ],
            [
                "2020-01-01T00:00:00Z",
                176096.7100570686
            ]
        ]
```

and 

```shell
❯ http POST localhost:3000/api/newmetric/1/query dimensions:='["created_at", "category"]' granularity=year Cookie:$COOKIE -pb
{
        "rows": [
            [
                "2016-01-01T00:00:00Z",
                "Doohickey",
                9031.557803943726
            ],
            [
                "2016-01-01T00:00:00Z",
                "Gadget",
                10672.625619920136
            ],
...
]}
```
