### ISSUE TITLE
Data App Containers

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#24861]
## Links

- [product doc (internal)](https://www.notion.so/metabase/Create-the-Data-App-container-f62783232ef0430b8527c74a2909d0b5)
- [initial design discussion (internal)](https://www.notion.so/metabase/App-Containers-2fb829e26e224bef9c891c6c97d97b0a)

### Milestone 1

**Goal:** make the app container working E2E reusing as much code we already have

**Backend**

- [x] #24880
- [x] #24879
- [x] #24941
- [x] #24951
- [x] #24981

**Frontend**

- [x] #24918
- [x] #24919
- [x] #24920
- [x] #25011
- [x] #24866

### Backlog

**Backend**

- [x] Allow selecting a homepage for an app
- [x] Support custom order for `app_nav` items
- [x] Allow marking some `app_nav` items as hidden for "view" mode (i.e. "not-editing" mode)
- [ ] Allow bookmarking apps and pages
- [x] #25097
- [x] Support external arbitrary links in `app_nav` (bonus)

**Frontend**

- [ ] Implement basic `app` entity actions (rename, change description, archive)
- [ ] Implement proper page creation flow (opening a blank page instead of a creation modal)
- [x] #25365
- [ ] Implement data app "preview" page (the one at `/apps/:id` as opposed to the launched mode)
- [ ] Fix state sync issues on the FE (e.g. archiving or renaming a data app won't be immediately reflected on the UI)
- [ ] Allow selecting a homepage for an app
- [ ] Support custom app URLs
- [ ] Implement app editing mode (this one should probably be broken down into smaller todos)
- [ ] #25456
- [ ] Implement hiding some items in app nav (mark some items as hidden for view mode, un-hide, don't show hidden items)
- [x] #25173
- [ ] Support sidebar drag-n-drop for apps
- [ ] Support external arbitrary links in app nav (bonus)
- [x] #25210
- [ ] Handle case when opening `/collection/:id` page and the collection is actually an app collection (404 / redirect to app?)
- [ ] Fix UI uses "collection" wording for archive flow
- [ ] Allow unarchiving apps
