### ISSUE TITLE
[Epic] Bring select chart types closer to feature parity

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#24877]
Some chart types, row charts in particular, are painfully behind others in terms of different functionality. The main places where we would like to reach parity are with allowing multiple series, stacked charts, and goals for row charts. Bringing labels to for pie, row, and scatter charts. And adding conditional formatting to pivot tables.

**Links**
- [product doc](https://www.notion.so/metabase/Bring-select-chart-types-closer-to-feature-parity-2963dfd2814946f18f403df30c2d6276)
- Issue links: 
    - https://github.com/metabase/metabase/issues/15693
    - https://github.com/metabase/metabase/issues/4588
    - https://github.com/metabase/metabase/issues/10967
    - https://github.com/metabase/metabase/issues/5855
    - https://github.com/metabase/metabase/issues/12977

**Implementation Plan**

***Milestone 1: Add conditional formatting to pivot tables*** 

- [x] https://github.com/metabase/metabase/pull/24930
- [x] https://github.com/metabase/metabase/pull/25882

***Milestone 2: Revamp the row chart type*** 
- [x] https://github.com/metabase/metabase/pull/25829 — contains components & data transformation logic for the main app chart
- [x] https://github.com/metabase/metabase/pull/25925
- [x] https://github.com/metabase/metabase/pull/25408
- [x] https://github.com/metabase/metabase/pull/26146

***Milestone 3: Add data labels to pie charts***
- [x] https://github.com/metabase/metabase/pull/25009

***Milestone 4: Add data labels to scatter charts***
- [FE] Add data labels to scatter charts — punted
