### ISSUE TITLE
Toucan 2 prep

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#24914]
Get ready for the switch to Toucan 2 by doing a little prep work.

- [x] Don't invoke Toucan models as functions (PR #24913)
- [x] Don't call `type` or `class` on Toucan models (PR #24915)
- [x] Don't use Toucan `<Model>Instance` classes (PR #24916)
- [x] Convert permissions-related methods like `metabase.models.interface/can-read?` from protocols to multimethods (PR #24917)
- [x] Convert `metabase.models.revision/IRevisioned` from a protocol to multimethods (PR #25108)
- [x] Enable unresolved symbol linter for tests (to catch stuff that should be disallowed like `map->ModelInstance`) (PR #25120)
- [x] Convert `metabase.models.serialization.hash/IdentityHashable` from a protocol to a multimethod (PR #25870)
- [x] some sort of wrapper macro for implementing `IModel` (PR: #27474)
- [x] Introduce Toucan 2-compatible hydration method definition macro (PR #27475)
- [ ] Create multimethod for serializing model instances to JSON and use that instead of implementing `add-encoder` directly
- [ ] `collection/allowed-namespaces` should dispatch off of model, not `(class model)`
- [x] Switch to Honey SQL 2, or implement a Toucan 2 Honey SQL 1 backend (PRs: #27619,  #27543)
- [x] Don't use models inside of Honey SQL queries (PRs: #27619,  #27543)

**Comment by camsaul** [comment]
finished
