### ISSUE TITLE
[Apps] Allow for action customization and form creation

### ISSUE THREAD

**Issue by snoe** [metabase/metabase#25020]
## Links
- [product doc](https://www.notion.so/metabase/Allow-for-action-customization-and-form-creation-394b911d89d045e7b7287cc40a7d29c3)

### Milestone 1

**Goal**: Add actions to pages, get back to writeback functionality in a non-hacky way

#### Backend
- [x] #25001 

#### Frontend

- [x] #25234
- [x] #25329
- [x] #25235
- [x] #25236
- [ ] [App] Configure a page redirect or refresh on success

### Milestone 2

**Goal**: Add form customization to query actions

#### Backend
- [x] #25042 

#### Frontend

- [x] UI to create a custom action https://github.com/metabase/metabase/pull/24997
- [x] UI to update a custom action https://github.com/metabase/metabase/pull/25074
- [x] UI to configure form field types for each parameter https://github.com/metabase/metabase/pull/25119
- [x] Updates to get parameters and execution working properly https://github.com/metabase/metabase/pull/25297
- [x] Connect action form settings to dashboard form modal https://github.com/metabase/metabase/pull/25344
- [x] UI to configure placeholders for each parameter https://github.com/metabase/metabase/pull/25407
- [x] UI to set whether parameters are required and define default values https://github.com/metabase/metabase/pull/25445
- [x] Allow Forms to be inline https://github.com/metabase/metabase/pull/25579 https://github.com/metabase/metabase/pull/25567
- [ ] allow button customization from the action creator
- [ ] allow error message customization
- [x] drag and drop form field reordering
- [ ] allow custom form titles and additional explanatory text
- [x] allow data reference access in popover

### Milestone 3

**Goal**: Add form customization to http actions

#### Backend
- [ ] possibly nothing

#### Frontend

- [ ] [App] UI to configure form for entering parameters
- [ ] [App] UI to configure presenting the action as an inline form, within a modal, with a confirmation dialog, or just a button
