### ISSUE TITLE
[Epic] Create a model without a question

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#25049]
Although we use questions to back models, the expectation of our customers is to create a model before asking questions. So the current way of turning questions into models feels backwards and is also hidden in the question configs. We want to make model creation a first-class citizen in the Metabase navigation, starting from the `+New` action.

Branch: `feature-25049`

**Links**
- [product doc](https://www.notion.so/metabase/Create-a-model-without-a-question-33f80933060a4a1b9f169769020b0b48)

**Implementation Plan**
- [ ] Auto pin created model to collection
- [x] Have cancel button behave coherently with create model
- [x] Disable clicking on metadata until we have a query (is that a sufficient condition?)
- [x] Do not show main app header in fresh model pages
- [x] https://github.com/metabase/metabase/pull/25799
- [x] https://github.com/metabase/metabase/pull/25817
- [x] Don't offer to add to Dashboard after saving
- [x] https://github.com/metabase/metabase/pull/25718
- [x] https://github.com/metabase/metabase/pull/25720
- [x] #25598
- [x] #25600
- [x] #25602

**Comment by daltojohnso** [comment]
Work should maybe be split up like...
1. create the `/model/new` route where users select btwn simple and native questions. Seems like we can reuse a lot of what's in `NewQueryOptions` but with a `to={Urls.newModel({ ... })}` instead of a `to={Urls.newQuestion({ ... })}`
2. We need a modal for the last step of model creation. Could reuse `SaveQuestionModal` since the logic shouldn't be very different, but will need to update copy. Need to update the `handleSave` function in `DatasetEditor` to open the modal when the model is unsaved.
3. other stuff... minor ui work, maybe like updating the `DatasetEditor` button text, but I think we get most of what's left for free

**Comment by mazameli** [comment]
I'm calling this done.
