### ISSUE TITLE
[Epic] formalize "virtual tables"

### ISSUE THREAD

**Issue by daltojohnso** [metabase/metabase#25048]
The notion of a "virtual table" (vs a real, "concrete" table that exists in a database connected to your Metabase instance) has evolved over time, especially with the introduction of new features that use nested cards as tables, like Models. This concept hasn't been formalized in our code, and this lack of formalization has been a cause for a lot of complexity around accessing the fields on tables and is at the root of a number of Models bugs. The work in this epic intends to formalize "virtual" tables in such a way that will eradicate a class of gnarly nested card/models bugs.

**Implementation Plan**

***Milestone 1*** cleanup (2 days)
- [x] remove field creation logic from `FieldDimension` (https://github.com/metabase/metabase/pull/25109)
- [x] clean up `StructuredQuery` and `NativeQuery` table methods -- split into separate file, write functions that are... functional, and thoroughly unit test

***Milestone 2*** class extension (2 days)
- [x] Investigate the possibility of extending `Table` (or a new abstract class) for the various use cases... concrete tables, native mode structured query tables, etc. -- update: not worth the time investment
- [ ] ~Assuming the above is feasible, implement the new class extension~

***Milestone 3*** caching bugs (1 day)
- [ ] ~solve nested card table fields caching issue via normalizr's `mergeStrategy`~
- [ ] ~(or) solve the caching issue via the use of multiple schemas~
- [x] (or) solve the caching issue via a new identifier property on `fields`*

**Comment by mazameli** [comment]
Nice. Micro thing, but let's leave epics off of the weekly tactical board, and instead add PRs that close to-do items in this epic to the tactical board.
