### ISSUE TITLE
[Apps] Scaffolding data-apps

### ISSUE THREAD

**Issue by snoe** [metabase/metabase#25070]
We want to be able to build out a functioning App given a list of starting tables. They should link to each other, provide implicit actions, and provide default filters.

## Links
- product doc
- [design](https://www.figma.com/file/rbjE1U9kb6IhJQNBY08PAz/Data-Apps-Exploration?node-id=364%3A15079)

### Milestone 1
**Goal**: Create a new app with empty list and detail pages given a set of tables

#### Backend
- [x] [Apps] Create new app scaffold endpoint, creates app nav items, and pages

#### Frontend
- [x] #25293

### Milestone 2
**Goal**: Fill in the scaffolded pages with components

#### Backend
- [x] [Apps] Add pk filters to Detail scaffold pages
- [x] [Apps] Add implicit actions Dashcards to scaffold pages
- [x] [Apps] Add parameterized titles

 **The following may be different depending on implicit view implementation** 

- [x] [Apps] Add List Question + Dashcard to List scaffold pages
- [x] [Apps] Add Object Question + Dashcard to Detail scaffold pages
- [x] [Apps] Add click behavior to scaffolded Lists to link to Details with pk filter
- [x] [Apps] Add implicit actions to scaffolded List rows
