### ISSUE TITLE
[Epic] Clean up and add view-details action to drill-through menus on unaggregated rows

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#25305]
**Links**
- [Product doc](https://www.notion.so/metabase/Clean-up-and-add-view-details-action-to-drill-through-menus-on-unaggregated-rows-63cd958ec5884127a991b7af1d9435b3)

**Implementation plan**
- [ ] Change quick filters heading
- [ ] Change quick filters for non-numeric types
- [ ] Add view details for each column
- [ ] Change click actions styles
- [ ] Add filter popover for long text
