### ISSUE TITLE
[Apps] Permissions

### ISSUE THREAD

**Issue by snoe** [metabase/metabase#25420]
## **Links**
- [product doc](https://www.notion.so/metabase/Implement-Data-Apps-Permissions-732e27313df14ec99a10d7603026a4f2)
- [eng doc](https://www.notion.so/metabase/Permission-Tasks-9fd88a803bed4a3a9a3d75ca1f07b971)

### Milestone 1

**Goal: Add new permissions to regex/schema/lists **

#### Backend
- [ ] [Apps] Add /app/* permissions
- [ ] [Apps] Add /db/:id/execute permission
- [ ] [Apps] Add /db/:id/schema/…./execute permission
    - custom vs implicit open question

#### Frontend  
- [ ] [Apps] Add top level App permissions UI
- [ ] [Apps] Add column to Data permissions UI for custom action execution permission
- [ ] [Apps] Add column to Data table permissions UI for implicit action execution permission
    - custom vs implicit open question

### Milestone 2

**Goal: Use app permissions and avoid running into collection permissions**

#### Backend  
- [ ] [Apps] Add /app routes
   - check app permission, set app context for query and execution
- [ ] [Apps] Modify actions processor to check app permission same as query processor.
- [ ] [Apps] Check blocking permissions for execute
- [ ] [Apps] How to run queries to check app and data permission instead of collection permission (how to modify ``query-processor.middleware.permissions/check-query-permissions`` to use `/app/:id/use` instead of ``/collection/:id/read`` in app context)

#### Frontend
- [ ] Modify all in-app calls to use `/api/app/*` routes
