### ISSUE TITLE
[Epic] Improve the visualization settings user experience

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#25453]
Identify and address low-hanging fruit in Visualization Settings to make things more intuitive, joyful, and consistent across different viz types.

**Links**
- [product doc](https://www.notion.so/metabase/Improve-the-visualization-settings-user-experience-8e1fb8fadb3f4cd9ba79e3bad7b2847b?d=0e9ef9c7028f4f67902bb7713db8873d)
- Viz settings migrations logic [doc](https://www.notion.so/metabase/Viz-settings-questions-migration-logic-728d4468412746b2bf7321d29d482d12) 

**Implementation Plan**

***Milestone 1: cheap FE-only quick wins*** 

- [x] [FE] Adjust pivot tables copy https://github.com/metabase/metabase/pull/25650
- [x] [FE] Always provide placeholder examples https://github.com/metabase/metabase/pull/25649
- [x] [FE] Placeholders and link to custom maps https://github.com/metabase/metabase/pull/25708
- [x] [FE] Change “Which axis?” to “Y-axis position” https://github.com/metabase/metabase/pull/25652
- [x] [FE] Standardize the types of radio buttons, button groups, etc. (ensure it looks fine in locales with longer strings) https://github.com/metabase/metabase/pull/25664
- [x] [FE] Remove “Add breakout” from Waterfall charts
- [x] [FE] Hide stacking options when there is one series https://github.com/metabase/metabase/pull/25654

### Milestones below for 0.46

***Milestone 2: General settings navigation — series settings and axes*** (https://github.com/metabase/metabase/issues/26887)
- [x] [FE] Merge Axis and Labels tab https://github.com/metabase/metabase/pull/25886
- [x] [FE] Consolidate series settings in a single place which includes:
    - [x] Series renaming
    - [-] Add a separate field for a breakout and move breakouts reordering widget to Y-axis
    - [x] Move all series settings under `...` menu

***Milestone 3: General settings navigation — table settings "add all"/"hide all"*** (https://github.com/metabase/metabase/issues/26889)

- [ ] [FE] Add an “Add all” and “Hide all” button to columns in Table settings
- [ ] [FE] Add e2e tests

***Milestone 4: General settings navigation — New viz type selection UI*** (https://github.com/metabase/metabase/issues/26890)

- [x] [FE] Implement new viz type selection UI
- [x] [FE] Add e2e tests

## Milestones below this point got cancelled

***Milestone 5: Remove viz type switches that do not change question types*** https://github.com/metabase/metabase/issues/26906
⚠️ Implement this milestone in a feature branch FE + BE together

- [FE] Remove “Stacking” settings (UI control + logic that use related settings values)
- [FE] Remove viz type series switches (UI control + logic that use related settings values for line/area/bar charts except combo chart)
- [BE] Migrate question types based on visual settings: [migration logic](https://www.notion.so/metabase/Viz-settings-questions-migration-logic-728d4468412746b2bf7321d29d482d12#f038a28490484d4db328dbaa2fd1917f). 

***Milestone 6: Conditional formatting*** https://github.com/metabase/metabase/issues/29008
⚠️ Implement this milestone in a feature branch FE + BE together

- [FE] Implement the new UI in which 1 rule can have only a single column
- [BE] Implement [viz settings](https://www.notion.so/metabase/Viz-settings-questions-migration-logic-728d4468412746b2bf7321d29d482d12#c53dc094942c4aa49d3336a8270e3c8f) migration

**Comment by cdeweyx** [comment]
Closing out this super-epic since all three remaining milestones have relevant info contained in their own epics:
- https://github.com/metabase/metabase/issues/26889
- https://github.com/metabase/metabase/issues/29008
- https://github.com/metabase/metabase/issues/26906
