### ISSUE TITLE
[Epic] Associate actions with models

### ISSUE THREAD

**Issue by metamben** [metabase/metabase#25487]
## Links

- Product doc (internal) [Closely associate actions and tables/models](https://www.notion.so/metabase/Closely-associate-actions-and-tables-models-579624779cb74b23bc58be7478b37d26)
- Related product doc (internal) [Enable implicit actions and views for data models](https://www.notion.so/metabase/App-Containers-2fb829e26e224bef9c891c6c97d97b0a)

### Milestone 1

**Goal:** associate actions with models

- [ ] Define a representation for empty models (i.e., w/o query/card)

**Backend**

- [ ] Create migration for actions pointing to their container model
  - [ ] Create empty model to accommodate existing actions (if we keep them)
  - [ ] Put actions without model under an empty model (or delete them)
- [ ] Adjust `POST` action endpoints to take the owner model ID
  - [ ] Check if the model is eligible 
- [ ] Hydrate actions in `GET` card endpoints
- [ ] Implement list and CRUD endpoints for empty models

**Frontend**

- [ ] Filter actions for model
- [ ] Create actions with model ID
- [ ] Allow models to be added to apps
- [ ] ...

### Milestone 2

**Goal:** Attach CUD actions to model

**Backend**

- [ ] Create migration for flagging actions as CUD
- [ ] Adjust `GET` card endpoints to return CUD actions
- [ ] Adjust `PUT` card endpoint to take CUD actions
- [ ] When scaffolding refer to the CUD actions if any

**Frontend**

- [ ] ...
