### ISSUE TITLE
[Epic] Prevent auto-apply filters in slow dashboards

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#25506]
**Links**
- Product doc https://www.notion.so/metabase/Prevent-auto-apply-filters-in-slow-dashboards-cc02d90dac9e42ee91f34c2a9810212f

**Implementation plan**
- [ ] BE - Add `auto_apply_filters` for dashboards
- [ ] FE - Add a setting to toggle auto-apply filters in dashboards (enabled by default)
- [ ] FE - Add a button to apply filters when the setting is disabled
- [ ] FE - Highlight filters that are changed since the last request
- [ ] FE - Add a notification about a slowly loading dashboard and suggest to turn off the setting

**API changes**
- Add a boolean field `auto_apply_filters` to `PUT /api/dashboard/:id`. 
- It should be returned where a dashboard is returned, e.g. in `GET /api/dashboard/:id`
