### ISSUE TITLE
[Epic] metabase-lib consolidation

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#25618]
The business logic is spread across the entire app while it should be in `metabase-lib` folder.

**Milestone 1 - move MBQL manipulation logic**
- [x] https://github.com/metabase/metabase/pull/25761
- [x] https://github.com/metabase/metabase/pull/25774
- [x] https://github.com/metabase/metabase/pull/25766
- [x] `query_builder/components/filters/pickers/DatePicker` folder @daltojohnso 
- [x] https://github.com/metabase/metabase/pull/25777
- [x] `modes` folder @ranquild 
- [x] `schema_metadata.js` @daltojohnso 
- [x] `metabase/lib/types.js` @daltojohnso 
- [x] `services.js`  @ranquild
- [x] `datamodel/FieldRemapping.jsx` @ranquild 
- [x] `datamodel/PartialQueryBuilder.jsx`@ranquild
- [x] `lib/click-behavior.js` @ranquild
- [x] `lib/data-modeling/utils.js` @ranquild
- [x] `parameters/utils/targets.ts` @daltojohnso 
- [x] `parameters/utils/mapping-options.js` @daltojohnso 
- [x] `DashboardClickDrill` @ranquild
- [x] `DatePicker`, `SingleDatePicker`, `RangeDatePicker` @ranquild 
- [x] `metabase/query_builder/components/Filter.jsx` @daltojohnso  

**Milestone 2 - reduce metabase-lib dependencies on metabase**
- [x] `metabase/entities/questions` @ranquild 
- [x] `metabase/lib/saved-questions` @ranquild
- [x] `metabase/lib/expressions` folder @ranquild
- [x] `metabase/modes/lib/modes` @ranquild
- [x] `metabase/parameters` folder @daltojohnso   
- [x] `metabase/lib/schema` @ranquild
- [x] `metabase/lib/schema_metadata` @ranquild
- [x] `metabase/lib/string` @ranquild 
- [x] `metabase/lib/engine` @ranquild
- [x] `metabase/writeback` @ranquild
