### ISSUE TITLE
[Epic] Metabase development mode

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#25660]
# Context
This project belongs to the long-arch of serialization for git integration.
As users will develop Metabase objects locally, we need a special local development mode with some modifications to let them work.

- [Product Doc](https://www.notion.so/metabase/Metabase-local-development-mode-2f3f8d1304c94a0a88070a99347ec895)
- [User flow](https://www.notion.so/metabase/Serialization-flow-858cb8f74dd94125a0873b201358585c)
- [FE Work](https://www.notion.so/metabase/FE-work-for-development-mode-cb5f0f9b6a9a48678470d138984778ba)

## Goals
- Remove all background processes (sync, scanning, model caching, alerts and subscriptions)
- A UI element to dump/load
- A visual differentiation from the production instance
- Skip setup and tutorial messages

# Tasks
- #25349
- #25640
- #26052
- [ ] Visual element to differentiate the development mode
- [ ] Skip setup/tutorial messages in development instances
- [ ] Wire everything with a `--dev` flag

**Comment by luizarakaki** [comment]
Closing this issue as the 45 PRs are merged. I'll create a new one for the planned work for 46.
