### ISSUE TITLE
Migrate driver tests to GitHub Actions workflows

### ISSUE THREAD

**Issue by ariya** [metabase/metabase#25781]
Primary motivations:

* Near-zero <sup>(1)</sup> cost, thanks for the free, unlimited Actions for open-source projects
* The tests also run for external <sup>(2)</sup> contributor's PRs
* The tests won't run for PRs (still) marked as draft

Tasks:

* [x] #25769 (Druid, MariaDB, Mongo, MySQL, Postgres, Spark, SQLite, SQL Server)
* [x] Migrate Mongo driver tests involving SSL (https://github.com/metabase/metabase/pull/27147)
    * ~~Depends on https://github.com/metabase/metabase-qa/pull/21~~
* [x] Migrate MySQL driver tests involving SSL (https://github.com/metabase/metabase/pull/27071)
* [x] Migrate Presto JDBC tests (#27164)
* [x] Migrate BigQuery tests (https://github.com/metabase/metabase/pull/27162)
* [x] Migrate Google Analytics tests (#27151)
* [x] Migrate Oracle tests (#27149)
* [x] Migrate Redshift tests (#27151)
* [x] Migrate Snowflake tests (https://github.com/metabase/metabase/pull/27103)
* [x] Migrate Vertica tests (https://github.com/metabase/metabase/pull/27148)
* [ ] Make new workflows required
* [x] Mirror new workflows in the skipped-tests (https://github.com/metabase/metabase/pull/27269)
* [ ] Move from Circle CI's database images to the official ones

This follows other recent migrations, e.g. E2E tests (#21100), backend tests (#19786, #14701), shared CLJS tests (#19854), frontend tests (#15507, #14050), smoke tests (#15792), etc.

Footnotes:
* <sup>(1)</sup> For some database, e.g. Spark, we need beefier CI machine. GitHub-own runner won't work, and hence we ought to use Buildjet (not free, but still very reasonable cost), which we already use sparingly anyway for other CI runs.
* <sup>(2)</sup> This is the case for tests of containerized-able database (e.g. Postgres, Mongo, etc). For cloud database (e.g. Redshift, Snowflake), the external contributor's PR won't run them.

**Comment by camsaul** [comment]
We don't need to 

> Move from Circle CI's database images to the official ones

since they're publicly available Docker images mostly based on the official ones anyway. We can move over whenever we feel like it

**Comment by camsaul** [comment]
This is done now as of https://github.com/metabase/metabase/pull/27149 -- the only thing left in CircleCI is a dummy job
