### ISSUE TITLE
Initialize Metabase with config from file follow-ons

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#26038]
Follow-ons to #2052/#25986:

- [x] Feature flag behind appropriate Enterprise/Pro token feature `:advanced-config` (PR #26463)
- [x] move some `metabase.config.file` impl code to EE namespaces (PR #26108, PR #26461)
- [ ] Document v1 of the config file spec, or come up with a plan for this 
    - [ ] A sample/template config file 
- [x] Support skipping sync when creating new Databases. So SerDes can do it's thing. (PR #26110)
- [x] Second launch with users in config file overwrites the password with plaintext password and login is impossible (PR https://github.com/metabase/metabase/pull/26105)
- [x] Add support for specifying Settings in a config file (PR #26109)
- [x] Need a list of all possible Settings that can be set (filter out read-only settings; we want to generate a list like https://github.com/metabase/metabase/blob/master/docs/configuring-metabase/environment-variables.md; so add keys for extra info) (PR #26428)
- [x] Always apply `:settings` first (PR #26462)

#### Possible follow-ons/open questions

- [ ] Should upsert vs. no-op be an option?
- [ ] We should warn if the setting is set via environment variable and it will be ignored in the config file 
- [ ] Add a command to init from file without having to launch Metabase? Or otherwise make it easier to use in concert with SerDes
- [ ] Support SerDes options such as the Collection IDs for selective deserialization? Should we add a `deserialize:` section to the config file to invoke SerDes on launch? 🤔 Or just make Settings for SerDes options so you can set them in `settings:`

**Comment by camsaul** [comment]
Closing this since all the important parts were implemented
