### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#26102]
@ariya made an initial draft of the release script in https://github.com/metabase/metabase/pull/23274

## The Next Steps
_The full list TBD:_
- [ ] Trigger the script manually and rely on the commit hash, rather than on the tag (#26101 )
- [ ] Make the script automatically handle tagging (the certain commit)
    - Make sure the tag doesn't already exist to prevent automatic tag overwriting
    - Make sure both oss and ee tags are applied to the same commit
    - Add (a regex?) tag format check
- [ ] Add additional checksum verifications for the uberjar
- [ ] ...

**Comment by nemanjaglumac** [comment]
Deprecated.
@iethree owns this now.
