### ISSUE TITLE
[Epic] Migrate entity forms to formik

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#26178]
Currently our forms mostly use an internal form framework. The goal is to migrate them to react components and use formik directly.

**User forms**
- [x] `NewsletterForm` https://github.com/metabase/metabase/pull/26192
- [x] `ForgotPassword` https://github.com/metabase/metabase/pull/26204
- [x] `ResetPassword`  https://github.com/metabase/metabase/pull/26214
- [x] `UserStep` https://github.com/metabase/metabase/pull/26215/
- [x] `DatabaseStep` https://github.com/metabase/metabase/pull/26216
- [x] `UserPasswordForm` https://github.com/metabase/metabase/pull/26228
- [x] `UserProfileForm` https://github.com/metabase/metabase/pull/26231
- [x] #35605

**Timeline forms**
- [x] `NewTimelineModal`, `EditTimelineModal` https://github.com/metabase/metabase/pull/26247
- [x] `NewEventModal`, `EditEventModal` https://github.com/metabase/metabase/pull/26264

**Collections**
- [x] `CollectionCreateForm` #26820

**Dashboard forms**
- [x] `CreateDashboardModal` #26770

**Snippet forms**
- [x] `SnippetModal` #26928
- [x] `SnippetCollectionModal` #26930

**Data app forms**
- [x] `ActionCreator` @iethree 
- [x] ~`DataAppNavBarContainer`~ (no longer exists)

**Setting forms**

There is some overlap with our settings "framework".
- [x] `SlackSetupForm`, `SlackStatusForm` https://github.com/metabase/metabase/pull/26273
- [x] `SettingsGoogleForm` https://github.com/metabase/metabase/pull/26293
- [x] `SettingsSAMLForm` https://github.com/metabase/metabase/pull/35731
- [x] `SettingsJWTForm` https://github.com/metabase/metabase/pull/35969
- [x] `SettingsLdapForm` https://github.com/metabase/metabase/pull/36054
- [x] #41593

**Database forms**
- [x] https://github.com/metabase/metabase/pull/26766
- [x] https://github.com/metabase/metabase/pull/26818
- [x] https://github.com/metabase/metabase/pull/26923

**Query builder forms**

- [x] https://github.com/metabase/metabase/pull/30418
- [x] #41539

**Entity Form**
- [x] #35966
- [x] #41848
