### ISSUE TITLE
[Epic] Data Apps v1

### ISSUE THREAD

**Issue by brunobergher** [metabase/metabase#26344]
This is the work we need to do in order to get Data Apps ready for release.
Work is broken out by themes and prioritized within each theme. If you’re unsure about prioritization, ask on Slack.
We'll update this list as we go along, after every demo and in the beginning of every week.

### Starting/Scaffolding

- [ ] #26590
- [ ] #26435
- [ ] #26436
- [x] #26700
- [x] https://github.com/metabase/metabase/issues/26577
- [x] #26380
- [x] #26345
- [x] #26375

### Actions
- [x] #26452
- [ ] https://github.com/metabase/metabase/issues/26582
- [ ] https://github.com/metabase/metabase/issues/26580
- [ ] #26450
- [ ] https://github.com/metabase/metabase/issues/26588
- [ ] #26451
- [ ] #26699
- [x] https://github.com/metabase/metabase/issues/26581
- [x] https://github.com/metabase/metabase/issues/26583
- [x] #26589
- [x] #26437
- [x] #26438
- [x] #26448
- [x] #26449
- [x] #26439
- [x] #26406
- [x] #26453
- [x] #26346
- [x] #26347
- [x] #26349
- [x] #26350

### Action Forms
- [x] #26724

_to avoid wasted effort, these 👇 should probably be blocked by moving action forms to the new form framework ☝️_
- [ ] https://github.com/metabase/metabase/issues/26701
- [x] https://github.com/metabase/metabase/issues/26579
- [x] https://github.com/metabase/metabase/issues/26585
- [ ] #27376
- [ ] #27387
- [ ] #27384
- [ ] #27386

**FormCategoryInput**
- [ ] #26441
- [ ] #27377

### Pages, Views

- [ ] #26730
- [ ] #26355
- [ ] #26356
- [ ] #26443
- [ ] #26444
- [ ] #26445
- [ ] #26446
- [ ] #27082
- [x] #26488
- [x] #26354
- [x] #26440
- [x] #26442
- [x] #26447
- [x] #26358
- [x] #26376

### Navigation

- [ ] #26454
- [ ] #26362
- [ ] https://github.com/metabase/metabase/issues/26587
- [x] #26455
- [x] https://github.com/metabase/metabase/issues/26578
- [x] https://github.com/metabase/metabase/issues/26584
- [x] #26456
- [x] #26361
- [x] #26363
- [x] #26364
- [x] #26366 

## Completeness opportunities (non-blocking)

- [x] #26478
- [ ] #26479
- [ ] #26480
- [ ] #26481
- [ ] https://github.com/metabase/metabase/issues/26586
- [x] #26482

## Things to explore now which aren't necessarily blockers

- [x] #26457
- [x] #26458
- [x] #26359
- [x] #26348
- [x] #26353
- [x] #26351

**Comment by iethree** [comment]
@cdeweyx can this epic be closed now? there's probably some individual tasks worth keeping, but I think this has been split up other places.

**Comment by cdeweyx** [comment]
Yeah, let's close it.
