### ISSUE TITLE
[Epic] Pivot Table Download Implementation

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#26564]
This is a little small to be a real epic, but there are enough steps I wanted somewhere to keep track of them.

Root issue: #2473

## Milestone 1
- [ ] Reverse the execution order of the `qp.pivot` queries so that totals come first. Add a layer afterwards that builds up a (transient) map with all the total/subtotal information, and then pokes it into the component rows at convenient times.
- [ ] FE: fix the non-static viz part of this. In theory it'll be simpler, but…
- [ ] FE (can be done by a backender): Add `.pivoted.csv` and `.pivoted.xlsx` to the download list with appropriate wiring
- [ ] FE: Change the download menu to look like so:
<details>
<summary>Download menu mockup</summary>
<img src="https://user-images.githubusercontent.com/784417/202401162-00ad885a-2d66-4516-892c-c3c5d11d0d91.png" />
</details>

- [ ] Optional: Add a limit to the maximum number of rows (and a config setting for it) so that we don't fill up the instance's memory. This probably isn't necessary since we'd only be keeping track of the subtotals, though? And how many can there be…

## MIlestone 2

- [ ] Rewrite the `qp.pivot` query to `UNION ALL` the 2ⁿ constituent queries (where _n_ is the number of breakouts)…
- [ ] …so that they can be `ORDER BY`-ed to include subtotals at appropriate times. Note: the easiest way to do this is `ORDER BY foo NULLS LAST`, which MBQL doesn't support and which isn't universally supported across DBs. I believe it can be hacked around with an `ORDER BY (CASE WHEN foo IS NULL THEN -999999 ELSE foo)` sort of thing.

**Comment by tsmacdonald** [comment]
Notes!

Cam wrote some implementation notes on Slack [here](https://metaboat.slack.com/archives/CKZEMT1MJ/p1668549569516519).

There are two branches, both of which are very broken. `pivot-table-csv-2473` mostly pivots on the Clojure side (with
some bugs and incompletenesses) and wired it into the API in a way I regret (see below). `qp-pivot-table-csv-2473` is
newer and tries to do the work on the QP side, but is currently broken.

# The query processor side

The key to how the pivot QP currently works is that it runs 2ⁿ queries (where *n* is the number of row or column
breakouts) and then, using a reducing function, concats the results together. It'd be ideal to `UNION ALL` those queries
so that it only runs once, but I don't think that's immediately necessary.

The approach I've been pursuing is to reverse the order in which the queries run, so that the grand total comes out
first, the various subtotals come out next, and then individual rows come out last. You can see the `reverse` call in
`generate-queries` on the QP branch. Note that this breaks the FE and I'm not sure why; for now when I need to look at the
FE I comment out `reverse` and put in an `identity`.

Anyway, the idea is to hang onto the subtotals and then pop them out at the right time. We only care about subtotals on
the rows, not the columns. For example, if you have a pivot table that looks like this:

```
-   | 2016                                | 2017                                | 2018 ...        | Row totals
-   | Doohickey | Gadget | Gizmo | Widget | Doohickey | Gadget | Gizmo | Widget | Doohickey | ... |
AK  | 239.23    | 287.75 | ... [I'm not typing in these numbers] ...                          ... | 36,456.1
AL  | 379.4     | 167    | ...                                                                ... | 38,920.81
```

Then we care about the totals by state but not by year or category. In other words, rows that look like
`["AK", nil, nil, 4, 36345.1]` but not that look like `[nil, 2016, nil, 5, 123.45]`. (NB: I made up the pivot groupings.)

The other key is that the data comes with with one row per set of aggregates, but we need to convert it from many skinny
rows to fewer wide rows. E.g., it comes looking something like:

```
[
 ("AK" "2016-01-01T00:00:00Z" "Doohickey" 0 239.2289290357025)
 ("AK" "2016-01-01T00:00:00Z" "Gadget" 0 287.75459270898403)
 ("AK" "2016-01-01T00:00:00Z" "Gizmo" 0 396.58205796260364)
 ("AK" "2016-01-01T00:00:00Z" "Widget" 0 170.14078226200036)
 ...
]
```

and we want it to look like:

```
[
  ["AK", 239.23, 287.75, ..., 36456.1]
  ...
]
```

The function `update-totals!` is perhaps the worst Clojure code I have written in my adult life, and I think there's a
better way of going about things than the current `swap!`-a-palooza, but you can see some of the general motivations.
Notably, there's the `values-for-breakout-columns` function that works like this:

```
(values-for-breakout-columns (db/select-one-field :dataset_query 'Card :id 2) vs2)
[["2016-01-01T00:00:00Z" "Doohickey"]
 ["2016-01-01T00:00:00Z" "Gadget"]
 ["2016-01-01T00:00:00Z" "Gizmo"]
 ["2016-01-01T00:00:00Z" "Widget"]
 ["2017-01-01T00:00:00Z" "Doohickey"]
 ["2017-01-01T00:00:00Z" "Gadget"]
 ["2017-01-01T00:00:00Z" "Gizmo"]
 ["2017-01-01T00:00:00Z" "Widget"]
 ["2018-01-01T00:00:00Z" "Doohickey"]
 ["2018-01-01T00:00:00Z" "Gadget"]
 ["2018-01-01T00:00:00Z" "Gizmo"]
 ["2018-01-01T00:00:00Z" "Widget"]
 ["2019-01-01T00:00:00Z" "Doohickey"]
 ["2019-01-01T00:00:00Z" "Gadget"]
 ["2019-01-01T00:00:00Z" "Gizmo"]
 ["2019-01-01T00:00:00Z" "Widget"]
 ["2020-01-01T00:00:00Z" "Doohickey"]
 ["2020-01-01T00:00:00Z" "Gadget"]
 ["2020-01-01T00:00:00Z" "Gizmo"]
 ["2020-01-01T00:00:00Z" "Widget"]]
```

These are exactly the columns you need values for in each row. So my thought was to create a map that has keys for each
of those elements (all 20 of them), stash the totals (plural! There could be multiple aggregates) in there under the
right key, and then spit out all of the values into one big ol' row.

There's an additional complication where there's missing data and it doesn't show up at all. For example, no Doohickeys
were sold in Maryland in 2016. An advantage of this approach (and a key bug in the `pivot-table-csv-2473` branch's
implementation) is that you need to be aware of those missing slots and just provide `nil` or whatever.

You can assume that all the cell-level totals (not row totals) will come in a sensible order, so your code just needs to
be aware that the current row is, for example, Alaska, and that it needs to stash the next up-to-20 items that will be
all the Alaska data organized by year and category. Once it encounters the next thing (Alabama), spit out the row and
reset.

If you have multiple row breakouts, which this example does not, you'll need to inject the column totals in after you
finish the set of rows.

As it stands I have the `row-mapping-fn` returning `nil` if it hasn't finished a row yet. I don't know if that's
actually a good idea. I'd think that where the `reduce` happens should filter out nils, but I don't know if it does yet.

You could definitely cache the row, column, and breakout indices, but I believe the fundamental approach of calculating
them is fine.

I want to apologize once more for the garbage state I left `metabase/query_processor/pivot.clj` in.

# The Frontend

This'll change the shape of the API response, so `data_grid.js` is going to have to change. In theory it should become
simpler, at least.

# The API

I went down the path (`pivot-table-csv-2473` branch) of adding `:pivoted.csv` and `:pivoted.xlsx` as export formats. In
hindsight I think that was *not* the move, and we should keep the current set of `:csv`, `:xlsx`, and `:json`. Instead,
add a (boolean?) parameter to the API call for `pivoted?` and default it to false. Then write some magic that swaps out
the `qp-runner` based on whether you need the pivoted one or not. I'm 90% sure that if you do this right then all of the
CSV and XLSX code will Just Work™ without modification. Having said that, I do think you'll have to rewrite how the
header row is done.

**Comment by brunobergher** [comment]
We should consider #28672 in this too. Maybe a separate project, but relevant.

**Comment by Tony-metabase** [comment]
I want to add here since it might have been overlooked but currently when you rename a column in a pivot it simply gets ignored (only happens to pivot) so just sharing since this is related to download

<img width="1512" alt="image" src="https://github.com/metabase/metabase/assets/110378427/611be637-a153-472e-9b8c-95f3b2418f60">

**Comment by ignacio-mb** [comment]
@Tony-metabase that was fixed by https://github.com/metabase/metabase/issues/17753 and https://github.com/metabase/metabase/pull/37208
