### ISSUE TITLE
Improve collection breadcrumbs with embedding parameters

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#26838]
[Product doc](https://www.notion.so/metabase/Improve-collection-breadcrumbs-with-embedding-parameters-51dd704168e344158b649415fb693960)

## Tasks
- [x] Introduce new `breadcrumbs` embed option.
- [x] Change how we're showing the breadcrumb collection
    https://github.com/metabase/metabase/blob/813da747ffc4a76f74efbe46eb658a9bdb24f95f/frontend/src/metabase/nav/components/AppBar/AppBarSmall.tsx#L92-L99
- [x] Modify logic in `getIsAppBarVisible` to follow [the next spec](https://www.notion.so/metabase/Improve-collection-breadcrumbs-with-embedding-parameters-51dd704168e344158b649415fb693960#0ef917ff09244d549fa3a269524c8378)
    https://github.com/metabase/metabase/blob/813da747ffc4a76f74efbe46eb658a9bdb24f95f/frontend/src/metabase/selectors/app.ts#L52

**Comment by paoliniluis** [comment]
https://github.com/metabase/metabase/issues/26256

**Comment by cdeweyx** [comment]
Fixed by https://github.com/metabase/metabase/pull/26977 — LGTM
