### ISSUE TITLE
Let SQL writers see the parameterized query they’re running

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#26837]
[Product doc](https://www.notion.so/metabase/Let-SQL-writers-see-the-parameterized-query-they-re-running-b69e103a6b2c46fc9632ce6636a140dd)

***Tasks***
- [x] https://github.com/metabase/metabase/pull/27005
- [x] https://github.com/metabase/metabase/pull/27072
- [x] https://github.com/metabase/metabase/pull/27113
- [x] https://github.com/metabase/metabase/pull/27159
- [x] https://github.com/metabase/metabase/pull/27321

**Comment by cdeweyx** [comment]
Seeing a couple of things to note before we can close this out: 

<img width="1366" alt="Screenshot 2022-12-12 at 14 14 24" src="https://user-images.githubusercontent.com/16455495/207134468-3e1e3182-a1f1-403a-b40d-c01159198f1b.png">

* Maybe existing prior to this, but you can see a weird overlap bug with the SQL syntax docs CTA and longer error messages
* We'd like to update the styling of general SQL editor error messages (like shown above) to [this frame](https://www.figma.com/file/e3UDStx7r5NGp9MLS3xooF/SQL-writers-see-the-parameterized-query-they're-running?node-id=348%3A2252&t=OSKzVjGyLnGFIGxO-0) — to match the pattern we decided on in the modal (shown below)


<img width="1364" alt="Screenshot 2022-12-12 at 14 21 28" src="https://user-images.githubusercontent.com/16455495/207135485-984bbff8-a813-451a-8283-b6004e47fdd7.png">

* This looks good to me 👌
