### ISSUE TITLE
Custom value list for dashboard filters and template tags (parameters)

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#26873]
# Context
Product doc: [Custom value list for dashboard filters and template tags (parameters)](https://www.notion.so/metabase/Custom-value-list-for-dashboard-filters-and-template-tags-parameters-8ddbdfa87b9e4d1c97e77d8b8c16c4ea)

https://github.com/metabase/metabase/issues/5245

# Requirements
- Users can create custom lists of values to be used in dashboard filters (substituting the field values from the database). These lists can come from:
  - A saved question
  - A static list the user inputs in the widget UI

Bonus:
- Do the same for template tags (if this adds significant effort to the project, we should create a separate issue to track it).

# Implementation Plan
[Reference doc](https://www.notion.so/metabase/Custom-values-list-fb91bcc197c64d7d8aa00b4486f19f7f)

## Milestone 0.5
PR: https://github.com/metabase/metabase/pull/27008
Static list and POC for card as custom list
- [x] Add `source` and `source-options` keys to `dashboard.parameters`
- [x] Modify the `api/dashboard/:dashboard-id/params/:param-id/values` endpoint to read from `source_type` appropriately
    - [x] If the `source_type` is `custom-list`, read values from `source`
    - [x] If the `source_type` is `card`, execute the relevant card and pluck out the resulting values
    - [x] Otherwise, use the existing behavior
- [x] Ensure the API works for embedding and public dashboards 

## Milestone 1
PR:  https://github.com/metabase/metabase/pull/27343
- [x] For cards, store the columns of the card used for values <strike>and labels</strike>
    - [x] I assume that if the columns change out from under us we should throw an error that the FE catches and uses to prompt people to update the settings
- [x] Ensure that a `source_type` of `card` also works with models
    
## Milestone 2
- [x] Custom list using `card` and `static list` for question
  - PR: https://github.com/metabase/metabase/pull/27403

## Milestone 3
- [x] Serialization
  - PR: https://github.com/metabase/metabase/pull/27422
  - PR: https://github.com/metabase/metabase/pull/27495
- [x] When archive questions that are linked to a parameter, warn users.
  - PR: https://github.com/metabase/metabase/pull/27483 
- [x] Review permissions, especially for embedding and public dashboards
  - [x] PR: https://github.com/metabase/metabase/pull/27439

## Milestone 4
- [x] Type handling: users can specify type so we could do proper filtering
- [ ] Let the second column in cards be used for labels (technical note: more complicated than it seems on the FE)

## Need to revisit
- [x] the list values from a card could have duplicated values, should we automatically de-duplicate them?
  - for source is card: https://github.com/metabase/metabase/pull/27697
  - for field: https://github.com/metabase/metabase/pull/27990

## Nice to haves
- [ ] When viewing a question, indicate if it's used for param values

**Comment by tsmacdonald** [comment]
# Implementation Plan
[Reference doc](https://www.notion.so/metabase/Custom-values-list-fb91bcc197c64d7d8aa00b4486f19f7f)

## Milestone 1
- [ ] Add `source` and `source-options` keys to `dashboard.parameters` and `report_card.parameters`
- [ ] Modify the `api/dashboard/:dashboard-id/params/:param-id/values` endpoint to read from `source_type` appropriately
    - [ ] If the `source_type` is `custom-list`, read values from `source`
    - [ ] If the `source_type` is `card`, execute the relevant card and pluck out the resulting values
    - [ ] Otherwise, use the existing behavior
- [ ] Do as above, but for `/api/field/:id/values`
- [ ] Ensure that a `source_type` of `card` also works with models
- [ ] For cards, store the columns of the card used for values and labels
    - [ ] I assume that if the columns change out from under us we should throw an error that the FE catches and uses to prompt people to update the settings

## Nice to haves
- [ ] When viewing a question, indicate if it's used for param values
