### ISSUE TITLE
Viz Settings Milestone 2: General series settings and navigation

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#26887]
Original Epic: https://github.com/metabase/metabase/issues/25453
[Product doc](https://www.notion.so/Improve-the-visualization-settings-user-experience-8e1fb8fadb3f4cd9ba79e3bad7b2847b?d=0e9ef9c7028f4f67902bb7713db8873d)

***Milestone 2: General settings navigation — series settings and axes*** 
- [x] [FE] Merge Axis and Labels tab https://github.com/metabase/metabase/pull/25886
- [x] [FE] Consolidate series settings in a single place which includes:
    - [x] Series renaming https://github.com/metabase/metabase/pull/27304
    - [ ] ~~Add a separate field for a breakout and move breakouts reordering widget to Y-axis~~
    - [x] Move all series settings under `...` menu

**Comment by npfitz** [comment]
Add a separate field for a breakout and move breakouts reordering widget to Y-axis is being punted due to some hidden complexity in separating those viz settings
