### ISSUE TITLE
[Epic] Custom value list for dashboard filters and template tags (parameters)

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#26898]
[Product doc](https://www.notion.so/metabase/Custom-value-list-for-dashboard-filters-and-template-tags-parameters-8ddbdfa87b9e4d1c97e77d8b8c16c4ea)

### Milestone 0 - Prototyping
- [x] https://github.com/metabase/metabase/pull/27170
- [x] https://github.com/metabase/metabase/pull/27263
- [x] https://github.com/metabase/metabase/pull/27354
- [x] https://github.com/metabase/metabase/pull/27405

### Milestone 1 - Parameters in dashboards
- [x] https://github.com/metabase/metabase/pull/27530
- [x] https://github.com/metabase/metabase/pull/27610
- [x] https://github.com/metabase/metabase/pull/27624
- [x] https://github.com/metabase/metabase/pull/27627
- [x] https://github.com/metabase/metabase/pull/27659
- [x] https://github.com/metabase/metabase/pull/27686
- [x] https://github.com/metabase/metabase/pull/27704

#### API changes

Add the following option to the parameter to `/api/dashboard/:id`:
- `values_query_type: "list" | "search" | "none"`
- `values_source_type: "card" | "static-list" | null `
- `values_source_config: { "card-id"?: number, "value-field": MbqlField, "values": string[] }`

### Milestone 3 - Parameters in native queries
- [x] https://github.com/metabase/metabase/pull/27713
- [x] https://github.com/metabase/metabase/pull/27727
- [x] https://github.com/metabase/metabase/pull/27863
- [x] https://github.com/metabase/metabase/pull/27894
- [x] https://github.com/metabase/metabase/pull/27904
- [x] https://github.com/metabase/metabase/pull/27913
- [x] https://github.com/metabase/metabase/pull/27953
- [x] https://github.com/metabase/metabase/pull/27977
- [x] https://github.com/metabase/metabase/pull/27995
- [x] https://github.com/metabase/metabase/pull/28054
- [x] https://github.com/metabase/metabase/pull/28055
- [x] https://github.com/metabase/metabase/pull/28058
- [x] https://github.com/metabase/metabase/pull/28117
- [x] https://github.com/metabase/metabase/pull/28119
- [x] https://github.com/metabase/metabase/pull/28118

#### `DataSelector`
- [ ] Add loading state for schemas list @kulyk 
- [ ] Virtualize lists (databases, schemas, tables, fields) @kulyk 

#### API changes

Add the following options to `template-tags` to `/api/card/:id`:
- `values_query_type: "list" | "search" | "none"`
- `values_source_type: "card" | "static-list" | null `
- `values_source_config: { "card-id"?: number, "value-field": MbqlField, "values": string[] }`

#### API changes

Add the same parameter options in template-tags for cards. 

Add endpoints for fetching field values for saved cards:
`/api/card/:card-id/params/:param-key/values` - to get the values list
`/api/card/:card-id/params/:param-key/search/:query` - to search for values
`/api/embed/card/:card-uuid/params/:param-key/values` - to get the values list on embed card
`/api/embed/card/:card-uuid/params/:param-key/search/:query` - to search for values on embed card
`/api/public/card/:card-uuid/params/:param-key/values` - to get the values list on public card
`/api/public/card/:card-uuid/params/:param-key/search/:query` - to search for values on public card

**Add endpoints to fetch parameter values when used in an unsaved card**:
`/api/parameter/:param-key/values`
`/api/parameter/:param-key/search/:query`

The 2 endpoints above will receive the following params:
- `field_ids` - a list of field ids that are mapped to this parameter
- `values_source_type`  - as in the parameter
- `values_source_config` - as in the parameter

The backend should do the following:
- if `values_source_type` is `card`, use `card-id` with `value-field` and get corresponding values
- if `values_source_type` is `static-list`, use `values`
- if `values_source_type` is `null`, get all values for `fields` and merge them with removing duplicates (current behavior)
