### ISSUE TITLE
[Epic] Split data access and query builder access and merge GUI and SQL permissions

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#26918]
Product doc: [Split data access and query builder access, merge GUI and SQL permission](https://www.notion.so/metabase/Split-data-access-and-query-builder-access-merge-GUI-and-SQL-permission-f18185f2c2954127bdfcb2864ef5c13f)

Tech design doc: [New Permissions Schema and API](https://www.notion.so/metabase/Design-Doc-New-Permissions-Schema-and-API-2a5ff641e7e848e99f8b49bb412ca83f)

PR with feature branch: https://github.com/metabase/metabase/pull/37473

```[tasklist]
### Milestone 1: New permissions table schema and backend API
- [x] Migration to add `data_permissions` table
- [x] Low-level APIs for reading and writing permissions
```

```[tasklist]
### Milestone 2: Migration of existing data permissions to new schema
- [x] Write data permission graph updates to `data_permissions` in parallel to `permissions`
- [ ] https://github.com/metabase/metabase/issues/37604
- [x] Set default permissions for new tables, databases, and groups
- [x] Add SQL migrations to populate `data_permissions` based on existing data perms
- [ ] https://github.com/metabase/metabase/pull/37930
- [x] Load test migrations at the scale of our largest cloud customers (maybe w/cloud data?)
- [ ] https://github.com/metabase/metabase/pull/37932
- [ ] https://github.com/metabase/metabase/issues/37997
- [x] Don't allow EE-only perms to be written on OSS instances
- [ ] https://github.com/metabase/metabase/issues/38052
```

```[tasklist]
### Milestone 3: Enforcement of permissions based on new permissions table
- [ ] https://github.com/metabase/metabase/issues/37919
- [ ] https://github.com/metabase/metabase/issues/38038
- [ ] https://github.com/metabase/metabase/issues/38039
- [ ] https://github.com/metabase/metabase/issues/38606
- [ ] https://github.com/metabase/metabase/issues/38040
- [x] Load test permission updates and enforcement at the scale of our largest cloud customers
```

```[tasklist]
### Milestone 4: Split data access and query builder access
- [x] Add new `:view-data` and `:make-query` permission types
- [x] Add (reversible) SQL migrations to populate this permission type for all groups & tables based on the existing values of `:data-permissions`  and `:native-query-editing`
- [x] Update the query processor to enforce native query permissions based on the `:view-data` `:make-query` permissions
- [ ] https://github.com/metabase/metabase/issues/40852
- [ ] https://github.com/metabase/metabase/issues/39586
- [ ] https://github.com/metabase/metabase/issues/41192
- [ ] https://github.com/metabase/metabase/issues/41221
```

```[tasklist]
### Milestone 5: Migrate collection permissions to new schema and API
- [ ] Update backend code to give the root collection ID 0
- [ ] Write collection permission graph updates to `permissions_v2` 
- [ ] Return collection permission graphs based on the entries in `permissions_v2`
- [ ] Set default permissions for new collections
- [ ] Enforce collection permissions based on the new table
- [ ] Add (reversible) SQL migration to populate `permissions_v2` with collection permissions
```

```[tasklist]
### Milestone 6: Migrate application permissions to new schema and API
- [ ] Migrate application permissions (steps TBD - this should be much simpler than data/collection permissions)
```
```[tasklist]
### Milestone 7: Cleanup
- [x] Delete code associated with the old permissions system
```

```[tasklist]
### Issues to check
- [ ] https://github.com/metabase/metabase/issues/13347
```
