### ISSUE TITLE
[Epic] Adopt Malli - Internal Use

### ISSUE THREAD

**Issue by escherize** [metabase/metabase#26940]
During our backend guild sync, we've agreed that [Malli](https://malli.io) has come far enough to be worth using. That will mean moving away from clojure spec and prismatic schema. 

Going forward we should stop writing new prismatic schema / clojure spec style data validation, in favor of malli.

One of the main benefits is dev-time static analysis by hooking into [clj-kondo](https://github.com/metosin/malli/blob/master/docs/function-schemas.md#tldr).

So far we rely heavily on **schema**. 307 `ns` require schema.core, and `s/defn` called 657 times. Most of those usages are simple. We have **specs** in 307 `ns`, and `s/defn` called 657 times

# Milestones

## 1. Install the library 

- [x] Install the library, and dev-setup
  - https://github.com/metabase/metabase/pull/26939

## 2. These cross-cutting converns are do-able after it's installed:

- [x] #27295
- [x] [#27118 - Port `defendpoint` to accept malli schemas](https://github.com/metabase/metabase/issues/27118)
  - [x] auto-generate dox
  - [x] give better error messages
- [x] ~#27588~

## 3. Extra Credit

- [x] #30674 
- [ ] [#20951 - Create generative test suite for MBQL/QP/drivers](https://github.com/metabase/metabase/pull/20951)
- [x] #27587
- [ ] [query-processor.store](https://github.com/metabase/metabase/blob/bcm-snowflake-efficient-sync/src/metabase/query_processor/store.clj#L63-L70)
- [ ] [shared.models.visualization-settings](https://github.com/metabase/metabase/blob/install-malli-and-dev-setup/shared/src/metabase/shared/models/visualization_settings.cljc#L40-L105)

There are probably more. To be added as noticed.

```[tasklist]
### Finish replacing prismatic schema
- [x] Remove `api/defendpoint` (165 to go)
- [ ] remove schema from `metabase.models.session`
- [ ] https://github.com/metabase/metabase/issues/33869
```

**Comment by escherize** [comment]
We've basically switched over to malli at this point.
