### ISSUE TITLE
[Epic] Data Apps Testing

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#26971]
**Milestone 1: Setup**
- [ ] setup JSON data that can be used directly for unit tests, and inserted into a SQL DB for e2e tests, should include many more column types than existing test dataset
- [ ] setup unit test helpers to load actions data and/or mock actions API endpoints
- [ ] setup e2e test helpers/framework to load/refresh actions data in postgres docker container

**Milestone 2: Frontend Unit Tests**
- [ ] Unit Test App Creator
- [ ] Unit Test Page Nav
- [ ] Unit Test Custom Action/Form Creation + Editing
- [ ] Unit test Action execution
- [ ] Unit Test List Viz
- [ ] Unit Test Object Detail Viz (on dashboards/pages)
- [ ] Unit test adding actions to pages

**Milestone 3: e2e test major user flows**
- [ ] Test App creation and archive
- [ ] Test app page creation and deletion
- [ ] Test scaffolding from tables
- [ ] Test scaffolding from models
- [ ] Test implicit actions: create, update, delete
- [ ] Test custom action creation and execution
