### ISSUE TITLE
[Epic] datetimeDiff

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#26999]
This epic tracks the implementation of the `datetimeDiff` custom expression function.

**Links**
- [product doc](https://www.notion.so/metabase/Unlock-advanced-date-time-manipulation-038f5cf80f364d7cb93341784169743c)

**Driver support**
- [x] postgres, bigquery, mysql https://github.com/metabase/metabase/pull/25722/
- [x] snowflake https://github.com/metabase/metabase/pull/26746
- [x] redshift https://github.com/metabase/metabase/pull/26758
- [x] vertica https://github.com/metabase/metabase/pull/26816
- [x] sqlserver https://github.com/metabase/metabase/pull/27002
- [x] mongo https://github.com/metabase/metabase/pull/27042
- [x] H2 https://github.com/metabase/metabase/pull/27064
- [x] Presto https://github.com/metabase/metabase/pull/27069
- [x] SQLite https://github.com/metabase/metabase/pull/27076
- [x] Oracle https://github.com/metabase/metabase/pull/27196
- [x] SparkSQL https://github.com/metabase/metabase/pull/27197
- [x] Athena https://github.com/metabase/metabase/pull/27205

**Odds and ends:**
- [x] Support "quarter" as a unit https://github.com/metabase/metabase/pull/27015
