### ISSUE TITLE
[Epic] We should support an alternative API authentication mechanism

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#2699]
Update 2023:

**Links**
- product doc: [product doc](https://www.notion.so/metabase/Add-API-key-as-an-API-auth-method-29510c70d9ca4bcebb125244aeba6373?pvs=4)
- eng doc: [eng doc](https://www.notion.so/metabase/Technical-Design-Doc-API-Key-Authentication-c71e8fcaabdc4340a4f42bc795a681b8)
- feature branch: TBD

---

Currently you can make requests to the Metabase API by setting the Cookie header to `metabase.SESSION_ID=XXX`, but sessions expire after 2 weeks so this isn't ideal for programatic access to Metabase. We should support an alternative API authentication method like OAuth or something simpler.

(I thought this was what the `MB_API_KEY` was for but that is not the case) 

Related to #2689

```[tasklist]
### Implementation Plan
- [ ] https://github.com/metabase/metabase/issues/36272
- [ ] https://github.com/metabase/metabase/issues/36347
- [ ] https://github.com/metabase/metabase/issues/36998
- [ ] https://github.com/metabase/metabase/issues/36999
- [x] Write a `DELETE /api/api-key/:id` endpoint to delete an API key
- [ ] https://github.com/metabase/metabase/issues/37000
- [ ] https://github.com/metabase/metabase/issues/36914
- [ ] https://github.com/metabase/metabase/issues/36570
- [x] Write a `GET /api/api-key/count` endpoint to return the total number of API keys
- [ ] https://github.com/metabase/metabase/issues/36805
- [ ] https://github.com/metabase/metabase/issues/37230
- [x] Enforce that API Key users can only belong to one group
- [ ] https://github.com/metabase/metabase/issues/37244
```

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by camsaul** [comment]
OAuth IMO is not what I'd describe as "simple". It's not a huge ask for clients to check for unauthenticated responses from the API and then automatically re-authenticate and re-issue the original request when they see one

**Comment by tlrobinson** [comment]
@camsaul I did say "or something simpler".

Forcing clients to manually re-authenticate if the session has expired is no more secure than, say, basic auth, so if that's the level of security we're going for we should just support basic auth.

**Comment by agilliland** [comment]
I removed the "security" label because it doesn't seem like this is a security problem.

Regarding the implementation, I think what we'd want to aim for here is a keypair + custom hash approach similar to what Amazon does such as .. http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html

I'd also recommend that the model continues to associate credentials and any api calls with a real user of the system because most of the operations that take place in the app are meant to have a sense of who completed them.

**Comment by camsaul** [comment]
@tlrobinson You don't need to pass a cookie, you can pass the session token directly using the `X-Metabase-Session` header:

```bash
curl -X GET \
  -H "Content-Type: application/json" \
  -H "X-Metabase-Session: 38f4939c-ad7f-4cbe-ae54-30946daf8593" \
  http://localhost:3000/api/user/current

# -> {"email":"cam@metabase.com","first_name":"Cam", ...}
```

**Comment by juanjoLenero** [comment]
An API Key would be useful for programatic access in the backend. Our use case is we want to provide our frontend developers with a couple of endponints:

1) Returns a list of all things embeddable, so they now what they are working with.

2) Would take an id from (1) and return an embeddable secret url.

Programatic access is important since the endpoints that list embeddable things is currently superuser only, and we are not comfortable with embedding plain text superuser credentials in our backend code. On top of that, our backend api is mostly stateless so we currently have no way of storing the session tokens and we would quickly run over the rate limits.

**Comment by mderazon** [comment]
Another point to consider - Sometimes keeping a session is not possible. For example, a cloud function that needs to call Metabase api, is stateless, so it has to create a new session each time and the doc specifically say
> You should cache credentials to reuse them until they expire, because logins are rate-limited for security.

**Comment by johnwiseheart** [comment]
An additional use case here is that when password login is disabled for the instance, its not possible to use the api at all (unless there is some way to grab an `X-Metabase-Session` using an LDAP login.

**Comment by tangerinehuge** [comment]
@johnwiseheart you are correct and this is a major security flaw IMO because it prevents you from using the API and enforcing 2FA simultaneously.

**Comment by paulinobruno** [comment]
I could think of two forms of usage:

(1) DataDog and Github both offer an "Api Key" approach, in a way that it never expires. From the security perspective, if it breach, the user needs to generate another key. Also, the Metabase API engines should know how to handle both Api Keys and the Session token (provided by the credentials endpoint);

(2) That "key" provided could be used in a "Client Credentials" approach. In other words, for generating a Metabase Session Token, instead of running the following cURL:
```shell
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"username": "person@metabase.com", "password": "fakepassword"}' \
  http://localhost:3000/api/session
```
One could rather:
```shell
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"username": "person@metabase.com", "api_key": "e3364ee3-c9c6-40a8-a546-1328185d5510"}' \
  http://localhost:3000/api/session
```
And that in turn would generate the same response payload `{"id":"38f4939c-ad7f-4cbe-ae54-30946daf8593"}` containing the Session Id to be further used in the `X-Metabase-Session` header.

**Comment by mstralka** [comment]
We want to use SSO exclusively with our self-hosted Enterprise instance.

We also need to use the API from our SaaS platform. Using the API requires a Metabase username and password.

If `MB_ENABLE_PASSWORD_LOGIN=false` then we can't use the API at all from our system because Metabase throws this exception:
~~~
Password login is disabled for this instance.
~~~

When will it be possible to use SSO exclusively and still use the API?

**Comment by jorgewesley** [comment]
Hey guys, all right with you? So I have two CRM systems, but one is connected to the metabase, can I send and synchronize all customers in both systems? I don't know if I was clear enough but if you need more information and you can help me. I'm grateful.

**Comment by paoliniluis** [comment]
@jorgewesley you can via the API. Please post questions on the forum

**Comment by romulomanzano** [comment]
Sharing my solution here in case it benefits anyone else.

I use this logic (see Python snippet below) to programmatically get the session details from the sso auth flow:

````
metabase_domain = "..."
jwt = "..."
# get new session
res = requests.get(metabase_domain + "/auth/sso?jwt={}".format(jwt))
metabase_cookies = dict(
    item.split("=") for item in res.request.headers["Cookie"].split("; ")
)
session_id = metabase_cookies["metabase.SESSION"]
# set header
header = {"X-Metabase-Session": session_id}
#etc...

```

You can then cache it for whatever time you want (sessions are valid for up to 14 days per their docs) and use it in your api calls.

**Comment by luizarakaki** [comment]
We are implementing API keys and would appreciate your feedback on our approach:

1. Admins can create API keys in the Auth tab in the admin panel
2. They key has a name and is assigned to a group
3. If the group ceases to exist, the key will have the `All Users` permission
4. They key name is used on dashboard/question revision history and audit logs
5. To use the API key, pass it on the request custom header `X-API-Key`

Feedback:
- Is it reasonable that only Admins can create API Keys?
- Does it make sense to use groups to manage permissions?
- Does the key creation and edition flow make sense?
- Is it ok to use the custom header `X-API-Key`? Anyone wants Basic or Bearer?
- Any concerns or improvements?

Feature walkthrough:
https://www.loom.com/share/81d92e1f2de9450482c82c566b41b422?sid=8f24b967-97f0-4b70-acb0-a31454d9f97c

![image](https://github.com/metabase/metabase/assets/32561114/8c2cf0fe-6f14-4175-941e-c532637a74c6)
![image](https://github.com/metabase/metabase/assets/32561114/112ac700-af1f-41dc-87a9-8c07b1438fd1)

**Comment by arathunku** [comment]
@luizarakaki looks amazing! :heart: 

> Is it reasonable that only Admins can create API Keys?

Yes, at least for our use case, it would be enough

> Does it make sense to use groups to manage permissions?

Yes


> Does the key creation and edition flow make sense?

One thing that's a red flag for me: API Key is visible on edit screen, how? I believe the key should be stored securely, like passwords, hashed, and we should be able to see it only on "create" or "regenerate api key". Maybe store first 3-5 chars of the key in plaintext for easier identification, but not the whole key.

Please also consider key format so that in the long-term future, the API key could be easily detected by [Github Secret Scanning](https://docs.github.com/en/code-security/secret-scanning/secret-scanning-partner-program)

**Comment by likeshumidity** [comment]
@luizarakaki one thing to consider as well is potentially treating API keys as users without email addresses or adding a flag to the user table or "type" column. Might be helpful for the API users to show up similar to users on group membership, etc. and to be able to be added to more than one group. The modal looks awesome though... Key name, group membership (would like to be able to select more than one like with users), API key and API key generation. Might be helpful to add disable/enable as well like deactivate/activate that users have.

**Comment by likeshumidity** [comment]
Another common pattern might be worth considering re: having key displayed is maybe display when generated but not after with a warning to download/copy it after generation.

**Comment by shahin43** [comment]
@paoliniluis  thanks for directing to the issue ! 

We have a requirement to enable jwt auth and use singing keys to generate a `metabase.SESSION` inorder to automate programmatic login in a custom app. But since SAML enabled, I understand we hit same endpoints with jwt logins and it doesn't work. 

@luizarakaki API Key would be nice feature to resolve issue we're facing. Is it gonna work when SAML enabled as well ?

**Comment by paoliniluis** [comment]
The objective of this issue is to provide a way to authenticate to Metabase with a fixed token even if SSO is enabled

**Comment by Timelessprod** [comment]
Hello, we may have the same need in my company to automate some roles managements using the API but we only use SSO for connexion to Metabase. Any ETA on when this will be implemented ? Thank you.

**Comment by rjrobinson** [comment]
👍🏼

**Comment by samuelna** [comment]
👍

**Comment by paoliniluis** [comment]
@Timelessprod v49

**Comment by Dev-OrwaSalim** [comment]
Hi @luizarakaki 

When is this going to be released and it will be supported for the open-source version?

**Comment by luizarakaki** [comment]
It will be released on 49 and and it is available on open-source.

**Comment by paoliniluis** [comment]
@luizarakaki time to close this?
