### ISSUE TITLE
Athena driver polish and follow-ons 

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#27012]
We shipped the Athena driver in 45 in #26301 but there are a few things we should do as polish and follow-ons:

- [ ] #26972
- [x] #26975
- [ ] Documentation in `docs/` (as/if needed)
- [ ] Get in touch with Amazon Athena JDBC driver team and ask them nicely to host it on Maven Central or somewhere else normal
     - [ ] Change the name of the s3 bucket we use to host the Athena driver to something more obvious (@dpsutton)
     - [ ] Strip the Log4j config file from the Athena driver in our S3 bucket
- [x] #27014
