### ISSUE TITLE
[Epic] Replace Data Selector component

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#27160]
Our [`DataSelector` component](https://github.com/metabase/metabase/tree/master/frontend/src/metabase/query_builder/components/DataSelector) became pretty fragile and hard to work with time as new functionality was added. Here are a few things it's doing:

* letting users pick databases, schemas, tables, and fields (for both real and virtual data sources; virtual = saved questions represented as tables)
* doing all the necessary data loading + various states handling (loading, error, empty, lacking permissions, etc.)
* search (FE-only or via `/api/search` endpoint)
* virtualizing long lists of data
* scoping the picker to a particular database/schema/table

`DataSelector` became pretty hard to modify and extend. On top of that, it's pretty far from our code quality bar on the FE which is troubling as the component is pretty important and often used.

## Proposal

During the Metabase 45 cycle, we've implemented a brand new picker for data app scaffolding. It doesn't support all the `DataSelector` use cases yet, but it's pretty close. It might be worth adding the missing features and replacing the legacy component with a new one.

The new component is called `DataPicker` and is stored under `metabase/containers` on the `data-apps-main` branch ([source code](https://github.com/metabase/metabase/tree/data-apps-main/frontend/src/metabase/containers/DataPicker)).

### Done before (for data apps)

- [x] #25997
- [x] #26018
- [x] #26019
- [x] #26023
- [x] #26024
- [x] #26033
- [x] #26039
- [x] #26122

### Blockers

_No blockers on the product/design side_

- [x] #27265
- [x] #27259
- [x] #27258
- [ ] Virtualize lists (databases, schemas, tables, fields)

### Nice to haves to achieve full feature parity

- [ ] Allow picking databases / schemas (not only tables / models / questions) (needs design)
- [ ] Allow picking table fields (needs design)
- [ ] Allow configuring steps (e.g. don't let a user change a selected database, schema, table, etc.)
- [ ] Add FE search (should show up when there're many databases / schemas / tables/ fields)  (needs design)
- [ ] Add popover variant  (needs design)

### Replacing Data Selector

**Admin**
- [ ] Replace [`DatabaseDataSelector` in `MetadataHeader`](https://github.com/metabase/metabase/blob/9eae0fc4d7c7169413972cdb6664b3788b1b0610/frontend/src/metabase/admin/datamodel/components/database/MetadataHeader.jsx#L9)
- [ ] Replace [`DatabaseSchemaAndTableDataSelector` in `FilteredToUrlTable`](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/admin/datamodel/hoc/FilteredToUrlTable.jsx)
- [ ] Replace [`DatabaseSchemaAndTableDataSelector` in `GuiQueryEditor`](https://github.com/metabase/metabase/blob/9eae0fc4d7c7169413972cdb6664b3788b1b0610/frontend/src/metabase/query_builder/components/GuiQueryEditor.jsx#L12)

**Query Builder**
- [ ] Replace [`SchemaTableAndFieldDataSelector` in `MappedFieldPicker`](https://github.com/metabase/metabase/blob/9eae0fc4d7c7169413972cdb6664b3788b1b0610/frontend/src/metabase/query_builder/components/DatasetEditor/DatasetFieldMetadataSidebar/MappedFieldPicker/MappedFieldPicker.tsx#L4) (model metadata editor)
- [ ] Replace [`DataSelector` in `DataSourceSelectors`](https://github.com/metabase/metabase/blob/9eae0fc4d7c7169413972cdb6664b3788b1b0610/frontend/src/metabase/query_builder/components/NativeQueryEditor/DataSourceSelectors/DataSourceSelectors.jsx#L5) (native query editor)
- [ ] Replace [`CollectionDatasetOrDataSourceSelector` in `DataStep`](https://github.com/metabase/metabase/blob/9eae0fc4d7c7169413972cdb6664b3788b1b0610/frontend/src/metabase/query_builder/components/notebook/steps/DataStep.jsx#L6) (starting data picker in notebook editor)
- [ ] Replace [`DataSourceSelector` in `JoinStep`](https://github.com/metabase/metabase/blob/9eae0fc4d7c7169413972cdb6664b3788b1b0610/frontend/src/metabase/query_builder/components/notebook/steps/JoinStep.jsx#L8) (notebook editor)
- [ ] Replace [`SchemaTableAndFieldDataSelector` in `TagEditorParam`](https://github.com/metabase/metabase/blob/9eae0fc4d7c7169413972cdb6664b3788b1b0610/frontend/src/metabase/query_builder/components/template_tags/TagEditorParam.jsx#L17) (native query editor)
- [ ] Replace [`DataSourceSelector` in `QuestionDataSelector`](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/query_builder/components/view/QuestionDataSelector.jsx)

**Wrapping up**
- [ ] Remove `DataSelector`

## Related Issues

- #25142
- #16862
- #20406
- #27101
- #14596
- #21511
- #24660

**Comment by flamber** [comment]
Related #4874

**Comment by ranquild** [comment]
Closing in favor of the new "Entity Picker" project
