### ISSUE TITLE
FE - Data Apps Permissions

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#27198]
We built the BE machinery to support Data Apps permissions and now we need to build the FE to control them.

Related BE PRs:
#25529
#25629
#25679
#25764
#25784
#26610
#26652

Product doc: [link](https://www.notion.so/metabase/Implement-Data-Apps-Permissions-732e27313df14ec99a10d7603026a4f2)
Figma file: [link](https://www.figma.com/file/Iq5YT2BLR6j726OLQU3SjG/Permissions?node-id=636%3A4582&t=QLLpv8eWdLXgFEj4-0)

High level plan (to be broken into milestones)
- [ ] Database page component to enable Actions ([link](https://www.figma.com/file/Iq5YT2BLR6j726OLQU3SjG/Permissions?node-id=636%3A4582&t=QLLpv8eWdLXgFEj4-4))
- [ ] New `Apps` permission tab (OSS) + Upsell callout ([link](https://www.figma.com/file/Iq5YT2BLR6j726OLQU3SjG/Permissions?node-id=503%3A2317&t=QLLpv8eWdLXgFEj4-4))
- [ ] New `Apps` permission tab (Pro) ([link](https://www.figma.com/file/Iq5YT2BLR6j726OLQU3SjG/Permissions?node-id=503%3A2087&t=QLLpv8eWdLXgFEj4-4))
- [ ] New column on `Data` permissions tab (OSS) ([link](https://www.figma.com/file/Iq5YT2BLR6j726OLQU3SjG/Permissions?node-id=590%3A1943&t=QLLpv8eWdLXgFEj4-4))
- [ ] New column on `Data` permissions tab (Pro) ([link](https://www.figma.com/file/Iq5YT2BLR6j726OLQU3SjG/Permissions?node-id=503%3A2847&t=QLLpv8eWdLXgFEj4-4))
