### ISSUE TITLE
[Epic] Get the Model detail page up to snuff

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#27581]
As part of the work on data apps last cycle we created a prototype of a model detail to provide context for the model and a home for associated things like actions. Currently, it’s underdone and doesn’t provide quite enough value, part of which is not having basic management features. Since models are where we want actions to live, we also need to level up that experience as well.

**Links**

* [Product doc](https://www.notion.so/metabase/Get-the-Model-detail-page-up-to-snuff-6f757aa5975c4e6888ec84bf0e8ec0b3)
* [Feature branch](https://github.com/metabase/metabase/pull/27311)

### ✅ 1. Model Management

- [x] #27311
- [x] #27628

### Frontend

- [x] #27657
- [x] #27851
- [x] #28063
  - [x] #28327
  - [x] #28126
  - [x] #28063
- [x] #28384
- [x] #28132 @ranquild 

### Backend

- [x] #27716
- [x] #27772
- [x] #27866
- [x] #27900
- [x] #27763
- [x] #28153
- [x] #28150

### Bugs and Polish

- [ ] #27852 @ranquild
- [x] #28406
- [x] #28443
- [x] #28419
- [x] #28442
- [x] #28417
- [x] #28455
- [x] #28464
- [x] #28525
- [ ] Disable actions for models with caching enabled
- [ ] #28493
- [x] #28501
- [x] #28536
- [ ] Seeing raw JSON in successful implicit update toast message when it affects no rows (e.g. use an ID that doesn't exist)
- [ ] Date and datetime columns in implicit actions use string input instead of date or datetime
- [ ] When submitting an action form with the `Enter` key, the modal will close even if there's an error
