### ISSUE TITLE
[Epic] Allow actions to be shared via public link

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#27626]
> A common use case for actions will be capturing user input and putting it into a database. Whether for internal or external purposes, the usefulness of this feature will be greatly enhanced if the action and its associated form can be accessed from outside Metabase.

**Links**
- [product doc](https://www.notion.so/metabase/Allow-actions-to-be-shared-via-public-link-7970b901caa2476586c1454762195c55)

**Implementation Plan**

***Milestone 1 (Product to review when this is done)***
- [x] Add **Make public** toggle to the action settings modal
  - [x] FE: https://github.com/metabase/metabase/pull/27809
  - [x] BE: #27714
- [x] Create a desktop public action page
  - [x] BE: #27723 
  - [x] BE: #27717
    - [x] Make sure the endpoint doesn't execute if actions are disabled for the database
  - [x] FE: #27747
- [x] Show thank you, error message after action form submission
  - [x] FE: #27747

New BE endpoints for Milestone 1:
- [x] `GET: /api/public/action/:uuid`: gets the action with public-only data
- [x] `POST: /api/action/:action-id/public_link`: enables action public sharing. Must be admin and public sharing must be enabled. Returns UUID.
- [x] `DELETE: /api/action/:action-id/public_link`: disables action public sharing. Must be admin and public sharing must be enabled. Returns UUID.
- [x] `POST: /api/public/action/:action-uuid/execute`:  submit a public action form. Rate limited.

***Milestone 2*** After the [model detail page](https://www.notion.so/metabase/Get-the-Model-detail-page-up-to-snuff-6f757aa5975c4e6888ec84bf0e8ec0b3) is done
- [x] Show labels for publicly accessible actions on the model detail page
  - [x] FE: https://github.com/metabase/metabase/pull/28039
  - [x] BE: https://github.com/metabase/metabase/issues/27718
- [x] Show publicly shared actions on `/admin/settings/public-sharing`.
  - [x] FE: https://github.com/metabase/metabase/pull/27675 
  - [x] BE: https://github.com/metabase/metabase/issues/27719
- [x] #27751
- [ ] Create a mobile public action page (it could be the same component, but want to stress that the mobile experience should be included)

New BE endpoints for Milestone 2:
- [x] `GET: /api/action/public`: return a list of shared actions similar to how we're currently returning shared questions

***Milestone 3*** Polish
- [x] https://github.com/metabase/metabase/pull/28453
- [x] https://github.com/metabase/metabase/pull/28456
- [ ] For some reason all parameter names for implicit actions are lowercased. I’d expect them to look the same they do in Metabase, e.g. what it’s set in Data Model for this table. 

**API needed**
Disclaimer: I'm not sure if any of these exist, if they do, please tell me their endpoints and check the corresponding checkbox down below:
- [ ] ✅ API to enable action public sharing `POST: /api/action/:action-id/public_link`. Must be admin and public sharing must be enabled. Returns UUID.
- [ ] ✅ API to disable action public sharing `DELETE: /api/action/:action-id/public_link`
    - Note that the API is exactly like the one when we disable public action on admin public sharing settings page `/admin/settings/public-sharing`, but that one also pass 2 additional parameter, `name` and `public_uuid` for some reason.
![image](https://user-images.githubusercontent.com/1937582/211806551-1fd4128c-fa6b-4552-a9be-9bd7b612a7e2.png)
- [ ] ~API to get an action that will be called on the model detail page should return the sharing status, so we could use to show it in the UI~
    ~We could potentially use the API `GET: /api/action/public`, so we don't have to implement a new one~
    We use `/api/action?model-id` which is already returning `public_uuid` at the time of this edit so we know which action is publicly available.
    ![image](https://user-images.githubusercontent.com/1937582/211806314-a6bcd88b-f72c-45f6-a501-487930a8d0d3.png)
   - ~Cal: Do we need an endpoint for this or can this data be loaded with the action?~ 
- [ ] ✅ API to get a public action to show on the public action page. `GET: /api/public/action/:action-uuid`
- [ ] 🟨 API to submit a public action form. Using similar endpoint name [defined in dashboard action](https://github.com/metabase/metabase/blob/b1f458277cd4a19dac168ed7fc6cdd31e60fba2d/frontend/src/metabase/services.js#L172). `POST: /api/public/action/:action-uuid/execute`
- [ ] ✅ API to return a list of shared actions similar to how we're currently returning shared questions and dashboards `GET: /api/action/public`
- [ ] ✅ API to revoke a public action link similar to how we're currently revoking public access on shared questions and dashboards `DELETE: /api/action/:action-id/public_link?name=ActionName&public_uuid=uuid`
    - A follow up question here is why we need to pass `name`, and `public_uuid` when revoking public access since `:action-id` in the URL path should be enough to identify the action we want to remove public access from. Is it because having `name`, and `public_uuid` makes troubleshooting easier?

**How to Test This Feature Out**
TBD
