### ISSUE TITLE
[Epic] audit_log table

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#27661]
Product doc: https://www.notion.so/metabase/Develop-the-Activity-Log-table-a457a9b1e8064a66b29a03d689c82061#9c477330fe3749aea5c17afae1d3d702

### Milestone 1

At the end of M1, a new `audit_log` table is created which is distinct from the existing `activity_log` and `view_log` tables. This table is used explicitly and only for the audit use case, unlike the other two which power in-app functionality (like "recent items" on the homepage). 

```[tasklist]
### Milestone 1
- [x] Create a new `audit_log` table that mirrors the existing `activity_log` table
- [x] Create an `AuditLog` model and API for writing events
- [x] Write existing `activity_log` events to the `audit_log` table in parallel
- [x] Write existing `view_log` events to the `audit_log` table in parallel
```

### Milestone 2

Milestone 2 consists of adding new events to the `audit_log` table and fixing the semantics of other events.

```[tasklist]
### Milestone 2
- [ ] https://github.com/metabase/metabase/issues/27782
- [ ] https://github.com/metabase/metabase/issues/28038
- [ ] https://github.com/metabase/metabase/issues/34099
- [ ] https://github.com/metabase/metabase/issues/34100
- [ ] https://github.com/metabase/metabase/issues/34102
- [ ] https://github.com/metabase/metabase/issues/34166
- [ ] https://github.com/metabase/metabase/issues/32532
- [ ] https://github.com/metabase/metabase/pull/35115
- [ ] https://github.com/metabase/metabase/issues/35174
- [ ] https://github.com/metabase/metabase/issues/35176
```

```[tasklist]
### Milestone 3 
- [ ] https://github.com/metabase/metabase/issues/34984
- [ ] https://github.com/metabase/metabase/issues/35288
```

```[tasklist]
### Milestone 4
- [ ] https://github.com/metabase/metabase/issues/34985
```
