### ISSUE TITLE
Custom list of values polish items

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#27684]
- [x] Enable custom list of values for Location too (this was an oversight in the product doc) - @ranquild 
- [x] Remove `null` or `empty` string values from saved question ([image](https://files.slack.com/files-pri/T078VCLCR-F04JJMHL4R4/image.png))
- [x] If I switch back and forth between these radio buttons, I lose my previous selections, which makes me sad/frustrated. Would it be hard to preserve what I’d previously selected? ([gif](https://files.slack.com/files-pri/T078VCLCR-F04KF11SLGY/losing-my-work.gif)) @ranquild 
- [ ] When the creator sets a custom list of values, the viewer shouldn’t be able to select other values (even if they exist). ([loom](https://www.loom.com/share/7f6662ebeec04ddbbffe910c0b88b3d6))
- [x] If I have a custom list in a dashboard filter and remove the assigned field, I can’t see the list anymore (this is a P3 at max) ([loom](https://www.loom.com/share/2b2496b778d24dbb8417c3101623e04e)) @ranquild 
- [x] When I change from a Dropdown list to Search box or Input box, the filter behavior doesn’t change ([loom](https://www.loom.com/share/7be2185a59574fbb9a7fe83af8c733cd)) @ranquild 
- [x] When I source field values from another question, I’m getting duplicated values (if they are duplicated in the source question)
([loom](https://www.loom.com/share/2d6b119476fe4e0795903de55db68e16))
- [x] Search box only works if using `Static list` or `Custom question` of values. If using the source field, it doesn't trigger the search query. ([loom](https://www.loom.com/share/3fd70591b91342eeb4e393bde4d7081c))
- [x] When changing the type of list from `Connected field` to `Static list` it should preserve the fields (the user can change or delete fields, but shouldn't need to write them all again). ([loom](https://www.loom.com/share/f957190f2b5a433f9903f8a3715d50b5))
- [x] Search box + Single select behaves oddly ([loom](https://www.loom.com/share/6889c1b697ec4d99b30b029cba7e46fd))

**Comment by qnkhuat** [comment]
> When the creator sets a custom list of values, the viewer shouldn’t be able to select other values (even if they exist)

I can't reproduce this, could you send me a link to the dashboard you had in your loom?

> If I have a custom list in a dashboard filter and remove the assigned field, I can’t see the list anymore (this is a P3 at max) 

@ranquild did you mention that this is a BE bug? I'm testing and when I click on the parameter after I remove field assignment, I don't see FE send a request to get the values field. Maybe this is a FE bug?

**Comment by ranquild** [comment]
@qnkhuat Yep, fixed it on the FE

**Comment by luizarakaki** [comment]
> I can't reproduce this, could you send me a link to the dashboard you had in your loom?

@qnkhuat I couldn't repro it anymore...

**Comment by qnkhuat** [comment]
@luizarakaki I think that's a FE issue.

**Comment by ranquild** [comment]
Part of the epic https://github.com/metabase/metabase/issues/26898
