### ISSUE TITLE
[Epic] Audit v2

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#27792]
📝 [Product doc](https://www.notion.so/Audit-v2-collections-and-navigation-bb26e544848c4dac9a89256d5cac3447)
🎨 [Designs](https://www.figma.com/file/A6Q4571ZvMq2qUUxLgKU4y/Audit-v2?node-id=0%3A1&t=S3beO7moHT9bdrGM-11)
🎥 [Kickoff meeting](https://metaboat.slack.com/archives/C056QEW4KNF/p1684265468104179)
### Milestone 1 - App DB

It seems that the first step is to make the app db appear as a database in the app, including on the frontend. There should be a read-only database available when the required token feature is active, and this database could be used in questions and models like a regular one.

- [x] #30278
- [x] #30301

### Milestone 2 - Built-in audit collections

When there is the app database, we can built content on top of it. We would need to add magic audit collections that are read-only and handled in some special way on the frontend. Then we need to add pre-built audit models, questions and dashboards to them.

```[tasklist]
### Backend
- [ ] https://github.com/metabase/metabase/issues/30887
- [ ] https://github.com/metabase/metabase/issues/30911
- [ ] https://github.com/metabase/metabase/issues/30886
- [ ] https://github.com/metabase/metabase/issues/31079
- [ ] https://github.com/metabase/metabase/issues/31204
```

```[tasklist]
### Frontend
- [ ] https://github.com/metabase/metabase/issues/30908
- [ ] https://github.com/metabase/metabase/issues/30988
- [ ] https://github.com/metabase/metabase/issues/31013
- [ ] https://github.com/metabase/metabase/issues/31014
- [ ] https://github.com/metabase/metabase/issues/31221
- [ ] https://github.com/metabase/metabase/issues/31212
- [ ] https://github.com/metabase/metabase/issues/31535
- [x] It should be possible to query Models from the AuditDB but users can't create new queries directly from that DB (the DB is not available in the DB list)
- [ ] https://github.com/metabase/metabase/issues/33554
- [ ] https://github.com/metabase/metabase/issues/34022
- [ ] https://github.com/metabase/metabase/issues/33309
- [ ] https://github.com/metabase/metabase/issues/33571
- [ ] https://github.com/metabase/metabase/issues/33995
```

### Milestone 3 - Build and transfer the Audit content
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/31419
- [x] Spin up the Audit instance with access to the Stats AppDB
- [x] Add a single dashboard to test the transfer mechanism
- [x] Build Audit content and merge to the core repo
- [ ] https://github.com/metabase/metabase/issues/31450
- [ ] https://github.com/metabase/metabase/issues/31561
- [ ] https://github.com/metabase/metabase/issues/31631
- [ ] https://github.com/metabase/metabase/issues/31632
- [x] Zip instance analytics on build
- [ ] https://github.com/metabase/metabase/pull/34449
```

### Milestone 4 - Custom collections
Here we add editable collections for duplicated questions, models, and dashboards.

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/34086
```

### Milestone 5 - Permissions
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/33246
- [ ] https://github.com/metabase/metabase/issues/34524
- [ ] https://github.com/metabase/metabase/issues/34032
```

### Milestone 6 - Polishing items
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/34095
- [x] Add views as migrations https://github.com/metabase/metabase/tree/auditv2-main/resources/instance_analytics_views
- [x] Instance analytics collection: remove the events button and show the "edit permissions" button on the top-level (not behind the ... menu)
- [x] Instance analytics collection: it shouldn't be possible to verify questions and models
- [x] Remove internal user from the Group Members and Users view: decided to not do this for now. There are legitimate reasons to see the internal user in audit logs, so I think we can keep this.
- [x] Not possible to remove auto-apply filters on premade dashboards
- [ ] https://github.com/metabase/metabase/issues/34915
- [ ] https://github.com/metabase/metabase/issues/34916
- [ ] https://github.com/metabase/metabase/issues/34917
- [ ] https://github.com/metabase/metabase/issues/34918
- [ ] https://github.com/metabase/metabase/issues/35287
- [ ] AFTER RC 1:
- [ ] https://github.com/metabase/metabase/issues/34386
- [ ] https://github.com/metabase/metabase/issues/35228
- [ ] Figure out if it is possible to archive/delete audit content
```

### Milestone 7 - Cleanup
```[tasklist]
### Tasks
- [ ] FE – cleanup (remove Audit v1)
- [ ] BE – cleanup (remove Audit v1)
- [ ] Remove the audit branch from the build workflow https://github.com/metabase/metabase/blob/58caf89b250d6077b9f147180c9e13f0e6f657a2/.github/workflows/uberjar.yml#L7
- [ ] https://github.com/metabase/metabase/issues/34746
- [ ] https://github.com/metabase/metabase/issues/35212
- [ ] https://github.com/metabase/metabase/issues/35225
- [ ] https://github.com/metabase/metabase/issues/35295
```

**Comment by luizarakaki** [comment]
Looks a good start! One thing to notice is that this new "database" can't be accessed by any other means. Users can't create questions or explore this database in Browse Data. It should be hidden and the data only exposed through Models.

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/22423 and https://github.com/metabase/metabase/issues/25335
