### ISSUE TITLE
[Epic] FE actions archiving and searching

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#27867]
Backend: #27866

### FE

- [ ] Implement opening actions from `/model/:modelId/actions/:actionId` URLs
- [ ] Implement viewing actions with read-only access in the editor
- [ ] Implement viewing implicit actions in the editor
- [ ] Implement archiving/unarchiving actions

**Comment by kulyk** [comment]
Closing in favor #27581 (duplicate)
