### ISSUE TITLE
[Epic] Add Link cards to dashboards

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#28073]
[Product doc](https://www.notion.so/metabase/Add-Link-cards-to-dashboards-c487037b2f63453faca79dffb959bb30)

Status: Mockups are getting some [higher-fidelity](https://metaboat.slack.com/archives/C02H619CJ8K/p1675093318093379) love but shouldn't be 100% blocking. Kyle has [a branch](https://github.com/metabase/metabase/tree/prototype/link-cards) that should offer a solid starting point. Project direction is vetted.

```[tasklist]
### Tasks

- [ ] https://github.com/metabase/metabase/issues/28245
- [ ] https://github.com/metabase/metabase/issues/28246
- [ ] https://github.com/metabase/metabase/pull/28528
- [ ] https://github.com/metabase/metabase/issues/29196
```

**Comment by qnkhuat** [comment]
There is a bug with the display of icon for cards that differs when editing and saving.

The reason is that search api doesn't return `card.display`

https://user-images.githubusercontent.com/25661381/220377897-55ca4afc-4e0e-43aa-99ea-dc27eebf4e41.mov

**Comment by qnkhuat** [comment]
@iethree can we close this?

**Comment by iethree** [comment]
there's one lingering incomplete item. Don't want that to get lost 🤔  thoughts @cdeweyx ?

**Comment by iethree** [comment]
ok. done now!
