### ISSUE TITLE
[Epic] Serialization improvements for 46

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#28302]
```[tasklist]
### Minimum
- [ ] https://github.com/metabase/metabase/issues/28856
- [ ] #28303
- [ ] #26859
- [ ] #26860
- [x] Fix nullpointer exception when loading content from the root collection
- [ ] https://github.com/metabase/metabase/issues/29688
- [ ] #29837
- [ ] https://github.com/metabase/metabase/issues/30075
- [ ] https://github.com/metabase/metabase/issues/30366
- [ ] https://github.com/metabase/metabase/issues/30433
```

```[tasklist]
### Nice to have
- [ ] #28037 
- [ ] #27003
- [ ] https://github.com/metabase/metabase/issues/30150
```

**Comment by muscovitebob** [comment]
Would it also be possible to property document [the endpoint](docs/api/ee/serialization-serialize.md)? The current documentation seems to be taken from a draft proposal of the feature and does not actually describe the current functionality of serialisation.
