### ISSUE TITLE
[Epic] Let users run actions from the model detail page

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#28305]
[Product doc](https://www.notion.so/metabase/Let-users-run-actions-from-the-model-detail-page-7350109fde194cb893deab712b92358b) to be broken out into an epic. [Slack thread](https://metaboat.slack.com/archives/C04FG88HL95/p1676451314707679?thread_ts=1676395419.011239&cid=C04FG88HL95).

### BE
- [x] https://github.com/metabase/metabase/pull/28335

### FE
- [x] https://github.com/metabase/metabase/pull/28361
- [ ] Add unit tests
