### ISSUE TITLE
[Epic] CI Flakes + Failures

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#28488]
**Update: Instead of using this epic, you can just add the `flaky-test-fix` label and it will appear on [this list](https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aflaky-test-fix).**

Maintaining our tests and CI environment is a shared responsibility. 
- If you note a CI issue that seems consistent enough to need attention, add it below. 
- If you decide to pick up a particular task, create an issue and assign yourself to it so we don't duplicate efforts. 
- If you've already fixed something, or it seems magically better, check it off!

## Latest purge of complete tasks: July 2023

```[tasklist]
### Frontend
- [ ] [SharingSidebar.unit.spec.js](https://github.com/metabase/metabase/actions/runs/4261422297/jobs/7415733811#step:5:258)
- [ ] https://github.com/metabase/metabase/issues/30938
- [ ] UploadSettings.unit.spec.tsx - [flake](https://github.com/metabase/metabase/actions/runs/5386767024/jobs/9777215875?pr=31887) ("button states › should show a loading spinner on submit" and "button states › should reset button loading state on input change")
```

```[tasklist]
### E2E
- [ ] e2e-tests-collections-ee (should be able to revert a dashboard (metabase#15237))
- [ ] https://github.com/metabase/metabase/issues/32889
- [ ] https://github.com/metabase/metabase/issues/32942
- [ ] https://github.com/metabase/metabase/issues/33171
- [ ] https://github.com/metabase/metabase/issues/33243
- [ ] https://github.com/metabase/metabase/issues/34697
- [ ] https://github.com/metabase/metabase/issues/34698
```

```[tasklist]
### Backend
- [ ] https://github.com/metabase/metabase/issues/32359
- [ ] https://github.com/metabase/metabase/issues/32355
- [ ] https://github.com/metabase/metabase/issues/32356
- [ ] https://github.com/metabase/metabase/issues/32088
- [ ] https://github.com/metabase/metabase/issues/28575
- [ ] https://github.com/metabase/metabase/issues/32919
- [ ] https://github.com/metabase/metabase/issues/34023
- [ ] https://github.com/metabase/metabase/issues/34089
- [ ] https://github.com/metabase/metabase/issues/34213
- [ ] https://github.com/metabase/metabase/issues/35360
- [ ] https://github.com/metabase/metabase/issues/35576
- [ ] https://github.com/metabase/metabase/issues/35856
- [ ] https://github.com/metabase/metabase/issues/35857
- [ ] https://github.com/metabase/metabase/issues/36089
- [ ] https://github.com/metabase/metabase/issues/36097
- [ ] https://github.com/metabase/metabase/issues/36099
- [ ] https://github.com/metabase/metabase/issues/36224
- [ ] https://github.com/metabase/metabase/issues/36397
- [ ] https://github.com/metabase/metabase/issues/36472
```

### Trunk.io Analytics
Test failures on `master` in the last 30 days
- [Drivers](https://app.trunk.io/metabase/metabase/metabase/ci-analytics/2_b93e2ef2-a474-47da-8665-f57b56aebd47?timeBased=false&numericAggregateFunctions=NUMERIC_AGGREGATE_FUNCTION_P50%2CNUMERIC_AGGREGATE_FUNCTION_P95&includeUnfinished=false&includeHidden=false&sortIndex=5&branch=DEFAULT_BRANCH&conclusion=GIT_HUB_REPO_ACTIVITY_RUN_CONCLUSION_FAILURE)
- [Backend](https://app.trunk.io/metabase/metabase/metabase/ci-analytics/2_ab0e0cb9-44a3-445b-b622-703b440aa313?timeBased=false&numericAggregateFunctions=NUMERIC_AGGREGATE_FUNCTION_P50%2CNUMERIC_AGGREGATE_FUNCTION_P95&includeUnfinished=false&includeHidden=false&sortIndex=5&branch=DEFAULT_BRANCH&conclusion=GIT_HUB_REPO_ACTIVITY_RUN_CONCLUSION_FAILURE)
- [Frontend](https://app.trunk.io/metabase/metabase/metabase/ci-analytics/2_72d83809-e7f6-4eb4-8706-0b6817372a48?timeBased=false&numericAggregateFunctions=NUMERIC_AGGREGATE_FUNCTION_P50%2CNUMERIC_AGGREGATE_FUNCTION_P95&includeUnfinished=false&includeHidden=false&sortIndex=5&branch=DEFAULT_BRANCH&conclusion=GIT_HUB_REPO_ACTIVITY_RUN_CONCLUSION_FAILURE)
- [E2E](https://app.trunk.io/metabase/metabase/metabase/ci-analytics/2_80a0ed6f-2b52-49f6-8b54-eaf532e242df?timeBased=false&numericAggregateFunctions=NUMERIC_AGGREGATE_FUNCTION_P50%2CNUMERIC_AGGREGATE_FUNCTION_P95&includeUnfinished=false&includeHidden=false&sortIndex=5&branch=DEFAULT_BRANCH&conclusion=GIT_HUB_REPO_ACTIVITY_RUN_CONCLUSION_FAILURE)

```[tasklist]
### WIP (backlog of assorted errors)
- [ ] cloverage was timing out until we increased the timeout to 90 minutes!
- [ ] revert-dashboard-with-tabs-advanced-test and revert-dashboard-with-tabs-basic-test
- [ ] [metabase.api.card-test/upload-csv!-schema-test](https://github.com/metabase/metabase/actions/runs/5277995272/jobs/9563271910?pr=31598)
- [ ] [be-tests-java-17-ee](https://github.com/metabase/metabase/actions/runs/5474163176/jobs/9968600100?pr=32170)
- [ ] [be-tests-bigquery-cloud-sdk-ee](https://github.com/metabase/metabase/actions/runs/5517779878/jobs/10060873679?pr=32173#logs) ([4 times in a row](https://github.com/metabase/metabase/actions/runs/5822731879?pr=33087))
- [ ] [BigQuery timeout: ERROR in metabase.query-processor-test.filter-test/nonstandard-temporal-arithmetic-test (default.clj:90)](https://github.com/metabase/metabase/actions/runs/5516189694/jobs/10057280756#step:3:902)
- [ ] [Druid 115 errors](https://github.com/metabase/metabase/actions/runs/5511754292/jobs/10047714125)
- [ ] MariaDB: [FAIL in metabase.driver.mysql-test/group-on-time-column-test ](https://github.com/metabase/metabase/actions/runs/5481128121/jobs/9985074749#step:4:951)
- [ ] #31330
```

**Comment by calherries** [comment]
This epic served its purpose, we use the flaky-test-fix label now to list flakes on [this list](https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Aflaky-test-fix)
