### ISSUE TITLE
[Epic] Further visually differentiate basic actions (Actions Polish)

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#28534]
## Context
Basic actions and custom actions feel very similar in the model detail page today, which further adds to the confusion around basic actions, how they differ, what auto-tracking schema means, etc. We can't solve all of these issues post string-freeze, but some light visual tweaks should help separate the two concepts out a bit for users.

## Tweaked Items
- [x] Smaller height for basic action cards
- [x] Updated color for basic action cards
- [x] https://github.com/metabase/metabase/pull/29892

## Mockup
[In Figma](https://www.figma.com/file/tPLGo6nrkHtqInHQxoElKa/Auto-tracking-schema-fix?t=icEAEMktpXIESoeA-0)
![Image](https://user-images.githubusercontent.com/16455495/220661741-7100e02d-4eed-4f90-9b22-ab5fdae3f396.png)
