### ISSUE TITLE
[Epic] De-crazy the expression editor function helper popover

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#28668]
We want to improve expression editor helper popover to make it less overwhelming and more clean and helpful.
To achieve that we want to change it's design and structure.

<table>
<tr>
<th> Before: </th>
<th> After: </th>
</tr>
<tr>
<td>

<img width="350" alt="Screenshot 2023-02-27 at 19 34 09" src="https://user-images.githubusercontent.com/7983744/221607763-7f4cd944-00e9-4b0e-9057-ce1487ce7bd1.png">

</td>
<td>

<img width="350" alt="Screenshot 2023-02-27 at 19 41 14" src="https://user-images.githubusercontent.com/7983744/221609926-ef52ac72-0e23-4190-b96b-53f5f4f5b81a.png">

</td>
</tr>
</table>

**Links**
- [product doc](https://www.notion.so/metabase/De-crazy-the-expression-editor-function-helper-popover-c43d8ff0b0ca4271b9c36ec2be844fe0)
- [design](https://www.figma.com/file/68g8S9L4cMesbctGfCySl7/De-crazy-the-expression-editor-function-helper-popover?node-id=0%3A1&t=1d5CQFMXJ6PhbMu8-0)
- feature branch: `28668-expression-editor`

**Implementation Plan**

- [x] [Refactored ExpressionWidget, ClauseStep components to TS](https://github.com/metabase/metabase/pull/28687)
- [x] [Change expression editor title, Implement info tooltip](https://github.com/metabase/metabase/pull/28776) 
- [x] [Change popover structure to match proposed design](https://github.com/metabase/metabase/pull/28920)
- [x] [Add interactivity for popover parameters](https://github.com/metabase/metabase/pull/28966)

**How to Test This Feature Out**

1. Start creating a new Question: click "New" button in the top bar -> Question.
2. Click "Custom column" in the Notebook.
3. Appeared expression editor should have new design and experience.
