### ISSUE TITLE
JSON unfolding by field

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#28667]
**Milestone 1**: Allow toggling JSON unfolding by top-level field
Resolves https://github.com/metabase/metabase/issues/24801
- [x] Add a setting to the field settings for JSON fields to toggle JSON unfolding on sync
- [x] Have that interact correctly with the existing "Unfold JSON Columns" database setting, which will become a default for the database.
- [x] https://github.com/metabase/metabase/pull/28742

**Milestone 2**: Have JSON fields sync automatically when JSON unfolding is toggled on/off
- [x] https://github.com/metabase/metabase/pull/29227

**Milestone 3**: Allow toggling JSON unfolding by nested field 

_update: milestone 3 is not done_

e.g. {"field_a" {"nested_field_1": ... "nested_field_2": ...}}  would automatically be unfolded to field_a.nested_field_1  and field_a.nested_field_2` , and these fields could be “folded” so there’s only field_a . Likewise field_a once folded, could be unfolded again

**Comment by cdeweyx** [comment]
@calherries Had this typo issue lying around, might have already addressed it but linking here for posterity: https://github.com/metabase/metabase/issues/28554

**Comment by calherries** [comment]
Yep, tackled that quirk already. I'll close it when this merges

**Comment by calherries** [comment]
@cdeweyx Originally we had discussed implementing milestone 3, but it as more of a nice-to-have, not required to solve the original issue. Do you feel like I should spend time on this, or move on to other things?

**Comment by cdeweyx** [comment]
@calherries Let's hold off on M3 for now
