### ISSUE TITLE
[Epic] Metabase Lib v2

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#28689]
MBQL queries modification.

```[tasklist]
- [ ] #30510
- [ ] #30504
- [ ] #30507
- [ ] #30508
- [ ] #30509
- [ ] #30511
- [ ] #30515
- [ ] #30514
- [ ] #30519
- [ ] https://github.com/metabase/metabase/issues/34112
- [ ] https://github.com/metabase/metabase/issues/31004
- [ ] #30513
- [ ] https://github.com/metabase/metabase/issues/36983
- [ ] https://github.com/metabase/metabase/issues/36110
```

**Comment by darksciencebase** [comment]
moved #31003 to "out of scope" as it's too close to parameters and we're not taking _that_ up now. more details in[ the slack thread](https://metaboat.slack.com/archives/C04CYTEL9N2/p1697799246523479)
