### ISSUE TITLE
[Epic] Make the bulk-move and bulk-archive actions more obvious

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#28737]
[Product doc](https://www.notion.so/metabase/Make-the-bulk-move-and-bulk-archive-actions-more-obvious-de4720add63b4810ac13556b39c3a082)
[Mockup](https://www.figma.com/file/ZSze42p3ChrTnvbuKArhf4/Bulk-Actions-Bar?node-id=601%3A20398&t=WahdvmsRaXtSdsAe-0)

- [x] [Table](https://github.com/metabase/metabase/pull/28793)
- [x] [Bulk action bar](https://github.com/metabase/metabase/pull/28797)
- [x] [Confirmation snack](https://github.com/metabase/metabase/pull/28807)
