### ISSUE TITLE
Review Ocient Driver

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#28897]
The Ocient team developed [their driver](https://github.com/Xeograph/metabase-ocient-driver) and are applying for the partnership program.

To add the driver to our Cloud offerings, we need to:
- [x] Code review looking for bad practices and security vulnerabilities
- [x] Give them a direction to solve the failing tests
- [x] As soon as we are comfortable with the driver state. [Add it to our CI pipeline](https://github.com/metabase/metabase-ee-extra/blob/master/.github/workflows/build.yml).

Test failures: 5
Report
```
Finding tests took 29.2 s.

Looking for test namespaces in directory modules/drivers/ocient/test

Running 2821 tests

...

Ran 2815 tests in 2169.727 seconds

14591 assertions, 5 failures, 0 errors.

{:test 2815,

:pass 14586,

:fail 5,

:error 0,

:type :summary,

:duration 2169726.893213,

:single-threaded 2596,

:parallel 219}

Ran 219 tests in parallel, 2596 single-threaded.

Finding and running tests took 37.3 mins.

Tests failed.

 

 

Failure logs:

FAIL in metabase.driver.sql-jdbc.sync.describe-database-test/database-schema-filtering-test (describe_database_test.clj:143)
:ocient Filtering connections for schemas works as expected  with an inclusion filter
expected: (contains? #{\s \v} (first schema-name))
  actual: (not (contains? #{\s \v} \m))
FAIL in metabase.driver.sql-jdbc.sync.describe-database-test/database-schema-filtering-test (describe_database_test.clj:143)
:ocient Filtering connections for schemas works as expected  with an inclusion filter
expected: (contains? #{\s \v} (first schema-name))
  actual: (not (contains? #{\s \v} \m))
FAIL in metabase.driver.sql-jdbc.sync.describe-database-test/database-schema-filtering-test (describe_database_test.clj:143)
:ocient Filtering connections for schemas works as expected  with an inclusion filter
expected: (contains? #{\s \v} (first schema-name))
  actual: (not (contains? #{\s \v} \m))
FAIL in metabase.driver.sql-jdbc.sync.describe-database-test/database-schema-filtering-test (describe_database_test.clj:143)
:ocient Filtering connections for schemas works as expected  with an inclusion filter
expected: (contains? #{\s \v} (first schema-name))
  actual: (not (contains? #{\s \v} \m))
1071/2821    37% [==================                                ]  ETA: 10:45Created a new logger for metabase.email
ERROR TypeError: Cannot read property 'table.column_formatting' of null
[main] TRACE metabase.email.messages - NOT including CSV attachement for Card "card-name" because less than 10 rows in results
1136/2821    40% [====================                              ]  ETA: 09:50Created a new logger for metabase.logger
FAIL in metabase.query-processor-test.date-bucketing-test/group-by-week-test (date_bucketing_test.clj:698)
JVM timezone set to Pacific 
:ocient
expected: (["2015-05-31T00:00:00-07:00" 46]
           ["2015-06-07T00:00:00-07:00" 47]
           ["2015-06-14T00:00:00-07:00" 40]
           ["2015-06-21T00:00:00-07:00" 60]
           ["2015-06-28T00:00:00-07:00" 7])
  actual: ([["2015-05-30T17:00:00-07:00" 46]
            ["2015-06-06T17:00:00-07:00" 47]
            ["2015-06-13T17:00:00-07:00" 40]
            ["2015-06-20T17:00:00-07:00" 60]
            ["2015-06-27T17:00:00-07:00" 7]])
2185/2821    77% [======================================            ]  ETA: 10:04Error in test-qp-middleware runf: #error {
 :cause Something went wrong
 :via
 [{:type java.lang.Exception
   :message Something went wrong
   :at [metabase.query_processor.middleware.catch_exceptions_test$fn__174855$fn__174856 invoke catch_exceptions_test.clj 85]}]
```

**Comment by metamben** [comment]
Opened a [PR](https://github.com/Xeograph/metabase-ocient-driver/pull/27) with my review comments.
