### ISSUE TITLE
[Epic] Bring consistency and simplicity to the custom expression editor popovers

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#29029]
We want to unify UX for expression editors:

- custom column editor
- custom filter
- custom expression in aggregation

Also let's address these found issues:
https://github.com/metabase/metabase/pull/28678#pullrequestreview-1331758567

**Links**
- [product doc](https://www.notion.so/metabase/Bring-consistency-and-simplicity-to-the-custom-expression-editor-popovers-c3f39e31c5d94229a37ed4ae3f9fd9cd)
- [design](https://www.figma.com/file/7xQlOsvKcP89gE6bkD4wBb/Bring-consistency-and-simplicity-to-the-custom-expression-editor-popovers?node-id=0-1)
- feature branch: `29029-expression-editor-ux`

**Implementation Plan**

- [x] Add “Cancel” button for custom filter and custom expression in aggregation
- [x] Update Expression editor field info tooltip UX
- [x] Fix an issue with Expression Function helper popover appearing below the Expression Editor popover for Filters and Aggregations - https://github.com/metabase/metabase/pull/28678#pullrequestreview-1331758567

**How to Test This Feature Out**

Check demo here - https://github.com/metabase/metabase/pull/29209
