### ISSUE TITLE
To Toucan 2

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#29231]
- [x] https://github.com/metabase/metabase/pull/29349
- [x] https://github.com/metabase/metabase/pull/29310
- [x] https://github.com/metabase/metabase/pull/29311
- [x] https://github.com/metabase/metabase/pull/29319
- [x] https://github.com/metabase/metabase/pull/29308
- [x] https://github.com/metabase/metabase/pull/29389
- [x] Prep work - define generic transforms, types
- models
  - [x] https://github.com/metabase/metabase/pull/30685
  - [x] https://github.com/metabase/metabase/pull/30690
  - [x] https://github.com/metabase/metabase/pull/30688
  - [x] https://github.com/metabase/metabase/pull/29513
  - [x] [DashboardCard, Dashboard, DashboardCardSeries](https://github.com/metabase/metabase/pull/30068)
  - [x] https://github.com/metabase/metabase/pull/30724
  - [x] https://github.com/metabase/metabase/pull/30657
  - [x] https://github.com/metabase/metabase/pull/30689
  - [x] metric, metric_important_field, segment
  - [x] https://github.com/metabase/metabase/pull/30692
  - [x] native_query_snippet
  - [x] parameter_card
  - [x] https://github.com/metabase/metabase/pull/30726
  - [x] pulse and friends
  - [x] query and friends
  - [x] user
