### ISSUE TITLE
[Epic] Prevent auto-apply filters in slow dashboards

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#29267]
Currently we reload all dashboard cards when a filter is changed. This might not work well when the queries are "heavy". This project is about adding a setting to prevent automatic application of filters, with a button to manually reload the dashboard when needed.

**Links**
- product doc: https://www.notion.so/metabase/Prevent-auto-apply-filters-in-slow-dashboards-cc02d90dac9e42ee91f34c2a9810212f
- designs https://www.figma.com/file/MPTXmUB6nJ2w0zi4aZTiwC/Prevent-auto-apply-filters-in-slow-dashboards?node-id=1169-4854&t=bNrcdnArNxOLegrS-0

**Implementation Plan**

Milestone 1 PR: https://github.com/metabase/metabase/pull/30232

```[tasklist]
# Milestone 1: Add dashboard settings + allow disabling auto-apply filters behavior on a dashboard
- [ ] https://github.com/metabase/metabase/pull/30069
- [ ] https://github.com/metabase/metabase/pull/29569
- [ ] https://github.com/metabase/metabase/pull/30071
- [ ] https://github.com/metabase/metabase/pull/30255
- [ ] https://github.com/metabase/metabase/pull/30232
```

```[tasklist]
# Milestone 2: Make it even easier for users to discover this new setting
- [ ] https://github.com/metabase/metabase/pull/29729
- [ ] https://github.com/metabase/metabase/pull/30371
- [ ] https://github.com/metabase/metabase/pull/30525
- [ ] https://github.com/metabase/metabase/pull/30613
- [ ] https://github.com/metabase/metabase/pull/30569
```

**How to Test This Feature Out**

- Open a dashboard with questions and filters mapped to them.
- Open the info sidebar -> Toggle off "Auto-apply filters".
- Change filters. The button to apply the changes should appear.
- Click the button. Only then the dashboard should be reloaded with new filter values.

**Comment by paoliniluis** [comment]
Related to https://github.com/metabase/metabase/issues/9871
