### ISSUE TITLE
instrument google auth for instances that have enabled tracking

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#2939]
- [x] google auth login event occured
- [x] google auth was enabled
- [x] google auth signup was enabled
- [ ] ~~google auth signup event occured~~ - probably not possible?

**Comment by kdoh** [comment]
#2941 will handle google auth logins (as well as normal logins and other types of auth activity). I think in theory we should get the admin side SSO setup events for free thanks to https://github.com/metabase/metabase/blob/master/frontend/src/metabase/admin/settings/containers/SettingsEditorApp.jsx#L67, but it would be good to get another pair of eyes to make sure. 

I'm pretty sure we can't currently instrument google auth account creations since that's not really something that takes place on the frontend unless we were able to check and see if last_login or whatever was null.
