### ISSUE TITLE
[Epic] Warn users before they lose new changes

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#29421]
[Product doc](https://www.notion.so/metabase/Warn-users-before-they-lose-new-changes-1641d98e1e1f4a99bda7f46d0b871ec6)

### Implementation plan

Add [onbeforeunload](https://www.w3schools.com/jsref/event_onbeforeunload.asp) checks (maybe with [useBeforeUnload](https://github.com/streamich/react-use/blob/master/docs/useBeforeUnload.md)) to:

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/29986
- [ ] https://github.com/metabase/metabase/pull/30292
- [ ] https://github.com/metabase/metabase/pull/30477
- [ ] https://github.com/metabase/metabase/pull/30523
- [ ] https://github.com/metabase/metabase/pull/30386
- [ ] https://github.com/metabase/metabase/pull/30415
- [ ] https://github.com/metabase/metabase/pull/30458
```

**Comment by paoliniluis** [comment]
Related to https://github.com/metabase/metabase/issues/8712, https://github.com/metabase/metabase/issues/12389 and https://github.com/metabase/metabase/issues/10427
