### ISSUE TITLE
[Epic] Connection impersonation

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#29491]
**Links**
- [product doc](https://www.notion.so/metabase/New-sandbox-mode-connection-impersonation-49ecf43c3ffa4983883131c2af10580f)
- [mockups](https://www.figma.com/file/0FbaSE58pGiAmnBk7Gd4ZF/Role-based-sandboxing?node-id=323-6939&t=qSczvJSuZj2IyDql-0) 
- feature branch: `feature-connection-impersonation`

**Implementation Plan**

```[tasklist]
### Milestone 1: connection impersonation shippable MVP
- [x] FE: https://github.com/metabase/metabase/pull/30132
- [x] FE: https://github.com/metabase/metabase/pull/30867
- [x] BE: https://github.com/metabase/metabase/pull/30714
- [x] FE: https://github.com/metabase/metabase/pull/31422
- [x] E2E: https://github.com/metabase/metabase/pull/31634
```

```[tasklist]
### Bugs and cleanup
- [x] BE: fix actions can be successfully executed by an impersonated user with restricted access
- [x] https://github.com/metabase/metabase/pull/31954
- [x] BE: impersonated users [don’t see](https://metaboat.slack.com/archives/C056QEW4KNF/p1686945893924999) list of values ([loom](https://www.loom.com/share/a6a6ba882602450da3d07064550d7fad))
- [x] https://github.com/metabase/metabase/pull/31882
- [ ] https://github.com/metabase/metabase/pull/31708
- [x] E2E: update specs after bugs are fixed
- [ ] https://github.com/metabase/metabase/pull/32579
```

**Comment by paoliniluis** [comment]
Related to https://github.com/metabase/metabase/issues/5147, https://github.com/metabase/metabase/issues/9845, https://github.com/metabase/metabase/issues/9947, https://github.com/metabase/metabase/issues/9906 and 

Impact on https://github.com/metabase/metabase/issues/10525
