### ISSUE TITLE
[Epic] Bring tabbed navigation to dashboards

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#29502]
[Product doc](https://www.notion.so/metabase/Bring-tabbed-navigation-to-dashboards-dd2e71b4d1954f8188ecbd9914e81420)
[Data model spec](https://www.notion.so/metabase/Engineering-Notes-Data-Model-Plan-92672ca13d9c4d45921df269bf13a657)

```[tasklist]
### Milestone 0: refactor inefficient dashboard cards updating
- [x] BE: https://github.com/metabase/metabase/pull/29641
- [x] FE: https://github.com/metabase/metabase/pull/29762
```

```[tasklist]
### Milestone 1: deliver basic tabs functionality
- [x] BE: https://github.com/metabase/metabase/pull/29802
- [x] BE: https://github.com/metabase/metabase/pull/29861
- [x] FE: https://github.com/metabase/metabase/pull/30189
```

```[tasklist]
### Milestone 2: polish (v47)
- [x] BE+FE: https://github.com/metabase/metabase/pull/30813
- [x] BE: https://github.com/metabase/metabase/pull/30249
- [x] BE: https://github.com/metabase/metabase/pull/30478
- [x] FE: https://github.com/metabase/metabase/pull/30464
- [x] FE: https://github.com/metabase/metabase/pull/30465
- [x] FE: https://github.com/metabase/metabase/pull/30540
- [x] FE: https://github.com/metabase/metabase/pull/30497
- [x] BE: https://github.com/metabase/metabase/pull/30784
- [x] BE: https://github.com/metabase/metabase/pull/31108
- [x] FE: https://github.com/metabase/metabase/pull/31578
- [x] BE+FE: https://github.com/metabase/metabase/pull/30502
- [x] BE: https://github.com/metabase/metabase/pull/30898
- [x] BE: https://github.com/metabase/metabase/issues/30791
- [x] BE: make sure API check permission when update tabs
- [x] FE: https://github.com/metabase/metabase/issues/30923
- [x] FE: https://github.com/metabase/metabase/pull/31376
- [x] FE: https://github.com/metabase/metabase/pull/31359
- [x] FE: https://github.com/metabase/metabase/pull/31411
```

```[tasklist]
### Milestone 3: follow-ups (v47 or later)
- [ ] BE: Clean up the event system and includes tabs activity
- [x] FE: https://github.com/metabase/metabase/pull/30833
- [ ] FE: "Add to dashboard" should add question to tab that was active when this is clicked
- [ ] BE: migrate to make all dashboards to have at least one tab
```

**Comment by paoliniluis** [comment]
https://github.com/metabase/metabase/issues/19347

**Comment by darksciencebase** [comment]
Moving this to Soon as we're not actively working on this right now but there are outstanding items under 'Milestone 3'

**Comment by luizarakaki** [comment]
Closing this for now.

Issues from milestone 3 will be prioritized individually on their own issues.
