### ISSUE TITLE
[Epic] CSV Upload

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#29561]
Allow very basic CSV uploads to create new tables + models in actions-enabled databases.

Resolves https://github.com/metabase/metabase/issues/6094

Product Doc: https://www.notion.so/metabase/Make-CSV-uploads-possible-390737edcab7475992d919e5aab867ae

```[tasklist]
### Frontend
- [ ] https://github.com/metabase/metabase/issues/29562
- [ ] https://github.com/metabase/metabase/issues/29563
- [ ] https://github.com/metabase/metabase/issues/29598
- [ ] https://github.com/metabase/metabase/issues/29601
- [ ] https://github.com/metabase/metabase/pull/30005
- [ ] https://github.com/metabase/metabase/pull/30009
- [ ] https://github.com/metabase/metabase/issues/30111
- [ ] https://github.com/metabase/metabase/issues/30261
- [ ] https://github.com/metabase/metabase/issues/30563
- [ ] https://github.com/metabase/metabase/issues/30564
- [ ] https://github.com/metabase/metabase/issues/30603
- [ ] https://github.com/metabase/metabase/issues/30604
- [ ] https://github.com/metabase/metabase/issues/30420
- [ ] https://github.com/metabase/metabase/issues/30614
- [ ] https://github.com/metabase/metabase/issues/31214
- [ ] https://github.com/metabase/metabase/issues/31215
- [ ] https://github.com/metabase/metabase/issues/31261
- [ ] https://github.com/metabase/metabase/issues/31262
- [ ] https://github.com/metabase/metabase/issues/31772
```

```[tasklist]
### Backend Milestone 2
- [ ] https://github.com/metabase/metabase/issues/31261
- [ ] https://github.com/metabase/metabase/issues/30795
- [ ] https://github.com/metabase/metabase/issues/30322
- [x] Avoid full database sync on upload [[PR Link](https://github.com/metabase/metabase/pull/31194)]
- [x] Catching and addressing failed upload cases e.g. `dog_breeds.csv` (should be fixed by change to sync strategy above)
- [ ] https://github.com/metabase/metabase/issues/31397
- [ ] https://github.com/metabase/metabase/issues/31580
```

```[tasklist]
### Backend Milestone 1
- [ ] https://github.com/metabase/metabase/issues/29675
- [ ] https://github.com/metabase/metabase/issues/29676
- [ ] https://github.com/metabase/metabase/issues/29759
- [ ] #29963
- [ ] #29967
- [ ] #29968
- [ ] #30076
- [ ] #30181
- [ ] https://github.com/metabase/metabase/pull/31029
- [ ] https://github.com/metabase/metabase/pull/31065
- [ ] https://github.com/metabase/metabase/issues/30459
- [x] Accept CSV file uploads
- [x] Figure out an acceptable schema for the table -->  [PR](https://github.com/metabase/metabase/pull/29650)
- [x] handle empty / incomplete files --> [PR](https://github.com/metabase/metabase/pull/29754)
- [x] Pass relevant error messages to the frontend
- [x] Error messaging for invalid data
- [x] BUG: a column with a number of length greater than 255 and a string of length less than 255 will incorrectly become a `varchar(255)` instead of `text`.
- [x] Make uploads prefix optional
- [x] Handle common currency symbols in numeric columns
- [x] Improve performance for supported dbs
- [x] perf tuning: MySQL
```

## Follow-ons (targeted to v48, will be broken out into separate project later)
- [ ] allow appends
- [ ] insert primary keys
- [ ] Sort schema list alphabetical in admin picker
- [ ] Re-upload option to overwrite in case of bad data
- [ ] Let people create schema via UI rather than requiring a db admin to do it

**Comment by calherries** [comment]
This doesn't have an issue because it's not worth the hassle, but I just merged https://github.com/metabase/metabase/pull/29636 into csv/main so we can get started writing driver code and tests for H2 and Postgres.
