### ISSUE TITLE
[Epic] Index individual entities and surface them in search

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#29651]
[Product doc](https://www.notion.so/metabase/Index-individual-entities-and-surface-them-in-search-9558b3e1f6bc45c39f5d14bfe18417e4)

```[tasklist]
### Backend
- [ ] https://github.com/metabase/metabase/issues/29790
- [x] CRUD for `model_index` table
- [x] sync functions (enumeration, generation tracking, deleting ones no longer present)
- [x] hook up sync functions to task system
- [x] Add index entities to search
```

```[tasklist]
### Frontend
- [ ] https://github.com/metabase/metabase/issues/29819
- [ ] https://github.com/metabase/metabase/issues/30167
- [ ] https://github.com/metabase/metabase/issues/30168
- [ ] https://github.com/metabase/metabase/issues/30482
- [ ] https://github.com/metabase/metabase/issues/31017
- [ ] https://github.com/metabase/metabase/issues/31046
- [ ] https://github.com/metabase/metabase/issues/31047
```

```[tasklist]
### Followup (Milestone 2?)
- [ ] unify naming?
- [ ] multiple indexes on same model. What constraints do we want/need?
- [x] implement for mysql
- [ ] make POST to create make the initial values asynchronously, (sync now for ease of demo)
- [ ] clear up `state` lifecycle: initial, indexed, overflow, etc
- [ ] what happens if there are too many values? currently it grabs 5001 of them and sets the state to overflow
- [ ] allow users to select their own PK
```

**Comment by darksciencebase** [comment]
Blessed by @cdeweyx, I'm closing this epic as done.
