### ISSUE TITLE
[Epic] Improve the flow for adding a question to a dashboard

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#29666]
[Product doc](https://www.notion.so/metabase/Improve-the-flow-for-adding-a-question-to-a-dashboard-424efa0806ec4b3dba8640ec70bd1259)

###

Development branch

```
question-to-dash-flow/main
```

### API changes

Add a new endpoint which returns the most recent viewed dashboard.
if the user has not viewed any dashboards in the last 24 hours, response will be 204

```
GET /api/activity/most_recently_viewed_dashboard
```

### Implementation details

```[tasklist]
### Milestone 1 (Rework files to TS and prepare BE)
- [ ] https://github.com/metabase/metabase/issues/30140
- [ ] https://github.com/metabase/metabase/pull/30566
- [ ] https://github.com/metabase/metabase/pull/30406
- [ ] https://github.com/metabase/metabase/pull/30418
- [ ] https://github.com/metabase/metabase/pull/30407
- [ ] https://github.com/metabase/metabase/pull/30224
- [ ] https://github.com/metabase/metabase/pull/30581
```

**Comment by paoliniluis** [comment]
Double checking if this issue is not the same as https://github.com/metabase/metabase/issues/29405 ?

**Comment by cdeweyx** [comment]
Yeah this is different, just around making it easier to add a question to a dashboard.

**Comment by NevRA** [comment]
@uladzimirdev can you add integration branch?

**Comment by uladzimirdev** [comment]
@cdeweyx we can for sure. We considerd two options: 1) to extend the existing endpoint 2) to create a new one. Initially even BE team though extending recent_views could be okay as they had an ongoing PR, but the latest info was to create a new endpoint, so @calherries is alighed with the decisions 😄

**Comment by calherries** [comment]
@uladzimirdev @NevRA I created the feature branch above for this epic and merged [Add GET "/most_recently_viewed_dashboard" endpoint](https://github.com/metabase/metabase/pull/30323#top) into it
