### ISSUE TITLE
[Epic] Sankey Chart v52

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#29671]
Closes https://github.com/metabase/metabase/issues/11888

**Links**
- feature branch: `sankey-echarts`

**Implementation Plan**

### Milestone 1: Minimum shippable Sankey [1-2 weeks]
- [x] Implement data settings to support the [first suitable data shape](https://www.notion.so/metabase/Offer-new-viz-type-Sankey-chart-ebc7f49acbf740249115f65d017e8bf6?pvs=4#11269354c901806893e7ced80221a325)
- [x] Add all columns to the data transformation for tooltips and click behavior
- [x] Implement correct chart layout calculation to avoid overflows
- [x] Use our palette when assigning colors to segments
- [x] Handle errors when data shape is not correct
- [x] Add extensive visual specs coverage
- [x] Edge color selection
- [x] Right/Left/Justify align

#### Blockers / zero-effort work

This list contains blockers and near-zero effort polish tasks.

- [x] Update Sankey visualization icon [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524042369109)
- [n/a] ~Hovers are laggy~ [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523715459839) [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524562507779) — unrelated, caused by [Pooling database sync status triggers rerender that hides ECharts tooltips](https://github.com/metabase/metabase/issues/50309#top)
- [x] Handle labels collision better [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523875300039) [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523886446819) [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524089924339) [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524222339589)
- [x] Keep drills that only make sense for sankey [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523595974099)
- [x] Improve the error message when data has a circular dependency [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523657120589)
- [x] Improve the error message when selecting the same column as source and target at the same time [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523845921729)
- [x] Tweak font style for labels [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523794332379)
- [x] Add padding [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731523961754569)
- [x] Change the default edge color to `source` [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524138661239)
- [x] Increase default sankey dashboard card size [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524182447699)
- [x] Fix tooltip values do not have formatting applied [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524495015619)
- [x] Handle longer node labels better [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524574427109)
- [x] Support compact numbers formatting [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524383195119)
- [x] Data labels configuration

#### Tests

- [x] Add dashboards E2E specs
- [-] Add BE static viz smoke test: https://github.com/metabase/metabase/pull/50793 (non-blocking)

**Comment by prassanna-ravishankar** [comment]
+1 would be nice
