### ISSUE TITLE
[Epic] Create the new Metric entity

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#29752]
**Links**
- Product doc https://www.notion.so/metabase/Create-the-new-Metric-entity-6539b2977d764948b46ee7b629969bbd
- Figma https://www.figma.com/file/17Z8b1uEdcrtpP8rVHaPAS/Metrics-2.0?node-id=0-689&t=wfHq3380ir60os25-0

**Implementation Plan**

### Milestone 1

We would allow creating a new entity - metric - that at this point cannot be used as a source for a new question. Using metrics in questions would be handled in the next milestone.

```[tasklist]
- [ ] BE - Add a property to `card` to know it's a "metric", like we do for models
- [ ] FE - Add `New -> Metric`, `Edit metric definition` flows with `/metric` url
- [ ] FE - Add clauses restrictions for metrics
- [ ] FE - Add special metric icons/headers, remove query editing controls in the simple mode
```

<img width="552" alt="Screenshot 2023-04-10 at 18 33 59" src="https://user-images.githubusercontent.com/8542534/230934148-e5e6c742-3ba0-4452-8a90-e564776ea06a.png">

### Milestone 2

Allow using metrics as sources in non-native questions. We would follow the existing approach with using them in `aggregation` clauses like `["metric", 1]` and make the UI more sophisticated later. When in the chill & notebook modes, the metric should be wrapped in a ad-hoc question with `aggregation` clause using the metric, similarly to models.

```[tasklist]
- [ ] FE - Allow creating ad-hoc questions based on metrics
- [ ] BE - Handle card-based metrics in the `aggregation` clause
```

<img width="834" alt="Screenshot 2023-04-10 at 18 40 47" src="https://user-images.githubusercontent.com/8542534/230936503-7b2001d4-ccb0-42bc-b403-db931c5bd870.png">

### Milestone 3

Expand the metric definition in the notebook editor and make these clauses readonly. This change doesn't affect the underlying query in any way.

<img width="664" alt="Screenshot 2023-04-10 at 18 43 04" src="https://user-images.githubusercontent.com/8542534/230937472-a05b1fd2-b8f7-4121-9675-e1fe2fa55cdb.png">

**Comment by bshepherdson** [comment]
It's a little unfortunate that the property for models is a boolean `dataset: true`. It sucks to proliferate that pattern and add `metric: true` as well, when we really want something more like `kind: card | model | metric | ...`. OTOH SQL doesn't like enums much.

This makes sense from a BE POV. I hope that we can get MLv2 in a good spot to support metrics before you get to Milestones 2 and 3.

**Comment by kamilmielnik** [comment]
Closing in favor of #37335
