### ISSUE TITLE
Adjust Markdown support in descriptions

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#29882]
Related to the epic https://github.com/metabase/metabase/issues/28754

Update markdown support in descriptions:
- forbid `# heading`
- show links as white text
- display markdown on blur in textarea at dashboard description

**Implementation Plan**
- [ ] figure out, maybe not full support of markdown is needed, but only _italic_, **bold** and [link](https://metabase.com)
- [ ] change color of the link to white
- [ ] add displaying markdown in dashboard description
- [ ] add tests
