### ISSUE TITLE
[Epic] Default Text Filters to contains

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#29881]
Closes https://github.com/metabase/metabase/issues/11369

**Implementation Plan**

### Milestone 1

Make new string field filters default to `string/contains` for high cardinality fields.

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/29411
- [ ] https://github.com/metabase/metabase/pull/29885
```

### Milestone 2

Make new `string/contains` and `string/does-not-contain` field filters case insensitive.

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/29887
- [ ] https://github.com/metabase/metabase/pull/30121
```
