### ISSUE TITLE
Non-Metabase users are unable to unsubscribe from alerts they have been subscribed to

### ISSUE THREAD

**Issue by likeshumidity** [metabase/metabase#29955]
[Product doc](https://www.notion.so/metabase/Let-non-users-unsubscribe-from-alerts-and-subscriptions-efc38b07283944f3b084f84146fed7ca)

**Is your feature request related to a problem? Please describe.**
Subscription recipients who are not Metabase users are unable to unsubscribe.

**Describe the solution you'd like**
- Allow subscription recipients who are not Metabase users to unsubscribe

**Describe alternatives you've considered**
- Add a subscription confirmation email prior to subscribing non-users to alerts

**How important is this feature to you?**
- Requested by customer
- This is potentially dangerous issue as a typo could cause the sender's email host (`.metabaseapp.com` or customer's host) to be marked as spam or damage the sending server reputation which is very difficult to fix.

**Additional context**
![image](https://user-images.githubusercontent.com/8808703/231007616-a3697872-1dd0-4369-b804-63db1fb765b2.png)

```[tasklist]
### Tasks
- [x] (BE) API Route and Backend Functionality (https://github.com/metabase/metabase/pull/30597)
- [x] (BE) Email Notifcation URL for Non-Users (https://github.com/metabase/metabase/pull/30892)
- [x] (BE) Return pulse name with unsubscribe request (https://github.com/metabase/metabase/pull/31672)
- [x] (FE) Create Unsubscribe Page and API Requests (https://github.com/metabase/metabase/pull/32379)
```

**Comment by JesseSDevaney** [comment]
Hey @luizarakaki! I am about to merge the FE portion for this issue - I believe the only remaining piece on the product doc is:
- Logging the unsubscribe/resubscribe events to the audit table

Has this already been done and the issue should be closed after my mergers? Or is this work still needed to be completed?

**Comment by luizarakaki** [comment]
Let's create a separate issue for audit tracking.

This would need the activity_log table that is still in the works. I think we can add this event on 48. cc @noahmoss @qwef
