### ISSUE TITLE
[Epic] Allow users to hide action form fields

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#30016]
[Product doc](https://www.notion.so/metabase/Allow-users-to-hide-action-form-fields-a30816929847430883b5be5dd74287e6)

Feature branch: [30016/main](https://github.com/metabase/metabase/tree/30016/main)

```[tasklist]
### Milestone 0
- [ ] https://github.com/metabase/metabase/pull/30870
- [ ] https://github.com/metabase/metabase/pull/30873
- [ ] https://github.com/metabase/metabase/pull/30900
- [ ] https://github.com/metabase/metabase/pull/30904
- [ ] https://github.com/metabase/metabase/pull/30931
- [ ] https://github.com/metabase/metabase/pull/30933
- [ ] https://github.com/metabase/metabase/pull/31027
- [ ] https://github.com/metabase/metabase/pull/31225
- [ ] https://github.com/metabase/metabase/pull/31320
- [ ] https://github.com/metabase/metabase/pull/31354
- [ ] https://github.com/metabase/metabase/pull/31329
- [ ] https://github.com/metabase/metabase/pull/31464
- [ ] https://github.com/metabase/metabase/pull/31655
- [ ] https://github.com/metabase/metabase/pull/31567
- [ ] https://github.com/metabase/metabase/pull/31659
- [ ] https://github.com/metabase/metabase/pull/31771
- [ ] https://github.com/metabase/metabase/pull/31759
- [ ] https://github.com/metabase/metabase/pull/30902
```
