### ISSUE TITLE
[Epic] New sandbox mode: connection impersonation

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#30020]
**Links**
- [product doc](https://www.notion.so/metabase/New-sandbox-mode-connection-impersonation-49ecf43c3ffa4983883131c2af10580f)
- [mockups](https://www.figma.com/file/0FbaSE58pGiAmnBk7Gd4ZF/Role-based-sandboxing?node-id=323-6939&t=qSczvJSuZj2IyDql-0) 
- feature branch: `feature-connection-impersonation`

**Implementation Plan**

```[tasklist]
### Milestone 1: connection impersonation shippable MVP
- [ ] https://github.com/metabase/metabase/pull/30132
- [ ] FE: Connect the UI to the API
- [ ] FE: Update the help sidebar
- [ ] E2E: add specs
- [ ] FE: show the connection impersonation UI on supported databases only
```

```[tasklist]
### Milestone 2: table visibility configuration
- [ ] FE: add table visibility permissions configuration flow
```

```[tasklist]
### Milestone 3: update in-product docs
- [ ] FE: add table visibility permissions configuration flow
```

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/5147

**Comment by alxnddr** [comment]
Duplicate of https://github.com/metabase/metabase/issues/29491
