### ISSUE TITLE
[Epic] Large databases can be very slow to view in Data Model

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#30190]
Closes https://github.com/metabase/metabase/issues/21985

The issue is that the data model page relies on `/api/database/:id/metadata` which loads all the tables with all the fields at once. This can be a very heavy call and we need to make the page load only minimal required data for each tab.

### Implementation plan

Currently the tab works by loading the full database metadata - both on load and on changes. We'll rework the data flow in the tab to load only minimal required data on demand.

#### Milestone 1 - everything but the field settings page

Integration branch https://github.com/metabase/metabase/pull/30338

Solves performance issues for most use cases. The only legacy tab that still loads all the data is field settings. You can open it by clicking on the gear icon on the page with the field list.

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/30204
- [ ] https://github.com/metabase/metabase/pull/30394
- [ ] https://github.com/metabase/metabase/pull/30352
- [ ] https://github.com/metabase/metabase/issues/30306
- [ ] https://github.com/metabase/metabase/pull/30416
- [ ] https://github.com/metabase/metabase/pull/30434
- [ ] https://github.com/metabase/metabase/pull/30338
```

#### Milestone 2 - field settings page

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/30423
- [ ] https://github.com/metabase/metabase/pull/30484
```
