### ISSUE TITLE
[Epic] MLv2 migration FE work

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#30237]
We're now focused on porting query logic in the notebook editor (epic #28034), but metabase-lib is used in way more different places. This issue collects significant chunks of work that can be done to assist the overall migration from MLv1 to MLv2

```[tasklist]
- [ ] Minimize MLv1 surface area. Example: `Question` class has methods that shouldn't be a part of metabase-lib and are worth moving out (e.g. URL building method or `apiGetResults`, but there could be more)
- [ ] Consolidate and/or port `*_type` property access. We want to make column properties like `base_type`, `effective_type`, and `semantic_type` opaque for the FE (see #30054). It'd be helpful if we could isolate or maybe immediately port the code accessing these properties to MLv2
- [ ] Once #28587 is done and we can turn cards into opaque objects, we should go through files working with `Question` instances and refactor them to use opaque cards + MLv2 helpers
- [ ] Refactor code from using raw api responses for `metabase-lib/metadata` entities (e.g. `Database`, `Table`, `Schema`, `Field`) to the corresponding `metabase-lib` classes. @ranquild
- [ ] #29369
```

**Comment by darksciencebase** [comment]
Outdated
