### ISSUE TITLE
BE - Hide App DB from the list on the database admin page

### ISSUE THREAD

**Issue by escherize** [metabase/metabase#30301]
Users should not **ever** be able to see the audit db, so we should not show it. This can be handled on BE.

----

## Tasks

- [x] Simply filtering this out on the `GET /api/database/`
- [x] swap `GET /api/database/` to use defendpoint
- [ ] investigate how this will fit together with permission updates
    - [ ] does this need to be hidden from the permissions graph?
    - [ ] does it being absent lead to any weird permission updates?

**Comment by escherize** [comment]
closed by #30305
