### ISSUE TITLE
Enable admins to pin a dashboard as their homepage

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#30391]
This feature will add the ability for Admins to assign a dashboard to be rendered on the homescreen for their users.

**Links**
- product doc: https://www.notion.so/metabase/Enable-admins-to-pin-a-dashboard-as-their-homepage-7502314358744260ae25cb93faf84d23
- feature branch: `custom-homepage`

```[tasklist]
### Tasks
- [ ] Add Settings to admin section
- [ ] Update homepage to render Dashboard when appropriate
- [ ] Add customize button to home screen
- [ ] Add message to dashoard edit screen
- [ ] Double check permissions and tests
```
