### ISSUE TITLE
Enforce `MB_AUDIT_MAX_RETENTION_DAYS`=30 in OSS instances for `query_execution` and `audit_log` tables

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#30492]
In the context of [Control the size of log tables for OSS and Paid plans](https://www.notion.so/metabase/Control-the-size-of-log-tables-for-OSS-and-Paid-plans-f94dda5477b7473eac7b226306087299) we should enforce the env var on OSS instances.

- This shouldn't be applied to Cloud instances, as they will be handled separately.

- [ ] Enforce `MB_AUDIT_MAX_RETENTION_DAYS` on OSS
- [ ] Apply to `query_execution`
- [ ] Apply to `audit_logs`
