### ISSUE TITLE
[MLv2] Breakouts

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#30509]
### Tasks

- [x] https://github.com/metabase/metabase/issues/29704
- [x] https://github.com/metabase/metabase/issues/29612
- [x] https://github.com/metabase/metabase/issues/30113
- [x] https://github.com/metabase/metabase/issues/29705
- [x] https://github.com/metabase/metabase/issues/29996
- [x] https://github.com/metabase/metabase/issues/28718
- [x] https://github.com/metabase/metabase/issues/30364
- [x] https://github.com/metabase/metabase/issues/30365
- [x] https://github.com/metabase/metabase/issues/30367
- [x] https://github.com/metabase/metabase/issues/30368
- [x] https://github.com/metabase/metabase/issues/30466
- [x] https://github.com/metabase/metabase/issues/30703
- [x] https://github.com/metabase/metabase/issues/30703
- [x] https://github.com/metabase/metabase/issues/30856
- [x] https://github.com/metabase/metabase/issues/30980
- [x] https://github.com/metabase/metabase/issues/30951
- [x] https://github.com/metabase/metabase/issues/31000
- [x] https://github.com/metabase/metabase/issues/30122
- [x] https://github.com/metabase/metabase/issues/31367
- [x] https://github.com/metabase/metabase/issues/31399
- [x] https://github.com/metabase/metabase/issues/31437
- [x] https://github.com/metabase/metabase/issues/31469
- [x] https://github.com/metabase/metabase/issues/31482

**Comment by kulyk** [comment]
Moved this epic off GitHub tasklists — it just stopped rendering :(

**Comment by camsaul** [comment]
Done
