### ISSUE TITLE
[MLv2] Custom columns

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#30513]
### Prior work

```[tasklist]
- [x] #28694
- [ ] https://github.com/metabase/metabase/issues/31155
- [ ] https://github.com/metabase/metabase/issues/31909
```

### Milestone 1 - computing columns and field refs using MLv2

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/35988
- [ ] https://github.com/metabase/metabase/pull/36265
- [ ] https://github.com/metabase/metabase/issues/36233
- [ ] https://github.com/metabase/metabase/issues/36254
- [ ] https://github.com/metabase/metabase/issues/36406
- [ ] https://github.com/metabase/metabase/issues/36710
- [ ] https://github.com/metabase/metabase/issues/36235
- [ ] https://github.com/metabase/metabase/issues/37292
```

### Milestone 2 - modifying the query using MLv2

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/34830
- [ ] https://github.com/metabase/metabase/issues/34831
- [ ] https://github.com/metabase/metabase/issues/36075
- [ ] https://github.com/metabase/metabase/issues/36120
- [ ] https://github.com/metabase/metabase/issues/36167
- [ ] https://github.com/metabase/metabase/issues/36168
- [ ] https://github.com/metabase/metabase/issues/36459
- [ ] https://github.com/metabase/metabase/issues/36464
- [ ] https://github.com/metabase/metabase/issues/35947
- [ ] https://github.com/metabase/metabase/issues/35948
- [ ] https://github.com/metabase/metabase/issues/36574
- [ ] https://github.com/metabase/metabase/issues/36575
- [ ] https://github.com/metabase/metabase/issues/35982
- [ ] https://github.com/metabase/metabase/issues/36746
- [ ] https://github.com/metabase/metabase/issues/37461
- [ ] https://github.com/metabase/metabase/issues/36211
- [ ] https://github.com/metabase/metabase/issues/37528
- [ ] https://github.com/metabase/metabase/issues/37573
```
```[tasklist]
### Milestone 3 - cleanup
- [ ] https://github.com/metabase/metabase/issues/36699
- [ ] https://github.com/metabase/metabase/issues/36717
- [ ] https://github.com/metabase/metabase/issues/36639
- [ ] https://github.com/metabase/metabase/issues/37173
```
