### ISSUE TITLE
[MLv2] Filters

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#30512]
## Backend

```[tasklist]
### Tasks
- [x] #28692
- [x] https://github.com/metabase/metabase/issues/29867
- [x] #28703
- [x] https://github.com/metabase/metabase/issues/31676
- [x] https://github.com/metabase/metabase/issues/31677
- [x] https://github.com/metabase/metabase/issues/32058
- [x] https://github.com/metabase/metabase/issues/32060
- [x] https://github.com/metabase/metabase/issues/32159
- [ ] https://github.com/metabase/metabase/issues/32160
- [ ] https://github.com/metabase/metabase/issues/32409
- [ ] https://github.com/metabase/metabase/issues/33022
- [ ] https://github.com/metabase/metabase/issues/33023
```

## Frontend

```[tasklist]
### Tasks
- [x] https://github.com/metabase/metabase/issues/31673
- [ ] https://github.com/metabase/metabase/issues/32405
- [ ] https://github.com/metabase/metabase/issues/32474
- [ ] https://github.com/metabase/metabase/issues/30999
- [ ] https://github.com/metabase/metabase/issues/32475
- [ ] https://github.com/metabase/metabase/issues/32476
- [ ] https://github.com/metabase/metabase/issues/31949
- [ ] https://github.com/metabase/metabase/issues/31948
```

### Open questions

1. `DefaultPicker` [uses `FieldValuesWidget`](https://github.com/metabase/metabase/blob/3d2c121d1e97aa70c942e491a8be70341da3a3d4/frontend/src/metabase/query_builder/components/filters/pickers/DefaultPicker.jsx#L119) and it expects a MLv1 `Field` instance. Should we refactor / build an alternative component or maybe we can find a workaround?
2. `DefaultPicker` [accesses field visualization settings](https://github.com/metabase/metabase/blob/5bfd21b770394cb14c0fcc31704878bdc6352741/frontend/src/metabase/query_builder/components/filters/pickers/DefaultPicker.jsx#L73) to display a currency symbol. We haven't touched visualization settings in MLv2 yet, so we'll need to figure this out
3. [`ParameterValueWidget`](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/parameters/components/ParameterValueWidget.jsx) component depends on the filter `DatePicker` component via `DateAllOptionWidget`
