### ISSUE TITLE
[MLv2] Joins

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#30514]
```[tasklist]
### Tasks
- [ ] #28724
- [ ] https://github.com/metabase/metabase/issues/30093
- [ ] https://github.com/metabase/metabase/issues/31070
- [ ] https://github.com/metabase/metabase/issues/31173
- [ ] https://github.com/metabase/metabase/issues/31174
- [ ] https://github.com/metabase/metabase/issues/31175
- [ ] https://github.com/metabase/metabase/issues/31176
- [ ] https://github.com/metabase/metabase/issues/31180
- [ ] https://github.com/metabase/metabase/issues/31664
- [ ] https://github.com/metabase/metabase/issues/31677
- [ ] https://github.com/metabase/metabase/issues/31915
- [ ] https://github.com/metabase/metabase/issues/31920
- [ ] https://github.com/metabase/metabase/issues/32005
- [ ] https://github.com/metabase/metabase/issues/32006
- [ ] https://github.com/metabase/metabase/issues/32007
- [ ] https://github.com/metabase/metabase/issues/32009
- [ ] https://github.com/metabase/metabase/issues/32014
- [ ] https://github.com/metabase/metabase/issues/32015
- [ ] https://github.com/metabase/metabase/issues/32026
- [ ] https://github.com/metabase/metabase/issues/32053
- [ ] https://github.com/metabase/metabase/issues/32058
- [ ] https://github.com/metabase/metabase/issues/32060
- [ ] https://github.com/metabase/metabase/issues/32081
- [ ] https://github.com/metabase/metabase/issues/32438
- [ ] https://github.com/metabase/metabase/issues/32437
- [ ] https://github.com/metabase/metabase/issues/32443
- [ ] https://github.com/metabase/metabase/issues/32454
- [ ] https://github.com/metabase/metabase/issues/32480
- [ ] https://github.com/metabase/metabase/issues/32509
- [ ] https://github.com/metabase/metabase/issues/32511
- [ ] https://github.com/metabase/metabase/issues/32530
- [ ] https://github.com/metabase/metabase/issues/32558
- [ ] https://github.com/metabase/metabase/issues/32764
- [ ] https://github.com/metabase/metabase/issues/32759
- [ ] https://github.com/metabase/metabase/issues/32758
- [ ] https://github.com/metabase/metabase/issues/32803
- [ ] https://github.com/metabase/metabase/issues/32897
- [ ] https://github.com/metabase/metabase/issues/32920
- [ ] https://github.com/metabase/metabase/issues/33012
- [ ] https://github.com/metabase/metabase/issues/33086
- [ ] https://github.com/metabase/metabase/issues/33083
- [ ] https://github.com/metabase/metabase/issues/33082
- [ ] https://github.com/metabase/metabase/issues/32063
- [ ] https://github.com/metabase/metabase/pull/33454
- [ ] https://github.com/metabase/metabase/issues/34370
- [ ] https://github.com/metabase/metabase/issues/34404
- [ ] https://github.com/metabase/metabase/issues/34526
```
