### ISSUE TITLE
[MLv2] Medium-Priority Bug Fixes

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#30519]
```[tasklist]
### Tasks
- [x] #29734
- [x] #29702
- [x] #29746
- [x] #29764
- [x] #29902
- [x] #29745
- [x] #29770
- [x] #29988
- [x] #29747
- [x] #29898
- [x] #29964
- [x] #29944
- [x] #29947
- [ ] #30568
- [ ] #29895
- [ ] #29908
- [ ] #30280
- [ ] #29748
- [ ] #29897
- [ ] #29904
- [ ] #29909
- [ ] #29910
- [ ] #29935
- [ ] #29936
- [ ] #29938
- [ ] #29941
- [ ] #29942
- [ ] #29946
- [ ] #29948
- [ ] #29950
- [ ] #29953
- [ ] #29958
- [ ] #30385
- [ ] https://github.com/metabase/metabase/issues/30397
- [ ] #30401
- [ ] https://github.com/metabase/metabase/issues/30857
- [ ] https://github.com/metabase/metabase/issues/30858
- [ ] https://github.com/metabase/metabase/issues/30948
- [ ] https://github.com/metabase/metabase/issues/30949
- [ ] https://github.com/metabase/metabase/issues/30950
- [ ] https://github.com/metabase/metabase/issues/30957
- [ ] #29949
- [ ] https://github.com/metabase/metabase/issues/31053
- [ ] https://github.com/metabase/metabase/issues/31223
- [ ] https://github.com/metabase/metabase/issues/31268
- [ ] https://github.com/metabase/metabase/issues/31365
- [ ] https://github.com/metabase/metabase/issues/31366
- [ ] https://github.com/metabase/metabase/issues/31368
- [ ] #31521
- [ ] https://github.com/metabase/metabase/issues/31624
- [ ] https://github.com/metabase/metabase/issues/31741
- [ ] https://github.com/metabase/metabase/issues/31769
- [ ] https://github.com/metabase/metabase/issues/31775
- [ ] https://github.com/metabase/metabase/issues/31858
- [ ] https://github.com/metabase/metabase/issues/32049
- [ ] https://github.com/metabase/metabase/issues/32063
```

**Comment by camsaul** [comment]
Closing this for now since all the stuff that's blocking the original MLv2 epic is fixed, and the remaining 2 bugs can be fixed at our leisure. We don't need an epic to track every rando bug that comes up with MLv2 anymore
