### ISSUE TITLE
[MLv2] Aggregations

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#30511]
```[tasklist]
### Tasks
- [x] #28693
- [ ] #28702
- [ ] https://github.com/metabase/metabase/issues/31001
- [ ] https://github.com/metabase/metabase/issues/31157
- [ ] https://github.com/metabase/metabase/issues/31255
- [ ] https://github.com/metabase/metabase/issues/31256
- [ ] https://github.com/metabase/metabase/issues/31266
- [ ] https://github.com/metabase/metabase/issues/31555
- [ ] https://github.com/metabase/metabase/issues/31871
```
