### ISSUE TITLE
[Epic] Add test coverage for Admin - Data Model

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#30557]
Epic https://github.com/metabase/metabase/issues/30941

## Location
- `frontend/src/metabase/admin/datamodel`

## Dimensions

- Permissions - admin / data / data model (EE)
- Schemas - not supported (MySQL) / 1 / 2+
- Table visibility - visible / hidden / hidden with a specified reason
- Table field sort order - database / alphabetical / smart / custom
- Field variant - regular / sensitive
- Field visibility - visible / details / none
- Field filtering settings - list / search / none
- Field casting
- Field values remapping - original / foreign key / custom
- Json fields

## Actions

Schemas:
- Search

Tables:
- Search
- View metadata / original schema
- Change table title
- Change / clear table description
- Change table visibility
- Change field order

Fields:
- Change field title
- Change / clear field description
- Change field visibility
- Change field semantic type 
- Change field foreign key target
- Change field currency
- Change field filtering settings
- Add type casting to a field
- Add foreign key values mapping
- Add custom values mapping
- Unfold json field
- Rescan field / all table field values
- Discard field / all table fields values 

### Integration tests

`MetadataEditor`

A page with a sidebar with schemas / tables and the list of fields in a table.

(no schema)
- [x] selects the first database by default
- [x] skips the schema selection

(single schema)
- [x] selects the first database by default
- [x] selects the only schema by default
- [x] allows to search for a table
- [x] allows to switch between metadata and original schema
- [x] allows to search for a field semantic type
- [x] allows to navigate to table settings
- [x] allows to rescan field values
- [x] allows to discard field values
- [x] does not allow to clear the table name
- [x] does not allow to clear the field name
- [x] allows to clear the table description
- [x] allows to clear the field description
- [x] shows field target for foreign keys
- [x] does not show field target for non-foreign keys
- [x] shows currency settings for supported fields
- [x] does not show currency settings for non-supported fields

(multiple schema)
- [x] does not select the first schema when there are multiple
- [x] allows to search for a schema
- [x] allows to search for a table
- [x] allows to navigate to table settings (including schema)

(multiple databases)
- [x] allows to switch databases

(no databases)
- [x] shows an empty state when there are no databases
- [x] shows an empty state when the specified database is not found

(json fields)
- [x] displays unfolded json fields with paths

(data model permissions)
- [x] displays access denied error for foreign keys with inaccessible targets

`MetadataTableSettings`

A separate page for table settings where it's possible to rescan values for all fields in the table.

(no schema)
- [x] allows to navigate to metadata editor

(one schema)
- [x] allows to navigate to metadata editor
- [x] allows to rescan field values
- [x] allows to discard field values

(multiple schemas)
- [x] allows to navigate to metadata editor (including schema)

`MetadataFieldSettings`

A separate page where it's possible to change advanced field properties like values remapping.

(no schema)
- [x] allows to navigate to metadata editor

(one schema)
- [x] allows to navigate to metadata editor

(multiple schemas)
- [x] allows to navigate to metadata editor (including schema)

(field settings)
- [x] does not allow to clear the field name
- [x] allows to clear the description
- [x] displays json field settings for json fields
- [x] does not display json field settings for non-json fields
- [x] displays type coercion settings for a supported field
- [x] does not display type coercion setting for an unsupported field
- [x] allows to rescan field values
- [x] allows to discard field values

(data model permissions)
- [x] displays access denied error for foreign keys with inaccessible targets
- [x] displays access denied error for existing custom values remapping

#### E2E tests

`MetadataEditor`

(admin permissions)

- [ ] show & hide all tables in a schema
- [ ] shows expanded / collapsed json fields
- [ ] allows to update the title of a table
- [ ] allows to update the description of a table
- [ ] allows to update the table visibility
- [ ] allows to update the table field order
- [ ] allows to update the field title
- [ ] allows to update the field description
- [ ] allows to update the field visibility
- [ ] allows to make a field a primary key
- [ ] allows to make a field a foreign key with a target
- [ ] allows to make a field a non-key
- [ ] allows to update the field currency

(json fields)
- [ ] allows to update the nested json field name

(data model permissions)
- [ ] allows to change the foreign key target with partial permissions

`MetadataFieldSettings`

(admin permissions)

- [ ] allows to update the field title
- [ ] allows to update the field description
- [ ] allows to update the field visibility
- [ ] allows to make a field a primary key
- [ ] allows to make a field a foreign key with a target
- [ ] allows to update the field currency
- [ ] allows to update the field filtering settings
- [ ] allows to enable type casting
- [ ] allows to set foreign key values remapping
- [ ] allows to set custom values remapping
- [ ] allows to toggle json fields

(data model permissions)
- [ ] allows to set foreign key values remapping
- [ ] allows to change the foreign key target
- [ ] does not allow to set custom values remapping
