### ISSUE TITLE
Use V2 paths in permissions graph and the admin UI

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#30666]
Final tasks for splitting data access and query builder access and merging GUI and SQL permissions.

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/27302
- [ ] https://github.com/metabase/metabase/issues/27200
- [ ] Update Cypress tests accordingly.
- [ ] Write V1 fallback paths whenever V2 paths are updated
```

**Comment by noahmoss** [comment]
Closing due to change in approach - new milestones in https://github.com/metabase/metabase/issues/26918
