### ISSUE TITLE
[Epic] Prepare metabase-lib/metadata for CLJS migration

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#30763]
Preparation work for migrating `metabase-lib/metadata` to CLJS:
- All `metabase-lib/metadata` classes have correct types
- Used in the app instead of raw api objects in all places
- Created in the app and tests in a proper way, e.g. via metadata creation

### Milestone 1 - fixing types and tests

I hit a major roadblock with the last type - `Field`. It's used incorrectly in many places. So we need to fix these places first before un-ignoring `Field`.

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/30661
- [ ] https://github.com/metabase/metabase/pull/30691
- [ ] https://github.com/metabase/metabase/pull/30694
- [ ] https://github.com/metabase/metabase/pull/30728
- [ ] https://github.com/metabase/metabase/pull/30729
- [ ] https://github.com/metabase/metabase/pull/30739
- [ ] https://github.com/metabase/metabase/pull/30754
- [ ] https://github.com/metabase/metabase/pull/30761
- [ ] https://github.com/metabase/metabase/pull/30769
- [ ] https://github.com/metabase/metabase/pull/30808
- [ ] https://github.com/metabase/metabase/pull/30825
- [ ] https://github.com/metabase/metabase/pull/30827
- [ ] https://github.com/metabase/metabase/pull/30828
- [ ] https://github.com/metabase/metabase/pull/30829
```

### Milestone 2 - refactor tests to create metabase-lib entities via `createMockMetadata`
```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/30832
- [ ] https://github.com/metabase/metabase/pull/30880
- [ ] https://github.com/metabase/metabase/pull/30899
```
