### ISSUE TITLE
[Epic] Add test coverage for Setup

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#30984]
Epic https://github.com/metabase/metabase/issues/30941

## Location
- `frontend/src/metabase/setup`

## Dimensions
- default browser language
- selected language
- available database engines
- cloud/non-cloud
- email set / not set
- user with/ without name
- tracking enabled / disabled
- root url (embedding)

## Actions
- change language
- enter user details
- enter database details / inviting another admin / skipping database setup
- toggling tracking on / off
- navigating between steps
- complete setup 
- subscribe to the newletter

### Unit tests

`getDefaultLocale`
- [ ] finds locale for one-symbol locale codes (e.g. `en`)
- [ ] finds locale for two-symbol locale codes (e.g. `en-US`)
- [ ] defaults to English if it is supported and the browser locale is not supported by the instance
- [ ] does not return a default locale when English is not supported by the instance

### Integration tests

`ActiveStep`
- [ ] renders the step content

`InactiveStep`
- [ ] renders the step content
- [ ] allows to navigate to the step when it was completed
- [ ] does not allow to navigate to the step when it was not completed
- [ ] does not allow to navigate to the step when setup was completed

`SetupSection`
- [ ] expands and collapses the section

`SetupHelp`
- [ ] renders the proper documentation link

`LanguageStep`
- [ ] renders the title when the step is active
- [ ] renders the title when the step is completed
- [ ] allows to submit the step only when the language was selected
- [ ] re-renders in the new language when it was selected and locale data was loaded
- [ ] navigates back to the step when it was selected

`UserStep`
- [ ] renders the title when the step is not reached
- [ ] renders the title when the step is active
- [ ] renders the title when the step is completed
- [ ] renders the greeting for the user with the first name
- [ ] renders the greeting for the user without the first name
- [ ] renders help text when running on cloud
- [ ] navigates back to the step when it was selected

`UserForm`
- [ ] allows to submit the form with the user name
- [ ] allows to submit the form without the user name
- [ ] validates and displays error messages for form fields
- [ ] validates the complexity of the user password

`DatabaseStep`
- [ ] renders the title when the step is not reached
- [ ] renders the title when the step is active
- [ ] renders the title when the step was completed with the database details
- [ ] renders the title when the step was completed with the user details (when email is configured)
- [ ] renders the title when the step was skipped
- [ ] navigates back to the step when it was selected
- [ ] allows to submit the step with valid database details
- [ ] renders an error message when submitting invalid database details
- [ ] allows to submit the step by inviting another admin when the email was configured
- [ ] does not allow to invite another admin when email is not configured
- [ ] allows to skip the step

`DatabaseHelp`
- [ ] renders the card when the database step is active
- [ ] does not render the card when the database step is not active

`InviteUserForm`
- [ ] allows to submit the form with the user name
- [ ] allows to submit the form without the user name
- [ ] validates and displays error messages for form fields
- [ ] validates that the newly invited user cannot have the same email as the current one

`PreferencesStep`
- [ ] renders the title when the step is not reached
- [ ] renders the title when the step is active
- [ ] renders the title when the step was completed and tracking was enabled
- [ ] renders the title when the step was completed and tracking was disabled
- [ ] allows to toggle tracking on and off
- [ ] allows to submit setup
- [ ] renders an error message if setup cannot be completed successfully 

`CompletedStep`
- [ ] renders when setup is completed
- [ ] does not render when setup is not completed
- [ ] renders a link to the app when `base` url was set
- [ ] renders a default link to the app when `base` url wasn't set
- [ ] renders the newsletter form

`NewsletterForm`
- [ ] allows to submit the form with the initial user email and shows the success message
- [ ] does not allow to submit the form without the user email

`CloudMigrationHelp`
- [ ] renders when setup is completed and on cloud with the correct link
- [ ] does not render when setup is not completed
- [ ] does not render when not on cloud

`WelcomePage`
- [ ] does not render initially if locale data is not loaded
- [ ] renders in English after the timeout even if locale data is not (yet) loaded
- [ ] renders in English if fails to load locale data
- [ ] renders in the user language (e.g. non-English) when the locale data was loaded

`SettingsPage`
- [ ] allows navigating back to the language step
- [ ] allows navigating back to the user step

`Setup`
- [ ] re-renders the welcome page when locale data was loaded after it was displayed
- [ ] re-renders all steps in the new language when the locale was changed and locale data was loaded
- [ ] allows to complete the setup flow with the database details
- [ ] allows to complete the setup flow with database details after the database step was skipped
- [ ] allows to complete the setup flow with database details after invite details were set
- [ ] allows to complete the setup flow without the database details
- [ ] allows to complete the setup flow by inviting another admin
- [ ] allows to complete the setup flow by inviting another admin after the database details were set
- [ ] allows to complete the setup flow with tracking enabled
- [ ] allows to complete the setup flow with tracking disabled
- [ ] sets the initial user email for the newsletter to one used in the setup

### E2E tests

- [ ] renders the welcome page and the steps in a non-English language if it is the default one in the browser
- [ ] re-renders the steps in a non-English language if the language was changed during setup
- [ ] allows to complete the setup flow with database details (Postgres)
- [ ] allows to complete the setup flow by inviting another admin and accepting the invite email
- [ ] allows to complete the setup flow by skipping database setup
- [ ] respects password policy settings and does not allow to proceed with an invalid password
- [ ] sends snowplow events
