### ISSUE TITLE
[MLv2] Drill Thru

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#31004]
| **Drill**                  | BE        | FE |
|----------------------------|-----------|----|
| `automatic-insights`       | ✅  | ✅ |
| `column-filter`            | ✅️        | ✅ |
| `distribution`             | ✅️        | ✅ |
| `fk-details`               | ✅        | ✅ |
| `fk-filter`                | ✅        | ✅ |
| `pivot`                    | ✅  | ✅ |
| `pk`                       | ✅        | ✅ |
| `quick-filter`             | ✅        | ✅ |
| `sort`                     | ✅        | ✅ |
| `summarize-column`         | ✅️        | ✅ |
| `summarize-column-by-time` | ✅️        | ✅ |
| `underlying-records`       | ✅️        | ✅ |
| `zoom`                     | ✅️        | ✅ |
| `zoom-in.binning`          | ✅        | ✅ |
| `zoom-in.geographic`       | ✅        | ✅ |
| `zoom-in.timeseries`       | ✅        | ✅ |

BE
- [X] #36125

## FE

[Drills FE integration branch ](https://github.com/metabase/metabase/pull/35952)

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/35949
- [ ] https://github.com/metabase/metabase/issues/36002
- [ ] https://github.com/metabase/metabase/issues/36321
- [ ] https://github.com/metabase/metabase/issues/36573
- [ ] https://github.com/metabase/metabase/issues/36615
- [ ] https://github.com/metabase/metabase/pull/35952
```

## BE

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/37633
- [ ] https://github.com/metabase/metabase/issues/36253
- [ ] https://github.com/metabase/metabase/issues/36674
- [ ] https://github.com/metabase/metabase/issues/33559
- [ ] https://github.com/metabase/metabase/issues/36125
- [ ] https://github.com/metabase/metabase/issues/33558
- [ ] https://github.com/metabase/metabase/issues/36173
- [ ] https://github.com/metabase/metabase/issues/36247
- [ ] https://github.com/metabase/metabase/issues/33560
- [ ] https://github.com/metabase/metabase/issues/36177
- [ ] https://github.com/metabase/metabase/issues/33730
- [ ] https://github.com/metabase/metabase/issues/36143
- [ ] https://github.com/metabase/metabase/issues/35618
- [ ] https://github.com/metabase/metabase/issues/36124
- [ ] https://github.com/metabase/metabase/pull/35878
- [ ] https://github.com/metabase/metabase/issues/36001
- [ ] https://github.com/metabase/metabase/issues/36000
- [ ] https://github.com/metabase/metabase/issues/36126
- [ ] https://github.com/metabase/metabase/issues/36129
- [ ] https://github.com/metabase/metabase/issues/36133
- [ ] https://github.com/metabase/metabase/issues/36130
- [ ] https://github.com/metabase/metabase/issues/35340
- [ ] https://github.com/metabase/metabase/issues/35343
- [ ] https://github.com/metabase/metabase/issues/35394
- [ ] https://github.com/metabase/metabase/issues/34443
- [ ] https://github.com/metabase/metabase/issues/35689
- [ ] https://github.com/metabase/metabase/issues/36581
- [ ] https://github.com/metabase/metabase/issues/36582
- [ ] https://github.com/metabase/metabase/issues/36583
- [ ] https://github.com/metabase/metabase/issues/36633
```

## Prior Work

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/30081
- [ ] https://github.com/metabase/metabase/pull/32431
- [ ] https://github.com/metabase/metabase/pull/33143
- [ ] https://github.com/metabase/metabase/issues/31007
- [ ] https://github.com/metabase/metabase/issues/33480
- [ ] https://github.com/metabase/metabase/issues/33479
- [ ] https://github.com/metabase/metabase/issues/33556
- [ ] https://github.com/metabase/metabase/pull/34231
- [ ] https://github.com/metabase/metabase/issues/33482
- [ ] https://github.com/metabase/metabase/issues/32108
- [ ] https://github.com/metabase/metabase/issues/33811
- [ ] https://github.com/metabase/metabase/issues/33557
- [ ] https://github.com/metabase/metabase/issues/33575
- [ ] https://github.com/metabase/metabase/issues/34233
- [ ] https://github.com/metabase/metabase/issues/34342
- [ ] https://github.com/metabase/metabase/issues/34346
- [ ] https://github.com/metabase/metabase/issues/34185
- [ ] https://github.com/metabase/metabase/issues/34497
- [ ] https://github.com/metabase/metabase/issues/34499
- [ ] https://github.com/metabase/metabase/issues/34223
- [ ] https://github.com/metabase/metabase/issues/34343
- [ ] https://github.com/metabase/metabase/issues/34107
- [ ] https://github.com/metabase/metabase/issues/34341
- [ ] https://github.com/metabase/metabase/issues/34383
- [ ] https://github.com/metabase/metabase/issues/34439
- [ ] https://github.com/metabase/metabase/issues/34440
- [ ] https://github.com/metabase/metabase/issues/34441
- [ ] https://github.com/metabase/metabase/issues/34445
- [ ] https://github.com/metabase/metabase/issues/34458
- [ ] https://github.com/metabase/metabase/issues/34874
- [ ] https://github.com/metabase/metabase/issues/34957
- [ ] https://github.com/metabase/metabase/issues/35247
- [ ] https://github.com/metabase/metabase/issues/35248
- [ ] https://github.com/metabase/metabase/issues/35341
- [ ] https://github.com/metabase/metabase/issues/35494
- [ ] https://github.com/metabase/metabase/issues/35509
- [ ] https://github.com/metabase/metabase/issues/35725
```
