### ISSUE TITLE
[Epic] *Really* encourage admins to add a DB

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#31015]
[Product doc](https://www.notion.so/metabase/Really-encourage-admins-to-add-a-DB-9c8c3a7d08ca45cb8672a154220f443e?pvs=4)

Integration branch: [`31015-integration-branch-encourage-admins-to-add-a-database`](https://github.com/metabase/metabase/tree/31015-integration-branch-encourage-admins-to-add-a-database)

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/31210
- [ ] https://github.com/metabase/metabase/pull/31470
- [ ] https://github.com/metabase/metabase/pull/31471
- [ ] https://github.com/metabase/metabase/pull/31545
- [ ] https://github.com/metabase/metabase/pull/31557
- [ ] https://github.com/metabase/metabase/pull/31610
```
