### ISSUE TITLE
[Epic] Add test coverage for Login

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#31115]
Epic https://github.com/metabase/metabase/issues/30941

## Location
- `frontend/src/metabase/auth`, starting from `Login` component

## Dimensions

- Login type - password, google auth, ldap, jwt, sso
- Each method configured & enabled / disabled

## Actions

- Log in via each method

## Pre-requirements

Same as in https://github.com/metabase/metabase/issues/31114

- [ ] Setup a test google auth account on CI with users (there is none currently)
- [ ] Setup a test ldap server on CI with users (the current one has no users)
- [ ] Setup a test jwt server on CI with users (there is none currently)
- [ ] Setup a test sso server on CI with users (there is none currently)

### Integration tests

`AuthButton`
- [ ] renders as a card with a link
- [ ] renders as a text link

`AuthLayout`
- [ ] renders with the illustration if it's enabled
- [ ] renders without the illustration if it's disabled

`PasswordButton`
- [ ] renders a link with the redirect url
- [ ] renders a link without the redirect url
- [ ] renders a link with ldap enabled
- [ ] renders a link with ldap disabled

`GoogleButton`
- [ ] renders as a text link with a redirect url

`SsoButton`
- [ ] automatically logs in if embedded
- [ ] does not automatically log in if not embedded
- [ ] logs in when clicking on the link when not embedded

`LoginForm`
- [ ] allows to submit the form only with an email and a non-empty password if ldap is disabled
- [ ] allows to submit the form with a username (= not just email) and a non-empty password if ldap is enabled
- [ ] allows to set "remember me" when session cookies aren't enabled
- [ ] does not allow to set "remember me" when session cookies are enabled

`PasswordPanel`
- [ ] allows to submit the login form
- [ ] renders backend errors when submitting the login form
- [ ] renders links to log in via other providers with the redirect url

`Login`
- [ ] implicitly selects the only available provider if it has a panel (= form) (e.g. only password is enabled)
- [ ] does not implicitly selects the only available provider if doesn't have a panel (e.g. only google auth is enabled)
- [ ] renders the panel (= form) of the selected provider
- [ ] renders links to log in via other providers with the redirect url
- [ ] supports navigation between auth methods (password -> jwt -> ldap)

### E2E tests

- [ ] logs in via password
- [ ] logs in via google auth
- [ ] logs in via ldap
- [ ] logs in via  jwt
- [ ] logs in via sso
- [ ] correctly redirects back to the page the user navigated from
- [ ] applies the user locale when it's different to the instance locale
- [ ] shows login errors for not valid passwords
- [ ] shows login errors for not existing users
