### ISSUE TITLE
[Epic] Add test coverage for Logout

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#31114]
Epic https://github.com/metabase/metabase/issues/30941

## Location
- `frontend/src/metabase/auth`, starting from `Logout` component

## Dimensions
- Login type - password, google auth, ldap, jwt, sso

## Actions
- logout

## Pre-requirements

- [ ] Setup a test google auth account on CI with users (there is none currently)
- [ ] Setup a test ldap server on CI with users (the current one has no users)
- [ ] Setup a test jwt server on CI with users (there is none currently)
- [ ] Setup a test sso server on CI with users (there is none currently)

### Integration tests

`Logout`
- [ ] deletes the session and refreshes the browser page

### E2E tests

- [ ] allows to logout and login again with a password / google auth / ldap / jwt / sso
- [ ] after logout, redirects attempts to access the restricted content to the login page (password / google auth / ldap / jwt / sso)
