### ISSUE TITLE
[Epic] Add test coverage for Forgot Password

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#31113]
Epic https://github.com/metabase/metabase/issues/30941

## Location
-  `frontend/src/metabase/auth`, starting from `ForgotPassword` component

## Dimensions

- email configured / not configured
- ldap enabled / disabled
- initial email set / not set

## Actions

- reset password

### Integration tests

`ForgotPassword`
- [ ] allows to the submit the form and shows a success message with a link to login
- [ ] allows to submit the form with the initial email
- [ ] shows an error message with a link to login if the email is not configured
- [ ] shows an error message if the email is configured and ldap is enabled

`ForgotPasswordForm`
- [ ] allows to submit the form with a valid email
- [ ] allows to submit the form with a valid initial email
- [ ] does not allow to submit an empty form
- [ ] does not allow to submit the form with an invalid email

### E2E tests

- [ ] submits a request to reset the password, clicks the link in the email, and opens the page to set a new password
- [ ] does not allow to reset the password with an email not matching users in the instance
