### ISSUE TITLE
[Epic] Add test coverage for Reset Password

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#31112]
Epic https://github.com/metabase/metabase/issues/30941

## Location
- `frontend/src/metabase/auth`, starting from `ResetPassword` component

## Dimensions

- reset password token - valid/invalid
- new password - valid/invalid

## Actions

- reset password

### Integration tests

`ResetPassword`
- [ ] allows to submit the password form, navigates to the home page and shows a toast
- [ ] shows a message for expired password reset tokens with a link to reset the password again
- [ ] shows an error message if the backend throws an error

`ResetPasswordForm`
- [ ] allows to submit a form with a valid new password
- [ ] does not allow to submit an empty form
- [ ] does not allow to submit the form with passwords not matching the policy
- [ ] does not allow to submit the form with an invalid confirmation password

### E2E tests

- [ ] allows to complete the password reset flow, starting from the forgot password page, then clicking the link with the password reset token in the email, setting the new password, navigating to the homepage, and making sure it is possible to logout and login once again with the new password
- [ ] allows to re-request the password reset token for expired tokens
- [ ] respects password policy settings and does not allow to proceed with an invalid password
