### ISSUE TITLE
[Epic] Add test coverage for Home page

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#31127]
Epic https://github.com/metabase/metabase/issues/30941

## Location
- `frontend/src/metabase/home`

## Dimensions

- User is admin / not admin
- User is installer (who completed the setup process) / no
- User with/without name
- Date of the first login of the current user - within the last 2 weeks / no
- Database count - 0, 1, 2+
- Sample database exists / does not exist
- Custom database exists / does not exist
- Schema count - 0, 1, 2+
- At least one model exists / does not exist
- At least one question exists / does not exist
- At least one dashboard exists / does not exist
- Popular items count - 0, 1, 2+
- Popular item types - tables, questions, models, dashboards
- Recent items count - 0, 1+
- Database "candidates" - exist / does not exist for the schema
- Illustration enabled / disabled
- Metabot enabled / disabled
- Custom dashboard set / not set

## Actions

- Open an X-ray dashboard
- Open a recent item
- Open a popular item
- Open documentation links
- Ask metabot prompts (here we only test whether the widget can be interacted with)

### Unit tests

`canUseMetabotOnDatabase`

matrix:
- supports nested queries - true / false
- has native write permissions - true / false
- engine type is sql - true / false

- [ ] = 2^3 = 8 cases (`it.each`)

### Integration tests

`HomeCaption`
- [ ] renders content

`HomeCardLink`
- [ ] renders a card with a link

`HomeHelpCard`
- [ ] renders a card with a docs link

`HomeModelCard`
- [ ] renders a card with a link to the item

`HomeGreeting`
- [ ] renders a message for users with the first name
- [ ] renders a message for users without the first name
- [ ] renders the metabot logo when the corresponding setting is enabled
- [ ] does not render the metabot logo when the setting is disabled

`HomePopularSection`
- [ ] renders tables / questions / models / dashboards  with correct titles, links, and icons
- [ ] renders a generic section title when there are more than 1 item
- [ ] renders a type-specific section title when there is one table / question / model / dashboard

`HomeRecentSection`
- [ ] renders tables / questions / models / dashboards  with correct titles, links, and icons
- [ ] renders a help link when the user is installer and the first login was within the last 2 weeks
- [ ] does not renders a help link when the user is not installer and the first login was within the last 2 weeks
- [ ] does not renders a help link when the user is installer but the first login was outside of the last 2 weeks
- [ ] does not renders a help link when the user is not installer and the first login was outside of the last 2 weeks

`HomeXrayCard`
- [ ] renders a card with a link

`HomeXraySection`

database selection:
- [ ] loads candidates for a user-defined database if it exists and the sync is completed
- [ ] loads candidates for the sample database if it exists and the sync is completed
- [ ] skips loading candidates if there are no databases where sync is completed
- [ ] skips loading candidates if there are no databases at all

no database:
- [ ] does not render if there is no proper database

sample database:
- [ ] renders x-ray dashboard links for the sample database with a special title and without the link to the database

user database:
- [ ] renders a link to the "browse database" page
- [ ] renders the links for a user database with a single schema
- [ ] renders the links for a user database with an empty schema (`""` and `null`)
- [ ] renders the links for a user database with multiple schemas
- [ ] allows switching between schemas when there are multiple ones
- [ ] renders an empty list if there are no candidates in a single-schema database
- [ ] allows switching between schemas with database candidates and without them

titles:
- [ ] renders the links for a database with more tables than we have unique card titles (currently 4)

`HomeContent`

popular section matrix:
- the user has one question and dashboard - true / false
- the user is installer - true / false
- the first login is within last week - true / false
- has popular items - true / false
- has recent items - true / false

- [ ] 2^5 = 32 cases for the popular section (`it.each`)

recent section matrix:
- the user has one question and dashboard - true / false
- has recent items - true / false
 
- [ ]  2^2 = 4 cases for the recent section

x-ray section matrix:
- has databases with completed sync - true / false
- x-rays enabled - true / false

- [ ]  2^2 = 4 cases for the x-ray section

`HomeLayout`
- [ ] renders the illustration when it is enabled
- [ ] does not render the illustration when it is not enabled
- [ ] renders the metabot widget when enabled
- [ ] does not render the metabot widget when not enabled
- [ ] allows to open and dismiss the custom homepage modal for admins
- [ ] does not allow to open a custom homepage model for non-admins

`CustomHomePageModal`
- [ ] allows to select a dashboard in the root collection
- [ ] allows to select a dashboard in a non-personal non-root collection
- [ ] does not allow to select a dashboard in a personal collection
- [ ] allows to cancel the model without submitting
- [ ] updates the setting and refreshes the session properties when changing the setting

`HomePage`

regular cases:
- [ ] open the sidebar when it's not a small screen
- [ ] does not open the sidebar when it's a small screen
- [ ] replaces the page with a custom dashboard if one exists
- [ ] renders the regular home page when a custom dashboard is not set

metabot matrix:
- has at least one model - yes / no
- has a supported database - yes / no
- has metabot enabled

- [ ] = 2^3 = 8 cases for the metabot widget vs the greeting message being rendered

### E2E tests

- [ ] allows to view x-ray dashboard for the sample database
- [ ] allows to view x-ray dashboard for the custom database
- [ ] allows to view popular items, with updates being reflected after navigating back to the homepage
- [ ] allows to view recent item, with updates being reflected after navigating back to the homepage
- [ ] allows to set and view a custom dashboard
- [ ] the sidebar gets opened when navigating to the homepage on a regular screen
- [ ] the sidebar does not get opened when navigating to the homepage on a small screen
