### ISSUE TITLE
[Epic] Add test coverage for Dashboard - Parameter Settings

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#31243]
Epic https://github.com/metabase/metabase/issues/30941

## Location
- `frontend/src/metabase/parameters`, starting from `ParameterSettings` component

## Dimensions
- parameter types
- connected fields

## Actions
- change name
- change source settings
- change default value
- toggle single/multi select
- set linked filters
- preview linked filters field mapping
- remove parameter

## Test cases

Parameter source settings to be tested separately as they're re-used across dashboards and the QB.

### Integration tests

`ParameterSidebar`
- [ ] renders the linked filters tab if the parameter supports them
- [ ] does not renders the linked filters tab if the parameter doesn't support them
- [ ] allows to switch between tabs
- [ ] allows to rename a parameter
- [ ] allows to change the default value
- [ ] allows to toggle single/multi selection
- [ ] allows to change the source settings
- [ ] allows to change the linked filters list
- [ ] allows to remove a parameter

`ParameterSettings`
- [ ] allows to change source settings when the parameter supports them
- [ ] does not allow to change source settings when the parameter doesn't support them
- [ ] allows to change single/multiple selection settings when the parameter supports them
- [ ] does not allow to change single/multiple selection settings when the parameter doesn't support them

`ParameterLinkedFilters`
- [ ] renders an empty state with a button to add a new parameter when there are no other parameters
- [ ] renders a list of parameters usable as a linked filter
- [ ] allows to toggle linked parameters
- [ ] allows to expand linked parameters
- [ ] renders an error if the current parameter is not connected to any field
- [ ] renders an error when some of the connected fields are inaccessible by the current user
- [ ] renders an error if the linked parameter is not connected to any field
- [ ] renders a mapping between parameters when each one is mapped to a single field
- [ ] renders a mapping between parameters when each one is mapped to multiple fields

### E2E tests

- [ ] changing parameter settings (name, single/multiple, default value) affects the dashboard
- [ ] removing parameter affects the dashboard
- [ ] setting linked filters properly limits the list of parameter value choices
