### ISSUE TITLE
[Safety Net] Improve the flow for adding a question to a dashboard

### ISSUE THREAD

**Issue by NevRA** [metabase/metabase#31290]
Epic: https://github.com/metabase/metabase/issues/29666

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/31797
``` 
- [ ] there doesn’t seem to be an e2e test; we should add them given that the new backend endpoint is used only here
- [ ] permissions edge cases are not e2e-covered, e.g. when you lose access to the most recent dashboard
