### ISSUE TITLE
[Epic] Add test coverage for Dashboard Click Behavior

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#31498]
Epic https://github.com/metabase/metabase/issues/30941
Estimate: 3 days

## Dimensions
- User permissions
- Dashcard visualization types
- Click behaviors (update filter value, open a URL, dashboard, question)
- Parameter mapping for click behavior ( to dashboards and questions )
- Is full app embedding

## Actions
- Set click behavior for a dashboard card
- Trigger click behavior on a dashboard card
  - Update a filter value
  - Open a url with interpolated click data
  - Open a question or a dashboard with mapped parameters

## Edge cases

- Target dashboard/question is not visible to a user
- If full app embedding, click behavior opens inner routes within the iframe
- Click behavior mapping uses invalid (e.g. removed) parameters

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/35034
- [ ] https://github.com/metabase/metabase/issues/35035
```

**Comment by kamilmielnik** [comment]
:warning: _this comment is WIP_ :warning: 

## Test cases

- [ ] Does not allow to set click behavior for virtual dashcards
  - [ ] Text
  - [ ] Heading
  - [ ] Action
  - [ ] Link
- [ ] Does not allow to set click behavior for visualizations with disabled click behavior
  - [ ] Object Detail
- [ ] Allows to set click behavior for Line Chart dashcard
  - [ ] "Open the Metabase drill-through menu"
  - [ ] "Go to a custom destination"
    - [ ] Dashboard
      - [ ] With passed values to dashboard filters
      - [ ] Does not show dashboards user has no permissions to
    - [ ] Saved question
      - [ ] With passed values to filter the question
      - [ ] Does not show questions user has no permissions to
    - [ ] URL
      - [ ] Simple URL
      - [ ] URL with referenced values
  - [ ] "Update a dashboard filter"
- [ ] Allows to set click behavior for Table dashcard
  - [ ] For a single column (cases just as setting click behavior for Line Chart dashcard)
  - [ ] For multiple columns (cases just as setting click behavior for Line Chart dashcard)
- [ ] Custom click behavior works
  - [ ] Line Chart (cases just as setting click behavior for Line Chart dashcard)
  - [ ] Table (cases just as setting click behavior for Line Chart dashcard)
