### ISSUE TITLE
Heading input and text dash-cards clipping after new grid sizing

### ISSUE THREAD

**Issue by JesseSDevaney** [metabase/metabase#31613]
### Describe the bug

Text dash-cards and the heading input field clip after the new dashboard grid sizing. Due to the resizing, rows are now smaller than before (at certain breakpoints) and this is causing the clipping.

**Text Fields**
![image](https://github.com/metabase/metabase/assets/22608765/0ae67ab1-e123-44b0-a98c-074e47bd41ac)

**Heading Input**
![image](https://github.com/metabase/metabase/assets/22608765/afb25c1a-e341-47c1-9f00-b7ae0080241c)

### To Reproduce

**Heading**
1. Go to any dashboard
2. Click on edit
3. Add a heading card
4. Focus the input on a heading card
5. See the heading input clipping on characters that dip down (`g`, `p`)

**Text**
1. Go to any dashboard
2. Click on edit
3. Add a text card
4. Resize to be one row in height
5. Add `# Heading` to the card
6. Save
7. See the text clipping
  - If you do not, slowly resize from largest to smallest to see the breakpoints at which text cards clip

### Expected behavior

No clipping should occur

### Fix Criteria

```[tasklist]
### Tasks
- [x] Fix heading input clipping [PR #31965](https://github.com/metabase/metabase/pull/31965)
- [x] Fix text cards clipping between small and large breakpoints  [PR #31965](https://github.com/metabase/metabase/pull/31965)
- [x] Backport Fixes [PR #32103](https://github.com/metabase/metabase/pull/32103)
```

### Information about your Metabase installation

```JSON
- Master
```

### Severity

P1: Broken common features, correctness
