### ISSUE TITLE
[Epic] Visualizations tech vision research and planning

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#32237]
In order to define a technical vision for our visualizations we need to perform research of potential options. The goals of are to understand if specific libraries comply with out functional and non-functional requirements, choose a library to use, and plan out our next steps for a refactor to this library.

**Links**
- [Eng doc hub](https://www.notion.so/metabase/Viz-library-research-4198b2726ac64f1d89ad1de6187532d2) 

```[tasklist]
### Choosing a candidate library
- [ ] https://github.com/metabase/metabase/issues/32844
- [ ] https://github.com/metabase/metabase/issues/32846
- [ ] https://github.com/metabase/metabase/issues/32847
- [ ] https://github.com/metabase/metabase/issues/32848
- [ ] https://github.com/metabase/metabase/issues/32849
```

```[tasklist]
### Evaluating ECharts
- [ ] https://github.com/metabase/metabase/issues/32851
- [ ] https://github.com/metabase/metabase/issues/32852
- [ ] https://github.com/metabase/metabase/issues/32853
- [ ] https://github.com/metabase/metabase/issues/32854
- [ ] https://github.com/metabase/metabase/issues/32856
- [ ] https://github.com/metabase/metabase/issues/32857
- [ ] https://github.com/metabase/metabase/issues/32858
- [ ] https://github.com/metabase/metabase/issues/32860
- [ ] https://github.com/metabase/metabase/issues/32861
- [ ] https://github.com/metabase/metabase/issues/32862
```

```[tasklist]
### Next Steps
- [ ] https://github.com/metabase/metabase/issues/32863
- [ ] https://github.com/metabase/metabase/issues/32864
- [ ] https://github.com/metabase/metabase/issues/32865
```
