### ISSUE TITLE
Menu component

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#32273]
Docs

- [Product doc](https://www.notion.so/metabase/Design-System-Menu-component-f8cffcd6aa374526bf6158d66b66c4f5?pvs=4)
- [Figma component](https://www.figma.com/file/MZhwfwmOaa8HeCBBUCeq7R/Menu?type=design&node-id=5-70&mode=design&t=4iBnf5NgLe2uH7PQ-11)

```[tasklist]
### Tasks
- [ ] Export the [Mantine](https://mantine.dev/core/menu/) `Menu` component from the `metabase/frontend/src/ui` according to the component’s category.
- [ ] Make sure the component style matches the component in Figma. You can add component specific styling to the `components:` section of `frontend/src/metabase/ui/theme.ts`
- [ ] Create a storybook file for the new component in the same directory. You can use `frontend/src/metabase/ui/components/inputs/Radio/Radio.stories.mdx` as an example.

```
