### ISSUE TITLE
Checkbox component

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#32270]
Docs

- [Product doc](https://www.notion.so/metabase/Design-System-Checkbox-component-8a916dfc82e64454981e51eba8978cef?pvs=4)
- [Figma component](https://www.figma.com/file/sF1qSHk6yVqO1rFgmH0nzT/Input-%2F-Checkbox?type=design&node-id=5-70&mode=design&t=TqHJM8JVRenem5Mk-11)

```[tasklist]
### Tasks
- [ ] Export the [Mantine](https://mantine.dev/core/checkbox/) `Checkbox` component from the `metabase/frontend/src/ui` according to the component’s category.
- [ ] Make sure the component style matches the component in Figma. You can add component specific styling to the `components:` section of `frontend/src/metabase/ui/theme.ts`
- [ ] Create a storybook file for the new component in the same directory. You can use `frontend/src/metabase/ui/components/inputs/Radio/Radio.stories.mdx` as an example.

```
