### ISSUE TITLE
[MLv2] Parameters

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#32293]
```[tasklist]
# Tasks
- [ ] Opaque parameters and helpers
- [ ] Migrate `FieldValuesWidget`
- [ ] Migrate `ParametersList` component
- [ ] Migrate native query template tag editor
- [ ] Migrate dashboard parameters
- [ ] Migrate public question, dashboard, etc.
- [ ] Migrate actions
- [ ] Migrate dashboard subscriptions
```
