### ISSUE TITLE
Button component

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#32308]
Docs

- [Product doc](https://www.notion.so/metabase/Design-System-Button-component-257718a5107e424599fa944dc455aacf?pvs=4)
- [Figma component](https://www.figma.com/file/Ey1rOyIxRHpmRvE9XrGyop/Button?type=design&node-id=418-2983&mode=design&t=p4TFOKysllG1a9PC-11)

```[tasklist]
### Tasks
- [ ] Export the [Mantine](https://mantine.dev/core/button/) `Button` component from the `metabase/frontend/src/ui` according to the component’s category.
- [ ] Make sure the component style matches the component in Figma. You can add component specific styling to the `components:` section of `frontend/src/metabase/ui/theme.ts`
- [ ] Create a storybook file for the new component in the same directory. You can use `frontend/src/metabase/ui/components/inputs/Radio/Radio.stories.mdx` as an example.

```

**Comment by ranquild** [comment]
Closed by https://github.com/metabase/metabase/pull/33175
