### ISSUE TITLE
Loader component

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#32309]
Docs

- [Product doc](https://www.notion.so/metabase/Design-system-Loader-component-1038a6a0661b471ea7710407b852faf2?pvs=4)
- [Figma component](https://www.figma.com/file/NUXRUa9Ot3HvgC1WwIA4UH/Loader?type=design&node-id=418-2983&mode=design&t=aPGdEhPIoQXkWpfC-11)

```[tasklist]
### Tasks
- [ ] Export the [Mantine](https://mantine.dev/core/button/) `Button` component from the `metabase/frontend/src/ui` according to the component’s category.
- [ ] Make sure the component style matches the component in Figma. You can add component specific styling to the `components:` section of `frontend/src/metabase/ui/theme.ts`
- [ ] Create a storybook file for the new component in the same directory. You can use `frontend/src/metabase/ui/components/inputs/Radio/Radio.stories.mdx` as an example.
- [ ] Add the following caveats to the Loader Story

```

Caveats
- Only use the “OVAL” variant unless otherwise called out
- Prefer usage of loader sizes less than XL unless specifically called out
