### ISSUE TITLE
[MLv2] Migrate app to MLv2 

### ISSUE THREAD

**Issue by kulyk** [metabase/metabase#32310]
`metabase-lib/metadata` contains a set of classes like `Database`, `Schema`, `Table`, `Field`, etc. Each of them is used independently and has its own set of methods. Also, all of them are used to build a single shared `Metadata` class instance.

I believe we shouldn't migrate MLv1 metadata to methods to MLv1 1:1. IMO, we should look into problems they're used for, and look for higher-level methods to address the same problems.

The tasklist groups bigger areas of Metabase working with MLv1 metadata. Crossing out every issue in the list wouldn't let us do `rm -rf metabase-lib/metadata`, but we should be about 99% there. The remaining bit is expected to be really tiny

```[tasklist]
# Tasks
- [ ] [MLv2] Migrate visualizations to MLv2
- [ ] [MLv2] Migrate QB data reference to MLv2
- [ ] [MLv2] Migrate metadata info components to MLv2
- [ ] [MLv2] Migrate model metadata editor to MLv2
- [ ] [MLv2] Migrate dashboards to MLv2
- [ ] [MLv2] Migrate Metabot to MLv2
- [ ] [MLv2] Migrate admin "Table Metadata" page to MLv2
- [ ] [MLv2] Migrate admin "Databases" page to MLv2
- [ ] [MLv2] Migrate admin "Data permissions" page to MLv2
- [ ] [MLv2] Migrate admin CSV uploads settings page to MLv2
- [ ] [MLv2] Migrate `DataSelector` and/or `DataPicker` to MLv2
- [ ] [MLv2] Migrate the Browse page to MLv2
- [ ] [MLv2] Migrate the model detail page to MLv2
- [ ] [MLv2] Migrate query builder to MLv2
- [ ] [MLv2] Update entity loaders for databases, schemas, tables, and fields
- [ ] [MLv2] Replace the `Metadata` object
```

**Comment by ranquild** [comment]
Moved to the main epic
