### ISSUE TITLE
[Epic] Allow basic deletes and updates on object detail views

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#32320]
### Links
- product doc: [_link to product doc_](https://www.notion.so/Allow-basic-deletes-and-updates-on-object-detail-views-f05b298c3aba4a6ca883b2738d86824d)
- integration branch: [`32320-object-detail-actions`](https://github.com/metabase/metabase/pull/new/32320-object-detail-actions)
- integration PRs:
  - Milestone 1: #32470

### What

There are two primary ways to fire an action on some given data right now: 1) Wire up a button on a dashboard (potentially with a filter to identify the data) 2) Run the action from Model Details and remember what data you want to act on. 

Both of these require you to remember what PK you want to act on / jump through unnecessary hoops to do a simple update / delete on a row of data. Let’s remove those requirements for cases where you simply want to act on an item.

Higher-level plan outlined in [Actions and Forms](https://www.notion.so/Actions-and-Forms-f78b84c111b3427aa32a6dfcd63b6562?pvs=21).

### Scope

When viewing the object detail for a record in a model that has basic actions enabled, the user will have a way to run basic edits / deletes.

![image](https://github.com/metabase/metabase/assets/6830683/beb6753e-0200-4c2b-8748-ed356cf87447)

```[tasklist]
### Milestone 1
- [ ] https://github.com/metabase/metabase/issues/32321
- [ ] https://github.com/metabase/metabase/issues/32322
- [ ] https://github.com/metabase/metabase/issues/32323
- [ ] https://github.com/metabase/metabase/issues/32350
- [ ] https://github.com/metabase/metabase/issues/32435
- [ ] https://github.com/metabase/metabase/issues/32668
- [ ] https://github.com/metabase/metabase/issues/32783
```

```[tasklist]
### Milestone 2
- [ ] https://github.com/metabase/metabase/issues/32667
- [ ] https://github.com/metabase/metabase/issues/33084
- [ ] https://github.com/metabase/metabase/issues/32974
- [ ] https://github.com/metabase/metabase/issues/32694
- [ ] https://github.com/metabase/metabase/issues/33238
```

**Comment by qnkhuat** [comment]
Should be included in 48
