### ISSUE TITLE
Enable parameter substitution to Heading text cards

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#32341]
**Problem** 
Parameter substitution is not enabled for heading cards.
- [Slack context](https://metaboat.slack.com/archives/C01LQQ2UW03/p1689179487577479)

**Desired Behavior**
Enable parameter substitution for heading cards and have it behave similarly to parameter substitution on normal text cards.

**BE Work**

![image](https://github.com/metabase/metabase/assets/22608765/cd136fbf-4e4c-4310-b156-118de20a54f2)
- [x] Cljs function `substitute_tags` has been updated with option to prevent escaping markdown related characters - to be used for headings
- [x] Update parameter substitution for heading cards (on dashboard subscriptions) to use this new functionality

```[tasklist]
### Tasks
- [x] (FE) Implement parameter mapping for heading cards and add tests (https://github.com/metabase/metabase/pull/32462)
- [x] (BE) Add optional parameter to avoid escaping characters for heading cards and update this to be used in dashboard subscriptions for heading cards (https://github.com/metabase/metabase/pull/32462)
- [x] Merge backport PR
```

**Comment by JesseSDevaney** [comment]
Need to merge backport before this is officially closed
