### ISSUE TITLE
[WIP] Testing Plan for Search Filters

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#32386]
## Description
For Epic [#27982](https://github.com/metabase/metabase/issues/27982)
## Location
- `frontend/src/metabase/search`
## Dimensions
- Search result count
	- No results
	- More than 1
	- More than 10 (i.e. pagination)
- Number of available assets to search
	- 0 (i.e. no databases / data at all)
	- 1+
- Showing filters based on admin/non-admin, Pro/EE vs Starter/OSS
	- Verified questions - only on Pro/EE
- Number of users (for `Created by` / `Edited by`)
	- 1 user (should we show these filters otherwise?)
	- 2+ users
- Filters
	- Entity type
	- Date filters
		- Today
		- 30 days ago
		- etc
	- Verified / unverified
	- Created by
	- Edited by
##### Global Search Bar
- Open search bar
	- With `/`
	- By clicking on the search bar
- Open a recent search
- Type a query into the search bar
- Adding a filter to the search
- Clicking on a search result
- Hovering over a search result
- Opening all results (redirect to full page search)
	- with `Enter`
	- clicking on `View all {num} results`
##### Full Page Search
- Clicking entity filters (i.e. Dashboards, collections, etc)
- Clicking through the paginated search results, if there are more than 10
- (Maybe an action if the user gets zero results)
##### Filter Modal
- Applying filters:
	- `type`
	- `created by`
	- `edited by`
	- `edited on`
	- `verified`
- clearing all filters
### Unit Tests
	- TBD
#### Search Item
- [x] should render name, icon, `Edited by` / `Created by` + time, and description (if available)
#### Search Bar
- Tooltips
	- [ ] Shows tooltip when hovering over search bar
	- [ ] Shows explanatory tooltip when hovering over the ‘/’ badge
- Typing a search query
	- [x] ~~Renders filter button only when search bar contains a query~~ _Removed after UI/UX discussion_
	- [x] ~~Renders search results when user types a query with results (maybe with >2 characters)~~ _Unneeded since we only trigger searches on `Enter`_
	- [x] ~~Debounces search calls when user types a query~~ _Unneeded since we only trigger searches on `Enter`_
	- [x] Renders 'no results found' when user types a query with no results
	- [x] Shows `view all results` when user types a query with results
	- [x] Should display `{num} results` with search query
- On clicking/focusing on search bar
	- [x] Displays recent search results of the search bar is clear
- Keyboard navigation
	- [x] Focuses on filter button when user tabs from search bar
	- [x] Allows navigation through search results with the `tab` button
- Highlighting
	- [x] Should highlight hovered/focused search item
	- [x] Should highlight filter button when filters are applied
#### Filter Modal
- Keyboard navigation
	- [x] Allow keyboard navigation through all filters
	- [x] Should only display types based on available entities
- Filter display
	- [x] Should display a list of users when clicking on `Created by` or `Edited by`
- Apply All Filters
	- [x] Should return all selected filters when `Apply all filters` is clicked
- Clear All Filters
	- [x] Should clear all selections when `Clear all filters` is clicked
####  Filters
- `Date Filter`
	- [ ] Date filter should show a list of date presets
	- [ ] Date filter should display date picker when clicking `Custom...`
- `Verified`
	- [x] Should only display verified on Pro/EE instances
- `Created by` / `Edited By`
	- [x] Should display a list of users when typing a name
####  Search Bar
- [x] should display an asset in `recent searches` after accessing it through a search
- [ ] Clicking `View All Results` should display the same search results in the full page search
- [ ] Search dropdown should be displayed in front of all other elements on screen
####  Filter Modal
- [x] should reload search with each applied filter after clicking `Apply All Filters`
	- Type
	- Created By (with date filter)
	- Edited By (with date filter)
	- Verified
- [x] should reload search with no filters applied after clicking `Clear All Filters`
####  Full Page Search
- [x] Sidebar should only display available types from search results
- [x] Accessing a search URL should display results based on query string and filters
