### ISSUE TITLE
Title component

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#32441]
Docs

- [Product doc](https://www.notion.so/metabase/Design-System-Title-component-b398e77cbeb649d89685916d9e97b85c?pvs=4)
- [Figma component](https://www.figma.com/file/SEQS7bshKQ4y4V5FwvdROv/Foundation-%2F-Title?type=design&node-id=5-70&mode=design&t=4qMAYMgbVbBQGMOB-11)

```[tasklist]
### Tasks
- [ ] Export the [Mantine](https://mantine.dev/core/title/) `Title` component from the `metabase/frontend/src/ui` according to the component’s category.
- [ ] Make sure the component style matches the component in Figma. You can add component specific styling to the `components:` section of `frontend/src/metabase/ui/theme.ts`
- [ ] Create a storybook file for the new component in the same directory. You can use `frontend/src/metabase/ui/components/inputs/Radio/Radio.stories.mdx` as an example.
- [ ] Find one small place to use the new component so we can ensure it works as intended.

```

**Comment by shivam5017** [comment]
Please provide access to figma and docs
