### ISSUE TITLE
[Epic] Know whether a table is writeable for actions

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#32978]
[Product doc](https://www.notion.so/metabase/Find-a-way-to-know-whether-a-DB-has-a-writeable-connection-or-not-090dd8a6bf244fc8bbaa042579a40228)

## Implementation Plan

```[tasklist]
### Milestone 1: Implement for Postgres
- [ ] https://github.com/metabase/metabase/pull/33415
```

```[tasklist]
### Milestone 2: Implement for MySQL
- [ ] https://github.com/metabase/metabase/pull/33598
```

```[tasklist]
### Milestone 3: Create driver feature
- [ ] https://github.com/metabase/metabase/pull/34128#top
```

## Not in scope

- We only store privileges for the DB connection's user. If connection impersonation is enabled for the database, we won't be able to return privileges for the given user. Metabase users using connection impersonation will get runtime errors if they try to run actions on the database.
- Column-level privileges are not considered. Only privileges down to table-level are.

## Testing plan

- Per driver, test a function that returns the set of privileges that a given user_role has from the database.
  - should work for current user
  - should work for a specific role
- Per driver, test that the data is returned by the set of privileges for a given role
  - should work for all privilege types: select/update/insert/delete
  - should work for current user
  - should work for a specific role

**Comment by calherries** [comment]
@cdeweyx can you check the epic milestones look okay to you?

**Comment by cdeweyx** [comment]
> @cdeweyx can you check the epic milestones look okay to you? Note I changed the title of the epic, because as we discussed on the call the solution will allow us to know whether a specific table is writable, not the DB.

Looks good to me, thanks for the heads up 👍
