### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by kdoh** [metabase/metabase#33278]
Docs
- [Figma component](https://www.figma.com/file/21uCY0czmCfb6QBjRce0I8/Input-%2F-Select?type=design&node-id=1-96&mode=design&t=57I559Y0U8w4QnNr-11)

```[tasklist]
### Tasks
- [ ] Export the [Mantine](https://mantine.dev/core/button/) `Select` component from the `metabase/frontend/src/ui` according to the component’s category.
- [ ] Make sure the component style matches the component in Figma. You can add component specific styling to the `components:` section of `frontend/src/metabase/ui/theme.ts`
- [ ] Create a storybook file for the new component in the same directory. You can use `frontend/src/metabase/ui/components/inputs/Radio/Radio.stories.mdx` as an example.

```

Let @vbenedetti know if you have any questions.
