### ISSUE TITLE
[Epic] Migrate Pie Chart to ECharts

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#33281]
**Links**
[Hub page: Viz revamp research and planning](https://www.notion.so/metabase/Viz-Revamp-Research-and-Planning-4198b2726ac64f1d89ad1de6187532d2#3e3dda5bce58473397e67bb44a741a65)
[Product doc: Implement the Pie chart using ECharts](https://www.notion.so/metabase/Implement-the-Pie-chart-using-ECharts-7e18ef8eac32425bada8a3ecd360158d)

## Static Chart
- [x] #43556
- [x] https://github.com/metabase/metabase/issues/43564

#### Formatting
- [x] https://github.com/metabase/metabase/issues/43762
- [x] https://github.com/metabase/metabase/issues/43773
- [x] https://github.com/metabase/metabase/issues/43774
- [x] https://github.com/metabase/metabase/issues/44086

#### Negative Metric Values
- [x] https://github.com/metabase/metabase/issues/43769
- [x] https://github.com/metabase/metabase/issues/43770

#### Other
- [x] https://github.com/metabase/metabase/issues/43764
- [x] https://github.com/metabase/metabase/issues/43766
- [x] https://github.com/metabase/metabase/issues/43557
- [x] https://github.com/metabase/metabase/issues/43797
- [x] https://github.com/metabase/metabase/issues/44019
- [x] https://github.com/metabase/metabase/issues/44085
- [x] https://github.com/metabase/metabase/issues/44087
- [x] https://github.com/metabase/metabase/issues/44847
- [x] https://github.com/metabase/metabase/issues/45149

## Dynamic Chart
- [x] https://github.com/metabase/metabase/issues/43961
- [x] https://github.com/metabase/metabase/issues/43558
- [x] https://github.com/metabase/metabase/issues/43559
- [x] https://github.com/metabase/metabase/issues/43974
- [x] https://github.com/metabase/metabase/issues/43560
- [x] https://github.com/metabase/metabase/issues/43561
- [x] https://github.com/metabase/metabase/issues/43562
- [x] https://github.com/metabase/metabase/issues/43565
- [x] https://github.com/metabase/metabase/issues/45687

### Dynamic Regressions
- [x] https://github.com/metabase/metabase/issues/43768
- [x] https://github.com/metabase/metabase/issues/44988
- [x] https://github.com/metabase/metabase/issues/45686

## Existing Bugs

[Issue query](https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen++sort%3Acreated-desc+label%3AType%3ABug+label%3A.Team%2FDashViz+pie)

### Fixed
- [x] https://github.com/metabase/metabase/issues/36096
- [x] https://github.com/metabase/metabase/issues/33503
- [x] https://github.com/metabase/metabase/issues/33063
- [x] https://github.com/metabase/metabase/issues/27547
- [x] https://github.com/metabase/metabase/issues/38424

#### Requires product input / new feature
- [ ] https://github.com/metabase/metabase/issues/30996
- [ ] https://github.com/metabase/metabase/issues/29597
- [ ] https://github.com/metabase/metabase/issues/33113

#### Not pie specific
- [ ] https://github.com/metabase/metabase/issues/28568
_pie chart is fixed, funnel is not_
- [ ] https://github.com/metabase/metabase/issues/22620
- [ ] https://github.com/metabase/metabase/issues/10127
- [ ] https://github.com/metabase/metabase/issues/6701

#### Not pie related
- [ ] https://github.com/metabase/metabase/issues/3198
- [ ] https://github.com/metabase/metabase/issues/14760
