### ISSUE TITLE
Optimize CI workflows

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#33326]
Full scope TBD

```[tasklist]
### E2E
- [ ] #33190
- [ ] Run only the changed spec
```

```[tasklist]
### Frontend
- [ ] https://github.com/metabase/metabase/pull/33269
```

```[tasklist]
### Backend
- [ ] https://github.com/metabase/metabase/pull/33270
```

```[tasklist]
### Drivers
```

**Comment by nemanjaglumac** [comment]
@iethree took over and is the driving force behind all CI improvements. This can be closed.
