### ISSUE TITLE
Bugs to solve after MBQL manipulation refactor

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#33413]
```[tasklist]
### Bugs
- [ ] https://github.com/metabase/metabase/issues/33335
- [ ] https://github.com/metabase/metabase/issues/27795
- [ ] https://github.com/metabase/metabase/issues/21502
- [ ] https://github.com/metabase/metabase/issues/19744
- [ ] https://github.com/metabase/metabase/issues/24703
- [ ] https://github.com/metabase/metabase/issues/5307
- [ ] https://github.com/metabase/metabase/issues/31384
- [ ] https://github.com/metabase/metabase/issues/28609
- [ ] https://github.com/metabase/metabase/issues/27735
- [ ] https://github.com/metabase/metabase/issues/33330
- [ ] https://github.com/metabase/metabase/issues/33336
- [ ] https://github.com/metabase/metabase/issues/28438
```

**Comment by darksciencebase** [comment]
closing in favor of https://github.com/orgs/metabase/projects/67/views/1
