### ISSUE TITLE
[Epic] Trend chart improvements

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#33411]
## Problem
Trend charts currently have several limitations on their usefulness
- They can only compare to the immediate previous period - previous day, month, quarter, etc. 
  - Trend charts do not skip over gaps in the data: if the immediate previous period is missing or contains a null-value, no comparison is displayed
- They can only display one comparison at a time
  - No option for a static comparison - e.g. to measure your trend against a target/goal
  - No option for arbitrary date comparison - i.e. # of periods ago instead of immediate previous period
  - No option for comparison with another column 
- There is no option to compact a long number

---
## Desired Behavior/Acceptance Criteria

**Milestone 1:** Update Trend Chart Copy
- [x] https://github.com/metabase/metabase/pull/35184

**Milestone 2:** Support arbitrary date comparison (FE 2)

- [x] #35551
  - Value: Instead of limiting users to selecting only the previous period, there will now be an option to select an arbitrary number of previous periods ago to compare against. So instead of comparing to last month, now we can compare to 3 months ago or 6 months ago.

- [x] #37026

**Milestone 3:** Support a static number comparison (FE 1)

- [x] #35552
  - Value: Users will now be able to select static numbers to compare the current value against. This opens up the ability to create targets/goals to strive for and measure against.

**Milestone 4:** Support comparison with another column (FE 0.5)

- [x] #35553
  - Value: Comparing a current metric to its previous value can be helpful, but so can comparing one metric to an entirely different metric. This addition will open the possibility of comparing your metric to other metrics (within the same table).

**Milestone 5:** Support value formatting (FE 0.5)

- [x] #35554
  - Value: Display long numbers sometimes provide irrelevant information. Sometimes I just want to see how many thousands or millions a value is, and I do not really care about the values in the hundreds. Well now you can choose to compact your values to show only the most important digits you care about.

**Milestone 6:** Enable multiple comparisons (FE 2)

- [x] #35555
  - Value: Often comparing a value against multiple numbers provides more context and actionable information than against only a single number. This addition will allow for multiple (up to 3) comparisons.

**Milestone X:** 

- [ ] Update search widget: "select” to match the designs of the new comparison select component
- [ ] Convert Trend Charts JavaScript files to TypeScript
- [x] Add Trend Charts variants to Storybook (and to prepare for future visual testing)

**Milestone 7:** Add new functionality to the static viz (FE 2, BE 2)

- [x] #35556
  - Value: All the updates to dashboards will be propagated to subscriptions/alerts. Users can now enjoy the same changes to the dashboard but in their email

---
## Additional Context
**Docs**
- [Product Doc](https://www.notion.so/metabase/Let-users-do-multiple-comparisons-to-Trend-charts-4d71dce69f8d4fb0835beb6ae064742e?d=01763b97f4de417d9dcad4f3cef2422c#d4aaa3e33fc94a3eb383a6d4ae02ed83)
- [Technical Doc](https://www.notion.so/metabase/Trend-chart-improvements-Technical-Plan-5a78c47fb2f940d393854126f62bf1a0)
- Feature Branch: `feature/trend-chart-improvements`

**Issues**
- https://github.com/metabase/metabase/issues/31951
- https://github.com/metabase/metabase/issues/25670
- https://github.com/metabase/metabase/issues/23385
- https://github.com/metabase/metabase/issues/13284
- https://github.com/metabase/metabase/issues/8919
- https://github.com/metabase/metabase/issues/11200
- https://github.com/metabase/metabase/issues/10021
- https://github.com/metabase/metabase/issues/9510
- https://github.com/metabase/metabase/issues/25594
