### ISSUE TITLE
[Epic] CI Improvements

### ISSUE THREAD

**Issue by perivamsi** [metabase/metabase#33615]
**Links**
- [product doc](https://www.notion.so/metabase/CI-Improvements-f72c828157774fc3b906e7b57d1d67c1)
- feature branch: `ci-improvements`
- [issue links](https://github.com/metabase/metabase/labels/.CI%20%26%20Tests) (need to review)

**Implementation Plan**

***Milestone 1***

```[tasklist]
### Tasks
- [ ] Change PRs to draft mode with every new push, this will reduce the number of times CI runs in PRs
- [ ] Introduce thread-safe version of with-temporary-setting-values
- [ ] Run frontend and backend jobs on BuildJet
- [ ] Run backend jobs only when backend changes or staticviz changes
- [ ] Run drivers jobs on when the relevant files change
- [ ] Run (most) REST API tests using mock request handler on same thread
```

***Milestone 2***

```[tasklist]
### Tasks
- [ ] Split Cypress folders further and run them using more parallel runners
- [ ] Run driver tests in parallel, identify which driver tests need to run sequentially
- [ ] Work with trunk.io and Aviator to add granular measurements for speed and test flakiness
- [ ] Run different workflows on different runners - BuildJet, GH and AWS
```

***Milestone 3***

```[tasklist]
### Tasks
- [ ] Replace Webpack with faster options such as Rspack or SWC.
- [ ] Tag flaky tests during CI runs and prioritize fixing them.
```
