### ISSUE TITLE
[Epic] Prevent users from losing their changes via “Back” and in-app navigation

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#33749]
### Links
- [Product doc](https://www.notion.so/metabase/Prevent-users-from-losing-their-changes-via-Back-and-in-app-navigation-01c80936e86e4196a2750e8a81b8321a)
- Feature branch: none, PRs can go straight to `master`
- Issue links:
  - #32037
  - #12389
  - #10427
- Previous epic: #29421
  - [Product doc](https://www.notion.so/metabase/Warn-users-before-they-lose-new-changes-1641d98e1e1f4a99bda7f46d0b871ec6)

### Testing Plan

All PRs should come with tests relevant for that particular place.
- example how to test `onbeforeunload`: [SegmentForm.unit.spec.tsx](https://github.com/metabase/metabase/blob/1f7e261ec4702b36aa1f815440396187c4b7e931/frontend/src/metabase/admin/datamodel/components/SegmentForm/SegmentForm.unit.spec.tsx)
- example how to test custom modal: ~[admin-permissions.cy.spec.js](https://github.com/metabase/metabase/blob/9d3ea413b038b5c91fd568db7d9815a8710295b3/e2e/test/scenarios/permissions/admin-permissions.cy.spec.js#L285)~ [DashboardApp.unit.spec.tsx](https://github.com/metabase/metabase/pull/33827/files#diff-880d0af04084ea5fcd6c71a2f1eaff3803cad206c44e64170a988b4122fead31R176-R199)

For modals (e.g. creating/editing an action) we should also test that the warning [is shown](https://www.notion.so/Prevent-users-from-losing-their-changes-via-Back-and-in-app-navigation-01c80936e86e4196a2750e8a81b8321a?d=c7810fde368547cab37f969a4d3ba02a&pvs=4#e57fc38f54f845c686500e78e4559970) when clicking the "Cancel" button.
If the modal can be closed in other ways (Esc key / "x" button / backdrop click), tests should account for that as well - this will apply to e.g.`ActionExecuteModal`.

### Implementation Plan

**All tasks in milestone 1 can be merged to `master` independently, in any order.**

```[tasklist]
### Milestone 1
- [ ] https://github.com/metabase/metabase/issues/33788
- [ ] https://github.com/metabase/metabase/issues/33783
- [ ] https://github.com/metabase/metabase/issues/33800
```

----

**All tasks in milestone 2 can be merged to `master` independently, in any order.**

```[tasklist]
### Milestone 2
- [ ] https://github.com/metabase/metabase/issues/33790
- [ ] https://github.com/metabase/metabase/issues/33791
- [ ] https://github.com/metabase/metabase/issues/34081
- [ ] https://github.com/metabase/metabase/issues/33792
- [ ] https://github.com/metabase/metabase/issues/33794
- [ ] https://github.com/metabase/metabase/issues/33793
- [ ] https://github.com/metabase/metabase/issues/33795
- [ ] https://github.com/metabase/metabase/issues/34074
```

----

**All tasks in milestone 3 can be merged to `master` independently, in any order.**

```[tasklist]
### Milestone 3
- [ ] https://github.com/metabase/metabase/issues/34422
- [ ] https://github.com/metabase/metabase/issues/34433
- [ ] https://github.com/metabase/metabase/issues/34490
- [ ] https://github.com/metabase/metabase/issues/34366
- [ ] https://github.com/metabase/metabase/issues/34430
- [ ] https://github.com/metabase/metabase/issues/34429
- [ ] https://github.com/metabase/metabase/issues/34428
```

```[tasklist]
### Milestone 4 (beyond release 48)
- [ ] https://github.com/metabase/metabase/issues/33832
- [ ] https://github.com/metabase/metabase/issues/16455
```

```[tasklist]
### Milestone 5 (beyond release 48)
- [ ] https://github.com/metabase/metabase/issues/34114
- [ ] https://github.com/metabase/metabase/issues/34119
- [ ] https://github.com/metabase/metabase/issues/34125
- [ ] https://github.com/metabase/metabase/issues/34126
- [ ] https://github.com/metabase/metabase/issues/34127
- [ ] https://github.com/metabase/metabase/issues/34686
```
