### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#33993]
Docs
- [Figma component](https://www.figma.com/file/xdNKMROC99J6Z4Sqg6V3JI/Input-%2F-Switch?type=design&node-id=1-96&mode=design&t=xWt81fdQtdXSTQ2j-0)

```[tasklist]
### Tasks
- [x] Export the [Mantine](https://v6.mantine.dev/core/switch/) `Switch` component from the `metabase/frontend/src/ui` according to the component’s category.
- [ ] Make sure the component style matches the component in Figma. You can add component specific styling to the `components:` section of `frontend/src/metabase/ui/theme.ts`
- [ ] Create a storybook file for the new component in the same directory. You can use `frontend/src/metabase/ui/components/inputs/Radio/Radio.stories.mdx` as an example.
```
