### ISSUE TITLE
[MLv2] Filters

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#34112]
Epic https://github.com/metabase/metabase/issues/28689
Design doc https://www.notion.so/metabase/Filters-API-e411d9d4f267454ba970a76b3f9ecd08?pvs=4#b778d2dcddb14ac6b5082eaca5f69642

### Prior work

```[tasklist]
### Tasks
- [x] #28692
- [x] https://github.com/metabase/metabase/issues/29867
- [x] #28703
- [x] https://github.com/metabase/metabase/issues/31676
- [x] https://github.com/metabase/metabase/issues/31677
- [x] https://github.com/metabase/metabase/issues/32058
- [x] https://github.com/metabase/metabase/issues/32060
- [x] https://github.com/metabase/metabase/issues/32159
- [ ] https://github.com/metabase/metabase/issues/32160
- [ ] https://github.com/metabase/metabase/issues/32409
- [ ] https://github.com/metabase/metabase/issues/33022
- [ ] https://github.com/metabase/metabase/issues/33023
```

### Milestone 1 - FilterPopover and notebook editor

Create MLv2-based `FilterPopover` and use it in the notebook editor.

Integration branch [34112-filters-milestone1](https://github.com/metabase/metabase/pull/34191)

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/34144
- [ ] https://github.com/metabase/metabase/issues/34190
- [ ] https://github.com/metabase/metabase/issues/34130
- [ ] https://github.com/metabase/metabase/issues/34269
- [ ] https://github.com/metabase/metabase/issues/34131
- [ ] https://github.com/metabase/metabase/issues/34134
- [ ] https://github.com/metabase/metabase/issues/34135
- [ ] https://github.com/metabase/metabase/issues/34245
- [ ] https://github.com/metabase/metabase/issues/34224
- [ ] https://github.com/metabase/metabase/issues/34274
- [ ] https://github.com/metabase/metabase/issues/34275
- [ ] https://github.com/metabase/metabase/issues/34378
- [ ] https://github.com/metabase/metabase/issues/34379
- [ ] https://github.com/metabase/metabase/issues/34511
- [ ] https://github.com/metabase/metabase/issues/34495
- [ ] https://github.com/metabase/metabase/issues/34496
- [ ] https://github.com/metabase/metabase/issues/34669
- [ ] https://github.com/metabase/metabase/issues/34332
- [ ] https://github.com/metabase/metabase/issues/34453
- [ ] https://github.com/metabase/metabase/issues/34667
- [ ] https://github.com/metabase/metabase/issues/34671
- [ ] https://github.com/metabase/metabase/issues/34691
- [ ] https://github.com/metabase/metabase/issues/34707
- [ ] https://github.com/metabase/metabase/issues/34736
- [ ] https://github.com/metabase/metabase/issues/34738
- [ ] https://github.com/metabase/metabase/issues/34737
- [ ] https://github.com/metabase/metabase/issues/35088
- [ ] https://github.com/metabase/metabase/issues/35159
- [ ] https://github.com/metabase/metabase/issues/35160
- [ ] https://github.com/metabase/metabase/issues/35161
- [ ] https://github.com/metabase/metabase/issues/35162
- [ ] https://github.com/metabase/metabase/issues/35163
- [ ] https://github.com/metabase/metabase/issues/35089
- [ ] https://github.com/metabase/metabase/issues/34959
- [ ] https://github.com/metabase/metabase/issues/34960
- [ ] https://github.com/metabase/metabase/issues/34965
- [ ] https://github.com/metabase/metabase/issues/34968
- [ ] https://github.com/metabase/metabase/issues/34973
- [ ] https://github.com/metabase/metabase/issues/35112
- [ ] https://github.com/metabase/metabase/issues/35312
- [ ] https://github.com/metabase/metabase/issues/34972
- [ ] https://github.com/metabase/metabase/issues/35257
- [ ] https://github.com/metabase/metabase/issues/34971
- [ ] https://github.com/metabase/metabase/issues/35153
- [ ] https://github.com/metabase/metabase/issues/35374
- [ ] https://github.com/metabase/metabase/issues/35377
- [ ] https://github.com/metabase/metabase/issues/35447
```

### Milestone 2 - simple mode

Use MLv2-based `FilterPopover` instead of the old one. Use MLv2 in the time series widget.

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/34962
- [ ] https://github.com/metabase/metabase/issues/35369
- [ ] https://github.com/metabase/metabase/issues/35675
- [ ] https://github.com/metabase/metabase/issues/35752
```

### Milestone 3 - filter modal

Use MLv2-based `FilterPopover`. Use MLv2 for the remaining parts.

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/36698
- [ ] https://github.com/metabase/metabase/issues/35746
- [ ] https://github.com/metabase/metabase/issues/35882
- [ ] https://github.com/metabase/metabase/issues/36033
- [ ] https://github.com/metabase/metabase/issues/36034
- [ ] https://github.com/metabase/metabase/issues/36035
- [ ] https://github.com/metabase/metabase/issues/36036
- [ ] https://github.com/metabase/metabase/issues/36037
- [ ] https://github.com/metabase/metabase/issues/36052
- [ ] https://github.com/metabase/metabase/issues/36060
- [ ] https://github.com/metabase/metabase/issues/36059
- [ ] https://github.com/metabase/metabase/issues/36061
- [ ] https://github.com/metabase/metabase/issues/36057
- [ ] https://github.com/metabase/metabase/issues/36038
- [ ] https://github.com/metabase/metabase/issues/36542
- [ ] https://github.com/metabase/metabase/issues/36058
- [ ] https://github.com/metabase/metabase/issues/36947
- [ ] https://github.com/metabase/metabase/issues/36948
- [ ] https://github.com/metabase/metabase/issues/37100
- [ ] https://github.com/metabase/metabase/issues/37175
- [ ] https://github.com/metabase/metabase/issues/37219
- [ ] https://github.com/metabase/metabase/issues/36988
- [ ] https://github.com/metabase/metabase/issues/37347
- [ ] https://github.com/metabase/metabase/issues/37369
- [ ] https://github.com/metabase/metabase/issues/37463
```

### Milestone 4 - parameter to query filter mapping in dashboards

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/37107
```

### Dimensions

Column source:
- Data source - table, structured question, native question, with selected columns or not
- Join - different data source (recur), self join, with selected columns or not
- Aggregation - without column, with column (recur), aggregation operator (whether the column type preserves the argument  type)
- Breakout - column source (recur), bucketing, binning
- Expression - column source (recur)
- Stage index - 0, 1, 2

Column semantic type
- category, ...

Filter type:
- string - operator, args count
- number - operator, args count, fractional numbers
- coordinate - operator, args count, "inside", fractional numbers
- boolean - operator
- specific date - operator, with or without time, date format
- relative date - past/current/next, (bucketing) unit, has current, has offset, offset (bucketing) unit
- exclude date - operator, (extraction) unit
- time - operator

Date & time formats
- Any ISO date format, with or without timezone
- Any ISO time format

### FE

Parameterized and exhaustive test suite: 
- Unit tests for filter wrappers 
- Integration tests for filter components

### BE

- `filters`
- `displayInfo`
- `filterableColumns`, `filterableColumnOperators`
- `filter`, `expressionClause`, `expressionParts`

### E2E

- E2E tests for different filter types and filter column sources
