### ISSUE TITLE
[EPIC] 48 technical debts

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#34360]
```[tasklist]
### Tasks
- [ ] API tests parallelization
- [ ] https://github.com/metabase/metabase/issues/26940
- [ ] Split liquibase migration
```

**Comment by darksciencebase** [comment]
closing in favor of triaging tech debt in the BE Tech Debt board and picking it up like any other task
