### ISSUE TITLE
[Testing Plan] Let people move cards between dashboard tabs

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#34368]
## Description
For Epic #34367

## Location
TBD

## Dimensions
* Dashboard Tab Menu
	* Only one tab (i.e. no other tabs available)
	* Multiple tabs
	* Showing the last selected tab as the default option
* Moving dashcards
	* Keeping the same dashcard query when the card is moved
	* Keeping the same dashcard size when the card is moved
* Permissions
	* User can only see dashboard tabs that they have permissions for
	* Users should only be allowed to move cards if they have permissions

## Actions
* Selecting the last selected tab to move the dashcard to
* Selecting a different tab in the tab menu to move the dashcard to
* Moving the dashcard to a different tab
* Adding a link to an existing dashcard tab
* Passing a filter value based on the selected tab in Click Behavior sidebar

#### Tab Selector Menu
* Users should see all tabs that are available in the dashboard
* Should show the `last_suggested_tab` based on a prop
* Should only show tab list when the `open` arrow is clicked
* All tabs (except the current one) should be seen
* Should trigger `onTabSelect` function when a user clicks on a dashboard tab in the menu, or if the currently shown tab is clicked

#### Dashcard Toolbar
* Only show the tab selector if there's more than one tab available
* Should trigger `dashcard move` function when a tab is selected

#### Click Behavior Sidebar
* Tab Selector
	* Users should only be able to see dashboards and tabs that they have permissions to see
	* Should trigger an 'onTabSelect' when a different tab is selected in the menu (to trigger the filter change)
* Filters
	* Dashboard filters should change when the tab selection is changed

#### Tab Selector Menu
* The tab selector menu should display new tabs after a tab has been added/removed from the dashboard
* Should display the last selected tab when the user is navigating through the dashboard
* Should move the dashcard when a tab is selected

#### Moving a Dashcard
* Cards should keep the same query + information when moved
* Cards should keep the same size when moved
* Should not show the dashcard movement selector if they only have readonly access

#### Click Behavior Sidebar
* User should be able to link to a dashboard tab
* The user should see dashboards and tabs that they have access to
* User should see and be able to select filters that are associated with a dashboard tab
* Should show filters for the currently-selected tab

**Comment by npretto** [comment]
This is my suggested testing plan for the first milestone after the changes to the feature/milestones:

## milestone 1 (move card behaviour)

### dimensions:
- permissions (it should already be handled by not being able to go to edit mode)
- how many tabs (1, 2, 3+)
- tab name size

### actions

- hover on move icon
- click on tab in menu


### test cases
- [ ] if no permission, don't show the move icon (it should already be handled by not being able to go to edit mode)
- [ ] if there's only one tab, don't show the move icon
- [ ] if >=2 tabs, show the move icon/menu
- [ ] when hovering the move icon, it should list all tabs but the current one
- [ ] when selecting a tab from the menu
  - [ ] it should move the card to the correct tab
  - [ ] it should keep the same dashcard query when the card is moved
  - [ ] it should keep the same dashcard size when the card is moved

**Comment by kamilmielnik** [comment]
I extracted #34780 from here, as #34779 was extracted from #34367.

**Comment by dragonsahead** [comment]
@kamilmielnik @npretto is this still relevant?

**Comment by npretto** [comment]
Closed, thanks
