### ISSUE TITLE
[Epic] Let people move cards between dashboard tabs

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#34367]
**Links**
- [Let people move cards between dashboard tabs](https://www.notion.so/metabase/Let-people-move-cards-between-dashboard-tabs-e797b321092b45a1bcbc4478d982a01e?pvs=4) 
- Testing Plan: https://github.com/metabase/metabase/issues/34368
- feature branch: `move-cards-between-tabs-feature-branch` 

**Implementation Plan**
* Implement the tab menu, and dashcard movement logic
* Implement logic to ensure that dashcards retain their size when moved across tabs

***Milestone 1: Initial dashcard movement***

```[tasklist]
### Tasks
- [x] Implement dashcard movement between tabs (`MOVE_DASHCARD_TO_TAB` redux action)
- [x] Implement dashcard tab menu within the toolbar (`DashCardTabMenu.tsx`) https://github.com/metabase/metabase/pull/34559
- [x] Check with PD/PMs that the toolbar looks good on small cards
- [ ] https://github.com/metabase/metabase/pull/34834
- [ ] https://github.com/metabase/metabase/pull/34846
- [ ] https://github.com/metabase/metabase/pull/34906
```

***Milestone 2: Undo notification***

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/34961
```
***Milestone 3: Analytics***

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/35123
```

***Milestone 4: [Polishment] left-align dashcard actions for small cards***
Milestone PR: https://github.com/metabase/metabase/pull/35240

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/35240
- [ ] https://github.com/metabase/metabase/pull/35243
- [ ] https://github.com/metabase/metabase/pull/35324
- [ ] https://github.com/metabase/metabase/pull/35327
- [ ] https://github.com/metabase/metabase/pull/35378
- [ ] https://github.com/metabase/metabase/pull/35366
- [ ] https://github.com/metabase/metabase/pull/35502
```

**Comment by npretto** [comment]
Updated the epic to be aligned with the recent discussions from slack: https://metaboat.slack.com/archives/C057T1QTB3L/p1697471382430159?thread_ts=1697110097.943389&cid=C057T1QTB3L
