### ISSUE TITLE
[Epic] Explain why linked filters don't work and prevent accidentally disabling them

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#34604]
When linked filters don't work, users should know about it and why. They should also be blocked from getting into a state where linked filters don't work.

This work came out of https://github.com/metabase/metabase/issues/33892 which raises one specific case but there are more ways linked filters can fail.

This epic tracks a series of fixes to eliminate cases when linked filters don't work but there's nothing in the UI to suggest otherwise.

```[tasklist]
### Cases when linked filters don't work, and we don't tell users about it
- [ ] https://github.com/metabase/metabase/issues/33892
- [ ] https://github.com/metabase/metabase/issues/34570
- [ ] https://github.com/metabase/metabase/issues/34657
```

```[tasklist]
### PRs
- [ ] https://github.com/metabase/metabase/pull/34424
- [ ] https://github.com/metabase/metabase/pull/34438
- [ ] https://github.com/metabase/metabase/pull/34531
```
