### ISSUE TITLE
[Epic] Static line/area/bar/combo scope for x.48

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#34672]
**Links**
- full project estimates beyond x.48: https://www.notion.so/metabase/Line-Area-Bar-Combo-ECharts-migration-4398d13993304e6eac174f15955631ef
- tech design doc: https://www.notion.so/metabase/ECharts-tech-design-15a2fc793f164ddb80c9723745c17d0a
- feature branch: `echarts-static-combo-chart`

Closes:
- https://github.com/metabase/metabase/issues/33798
- https://github.com/metabase/metabase/issues/33705
- https://github.com/metabase/metabase/issues/30807
- https://github.com/metabase/metabase/issues/30609
- https://github.com/metabase/metabase/issues/30551
- https://github.com/metabase/metabase/issues/30325
- https://github.com/metabase/metabase/issues/30315
- https://github.com/metabase/metabase/issues/30142
- https://github.com/metabase/metabase/issues/29852
- https://github.com/metabase/metabase/issues/29836
- https://github.com/metabase/metabase/issues/29281
- https://github.com/metabase/metabase/issues/28822
- https://github.com/metabase/metabase/issues/27942
- https://github.com/metabase/metabase/issues/26769
- https://github.com/metabase/metabase/issues/25896
- https://github.com/metabase/metabase/issues/23743
- https://github.com/metabase/metabase/issues/20559

**Implementation Plan**

***Milestone 1: Replace the existing static combo chart***
This milestone represents smallest shippable scope that fully replaces existing charts, do not introduce regressions, fixes some of issues

```[tasklist]
### Line/area/bar/combo
- [ ] Clean up the prototype
- [ ] Axes label positioning
- [ ] Implement series settings
- [ ] Add static legend
- [ ] BE: pass combined cards data to JS
```

### Combined scalar
- [ ] BE: pass combined scalars cards + datasets to JS
- [ ] FE: render combined scalars as bars
```

***Milestone 2: Full feature parity***
```[tasklist]
### Tasks
- [ ] Implement normalized stacking
- [ ] Goal line
- [ ] Trend line 
- [ ] FE: Render timeline events
- [ ] BE: Provide timeline events data
```
