### ISSUE TITLE
[Epic] Prevent users from adding questions from personal collections to dashboards in public collections

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#34733]
**Links**
- issue: https://github.com/metabase/metabase/issues/34045
- eng doc: https://www.notion.so/metabase/Prevent-users-from-adding-questions-from-personal-collections-to-dashboards-in-public-collections-d94438b13f974e0fbe97d99f732433d1

### Milestones overview

```[tasklist]
### Milestone 1: Collection changes
- [x] [Dashboard changes](#dashboard-changes)
- [x] [Query builder changes](#query-builder-changes)
- [x] [Handle most recently viewed dashboard](#most-recently-viewed-dashboard)
- [x] [Hide `+ Create a new dashboard` option](#hide-create-a-new-dashboard-option)
- [x] [Hide dashboards in public collections in dashboard picker (query builder)](#hide-dashboards-in-dashboard-picker)
- [x] [Handle dashboard changes and query builder changes after moving dashboards/questions to a different kind of collection](#handle-moving-items-to-different-collection-type)
- [x] Add E2E tests for handling moving dashboards/questions
- [ ] https://github.com/metabase/metabase/pull/35135
```

#### Testing plan for milestone 1
Dashboards
1. Add a question to a dashboard in a public collection
    **expectation**:
    - hides all personal collections
    - show all questions
1. Add a question to a dashboard in a personal collection
    **expectation**:
    - shows all collections
    - show all questions
1. move a dashboard from a personal collection to a public collection and test 1)
    **expectation**: hides all personal collections
    - hides all personal collections
    - show all questions
1. move a dashboard from a public collection to a personal collection and test 2)
    **expectation**:
    - shows all collections
    - show all questions

Query builder

Newly created question
1. Select a dashboard for a question in a public collection
    **expectation**: shows all collections
1. Select a dashboard for a question in a personal collection
    **expectation**: hides all public collections
1. Open public collection for a question in a public collection
    **expectation**:
        - shows `+ Create a new dashboard` option
        - shows dashboards
1. Open personal collection for a question in a public collection
    **expectation**:
        - shows `+ Create a new dashboard` option
        - shows dashboards
1. Open public collection for a question in a personal collection (this only happens for the root collection, as other public collections are already hidden)
    **expectation**:
        - hides `+ Create a new dashboard` option
        - hides dashboards
1. Open personal collection for a question in a personal collection
    **expectation**:
        - shows `+ Create a new dashboard` option
        - shows dashboards
1. When the question is in a public collection and the most recently viewed dashboard is in a public collection
    **expectation**:
        - shows the most recently viewed dashboard
1. When the question is in a public collection and the most recently viewed dashboard is in a personal collection
    **expectation**:
        - shows the most recently viewed dashboard
1. When the question is in a personal collection and the most recently viewed dashboard is in a public collection
    **expectation**:
        - shows the root collection instead
1. When the question is in a personal collection and the most recently viewed dashboard is in a personal collection
    **expectation**:
        - shows the most recently viewed dashboard

Existing question
1. Move a question from a personal collection to a public collection and test 1) from the **Newly created question** section
    **expectation**: shows all collections
1. Move a question from a public collection to a personal collection and test 2) from the **Newly created question** section
    **expectation**: hides all public collections
1. Test the rest of the scenarios from the **Newly created question** section

```[tasklist]
### Milestone 2: Item changes and search
- [x] [Hide items when searching in question picker (dashboards)](#search-question-picker)
- [x] [Hide items when searching in dashboard picker (query builder)](#search-dashboard-picker)
- [x] [Hide public collections in create a new dashboard modal](#hide-public-collections-in-create-dashboard-modal)
- [x] [Hide `+ New collection` option in `FormCollectionPicker.tsx`](#hide-new-collection-option)
- [x] [Hide public collections in create a new collection modal](#hide-public-collections-in-create-collection-modal)
- [x] Hide personal collections and dashboards when configuring click behavior linking to dashboards
- [x] Hide personal collections and questions when configuring click behavior linking to questions
- [ ] https://github.com/metabase/metabase/pull/35215
- [ ] https://github.com/metabase/metabase/pull/35277
- [ ] https://github.com/metabase/metabase/pull/35317
```

#### Testing plan for milestone 2

Dashboards
1. Search questions for a dashboard in a public collection
    **expectation**:
    - show only questions in public collections
1. Search questions for a dashboard in a personal collection
    **expectation**:
    - show all questions

Dashboard click behavior
1. Link to questions/dashboards for a question in a public collection
    **expectation**:
    - show only questions/dashboards in public collections
    - search should return only questions/dashboards in public collections
1. Link to questions/dashboards for a question in a personal collection
    **expectation**:
    - show all questions/dashboards
    - search should return all questions/dashboards

Query builder

Newly created question
1. Search a dashboard for a question in a public collection
    **expectation**:
    - show all dashboards
1. Search a dashboard for a question in a personal collection
    **expectation**:
    - show only questions in personal collections
1. Select `Create a new dashboard` for a question in a public collection
    **expectation**:
    - show all collections
    - always show `New collection`
1. Select `Create a new dashboard` for a question in a personal collection
    **expectation**:
    - show only personal collections
    - only show `New collection` option in personal collections
1. Select `New collection` for a question in a public collection
    **expectation**:
    - show all collections
1. Select `New collection` for a question in a personal collection
    **expectation**:
    - show only personal collections

Existing question

Test everything the same as **Newly created question**

#### Dashboard changes <a id="dashboard-changes"></a>
BE
- Hydrates `is_personal` in `GET /api/dashboard/:id`'s `response.collection`
- Hydrates `is_personal` in `GET /api/collection` (use to hide personal collections in the question picker)

FE
- adding questions from a dashboard
    ```ts
    if (!is_personal) {
      // public collection
      // hide personal collections in the question picker
    }
    ```
- When adding questions to a dashboard in public collections, only show public collections (hide personal collections)
    ```ts
    // only public collections
    collections.filter(c => !c.is_personal)
    ```

#### Query builder changes <a id="query-builder-changes"></a>
BE
- Hydrates `is_personal` in `POST /api/card/`'s `response.collection` (when adding a newly created question to a dashboard) (might be optional, if we figure out a way for front end to use the data from `GET /api/card:id` instead. Needs to dispatch some Redux actions manully)
- Hydrates `is_personal` in `GET /api/card/:id`'s `response.collection` (when adding an existing question to a dashboard)

FE
- When adding a question in personal collection, only show personal collections (hide public collections)
    ```ts
    // to check is a question is in a personal collections
    card.collection.is_personal

    // shows only personal collections
    collections.filter(c => c.is_personal)
    ```

#### Handle most recently viewed dashboard <a id="most-recently-viewed-dashboard"></a>
BE
- Hydrates `is_personal` in `GET /api/activity/most_recently_viewed_dashboard`'s `response.collection`, there isn't a `collection` key currently.

FE
When trying to add a question to a dashboard in query builder, if there's a most recently viewed dashboard:
- If the question is in a personal collection
  - if the most recently viewed dashboard is in a public collection, discard it and show root collection instead
  - if the most recently viewed dashboard is in a personal collection, keep the collection

#### Hide `+ create a new dashboard` option <a id="hide-create-a-new-dashboard-option"></a>
FE
- if the question is in a personal collection, hide `+ create a new dashboard` option` in public collections (currently the root collection only)

#### Hide dashboards in public collections in dashboard picker (query builder) <a id="hide-dashboards-in-dashboard-picker"></a>
BE
- `GET  /api/collection/:id/items` to allow excluding items from public collections. Could use the similar approach in `GET /api/search` (This could be optional, FE could decided not to render the items entirely, because BE changes could be costly)
- 
FE
- When the question is in personal collection, hide dashboards in public collections (dashboards in the root collection). This only happens when users are viewing the root collection because we will hide other public collections so they are unselectable.

#### Handle dashboard changes and query builder changes after moving dashboards/questions to a different kind of collection <a id="handle-moving-items-to-different-collection-type"></a>

BE
- Hydrates `PUT /api/card/:id`'s `collection.is_personal`
- Hydrates `PUT /api/dashboard/:id`'s `collection.is_personal`

FE
There should be no change, the new information should be coming from the above 2 updated endpoints

#### Hide items when searching in question picker (dashboards) <a id="search-question-picker"></a>
BE
- `GET /api/search` to allow excluding questions and models from personal collections
  option 1:
  enum - all items, only items from personal collections, only items from non-personal items

  option 2:
  context: "question" | "dashboard"
  collection_id: the collection of the enclosing question or dashboard

FE
- Pass options to search endpoint to exclude questions and models from personal collections

#### Hide items when searching in dashboard picker (query builder) <a id="search-dashboard-picker"></a>
BE
- `GET /api/search` to allow excluding dashboards from public collections

FE
- Pass options to search endpoint to exclude dashboards from public collections

#### Hide public collections in create a new dashboard modal <a id="hide-public-collections-in-create-dashboard-modal"></a>
FE
- Modify `AddToDashSelectDashModal.tsx` and pass a flag to hide public collections to `CreateDashboardModal`
    ```ts
    if (shouldCreateDashboard) {
      return (
        <CreateDashboardModal
          // the new flag
          showOnlyPersonalCollections={isQuestionInPersonalCollection}
          collectionId={card.collection_id}
          onCreate={navigateToDashboard}
          onClose={() => setShouldCreateDashboard(false)}
        />
      );
    }
    ```

#### Hide `+ New collection` option in `FormCollectionPicker.tsx` <a id="hide-new-collection-option"></a>
FE
- Modify `FormCollectionPicker.tsx` to pass a flag to hide `<CreateCollectionOnTheGoButton />` when viewing the root collection and the question is in personal collection

#### Hide public collections in create a new collection modal <a id="hide-public-collections-in-create-collection-modal"></a>
FE
- Modify `CreateCollectionOnTheGo.tsx` to pass a flag to `<CreateCollectionModal />` to hide public collections when viewing the root collection and the question is in personal collection

<details>
<summary>
**Old specs**
</summary>

**Prerequisite**
BE change from 1.2) and 3.2)
Modify `GET /api/collection/:collection-id/items`
1. to allow excluding dashboards from public collections
3. to allow excluding questions and models from personal collections and their descendants

**Implementation Plan**
> **Note**
> The file locations are from [this pull request](https://github.com/metabase/metabase/pull/34276), so the actual locations on `master` would be a bit different.

0. Create a new util to determine if a collection is a personal collection or is its descendant
```ts
function isInPersonalCollection(collection: Collection) {
  return (
    collection.personal_owner_id != null ||
    collection.effective_ancestors.some(parent => parent.personal_owner_id != null)
  );
}
```
1. Hides dashboards from public collections when adding a question from a personal collection via modal when adding a question to a dashboard (from either creating a new question or from existing questions)
    ![image](https://github.com/metabase/metabase/assets/1937582/29fdaac4-2f16-4452-8ccb-4128e220628b)
    1.1 `/Users/kelvin/workspace/metabase/frontend/src/metabase/containers/DashboardPicker.tsx`, `/Users/kelvin/workspace/metabase/frontend/src/metabase/containers/ItemPicker/ItemPicker.tsx`
    Modify `ItemPicker` to accept a new prop/flag to hide items from public collections
    1.2 [BE] Modify `GET /api/collection/:collection-id/items?models=dashboard` to allow excluding dashboards from public collections
4. Hides **+ Create a new dashboard button** when trying to add a question from a personal collection and viewing a public collection. (this is the same condition as in point 1.)
    ![image](https://github.com/metabase/metabase/assets/1937582/d9156c07-f32a-4032-8c5f-fa0311f0628f)
    3.1 `/Users/kelvin/workspace/metabase/frontend/src/metabase/containers/AddToDashSelectDashModal/AddToDashSelectDashModal.tsx`
    Call `GET /api/collection/:id` to determine if we want to hide the option using the same logic in point 1) using the util from 0)
5. Hides questions from personal collections when trying to add questions to dashboards in public collections
    ![image](https://github.com/metabase/metabase/assets/1937582/f83a05fc-2a6e-467a-93a2-2889629abffa)
    4.1 `/Users/kelvin/workspace/metabase/frontend/src/metabase/dashboard/components/add-card-sidebar/QuestionPicker.jsx`
    Modify `QuestionPicker` to accept a new prop/flag to hide items from personal collections (could be the same flag from point 1.1)
    4.2 [BE] Modify `GET /api/collection/:collection-id/items?models=card&models=dataset` to allow excluding questions and models from personal collections and their descendants

**Testing Plan**
In all scenarios: Tests when admins add a question to another user's personal collection as well.
1. Adding a question to a dashboard when creating a new question
    1.1 Adds a question from a public collection to a dashboard from public collections
    **expectation:**
      - Shows all dashboards
      - Shows **+ Create a new dashboard button** option
    1.2 Adds a question from a public collection to a dashboard from personal collections
    **expectation:**
      - Shows all dashboards
      - Shows **+ Create a new dashboard button** option
    1.3 Adds a question from a personal collection to a dashboard from public collections
    **expectation:**
      - Hides all dashboards
      - Hides **+ Create a new dashboard button** option
    1.4 Adds a question from a personal collection to a dashboard from personal collections
    **expectation:**
      - Shows all dashboards
      - Shows **+ Create a new dashboard button** option
1. Adding a question to a dashboard when viewing an existing question (Same conditions as in point 1)
    1.1 Adds a question from a public collection to a dashboard from public collections
    **expectation:**
      - Shows all dashboards
      - Shows **+ Create a new dashboard button** option
    1.2 Adds a question from a public collection to a dashboard from personal collections
    **expectation:**
      - Shows all dashboards
      - Shows **+ Create a new dashboard button** option
    1.3 Adds a question from a personal collection to a dashboard from public collections
    **expectation:**
      - **Hides** all dashboards
      - **Hides** **+ Create a new dashboard button** option
    1.4 Adds a question from a personal collection to a dashboard from personal collections
    **expectation:**
      - Shows all dashboards
      - Shows **+ Create a new dashboard button** option
1. Adding questions to a dashboard when editing a dashboard
    1.1 Adds a question from a public collection to a dashboard from public collections
    **expectation:**
      - Shows all questions
    1.2 Adds a question from a public collection to a dashboard from personal collections
    **expectation:**
      - Shows all questions
    1.3 Adds a question from a personal collection to a dashboard from public collections
    **expectation:**
      - **Hides** all questions
    1.4 Adds a question from a personal collection to a dashboard from personal collections
    **expectation:**
      - Shows all questions
</details>

**Comment by sarahmae1623** [comment]
assets/server-statistics-csv-example.csv

**Comment by WiNloSt** [comment]
All milestones are merged 🎉

**Comment by sarahmae1623** [comment]
> assets/server-statistics-csv-example.csv
