### ISSUE TITLE
[INTERNAL] Refine file-paths related to the CI

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#34880]
We currently have one huge rule called `*ci` that includes almost all files in the `.github/` directory (except markdown and `team.json`). And we have way too many workflows and actions. Any time anyone touches **any** file in this folder, no matter how (un)related it might be, literally all workflows will spin up. It's wasteful and sub-optimal.

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/34882
- [ ] https://github.com/metabase/metabase/pull/34890
- [ ] https://github.com/metabase/metabase/pull/35527
- [ ] https://github.com/metabase/metabase/pull/35533
- [ ] https://github.com/metabase/metabase/pull/34892
- [ ] https://github.com/metabase/metabase/pull/34209
- [ ] https://github.com/metabase/metabase/pull/35580
- [ ] https://github.com/metabase/metabase/pull/35617
```

**Comment by nemanjaglumac** [comment]
This Epic is now complete.
Some further improvements might include: cljs, whitespace and build scripts workflows.

That was outside of the current scope.
