### ISSUE TITLE
Add percentage type to metadata

### ISSUE THREAD

**Issue by maxzheng** [metabase/metabase#35124]
**Is your feature request related to a problem? Please describe.**
In Metadata, there are quantity and money types, but it's missing percentage. So for a ratio/rate, there isn't any type and so it will just display as a decimal. To show as a percentage, you have to manually to % in the question's editor **every time**. 

**Describe the solution you'd like**
Add percentage type so admins can set it in metadata once and users don't need to repeatedly set it in editor land. 

**Describe alternatives you've considered**
Repeatedly set it in editor per each use

**How important is this feature to you?**
Violates the DRY principle

#### WIP branch
`add-percent-metadata-type-35124`

### Milestone 1

The goal of this milestone is to support the new "Percentage" semantic column type so that all values of the column are rendered as percents.

```[tasklist]
### Tasks
- [x] BE: Add the "Percentage" semantic column type
- [x] FE: Add the "Percentage" item to the semantic column type picker
- [ ] FE: Infer "Percentage" formatting from the semantic type in the column viz settings
- [x] FE/BE: Add specs
```

### Milestone 2 (optional)

Improve UX in places where we already show percentages to avoid duplication

```[tasklist]
### Tasks
- [ ] FE: Stacked tooltips
- [ ] FE: Pie charts
- [ ] FE: Normalized stacked bar/area charts
- [ ] FE: Update filters UX
```

**Comment by calherries** [comment]
[Slack discussion](https://metaboat.slack.com/archives/C057T1QTB3L/p1698758976060659)

This requires adding a semantic type for percentage values, which requires BE and FE changes (probably about 20 LOC).

Context from Nick for the FE changes:

> the default value for that particular setting is decided [here](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/visualizations/lib/settings/column.js#L269). Looks like we call `isCurrency`, which looks at the semantic type of the field. we could add some additional logic to that function to make it a bit smarter. I guess right now, the default will only ever be currency or decimal

**Comment by cdeweyx** [comment]
@calherries did we ever get a chance to move on this? Just want to make sure it doesn't get lost in the reorg shuffle.

**Comment by calherries** [comment]
@cdeweyx No, I didn't get the chance to look at this. Can you reassign?

**Comment by alxnddr** [comment]
On the FE side the following items needs to be implemented or considered:
- Update places where we already show percentages to avoid duplication
  - Stacked tooltips
  - Pie charts
  - Normalized stacked bar charts
- Update the formatting function so it supports percentage formatting based on the new column type
- Ensure auto Y-axis split separates percentage metrics from others
- Support percentage formatting in csv/json/xlsx exports
- Support percentage formatting in all static viz that has its own formatting
