### ISSUE TITLE
[Testing Plan] Auto-wire up dashboard field filters

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#35149]
## Description
For Epic #35147
## Location
- `frontend/src/metabase/dashboard/[TBD]`
## Dimensions
* Applying filter to multiple dashboard cards
	* Only one card in the dashboard with the field
	* Multiple cards with the same field and no field filters applied
	* Multiple cards, with some that already have field filter applied
* Undo banner
	* Only one card with the field filter applied
	* Multiple cards with the same field filter applied
		* Keeping the field filter on the original card with the newly applied filter
	* Multiple cards, some with the new applied filter and some without
		* Keeping the fields of cards that had their own field filters already

## Actions
* Applying the field filter
* Clicking `undo` on the field filter application

### Unit Tests
* TBD

### Integration Tests
- [ ] Auto applying field filters
	- [ ] Selecting a field filter on a card triggers the `apply` function on the card
	- [ ] Selecting a field filter on a card triggers the `apply` function on other cards with the same field
	- [ ] Selecting a field filter on a card doesn't trigger the `apply` function on cards that already have a field filter applied to them
	- [ ] Selecting a field filter on a card doesn't trigger the `apply` function on cards that don't have the same field as the original card

- [ ] `Undo` Banner
	- [ ] The `undo` banner only appears when more than one card has a field filter auto-applied to it
	- [ ] Undoing the auto-application triggers an `unapply` function on cards
	- [ ] Undoing the auto-application doesn't trigger an `unapply` function on cards that previously had a field filter applied to them

### E2E Tests
- [ ] Applying a field filter to a card should apply the same field filter to cards with the same field
- [ ] Applying a field filter to a card should not apply the same field filter to cards that don't have the same field 
- [ ] Applying a field filter to a card should not apply the same field filter to cards already have a filter applied to them
- [ ] Triggering an auto-apply on multiple cards should trigger the `undo` explanatory banner
- [ ] Clicking `undo` should revert cards to their previous state before the auto apply, except the original card that had their field filter applied
