### ISSUE TITLE
[Epic] Make dashboard saves faster

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#35209]
Resolves [Update dashboard performance 48](https://github.com/metabase/metabase/issues/34721#top)

Saving a dashboard takes too long on master, due to https://github.com/metabase/metabase/pull/33392

```[tasklist]
### Problems
- [ ] https://github.com/metabase/metabase/issues/34828
- [x] Two revisions can be created when a dashboard is saved
- [x] FE calls separate endpoints for updating a dashboard vs its dashcards and tabs
```

```[tasklist]
### PRs
- [ ] https://github.com/metabase/metabase/pull/34947
- [ ] https://github.com/metabase/metabase/pull/35223
- [ ] https://github.com/metabase/metabase/pull/35406
- [ ] https://github.com/metabase/metabase/pull/35413
- [ ] https://github.com/metabase/metabase/pull/35499
```

**Comment by calherries** [comment]
The problem is resolved on the BE. The remaining problem is still on the FE, with a redundant GET request. See [this comment](https://github.com/metabase/metabase/issues/34828#issuecomment-1802203038).
