### ISSUE TITLE
[Epic] Overhaul Entity Picker

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#35564]
[Product Doc
](https://www.notion.so/metabase/Make-picking-an-item-a-nice-experience-with-an-EntityPicker-component-05e457c1b84f413f84ab9756e0c68b57)[Technical Design
](https://www.notion.so/metabase/EntityPicker-Technical-Design-d4483523312e46c38ffd0bfe9c2371c7)

```[tasklist]
### Milestone 1: collection picker and mover (admin/webapp)
- [ ] https://github.com/metabase/metabase/issues/36411
- [ ] https://github.com/metabase/metabase/issues/37833
- [ ] https://github.com/metabase/metabase/issues/39702
- [ ] https://github.com/metabase/metabase/issues/39432
```

```[tasklist]
### Milestone 2: question picker (admin/webapp)
- [ ] https://github.com/metabase/metabase/issues/36376
```

```[tasklist]
### Milestone 3: dashboard picker (admin/webapp)
- [ ] https://github.com/metabase/metabase/issues/39140
```

```[tasklist]
### Milestone 4: recents (admin/webapp)
- [ ] https://github.com/metabase/metabase/issues/41957
- [ ] https://github.com/metabase/metabase/issues/39528
```

```[tasklist]
### Milestone 5: data picker (qc)
- [x] https://github.com/metabase/metabase/issues/40377
- [ ] https://github.com/metabase/metabase/issues/42774
- [ ] https://github.com/metabase/metabase/issues/40717
- [ ] https://github.com/metabase/metabase/issues/39431
```

Issues that should be handled:
- https://github.com/metabase/metabase/issues/25142
- https://github.com/metabase/metabase/issues/16862
- https://github.com/metabase/metabase/issues/20406
- https://github.com/metabase/metabase/issues/30117
- https://github.com/metabase/metabase/issues/21786
- https://github.com/metabase/metabase/issues/27101
- https://github.com/metabase/metabase/issues/21511
- https://github.com/metabase/metabase/issues/24660

**Comment by luizarakaki** [comment]
Previous work https://github.com/metabase/metabase/issues/27160

**Comment by kamilmielnik** [comment]
I changed the order of milestones 2 & 3 because `QuestionPicker` component will be reused in `DataPicker` component.

**Comment by iethree** [comment]
🥳
