### ISSUE TITLE
Tame E2E flakes

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#35607]
This project is an attempt to strategically tame existing E2E flakes, and to prevent creating new ones. It will be carried on in a few steps. Exact steps and phases TBD.

As @perivamsi suggested the most important two steps in the first phase are:

```[tasklist]
- [x] Identify and mark all flakes
- [ ] https://github.com/metabase/metabase/issues/35661
```

Slightly higher priority should have tests that fail even after two retries, but we should aim to almost eliminate all flakes if possible.
In an ideal scenario, we can safely remove internal Cypress retries and still be confident that tests work. That might be a somewhat lofty goal given how fragile and unpredictable CI environment can be, but it's still worth trying to get there.

Please note that the aggregate issue that was tracking all flakes is https://github.com/metabase/metabase/issues/28488.
Some of the currently active flakes are labelled with the [`flaky-test-fix`](https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+label%3Aflaky-test-fix) label.

> **Important**
> For this particular project, we have to keep eye on the recently fixed flakes (no older than the last seven days). Only fixes that were stress-tested count.

```[tasklist]
### Active flake fixes
- [x] https://github.com/metabase/metabase/pull/35427
- [x] https://github.com/metabase/metabase/pull/35579
- [ ] https://github.com/metabase/metabase/pull/35589
- [ ] https://github.com/metabase/metabase/pull/35616
- [ ] https://github.com/metabase/metabase/pull/35655
- [ ] https://github.com/metabase/metabase/issues/36675
- [ ] https://github.com/metabase/metabase/issues/36678
- [ ] https://github.com/metabase/metabase/issues/36679
- [ ] https://github.com/metabase/metabase/issues/36680
- [ ] https://github.com/metabase/metabase/issues/36681
- [ ] https://github.com/metabase/metabase/issues/36682
- [ ] https://github.com/metabase/metabase/issues/36683
- [ ] https://github.com/metabase/metabase/issues/36684
- [ ] https://github.com/metabase/metabase/issues/36685
- [ ] https://github.com/metabase/metabase/issues/36686
- [ ] https://github.com/metabase/metabase/issues/36687
- [ ] https://github.com/metabase/metabase/issues/36688
- [ ] https://github.com/metabase/metabase/issues/36689
```
```[tasklist]
### Old skipped (quarantined) flakes
- [ ] https://github.com/metabase/metabase/pull/35984
- [ ] https://github.com/metabase/metabase/pull/35986
- [ ] https://github.com/metabase/metabase/pull/36041
- [ ] https://github.com/metabase/metabase/pull/36050
- [ ] https://github.com/metabase/metabase/pull/36077
- [ ] https://github.com/metabase/metabase/pull/36080
```

**Comment by iethree** [comment]
does it make sense to keep this open?

**Comment by nemanjaglumac** [comment]
> does it make sense to keep this open?

This greatly depends on what next steps @perivamsi proposes. If they need to be tracked, we can leave this open. No other reason to keep this issue open otherwise.

**Comment by perivamsi** [comment]
Let's keep this epic please. I want to track ongoing flakes using this.

**Comment by nemanjaglumac** [comment]
@perivamsi 

@iethree did an amazing job with the flake report automation. Are you ok with closing the issue now?

**Comment by perivamsi** [comment]
Yes please
