### ISSUE TITLE
[Epic] Allow appending more data to CSV uploads

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#35614]
**Links**
- [product doc](https://www.notion.so/metabase/Allow-appends-on-existing-CSV-upload-models-f1f13864632d4cfd83522fce762890eb#58380830c6ca45df923e4cacc4af1964)
- [eng doc](https://www.notion.so/metabase/Eng-Allow-appending-more-data-to-CSV-uploads-4c40e06fa64744c699588b8d8576e5df)

```[tasklist]
### Milestone 0: Append from Model Page
- [ ] https://github.com/metabase/metabase/pull/36640
- [ ] https://github.com/metabase/metabase/pull/36705
- [ ] https://github.com/metabase/metabase/issues/36776
- [ ] https://github.com/metabase/metabase/pull/36950
- [ ] https://github.com/metabase/metabase/pull/36990
- [ ] https://github.com/metabase/metabase/pull/36995
- [ ] https://github.com/metabase/metabase/pull/37052
- [ ] https://github.com/metabase/metabase/pull/38274
- [ ] https://github.com/metabase/metabase/pull/37220
```

```[tasklist]
### Milestone 1: Append from Collection Page
- [ ] https://github.com/metabase/metabase/pull/38322
- [ ] https://github.com/metabase/metabase/issues/38435
```

**Comment by calherries** [comment]
Moved outstanding follow-up tasks to another epic https://github.com/metabase/metabase/issues/38853
