### ISSUE TITLE
[Epic] White-labeling: Customizing or hiding “Help” link

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#35915]
**Links**
- [product doc](https://www.notion.so/metabase/White-labeling-Customizing-or-hiding-Help-link-8840fbdfd3c743ccaff9301a835ec81c?pvs=4)
- feature branch: `white-label-hel-link-feature-branch ` ([pr](https://github.com/metabase/metabase/pull/36172))
- [Testing plan](https://github.com/metabase/metabase/issues/36250)

# Milestone 1 - basic functionality
```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/35960
- [ ] https://github.com/metabase/metabase/pull/36208
- [ ] https://github.com/metabase/metabase/pull/36478
- [ ] https://github.com/metabase/metabase/pull/36480
- [x] https://github.com/metabase/metabase/pull/36328 (add settings on the backend with validation) / (add the `help-link` setting to the anonymous instance analytics)(see [product doc](https://www.notion.so/metabase/White-labeling-Customizing-or-hiding-Help-link-8840fbdfd3c743ccaff9301a835ec81c?pvs=4#4315376092b84191a5c339d27ffdbb80))
```
