### ISSUE TITLE
[MLv2] Computing clauses and columns in the query builder

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#36108]
Definition of done:
- QB uses only MLv2 to compute the list of columns (like `filterableColumns`) and clauses (like `aggregations`)

### Question methods

```[tasklist]
### FE
- [ ] https://github.com/metabase/metabase/issues/37390
- [ ] https://github.com/metabase/metabase/issues/37511
- [ ] https://github.com/metabase/metabase/issues/37510
- [ ] https://github.com/metabase/metabase/issues/37687
- [ ] https://github.com/metabase/metabase/issues/37171
- [ ] https://github.com/metabase/metabase/issues/37172
- [ ] https://github.com/metabase/metabase/issues/37508
- [ ] https://github.com/metabase/metabase/issues/37389
- [ ] https://github.com/metabase/metabase/issues/37507
- [ ] https://github.com/metabase/metabase/issues/37169
- [ ] https://github.com/metabase/metabase/issues/37170
- [ ] https://github.com/metabase/metabase/issues/37506
- [ ] https://github.com/metabase/metabase/issues/37509
```

```[tasklist]
### BE
- [ ] https://github.com/metabase/metabase/issues/38510
- [ ] https://github.com/metabase/metabase/issues/37626
- [ ] https://github.com/metabase/metabase/issues/37678
- [ ] https://github.com/metabase/metabase/issues/37782
- [ ] https://github.com/metabase/metabase/issues/37688
- [ ] https://github.com/metabase/metabase/issues/38253
- [ ] https://github.com/metabase/metabase/issues/37698
- [ ] https://github.com/metabase/metabase/issues/36974
- [ ] https://github.com/metabase/metabase/issues/37659
- [ ] https://github.com/metabase/metabase/issues/36973
- [ ] https://github.com/metabase/metabase/issues/37120
- [ ] https://github.com/metabase/metabase/issues/36978
- [ ] https://github.com/metabase/metabase/issues/36977
- [ ] https://github.com/metabase/metabase/issues/37851
- [ ] https://github.com/metabase/metabase/issues/38312
```

### Actions

```[tasklist]
### FE
- [ ] https://github.com/metabase/metabase/issues/37392
- [ ] https://github.com/metabase/metabase/issues/37391
- [ ] https://github.com/metabase/metabase/issues/37393
```

```[tasklist]
### BE
- [ ] https://github.com/metabase/metabase/issues/37517
```

### Components

```[tasklist]
### FE
- [ ] https://github.com/metabase/metabase/issues/37227
- [ ] https://github.com/metabase/metabase/issues/37677
- [ ] https://github.com/metabase/metabase/issues/37396
- [ ] https://github.com/metabase/metabase/issues/37516
- [ ] https://github.com/metabase/metabase/issues/37527
- [ ] https://github.com/metabase/metabase/issues/37628
- [ ] https://github.com/metabase/metabase/issues/37629
- [ ] https://github.com/metabase/metabase/issues/37395
- [ ] https://github.com/metabase/metabase/issues/37397
- [ ] https://github.com/metabase/metabase/issues/37399
- [ ] https://github.com/metabase/metabase/issues/37512
- [ ] https://github.com/metabase/metabase/issues/37513
- [ ] https://github.com/metabase/metabase/issues/37514
- [ ] https://github.com/metabase/metabase/issues/37515
```

### Unused code

```[tasklist]
### FE
- [ ] https://github.com/metabase/metabase/issues/36736
- [ ] https://github.com/metabase/metabase/issues/36737
```
