### ISSUE TITLE
[MLv2] [Testing Plan] Drill Thru

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#36253]
### automatic-insights

```[tasklist]
- [x] works for cell (dot) query (huh?)
- [x] works for pivot cell
- [x] works for legend item
- [x] not returned for query with no breakouts
- [x] checks `enable-xrays` Setting
- [x] removes filters
- [x] adds a filter for breakout `dimensions` using the same logic as in `underlying-records`
```

### column-filter

```[tasklist]
- [x] works for column header
- [x] checks column is not `:type/Structured`
```

### distribution

```[tasklist]
- [x] works for column header
- [x] not returned for query with aggregations or breakouts
- [x] checks column not `type/PK`, `type/SerializedJSON`, `type/Description`, `type/Comment`
- [x] Remove all aggregation, breakout, orderBy, limit clauses
- [x] Aggregate by "count" operator
- [x] Breakout by the selected column. If the column is a date column, add "Month" temporal unit. If the column is a numeric column, apply the default binning strategy. Otherwise use the column as it is.
```

### fk-details

```[tasklist]
- [x] works for Cell
- [x] checks Column is `type/FK`
- [x] checks `value` is not `null`
- [x] Finds the target table for the selected FK. Creates a new query that targets the FK table and add a `=` filter using the corresponding PK column and the selected value
- [x] Preserve filters from the original query that use `=` operator and are based on **other** FK columns targeting the same FK table as the selected FK. This can only happen when the target table's PK consists of multiple columns.
```

### fk-filter

```[tasklist]
- [x] works for Cell
- [x] checks Selected column is `type/FK`
- [x] Returns `columnName` and `tableName` for the FK column. On the FE we strip `ID` suffix and turn `Product ID` into `Product's` and pluralize the table name.
- [x] Add a `=` filter for the selected column and value. Make sure to append the query stage when needed.
```

### pivot

```[tasklist]
- [x] works for Cell
- [x] checks Query has at least 1 aggregation
- [x] checks Column from the aggregation clause was selected (???)
- [x] query shape is allowed: 1 aggregation and no breakouts - `type/Date`, `type/Address`, and `type/Category` (only which are not also `type/Address`)
- [x] query shape is allowed: At least 1 aggregation and exactly 1 breakout based on `Address` column - `Date`, `Category`
- [x] query shape is allowed: At least 1 aggregation and 1-2 breakouts based on `Category` columns - `Date`, `Category`
- [x] query shape is allowed: At least 1 aggregation and either (1 breakout on a date column OR 1st breakout is `Date` and 2nd is `Category`) - `Address`, `Category`
- [x] Removes existing breakouts
- [x] Adds filters based on `dimensions`, i.e. filters for all existing breakout
- [x] Adds a breakout based on the selected column
```

### pk

```[tasklist]
- [x] works for Cell
- [x] checks Selected column is not a FK column
- [x] checks There are multiple PK columns in returned columns
- [x] checks Select column is a PK column OR the query has no aggregations (in this case the first available PK column and its value are used instead of the selected one)
- [x] checks The PK value is not `null`. Make sure to take the previous point into account, e.g. the selected column's value can be `null` but the PK column value in the same row can be not `null`).
- [x] Adds `=` filter for the PK column and it's value
```

### quick-filter

```[tasklist]
- [x] works for Cell
- [x] checks Column not `type/PK`, `type/FK`, or `type/Structured`
- [x] ~~checks Column can be filtered upon (exists in `filterableColumns`)~~ that can't happen currently in practice
- [x] For `null` value, allow only `=` and `≠` operators, which map to `is-null` and `not-null` filter operators
- [x] For date and numeric columns, allow `<`, `>`, `=`, `≠` operators
- [x] For string columns which have `type/Comment` or `type/Description` semantic type, allow `contains` and `does-not-contain` operators.
- [x] For other cases, including string columns, allow only `=` and `≠` operators.
- [x] Return raw `value` in `displayInfo` for the drill. Is it used to show `Is ${value}` for string column operators.
- [x] Adds a filter clause based on the selected column, value, and the operator
- [x] Appends a query stage if the selected column is coming from an aggregation or breakout clause.
```

### sort

```[tasklist]
- [x] works for Column header
- [x] checks Column not `type/Structured`
- [x] If the column is already sorted, allow only the opposite direction to be applied
- [x] Adds a sort clause with the selection direction
```

### summarize-column

```[tasklist]
- [x] works for Column header
- [x] checks No aggregation or breakout clauses in the query
- [x] Returns operators that are compatible with the column. For `Summable` columns, all 3 are supported. For other columns only `distinct`.
- [x] Adds an aggregation clause with the selected operator
```

### summarize-column-by-time

```[tasklist]
- [x] works for Column header
- [x] checks No aggregation or breakout clauses in the query
- [x] checks The selected column is `Summable`, i.e. compatible with `sum` operator
- [x] checks There are date columns available for the breakout clause
- [x] Adds aggregation clause for the selected column
- [x] Adds a breakout on the first available date column. Use the default temporal unit available for this column. This unit **should be** computed based on `fingerprint` like [this](https://github.com/metabase/metabase/blob/0624d8d0933f577cc70c03948f4b57f73fe13ada/frontend/src/metabase-lib/metadata/Field.ts#L397) but currently it's hard-coded to `:month`. Separate bug [#38471](https://github.com/metabase/metabase/issues/38471)
```

### underlying-records

```[tasklist]
- [x] works for Cell
- [x] works for Pivot cell
- [x] works for Legend item
- [x] checks Not empty `dimensions`, i.e. at least 1 breakout in the query
- [x] Drops all query stages where there are no aggregation clauses until the last one.
- [x] Removes all aggregation, breakout, sort, limit, field clauses
- [x] Adds filters for every breakout `dimensions` using this logic https://github.com/metabase/metabase/blob/0624d8d0933f577cc70c03948f4b57f73fe13ada/frontend/src/metabase-lib/queries/utils/actions.js#L99
- [x] If there is a selected column (cell only), extract filters associated with this aggregation column. It could be built-in operators (SumIf) or Metrics with filters. Add these filters to the query.
```

### zoom

```[tasklist]
- [x] works for Cell
- [x] checks There is only on PK column available in returned columns
- [x] checks Selected column is not a FK, or an FK with NULL value (otherwise fk-details drill instead)
- [x] checks The value for the PK column (which can be different to selected column) in the data row is not `null`.
```

### zoom-in.binning

```[tasklist]
- [x] works for Cell
- [x] works for Pivot cell
- [x] works for Legend item
- [x] checks `dimensions` have a numeric column with a binning strategy applied. It can be the default one ("Auto"). Only the first matching column would be used in query transformation.
- [x] Removes breakouts for `dimensions`. Please note that with regular cells and pivot cells it would mean removing all breakouts; but with legend item clicks it would remove the breakout for the legend item column only.
- [x] Adds a filter based on columns and values from `dimensions`. Take temporal units and binning strategies into account https://github.com/metabase/metabase/blob/0624d8d0933f577cc70c03948f4b57f73fe13ada/frontend/src/metabase-lib/queries/utils/actions.js#L99
- [x] Adds a breakout based on the numeric column (from requirements). For location columns, use the binning strategy that is 10x more granular (e.g. `Every 1 degree` -> `Every 0.1 degrees`). For numeric columns, use the default binning strategy ("Auto").
- [x] Make sure this works correctly for nil bin values (either not returned, or generates an appropriate filter -- see #36581 for example)
```

### zoom-in.geographic

```[tasklist]
- [x] works for Cell
- [x] works for Pivot cell
- [x] works for Legend item
- [x] supports Country -> State (note: not currently supported, ask @camsaul for details)
- [x] supports Country -> LatLon(10)
- [x] supports State -> LatLon(1)
- [x] supports City -> LatLon(0.1)
- [x] supports LatLon -> LatLon
- [x] Impl: Country -> LatLon(10). If there is no `type/State` column available but there are `type/Latitude` and `type/Longitude` columns, add a filter based on the selected country and 2 breakouts (latitude and longitude) using "Every 10 degrees" binning strategy.
- [x] Impl: State -> LatLon(1). Add a filter based on the selected state and 2 breakouts (latitude and longitude) using "Every 1 degree" binning strategy.
- [x] Impl: City -> LatLon(0.1). Add a filter based on the selected city and 2 breakouts (latitude and longitude) using "Every 0.1 degrees" binning strategy.
- [x] Impl: LatLon -> LatLon. If the binning strategy is more greater than every 20 degrees, change it to 10 degrees. Otherwise divide the value by 10 and use it as the new binning strategy.
- [x] Make sure this works correctly for nil bin values (either not returned, or generates an appropriate filter -- see #36581 for example)
```

### zoom-in.timeseries

```[tasklist]
- [x] works for Cell
- [x] works for Pivot cell
- [x] works for Legend item
- [x] checks `dimensions` have a date column with `year`, `quarter`, `month`, `week`, `day`, `hour` temporal unit. For other units, or when there is no temporal bucketing this drill cannot be applied. Changing `hour` to `minute` ends the sequence. Only the first matching column would be used in query transformation.
- [x] `displayInfo` returns `displayName` with `See this {0} by {1}` string using the current and the next available temporal unit.
- [x] Removes breakouts for `dimensions`. Please note that with regular cells and pivot cells it would mean removing all breakouts; but with legend item clicks it would remove the breakout for the legend item column only.
- [x] Adds a filter based on columns and values from `dimensions`. Take temporal units and binning strategies into account https://github.com/metabase/metabase/blob/0624d8d0933f577cc70c03948f4b57f73fe13ada/frontend/src/metabase-lib/queries/utils/actions.js#L99
- [x] Adds a breakout based on the date column (from requirements), using the next (more granular) temporal unit.
```

### Drill entry points

Available drill entry points:
- Column header
- Cell (dot)
- Pivot cell
- Legend item

`ClickObject` represents data for the drill. It has the following properties which are passed to MLv2 functions:
- `column`
- `value`
- `data`
- `dimensions`

Column header click:
- `column` - `DatasetColumn`
- `value` - `undefined`
- `data` - `undefined`
- `dimensions` - `undefined`

Raw cell click (no aggregations or breakouts):
- `column` - `DatasetColumn`
- `value` - cell value
- `data` - corresponds to `rows` in `dataset` response; of shape `[{ col, value }]`, where `col` is a `DatasetColumn`
- `dimensions` - `undefined`

Aggregated cell click (has aggregations and maybe breakouts):
- `column` - `DatasetColumn`
- `value` - aggregation column value
- `data` - corresponds to `rows` in `dataset` response; of shape `[{ col, value }]`, where `col` is a `DatasetColumn`
- `dimensions` - `[{ column, value }]` for breakout columns only

Pivot cell click:
- `column` - `undefined`
- `value` - aggregation column value
- `data` - dataset row
- `dimensions` - `[{ column, value }]` for breakout columns only, for pivot cells there would be always 2 items

Legend item click:
- `column` - `undefined`
- `value` - `undefined`
- `data` - `undefined`
- `dimensions` - would contain only 1 `[{ column, value }]` where the column and value correspond to the breakout dimension used for the legend item; in most cases it's the second breakout in the query

#### Cheatsheet

|                       | `column`        | `value`           | `data`             | `dimensions`          |
|-----------------------|-----------------|-------------------|--------------------|-----------------------|
| Column header click   | `DatasetColumn` | -                 | -                  | -                     |
| Raw cell click        | `DatasetColumn` | cell value        | `[{ col, value }]` | -                     |
| Aggregated cell click | `DatasetColumn` | aggregation value | `[{ col, value }]` | `[{ column, value }]` |
| Pivot cell click      | -               | aggregation value | dataset row        | `[{ column, value }]` |
| Legend item click     | -               | -                 | -                  | `[{ column, value }]` |

### Not editable queries

Queries can be "editable" and "not editable". A non-editable query means the following:
- No data permissions at all (no `Database` in `Metadata`)
- Sandboxed access with no access to the source table (there is `Database` but no source `Table` in `Metadata`)
- No access to run queries against the source card (no virtual `Table`, i.e. with `card__1` id in `Metadata`)

**Currently no drills are available for native or non-editable GUI queries.**

### automatic-insights

Generates an X-ray dashboard for a query with a breakout.

Implementation https://github.com/metabase/metabase/blob/5f02f32332a7863548dc9fd2c87c686324ff0883/frontend/src/metabase-lib/queries/drills/automatic-insights-drill.ts#L5

Entry points:
- Cell (dot)
- Pivot cell
- Legend item 

Requirements:
- Query has at least 1 breakout
- `enable-xrays` setting is `true`

Query transformation:
- Remove filters
- Add a filter for breakout `dimensions`  using the same logic as in `underlying-records`

Question transformation:
- Set `table` display

### column-filter

Enables "Filter by this column" menu item. 

The caveat here is that for aggregation and breakout columns we need to append a stage before adding a filter. There is a helper function called `filterDrillDetails` which returns the query with a possibly appended stage, and the corresponding column for that stage. In each test case where drill thru is allowed we need to verify that `filterDrillDetails` appended the stage where needed.

Another caveat is that we need to verify that `filterDrillDetails` returned a _filterable_ column, i.e. a column obtained from `filterableColumns` call. A good way to verify that is to call `filterableColumnOperators` and check that a non-empty list is returned.

Implementation https://github.com/metabase/metabase/blob/a78b49446cf605cee46f5ef62243c0d421b0ff32/frontend/src/metabase-lib/queries/drills/column-filter-drill.ts#L10

Entry points:
- Column header

Requirements:
- Column not `type/Structured`

Query transformation:
- None/identity. The FE will show the FilterPicker and not call `drillThru` for this drill.

Question transformation:
- None

### distribution

Raw data with a breakout based on the selected column. 

For date columns, sets "Month" as a temporal unit. For numeric columns, uses the default binning strategy. Other columns are not changed.

Implementation https://github.com/metabase/metabase/blob/fa76af8cf88eeb44a6c5581ea8ac18a30b75ebf6/frontend/src/metabase-lib/queries/drills/distribution-drill.js#L11

Entry points:
- Column header

Requirements:
- No aggregation or breakout clauses in the query
- Column not `type/PK`, `type/SerializedJSON`, `type/Description`, `type/Comment`

Query transformation (last stage only):
- Remove all aggregation, breakout, orderBy, limit clauses
- Aggregate by "count" operator
- Breakout by the selected column. If the column is a date column, add "Month" temporal unit. If the column is a numeric column, apply the default binning strategy. Otherwise use the column as it is.

Question transformation:
- Set "bar" display

### fk-details

Object details drill for FK fields. Creates a new query based on the FK table with a `=` filter based on selected value.

Implementation:
https://github.com/metabase/metabase/blob/50208950907cb68f997562e67a24ceac4b81e1de/frontend/src/metabase-lib/queries/drills/object-detail-drill.ts#L117
https://github.com/metabase/metabase/blob/50208950907cb68f997562e67a24ceac4b81e1de/frontend/src/metabase-lib/queries/drills/object-detail-drill.ts#L55

Entry points:
- Cell

Requirements:
- Column is `type/FK`
- `value` is not `null`

Query transformation:
- Find the target table for the selected FK
- Create a new query that targets the FK table and add a `=` filter using the corresponding PK column and the selected value
- Preserve filters from the original query that use `=` operator and are based on **other** FK columns targeting the same FK table as the selected FK. This can only happen when the target table's PK consists of multiple columns.

Question transformation:
- Set default display

### fk-filter

Adds a simple `=` filter for the selected FK column. Enables option like`View this Product's Reviews`.

Implementation:
https://github.com/metabase/metabase/blob/fa76af8cf88eeb44a6c5581ea8ac18a30b75ebf6/frontend/src/metabase-lib/queries/drills/foreign-key-drill.js#L4

Entry points:
- Cell

Requirements:
- Selected column is `type/FK`
- Return `columnName` and `tableName` for the FK column. On the FE we strip `ID` suffix and turn `Product ID` into `Product's` and pluralize the table name.

Query transformation:
- Add a `=` filter for the selected column and value. Make sure to append the query stage when needed.

Question transformation:
- None

### pivot

"Breakout by" transform.

Implementation:
https://github.com/metabase/metabase/blob/1efa6c6f000cb4bd38065563176c35ea0027c865/frontend/src/metabase-lib/queries/drills/pivot-drill.ts#L25

Entry points:
- Cell

Requirements:
- Query with at least 1 aggregation
- Column from the aggregation clause was selected

For different query types/shapes different breakout columns are allowed:
- No aggregations and no breakouts - `type/Date`, `type/Address`, and `type/Category` (only which are not also `type/Address`)
- At least 1 aggregation and exactly 1 breakout based on `Address` column - `Date`, `Category`
- At least 1 aggregation and 1-2 breakouts based on `Category` columns - `Date`, `Category`
- At least 1 aggregation and either (1 breakout on a date column OR 1st breakout is `Date` and 2nd is `Category`) - `Address`, `Category`
- In other cases the drill is not supported

Query transformation is similar to `zoom-in` but can be simplified because legend items aren't supported:
- Remove existing breakouts
- Add filters based on `dimensions`, i.e. filters for all existing breakout
- Add a breakout based on the selected column

Question transformation:
- Set default display

Other functions:
- `pivotTypes` function that return available column types for the drill - "category" | "location" | "time"
- `pivotColumnsForType` returns the list of available columns for the drill and the selected type

### pk

Object details drill for cases when there is multiple PK columns.

Implementation:
https://github.com/metabase/metabase/blob/50208950907cb68f997562e67a24ceac4b81e1de/frontend/src/metabase-lib/queries/drills/object-detail-drill.ts#L99

Entry points:
- Cell

Requirements:
- Selected column is not a FK column
- There are multiple PK columns in returned columns
- Select column is a PK column OR the query has no aggregations (in this case the first available PK column and its value are used instead of the selected one)
- The PK value is not `null`. Make sure to take the previous point into account, e.g. the selected column's value can be `null` but the PK column value in the same row can be not `null`).

Query transformation:
- Add `=` filter for the PK column and it's value

Question transformation:
- None

### quick-filter

Adds a filter clause with simple operators like `<`, `>`, `=`, `≠`, `contains`, does-not-contain`.

Implementation:
https://github.com/metabase/metabase/blob/1efa6c6f000cb4bd38065563176c35ea0027c865/frontend/src/metabase-lib/queries/drills/quick-filter-drill.ts#L65

Entry points:
- Cell

Requirements:
- Column not `type/PK`, `type/FK`, or `type/Structured`
- Column can be filtered upon (exists in `filterableColumns`)
- For `null` value, allow only `=` and `≠` operators, which map to `is-null` and `not-null` filter operators
- For date and numeric columns, allow `<`, `>`, `=`, `≠` operators
- For string columns which have `type/Comment` or `type/Description` semantic type, allow `contains` and `does-not-contain` operators.
- For other cases, including string columns, allow only `=` and `≠` operators.
- Return raw `value` in `displayInfo` for the drill. Is it used to show `Is ${value}` for string column operators.

Query transformation:
- Add a filter clause based on the selected column, value, and the operator
- Append a query stage if the selected column is coming from an aggregation or breakout clause.

Question transformation:
- None

There is a separate function `filterDrillDetails` which returns `query` and `column` used for the `FilterPicker`. It should automatically append a query stage and find the corresponding _filterable_ column in this stage. It is used for `contains` and `does-not-contain` operators.

### sort

Adds an order by clause on the selected column.

Implementation:
https://github.com/metabase/metabase/blob/fa76af8cf88eeb44a6c5581ea8ac18a30b75ebf6/frontend/src/metabase-lib/queries/drills/sort-drill.js#L7

Entry points:
- Column header

Requirements:
- Column not `type/Structured`
- If the column is already sorted, allow only the opposite direction to be applied

Query transformation:
- Add a sort clause with the selection direction

Question transformation:
- None

### summarize-column

Adds an aggregation clause based on the selected column. Could be either `sum`, `avg`, or `distinct`.

Implementation: 
https://github.com/metabase/metabase/blob/fa76af8cf88eeb44a6c5581ea8ac18a30b75ebf6/frontend/src/metabase-lib/queries/drills/summarize-column-drill.js#L13

Entry points:
- Column header

Requirements:
- No aggregation or breakout clauses in the query
- Return operators that are compatible with the column. For `Summable` columns, all 3 are supported. For other columns only `distinct`.

Query transformation:
- Add an aggregation clause with the selected operator

Question transformation:
- Set default display

### summarize-column-by-time

Adds a `sum` aggregation clause for the selected column and a breakout on the first available date column.

Implementation:
https://github.com/metabase/metabase/blob/fa76af8cf88eeb44a6c5581ea8ac18a30b75ebf6/frontend/src/metabase-lib/queries/drills/summarize-column-by-time-drill.js#L7

Entry points:
- Column header

Requirements:
- No aggregation or breakout clauses in the query
- The selected column is `Summable`, i.e. compatible with `sum` operator
- There are date columns available for the breakout clause

Query transformation:
- Add aggregation clause for the selected column
- Add a breakout on the first available date column. Use the default temporal unit available for this column. This unit is computed based on `fingerprint` https://github.com/metabase/metabase/blob/0624d8d0933f577cc70c03948f4b57f73fe13ada/frontend/src/metabase-lib/metadata/Field.ts#L397

Question transformation:
- Set default display

### underlying-records

"View these Orders" transformation.

Implementation
https://github.com/metabase/metabase/blob/8ae401a968465ddb5b120c1770da146d429b4ad6/frontend/src/metabase-lib/queries/drills/underlying-records-drill.js#L32

Entry points:
- Cell
- Pivot cell
- Legend item

Requirements:
- Not empty `dimensions`, i.e. at least 1 breakout in the query

Query transformation:
- Drop all query stages where there are no aggregation clauses until the last one.
- Remove all aggregation, breakout, sort, limit, field clauses
- Add filters for every breakout `dimensions` using this logic https://github.com/metabase/metabase/blob/0624d8d0933f577cc70c03948f4b57f73fe13ada/frontend/src/metabase-lib/queries/utils/actions.js#L99
- If there is a selected column (cell only), extract filters associated with this aggregation column. It could be built-in operators (SumIf) or Metrics with filters. Add these filters to the query.

Question transformation:
- Set display "table"

### zoom

Object details drill for PK columns when there is a single PK column available.

Implementation:
https://github.com/metabase/metabase/blob/50208950907cb68f997562e67a24ceac4b81e1de/frontend/src/metabase-lib/queries/drills/object-detail-drill.ts#L111

Entry points:
- Cell

Requirements:
- There is only on PK column available in returned columns
- Selected column is not a FK
- Selected column is either a FK OR the query has no aggregations (in this case the PK column should be used instead of the selected column)
- The value for the PK column (which can be different to selected column) in the data row is not `null`.

Query transformation:
- None/identity

Question transformation:
- None

### zoom-in.binning

"Zoom" transform for numeric (including location) columns.

Implementation:
https://github.com/metabase/metabase/blob/e0ac6bc808649dd33bcd837513017952df5db096/frontend/src/metabase-lib/queries/utils/drilldown.js#L363

Entry points:
- Cell
- Pivot cell
- Legend item

Requirements:
- `dimensions` have a numeric column with a binning strategy applied. It can be the default one ("Auto"). Only the first matching column would be used in query transformation.

Query transformation:
- Remove breakouts for `dimensions`. Please note that with regular cells and pivot cells it would mean removing all breakouts; but with legend item clicks it would remove the breakout for the legend item column only.
- Add a filter based on columns and values from `dimensions`. Take temporal units and binning strategies into account https://github.com/metabase/metabase/blob/0624d8d0933f577cc70c03948f4b57f73fe13ada/frontend/src/metabase-lib/queries/utils/actions.js#L99
- Add a breakout based on the numeric column (from requirements). For location columns, use the binning strategy that is 10x more granular (e.g. `Every 1 degree` -> `Every 0.1 degrees`). For numeric columns, use the default binning strategy ("Auto").

Question transformation:
- Set default display

### zoom-in.geographic

"Zoom" transform for different geo semantic types.

Implementation:
https://github.com/metabase/metabase/blob/e0ac6bc808649dd33bcd837513017952df5db096/frontend/src/metabase-lib/queries/utils/drilldown.js#L350

Entry points:
- Cell
- Pivot cell
- Legend item

Possible transformations:
- Country -> State
- Country -> LatLon(10)
- State -> LatLon(1)
- City -> LatLon(0.1)
- LatLon -> LatLon

Query transformation follows rules from other `zoom-in` transforms, however new breakout columns are handled differently for each type.
- Country -> State. If a column with `type/State` semantic type exists, add a filter based on the selected country and breakout by State.
- Country -> LatLon(10). If there is no `type/State` column available but there are `type/Latitude` and `type/Longitude` columns, add a filter based on the selected country and 2 breakouts (latitude and longitude) using "Every 10 degrees" binning strategy.
- State -> LatLon(1). Add a filter based on the selected state and 2 breakouts (latitude and longitude) using "Every 1 degree" binning strategy.
- City -> LatLon(0.1). Add a filter based on the selected city and 2 breakouts (latitude and longitude) using "Every 0.1 degrees" binning strategy.
- LatLon -> LatLon. If the binning strategy is more greater than every 20 degrees, change it to 10 degrees. Otherwise divide the value by 10 and use it as the new binning strategy.

Question transformation:
- Set default display

### zoom-in.timeseries

"See this month by weeks" type of transform. 

Implementation:
https://github.com/metabase/metabase/blob/e0ac6bc808649dd33bcd837513017952df5db096/frontend/src/metabase-lib/queries/utils/drilldown.js#L340

Entry points:
- Cell
- Pivot cell
- Legend item

Requirements:
- `dimensions` have a date column with `year`, `quarter`, `month`, `week`, `day`, `hour` temporal unit. For other units, or when there is no temporal bucketing this drill cannot be applied. Changing `hour` to `minute` ends the sequence. Only the first matching column would be used in query transformation.
- `displayInfo` returns `displayName` with `See this {0} by {1}` string using the current and the next available temporal unit.

Query transformation:
- Remove breakouts for `dimensions`. Please note that with regular cells and pivot cells it would mean removing all breakouts; but with legend item clicks it would remove the breakout for the legend item column only.
- Add a filter based on columns and values from `dimensions`. Take temporal units and binning strategies into account https://github.com/metabase/metabase/blob/0624d8d0933f577cc70c03948f4b57f73fe13ada/frontend/src/metabase-lib/queries/utils/actions.js#L99
- Add a breakout based on the date column (from requirements), using the next (more granular) temporal unit.

Question transformation:
- Set default display

**Comment by camsaul** [comment]
See also #33730

**Comment by camsaul** [comment]
Another dimension we need to consider: we should check that all drills that deal with binning work for `nil` binned values. See #36581 for example -- we need to check that the other drills like zoom-in bins and zoom-in geo handle nil values as well

**Comment by bshepherdson** [comment]
Another dimension to consider: see #38034 for a model-only issue. There are quirks of metadata for models, especially around joins, so that should be tested. Both MBQL models and SQL models with metadata added.

**Comment by bshepherdson** [comment]
When the final two PRs land, this is all done aside from the two known issues which are separately filed.

Final PRs: 
- #38297
- #38472

Known issues:
- #38471
- #36659
