### ISSUE TITLE
[Epic] [dc.js Migration] Static Scatter Plot

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#36288]
```[tasklist]
### Features
- [ ] https://github.com/metabase/metabase/issues/35800
- [ ] https://github.com/metabase/metabase/issues/35802
- [ ] https://github.com/metabase/metabase/issues/35811
- [ ] https://github.com/metabase/metabase/issues/36289
- [ ] https://github.com/metabase/metabase/issues/36290
```

```[tasklist]
### Regressions from old implementation
- [ ] https://github.com/metabase/metabase/issues/36584
- [ ] https://github.com/metabase/metabase/issues/36588
```
