### ISSUE TITLE
[Epic] [dc.js Migration] Static Waterfall Chart

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#36296]
```[tasklist]
### Features
- [ ] https://github.com/metabase/metabase/issues/35810
- [ ] https://github.com/metabase/metabase/issues/36833
- [ ] https://github.com/metabase/metabase/issues/36834
- [ ] https://github.com/metabase/metabase/issues/36835
- [ ] https://github.com/metabase/metabase/issues/35801
- [ ] https://github.com/metabase/metabase/issues/35812
- [ ] https://github.com/metabase/metabase/issues/36297
- [ ] https://github.com/metabase/metabase/issues/36299
- [ ] https://github.com/metabase/metabase/issues/36828
- [ ] https://github.com/metabase/metabase/issues/36829
```
