### ISSUE TITLE
[Epic] [dc.js Migration] Dynamic Combo Chart

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#36291]
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/36183
- [ ] https://github.com/metabase/metabase/issues/35793
- [ ] https://github.com/metabase/metabase/issues/36293
- [ ] https://github.com/metabase/metabase/issues/35795
- [ ] https://github.com/metabase/metabase/issues/35797
- [ ] https://github.com/metabase/metabase/issues/35781
- [ ] https://github.com/metabase/metabase/issues/36292
- [ ] https://github.com/metabase/metabase/issues/36294
```
