### ISSUE TITLE
[Epic] Optimize build at CI

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#36336]
**Links**

Master issue for dropping unnecessary work at CI during making a build. So far my observations are:

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/36338
- [ ] https://github.com/metabase/metabase/issues/42714
- [ ] https://github.com/metabase/metabase/pull/46225
- [x] Deduplicated dependencies in yarn.lock to speed up node_modules installation
- [x] `yarn` should always be called with `--frozen-lockfile` at ci, but because of scripts from package.json, we run just `yarn` multiple times during the build
- [ ] https://github.com/metabase/metabase/issues/47227
```

**Comment by iethree** [comment]
Some prior art, for context:
esbuild: https://github.com/metabase/metabase/pull/22409
esbuild revert: https://github.com/metabase/metabase/pull/23679
swc attempt: https://github.com/metabase/metabase/pull/29628
