### ISSUE TITLE
Default dashboards to a fixed width to give creators a more predictable canvas

### ISSUE THREAD

**Issue by cdeweyx** [metabase/metabase#36358]
## Context
[Product doc](https://www.notion.so/Default-dashboards-to-a-max-width-to-give-creators-a-more-predictable-canvas-0a4f5b03fcba42f59752a6c41c453ebb)
Epic: https://github.com/metabase/metabase/issues/36010
Non-blocking milestones of this feature: https://github.com/metabase/metabase/issues/38446

---
## Tasks

**Dashboards Needing Changes**
1. Full-App
2. Static Embedding (`PublicDashboard`)
3. X-Rays (`AutomaticDashboardApp`)

---
#### Milestone 1
**BE**
- https://github.com/metabase/metabase/pull/38247
  - [x] (BE) Create new `width` setting on dashboard object with 2 options: `"full" | "fixed"`
  - [x] (BE) Create migration to set all existing dashboards to `width = "full"`

**FE**
- https://github.com/metabase/metabase/pull/38377
  - [x] (FE) Create `width` setting toggle for changing between `"full"` and  `"fixed"`. This toggle should only be exposed in **edit mode**.
    - `"full"` means `On`
    - **(default option)** `"fixed"` means `Off`
  - [x] (FE) Dashboard grid scaling
    - [x] When `width = "full"`, dashboard grid should auto-scale to the full-width available
    - [x] When `width = "fixed"`, dashboard grid should remain at the fixed width until it is the size of the viewport and then should responsively resize until mobile view
    - [x] Both options should condense to one column when the normal mobile breakpoint is reached

---
#### Milestone 2

- https://github.com/metabase/metabase/pull/38450
  - [x] (FE) Collaborate with design to spec out new dash-card minimum and default sizes (because the new fixed-width may lead to the current defaults becoming nonsensical).

---
#### Milestone 3
- https://github.com/metabase/metabase/pull/38585
  - [x] Add fixed width behavior to dashboard filters
    - [x] Make sure dashboard sidebars still stay fixed to the edge of the viewport
- https://github.com/metabase/metabase/pull/38574
  - [x] Flip the order of tabs and filters in public dashboards

**Comment by JesseSDevaney** [comment]
The rest of the work for this feature is now being tracked in a non-blocking issue
- https://github.com/metabase/metabase/issues/38446
