### ISSUE TITLE
[Epic] Browse models

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#36368]
**Links**
- [product doc on alignment for next steps](https://www.notion.so/metabase/Alignment-on-direction-for-Browse-Data-Models-v0-2-dbc94b4f013f4f59be309728f89bf143)
- [original product doc](https://www.notion.so/metabase/Bring-models-into-Browse-Data-and-make-it-easy-to-find-a-starting-point-a170b6815bc4405e98bff5032d870d87)
- branch: `models-in-browse-data` (#37707) and several downstream branches

```[tasklist]
- [x] Initial porting and tidying of files (https://github.com/metabase/metabase/pull/38107)
- [x] Semantic cleanup of e2e files (https://github.com/metabase/metabase/pull/38126)
- [x] Make two tabs in the browse data page (https://github.com/metabase/metabase/pull/37707)
- [x] Give the models tab an empty-list message ("No models here yet") (https://github.com/metabase/metabase/pull/37707)
- [x] Add one dummy model to the model tab, correctly styled (https://github.com/metabase/metabase/pull/37707)
- [x] Populate model tab with models from the backend (https://github.com/metabase/metabase/pull/37707)
- [x] Organize models by parent collection (https://github.com/metabase/metabase/pull/37707)
- [x] Add loading indicator to model list (https://github.com/metabase/metabase/pull/37707)
- [x] Add image to empty-list message (https://github.com/metabase/metabase/pull/37707)
- [x] Ensure that design is responsive (https://github.com/metabase/metabase/pull/37707)
- [x] Separate URLs per tab (#https://github.com/metabase/metabase/pull/37707)
- [x] Exclude models in personal collections
- [x] Ensure clicking the models goes to the right place (https://github.com/metabase/metabase/pull/37707)
- [x] Add tests
- [x] Use abbreviated relative time strings like 30min, 20h, 10d
- [x] Clicking on the model should take you to the model “explore” url
- [x] Make styles exactly right
- [x] Bring breadcrumbs inside Database tab
- [x] Add a white background on the Browse Data header, which will require changing the deep structure of the page (#37707)
- [x] Make the database box-shadow match the model box shadow
- [x] Remember last active tab (as described in product doc) (#38291)
- [x] Add verified badges to model cards
- [x] Fix model description overflow
- [x] Fix overwide collection header link
- [x] Make cards look more cards on collections (#38518)
- [x] Elevate Browse data link in the side nav (#38518)
- [x] Add a banner reading, "Models help curate data to make it easier to find answers to questions all in one place." (#38261)
- [x] Allow user to filter models by verification status (#38661)
```

```[tasklist]
## Follow-up work (post 49RC1)
- [x] Allow user to expand/collapse groups of models (#38704)
- [x] Add context menus to the models
```
```[tasklist]
### Future stuff
- [x] Add snowplow events that track clicks on models and tables (https://github.com/metabase/metabase/pull/37923)
- [x] Localize relative time strings with context for translators (#38114)
- [x] Use last initial not full last name in last edited info (this may require a change to the backend) (#38166)
- [x] Introduce virtualization for smoother scrolling (https://github.com/metabase/metabase/pull/37818)
```

```[tasklist]
### The Restoration
- [x] Restore models in browse data https://github.com/metabase/metabase/pull/40633
```

**Comment by rafpaf** [comment]
New work on Browse models is tracked in this epic: https://github.com/metabase/metabase/issues/41590
