### ISSUE TITLE
[Epic] Let admins delete previous CSV uploads and their underlying table

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#36369]
**Links**
- product doc: [link](https://www.notion.so/metabase/Let-admins-delete-previous-CSV-uploads-and-their-underlying-table-843a48623b474010a8886ee93740bde1)
- eng doc: _link to technical design doc, if any_
- feature branch: `branch-name` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_
- issue links: _related issues if any_

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/41114
- [ ] https://github.com/metabase/metabase/issues/41118
- [ ] https://github.com/metabase/metabase/issues/42069
- [ ] https://github.com/metabase/harbormaster/issues/4917
```

Closes
https://github.com/metabase/metabase/issues/32566
