### ISSUE TITLE
[Epic] Make the nav sidebar more predictable and discoverable

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#36370]
**Links**
- product doc: [link](https://www.notion.so/metabase/Make-the-nav-sidebar-more-predictable-and-discoverable-b205ed974d314aa5a8f21172911a3324)
- eng doc: _link to technical design doc, if any_
- feature branch: `branch-name` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_
- issue links: _related issues if any_

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/36963
- [x] Make navbar UI match the new designs (https://github.com/metabase/metabase/pull/37821)
- [x] Handle embedding logic
- [x] Implement new heuristics for navbar
- [x] Handle case where user has a custom home page / landing page configured
- [x] Add test cases
- [x] Handle mobile hover states
- [x] Update sidebar UI
```

**Comment by sloansparger** [comment]
@luizarakaki I've just merged the last change if you want to check it out!
