### ISSUE TITLE
CollectionPicker

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#36411]
working branch:  https://github.com/metabase/metabase/tree/entity-picker/entity-store

```[tasklist]
### Tasks
- [x] Style Mantine NavLink
- [x] Create Building Block UI item list component
- [x] loads path to selected collection
- [x] handles personal collections
- [x] handle snippet collections
- [x] option: hide personal collections
- [x] handle "all personal collections"
- [x] handles adding a new collection
- [x] use entity cache for collection item fetching
- [x] add search functionality
- [x] tabs support
- [x] handle snap-to-right scroll
- [x] make collectionPicker the top level component
- [x] handles picking collections where a user is missing permissions on parent collections
- [x] make UI components modular and exportable
- [x] need a new entry point button that doesn't look like a dropdown (needs design)
- [x] improve all personal collection fetching performance
- [x] handle read-only collections in search (need can_write hydrated)
- [x] handle verified item icons
- [x] create e2e test helpers for new entity picker
- [x] virtualize item list
- [x] update existing e2e tests that pick collections
- [x] unit tests
- [x] add new e2e tests to fully cover new picker + search
- [x] Make sure there are no regression from the changes in epic #34733 (hide personal items on shared dashboards)
- [x] entities copied/modified from metabase analytics should default to saving in “custom reports”
- [ ] itemlist: scroll pre-selected item into view
```
