### ISSUE TITLE
[Epic] Change the default access of new added databases and groups

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#36428]
**Links**
- product doc: [link](https://www.notion.so/metabase/Change-the-default-access-of-new-added-databases-889d36bf79ce4a798a93148a8b992c0f?pvs=4)
- eng doc: _link to technical design doc, if any_
- feature branch: `branch-name` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_
- issue links:
- https://github.com/metabase/metabase/issues/6735

Depends on the Split data access project

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/40869
- [ ] https://github.com/metabase/metabase/pull/41323
- [ ] https://github.com/metabase/metabase/issues/41701
- [ ] https://github.com/metabase/metabase/issues/42592
```

**Comment by ignacio-mb** [comment]
@luizarakaki adding v50 milestone
