### ISSUE TITLE
[Epic] Enable saving questions directly to dashboards and make this the default path

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#36430]
**Links**
- product doc: [link](https://www.notion.so/metabase/Enable-saving-questions-directly-to-dashboards-and-make-this-the-default-path-a84be6e0540241189b251401fb35ca91?pvs=4)
- eng doc: _link to technical design doc, if any_
- feature branch: `branch-name` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_
- issue links: _related issues if any_

```[tasklist]
### BE Tasks
- [ ] https://github.com/metabase/metabase/issues/38205
- [ ] When we move dashboards, we also move their dependent cards
- [ ] When we archive dashboards, we also archive their dependent cards
- [ ] When we duplicate dashboards, we also correctly duplicate their dependent cards (aka change dashboard_id)
- [ ] Dashboard questions appear in search, but it returns the dashboard, not the question
- [ ] Hide dependent cards in collection endpoints
- [ ] Prevent the dashboard dependent card to be as a model
- [ ] Prevent the dashboard dependent card to be as a sandbox
- [ ] Prevent the dashboard dependent card to be as the starting point for another query (should not come back in the "Saved Questions" data sources option)
- [ ] Prevent the dashboard dependent card inside a native query with the {{#\1234}} syntax
```

**Comment by camsaul** [comment]
I think you're missing some things here, for example we need code preventing you from using one of these Dashboard-dependent Cards:
   - as a Model
   - as a sandbox
   - as the starting point for another query (should not come back in the "Saved Questions" data sources option)
   - inside a native query with the `{{#1234}}` syntax

I think this should also be its own distinct `type` of saved question once #38074 lands

**Comment by luizarakaki** [comment]
Closed in favor of [#47326](https://github.com/metabase/metabase/issues/47326)
