### ISSUE TITLE
[Epic]Embedding settings cleanup and surface interactive embedding Quickstart 

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#36481]
**Links**
- [product doc](https://www.notion.so/metabase/Embedding-settings-cleanup-and-surface-interactive-embedding-Quickstart-7e4ed0b3a47947ac9235e53998db1280)
- [Technical doc](https://www.notion.so/metabase/Technical-plan-48425a0168cf48728bb97d08e3ee207d)
- [Testing plan](https://www.notion.so/metabase/Test-plan-062f54a005cf4f0fa949a8850d828396)

## Tasks

```[tasklist]
### Milestone "analytics" `embed-settings-cleanup-analytics`
- [ ] https://github.com/metabase/metabase/issues/36754
- [ ] https://github.com/metabase/metabase/pull/36962
```

[Embedding settings cleanup - Milestone 1](https://github.com/metabase/metabase/pull/37043)
```[tasklist]
### Milestone 1 - General embedding settings page `embed-settings-cleanup-milestone1`
- [ ] https://github.com/metabase/metabase/pull/36802
- [ ] https://github.com/metabase/metabase/pull/36857
- [ ] https://github.com/metabase/metabase/pull/36819
- [ ] https://github.com/metabase/metabase/pull/36938
- [ ] https://github.com/metabase/metabase/pull/36944
- [ ] https://github.com/metabase/metabase/pull/36949
- [ ] https://github.com/metabase/metabase/pull/37044
- [x] Review by product & design
- [x] Verify if everything in the testing plan has been tested
```

[Embedding settings cleanup - Milestone 2](https://github.com/metabase/metabase/pull/37430)
```[tasklist]
### Milestone 2 - Polishment embed-settings-cleanup-milestone2
- [ ] https://github.com/metabase/metabase/pull/37053
- [ ] https://github.com/metabase/metabase/pull/37403
- [ ] https://github.com/metabase/metabase/pull/37523
```
