### ISSUE TITLE
[Epic] Let creators make dashboard and native query filters required

### ISSUE THREAD

**Issue by NevRA** [metabase/metabase#36524]
[Product doc](https://www.notion.so/metabase/Let-creators-make-dashboard-filters-required-7ea3d7caf63545d2b713d1509e4267ad)
[Testing plan](https://github.com/metabase/metabase/issues/37520)

Follow-ups: [Required parameters: follow-ups ](https://github.com/metabase/metabase/issues/38603)

## Issues to close
- https://github.com/metabase/metabase/issues/18097
- https://github.com/metabase/metabase/issues/5320

## Milestones

```[tasklist]
### 1. Native queries
- [ ] https://github.com/metabase/metabase/pull/37800
- [ ] https://github.com/metabase/metabase/pull/37709
- [ ] https://github.com/metabase/metabase/pull/37858
- [ ] https://github.com/metabase/metabase/pull/37696
- [ ] https://github.com/metabase/metabase/pull/38006
- [ ] https://github.com/metabase/metabase/pull/38232
```
---
The two below are in fact a single milestone but I've split them out in two groups.
```[tasklist]
### 2. Dashboards & Embeddings
- [ ] https://github.com/metabase/metabase/pull/38050
- [ ] https://github.com/metabase/metabase/pull/38177
- [ ] https://github.com/metabase/metabase/pull/38203
- [ ] https://github.com/metabase/metabase/pull/38327
- [ ] https://github.com/metabase/metabase/pull/38395
```

**Comment by oleggromov** [comment]
Everything is merged.

**Comment by JeroenNelen** [comment]
Could you add an 'first value alphabetically' option for the 'default value' that becomes required after making the filter required?
Because if we want to use this in a multi-tenant setup where the filter is used for tenant-specific data
e.g. a setup where our database contains multiple schools (tenants) so we have a filter on tenant_ID but we also have a filter on 'student' and we want the student filter to be required, however when making it required it demands a default value but this default value is related to the specific tenant/school so we would need a generic option like 'first one (alphabetically)' because school A might have a student named Anna and school B will not have that student, but it could use the first one being Brian in that case (as an example).

**Comment by uladzimirdev** [comment]
@JeroenNelen this task is completed. If you have any suggestions or improvements in mind, please create a new detailed issue and we'll prioritize it
