### ISSUE TITLE
[Epic] Bigquery: Sync required partition column

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#36668]
**Links**
- product doc: https://www.notion.so/metabase/Support-scanning-on-tables-with-enforced-partitions-in-BigQuery-0b7bce07314c4f20a3ea3dedf3f723ba?pvs=4
- eng doc: https://www.notion.so/metabase/Bigquery-Sync-required-partition-key-c2943ffae97245b98dbb89fe1adf7ad4?pvs=4
- feature branch: `branch-name` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_
- issue links: https://github.com/metabase/metabase/issues/25752

**Implementation Plan**

```[tasklist]
### Milestone 1:  Sync which table requires a partition filter
- [x] Add new column `metabase_table.database_require_fitler`
- [x] Sync tables that require a filter and set `database_require_filter` to true
```
PR:  https://github.com/metabase/metabase/pull/36677

```[tasklist]
### Milestone 2: Sync partition keys
- [x] Add new column `metabase_field.database_partitioned`
- [x] Sync partition fields and set their `database_partitioned` to true
```

PR: https://github.com/metabase/metabase/pull/36892

```[tasklist]
### Milestone 3: Fix sync for tables that require a partition field
- [x] Fix sync field values
- [x] Fix fingerprint
```

PR: https://github.com/metabase/metabase/pull/37102

```[tasklist]
### ~Milestone 4: Automatically adds the required filter in notebook editor~ (out of scope)
- [x] BE part of https://github.com/metabase/metabase/issues/36983
- [ ] https://github.com/metabase/metabase/issues/37185
```

- [Ref](https://cloud.google.com/bigquery/docs/materialized-views-create#partitioned_materialized_views)

**Comment by qnkhuat** [comment]
milestone 4 is out of the scope of this project, it'll be handled as part of another project in the future.

see https://metaboat.slack.com/archives/C04DN5VRQM6/p1707140273126219?thread_ts=1705615352.637879&cid=C04DN5VRQM6

**Comment by carstenkadmos** [comment]
is there a ticket for milestone 4? still has big impact on our project.

**Comment by qnkhuat** [comment]
That's out of the scope of this project.

You can upvote this [issue](https://github.com/metabase/metabase/issues/37185) and also add a comment describing your use case. It'd help us prioritize!

As a workaround, I recommend creating a model that includes a filter by default for these tables.

**Comment by carstenkadmos** [comment]
Thank you. I did that. One more question. I have updated to 0.49.1 now and the sync does not seem to work. I started everything manually and there is no difference to before. The log also shows still the same error :

> clojure.lang.ExceptionInfo: Error executing query: com.google.cloud.bigquery.BigQueryException: Cannot query over table 'datamart.alert_kyc_failures_verified_beneficiaries_state' without a filter over column(s) 'dt', 'hr' that can be used for partition elimination
