### ISSUE TITLE
[BE] Add analytics events for embedding settings cleanup

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#36754]
[Product doc](https://www.notion.so/metabase/Embedding-settings-cleanup-and-surface-interactive-embedding-Quickstart-7e4ed0b3a47947ac9235e53998db1280)

As part of the embedding settings cleanup we need some analytics [defined here](https://www.notion.so/metabase/Embedding-settings-cleanup-and-surface-interactive-embedding-Quickstart-7e4ed0b3a47947ac9235e53998db1280?pvs=4#7bfcc600f67f40f198b0a1a1c7c4489b)

```[tasklist]
### Tasks
- [x] add `enabled-embedding` to the tracked settings
- [x] track if the users set a value for authorized_origins (just if there is a value, not the value itself) as embedding_app_origin_set
- [x] add the tracking for [Embedding disabled](https://www.notion.so/metabase/Embedding-disabled-92c0db8a464e4f1692b95ba87987d339)
```

**Comment by npretto** [comment]
Closed by https://github.com/metabase/metabase/pull/36962
