### ISSUE TITLE
[Epic] Effective caching

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#36847]
**Links**
- arc: [Cache arc](https://www.notion.so/metabase/Cache-arc-cdfddc99fbea40339679c6adf9948e34)

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/37729
- [ ] https://github.com/metabase/metabase/issues/38434
- [x] Log cache settings changes to audit_log
- [ ] https://github.com/metabase/metabase/pull/40512
- [ ] https://github.com/metabase/metabase/issues/40548
- [ ] https://github.com/metabase/metabase/issues/41126
```
