### ISSUE TITLE
[Epic] ECharts visualizations testing

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#36880]
This epic covers testing aspect of replacing dc.js with ECharts. The idea is not only to update existing tests but also create an extensive and bulletproof coverage for the new implementation which was previously missing.

**Links**
- [Testing strategy for viz](https://www.notion.so/metabase/Testing-strategy-c5bd82e8f2574954b990ea0a4b86fe63)
- [List of dimensions to cover](https://www.notion.so/metabase/WIP-Testing-dimensions-of-the-combo-chart-195e39a273744e3d84154f091d352b25)

```[tasklist]
### Set up visual testing for Storybook
- [ ] Investigate whether it is possible to use "reg-suit" to manage reporting and storing snapshots in S3 instead of repo
- [ ] Based on the previous step update & merge https://github.com/metabase/metabase/pull/35639
```

```[tasklist]
### Configure storybook so it renders dynamic visualizations
- [ ] Add a single story that renders any dynamic viz chart through the `Visualization` component
- [ ] Make it consume the same data as new static chart stories for ECharts
- [ ] Create a component for storybook that renders both dynamic and static viz side by side from a provided json with data
```

```[tasklist]
### Add tests
- [ ] Add extensive visual tests on every dimension listed in the attached notion doc
- [ ] Add unit tests on the data transformation code
```

```[tasklist]
### Update old tests
- [ ] Update existing E2E tests
- [ ] Update existing unit tests
```

```[tasklist]
### Drop Percy
- [ ] Remove Percy tests
- [ ] Cancel Percy subscription
```
