### ISSUE TITLE
[Epic] Parse SQL

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#36911]
[arc for now](https://www.notion.so/metabase/Parse-SQL-arc-16c8b01aabd94a50be90042f965d51db)

## :ballot_box_with_check:  Milestone 1: Basic Lineage

- [x] Spin out a new library that can be used from within core Metabase
- [x] #38924
- [x] #38925
- [x] #38926
- [x] #39950 
- [x] #40247
- [x] https://github.com/metabase/macaw/issues/15

## :ballot_box_with_check:  Milestone 2: Finish exposing stale queries (Query Validator)

- [x] #39954
- [x] #39953
- [x] #41242
- [x] #41400

## :ballot_box_with_check: Milestone 3: Sanitization

- [x] #41115

## :ballot_box_with_check: Milestone 3½: Lineage operational cleanup

- [x] https://github.com/camsaul/toucan2/issues/129
- [x] Once the Toucan2 bug is fixed, move the hooks from #39707 into `after-update` instead of `before-update`
- [x] #39998
- [x] #41163 

### Part A: Name-matching

- [x] Intelligently handle case when matching columns/tables
- [x] Intelligently handle quoting when matching columns/tables
- [x] Intelligently handle DB schemas when matching tables/columns

### :ballot_box_with_check: Part B: Query Components (lol)

- [x] https://github.com/metabase/macaw/issues/19

### :ballot_box_with_check: Part C: Miscellaneous

- [x] https://github.com/metabase/macaw/issues/14
- [x] Confirm that it doesn't matter that Macaw is dialect-agnostic

## :ballot_box_with_check: Milestone 5A: Query rewriting, simple version

- [x] Let columns be renamed
- [x] Let tables be renamed
- [x] Let schemas be renamed
- [x] Document it all

## Milestone 5B: Query rewriting, with template tags

[Here](https://www.notion.so/metabase/Query-Renaming-Steps-bbed645151fe41b4859c99f9a866cd21) is a Notion doc with some technical details, inspired by an earlier chat centered on [this](https://www.notion.so/metabase/tt-Query-Renaming-Plan-494fd4f7ddee4cf0a93b01a3e8418e14) Notion doc.

- [x] https://github.com/metabase/macaw/issues/32
- [x] https://github.com/metabase/macaw/issues/34
- [x] https://github.com/metabase/metabase/issues/43096
- [x] #42580
- [x] #42581
- [x] #42582
- [x] #42648
- [x] #42583
- [x] #43291

## Milestone X: Misc. bookkeeping
- [x] #43517

**Comment by darksciencebase** [comment]
closing in favor of smaller tracking issues
