### ISSUE TITLE
Help white-labeling admins remove links to metabase.com outside of admin settings

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#36966]
**Links**
- [product doc](https://www.notion.so/metabase/Help-white-labeling-admins-remove-any-references-to-Metabase-outside-of-admin-settings-f5ddbca732ff400ab858d9e173562b0b?d=fe1fe3f2da854da8aa4260b81a37d19e#1793a7b1b07b427684a46d9413ff0856)
- [Technical design doc](https://www.notion.so/metabase/Tech-Remove-Metabase-references-outside-of-admin-settings-f88ff0fa8f574d6393c6fe5a15911b0a?d=b6c059f19e7e44d58c440a5181a4fb47#c600388e76734c9d9c2af302004b4b3f)
- [Testing plan](https://www.notion.so/metabase/WIP-Testing-Plan-Remove-Metabase-references-outside-of-admin-settings-f3c254867cf44fb3952ab4c9e677e6cf)
- feature branch: `tbd` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_

```[tasklist]
### Milestone 1
- [x] List all places where we want to remove Metabase links outside admin settings https://github.com/metabase/metabase/commit/43e0574148/
- [ ] https://github.com/metabase/metabase/pull/37076
```

```[tasklist]
### Milestone 2
- [ ] https://github.com/metabase/metabase/pull/37738
- [x] Analytics (done in https://github.com/metabase/metabase/issues/37656)
- [ ] [optional] implement an abstraction that deals with removing Metabase links
```

**Comment by WiNloSt** [comment]
I'll close the epic since Milestone 2 doesn't change any behavior in the application. It just changes the developer experience.
