### ISSUE TITLE
[Epic] Metrics v2

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#37335]
# Links
- product docs:
  - [:star: Create the new Metric entity](https://www.notion.so/metabase/Create-the-new-Metric-entity-6539b2977d764948b46ee7b629969bbd#2f7e521583864a30b160fb07034edea0)
  - [:chains: Sequence plan for metrics v2](https://www.notion.so/metabase/Sequence-plan-for-metrics-v2-c668089cdc394406a282770c7538d74b)
  - [Metrics v2 technical design docs](https://www.notion.so/metabase/Metrics-v2-3349548e8b9c4bb8b51b8458ce1dbde5)
  - [Provide an upgrade path for organic metric definitions](https://www.notion.so/metabase/Provide-an-upgrade-path-for-organic-metric-definitions-fcd6a4e1bb3249ffacf442009404d031)
  - [Deprecate Metrics 1.0](https://www.notion.so/metabase/Deprecate-Metrics-1-0-9023c808fc4448dcb47b168ede2bdb0f?pvs=25)
- [Figma](https://www.figma.com/file/17Z8b1uEdcrtpP8rVHaPAS/Metrics-2.0?type=design&node-id=611-9029&mode=design&t=uOCGLa9ggM4DGJ4z-4)
  - [Make Metrics in collections shine](https://www.figma.com/file/pznXbRDT8BMZmACzcPjinw/Make-Metrics-in-collections-shine?type=design&mode=design&t=Rnx3iODBeHB3LdqF-0)
- feature branch: `metrics-v2` (integration PR: #38457)

# Implementation Plan

## 1. Creating new metrics

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/41017
- [ ] https://github.com/metabase/metabase/issues/41016
```

## 2. Ad-hoc questions based on metrics
```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/41626
- [ ] https://github.com/metabase/metabase/issues/41015
- [ ] https://github.com/metabase/metabase/issues/41014
- [ ] https://github.com/metabase/metabase/issues/41013
- [ ] https://github.com/metabase/metabase/issues/41011
- [ ] https://github.com/metabase/metabase/issues/41012
- [ ] https://github.com/metabase/metabase/issues/41200
```

## 3. New questions based on Metrics
```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/41520
- [ ] https://github.com/metabase/metabase/issues/41628
- [ ] https://github.com/metabase/metabase/issues/41184
- [ ] https://github.com/metabase/metabase/issues/41009
- [ ] https://github.com/metabase/metabase/issues/41010
- [ ] https://github.com/metabase/metabase/issues/41568
```

## 4. Allow joins on Metrics

```[tasklist]
- [x] https://github.com/metabase/metabase/issues/41899
- [ ] https://github.com/metabase/metabase/issues/41709
- [ ] https://github.com/metabase/metabase/issues/41917
```

## 5. Blocks merging
```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/42130
- [ ] https://github.com/metabase/metabase/issues/42462
- [ ] https://github.com/metabase/metabase/issues/42470
- [ ] https://github.com/metabase/metabase/issues/42742
- [ ] https://github.com/metabase/metabase/issues/42598
- [ ] https://github.com/metabase/metabase/issues/42278
- [ ] https://github.com/metabase/metabase/issues/42656
- [ ] https://github.com/metabase/metabase/issues/42463
- [ ] https://github.com/metabase/metabase/issues/42356
- [ ] https://github.com/metabase/metabase/issues/42176
- [ ] https://github.com/metabase/metabase/issues/42168
- [ ] https://github.com/metabase/metabase/issues/41935
- [ ] https://github.com/metabase/metabase/issues/42060
- [ ] https://github.com/metabase/metabase/issues/41927
- [ ] https://github.com/metabase/metabase/issues/42618
- [ ] https://github.com/metabase/metabase/issues/41933
- [ ] https://github.com/metabase/metabase/issues/41936
- [ ] https://github.com/metabase/metabase/issues/41934
- [ ] https://github.com/metabase/metabase/issues/41744
- [ ] https://github.com/metabase/metabase/issues/41743
- [ ] https://github.com/metabase/metabase/issues/42028
- [ ] https://github.com/metabase/metabase/issues/41937
- [ ] https://github.com/metabase/metabase/issues/42471
- [ ] https://github.com/metabase/metabase/issues/41932
- [ ] https://github.com/metabase/metabase/issues/41993
- [ ] https://github.com/metabase/metabase/issues/42155
- [ ] https://github.com/metabase/metabase/issues/42001
- [ ] https://github.com/metabase/metabase/issues/42056
- [ ] https://github.com/metabase/metabase/issues/41929
- [ ] https://github.com/metabase/metabase/issues/41928
- [ ] https://github.com/metabase/metabase/issues/41930
```

## 6. Blocks merging - migration

- product doc: [Deprecate Metrics 1.0](https://www.notion.so/metabase/Deprecate-Metrics-1-0-9023c808fc4448dcb47b168ede2bdb0f?pvs=25)
- tech doc: [Metrics v2 migration](https://www.notion.so/metabase/Tech-Metrics-v2-migration-f5944676c66f40fd9284aba6c3604367)

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/37982
- [ ] https://github.com/metabase/metabase/issues/42186
- [ ] https://github.com/metabase/metabase/issues/42187
- [ ] https://github.com/metabase/metabase/issues/42188
- [ ] https://github.com/metabase/metabase/issues/42189
- [ ] https://github.com/metabase/metabase/issues/42190
- [ ] https://github.com/metabase/metabase/issues/42191
```

## 7. Does not block merging

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/43151
- [ ] https://github.com/metabase/metabase/issues/42464
- [ ] https://github.com/metabase/metabase/issues/42893
- [ ] https://github.com/metabase/metabase/issues/41931
- [ ] https://github.com/metabase/metabase/issues/42392
- [ ] https://github.com/metabase/metabase/issues/41473
- [ ] [BE] Review Metric revisions
- [ ] https://github.com/metabase/metabase/issues/42782
- [ ] https://github.com/metabase/metabase/issues/42575
- [ ] https://github.com/metabase/metabase/issues/42237
- [ ] https://github.com/metabase/metabase/issues/42360
- [ ] https://github.com/metabase/metabase/issues/42252
- [ ] https://github.com/metabase/metabase/issues/42474
- [ ] https://github.com/metabase/metabase/issues/42607
```

**Comment by mngr** [comment]
@NevRA can we close this epic?

**Comment by NevRA** [comment]
> @NevRA can we close this epic?

Yes, let's do. Technically it's already merged
