### ISSUE TITLE
[MLv2] [FE] Use MLv2 `displayInfo` in `isStructured`, `isNative`, `isQueryEditable`

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#37389]
Previously blocked by https://github.com/metabase/metabase/issues/36973.
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/37786
- [ ] https://github.com/metabase/metabase/pull/37862
- [ ] #37805
- [ ] https://github.com/metabase/metabase/pull/37886
- [ ] https://github.com/metabase/metabase/pull/37977
```
