### ISSUE TITLE
[Epic] Optimize build time 

### ISSUE THREAD

**Issue by NevRA** [metabase/metabase#37576]
```[tasklist]
### Tasks
- [ ] Migrate FE webpack from babel-loader to the SWC loader
- [ ] Disable source maps generation on regular branches
- [ ] Optimise CLJS build
- [ ] Optimise startup time of shadow-cljs compiler
- [ ] Optimise driver build
```
