### ISSUE TITLE
Migrate FE webpack from babel-loader to the SWC loader

### ISSUE THREAD

**Issue by NevRA** [metabase/metabase#37577]
The current webpack build takes about **70-80** seconds on CI, and this time can be almost halved if we stop using babel-loader.
The main problem is that we use a plugin for Emotion, which also needs to be migrated, and in the long term, we should consider moving away from Emotion.

Here is [PoC PR](https://github.com/metabase/metabase/pull/37054) of the SWC loader you can use as the reference.
The only known issue is that we need to figure out why the Cypress tests are not running on CI. Locally, everything works fine.

```[tasklist]
### Tasks
- [ ] Investigate the issue with Cypress 
- [ ] https://github.com/metabase/metabase/issues/45905
- [ ] Remove all babel references 
- [ ] https://github.com/metabase/metabase/issues/45906
```

**Comment by paoliniluis** [comment]
related to https://github.com/metabase/metabase/issues/28779
