### ISSUE TITLE
Add anonymous usage tracking for relevant white-labeling

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#37656]
[Product doc](https://www.notion.so/metabase/Add-anonymous-usage-tracking-for-relevant-white-labeling-7201dddf161e44efa947e61c004f7d43)

This task requires adding and renaming some fields in `instance-settings` in `src/metabase/analytics/stats.clj`.

For some values, it may be needed/desirable to create helper functions such as for the [email](https://github.com/metabase/metabase/blob/ff4acb4df17b2c3316467611a250dc97f848ae0f/src/metabase/email.clj#L96-L102)

```[tasklist]
### Tasks
- [x] rename the `site_name` and `help_link` fields
- [x] `appearance_logo`
- [x] `appareance_favicon`
- [x] `apperance_loading_message`
- [x] `appearance_metabot_greeting`
- [x] `apparerance_lighthouse_illustration`
- [x] `appearance_ui_colors`
- [x] `appearance_chart_colors`
- [x] `appearance_show_mb_links`
```
