### ISSUE TITLE
Update `can-read?` and `can-write?` model methods to enforce based on the new perms API

### ISSUE THREAD

**Issue by noahmoss** [metabase/metabase#37919]
For each namespace:
* Implement `can-read?` and `can-write?` on the model to call `data-perms/database-permission-for-user` and/or `data-perms/table-permission-for-user`, to replicate the previous permissions.
* Delete the previous implementation of `mi/perms-objects-set`
* Add or update tests for the model for `can-read?` and `can-write?`
* End goal: if we delete all data perms from the `permissions` table, these models should behave the same w.r.t permissions

```[tasklist]
### Tasks
- [x] Update src/metabase/models/field.clj to new permissions mechanism
- [x] Update src/metabase/models/table.clj to new permissions mechanism
- [x] Update src/metabase/models/database.clj to new permissions mechanism
- [x] Update src/metabase/models/metric.clj to new permissions mechanism
- [x] Update src/metabase/models/segment.clj to new permissions mechanism
```
