### ISSUE TITLE
Migrate from react-sortable to DnD-Kit

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#37921]
**Links**
- Notion doc: [Link](https://www.notion.so/metabase/84-Remove-react-sortable-8c293410987a44d4a3a3c4223fa385f8)

This migration serves 2 purposes: To reduce the number of libraries used for Drag and Drop functionality, and to remove an outdated dependency that may impact our ability to update to `React 18`. This epic will serve to track progress of converting the places `react-sortable` is used, with the completion being removing it package.json.

Because library usage is isolated throughout the app, it should be possible to merge branches into master as they complete.

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/37922
- [ ] https://github.com/metabase/metabase/issues/37925
- [ ] https://github.com/metabase/metabase/issues/38092
- [ ] https://github.com/metabase/metabase/issues/38293
- [ ] https://github.com/metabase/metabase/issues/39655
```

**Comment by Anishali2** [comment]
@npfitz I can do your job with dnd-kit can you guide me through the project or where to start so I can start working on it 
If you don't know much about me let me tell you I'm working on a dnd app from 10 months and recently im working on v.2.0 of the project and I'm working on dnd-kit here is the example 
https://tapday-2.vercel.app/home/main

if you want me to showcase the version one I will but it's build in react-beautiful-dnd
