### ISSUE TITLE
[Epic] Make Archive actually usable

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#38063]
**Links**
- [product doc](https://www.notion.so/metabase/Make-Archive-actually-usable-0c155dfff4b14729be02863b5db37a7c)
- eng doc: _link to technical design doc, if any_
- feature branch: `branch-name` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_
- issue links:
  - #4013
  - #29229
  - #38646
  - #10987
  - #33180
  - #26168
  - #21341
  - #18372
  - #9555
  - #2783

```[tasklist]
### Milestone 1: Migrate trash to a collection + make it usable
- [ ] https://github.com/metabase/metabase/issues/41660
- [ ] https://github.com/metabase/metabase/issues/41661
- [x] API: Do not exclude trashed items from GET endpoints for cards, collections, or dashboards
- [x] BE: create the trash collection
- [ ] https://github.com/metabase/metabase/issues/41913
- [ ] https://github.com/metabase/metabase/issues/41914
- [ ] https://github.com/metabase/metabase/issues/41915
- [ ] https://github.com/metabase/metabase/issues/41916
- [x] FE: all users to move items in trash outside of the trash
- [x] E2E: add test coverage
- [x] FE: remap the trash collection route to just `/trash`
- [ ] https://github.com/metabase/metabase/issues/42343
- [x] Decide whether to have static trash ID, or dynamic. Implement dynamic if that's what we go with
- [x] Team bug bash
- [ ] https://github.com/metabase/metabase/issues/42301
- [ ] https://github.com/metabase/metabase/issues/42505
- [ ] https://github.com/metabase/metabase/issues/42700
- [ ] https://github.com/metabase/metabase/issues/43159
- [ ] https://github.com/metabase/metabase/issues/43494
```

```[tasklist]
### Milestone 2: Filter trashed items on search page
- [ ] https://github.com/metabase/metabase/issues/42401
```

```[tasklist]
### Milestone 3: Polish and improvements
- [ ] BE: implement a bulk archive/delete endpoint
- [x] BE: Tell frontend whether an item can be unarchived successfully
- [ ] FE: convert all trash network requests to use RTKQuery
- [ ] BE: Unbookmark items when they get archived (FE currently breaks when restoring bookmarked items)
```

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/42963
- [x] Fix pagination for the Trash
- [ ] https://github.com/metabase/metabase/issues/44708
```
