### ISSUE TITLE
[Epic] Auto-archive unused items

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#38064]
**Links**
- [product doc](https://www.notion.so/metabase/Auto-archive-unused-items-54b3b58e254a48e69b26a054c84fd944): _link to product doc_
- [eng doc](https://www.notion.so/metabase/Autotrash-fb69b98350364c0fa9d3433ba5ab2d41)
- feature branch: `branch-name` _this should be the feature branch where this work will be done in. PRs will be delivered against this branch_
- issue links: _related issues if any_

```[tasklist]
- [x] https://github.com/metabase/metabase/issues/44252 Prerequisite
- [x] https://github.com/metabase/metabase/issues/44253 Milestone 1 - Find items to auto-archive
- [ ] https://github.com/metabase/metabase/issues/46292
```
