### ISSUE TITLE
[Epic] Capture more metadata: table count, field usage, last viewed/used_at

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#38229]
Technical doc: https://www.notion.so/metabase/Accurate-fingerprint-729a720cdd4f41029a49d647fa9583b2?pvs=4
Related to https://www.notion.so/metabase/Capture-field-and-table-usage-metadata-990e99226d234d8b916478109162cd42?pvs=4

```[tasklist]
### Milestone 1: Sync table row count (Postgres only)
- [ ] https://github.com/metabase/metabase/pull/39670
- [ ] https://github.com/metabase/metabase/pull/39494
```

```[tasklist]
### Milestone 2: Count field usage
- [x] Add new `field_usage` table
- [ ] https://github.com/metabase/metabase/issues/40494
```

```[tasklist]
### Milestone 3: Capture last\_viewed\_at and last\_used\_at
- [ ] #41006 
- [ ] https://github.com/metabase/metabase/pull/41748
```

The use case for Milestone 3 is [Auto cleanup collections](https://www.notion.so/metabase/Auto-cleanup-collections-54b3b58e254a48e69b26a054c84fd944)
For this project, we need signal that an item (collection, question, model, dashboard) is irrelevant.
For dashboards, `last_viewed_at` is enough.
For questions and models, we need to know if it is used by other things (like nested questions, sandbox definition, custom field values, goals), so we are proposing a `last_used_at` property that registers everytime that item is used.

[New technical design doc](https://www.notion.so/metabase/Capturing-last_used_at-last_viewed_at-45f16ce82494477688733b05596743fb)

```[tasklist]
### Milestone 4: Capture view count for questions, models, and dashboards.
- [ ] https://github.com/metabase/metabase/pull/41840
- [ ] https://github.com/metabase/metabase/pull/41886
- [ ] https://github.com/metabase/metabase/pull/41882
```
The use case for Milestone 4 is TBD, but most likely this would be shown in collections to help users find relevant content or help rank search results. 
[Milestone 4 technical doc](https://www.notion.so/metabase/e12aa6ef472c4d6ab871f60d1947327b?v=fd15329da9594408807fc38c3a4edb7a&p=086dec987ce84759baca325399c43da5&pm=s)

**Comment by qnkhuat** [comment]
Technical doc https://www.notion.so/metabase/Accurate-fingerprint-729a720cdd4f41029a49d647fa9583b2?pvs=4
