### ISSUE TITLE
[Epic] Meet embedders at the door - minimal edition

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#38233]
**Links**
- [product doc](https://www.notion.so/metabase/Meet-embedders-at-the-door-during-setup-d291f12e5ba244ba8cf803af18f63e86)
- [eng doc](https://www.notion.so/metabase/Meet-embedders-at-the-door-v49-d60a1242b7754a1cb9a3bcdae36fafe9)
- [testing plan](https://www.notion.so/Testing-plan-for-v49-d0e68bb6c94f4ff7b37860cd5b7faa35)

This Epic is only for the reduced version that we're aiming to deliver in v49:
- Usage question during the setup
- Hiding the database setup step for people who are interested in embedding
- [Very minimal homepage](https://www.figma.com/file/UFay4YjWyUMyl23T1cXzeC/Meet-first-time-embedders-at-the-door-with-a-dashboard?type=design&node-id=1449-15934&mode=design&t=U9k8MkZGkGEEO4BF-4) with just a couple of links

***Milestone 1*** - [`meet-embedders-v1-ms1`](https://github.com/metabase/metabase/pull/38520)

```[tasklist]
### Milestone 1
- [ ] https://github.com/metabase/metabase/pull/38201
- [ ] https://github.com/metabase/metabase/pull/38267
- [ ] https://github.com/metabase/metabase/pull/38390
- [ ] https://github.com/metabase/metabase/pull/38402
- [ ] https://github.com/metabase/metabase/pull/38465
- [x] Design/Product check
- [ ] https://github.com/metabase/metabase/pull/38521
```

**Comment by npretto** [comment]
I extracted some tasks to https://github.com/metabase/metabase/issues/38556 to make it mergeable today before RC1
