### ISSUE TITLE
[MLv2] [Blocked] Migrate `canRun()` method to MLv2

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#38269]
This task cannot be fully implemented until we land https://github.com/metabase/metabase/issues/38268 into `master`.
`canRun()` currently doesn't take the required filters into account.

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/38240
- [ ] Migrate `canRun()` for the nativeQuery
- [ ] Remove `canRun()` method altogether
```
