### ISSUE TITLE
[Epic] Surface column info in places where it’d be most useful

### ISSUE THREAD

**Issue by romeovs** [metabase/metabase#38394]
Column descriptions aren’t tremendously widespread and common, in part because they’re too cumbersome to add right now (that’s why we want to [allow for editing descriptions from metadata hover cards](https://www.notion.so/metabase/Allow-for-editing-descriptions-from-metadata-hover-cards-9e213c1282cd4a5cabd54a07756b31e8)). But when they are present, they’re often useful. 

We already have a way to display all that when hovering for a moment over a column heading, but we don’t make any of that information accessible in moments when it would be most useful, like when filtering, summarizing, or joining.

In the past, we tried displaying info cards when the user hovered over a column in one of those contexts, but we found it really annoying and unexpected.

We should instead try either a smaller, predictable hover target, or a clear click target as the way to get this information to show up.

<img width="630" alt="Screenshot 2024-02-02 at 16 42 28" src="https://github.com/metabase/metabase/assets/1250185/a576c552-445e-4e84-8b04-36c4d58c1490">

**Links**
- [product doc](https://www.notion.so/metabase/Surface-column-info-in-places-where-it-d-be-most-useful-20c4a6bdc923488f88a37b49f5fbd42a)
- [eng doc](https://www.notion.so/metabase/Technical-Design-Doc-d020470e49454e9c9668f82b0f623913)
- feature branch: [38394-surface-column-info](https://github.com/metabase/metabase/tree/38394-surface-column-info)

**Implementation Plan**
```[tasklist]
### Milestone 1: Current implementation
- [ ] https://github.com/metabase/metabase/issues/38432
- [ ] https://github.com/metabase/metabase/issues/38670
```

```[tasklist]
### Milestone 2: Notebook mode
- [ ] https://github.com/metabase/metabase/issues/38698
- [ ] https://github.com/metabase/metabase/issues/38845
- [ ] https://github.com/metabase/metabase/issues/38863
- [ ] https://github.com/metabase/metabase/issues/38869
- [x] Validate the usability of the approach with product before any next steps
- [ ] https://github.com/metabase/metabase/issues/39305
- [ ] Fix middle mouse click issue on table info card
```

```[tasklist]
###  Milestone 3: Chill mode
- [ ] https://github.com/metabase/metabase/issues/38812
- [ ] https://github.com/metabase/metabase/issues/38902
- [ ] https://github.com/metabase/metabase/issues/38918
```

```[tasklist]
### Milestone 4: Native Query Editor
- [ ] https://github.com/metabase/metabase/issues/39042
- [ ] https://github.com/metabase/metabase/issues/39114
```

```[tasklist]
### Milestone 5: Dashboards
- [x] ~~Add hover card on column picker when mapping filter widgets to cards~~
```

```[tasklist]
### Milestone 6: Admin Panel
- [ ] https://github.com/metabase/metabase/issues/39240
```
