### ISSUE TITLE
Fixed width dashboards (non-blocking milestones)

### ISSUE THREAD

**Issue by JesseSDevaney** [metabase/metabase#38446]
## Context
[Product doc](https://www.notion.so/Default-dashboards-to-a-max-width-to-give-creators-a-more-predictable-canvas-0a4f5b03fcba42f59752a6c41c453ebb)
Epic: https://github.com/metabase/metabase/issues/36010
Blocking milestones of this feature: https://github.com/metabase/metabase/issues/36358

---
## Tasks

**Dashboards Needing Changes**
1. Full-App
2. Static Embedding (`PublicDashboard`)
3. X-Rays (`AutomaticDashboardApp`)

---
#### Milestone 4: Make Dashboard Header Fixed Width
- https://github.com/metabase/metabase/pull/38634
  - [x] Include the full dashboard header in the fixed width container (edit mode header is the obstacle)
    - [x] Save mode UI should still extend to the edge of the viewport

---
#### Milestone 5: Clean-up RC1 Commits
- https://github.com/metabase/metabase/pull/38678
  - [x] Clean-up new Mantine tool-tips replacing old tool-tips on dashboard header buttons
- [x] Clean-up the filters moved below tabs in public/embedded dashboards (pre-RC1 work)
  - [ ] Create an issue to track the problem of using EmbedFrame to handle multiple different embedded scenarios (dashboards, questions, actions, ...). Refactoring this to respect separation of concerns would make it easier  to understand, maintain, and develop on top of.
  - https://github.com/metabase/metabase/pull/38766
    - [x] Add sticky filters to public/embedded dashboards (related issue: #24726)
    - https://github.com/metabase/metabase/pull/38882
      - [x] Prevent parameters container from being rendered on public/embedded dashboards when no visible filters are present ([see comment](https://github.com/metabase/metabase/pull/38634#discussion_r1487418364))

---
#### Milestone 6: Setup Analytics
- https://github.com/metabase/metabase/pull/38871
- https://github.com/metabase/metabase/pull/38872
  - [x] Setup analytics to track this new settings usage
    - [Event Spec](https://www.notion.so/metabase/Dashboard-width-toggled-1b3b1e5693f44a44bf79b30fcb732a67?pvs=4)
    - [Analytics Doc](https://www.notion.so/5da1f874beda4153b4fccfa6c1e77caa?pvs=4)
  
---
#### :x: Milestone 7: Make dashboard body true fixed width w/ overflow scroll
_Left unimplemented: Value < Effort Required_
- [ ] Turn off fixed-width logic when reaching the mobile breakpoint
- [ ] Make the dashboard have true fixed width + overflow scroll when mobile breakpoint < width < 1048px
  - [ ] Need to add this functionality to Public/Embed Dashboards + X-Rays as well

---
#### Milestone Xtra: Miscellaneous Clean-up
- https://github.com/metabase/metabase/pull/38790
  - https://github.com/metabase/metabase/pull/38834
  - [x] Adjust X-Ray dashboards to use the full grid width
    - X-Rays only use 3/4 of the dashboard grid. This combined with the new fixed-width feature makes X-Ray dashboards look unpolished.
    ![image](https://github.com/metabase/metabase/assets/22608765/a4d787ca-840b-4b37-8a96-b3fc89df24cc)
- https://github.com/metabase/metabase/pull/38836
  - https://github.com/metabase/metabase/pull/38884
    - [x] Update X-Rays to respect the new default card sizes
- https://github.com/metabase/metabase/pull/38880
  - [x] Fix dashboard header margin bug ([thread](https://metaboat.slack.com/archives/C505ZNNH4/p1708059629202699))
