### ISSUE TITLE
[Epic] Improve performance of dashboards MLv2

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#38501]
Dashboard editing became extremely slow, what was described in the issue https://github.com/metabase/metabase/issues/38225

There are at least two reasons for it:
1. Not optimal frontend data flow, which triggers heavy operations and unnecessary re-rendering even after a small change
2. re-creating question on FE which leads to new instances of queries in many places which led to cache invalidation in MLv2 -> slow MLv2 calls

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/38426
- [ ] https://github.com/metabase/metabase/pull/38361
- [ ] https://github.com/metabase/metabase/pull/38360
- [ ] https://github.com/metabase/metabase/pull/38325
- [ ] https://github.com/metabase/metabase/pull/38425
- [ ] https://github.com/metabase/metabase/issues/38502
- [ ] https://github.com/metabase/metabase/pull/38375
- [ ] https://github.com/metabase/metabase/pull/38409
```

**Comment by bshepherdson** [comment]
I've added the two CLJS PRs above as well.

I also edited the description slightly to distinguish MLv2 code (ie. CLJS code running in the FE) from the BE (meaning the server). To be clear, there's no network traffic directly involved here.

**Comment by uladzimirdev** [comment]
All the related tasks are completed, the main fix is provided, other issues/PR which didn't make a significant difference were closed
