### ISSUE TITLE
Post RC1 refactors for Meet embedders

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#38556]
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/38669
- [ ] https://github.com/metabase/metabase/pull/38708
- [x] make sure the snowplow e2e tests all the events (specifically: at least app the steps)
- [ ] https://github.com/metabase/metabase/pull/38772
```
