### ISSUE TITLE
Required parameters: follow-ups 

### ISSUE THREAD

**Issue by oleggromov** [metabase/metabase#38603]
Once the [[Epic] Let creators make dashboard and native query filters required](https://github.com/metabase/metabase/issues/36524) lands, we need to do a bunch of follow-ups.

## Milestone 3
- [x]  https://github.com/metabase/metabase/pull/39159
## Core updates
Please leave these to @oleggromov 

- [x] https://github.com/metabase/metabase/pull/38906
- [x] https://github.com/metabase/metabase/pull/38997
- [x] https://github.com/metabase/metabase/pull/39128

## UI/UX updates
These mostly depend on the core updates above, because it's impractical to update the currently convoluted components (in particular, `ParameterValueWidget`) _before_ we change them to use Mantine.

- [x] https://github.com/metabase/metabase/pull/38468
- [x] https://github.com/metabase/metabase/pull/39068
- [x] increase gap between the toggle and input by 4px - addressed in https://github.com/metabase/metabase/pull/38906
- [x] https://github.com/metabase/metabase/pull/39206

**Comment by oleggromov** [comment]
This round of follow-ups is merged.
The next is https://github.com/metabase/metabase/issues/39211
