### ISSUE TITLE
[Epic] SCIM support

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#38621]
Closes https://github.com/metabase/metabase/issues/18319
[Product doc](https://www.notion.so/metabase/Support-SCIM-for-user-provisioning-and-deprovisioning-a41d6d08e965498e93fdbce99ba1d301)
[Figma](https://www.figma.com/design/E42ezp6P3kY4PJj0r5tIOM/Support-SCIM-for-user-provisioning-and-deprovisioning?node-id=2095-1152&t=7TcfCvDuJm6fcmgB-1)

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/41816/
- [x] [BE] Add `scope` to API keys and add support for a `scim` scope
- [x] [BE] Authenticate SCIM endpoints with the `scim`-scoped API key
- [x] [BE] Implement SCIM User endpoints
- [x] [BE] Imlpement SCIM Group endpoints
- [x] [BE] Filter out SCIM token from API Keys endpoints
- [ ] https://github.com/metabase/metabase/issues/43132
- [x] Test the implementation of the SCIM spec using Okta's test suite
```
