### ISSUE TITLE
[Epic] Improve API Data Fetching

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#38686]
[Frontend RFC](https://www.notion.so/metabase/85-Use-a-Real-data-fetching-caching-library-afb42a65e79f449982414639668e2b06#2a6aa6c77c8f4f6995ee70907b9b88ea)

```[tasklist]
### Research / PoC Phase
- [x] Research major data fetching libraries
- [x] Prototype 1 or more libraries using for api requests for entities and non-entities
- [ ] https://github.com/metabase/metabase/issues/39481
- [ ] https://github.com/metabase/metabase/issues/39482
- [x] Present proposal to frontend guild (march 13)
```
### Proposal

[We should use RTK Query](https://www.notion.so/metabase/Picking-a-real-data-fetching-library-d38077b06b9d4b09ba15db09ad608be0)

### Goals

- have a consistent, easy-to-use, hook-based way to make cached (or non-cached) API queries
- use a library that is well maintained and documented
- find something that will eventually play nicely with our entity store

### Possible Libraries

- [SWR](https://swr.vercel.app/)
- [Tanstack Query](https://tanstack.com/query/latest)
- [RTK Query](https://redux-toolkit.js.org/rtk-query/overview)

```[tasklist]
### Implementation Phase
- [ ] https://github.com/metabase/metabase/pull/39092
- [ ] https://github.com/metabase/metabase/pull/40043
- [ ] https://github.com/metabase/metabase/pull/39179
- [ ] https://github.com/metabase/metabase/pull/39273
- [ ] https://github.com/metabase/metabase/pull/39270
- [ ] https://github.com/metabase/metabase/pull/39266
```

**Comment by iethree** [comment]
closing in favor of the migration epic: https://github.com/metabase/metabase/issues/40788
