### ISSUE TITLE
BE - Support metrics in MLv2

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#38724]
```[tasklist]
### Tasks
- [ ] Make sure the metadata needed for metrics is available
- [ ] Adjust API endpoints to return metrics
- [ ] Expose metrics columns in visible-columns and retrurned-columns
- [ ] Make sure filters on metric columns can be created
- [ ] Make sure the metric aggregation appears by default
- [ ] Make sure the aggregation can be edited
- [ ] Make sure the question is savable
```
