### ISSUE TITLE
[Epic] Replace CSV data

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#38788]
[product doc, milestone 2](https://www.notion.so/metabase/Allow-append-and-replace-to-existing-CSV-uploads-f1f13864632d4cfd83522fce762890eb?pvs=4#7e36dd9a56434f71941530ae516788f1)
[technical design doc](https://www.notion.so/metabase/Tech-Replace-uploaded-table-fbf87ad7c0a7485bb74abd66b7d658a5?pvs=4)

BE: BEC
FE: Admin/Webapp
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/40364
- [ ] https://github.com/metabase/metabase/issues/40365
- [ ] https://github.com/metabase/metabase/issues/40368
- [ ] https://github.com/metabase/metabase/issues/40469
- [ ] https://github.com/metabase/metabase/pull/40610
```

Closes:
https://github.com/metabase/metabase/issues/33272
