### ISSUE TITLE
[Epic] Remove global plain CSS styles

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#38811]
Relates to https://github.com/metabase/metabase/issues/33854

**Links**
- Eng doc: [Link](https://www.notion.so/metabase/83-Prepare-global-css-for-migration-to-css-modules-4ab29b8589b545e0960bf032d24a11a9)
- Problem description: [Link](https://www.notion.so/metabase/Embedding-SDK-8103306366be4f0786b489ad2324235c?pvs=4#83440af594a941ee8b14aaa1e1ac742b)

**Implementation Plan**

```[tasklist]
### Milestone 1 - Migrate global CSS to CSS modules
- [x] https://github.com/metabase/metabase/pull/39020 - Migrate global CSS to CSS modules - Add ":global" for all empty global styles; Remove ":local"
- [x] https://github.com/metabase/metabase/pull/39020 - Configure css-loader to have local scope by default
- [x] https://github.com/metabase/metabase/pull/39020 - Update css-loader dependency
- [x] https://github.com/metabase/metabase/pull/39020 - Find a way to isolate global third-party stylesheets - leaflet, ace-builds, tippy.js ...
- [x] https://github.com/metabase/metabase/pull/39220 - Remove unused classes
- [ ] https://github.com/metabase/metabase/pull/39239
```

```[tasklist]
### Milestone 2 - Get rid of global styles in Embedding SDK components
- [ ] https://github.com/metabase/metabase/issues/39123
- [ ] https://github.com/metabase/metabase/pull/39324
- [ ] https://github.com/metabase/metabase/pull/40103
- [ ] https://github.com/metabase/metabase/pull/40106
- [ ] https://github.com/metabase/metabase/pull/40007
- [ ] https://github.com/metabase/metabase/issues/40128
- [ ] https://github.com/metabase/metabase/issues/40127
- [ ] https://github.com/metabase/metabase/issues/40349
- [ ] https://github.com/metabase/metabase/issues/40722
- [ ] https://github.com/metabase/metabase/issues/40904
- [ ] https://github.com/metabase/metabase/issues/40496
- [ ] https://github.com/metabase/metabase/issues/40129
- [ ] https://github.com/metabase/metabase/issues/40910
- [ ] https://github.com/metabase/metabase/issues/41019
- [ ] https://github.com/metabase/metabase/issues/41077
- [ ] https://github.com/metabase/metabase/issues/40231
- [ ] https://github.com/metabase/metabase/issues/41256
- [ ] https://github.com/metabase/metabase/issues/41239
- [ ] https://github.com/metabase/metabase/issues/40357
- [ ] https://github.com/metabase/metabase/issues/40521
- [ ] https://github.com/metabase/metabase/issues/40444
- [ ] https://github.com/metabase/metabase/issues/40562
- [ ] https://github.com/metabase/metabase/issues/40565
- [ ] https://github.com/metabase/metabase/issues/40571
- [ ] https://github.com/metabase/metabase/issues/40585
- [ ] https://github.com/metabase/metabase/issues/40502
- [ ] https://github.com/metabase/metabase/issues/40583
- [ ] https://github.com/metabase/metabase/issues/40497
- [ ] https://github.com/metabase/metabase/issues/41356
- [ ] https://github.com/metabase/metabase/issues/40620
- [ ] https://github.com/metabase/metabase/issues/40506
- [ ] https://github.com/metabase/metabase/issues/40576
- [ ] https://github.com/metabase/metabase/issues/41364
- [ ] https://github.com/metabase/metabase/issues/41347
- [ ] https://github.com/metabase/metabase/issues/41354
- [ ] https://github.com/metabase/metabase/issues/41258
```
