### ISSUE TITLE
[Epic] Use Mantine Notification Component

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#38832]
[discussion](https://metaboat.slack.com/archives/C057WD5L0JG/p1708028714904999?thread_ts=1708026596.591569&cid=C057WD5L0JG)

https://v6.mantine.dev/core/notification/

```[tasklist]
### Prep
- [ ] Design pass on notification
- [ ] implementation of notification designs
```

```[tasklist]
### Implementation
- [ ] separate notifications from undos
- [ ] Admin: saved/error notifications
- [ ] Global toast/undos
- [ ] Upload / db sync popups?
```
