### ISSUE TITLE
[Epic] CSV Append Follow-Ups

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#38853]
This is an epic for the tasks left over from https://github.com/metabase/metabase/issues/35614 that didn't make it to the 49 RC1.

**Links**
- [product doc](https://www.notion.so/metabase/Allow-appends-on-existing-CSV-upload-models-f1f13864632d4cfd83522fce762890eb#58380830c6ca45df923e4cacc4af1964)
- [eng doc](https://www.notion.so/metabase/Eng-Allow-appending-more-data-to-CSV-uploads-4c40e06fa64744c699588b8d8576e5df)

```[tasklist]
### Cleanup / Misc
- [ ] https://github.com/metabase/metabase/issues/38955
- [ ] https://github.com/metabase/metabase/issues/38956
- [ ] https://github.com/metabase/metabase/issues/38958
- [ ] https://github.com/metabase/metabase/issues/37069
- [ ] https://github.com/metabase/metabase/issues/39818
- [ ] https://github.com/metabase/metabase/issues/39867
- [ ] https://github.com/metabase/metabase/issues/39868
- [ ] https://github.com/metabase/metabase/issues/34325
```
