### ISSUE TITLE
[Epic] Add license activation in the initial setup

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#38867]
**Links**
- product doc: [Add license activation step in /setup](https://www.notion.so/metabase/Add-license-activation-step-in-setup-c186326d2efd4467a7e9d09138fca48c)
- eng doc: [Add license activation step in /setup](https://www.notion.so/metabase/Add-license-activation-step-in-setup-77d8f3e5c2484226b8a162098b6eea5b)
- feature branch: [`license-activation-step`](https://github.com/metabase/metabase/pull/39257)

***Milestone 1***

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/38858
- [ ] https://github.com/metabase/metabase/pull/38953
- [ ] https://github.com/metabase/metabase/pull/39151
- [ ] https://github.com/metabase/metabase/pull/39103
- [ ] https://github.com/metabase/metabase/pull/39292
- [ ] https://github.com/metabase/metabase/pull/39440
- [ ] https://github.com/metabase/metabase/pull/39443
- [ ] https://github.com/metabase/metabase/pull/39257
```

***Milestone 2 - polishing***

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/39067
- [ ] https://github.com/metabase/metabase/pull/39931
- [x] ask schema change for the events
```
