### ISSUE TITLE
[Epic] Add Extract action to chill mode column headings

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#38964]
# Links

- [Product doc](https://www.notion.so/metabase/Add-Extract-action-to-chill-mode-column-headings-14867dac1e934ba2bde66671f845f3f9)
- [Eng doc](https://www.notion.so/metabase/Add-Extract-action-to-chill-mode-column-headings-technical-design-doc-0ca8f957d8b94d4b91159629b73ff2e4?pvs=4)
- [Figma](https://www.figma.com/file/yl8Yy4iMSpaWzjuNoEjBZu/Add-Extract-action-to-chill-mode-column-headings?type=design&node-id=5916%3A4721&mode=design&t=RD83L36AiFte8U4m-1)
- [Figma prototype](https://www.figma.com/proto/yl8Yy4iMSpaWzjuNoEjBZu/Add-Extract-action-to-chill-mode-column-headings?page-id=5916%3A13164&type=design&node-id=5916-4722&viewport=-7634%2C-1321%2C0.14&t=ny68qzp6zpbyeWLZ-1&scaling=contain&starting-point-node-id=5916%3A4722&mode=design)
- [Testing plan](https://github.com/metabase/metabase/issues/39291)
- feature branch: TBD

# Implementation Plan

## Milestone 1 - Date/time columns

Milestone 1 should only cover datetime extractions, specifically the following 6 (see [Figma](https://www.figma.com/file/yl8Yy4iMSpaWzjuNoEjBZu/Add-Extract-action-to-chill-mode-column-headings?type=design&node-id=5916-4957&mode=design&t=0TXjT9JJUxyx3k9k-4)):
- Hour of day
- Day of month
- Day of week
- Month
- Quarter
- Year

```[tasklist]
### Backend
- [ ] https://github.com/metabase/metabase/pull/39162
- [ ] https://github.com/metabase/metabase/issues/40125
```

```[tasklist]
### Frontend
- [ ] https://github.com/metabase/metabase/issues/39248
- [ ] https://github.com/metabase/metabase/pull/39770
- [ ] https://github.com/metabase/metabase/issues/39982
```

## Milestone 2 - URL columns

Splitting up URLs to extract the (sub)domain(s) is not a simple task. There are libraries for it but they're complex, and we can't push those into the data warehouse anyway. I think we'll have to do the best we can with a `regexextract` so that it can be handled at the database level.

Estimate: 0.5 to 1 day to write and heavily test the regexes; plus a bit to integrate the new type into the `column-extract` drill.

```[tasklist]
### Backend
- [ ] https://github.com/metabase/metabase/pull/40188
```

## Milestone 3 - Email columns

Extracting the host after the `@` is straightfoward. Going from there to the domain can reuse the regex from Milestone 2.

Estimate: 0.5 days to build the email regex and integrate into the `column-extract` drill.

```[tasklist]
### Backend
- [ ] https://github.com/metabase/metabase/pull/40200
```

**Comment by bshepherdson** [comment]
This has all landed in master and has a :+1: from PMs.
