### ISSUE TITLE
[Epic] Cache admin

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#39153]
**Links**
- [product doc: rework cache setup](https://www.notion.so/metabase/Rework-cache-setup-and-management-db37ccc280db4da484c15770bd18f0bd#7460c0b5537f43339fe1ac354badc60b)
- [product doc: add and refine cache invalidation policies](https://www.notion.so/metabase/Add-and-refine-cache-invalidation-policies-e6d69bd2ffa54351ab0b902637b50b15)
- [technical design doc](https://www.notion.so/metabase/Tech-Cache-arc-bbbdc728e38c49dbad52cebd22c9011e) for the BE
- [figma](https://www.figma.com/file/x87hHuf4RabjMBuyV2Lq7c/caching-arc-low-fi-explorations?type=design&node-id=693-18853&mode=design&t=VqIEhJO0vzEsCzDr-0)

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/41425
- [ ] https://github.com/metabase/metabase/issues/41426
- [ ] https://github.com/metabase/metabase/issues/41427
- [ ] https://github.com/metabase/metabase/issues/41478
- [ ] https://github.com/metabase/metabase/issues/42591
- [ ] https://github.com/metabase/metabase/issues/42718
- [ ] https://github.com/metabase/metabase/issues/41455
- [ ] https://github.com/metabase/metabase/issues/42568
```
