### ISSUE TITLE
Create new UI for performance admin, with three possible cache invalidation strategies for databases

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#39163]
```[tasklist]
### Milestone 1
- [x] Add Performance tab (https://github.com/metabase/metabase/pull/39234)
- [x] Add data caching settings tab (https://github.com/metabase/metabase/pull/39234)
- [x] Add three-panel configuration editor (https://github.com/metabase/metabase/pull/39234)
- [x] Add don't cache (with no connection to backend (https://github.com/metabase/metabase/pull/39234)
- [x] Add TTL (with no connection to backend) (https://github.com/metabase/metabase/pull/39234)
- [x] Add don't cache (with real connection to backend) https://github.com/metabase/metabase/pull/39234
- [x] Add TTL (with real connection to backend) https://github.com/metabase/metabase/pull/39234
- [x] Split out enterprise-specific code #39234
- [x] Add configuration option for cache strategy: duration #39234
- [x] Add error messages to form (#39234)
- [x] Add confirmation modal before resetting databases to default  (#39234)
- [x] Add confirmation modal before leaving page  (#39234)
- [x] Remove superseded items from cache settings page  (#39234)
- [x] Add basic unit tests  (#39234)
- [x] Ensure "reset all" button shows different loading states  (#39234)
- [x] Add background hover color to "reset all" button  (#39234)
- [x] Ensure "Save changes" button says "Save changes" after form is edited  (#39234)
- [x] Ensure "Reset all to default" button says "Reset all to default" when form is edited  (#39234)
- [x] Add 'example' link with tooltip  (#39234)
- [x] To say that the root strategy is "nocache, delete it  (#39234)
- [x] Use 'Reset all database caching policies to the default?' in the reset button confirmation modal  (#39234)
- [x] Split StrategyEditorForDatabases into smaller components and hooks  (#39234)
- [x] Split out enterprise code thoroughly
- [x] Tweak: reset button from 'Saved' to 'Save changes' when the user edits the form
```

**Milestone 2 is now in a separate issue: #40978*

```[tasklist]
### Open questions (note: these are not tasks)
- [x] It might be confusing to say 'resetting to duration' if the database strategies are also duration. Perhaps we should say 'resetting to duration (10 hours)' or just 'reset to the default strategy'
```

**Comment by rafpaf** [comment]
Moved this list into the epic issue: https://github.com/metabase/metabase/issues/39153
