### ISSUE TITLE
[Epic] Better UI/UX for picking default parameter values

### ISSUE THREAD

**Issue by oleggromov** [metabase/metabase#39211]
**Links**
Product doc: ❤️ [Better UI/UX for picking default parameter values](https://www.notion.so/metabase/Better-UI-UX-for-picking-default-parameter-values-6ce0b45af9604f2e90330b44c457311a)
Previous project: ⭐️ [Let creators make dashboard filters required](https://www.notion.so/metabase/Let-creators-make-dashboard-filters-required-7ea3d7caf63545d2b713d1509e4267ad) 

## Milestone 0
- [ ] **WIP** Identify and catalogue all value picker widget behaviors
- [ ] Figure out possible complications 
- [ ] Put together a project plan 

The next steps will be based upon these findings. 

## Milestone 1 — native query default value pickers
- [x] https://github.com/metabase/metabase/pull/39454 — plain values, dates
- [x] https://github.com/metabase/metabase/pull/39852 — categories with different sources to pick from
- [ ] Field parameters
- [ ] Error states, default toggle/blur behavior, other small additions
- [ ] Add a comprehensive set of tests covering:
  - [ ] new UI behaviors
  - [ ] parameter processing (lib)

## Milestone 2 — dashboard default value pickers
TBD

## Next milestones
TBD:
- native question filter components 
- dashboard filter componets
- embeddings
- remove the entire `ParameterValueWidget` with deps

## Issues to be addressed (incomplete list)

- when input is losing focus, restore [the default value](https://metaboat.slack.com/archives/C02H619CJ8K/p1707957402805569?thread_ts=1707417723.403539&cid=C02H619CJ8K)
  - In a TextWidget, press Enter - and it won't set default value back
-  improvements to the default value picking flow (points [A-C here](https://metaboat.slack.com/archives/C02H619CJ8K/p1707957402805569?thread_ts=1707417723.403539&cid=C02H619CJ8K)), and also [Conor's comment](https://metaboat.slack.com/archives/C02H619CJ8K/p1708040647469919?thread_ts=1707417723.403539&cid=C02H619CJ8K)
  - Same as above but might have additional details: ensure input error states are correct as in the [slack comment](https://metaboat.slack.com/archives/C0645JP1W81/p1706217318961009?thread_ts=1706207086.466069&cid=C0645JP1W81)
