### ISSUE TITLE
[Epic] Allow reordering of items in notebook mode 

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#39210]
Fixes https://github.com/metabase/metabase/issues/38862

```[tasklist]
### Frontend
- [ ] https://github.com/metabase/metabase/pull/39200
- [ ] https://github.com/metabase/metabase/pull/39205
```

```[tasklist]
### Backend
- [ ] https://github.com/metabase/metabase/issues/39215
```
