### ISSUE TITLE
Setting or updating a `user-local` setting by a non-admin is followed by fetching all settings, which results in `403`

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#39221]
We have so called `user-local` settings. They can be limited to admins, setting managers or allowed to be used by any authenticated user. Read more about it [here](https://github.com/metabase/metabase/blob/master/src/metabase/models/setting.clj#L1098).

The problem arises when a non-admin user sets or updates the setting.
The `updateSetting` action (as defined [here](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/admin/settings/settings.js#L53)) then fetches all settings which is something that's allowed only by admins, or superusers.
https://github.com/metabase/metabase/blob/7f0d671/src/metabase/api/setting.clj#L28-L29

## Current behavior
- Non-admin sets or updates the setting.
- Frontend tries to fetch all settings
- The endpoint returns `403`

## Expected behavior
- Non-admin sets or updates the setting.
- Frontend either fetches `/api/session/properties` or it skips the fetching logic altogether

```[tasklist]
### User-local settings not restricted to admins
- [x] last-used-native-database-id (#39251)
- [ ] dismissed-browse-models-banner (#39359)
- [ ] dismissed-custom-dashboard-toast (#39359)
```

### Related
#39223

**Comment by nemanjaglumac** [comment]
Reopening because there are more user-local settings we need to take care of.
Updated the description of this issue with a task list.
