### ISSUE TITLE
[Epic] Let white-labeling customers customize illustrations

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#39246]
**Links**
- [Product doc](https://www.notion.so/metabase/Let-white-labeling-customers-customize-illustrations-24e120498d5f414aaf52ddd0de9e20fc)
- [Eng doc](https://www.notion.so/metabase/Tech-Let-white-labeling-customers-customize-illustrations-e8adba727d0e4297b2ed8679ab79a8d6)
- [Testing plan](https://www.notion.so/metabase/Testing-plan-Let-white-labeling-customers-customize-illustrations-3985c2369ca647a19f5f454e390a9bca)
- integration branch: `39246-milestone-1`

```[tasklist]
#### Milestone 1
- [ ] https://github.com/metabase/metabase/pull/39299
- [ ] https://github.com/metabase/metabase/pull/40487
- [ ] https://github.com/metabase/metabase/pull/40491
- [ ] https://github.com/metabase/metabase/pull/40139
- [ ] https://github.com/metabase/metabase/pull/40710
- [x] https://github.com/metabase/metabase/pull/40219 - integration branch
```

```[tasklist]
#### Milestone 2
- [x] ~Connect to the BE referencing files~ We decided [not to do this](https://metaboat.slack.com/archives/C063Q3F1HPF/p1709737723369799)
- [ ] https://github.com/metabase/metabase/pull/40681
- [ ] Ping Thomas once analytics is merged to master
```
