### ISSUE TITLE
[Epic] Command Palette v1

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#39259]
**Links**
- product doc: [_link to product doc_](https://www.notion.so/metabase/Command-Palette-0559f5cbae0d45e7bc2f6960775d0b8b)
- feature branch: `command-palette/main` 

**Implementation Plan**
Using the [kbar](https://github.com/timc1/kbar) library, we will build up a command palette with contextually aware actions. `kbar` has some great functionality to dynamically register actions through hooks when those components mount, and remove them when components are unmounted. This may require converting some class components to be more functional, but overall gives a very straightforward path.

Ideally, This can be merged when milestone 1 is complete, and expanded through PRs to master

```[tasklist]
### Milestone 1 - Command Palette introduction and general actions
- [ ] https://github.com/metabase/metabase/issues/40312
- [ ] https://github.com/metabase/metabase/issues/40317
- [ ] https://github.com/metabase/metabase/issues/39479
- [x] Recent Items
- [x] Entity search
- [x] General Actions
- [x] Ensure this is not present in embedding applications
- [x] The default order of items should be the same of +new button: question, sql query, dashboard, collection, model
- [x] Admins shouldn't see admin settings by default (only on search)
- [x] e2e and unit tests
```

```[tasklist]
### Milestone 2 - Admin
- [x] Add admin settings search and back
- [x] e2e and unit tests
```

```[tasklist]
### Milestone 2.5 - UI Polish and exploration
- [ ] https://github.com/metabase/metabase/issues/40671
- [ ] https://github.com/metabase/metabase/issues/40895
- [ ] https://github.com/metabase/metabase/issues/40735
- [ ] https://github.com/metabase/metabase/issues/40631
- [ ] https://github.com/metabase/metabase/issues/41028
- [ ] https://github.com/metabase/metabase/issues/41417
- [ ] https://github.com/metabase/metabase/issues/41536
- [ ] https://github.com/metabase/metabase/issues/41994
- [ ] https://github.com/metabase/metabase/issues/41901
- [ ] https://github.com/metabase/metabase/issues/42078
- [ ] https://github.com/metabase/metabase/issues/42346
- [ ] https://github.com/metabase/metabase/issues/42701
```
