### ISSUE TITLE
[Epic] Highlight the selected data source in the notebook editor

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#39542]
**Links**
- [product doc](https://www.notion.so/metabase/Highlight-the-selected-data-source-in-the-query-builder-877bf66e580543eb881fca601a714817)
- feature branch: `highlight-data-source`
- issue links: N/A
- [testing plan](https://github.com/metabase/metabase/issues/39544)

**Implementation Plan**
Any of the initial tasks can be expanded into a full-blown task list as we learn more about them. For each item on the list, the plan is to:
1. go over the happy-path scenarios
2. document what's not working
3. fix what's not working
4. add tests

```[tasklist]
### Cleanup and refactoring
- [ ] https://github.com/metabase/metabase/pull/39681
```

```[tasklist]
### Dimensions
- [x] Ad-hoc
- [x] Saved question (simple)
- [x] Saved question (nested)
- [x] Saved model (view + edit query definition)
```

```[tasklist]
### Edge cases
- [ ] TBD
```

```[tasklist]
## Existing or related issue
- [ ] #39699
- [ ] #25142
- [ ] https://github.com/metabase/metabase/issues/39807
- [ ] https://github.com/metabase/metabase/issues/39812
```
