### ISSUE TITLE
[Epic] Productize Cloud migrations

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#39654]
[Product doc](https://www.notion.so/metabase/Productize-Cloud-migration-9ac517a86a5d4312ae4f0a37c9625e67?d=fb68e9f5a88f401fbeb8d6e41b4dc7c5)

[Tech spec](https://www.notion.so/metabase/Tech-Productize-Cloud-migration-030865067e64417a96218588e6f91a72)

```[tasklist]
### Tasks
- [ ] metabase/infra-frontend#954
- [ ] metabase/infra-frontend#956
- [ ] https://github.com/metabase/harbormaster/pull/4865
- [ ] https://github.com/metabase/metabase/pull/41317
- [ ] https://github.com/metabase/metabase/issues/41474
```
