### ISSUE TITLE
CollectionPicker improvements

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#39702]
```[tasklist]
### TODO
- [ ] https://github.com/metabase/metabase/issues/39965
- [ ] https://github.com/metabase/metabase/issues/39966
```

```[tasklist]
### Maybe
- [ ] Add collection descriptions somewhere
```
