### ISSUE TITLE
[Epic] Air Gapped Enterprise Tokens

### ISSUE THREAD

**Issue by escherize** [metabase/metabase#39711]
**Links**
- product doc: [Product Doc](https://www.notion.so/metabase/Productize-Air-Gapping-44660f7e5e114411901edeecc72b6828)
- eng doc: [Tech Doc](https://www.notion.so/metabase/Air-Gap-Technical-Design-Doc-c9e321cb04b7407581850da7152c2fc8)
- feature branch: [`airgap-token`](https://github.com/metabase/metabase/pull/39733)

### Milestone 1
- [x] add :max-users and :company to `TokenStatus` schema
- [x] Read and decrypt airgapped token using public key in resources
- [x] read `max-user`
- [x] write function to read `max-user` from the airgap token contents
- [x] Add a check-max-users function to deny user creation when max-users != -1 and (user_count - internal_user) > max-users
- [x] enforce valid-thru time when checking features (this is a good time to double check that it's still valid)
- [x] return the same shape of map as harbormaster for an error to decode, etc.
- [x] setup usable script to generate signed airgap tokens
- [x] ensure existance of public key before trying to decrypt token
- [x] fix tests
--- 
_(milestone 1 is mvp, I think.)_

----

### Feedback from Success Team
- [x] Add diagnostic info about airgap (these are only included when it is enabled): max-user cap, current-user-count, enabled or not, and expiration date.

-----
### Milestone 2
- [x] Gracefully downgrade to OSS-mode when the airgap token is expired
    - [x] should behave as if HarborMaster declined a regular token
- [ ] Banners:
    - [ ] figure out what api we should use to send this over.
    - [x] Add banner to admin section with the `:valid-thru` date.
    - [ ] Add warning banner all over for admins when we are "getting close" to `:valid-thru` date.
    - [ ] Add banner when token has expired
- [ ] More lockouts:
    - [x] On startup check if `select count(1) from users > max-user` and then disable the rest (with sorting to not disable admins first). Print a log line, and it’s their admin’s problem to figure out who to remove and who to enable.
    - [ ] Limit number of sessions to `max-users`.

**Comment by escherize** [comment]
Closing as this is in effect working. There are some nice to haves that are low priority, but the bulk of the work is done here.
