### ISSUE TITLE
[Epic] Preserve Dashboard Filter States

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#39809]
**Links**
- [product doc](https://www.notion.so/metabase/Preserve-dashboard-filter-states-for-users-0f89ff0da0c24026a3692b0f9d704fed)
- feature branch: `preserve-dashboard-filter-states`
- [Testing plan](https://github.com/metabase/metabase/issues/39808)

**Implementation Plan**

***Milestone 1***
```[tasklist]
### Frontend
- [ ] https://github.com/metabase/metabase/pull/39511
- [ ] Replace localStorage usage with a BE implementation - https://github.com/metabase/metabase/pull/39813
- [ ] Verify implementation on embeds, public and regular dashboards with tests
```
```[tasklist]
### Backend
- [ ] https://github.com/metabase/metabase/issues/39810
```

**Comment by uladzimirdev** [comment]
- Interactive embeddings work based on my local testings ✅ 
- static embeddings do not save state as expected ✅ 
- public dashboards do not save state, [changed requirement](https://metaboat.slack.com/archives/C0645JP1W81/p1715941069842299?thread_ts=1715940692.731129&cid=C0645JP1W81)
