### ISSUE TITLE
[Epic] Druid JDBC driver

### ISSUE THREAD

**Issue by lbrdnk** [metabase/metabase#39938]
**Links**
- [product doc](https://www.notion.so/metabase/Revamped-Druid-driver-27f139935c26401bb378f5a1ccd15f90?pvs=4)
- [eng doc](https://www.notion.so/metabase/Druid-JDBC-driver-867deedf6a254d69837b046f7c5d7341?pvs=4)
- [feature branch `druid-jdbc`](https://github.com/metabase/metabase/tree/druid-jdbc)

**Implementation Plan**

```[tasklist]
### Phase 0
- [x] Get the dockerized Druid running for local development with sample data Druid provides.
- [x] Create new plain :druid-jdbc driver module using the Avatica JDBC driver. Register the empty driver.
- [x] Manually test interaction with local Druid deployment using newly created Metabase driver — eg. do select from druid sample data using Avatica JDBC driver in repl, from namespace of :druid-jdbc
```

```[tasklist]
### Phase 1
- [ ] https://github.com/metabase/metabase/issues/39939
- [ ] https://github.com/metabase/metabase/issues/40094
- [x] Ensure that we are able to run simple mbql queries (MBQL select and more works out of the box)
- [ ] https://github.com/metabase/metabase/issues/40096
```
Next phases and tasks will be added in accordance with progress.
```[tasklist]
### Phase 2
- [ ] https://github.com/metabase/metabase/issues/40501
```

**Comment by lbrdnk** [comment]
Driver has been merged to master with PR https://github.com/metabase/metabase/pull/40293.
