### ISSUE TITLE
[Epic] Make it easy to combine columns in chill mode

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#39977]
# Links
- [Product doc](https://www.notion.so/metabase/Make-it-easy-to-combine-columns-in-chill-mode-08c91f890d92452bb672591c7812f9e9)
- [Eng doc](https://www.notion.so/metabase/Tech-Make-it-easy-to-combine-columns-in-chill-mode-df6957f2e4974b30a4b8d5184c52c3b5?d=af7de82f635645dea009484f6481f4ed)
- [Figma](https://www.figma.com/file/mdsv3PhsTo9VZd3uAY0naT/Make-it-easy-to-combine-columns-in-chill-mode?type=design&node-id=7952-9453&mode=design&t=l3oa5aDe95AmvFKn-0)
- [Testing plan](https://github.com/metabase/metabase/issues/39984)
- Feature branch: `combine-columns`

# Implementation Plan

## Milestone 1 - Column header

```[tasklist]
### Backend
- [ ] https://github.com/metabase/metabase/issues/39978
```

```[tasklist]
### Frontend
- [ ] https://github.com/metabase/metabase/issues/39980
- [ ] https://github.com/metabase/metabase/issues/39981
- [ ] https://github.com/metabase/metabase/issues/41350
- [ ] https://github.com/metabase/metabase/issues/41353
```

# Testing plan

#39984
