### ISSUE TITLE
[Epic] Faster sync

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#39986]
Sync is slower than it could be. There's a ton of work we could do to optimize it. This issue tracks what we've done and what we can do (note: we're not necessarily going to do all of this).

```[tasklist]
### Redshift sync-fields and sync-fks
- [ ] https://github.com/metabase/metabase/issues/38492
- [ ] https://github.com/metabase/metabase/pull/38828
- [ ] https://github.com/metabase/metabase/pull/38970
- [ ] https://github.com/metabase/metabase/pull/41068
```
```[tasklist]
### Follow up tasks
- [ ] https://github.com/metabase/metabase/pull/41588
- [ ] https://github.com/metabase/metabase/pull/41375
- [ ] https://github.com/metabase/metabase/pull/41528
```

**Pause and think once the above is complete**

```[tasklist]
### Faster sync-fields and sync-fks for more drivers
- [ ] Implement for drivers that don't support `:nested-field-columns`, e.g. snowflake, bigquery, what else ???
- [ ] Support `:nested-field-columns` JDBC databases, e.g. postgres, mysql
- [ ] Support for non-JDBC databases e.g. mongo
```
```[tasklist]
### Other things
- [ ] sync-indexes suffers from a similar problem as sync-fields and sync-fks for databases that support `:index-info` (e.g. bigquery, mongo)
- [ ] https://github.com/metabase/metabase/issues/39971
- [ ] explore whether ELT speeds up ingestion
- [ ] fingerprinting could be (mostly) decoupled from semantic_type classification, and happen later
- [ ] in-DB fingerprinting like accurate re-fingerprinting
- [ ] use index scans instead of table scans for updating fields
```

**Comment by calherries** [comment]
Closing this as completed because the rest will be prioritized by https://www.notion.so/metabase/Faster-sync-for-more-drivers-d5b657aba7354a19bf89d62f1038a8ff
