### ISSUE TITLE
[Epic] Initial homepage experience for embedding admins

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#40005]
**Links**
- product doc: [Initial homepage experience for embedding admins](https://www.notion.so/metabase/Initial-homepage-experience-for-embedding-admins-9431f50fdf3a4f63b291dc801349c335)
- eng doc: [Initial homepage experience for embedding admins](https://www.notion.so/metabase/Initial-homepage-experience-for-embedding-admins-was-Meet-embedders-at-the-door-full-version-63fa3a8e07634c9faf67d5bdd5a2df08)
- feature branch: `embed-homepage` / https://github.com/metabase/metabase/pull/40382

**Implementation Plan**

MS1: https://github.com/metabase/metabase/pull/40382

```[tasklist]
### MS 1 - Homepage without example dashboard -`embed-homepage`
- [ ] https://github.com/metabase/metabase/pull/40251
- [ ] https://github.com/metabase/metabase/pull/40455
- [ ] https://github.com/metabase/metabase/pull/40528
- [ ] https://github.com/metabase/metabase/pull/40587
- [x] double check unit tests and e2es (I'm actually writing them as I go)
- [ ] https://github.com/metabase/metabase/pull/40638
- [ ] https://github.com/metabase/metabase/pull/40813
```

MS2: https://github.com/metabase/metabase/pull/41180

```[tasklist]
### MS 2 - Add example dashboard reference
- [x] dependency on https://github.com/metabase/metabase/issues/40066
- [ ] https://github.com/metabase/metabase/pull/41138
```

```[tasklist]
### MS 3 - Dismiss with feedback - `embed-homepage-ms3`
- [x] dependency on https://github.com/metabase/harbormaster/issues/4783
- [ ] https://github.com/metabase/harbormaster/issues/4814
- [ ] https://github.com/metabase/metabase/pull/40746
- [ ] https://github.com/metabase/metabase/pull/40974
```

MS4: https://github.com/metabase/metabase/pull/41990
```[tasklist]
### MS 4 - Analytics + polishment - `embed-homepage-milestone4`
- [ ] https://github.com/metabase/metabase/pull/41575
- [ ] https://github.com/metabase/metabase/pull/41638
- [ ] https://github.com/metabase/metabase/pull/41644
- [ ] https://github.com/metabase/metabase/pull/41725
- [ ] https://github.com/metabase/metabase/pull/41784
- [ ] https://github.com/metabase/metabase/pull/42042
- [ ] https://github.com/metabase/metabase/pull/42200
- [x] [AFTER MERGING ON MASTER] snowplow ping about schema changes
```
