### ISSUE TITLE
[Epic] Fix huge collection permission graphs

### ISSUE THREAD

**Issue by escherize** [metabase/metabase#40030]
There is some extra complexity here in that we must show a warning when the user has `read` or `edit` permissions to a sub collection with `none` permissions.

We are tackling this with multiple fixes:

**Implementation Plan**

- [x] parallelize permission graph lookup with a bounded thread pool
- [x] make collection permission graph revisions be recorded async
- [x] do not send back the entire perm graph on a PUT request

**Comment by perivamsi** [comment]
can be closed, duplicate of https://github.com/metabase/metabase/issues/36647

**Comment by paoliniluis** [comment]
@perivamsi nope, this is for collection graphs, the other one is for data graphs

**Comment by perivamsi** [comment]
Are you sure? Both say permissions

@escherize to confirm

**Comment by paoliniluis** [comment]
The 2 permission graphs are different

**Comment by escherize** [comment]
This has been addressed by multiple recently merged PRs. 

- [Async coll perm graph revision](https://github.com/metabase/metabase/pull/45258)
- [parallelize coll perm graph group lookup](https://github.com/metabase/metabase/pull/45256)
- [add skip_graph to coll perm PUT](https://github.com/metabase/metabase/pull/45438)
