### ISSUE TITLE
[Epic] Upgrade to React 18

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#40107]
**Links**
- feature branch: `update-react-18`

**Implementation Plan**
This is subject to change (and has already changed), but the current implementation plan revolves around migrating away from libraries that are known to not fully work with react 18, and then start addressing issues that CI and Unit tests catch.

```[tasklist]
### Upgrade secondary dependencies
- [ ] https://github.com/metabase/metabase/issues/39714
- [ ] https://github.com/metabase/metabase/issues/37921
- [x] Update user-auth-wrapper to v2
- [x] Update react-draggable
```
```[tasklist]
### Pre-18 Work (required things we can get done prior to actual package upgrade)
- [ ] https://github.com/metabase/metabase/issues/40178
- [ ] https://github.com/metabase/metabase/issues/41271
- [ ] https://github.com/metabase/metabase/issues/40267
- [ ] https://github.com/metabase/metabase/issues/41208
```

```[tasklist]
### React 18 Upgrade
- [x] Update react to v18
- [x] Migration types for props to contain definition for `children`
- [x] Update react library to latest version
- [x] table headers issue (drag start to end < 5px is considered a click)
- [x] Fix e2e tests
- [ ] https://github.com/metabase/metabase/issues/43373
```
