### ISSUE TITLE
[Epic] Enable drill-thru for single-row aggregates

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#40174]
This may not deserve an Epic; it's a modest bug in the logic for when particular drill-thrus should appear.

**Links**
- [product doc](https://www.notion.so/metabase/Enable-drill-thru-for-single-row-aggregates-437fc82fb0e546569086cfe73307e339)
- eng doc: none needed; this is straightforward.
- feature branch: mblib-drills-single-row-aggregates

```[tasklist]
### Tasks
- [ ] Fix `quick-filter` logic so it _does not_ appear for single-row aggregates
- [ ] Fix `underlying-records` logic so it _does_ appear for single-row aggregates
- [ ] Test these cases.
```
