### ISSUE TITLE
[Epic] Show generated SQL in a side bar automatically

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#40254]
**Links**
- [Product doc](https://www.notion.so/metabase/Show-generated-SQL-in-a-side-bar-automatically-b56dbea3ece942ac981ee0326e5867c8)
- [Eng doc](https://www.notion.so/metabase/Tech-Show-generated-SQL-in-a-side-bar-automatically-febee0259d2d40e294a06d2f4930122e?pvs=4)
- Feature branch:  check under each of the milestones
- [Figma](https://www.figma.com/file/TZseFDIOAhNU6ArKtFmxBx/Show-generated-SQL-in-a-side-bar-automatically?type=design&node-id=1-286&mode=design&t=ptjbABjX6rJIqwRt-0)
- Testing plan: https://github.com/metabase/metabase/issues/40579

# Implementation Plan

## Milestone 0
Good litmus test for the scope of this milestone is that all steps in it should easily be merged into `master` and even backported.
```[tasklist]
## Prep and necessary cleanup
- [ ] #40136
- [ ] https://github.com/metabase/metabase/pull/40268
- [ ] https://github.com/metabase/metabase/pull/40286
- [ ] https://github.com/metabase/metabase/pull/40316
```

## Milestone 1
For the proof of concept, our goal is to have a SQL preview that automatically updates with each new step being added/removed in the Notebook GUI editor. Code highlighting, line numbering, and the ability to resize the sidebar are not important for this phase.

Feature branch: https://github.com/metabase/metabase/tree/sql-sidebar-preview-poc
```[tasklist]
## Working Prototype
- [x] Show SQL preview in the sidebar and update synchronously with steps in the notebook GUI editor (#40279)
- [x] Hook the sidebar to the toggle query button and preserve the preference in the Redux store `uiState`  (#40327)
- [x] Convert to the native query (#40362)
- [x] Make minimal necessary CSS tweaks (#40463)
- [x] Adjust the sidebar to work with small screens (#40463)
- [x] Cover with E2E tests before merging (https://github.com/metabase/metabase/pull/40540)
```

```[tasklist]
## Extras
- [x] #40430
```

## Milestone 2
Tasks that should happen after we gather some initial feedback on PoC from the product, design, and from the users.
```[tasklist]
## Visual tweaks
- [ ] https://github.com/metabase/metabase/issues/40668
- [ ] https://github.com/metabase/metabase/issues/40697
```

```[tasklist]
## Follow ups after M1
- [ ] https://github.com/metabase/metabase/pull/40630
```

## Milestone 3
```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/40948
- [ ] https://github.com/metabase/metabase/pull/40984
- [ ] https://github.com/metabase/metabase/issues/41058
```

```[tasklist]
### Follow ups
- [ ] Unit tests
- [ ] https://github.com/metabase/metabase/pull/41082
- [ ] https://github.com/metabase/metabase/pull/41141
```

## Post-development checklist
```[tasklist]
- [x] Delete code related to the previous modal
- [x] Potentially move some related components around if they need to live closer to the notebook
```
