### ISSUE TITLE
Implement and test nested field columns

### ISSUE THREAD

**Issue by lbrdnk** [metabase/metabase#40501]
```[tasklist]
### Tasks
- [x] Initial implementation of nested field columns
- [x] Make existing nested field columns tests work with Druid JDBC
- [ ] https://github.com/metabase/metabase/issues/41094
```

**Comment by lbrdnk** [comment]
Nested field columns tests were ported. Druid testing image got added json tables on build time. Green CI run with nfc tests: https://github.com/metabase/metabase/actions/runs/8811761084.
