### ISSUE TITLE
[Epic] Data picker

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#40717]
**Links**
- parent epic: #35564
- [Product Doc](https://www.notion.so/metabase/Make-picking-an-item-a-nice-experience-with-an-EntityPicker-component-05e457c1b84f413f84ab9756e0c68b57)
- [Technical Design](https://www.notion.so/metabase/EntityPicker-Technical-Design-d4483523312e46c38ffd0bfe9c2371c7)
- feature branch: `data-picker`
  - Epic PR: #41175

**Implementation Plan**

The first milestone is about implementing the data picker and using it in `DataStep` component.

```[tasklist]
### Milestone 1
- [ ] https://github.com/metabase/metabase/issues/40298
- [ ] https://github.com/metabase/metabase/issues/41182
- [ ] https://github.com/metabase/metabase/issues/40719
- [ ] https://github.com/metabase/metabase/pull/42315
- [ ] https://github.com/metabase/metabase/issues/41172
- [ ] https://github.com/metabase/metabase/issues/42335
```

```[tasklist]
### Milestone 2 - Use Data picker in other places
- [ ] https://github.com/metabase/metabase/issues/40952
- [ ] https://github.com/metabase/metabase/issues/42559
- [ ] https://github.com/metabase/metabase/issues/40953
- [ ] https://github.com/metabase/metabase/issues/42675
```
