### ISSUE TITLE
[Epic] Migrate (entities) to RTK Query

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#40788]
Make the entity framework use RTK query under the hood for all API requests.

# Entities

```[tasklist]
## Milestone 1 - replace api handlers in entities
- [ ] https://github.com/metabase/metabase/issues/40789
- [ ] https://github.com/metabase/metabase/issues/40790
- [ ] https://github.com/metabase/metabase/issues/41818
- [ ] https://github.com/metabase/metabase/issues/40791
- [ ] https://github.com/metabase/metabase/issues/40792
- [ ] https://github.com/metabase/metabase/issues/40793
- [ ] https://github.com/metabase/metabase/issues/40794
- [ ] https://github.com/metabase/metabase/issues/40795
- [ ] https://github.com/metabase/metabase/issues/40796
- [ ] https://github.com/metabase/metabase/issues/40797
- [ ] https://github.com/metabase/metabase/issues/40798
- [ ] https://github.com/metabase/metabase/issues/40799
- [ ] https://github.com/metabase/metabase/issues/40800
- [ ] https://github.com/metabase/metabase/issues/40801
- [ ] https://github.com/metabase/metabase/issues/40802
- [ ] https://github.com/metabase/metabase/issues/40803
- [ ] https://github.com/metabase/metabase/issues/40804
- [ ] https://github.com/metabase/metabase/issues/40805
- [ ] https://github.com/metabase/metabase/issues/40806
- [ ] https://github.com/metabase/metabase/issues/40807
- [ ] https://github.com/metabase/metabase/issues/40808
- [ ] https://github.com/metabase/metabase/issues/40809
- [ ] https://github.com/metabase/metabase/issues/40810
- [ ] https://github.com/metabase/metabase/issues/40811
- [ ] https://github.com/metabase/metabase/issues/40812
- [ ] https://github.com/metabase/metabase/pull/41622
- [ ] https://github.com/metabase/metabase/issues/41467
- [ ] https://github.com/metabase/metabase/issues/42503
```

```[tasklist]
## Milestone 2 - use RTK query instead of entity loaders
- [x] https://github.com/metabase/metabase/issues/44301
- [ ] https://github.com/metabase/metabase/issues/50317
- [ ] https://github.com/metabase/metabase/issues/43630
- [ ] alerts
- [ ] bookmarks
- [ ] dashboards
- [ ] database-candidates
- [ ] databases
- [ ] fields
- [ ] groups
- [ ] metrics
- [ ] persisted-models
- [ ] https://github.com/metabase/metabase/issues/41845
- [ ] pulses
- [ ] questions
- [ ] https://github.com/metabase/metabase/issues/41844
- [ ] revisions
- [ ] schemas
- [ ] search
- [ ] segments
- [ ] snippet-collections
- [ ] snippets
- [ ] tables
- [ ] https://github.com/metabase/metabase/issues/41580
- [ ] timeline-events
- [ ] timelines
- [ ] users
```
```[tasklist]
### Followups
- [ ] https://github.com/metabase/metabase/issues/41511
```

# Other endpoints
```[tasklist]
## Milestone 3
- [ ] services.js
```
