### ISSUE TITLE
Migrate anonymous tracking to Snowplow

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#40868]
There is a new [product doc](https://www.notion.so/metabase/Migrate-Anonymous-Stats-ping-to-Snowplow-18f155e235d34ba09f45518a866336e2?pvs=4)

```[tasklist]
### Tasks
- [ ] Milestone 1: initial migration and essential fields
- [ ] Milestone 2: extra features
- [ ] Milestone 3: extra metrics
```
