### ISSUE TITLE
[Epic] Fix FE metadata issues with duplicate columns

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#40898]
Fixes the FE part of https://github.com/metabase/metabase/issues/36185
RTK query epic https://github.com/metabase/metabase/issues/40788

The underlying problem is that the FE normalizes all API data. For fields, the FE uses `field.id:field.table_id` for the key, which is not unique in case there is a model with metadata overrides where different query columns are mapped to the same field in the database. If this happens, the FE overwrites one field with another. From this point MBQL lib cannot function properly because metadata is incorrect.

Our solution to this issue is to construct metadata for MBQL lib using raw API data. New metadata object would have this shape:
```
{
  databases: Record<DatabaseId, Database>;
  tables: Record<TableId, Table>;
  fields: Record<FieldId, Field>;
  cards: Record<CardId, Card>;
}
```

We would group entities from responses by ID but won't do any normalization. E.g. if each `table` has `fields`, they would be passed unchanged and won't appear in the top-level `fields` property. MBQL lib should be updated to use this new format instead of the current one. It's very close to what we already have and shouldn't result in massive changes.

**Milestone 1 - replace api handlers in entities** - done

Part of milestone 1 in the [RTK query epic](https://github.com/metabase/metabase/issues/40788)

**Milestone 2 - use RTK query and entity framework caching for metadata requests**

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/43628
- [ ] https://github.com/metabase/metabase/issues/43629
- [ ] https://github.com/metabase/metabase/pull/44721
```

**Comment by kamilmielnik** [comment]
I moved #44301, #44491, #44492 & #43630 to the RTK Query epic: #40788

#44721 was the PR that allowed us to fix field-related FE metadata issues without a large RTK Query refactoring - I added it to this epic.

Epic is complete. Closing.
