### ISSUE TITLE
[Epic] Modularize, rework, and improve search

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#40964]
```[tasklist]
### Beta-ready
- [ ] https://github.com/metabase/metabase/issues/50778
```

```[tasklist]
### Release-ready
- [ ] Performance measurements
- [x] Do not reindex on restarts
- [x] An exact matcher
```

```[tasklist]
### Tiding things up
- [ ] Engine-independent index table definition
- [ ] https://github.com/metabase/metabase/issues/50206
``` 

----

# Previous version

```[tasklist]
### M1: minimal search
- [x] Minimal index management: delete/create/fill
- [x] Fill index with data: Questions (no Metrics/Models), Dashboards
- [x] Search query
- [x] Integrate with REST API (cookie + querystring to switch it)
- [x] Hide behind setting
- [x] https://github.com/metabase/metabase/pull/47752
- [x] Populate index on bootstrap
- [x] API to trigger synchronous re-indexing
- [ ] https://github.com/metabase/metabase/pull/47846
- [x] Search does completion
- [x] Faster model set
- [x] Skip ranking
- [ ] https://github.com/metabase/metabase/pull/48053
- [x] Filter models
- [x] Bug: model etc selectors not populated the same
```

```[tasklist]
### M2: replacing current search
- [x] More models
- [x] Batch insertion
- [x] Permissions
- [x] Replace index periodically via task
- [x] Update API to trigger the task, rather that reindexing directly
- [ ] https://github.com/metabase/metabase/pull/49335
- [ ] https://github.com/metabase/metabase/pull/49327
- [ ] https://github.com/metabase/metabase/pull/49422
- [x] Indexed Entity models
- [x] Handle archived filtering (hard off for some models)
- [ ] https://github.com/metabase/metabase/pull/49520
- [ ] https://github.com/metabase/metabase/pull/49484#pullrequestreview-2413389272
- [ ] https://github.com/metabase/metabase/pull/49660
- [ ] https://github.com/metabase/metabase/pull/49777
- [ ] https://github.com/metabase/metabase/pull/49824
- [ ] https://github.com/metabase/metabase/pull/49825
- [x] Clean up filter mapping
- [ ] https://github.com/metabase/metabase/pull/49842
- [ ] https://github.com/metabase/metabase/pull/49861
- [ ] https://github.com/metabase/metabase/pull/49666
- [ ] https://github.com/metabase/metabase/pull/49866
- [ ] https://github.com/metabase/metabase/pull/49899
- [ ] https://github.com/metabase/metabase/pull/49933
- [ ] https://github.com/metabase/metabase/pull/49951
- [ ] https://github.com/metabase/metabase/pull/50001
- [ ] https://github.com/metabase/metabase/pull/50019
- [ ] https://github.com/metabase/metabase/pull/50071
- [ ] https://github.com/metabase/metabase/pull/50046
- [ ] https://github.com/metabase/metabase/pull/50126
- [ ] https://github.com/metabase/metabase/issues/50204
- [ ] https://github.com/metabase/metabase/issues/50205
- [ ] https://github.com/metabase/metabase/issues/50206
- [ ] https://github.com/metabase/metabase/issues/50261
- [x] Smart bootstrapping - don't blow away the index if the schema is correct
```

```[tasklist]
### M3: making search better
- [ ] Only search completions in the command palette context
- [ ] Handle synonyms
- [ ] Better stemming
```

```[tasklist]
### M4: semantic search
- [ ] Option to enable (system setting, check for pg_vector)
- [ ] Model downloader
- [ ] Generate embeddings
```

**Comment by crisptrutski** [comment]
- [ ] Pinned weight 0 by default

**Comment by luizarakaki** [comment]
Closing this one in favor of https://github.com/metabase/metabase/issues/50927 that contains the related work to ship the experimental version on 52 and make it GA on 53 (and remove old search)
