### ISSUE TITLE
Cache UI: Follow-up work

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#40978]
```[tasklist]
### Follow up work for cache UI
- [x] Measure minimum query duration in seconds (#40970)
- [x] Change default minimum query duration to 1 second (not 60 seconds) (#40970)
- [x] Add 'Invalidate now' button (#40972)
- [x] Move Invalidate now button to the top of the form along with the name of the database (#40972)
- [x] Create DelayedSpinner component (#41103)
- [ ] Add e2e tests. This will be complicated, since our test of the old cache invalidation UI was disabled due to a bug
- [ ] Ensure that form fields can be tabbed into even when behind form buttons div (I have this in a branch but I'm not sure it's worth pursuing)
- [x] Rename TTL to Multiplier
- [x] [not planned] Tweak: remove value from inputs (and just show placeholder) if it matches the default (and ensure form dirty status is correct)
- [ ] Polish: delay all spinners by 300 ms
- [ ] Try Ryan's suggestion to avoid the useVerticallyOverflows hook (https://app.graphite.dev/github/pr/metabase/metabase/39234/Basic-cache-admin-UI?utm_source=gt-slack-notif#comment-PRRC_kwDOAczgH85cTMwl)
- [ ] Explore Ryan's suggestion to use different forms for different strategies (https://app.graphite.dev/github/pr/metabase/metabase/39234/Basic-cache-admin-UI?utm_source=gt-slack-notif#comment-PRRC_kwDOAczgH85cTRiE)
- [ ] https://github.com/metabase/metabase/issues/41119
```

**Comment by rafpaf** [comment]
I've moved this list into the epic issue: https://github.com/metabase/metabase/issues/39153
