### ISSUE TITLE
[Epic] Let users change the filter type after creation

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#41037]
**Links**
- 📔 [product doc](https://www.notion.so/metabase/Let-users-change-the-filter-type-after-creation-514c727bb17c48cc8bad24d91e9423df)
- feature branch: `change-filter-type`
- issue links: 
	- https://github.com/metabase/metabase/issues/14296
	- https://github.com/metabase/metabase/issues/20048
- 📔  [testing plan](https://www.notion.so/metabase/Testing-plan-84e93a971dc44974b177cbadc083612b)

**Implementation Plan**

***Milestone 1***
```[tasklist]
### Reworking to Mantine
- [ ] https://github.com/metabase/metabase/issues/41140
- [ ] https://github.com/metabase/metabase/issues/41174
``` 

***Milestone 2***
```[tasklist]
### Add changing type to the sidebar
- [ ] https://github.com/metabase/metabase/issues/41168
``` 

***Milestone 3***
```[tasklist]
### Removing mapping
- [ ] https://github.com/metabase/metabase/issues/41331
- [ ] https://github.com/metabase/metabase/issues/41371
```

***Milestone 4***
```[tasklist]
### Changing operator
- [ ] https://github.com/metabase/metabase/issues/41396
- [ ] https://github.com/metabase/metabase/issues/41313
- [ ] https://github.com/metabase/metabase/issues/41475
```

***Milestone 5***
```[tasklist]
### Handle Native questions
- [ ] https://github.com/metabase/metabase/issues/41397
- [ ] https://github.com/metabase/metabase/issues/41647
``` 

***Milestone 6***
```[tasklist]
### Preserving mappings
- [ ] https://github.com/metabase/metabase/issues/41658
``` 

***Milestone 7***
```[tasklist]
### Follow-ups
- [ ] https://github.com/metabase/metabase/issues/42198
- [ ] https://github.com/metabase/metabase/issues/42196
- [ ] https://github.com/metabase/metabase/issues/42197
- [ ] https://github.com/metabase/metabase/issues/42163
- [ ] https://github.com/metabase/metabase/issues/42105
- [ ] https://github.com/metabase/metabase/issues/41517
- [ ] https://github.com/metabase/metabase/issues/42104
```
