### ISSUE TITLE
[Epic] Improve code-splitting

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#41032]
Our existing code-splitting strategy does not provide optimal loading performance. Currently, all libraries go into the `vendor` bundle resulting in 5.66 MB (1.38 gzipped) and all of our code is included into `app-*` bundle which results in 4.25 MB (1.11 gzipped). These sizes impact the application startup time which delays data fetching requests:
<img width="617" alt="Screenshot 2024-04-04 at 11 37 33 AM" src="https://github.com/metabase/metabase/assets/14301985/93375c22-5088-4b67-8aa7-c40bf7ad9916">

Current bundle analyzer snapshot
<img width="1726" alt="Screenshot 2024-04-04 at 11 21 40 AM" src="https://github.com/metabase/metabase/assets/14301985/369b4c7d-95f6-4ff1-85a0-a68befff8acf">

A few things can be improvide. Firstly, we can start by splitting out rarely used heavy libraries like we already do with the sql-formatter. Then we need to split the app into chunks by areas. For example, dashboards may not need all the code of the QueryBuilder which includes almost the heaviest dependency `ace`.

**Implementation Plan**

- [ ] Asynchronously load big chunks for rare one-time operations: pdf downloads, png downloads
- [ ] Detach query builder chunk
- [ ] Detach admin panel chunk
- [ ] Detach collections chunk
- [ ] Detach visualizations chunk
- [ ] Detach dashboards chunk
- [ ] Add CI check to ensure the chunks size keeps being reasonable

**Comment by uladzimirdev** [comment]
related https://github.com/metabase/metabase/issues/42550
