### ISSUE TITLE
[Mega Epic] Embedding SDK

### ISSUE THREAD

**Issue by deniskaber** [metabase/metabase#41095]
**Links**
- product doc: https://www.notion.so/metabase/Embedding-ccadeca5900e44428b2ed87f96a1beb1
- eng doc: https://www.notion.so/metabase/Embedding-SDK-Roadmap-02d1fba72171455bb3496d7d996cd302

**Implementation Plan**

***Milestone 1 – PoC***

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/39115
```

***Milestone 2 – Technical foundation***

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/40241
- [ ] https://github.com/metabase/metabase/issues/38811
- [ ] https://github.com/metabase/metabase/pull/40975
```

***Milestone 3 – Single question w/ drill-down***

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/41106
- [ ] https://github.com/metabase/metabase/pull/41560
- [ ] https://github.com/metabase/metabase/pull/41860
- [ ] Fixup `window.history` usages in QueryVisualization component
```
