### ISSUE TITLE
[Epic] In-Product Upsells (part 1)

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#41116]
**Links**
- [product doc](https://www.notion.so/metabase/Upsells-System-4d198833c10d4f89a2ddfe407b2ef026)
- [another product doc](https://www.notion.so/metabase/Implement-upsell-system-part-1-1f01945a71b845c4870ac1b37ec93632?pm=c)
- [design doc](https://www.notion.so/metabase/Upsell-System-Guidelines-WIP-72ce6f7402fb4c93a165e904dcf7a93c)
- [eng doc](https://www.notion.so/metabase/Upsells-Engineering-Plan-32229bdbaaf84e59be135e5af9227f42)
- [figma designs](https://www.figma.com/file/kdZZogH2tWBVwnG03N7XXc/Upsell-System?type=design&node-id=232-4979&mode=design&t=URjxcPyUA9YXCG8H-0)
- [slack discussion](https://metaboat.slack.com/archives/C064EB1UE5P/p1711980324110339)

```[tasklist]
### Preliminary: Generic/Reusable Components
- [x] Wrapper HoC to control when components appear
- [x] Create Generic Upsell Badge
- [x] Create Generic Upsell Card
- [x] Implement UTM linking/tracking
- [x] add plan info to UTM
- [ ] https://github.com/metabase/metabase/issues/42802
- [ ] Add hoverGem component
- [x] Remove `utm_` from the `source_plan` parameter
```

```[tasklist]
### Specific Upsell Components
- [ ] https://github.com/metabase/metabase/issues/42706
- [ ] https://github.com/metabase/metabase/issues/42708
- [ ] https://github.com/metabase/metabase/issues/42707
- [ ] https://github.com/metabase/metabase/issues/42713
- [ ] https://github.com/metabase/metabase/issues/42828
```

**Comment by luizarakaki** [comment]
Closing this epic as the work expected for part 1 is done.
Following work will be done in [#42846](https://github.com/metabase/metabase/issues/42846)
