### ISSUE TITLE
[Epic] Custom column expression shortcuts

### ISSUE THREAD

**Issue by romeovs** [metabase/metabase#41177]
[product doc](https://www.notion.so/metabase/Custom-expression-snippet-to-combine-columns-858e52c35829436ab9ef89bcfdd4b2c2)
[technical doc](https://www.notion.so/metabase/Tech-Combine-shortcuts-for-custom-columns-a527ffcd30314f388215a79e3b416de4)
[testing plan](https://github.com/metabase/metabase/issues/41782)

Feature branch: [`notebook-expression-shortcuts`](https://github.com/metabase/metabase/tree/notebook-expression-shortcuts)

### Milestone 1: Combine columns

```[tasklist]
#### Backend
- [x] Add support for previewing the result of an expression on a column `Lib.previewExpression`
```

```[tasklist]
#### Frontend
- [ ] https://github.com/metabase/metabase/issues/41178
- [x] https://github.com/metabase/metabase/issues/41766
- [ ] https://github.com/metabase/metabase/issues/41350
```

### Milestone 3: Extract columns

```[tasklist]
#### Frontend
- [ ] https://github.com/metabase/metabase/issues/41504
- [ ] https://github.com/metabase/metabase/issues/42093
```
