### ISSUE TITLE
Product Iteration - Split data permissions UI

### ISSUE THREAD

**Issue by sloansparger** [metabase/metabase#41221]
```[tasklist]
### Tasks
- [x] Add a warning at the top of the permissions table if permissions graph contains Legacy No Self Service
- [x] Add warning that native query permissions will be removed from all tables if it's currently selected and the user is createing granular permissions for a table
- [x] Update warning when sandboxing a table should also notify the user that native query permissions will be removed from all tables/schemas if native is selected
```
