### ISSUE TITLE
Migrate global css in `frontend/src/metabase/css/core/rounded.module.css`, `frontend/src/metabase/css/core/shadow.module.css`, `frontend/src/metabase/css/core/transitions.module.css`, `frontend/src/metabase/css/core/width.module.css`, `frontend/src/metabase/query_builder/components/DataSelector/DataSelector.module.css`

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#41356]
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/41357
- [ ] https://github.com/metabase/metabase/pull/41359
- [ ] https://github.com/metabase/metabase/pull/41360
- [ ] https://github.com/metabase/metabase/pull/41361
- [ ] https://github.com/metabase/metabase/pull/41362
```
