### ISSUE TITLE
[Cache] Milestone 2: Follow-up work including "Invalidate now"

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#41426]
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/41433
- [x] Measure minimum query duration in seconds (#40970)
- [x] Change default minimum query duration to 1 second (not 60 seconds) (#40970)
- [x] Move Invalidate now button to the top of the form along with the name of the database (#40972)
- [x] Create DelayedSpinner component (#41103)
- [x] Rename TTL to Multiplier
- [x] [not planned] Tweak: remove value from inputs (and just show placeholder) if it matches the default (and ensure form dirty status is correct)
- [x] [won't fix] Ensure that form fields can be tabbed into even when behind form buttons div (I have this in a branch but I'm not sure it's worth pursuing)
```
