### ISSUE TITLE
[Cache] Milestone 8: final polish (up next: Migrate CacheConfigApi to RTK)

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#41455]
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/42635
- [ ] https://github.com/metabase/metabase/issues/41119
- [x] Add e2e tests. This will be complicated, since our test of the old cache invalidation UI was disabled due to a bug
- [x] Try Ryan's suggestion to avoid the useVerticallyOverflows hook (https://app.graphite.dev/github/pr/metabase/metabase/39234/Basic-cache-admin-UI?utm_source=gt-slack-notif#comment-PRRC_kwDOAczgH85cTMwl)
- [ ] https://github.com/metabase/metabase/issues/41606
```

Not currently planned:
* Explore Ryan's suggestion to use different forms for different strategies (https://app.graphite.dev/github/pr/metabase/metabase/39234/Basic-cache-admin-UI?utm_source=gt-slack-notif#comment-PRRC_kwDOAczgH85cTRiE)
