### ISSUE TITLE
[Browse] Milestone 1: Enhance the ItemsTable and use it to list models

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#41591]
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/41909
- [ ] https://github.com/metabase/metabase/issues/41911
- [ ] https://github.com/metabase/metabase/issues/41912
- [ ] https://github.com/metabase/metabase/pull/41952
- [ ] https://github.com/metabase/metabase/issues/41908
- [ ] https://github.com/metabase/metabase/pull/41955
- [ ] https://github.com/metabase/metabase/issues/41603
- [ ] https://github.com/metabase/metabase/pull/41959
- [ ] https://github.com/metabase/metabase/pull/41960
- [ ] https://github.com/metabase/metabase/pull/42113
- [ ] https://github.com/metabase/metabase/pull/42111
```

**Comment by dpsutton** [comment]
this seems like a duplicate layer of https://github.com/metabase/metabase/issues/41603
