### ISSUE TITLE
[Epic] Browse models

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#41590]
**Links**
- [product doc](https://www.notion.so/metabase/Alignment-on-direction-for-Browse-Data-Models-v0-2-dbc94b4f013f4f59be309728f89bf143?pvs=26&qid=)
- [design loom](https://www.loom.com/share/fed338145e6e44c3b99b3c82b1c44913)

```[tasklist]
### Milestones
- [ ] https://github.com/metabase/metabase/issues/41591
- [ ] https://github.com/metabase/metabase/issues/42696
- [ ] https://github.com/metabase/metabase/issues/42298
```

```[tasklist]
### Post RC
- [ ] #42952
- [ ] #42570
```
