### ISSUE TITLE
[Browse] Add list of models to /browse/models

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#41603]
```[tasklist]
### Tasks
- [x] Add list
- [x] Add column: description
- [x] Add column: collection
- [x] Remove ellipsis menu from list of models
- [x] Remove title of 'type' column
- [x] Remove column: Last edited by
- [x] Remove column: Last edited at
- [x] possible refactor: port ItemsTable to TS
- [x] Make filters work again
- [x] Add popover for filters
- [x] Make non-drag-'n'-droppable
- [x] Make Browse databases work
- [x] Make Browse schemas work
- [x] Make Browse tables work
- [x] Make collection breadcrumbs responsive
```
