### ISSUE TITLE
[Epic] Improve pulse performance and debuggability

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#41764]
**Links**
- eng doc: https://www.notion.so/metabase/Improve-Pulse-performance-and-debuggability-caa4921e7376452f8c721d30eb3a7bb9?pvs=4
- GH issues:
- https://github.com/metabase/metabase/issues/14613
- https://github.com/metabase/metabase/issues/38800
- https://github.com/metabase/metabase/issues/6648
- https://github.com/metabase/metabase/issues/3846
- https://github.com/metabase/metabase/issues/12084
- https://github.com/metabase/metabase/issues/8416
- https://github.com/metabase/metabase/issues/9436

```[tasklist]
### Milestone 1: Parallelizing send pulses (BE only)
- [ ] https://github.com/metabase/metabase/pull/41772
- [ ] https://github.com/metabase/metabase/pull/42331
```

```[tasklist]
### Milestone 2: Better granularity for pulse (postponed)
- [ ] BE: rework pulse_channel schema to accept a cron_schedule
- [ ] BE: rework API endpoints to accept cron_schedule
- [ ] FE: Update UI to now send a cron_schedule have better granularity config
```

```[tasklist]
### Milestone 3: Improve taskhistory
- [ ] https://github.com/metabase/metabase/pull/42372
```

```[tasklist]
### Milestone 4: Clean up SendPulse task when archiving dashboard
- [ ] https://github.com/metabase/metabase/pull/42558
```

**Comment by qnkhuat** [comment]
We've decided to postpone milestone 2 as we might refactor pulse soon.
