### ISSUE TITLE
[Epic] Extract column in chill mode follow-ups

### ISSUE THREAD

**Issue by romeovs** [metabase/metabase#41770]
[product doc](https://www.notion.so/metabase/Extract-column-in-chill-mode-follow-ups-f6dd3184a3334544b844a61dd74d0b78)

## Implementation Plan

```[tasklist]
### Milestone 1
- [x] Add "domain name and top level domain" option (BE)
- [ ] https://github.com/metabase/metabase/issues/41771
- [ ] https://github.com/metabase/metabase/pull/41484
- [ ] https://github.com/metabase/metabase/pull/41540
- [ ] https://github.com/metabase/metabase/pull/41548
- [ ] https://github.com/metabase/metabase/issues/41773
- [ ] https://github.com/metabase/metabase/issues/42096
- [ ] https://github.com/metabase/metabase/issues/41350
```
