### ISSUE TITLE
FE: handle new "move to trash" / "restore" functionality for collections/dashboards/models/questions

### ISSUE THREAD

**Issue by sloansparger** [metabase/metabase#41914]
```[tasklist]
### Tasks
- [x] add "restore" options to trash collection items
- [x] add archive banner to allow users to "restore" an archived entity while viewing it
- [x] enable users to view item in collection upon restoring an item
- [x] bug - dashboards/questions/models pages do not automatically show state updates + requires refresh to see archive/unarchive/delete
```
