### ISSUE TITLE
FE: implement updated archive UI

### ISSUE THREAD

**Issue by sloansparger** [metabase/metabase#41913]
```[tasklist]
### Tasks
- [x] make trash collection not expandable in sidebar
- [x] add trash icon to trash collection in sidebar
- [x] add extra spacing above trash collection in sidebar
- [x] update "Archive" copy to "Move to trash" in collection list items
- [x] table headers should mention deleted by / deleted at instead of modified for trash collection
- [x] impl new empty trash collection state
- [x] don't render pins in root trash collection
```
