### ISSUE TITLE
FE: allow users to view archived question/models results while logged in

### ISSUE THREAD

**Issue by sloansparger** [metabase/metabase#41915]
```[tasklist]
### Tasks
- [x] allow users to view archive questions + models and hide/disable any edit action
- [x] allow users to view archive models and hide/disable any edit action
- [x] allow users to view archive collections and hide/disable any edit action
```
