### ISSUE TITLE
[Epic] Basic theming for React embedding SDK

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#41947]
Allow SDK users to customize the appearance of React components in the interactive embedding SDK, by exposing a theme configuration prop to the MetabaseProvider.

We achieve this by converting a subset of Emotion components to use Mantine components from `metabase/ui`. This would allow a subset of user's themes (e.g. color palette, fonts, base font sizes) to be applied to the embedded components, such as tables, popovers and filters.

In addition, we will expose custom theme configurations for users to be able to customize specific theme options, which is then merged/injected into target component's styles. This epic focuses on basic theming to match the SDK user's app branding, such as color palette, base font sizes, font family and line height.

**Links**
- [product doc](https://www.notion.so/metabase/Theming-CSS-overrides-c2522c9fb85d43669cf86e650a27bf68?pvs=4)
- [tech doc](https://www.notion.so/metabase/Metabase-Embedding-SDK-for-React-theming-milestones-867fcecba0f74abd8158b6cd3164cac4?pvs=4)
- feature branch: `embedding-sdk-theming`

**Implementation Plan**

***Milestone 1***
```[tasklist]
### Expose theme configuration to MetabaseProvider
- [ ] https://github.com/metabase/metabase/issues/41948
- [ ] https://github.com/metabase/metabase/issues/42201
- [ ] https://github.com/metabase/metabase/issues/42214
```

***Milestone 2***
```[tasklist]
### Basic theming for question visualizations
- [ ] https://github.com/metabase/metabase/issues/41949
- [ ] https://github.com/metabase/metabase/issues/42157
- [ ] https://github.com/metabase/metabase/issues/42321
- [ ] https://github.com/metabase/metabase/issues/42199
- [ ] https://github.com/metabase/metabase/issues/42159
- [ ] https://github.com/metabase/metabase/issues/42158
```

***Milestone 3***
```[tasklist]
### Basic theming for interactive questions
- [ ] https://github.com/metabase/metabase/issues/42560
```

**Comment by heypoom** [comment]
@albertoperdomo @NevRA note that all tasks on this epic are merged, therefore let's close it.
