### ISSUE TITLE
[Epic] Selecting multiple values for all text filters

### ISSUE THREAD

**Issue by bshepherdson** [metabase/metabase#41956]
**Links**
- [Product doc](https://www.notion.so/Offer-the-ability-to-select-multiple-values-for-all-text-filters-e41ed1d75702473683967ba57dd3a331?pvs=24)
- [Eng doc](https://www.notion.so/metabase/Tech-Selecting-multiple-values-for-all-text-filters-83aa3b8a803741e2b2e94e242cec85f3)
- Feature branch: None needed?

**Implementation Plan**
The goal of this milestone to have the feature parity with the current behavior for "Is" (`=`) and "Is not" (`!=`) filters.

```[tasklist]
## Milestone 1 (query builder)
- [x] #41958 
- [x] #42101 ([Figma](https://www.figma.com/file/9ya59GapN0pG4wOExkLsH1/Offer-the-ability-to-select-multiple-options-for-dropdowns-for-all-text-filters?type=design&node-id=4058-6459&mode=design&t=NmuEmlCotcDeQQPk-0))
```

```[tasklist]
## Milestone 2 (dashboard)
- [ ] https://github.com/metabase/metabase/pull/42404
- [ ] Expand the dashboard filters to allow multi-select ([Figma](https://www.figma.com/file/9ya59GapN0pG4wOExkLsH1/Offer-the-ability-to-select-multiple-options-for-dropdowns-for-all-text-filters?type=design&node-id=4058-6531&mode=design&t=GZcx7ktU7yCQ6HnQ-0)) (https://github.com/metabase/metabase/pull/42013)
```
