### ISSUE TITLE
Beef up Recents 🥩 

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#41957]
related to https://github.com/metabase/metabase/issues/39528
[product doc ](https://www.notion.so/metabase/Add-Recents-tab-to-the-new-EntityPicker-component-895cd80f2b0f4e56a008a82b436c3a00?pm=c)

For the new recent item picker, we're going to need some changes to the activity/recents api

- We need to track the most recent 20 items that each user has "touched" (ie viewed) of each entity type	
	- question
	- model
	- table (probably don't need right now)
	- dashboard
	- collection
- for a collection to be "recently viewed" [means](https://metaboat.slack.com/archives/C064EB1UE5P/p1714504102513489?thread_ts=1714169076.361039&cid=C064EB1UE5P) that:
	- the collection was created
	- a dashboard or question was saved in the collection
	- a dashboard, question, or collection was moved into the collection
- We also need more information about each item than the current api provides
	- `can_write`
	- `last_touched` or some sort of proxy for sorting by most recently used (i think this is what the timestamp field in the recent_views table is doing)
	- parent information - collection name + authority level (eventually parent db for tables)
- While we're at it, can we make the payload for the recents endpoint conform more closely to search and/or collection items?
	- 	nesting `model_object` inside each recent item is a weird pattern that's used nowhere else and is completely unnecessary, we can just populate a `model` property on each item like we do elsewhere
	- we should probably update the popular items api to match

### Desired RecentItem Shape
(open to discussion)

```ts
interface RecentItem {
  id: number;
  name: string;
  model: string; // should differentiate between regular cards and "dataset" for models
  can_write: boolean;
  display: string; // for questions
  parent_collection: { // for non-tables
    id: number;
    name: string;
    authority_level: "official" | null; // for collections
  } | null;
  database: { // for tables
    id: number;
    name: string; // display name
  } | null;
  authority_level: "official" | null; // for collections
  moderated_status: "verified" | null; // for models
  timestamp: string; // last touched
}
```
```[tasklist]
### Tasks
- [x] update return from /activity/recent_views
- [x] track models as distinct from cards
- [x] update recents to preserve inside category (not just last 30 whatevers, but 20 cards, 20 dashboards, etc...)
- [x] Capture collection uses (add event for collection creation, event for moving card, dash, collection)
- [x] update /popular_items return shape to match recent_views
- [x] https://github.com/metabase/metabase/issues/42665
```
