### ISSUE TITLE
Support combo stacked charts

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#41976]
PRD: https://www.notion.so/metabase/Add-support-for-combo-stacked-bar-charts-3f04bf541bcc4976bb81886d5c8bcd29

```[tasklist]
### Milestone 1: support combo stacking only on Combo viz type
- [ ] https://github.com/metabase/metabase/pull/42085
- [ ] https://github.com/metabase/metabase/issues/42195
- [ ] https://github.com/metabase/metabase/pull/42600
```
