### ISSUE TITLE
[Epic] Let time granularity be parameterized for MBQL questions

### ISSUE THREAD

**Issue by bshepherdson** [metabase/metabase#42118]
**Links**
- [product doc](https://www.notion.so/metabase/Let-time-granularity-be-parametrized-41a26d41cc414806b92929e0e4c859a6)
- [eng doc](https://www.notion.so/metabase/Tech-Let-time-granularity-be-parametrized-for-MBQL-questions-0e14410d4d90478481be6412fb473914)
- No feature branch yet; early QP features can land in master.
- issue links: _related issues if any_

**Implementation Plan**

***Milestone 1: Core functionality***

- [ ] BE: Expand `:type :temporal-unit` parameters when running a query
- [ ] BE: Support saving and returning `:type :temporal-unit` parameters and mappings
- [ ] FE: Create/edit/delete `temporal-unit` parameters
- [ ] FE: New parameter widget for this type
- [ ] FE: Allow mapping `temporal-unit` parameters to cards

***Milestone 2: Autowiring***

- [ ] FE: Add autowiring for `temporal-unit` parameters

***Milestone 3: Allowlist of temporal units***

- [ ] BE: Support saving and returning this setting (probably Just Works; but test it)
- [ ] FE: Allow configuring `temporal unit` parameters to allow only a subset of the units
- [ ] FE: Update the widget to only show the allowed subset
