### ISSUE TITLE
[Epic] Databricks JDBC

### ISSUE THREAD

**Issue by lbrdnk** [metabase/metabase#42262]
**Links**
- product doc: N/A
- eng doc: N/A
- feature branch: [`databricks-jdbc`](https://github.com/metabase/metabase/tree/databricks-jdbc)

**Implementation Plan**

```[tasklist]
### Impl
- [x] Implement driver base
- [x] Make sync work
- [x] Examine usability of existing tests
- [ ] https://github.com/metabase/metabase/issues/43497
- [ ] https://github.com/metabase/metabase/issues/43854
- [ ] https://github.com/metabase/metabase/issues/43857
- [ ] https://github.com/metabase/metabase/issues/43858
- [ ] https://github.com/metabase/metabase/issues/44083
```
Further tasks will be added based on results of existing.
