### ISSUE TITLE
[Browse] Milestone 3: Cleanup

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#42298]
```[tasklist]
### Tasks
- [ ] #42964
- [ ] https://github.com/metabase/metabase/issues/43014
- [ ] https://github.com/metabase/metabase/issues/42951
- [ ] https://github.com/metabase/metabase/issues/43253
- [x] Add ellipsis to descriptions
- [ ] #43251
- [ ] https://github.com/metabase/metabase/issues/42781
- [ ] https://github.com/metabase/metabase/issues/44157
```
