### ISSUE TITLE
[Epic] Clickhouse upload CSV support for Cloud

### ISSUE THREAD

**Issue by calherries** [metabase/metabase#42294]
CH supporting CSV uploads supports https://github.com/metabase/harbormaster/issues/4931

```[tasklist]
###
- [ ] https://github.com/metabase/metabase/pull/42359
- [x] https://github.com/metabase/metabase/pull/42531
- [ ] https://github.com/ClickHouse/metabase-clickhouse-driver/pull/236
- [ ] https://github.com/metabase/metabase/pull/42851
- [ ] https://github.com/metabase/metabase/pull/42869
- [ ] https://github.com/ClickHouse/metabase-clickhouse-driver/pull/239
```

**Comment by calherries** [comment]
This is currently waiting on the ClickHouse driver release for 50: https://github.com/ClickHouse/metabase-clickhouse-driver/pull/239
