### ISSUE TITLE
Add Upload CSVs button for customers with feature flag

### ISSUE THREAD

**Issue by trinya** [metabase/metabase#42381]
**Context**

Customers can have a `DWH` subscription.

**Proposal**

Add a `CSV upload` button for these customers when the feature flag:

```
attached-dwh = ON
```

See [designs](https://www.figma.com/file/zzRODww44883ojSwMlUT9E/Baby-Data-Warehouse---Milestone-3---CSV-entrypoints?type=design&node-id=1520-32973&mode=design&t=m2BuyOFqyajLn9EC-4).

related to: https://github.com/metabase/harbormaster/issues/4931

```[tasklist]
### Tasks
- [x] Add new DWH plans to settings and Plan
- [x] Show the `Upload CSVs` button on the left navigation
- [x] When the button is clicked, it should launch the uploading CSVs file dialog and proceed to the CSV upload (to the attached storage that should be pre-enabled for these customers)
- [x] When the button is clicked, send a Snowplow event: `csv_upload_clicked`, source: `left_nav`
- [ ] Write relevant e2e tests
```
