### ISSUE TITLE
[Epic] Modular Backend

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#42434]
[https://www.notion.so/metabase/Backend-Modularization-2025-Plan-17669354c90180b98bd4eb9c8ccf2395](https://www.notion.so/metabase/Backend-Modularization-2025-Plan-17669354c90180b98bd4eb9c8ccf2395)

```[tasklist]
- [ ] #42250
- [ ] #42433
- [ ] https://github.com/metabase/metabase/pull/42436
- [ ] https://github.com/metabase/metabase/pull/42437
- [ ] https://github.com/metabase/metabase/pull/42468
- [ ] https://github.com/metabase/metabase/pull/42469
- [ ] https://github.com/metabase/metabase/pull/42487
- [ ] https://github.com/metabase/metabase/pull/42491
- [ ] https://github.com/metabase/metabase/pull/48640
- [ ] https://github.com/metabase/metabase/pull/50839
- [ ] [Backend modularization] `enterprise/advanced-config`
- [ ] [Backend modularization] `enterprise/advanced-permissions`
- [ ] [Backend modularization] `enterprise/airgap`
- [ ] [Backend modularization] `enterprise/advanced-config`
- [ ] [Backend modularization] `enterprise/advanced-permissions`
- [ ] [Backend modularization] `enterprise/airgap`
- [ ] [Backend modularization] `enterprise/api`
- [ ] [Backend modularization] `enterprise/audit-app`
- [ ] [Backend modularization] `enterprise/auth-provider`
- [ ] [Backend modularization] `enterprise/billing`
- [ ] [Backend modularization] `enterprise/cache`
- [ ] [Backend modularization] `enterprise/content-verification`
- [ ] [Backend modularization] `enterprise/core`
- [ ] [Backend modularization] `enterprise/dashboard-subscription-filters`
- [ ] [Backend modularization] `enterprise/enhancements`
- [ ] [Backend modularization] `enterprise/llm`
- [ ] https://github.com/metabase/metabase/issues/52183
- [ ] [Backend modularization] `enterprise/query-reference-validation`
- [ ] [Backend modularization] `enterprise/sandbox`
- [ ] [Backend modularization] `enterprise/scim`
- [ ] [Backend modularization] `enterprise/search`
- [ ] [Backend modularization] `enterprise/serialization`
- [ ] [Backend modularization] `enterprise/snippet-collections`
- [ ] [Backend modularization] `enterprise/sso`
- [ ] [Backend modularization] `enterprise/stale`
- [ ] [Backend modularization] `enterprise/stats`
- [ ] [Backend modularization] `enterprise/task`
- [ ] [Backend modularization] `enterprise/upload-management`
- [ ] https://github.com/metabase/metabase/issues/52169
- [ ] [Backend modularization] `analytics`
- [ ] https://github.com/metabase/metabase/issues/52178
- [ ] [Backend modularization] `api`
- [ ] https://github.com/metabase/metabase/issues/52224
- [ ] [Backend modularization] `audit`
- [ ] [Backend modularization] `auth-provider`
- [ ] https://github.com/metabase/metabase/issues/52154
- [ ] https://github.com/metabase/metabase/issues/52238
- [ ] [Backend modularization] `cmd`
- [ ] https://github.com/metabase/metabase/issues/52176
- [ ] [Backend modularization] `config`
- [ ] https://github.com/metabase/metabase/issues/52153
- [ ] https://github.com/metabase/metabase/issues/52174
- [ ] [Backend modularization] `driver`
- [ ] [Backend modularization] `eid-translation`
- [ ] https://github.com/metabase/metabase/issues/52237
- [ ] [Backend modularization] `embed`
- [ ] [Backend modularization] `events`
- [ ] [Backend modularization] `formatter`
- [ ] [Backend modularization] `integrations`
- [ ] https://github.com/metabase/metabase/issues/53281
- [x] [Backend modularization] `lib`
- [ ] [Backend modularization] `logger`
- [ ] https://github.com/metabase/metabase/issues/52166
- [ ] [Backend modularization] `models`
- [ ] [Backend modularization] `moderation`
- [ ] [Backend modularization] `notification`
- [ ] https://github.com/metabase/metabase/issues/52926
- [ ] [Backend modularization] `plugins`
- [x] [Backend modularization] `premium-features`
- [ ] [Backend modularization] `public-settings`
- [ ] [Backend modularization] `pulse`
- [ ] https://github.com/metabase/metabase/issues/52164
- [ ] [Backend modularization] `query-processor`
- [ ] https://github.com/metabase/metabase/issues/52142
- [x] [Backend modularization] `request`
- [ ] https://github.com/metabase/metabase/issues/52152
- [x] [Backend modularization] `search`
- [x] [Backend modularization] `server`
- [ ] https://github.com/metabase/metabase/issues/52232
- [ ] https://github.com/metabase/metabase/issues/52250
- [ ] [Backend modularization] `task`
- [ ] https://github.com/metabase/metabase/issues/52172
- [ ] [Backend modularization] `types`
- [ ] [Backend modularization] `upload`
- [ ] [Backend modularization] `util`
- [ ] https://github.com/metabase/metabase/issues/52146
```

**Comment by camsaul** [comment]
Closing this in favor of https://linear.app/metabase/project/backend-modularization-c89167255eb3
