### ISSUE TITLE
[Epic] Improve navigation and behavior for multi-select text filters

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#42504]
**Links**
- [Product doc](https://www.notion.so/Offer-the-ability-to-select-multiple-values-for-all-text-filters-e41ed1d75702473683967ba57dd3a331?pvs=24)
- [Eng doc](https://www.notion.so/metabase/Tech-Selecting-multiple-values-for-all-text-filters-83aa3b8a803741e2b2e94e242cec85f3)
- Feature branch: None needed. We should be able to merge any of the tasks below independently to `master`.

**Implementation Plan**
Introduce new behavior, and improve the existing UX. These changes should apply to "is", "is not", "contains", "starts with" and "ends with" filters.
```[tasklist]
### Notebook and Chill mode editor
- [ ] https://github.com/metabase/metabase/issues/42783
- [ ] Allow applying the filter and closing the popover by pressing "Enter/Return"
```

```[tasklist]
### Dashboard filter input
- [ ] https://github.com/metabase/metabase/issues/43290
- [ ] Allow applying the filter and closing the popover by pressing "Enter/Return"
```
