### ISSUE TITLE
[Epic] Improve Info Sidebars + Introduce Sidesheets

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#42527]
Docs
- [Product Doc](https://www.notion.so/metabase/Rework-the-info-sidebar-and-entity-actions-9df9b242aef24c9babe3f27b45f61056)
- [Technical Design](https://www.notion.so/metabase/Sidesheets-for-Questions-Dashboards-and-Collections-c26fe9183d074356808fad00de27c58a)
- [Figma Designs](https://www.figma.com/design/NOCVfjRaqkVhNqNq8jL9mX/Rework-the-info-sidebar-and-entity-actions?node-id=917-6517&t=7giObEhGrQ7hOcok-0)

```[tasklist]
### Milestone 0: Design + Planning
- [x] Investigate Existing Sidebar code
- [x] Tech Design Document
- [x] Testing Plan
```

```[tasklist]
### Milestone 1: Actions Menu Changes
- [ ] https://github.com/metabase/metabase/pull/46106
- [ ] https://github.com/metabase/metabase/issues/46252
- [ ] https://github.com/metabase/metabase/issues/46096
- [ ] https://github.com/metabase/metabase/issues/46191
- [ ] https://github.com/metabase/metabase/issues/46192
```

```[tasklist]
### Milestone 2: Side Sheets
- [ ] https://github.com/metabase/metabase/issues/46639
- [ ] https://github.com/metabase/metabase/issues/47132
- [ ] https://github.com/metabase/metabase/issues/47130
- [ ] https://github.com/metabase/metabase/issues/47131
- [ ] https://github.com/metabase/metabase/issues/47133
- [ ] https://github.com/metabase/metabase/issues/47673
- [ ] https://github.com/metabase/metabase/issues/47674
- [ ] https://github.com/metabase/metabase/issues/47919
- [ ] https://github.com/metabase/metabase/issues/47904
- [ ] https://github.com/metabase/metabase/issues/48099
- [ ] https://github.com/metabase/metabase/issues/48100
- [ ] https://github.com/metabase/metabase/issues/48174
- [ ] https://github.com/metabase/metabase/pull/47871
```
