### ISSUE TITLE
[Epic] Optimize bundle size

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#42550]
Adding new UI library or migrating to another charts lib leads to bundle bloating, which affects cypress or local development.

[tasklist]
### **Implementation Plan**
- [x] https://github.com/metabase/metabase/issues/42551
- [x] https://github.com/metabase/metabase/issues/42555
- [ ] ~https://github.com/metabase/metabase/issues/42552~
- [x] upgrade RTK to deduplicate reselect
- [x] lazy load `jsrsasign`
- [ ] lazy load `ace`
- [ ] cut unused moment-timezone data in dev mode
- [x] exclude cljs dev tools during local cypress run by default
