### ISSUE TITLE
[Epic] Add download PDF to static embedded dashboards and make knobs for downloads consistent between public links and static embeds

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#42628]
**Links**
- product doc: https://www.notion.so/metabase/Add-download-PDF-to-static-embedded-dashboards-a155ebfce35346178e657a440723b2a1

**Implementation Plan**

```[tasklist]
### Milestone 1 - refactors and preparation tasks
- [ ] https://github.com/metabase/metabase/issues/43289
- [x] ~move all embed params to redux~ (decided not to do this)
- [ ] https://github.com/metabase/metabase/pull/43495
```

```[tasklist]
### Milestone 2 - functionality
- [ ] https://github.com/metabase/metabase/issues/43605
- [ ] https://github.com/metabase/metabase/issues/44067
- [ ] https://github.com/metabase/metabase/issues/44285
- [ ] https://github.com/metabase/metabase/pull/45178
- [ ] https://github.com/metabase/metabase/pull/45240
```

```[tasklist]
### Milestone 3
- [ ] https://github.com/metabase/metabase/issues/45932
- [ ] https://github.com/metabase/metabase/issues/46007
- [ ] https://github.com/metabase/metabase/pull/46132
- [ ] https://github.com/metabase/metabase/issues/46422
```

This would solve https://github.com/metabase/metabase/issues/34384
