### ISSUE TITLE
[Epic] Improve theming consistency for React embedding SDK

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#42694]
**Goals**
1. Focus on ensuring that changes are cascaded.
2. Theming should not feel inconsistent or broken
3. Granularity comes later.

**Links**
- [product doc](https://www.notion.so/metabase/SDK-Coarse-Theming-6fedde5eb0404778b86a2a4006d377f7?pvs=4)
- [eng doc](https://www.notion.so/metabase/Next-Theming-Milestones-4e82017c97844adb983add93fed2c6d1?pvs=4)

**Implementation Plan**

***Milestone 1: Expose color settings and improve font consistency***

```[tasklist]
### Tasks
- [ ] #42680
- [ ] #42684
- [ ] #42676
- [ ] https://github.com/metabase/metabase/pull/42855
- [ ] https://github.com/metabase/metabase/issues/42705
- [ ] #42563
```

***Milestone 1.5: Migrate hardcoded colors in main app styles***

```[tasklist]
### Tasks
- [ ] #43413
- [ ] #43512
- [ ] #43598
- [ ] #43608
- [ ] #43676
- [ ] #43687
```

***Milestone 2: Chart colors, color contrast and font scaling***

```[tasklist]
### Tasks
- [ ] #42686
- [ ] #42685
- [ ] https://github.com/metabase/metabase/issues/42947
- [ ] #42692
```

***Milestone 3: Fix styling issues in static dashboards and add to demo app***

```[tasklist]
### Tasks
- [ ] #43665
- [ ] #42678
- [ ] https://github.com/metabase/shoppy/issues/26
- [ ] https://github.com/metabase/metabase/issues/43820
- [ ] https://github.com/metabase/metabase/issues/43918
- [ ] https://github.com/metabase/metabase/issues/43819
- [ ] #42693
- [ ] #43672
```

***Milestone 4: Address theming in more visualizations and cleanup theming migration***

```[tasklist]
### Tasks
- [ ] #43265
- [ ] https://github.com/metabase/metabase/issues/44115
- [ ] #43674
- [ ] https://github.com/metabase/metabase/issues/44222
- [ ] https://github.com/metabase/metabase/issues/44226
```
