### ISSUE TITLE
[Epic] Automate SDK changelog

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#42748]
### Description
We want a way to generate SDK changelog easily, and possibly automate it. We ended up choosing [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) as a format to help streamline changelog generation process.

Here's the current shape of [the convention](https://metaboat.slack.com/archives/C063Q3F1HPF/p1715787524818449?thread_ts=1715784742.767949&cid=C063Q3F1HPF)
- We allow 2 type `fix` and `feat`
- Always add the scope, and the only supported scope now is `sdk`
- Breaking change notation `!` has been discussed yet. So there's no enforcing it now.
- Add a conventional commit message in either
  - PR title: This will be included as the squash commit message to master
  - Each commit message: normally when squash merging GH will combine all commit message, so I could grab message from that

### Milestone 1

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/42749
- [ ] https://github.com/metabase/metabase/issues/42750
- [ ] https://github.com/metabase/metabase/issues/43582
- [ ] https://github.com/metabase/metabase/issues/43583
- [ ] https://github.com/metabase/metabase/issues/43746
```
