### ISSUE TITLE
[Epic] Optimize dashboard rendering

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#42881]
Dashboard rendering is slow and not optimal, but it's close to impossible to make any change there, so let's prepare it

<img width="1242" alt="image" src="https://github.com/metabase/metabase/assets/125459446/3c48fb44-37d4-4e63-b1f0-07832bffb7cd">
starting point - 105 renderings in a simple dashboard with 2 cards

<img width="615" alt="image" src="https://github.com/metabase/metabase/assets/125459446/2ea2c35a-3108-401d-b0ca-ade771c41ee2">

TBA
**Implementation Plan**
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/42882
- [ ] https://github.com/metabase/metabase/issues/42883
- [ ] https://github.com/metabase/metabase/issues/42884
- [ ] https://github.com/metabase/metabase/issues/42885
- [ ] https://github.com/metabase/metabase/pull/43431
- [ ] https://github.com/metabase/metabase/pull/43340
- [ ] https://github.com/metabase/metabase/pull/43323
- [ ] https://github.com/metabase/metabase/pull/43169
```
