### ISSUE TITLE
[Epic] Modularized Search

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#42997]
**Links**
- product doc: https://www.notion.so/metabase/Modularize-and-improve-search-e5b7ecb42cc642dabc374a1b5705a2c6
- eng docs:
  - https://www.notion.so/metabase/Search-Modularization-part-1-7f3ed9b914a5455fbe311d25af565daa
  - https://www.notion.so/metabase/Search-Modularization-part-2-d9cd42174d6d4be785833599771441d6
- feature branch: none yet
- issue links: _related issues if any_

**Implementation Plan**

***Milestone 1***

- [ ] Rewrite model scoring to be a registry of only outliers
- [ ] Combine "model registration" as a single multimethod
- [ ] Move model registration code to respectful model files
- [ ] Push out all model-specific clauses to a multimethod

***Milestone 2***

**Comment by calherries** [comment]
most recently, we decided to start on getting all searchable data into one table. see the first milestone plan [here](https://www.notion.so/metabase/Search-Modularization-d9cd42174d6d4be785833599771441d6?pvs=4#84e898b77752454e8549bbf9e907b440).

a prototype/POC for this was started in this PR: https://github.com/metabase/metabase/pull/43986

**Comment by crisptrutski** [comment]
Superseded by https://github.com/metabase/metabase/issues/40964
