### ISSUE TITLE
Measure search performance

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#43017]
Project Doc: [Notion Doc](https://www.notion.so/metabase/Measure-search-performance-958a28ef144a4b94be8b3b1f0ce4ab34)

```[tasklist]
### Tasks
- [ ] Remove Snowplow Events from BE Search Endpoint
- [ ] Add onQueryStarted handler to `metabase/api/search.ts` to emit snowplow events
- [ ] Add snowplow events to command palette
- [ ] Add snowplow events to search app
- [ ] Add snowplow events to entity picker
- [ ] Update snowplow event schemas
```
