### ISSUE TITLE
Serialized models should declare fields to serialize

### ISSUE THREAD

**Issue by piranha** [metabase/metabase#43068]
And a test making sure that every new column added with migration should be handled by a developer.

[Context](https://metaboat.slack.com/archives/C0641E4PB9B/p1715913839189749)
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/45209
- [ ] #45455
- [ ] https://github.com/metabase/metabase/pull/46481
- [ ] https://github.com/metabase/metabase/pull/46147
- [ ] https://github.com/metabase/metabase/pull/46912
- [ ] https://github.com/metabase/metabase/pull/46966
- [ ] https://github.com/metabase/metabase/pull/46973
- [ ] https://github.com/metabase/metabase/pull/47121
- [ ] https://github.com/metabase/metabase/pull/47136
- [ ] https://github.com/metabase/metabase/pull/47220
- [ ] https://github.com/metabase/metabase/issues/47226
- [ ] https://github.com/metabase/metabase/pull/47268
```
