### ISSUE TITLE
[Epic] Make dashboard filter auto-wire less presumptuous

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#43182]
**Links**
- [product doc](https://www.notion.so/metabase/Make-dashboard-filter-auto-wire-less-presumptuous-7f60adeccb38442c84cdde5663045e3f)
- feature branch: `filters-auto-wire-presumptuous`
- [testing plan](https://github.com/metabase/metabase/issues/43806)

**Implementation Plan**

```[tasklist]
### ***Milestone 1*** - Main functionality
- [ ] https://github.com/metabase/metabase/issues/43183
- [ ] https://github.com/metabase/metabase/issues/43184
- [ ] https://github.com/metabase/metabase/issues/43268
```

```[tasklist]
### ***Milestone 2*** - Follow ups
- [ ] https://github.com/metabase/metabase/pull/44015
- [ ] https://github.com/metabase/metabase/issues/43964
```
