### ISSUE TITLE
[Epic] DevEx Projects

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#43320]
```[tasklist]
### CI
- [x] https://github.com/metabase/metabase/issues/43343
- [ ] https://github.com/metabase/metabase/issues/44364
- [ ] https://github.com/metabase/metabase/issues/44661
- [ ] https://github.com/metabase/metabase/issues/43594
- [ ] https://github.com/metabase/metabase/issues/44952
- [ ] https://github.com/metabase/metabase/issues/44957
- [ ] https://github.com/metabase/metabase/issues/43505
- [ ] https://github.com/metabase/metabase/issues/45009
- [ ] https://github.com/metabase/metabase/issues/44662
- [ ] https://github.com/metabase/metabase/issues/45501
- [ ] #46415
- [ ] https://github.com/metabase/metabase/issues/47500
- [ ] https://github.com/metabase/metabase/issues/48326
- [ ] Basic Performance Testing in CI
```

```[tasklist]
### e2e debugging experience
- [ ] https://github.com/metabase/metabase/issues/46870
- [ ] https://github.com/metabase/metabase/issues/46954
- [ ] add names of falining tests to annotation of github actions page
```

```[tasklist]
### Release
- [ ] https://github.com/metabase/metabase/issues/43504
- [ ] https://github.com/metabase/metabase/pull/36420
- [ ] https://github.com/metabase/metabase/pull/39634
- [ ] https://github.com/metabase/metabase/pull/37613
- [ ] https://github.com/metabase/metabase/issues/43627
- [ ] https://github.com/metabase/metabase/issues/44117
- [ ] https://github.com/metabase/metabase/issues/44154
- [ ] https://github.com/metabase/metabase/issues/44123
- [ ] https://github.com/metabase/metabase/pull/44663
- [ ] https://github.com/metabase/metabase/issues/45353
- [ ] https://github.com/metabase/metabase/pull/45048
- [ ] https://github.com/metabase/metabase/issues/44037
- [ ] https://github.com/metabase/metabase/issues/47785
- [ ] https://github.com/metabase/metabase/issues/47786
- [ ] https://github.com/metabase/metabase/issues/48281
- [ ] https://github.com/metabase/metabase/issues/48121
- [ ] https://github.com/metabase/metabase/issues/46838
- [ ] https://github.com/metabase/metabase/issues/48627
- [ ] https://github.com/metabase/metabase/pull/49340
- [ ] https://github.com/metabase/metabase/issues/50741
- [ ] https://github.com/metabase/metabase/issues/50742
- [ ] Notify on ee-extra build/merge failures
- [ ] Integrate third party driver tests into release process?
```

```[tasklist]
### Misc
- [x] Create Devex Survey
- [x] Create Devex Dashboard
- [ ] https://github.com/metabase/metabase/pull/43420
- [ ] https://github.com/metabase/metabase/issues/43419
- [ ] https://github.com/metabase/metabase/pull/44401
- [ ] https://github.com/metabase/metabase/issues/46424
- [ ] https://github.com/metabase/metabase/issues/47118
- [ ] https://github.com/metabase/metabase/issues/46823
- [ ] https://github.com/metabase/metabase/issues/47165
```
```[tasklist]
### Requests from developers
- [ ] https://github.com/metabase/metabase/issues/45698
- [ ] https://github.com/metabase/metabase/issues/47087
- [ ] https://github.com/metabase/metabase/issues/46889
- [ ] https://github.com/metabase/metabase/issues/46869
- [ ] https://github.com/metabase/metabase/issues/46840
- [ ] https://github.com/metabase/metabase/issues/46962
- [ ] Introduce a way to check if new code adds new warnings or errors in console and fail CI
- [ ] Get rid of prop-types warnings from browser console
```
```[tasklist]
### jest unit tests
- [ ] https://github.com/metabase/metabase/issues/46264
- [ ] specify node env for tests which do not require DOM
- [ ] bundle cljs files for unit tests - so we can skip a huge step on requiring cljs files for every single test
```

```[tasklist]
### CI build time improvements
- [x] migrate from babel to swc - finish prior work from Roman
- [x] remove duplicated build steps
- [ ] https://github.com/metabase/metabase/issues/47025
- [ ] https://github.com/metabase/metabase/issues/45700
- [ ] https://github.com/metabase/metabase/issues/37576
- [ ] https://github.com/metabase/metabase/issues/36336
```
