### ISSUE TITLE
Optimize dashboard metadata request

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#43378]
Should be based on changes here https://github.com/metabase/metabase/pull/43416

Currently it takes ~3.5s for the BE to calculate metadata for a medium size dashboard. 

Repro:
- Open https://stats.metabase.com/dashboard/1880
- See `/api/dashboard/:id/query_metadata`:

<img width="868" alt="Screenshot 2024-05-30 at 17 44 36" src="https://github.com/metabase/metabase/assets/8542534/896ea2fd-7584-48c0-92c3-9e1f50f0b6fc">

This is very slow and we need to optimize this.
```[tasklist]
### Tasks
- [ ] Memoize the query_metadata call
- [ ] Batch fetch table metadata
- [ ] https://github.com/metabase/metabase/issues/43509
- [ ] Batch fetch database
- [ ] Batch fetch dashboard
- [ ] Batch fetch fields
```

**Comment by perivamsi** [comment]
Pausing the work on this for now - as of 6/11
