### ISSUE TITLE
Consolidate e2e Repro Specs

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#43505]
There is significant (4-6 second) setup overhead in separate test files in CI. combining dozens of reproduction specs that all have 1 or 2 tests, provides several minutes of CI savings in many cases

We should consolidate all of these, even when there are only a couple offenders to eliminate the pattern from the codebase and to keep it from continuing.

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/43328
- [ ] https://github.com/metabase/metabase/pull/43342
- [ ] https://github.com/metabase/metabase/pull/43271
- [ ] https://github.com/metabase/metabase/pull/43519
- [ ] https://github.com/metabase/metabase/pull/43619
- [ ] https://github.com/metabase/metabase/pull/43514
- [ ] https://github.com/metabase/metabase/pull/43527
- [ ] https://github.com/metabase/metabase/pull/43552
- [ ] https://github.com/metabase/metabase/pull/43616
- [ ] https://github.com/metabase/metabase/pull/43613
- [ ] https://github.com/metabase/metabase/pull/43717
- [ ] https://github.com/metabase/metabase/pull/43716
- [ ] https://github.com/metabase/metabase/pull/43718
- [ ] https://github.com/metabase/metabase/pull/43844
- [ ] https://github.com/metabase/metabase/pull/43843
- [ ] https://github.com/metabase/metabase/pull/43841
- [ ] https://github.com/metabase/metabase/pull/43846
- [ ] https://github.com/metabase/metabase/pull/43853
- [ ] onboarding
- [ ] binning
```

**Comment by iethree** [comment]
One down side to this project is that some developers find working with large files to be rather cumbersome.

One alternative approach suggested by @romeovs is keeping test files small, but running them via imports into larger files, which should solve  the performance problem.

see [discussion](https://metaboat.slack.com/archives/C0669P4AF9N/p1719825667882659) and proof of concept PR:
- https://github.com/metabase/metabase/pull/44889

One open question: 
- Do most developers find large files hard to work with?

One blocker: 
- we need a linter that can ensure that all spec files are imported into runner files so that we don't end up with orphan spec files that never get run.
