### ISSUE TITLE
[Notifications] Webhook channel for alert

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#43822]
**Links**
- product doc: https://www.notion.so/metabase/Enable-users-to-create-custom-webhook-notification-channels-da7234d688e344b2b376e22818f3c727 (WIP)
- high level eng doc: https://www.notion.so/metabase/Notification-high-level-design-9620a4a69db0494f806a146cc9174964
- Webhook tech doc: https://www.notion.so/metabase/Webhook-for-Alert-4f9c7727e06c4c958687c25e1eece21e?pvs=4
- Feature branch: [feat-http-channel](https://github.com/metabase/metabase/pull/45201)

**Implementation Plan**

```[tasklist]
### Milestone 1: Channel Refactor -- BE only
- [x] Create a new module: channel
- [x] Introduce a set of channels multi-methods
- [x] Migrate email and slacks to the new channel module
- [x] #43924
```

```[tasklist]
### Milestone 2.1: Setup page
- [x] [BE] [introduce a new multimethod `channel/can-connect?` and implement for http](https://github.com/metabase/metabase/pull/44955) (0.5 day)
- [x] [BE] [Add the `channel` table](https://github.com/metabase/metabase/pull/45207) (0.5 day)
- [x] [BE] [Implement channel CRUD APIs](https://github.com/metabase/metabase/pull/45207) (1.5 days)
- [x] [BE] [Implement test connection API ](https://github.com/metabase/metabase/pull/45207)(0.5 day)
- [ ] https://github.com/metabase/metabase/issues/45574
```

```[tasklist]
### Milestone 2.2: Implement HTTP channel (outcome: repl demo to send data to zapier)
- [x] [BE] https://github.com/metabase/metabase/pull/45545 (1 day)
```

```[tasklist]
### Milestone 2.3: Enable HTTP channel for alert
- [x] [BE] [Update `GET /api/pulse/form_input` to return HTTP channel details (0.5 day)](https://github.com/metabase/metabase/pull/45839)
- [x] [BE] [Update `POST /api/alert` and `PUT /api/alert/:id` to accept HTTP channels (0.5 day)](https://github.com/metabase/metabase/pull/45839)
- [x] [BE] [Update `POST /api/pulse/test` so that we can test HTTP channels for alert ( 1 day )](https://github.com/metabase/metabase/pull/45839)
- [x] [BE] [Do not show channel.details for non-admin users](https://github.com/metabase/metabase/pull/46034)
- [x] [BE] [Disable channel will delete pulse channel](https://github.com/metabase/metabase/pull/46115)
- [ ] https://github.com/metabase/metabase/issues/46341
- [ ] https://github.com/metabase/metabase/issues/46657
```
```[tasklist]
### Milestone 3: serdes and audit
- [x] [BE] [ensure we serdes channel properly (0.5 day)](https://github.com/metabase/metabase/pull/46031)
- [x] [BE] [audit log channel creation / update (0.5 day)](https://github.com/metabase/metabase/pull/46113)
- [x] [BE] [Record a `TaskHistory` for each `channel/send!` call. include the retry info](https://github.com/metabase/metabase/pull/46218)
```

**Comment by darksciencebase** [comment]
This will close https://github.com/metabase/metabase/issues/2298
