### ISSUE TITLE
[Epic] Re-design transparent theme for static embedding and public links

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#43838]
**Links**
- [product doc](https://www.notion.so/metabase/Re-design-transparent-theme-for-static-embedding-and-public-links-a28e98a6e5c64301a48387c7b333d569)
- [testing plan](https://www.notion.so/metabase/Testing-plan-3e67037b08434033a5f653c83c622e92)
- [Figma file](https://www.figma.com/design/1YcsFf5yYdFZTguwoKVdkj/Re-design-the-transparent-background-setting-in-interactive-embedds?node-id=917-6518&t=xGtBN4rhXtqkfgnr-0)

Milestone 1 branch: [`43838-milestone-1-necessity`](https://github.com/metabase/metabase/tree/43838-milestone-1-necessity)
```[tasklist]
### Milestone 1 - Necessity
- [ ] https://github.com/metabase/metabase/issues/44068
- [x] Handle dashboard sticky filters on transparent background
- [ ] https://github.com/metabase/metabase/issues/44273
- [ ] https://github.com/metabase/metabase/issues/44476
- [ ] https://github.com/metabase/metabase/issues/45090
- [ ] https://github.com/metabase/metabase/issues/45202
- [ ] https://github.com/metabase/metabase/issues/45407
- [ ] https://github.com/metabase/metabase/issues/45427
- [ ] https://github.com/metabase/metabase/issues/45565
```

```[tasklist]
### Milestone 2 - Polishing
- [ ] https://github.com/metabase/metabase/issues/45723
- [ ] https://github.com/metabase/metabase/issues/46378
- [ ] https://github.com/metabase/metabase/issues/46419
```
```[tasklist]
### Future milestones
- [ ] https://github.com/metabase/metabase/issues/46479
- [x] Introduce hover colors
- [ ] Allow simulating user background color
- [ ] Match `.DashboardNight` (dashboard) to `.ThemeNight` (EmbedFrame)
- [ ] https://github.com/metabase/metabase/issues/45422
- [x] ensure SDK compatibility with new semantic colors
```

**Comment by WiNloSt** [comment]
We [discussed that](https://metaboat.slack.com/archives/C063Q3F1HPF/p1724398752339749?thread_ts=1724077872.663639&cid=C063Q3F1HPF) we can close this issue once the UTM tag is merged, which it has been.
