### ISSUE TITLE
[ParseSQL] Correctness of Query Column Attribution

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#43919]
**Implementation Plan**

```[tasklist]
### Tasks
- [x] #42584
- [ ] #42585
- [ ] https://github.com/metabase/metabase/issues/44046
- [ ] https://github.com/metabase/metabase/issues/44380
- [ ] https://github.com/metabase/metabase/issues/44045
- [ ] https://github.com/metabase/macaw/pull/84
```

**Deferred**

- #42586
- #43725
- https://github.com/metabase/metabase/issues/42938
- https://github.com/metabase/metabase/issues/46955

**Comment by crisptrutski** [comment]
We've decided to pause implementing further analysis support, but before closing this Epic we should sanity check our correctness somehow. A good baseline to use is to compare the existing analysis for MBQL cards to the analysis we get from first compiling them to SQL and then using Macaw to analyze them.
