### ISSUE TITLE
[ParseSQL] Prepare for the release

### ISSUE THREAD

**Issue by darksciencebase** [metabase/metabase#43920]
**Implementation Plan**

```[tasklist]
### Tasks
- [ ] #43516
- [ ] #44118
- [ ] https://github.com/metabase/macaw/issues/58
- [ ] #43643
- [ ] #43644
- [x] What about column refs that don't match fields?
- [x] What about table refs that don't match anything?
- [ ] https://github.com/metabase/metabase/pull/47063
- [ ] #43645
- [ ] #43646
- [ ] https://github.com/metabase/metabase/issues/47180
- [x] Get EE token added to cloud etc
- [x] Reduce log levels from DEBUG to INFO prior to release?
- [ ] https://github.com/metabase/metabase/pull/47216
```

**Comment by crisptrutski** [comment]
I see there 4 open bullet points on this epic, can we keep it open until they are all resolved?

**Comment by tsmacdonald** [comment]
Cloud token: https://github.com/metabase/harbormaster/pull/5261

**Comment by crisptrutski** [comment]
Don't see anything else to do here
