### ISSUE TITLE
improve legends

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#44019]
https://metaboat.slack.com/archives/C064QMXEV9N/p1717460443337769?thread_ts=1717460135.322869&cid=C064QMXEV9N

## TODO
- [x] move to bottom (https://github.com/metabase/metabase/pull/43555/commits/9c8fcbf85ebe12bc4b519aa39d5b1c6578e9f00c)
- [x] decrease dot margin (https://github.com/metabase/metabase/pull/43555/commits/5fe843add2fd5d9831617ddc28e61fa725f5c5ee)
- [x] show in columns (https://github.com/metabase/metabase/pull/43555/commits/98c2f658ff2cf84238762fa327fd86aeac59f098)
- [x] sort items vertically in columns (https://github.com/metabase/metabase/pull/43555/commits/9f8369ddb7e3c39aada6d15dba5f618eb3b6acf3)
- [x] don't use columns if we can fit everything in one row (https://github.com/metabase/metabase/pull/43555/commits/45712c5b604d147a819cd08e720e64ab72bf7987)
- [x] legends should be aligned to chart edge, not image edge (https://github.com/metabase/metabase/pull/43969/commits/e23ff880c868cb837f0f606d702acda16b72f32d)
- [x] always show legend in static viz, even if setting is disabled (https://github.com/metabase/metabase/pull/43555/commits/a8f089c25291c4182c67e2f7b972efaf27722b78)
- [x] should center the legend if it's just one column (https://metaboat.slack.com/archives/C077SMHSUTV/p1718204317785689) (https://github.com/metabase/metabase/pull/43969/commits/e23ff880c868cb837f0f606d702acda16b72f32d)
- [x] show legend with just one item (question/14994) (https://github.com/metabase/metabase/pull/43555/commits/b51e95091fab85c7aceef74a7c8ca38b9aba5f9e)
- [x] right justify percentages (https://github.com/metabase/metabase/pull/43555/commits/5a656cc6c7cfa34be70c2801f4b27058c159eb9a)
