### ISSUE TITLE
[Epic] Elevate “include this period” in time filters

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#44096]
**Links**
- [Product doc](https://www.notion.so/metabase/Elevate-include-this-period-in-time-filter-b828dcca50b7491c9f1719d2bf6c60a0?pvs=4)
- Eng doc - TDB
- Feature branch:  `qc-proj-elevate-include-this-period`
- [Figma](https://www.figma.com/design/ofKULr1X7TQf5MZCkbJZvx/Elevate-%E2%80%9Cinclude-this-period%E2%80%9D-in-time-filter?node-id=1-286&t=vXLIPw5F50pJoQyr-0)
- Testing plan: #44323

# Implementation Plan
This should be fairly self-contained epic that most likely doesn't need more than one milestone. It has three distinct places in the UI that need to be updated. Maybe it makes sense to merge them all together to `master`, or maybe they are distinct enough which allows merging them individually. I'll know this when I dig into the code.

## Milestone 1
Update and re-work the existing frontend/src/metabase/querying/components/DatePicker/RelativeDatePicker/DateIntervalPicker/DateIntervalPicker.tsx component.
```[tasklist]
- [x] Add the new option to the filter in the notebook mode (#44179)
- [x] Add the new option to the filter modal in the simple mode (#44179)
- [x] Add the new option to the filter in the drill-through context menu (simple mode) (#44179)
- [x] Elevate the "Starting from " icon/action (#44242)
- [x] Merge milestone 1 to `master` (#44279)
```

## Milestone 2
Time-series chrome component.
Implementing this will resolve #42220

```[tasklist]
- [x] Add the new option to the time-series chrome in the charts/data visualizations (#44247)
- [x] Cover new changes with more tests (#44247)
```

## Milestone 3
Milestone 1 and Milestone 2 follow-ups.
> [!Note]
> I propose we merge the Milestone 1 and 2 to `master` to give product and design teams a few days to feel the new changes before we start polishing them.
```[tasklist]
- [x] Update copy (Past -> Previous) ([Slack context](https://metaboat.slack.com/archives/C02H619CJ8K/p1718358798489699)) (#44299)
- [ ] Tweak the design (#44554)
```

### Additional Notes
The related issue/feature request: https://github.com/metabase/metabase/issues/42220
