### ISSUE TITLE
[ParseSQL] Robustness of Query Analysis

### ISSUE THREAD

**Issue by crisptrutski** [metabase/metabase#44199]
### Description

While we catch all errors encountered during analysis, the first prize is to not have the errors in the first place.

There are a few prongs to our defense:
 
### 1. Don't analyze things we know we can't support, e.g. MongoDB queries.

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/44350
```

### 2. Identify and fix bugs due to problems with our grammar.

These may require workarounds for now since we are using a 3rd party grammar, e.g. by de-then-re-sugaring with sentinels.

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/44062
- [ ] https://github.com/metabase/macaw/issues/72
- [ ] https://github.com/metabase/macaw/issues/42
- [ ] https://github.com/metabase/metabase/issues/44200
```

#### Deferred

- https://github.com/metabase/macaw/issues/76 (unlikely to be used by customers)
- https://github.com/metabase/macaw/issues/73 (affects only small percent of queries using)
- https://github.com/metabase/macaw/issues/75

### 3. Identify and fix bugs due to problems with our analysis.

Thankfully nothing like this has come up yet, but here's an empty section so we remember to look out for it.

```[tasklist]
- [x] Found some NPEs and fixed them
```
