### ISSUE TITLE
Find items to auto-archive with a modal

### ISSUE THREAD

**Issue by johnswanson** [metabase/metabase#44253]
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/44923
- [x] Expose that backend API in a new endpoint
- [ ] https://github.com/metabase/metabase/issues/44477
- [x] Backend API emits events
- [x] add collection info into the stale API endpoint
- [x] JSON schema for snowflake events
```
