### ISSUE TITLE
[Epic] Support BigInt type

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#44713]
Bug report: https://github.com/metabase/metabase/issues/5816

Since numbers in JS are in 64-bit floating-point format, BigInt values outside of `[-9007199254740991, 9007199254740991]` have precision issues. We can use native `bigint` type on the FE to support BigInt values.

```[tasklist]
### Implementation Plan
- [ ] Correctly serialize requests payloads and deserialize responses with BigInts
- [ ] Support BigInts in ECharts
- [ ] Support BigInts in Clojure metabase-lib (filters construction)
- [ ] ...
```

**Comment by q578135872** [comment]
strongly support this proposal

**Comment by james-sift** [comment]
Also strongly support this, especially support for BigInt64Arrays and BigUint64Array as columns in a datset.

**Comment by caseyandgina** [comment]
Yes, please!  It's a big problem and frankly kind of ridiculous that this is still an issue after so many years, when it breaks the fundamental expectation that Metabase should be able to accurately display and use database values.  The primary application used where I work happens to utilize 64-bit integers that exclusively fall above the 53-bit threshold for many different things.

We solved the same type of problem in a different JavaScript context with this:  https://www.npmjs.com/package/lossless-json
