### ISSUE TITLE
Small UI tweaks on browse section, application permissions, and entity picker

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#44783]
```[tasklist]
### Tasks
- [ ] Move the `Browse` section in the sidebar below `Collections` and above `Trash` ([context](https://metaboat.slack.com/archives/C064EB1UE5P/p1718672513571679))
- [ ] Change the copy from the `Monitoring` permission tooltip to `This grants access to the Tools and Troubleshooting sections in Admin.` ([context](https://metaboat.slack.com/archives/C01LQQ2UW03/p1718635102050019))
- [ ] In the dashboard picker, replace the dashboard tab and icon with `Collections` and the `folder` icon ([context](https://metaboat.slack.com/archives/C01LQQ2UW03/p1718958110082899))
```
