### ISSUE TITLE
[Epic] REST API for the Query Validator

### ISSUE THREAD

**Issue by tsmacdonald** [metabase/metabase#44976]
**Links**
- [product doc](https://www.notion.so/metabase/Query-validator-a8981d498f324da5acf9284e7d7ba2f6)
- [eng doc](https://www.notion.so/df75801389a1434c95139fa1227798bf?pvs=25)

**Implementation Plan**

## Milestone 1

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/45026
- [ ] https://github.com/metabase/metabase/issues/45673
- [ ] https://github.com/metabase/metabase/issues/45756
- [ ] #43516
- [x] [Allow filtering endpoint by collection](https://github.com/metabase/metabase/pull/46024)
- [x] [Add effective_ancestors to the response to populate the collection breadcrumb](https://github.com/metabase/metabase/pull/46024)
```

### Deferred
-  https://github.com/metabase/metabase/issues/45552

## Milestone 2

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/45971
- [ ] https://github.com/metabase/metabase/issues/45027
- [ ] https://github.com/metabase/metabase/issues/45028
```
