### ISSUE TITLE
[Cache] Add e2e tests for questions and dashboards

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#45355]
```[tasklist]
### Tasks
- [x] dashboard > direct > adaptive
- [x] dashboard > via database > adaptive
- [x] dashboard > via root > adaptive
- [x] dashboard > direct > duration
- [x] dashboard > via database > duration
- [x] dashboard > via root > duration
- [x] dashboard > direct > nocache
- [x] dashboard > via database > nocache
- [x] dashboard > via root > nocache
- [x] question > direct > adaptive
- [x] question > via database > adaptive
- [x] question > via root > adaptive
- [x] question > direct > duration
- [x] question > via database > duration
- [x] question > via root > duration
- [x] question > direct > nocache
- [x] question > via database > nocache
- [x] question > via root > nocache
```

```[tasklist]
### Not currently planned
- [ ] question > via root > schedule
- [ ] question > via database > schedule
- [ ] question > direct > schedule
- [ ] dashboard > via root > schedule
- [ ] dashboard > via database > schedule
- [ ] dashboard > direct > schedule
```
