### ISSUE TITLE
[ParseSQL] Rate limited Query Analysis 

### ISSUE THREAD

**Issue by crisptrutski** [metabase/metabase#45460]
## Description

This work stream involves re-working the way that Query Analysis is scheduled, to ensure that we reach complete coverage without causing undue load on the Metabase instance(s). 

**Links**
- product doc: N/A (see [postmortem](https://www.notion.so/metabase/v50-Up-to-50k-minute-log-lines-with-SQL-Parser-errors-c699c635a4c243a8a9f298ce725c7964))
- eng docs:
  - [Robust SQL Parser Analysis](https://www.notion.so/metabase/Robust-backfill-for-the-SQL-Parser-16fd98ea45794300812c134197caef25)
  - [Reduced scope version](https://www.notion.so/metabase/Minimal-SQL-Analysis-Scheduling-ab8b5a63c1dc4fa3b820173b0cd9fe75)
- feature branch: Work will be done in master.

**Implementation Plan**

```[tasklist]
### Milestone 1 - bound realtime work
- [ ] https://github.com/metabase/metabase/issues/45461
- [ ] https://github.com/metabase/metabase/issues/45462
- [ ] https://github.com/metabase/metabase/issues/45463
```

```[tasklist]
### Milestone 2 - backfill safely
- [ ] https://github.com/metabase/metabase/issues/45464
- [ ] https://github.com/metabase/metabase/issues/45470
- [ ] https://github.com/metabase/metabase/issues/45471
- [ ] https://github.com/metabase/metabase/issues/45720
```

```[tasklist]
### Testing
- [x] Hook versus Sweeper race test
- [x] Manual Testing - hook only
- [x] Manual Testing - create, update, delete
- [x] Component tests
- [x] ~~End-to-end test~~ Will write a larger test that includes the validator tool
- [x] Cloud instance backfill
- [x] Local stress test
```

**Comment by crisptrutski** [comment]
Moved Milestone 3 to its own Epic
