### ISSUE TITLE
Mantine v7

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#45941]
Now that we're on React 18, we should upgrade to mantine v7 sooner rather than later to take advantage of new components, better component APIs, more performant styling, and better accessiblity.

see:
- https://github.com/metabase/metabase/pull/33368

```[tasklist]
### Tasks
- [x] Update Branch to Mantine v7
- [x] Setup Base Theme
- [ ] Convert each set of overrides to CSS
- [ ] Design review + figma comparison
- [ ] setup Loki tests against UI components storybook
```

```[tasklist]
### Follow-ups
- [ ] remove `theme.fn.themeColor` usage?
- [ ] audit all `styles` props: https://mantine.dev/guides/6x-to-7x/#styles-prop
- [ ] change spacing to gap props on stack components
- [ ] overrides truncation
```
