### ISSUE TITLE
Improved Query Analysis Workflow and Persistence

### ISSUE THREAD

**Issue by crisptrutski** [metabase/metabase#46051]
This continues on from https://github.com/metabase/metabase/issues/45460.

```[tasklist]
- [ ] Introduce QueryAnalysis model to act as root node for an analysis snapshot
- [ ] Update SQL Analyzer to use root node to deduplicate work and perform atomic swaps
- [ ] Update SQL Analysis Sweeper to use root node to queue analysis more intelligently
- [ ] Remove obsolete mechanisms, like the in-memory failure map
```
