### ISSUE TITLE
[Epic] Open the data source (in a new tab) from the notebook editor

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#46201]
**Links**
- product doc: [Link to open the data source from the notebook editor](https://www.notion.so/metabase/Link-to-open-the-data-source-from-the-notebook-editor-640e1723dddb4ddb978190cca6a72791)
- [figma](https://www.figma.com/design/06jovUhXOrsRO8FYZi7G1d/Data-picker-improvements?node-id=6126-9480&t=5KR7Jvs7Hz0AXEbe-0)
- eng doc: N/A
- feature branch: `notebook-open-data-source`
- issue links: N/A
- testing plan: #46203

**Implementation Plan**
Alter the click behavior for certain UI elements to open the underlying data source in a new tab/window. The click handler should react to CMD + click, CTRL + click or middle button/scroll click.

```[tasklist]
### Milestone 1 (notebook data picker) #46228
- [x] Questions (based on the raw table, on the saved question, on the model)
- [x] Models (based on the raw table, on the saved question, on the model)
- [x] Testing coverage
```

```[tasklist]
### Milestone 2 (notebook joins) #46582
- [x] Raw tables
- [x] Questions
- [x] Models
```

```[tasklist]
### Milestone 3 (tooltips) #46552
- [x] Notebook data picker
- [x] Notebook joins
```

```[tasklist]
### Milestone 4 (follow ups and edge cases)
- [x] Make sure opening links works when Metabase is deployed on a subpath (#46684)
- [x] Prevent opening data source in an embedding SDK scenario (#46743)
- [ ] Add E2E sandboxing scenarios (#46903)
```
