### ISSUE TITLE
[Epic] Dashboard perf fixes

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#46232]
```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/46234
- [ ] https://github.com/metabase/metabase/pull/46204
- [ ] https://github.com/metabase/metabase/pull/46199
- [ ] https://github.com/metabase/metabase/issues/46339
- [ ] https://github.com/metabase/metabase/issues/46233
- [ ] https://github.com/metabase/metabase/issues/46181
- [ ] https://github.com/metabase/metabase/issues/46179
- [ ] https://github.com/metabase/metabase/issues/46183
```
