### ISSUE TITLE
Milestone 2 - Manual auto-archive

### ISSUE THREAD

**Issue by johnswanson** [metabase/metabase#46292]
```[tasklist]
### Tasks
- [ ] POST endpoint to archive all stale items in a collection
- [ ] FE add button to archive all items in a collection
- [ ] https://github.com/metabase/metabase/issues/48348
```
