### ISSUE TITLE
[Epic] Improve tables

### ISSUE THREAD

**Issue by sloansparger** [metabase/metabase#46343]
**Links**
- eng doc: **WIP** https://www.notion.so/metabase/Reusable-Table-Component-c0afb3427838465f9193b836a97bf7b4?pvs=4
- feature branch: TBD

**Problem**
We have multiple places in Metabase where we need to show a table of information, however each places implements its own table resulting in discrepancies in visuals and implementation logic. We'd like to both solve the poor developer experience that results from having to build a new table for every feature and provide an core solution that makes it easier to create higher quality tables. Currently tables suffer from a few common issue around pagination bugs, selection logic being incorrect, sub-par loading experiences, and more. By the end of this epic those things should all be resolved.

**Implementation Plan**

```[tasklist]
### Tasks
- [ ] Engineering Doc - Spec out a reusable table component
- [ ] Milestone 1: Add a core table implementation
- [ ] Milestone 2: Port existing tables to table solutions
- [ ] Milestone 3: Create a better loading experience for tables
```
