### ISSUE TITLE
[Epic] Show columns from all stages in the dashboard filters

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#46519]
**Links**
- Product doc: https://www.notion.so/metabase/Allow-to-use-in-dashboard-filters-both-pre-and-post-last-aggregation-columns-b32a6bb5cebc4723b8b9b81870217a79
- Tech doc: https://www.notion.so/metabase/Tech-Allow-to-use-both-pre-and-post-last-aggregation-columns-in-dashboard-filters-1f8c3309aa824463827a38bedcd47ac6
- Testing plan: #46520
- Feature branch: `dashboard-filter-columns`
  - PR with feature branch: #47167
- Links:
  - Fixes #19744
  - Follow up epic: #48681

### Milestone 1

```[tasklist]
### Backend
- [ ] https://github.com/metabase/metabase/issues/46914
- [ ] https://github.com/metabase/metabase/issues/47304
- [ ] https://github.com/metabase/metabase/issues/47184
- [ ] https://github.com/metabase/metabase/issues/48258
- [ ] https://github.com/metabase/metabase/issues/48441
- [ ] https://github.com/metabase/metabase/issues/48884
- [ ] https://github.com/metabase/metabase/issues/48339
- [ ] https://github.com/metabase/metabase/issues/48734
- [ ] https://github.com/metabase/metabase/issues/49282
- [ ] https://github.com/metabase/metabase/issues/48613
- [ ] https://github.com/metabase/metabase/issues/49110
```

```[tasklist]
### Frontend
- [ ] https://github.com/metabase/metabase/pull/46719
- [ ] https://github.com/metabase/metabase/pull/46721
- [ ] https://github.com/metabase/metabase/issues/46522
- [ ] https://github.com/metabase/metabase/issues/46915
- [ ] https://github.com/metabase/metabase/issues/47166
- [ ] https://github.com/metabase/metabase/issues/48253
- [ ] https://github.com/metabase/metabase/issues/48260
- [ ] https://github.com/metabase/metabase/issues/47235
- [ ] https://github.com/metabase/metabase/issues/48787
- [ ] https://github.com/metabase/metabase/issues/48885
- [ ] https://github.com/metabase/metabase/issues/49218
```

```[tasklist]
### Tests
- [ ] https://github.com/metabase/metabase/issues/46526
- [ ] https://github.com/metabase/metabase/issues/46527
- [ ] https://github.com/metabase/metabase/issues/47219
- [ ] https://github.com/metabase/metabase/issues/48445
- [ ] https://github.com/metabase/metabase/issues/49022
- [ ] https://github.com/metabase/metabase/issues/49233
- [ ] https://github.com/metabase/metabase/issues/47234
- [ ] https://github.com/metabase/metabase/issues/46520
- [ ] https://github.com/metabase/metabase/issues/46528
```

```[tasklist]
### Bugs that will be fixed when this epic is merged
- [ ] https://github.com/metabase/metabase/issues/19744
```
