### ISSUE TITLE
[Epic] Allow multiple breakouts of the same column

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#46536]
Product doc https://www.notion.so/metabase/Allow-multiple-breakouts-of-the-same-column-9b6c5b715f8a4434b74501f13271be89

### Milestone 1 - support multiple breakouts without allowing them in the UI

Can be merged to master directly since we don't change the existing behavior until milestone 2.

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/46594
- [ ] https://github.com/metabase/metabase/pull/46555
- [ ] https://github.com/metabase/metabase/issues/46644
```

### Milestone 2 - allow multiple breakouts in the UI

Actually allow multiple columns in the notebook editor.

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/46776
- [ ] https://github.com/metabase/metabase/issues/46610
```

### Milestone 3 - MBQL lib bugs

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/47575
```
