### ISSUE TITLE
[Epic] Reduce the number of choices in onboarding flow

### ISSUE THREAD

**Issue by npretto** [metabase/metabase#46741]
**Links**
- [product doc](https://www.notion.so/metabase/Reduce-the-number-of-choices-in-onboarding-flow-f74849658dce4cceb9a9fd33b243f820)
- [eng doc](https://www.notion.so/metabase/Tech-Reduce-the-number-of-choices-in-onboarding-flow-9def6e76d62d4c4f86b269191324ce69)

**Implementation Plan**

```[tasklist]
### Milestone 1 - newsletter
- [ ] https://github.com/metabase/metabase/pull/46834
- [ ] https://github.com/metabase/metabase/pull/46783
- [ ] https://github.com/metabase/metabase/pull/47021
```

```[tasklist]
### Milestone 2 - hide data consent step
- [ ] https://github.com/metabase/metabase/pull/46965
- [ ] https://github.com/metabase/metabase/pull/47055
```

UPDATE: this was supposed to be backported to v50, so there's the backport PR: https://github.com/metabase/metabase/pull/47067

**Comment by npretto** [comment]
Closed by the backport here: [Reduce the number of choices in onboarding flow [backport] (+316 −239)](https://github.com/metabase/metabase/pull/47067)
