### ISSUE TITLE
[Epic] Feature flag and settings for SDK

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#46970]
>[!CAUTION]
> Do not merge the feature branch `46970-sdk-feature-flag-and-settings` unless we are ready to launch the SDK publicly as a whole.

**Links**
- [Product doc](https://www.notion.so/metabase/Feature-flag-and-settings-for-SDK-8ed424c776194528b6332c5fc2510a0c)
- [Eng doc](https://www.notion.so/metabase/Tech-Split-the-admin-settings-for-iframe-and-SDK-embedding-9945e76d7e80404fa79b7d5b93049978)
- [Testing plan](https://www.notion.so/metabase/Testing-plan-Split-the-admin-settings-for-iframe-and-SDK-embedding-c11a850f05254fa28133ed616546dfa0)
- [Figma file](https://www.figma.com/design/W1TfzdrR8ldzp4vdjP1z36/SDK-Embedding%3A-admin-settings-%2B-embed-flow?node-id=10563-15285&node-type=section&t=i9w041BGBjMvF49p-0)
- feature branch:
    ```
    46970-sdk-feature-flag-and-settings
    ```

Milestone 0 branch (BE)
```
46970-milestone-0
```
```[tasklist]
### Milestone 0: BE
- [ ] https://github.com/metabase/metabase/issues/47521
- [ ] https://github.com/metabase/metabase/issues/47522
- [ ] https://github.com/metabase/metabase/issues/47525
- [ ] https://github.com/metabase/metabase/issues/47526
- [ ] https://github.com/metabase/metabase/issues/47528
- [ ] https://github.com/metabase/metabase/issues/47524
- [ ] https://github.com/metabase/metabase/issues/47527
- [ ] https://github.com/metabase/metabase/issues/47906
```

Milestone 1 branch
```
46970-milestone-1
```

```[tasklist]
### Milestone 1
- [ ] https://github.com/metabase/metabase/issues/47185
- [ ] https://github.com/metabase/metabase/issues/47501
- [ ] https://github.com/metabase/metabase/issues/47682
- [x] Add an SDK setting page with CORS setting similar to the one for interactive embedding
- [x] Wire the new setting on BE and implement BE setting logic (will be implemented in milestone 0)
- [ ] https://github.com/metabase/metabase/issues/47754
```

Milestone 2 branch
```
46970-milestone-2
```
```[tasklist]
### Milestone 2
- [ ] https://github.com/metabase/metabase/issues/47766
- [ ] https://github.com/metabase/metabase/issues/47881
- [ ] https://github.com/metabase/metabase/issues/47767
- [ ] https://github.com/metabase/metabase/issues/47768
- [x] make sure https://github.com/metabase/metabase/commit/0888589d373d694a715582da2c30f8bed2abb8cb is reverted before merging to master
```
