### ISSUE TITLE
E2E Sandboxing Test Fixes/Improvements

### ISSUE THREAD

**Issue by sloansparger** [metabase/metabase#47095]
Some sandboxing E2E tests are giving us false positives. There's two major issues that led to this being possible:
- E2E sandboxing setup was broken during the split permissions migration that happened from v49 -> v50
- Assertions in our sandbox tests aren't strict enough and generally make no assertions that the underlying data is actually sandboxed.

For a more eloquent explanation and history of this problem, read @nemanjaglumac's message here:
https://metaboat.slack.com/archives/C505ZNNH4/p1724187422396359

```[tasklist]
### Tasks
- [x] add assertions that tests are working with sandboxed data (test for `is_sandboxed` on results data, add assertions that certain data should not be visible, and add assertions that results are limited)
- [x] add helpers for modifying the default group's permissions to allow for setting up sandboxing using `default` snapshot + port tests to new utils
- [x] remove the` default-ee` snapshot
```
