### ISSUE TITLE
[Epic] Explain usage and restrictions for metrics

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#47147]
Product doc https://www.notion.so/metabase/Explain-usage-and-restrictions-for-metrics-3909b6db9fbb4707b4f823a904721096

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/47148
- [ ] https://github.com/metabase/metabase/issues/47152
- [ ] https://github.com/metabase/metabase/issues/47149
- [ ] https://github.com/metabase/metabase/issues/47588
- [ ] https://github.com/metabase/metabase/issues/47151
- [ ] https://github.com/metabase/metabase/issues/47701
- [ ] https://github.com/metabase/metabase/issues/47600
```
