### ISSUE TITLE
[Epic] Simple Metrics Overview Page

### ISSUE THREAD

**Issue by romeovs** [metabase/metabase#47187]
**Links**
- [product doc](https://www.notion.so/metabase/Allow-users-to-view-all-metrics-in-one-place-de5ca5fcc8a24d8499d167a74137feac)

As part of [Allow users to view all metrics in one place](https://www.notion.so/metabase/Allow-users-to-view-all-metrics-in-one-place-de5ca5fcc8a24d8499d167a74137feac) we want to show a simple bare-bones table of metrics.

**Implementation Plan**

***Milestone 1***

```[tasklist]
- [ ] Add simple Browse metrics page like the /browser/models page
- [ ] Implement row actions (…) on the “Browse metrics” page
- [ ] Implement pagination on the “Browse metrics” page
```
