### ISSUE TITLE
[Epic] Multi-dimensional / Sunburst Pie chart

### ISSUE THREAD

**Issue by EmmadUsmani** [metabase/metabase#47209]
**Links**
- product doc: [Offer new viz type: Multi-dimensional / Sunburst Pie chart](https://www.notion.so/metabase/Offer-new-viz-type-Multi-dimensional-Sunburst-Pie-chart-1bf26a2d04064f45ba8918c8f87d15ac)
- feature branch:  add-sunburst-to-pie-chart
- pr: https://github.com/metabase/metabase/pull/47208

Total estimate: 20 days / 4 weeks

### ECharts Data Layer (`chartModel`) [1-2 days]
- [x] add middle ring slices to `chartModel.slices`
- [x] render basic middle ring in option
- [x] add outer ring slices to `chartModel.slices`
- [x] render basic outer ring in option
- [x] ~update `isNonPositive` to account for middle and outer ring slices~
- [x] only show unaggregated warning if last ring has unaggregated values
- [x] aggregate slices into `other` in middle and outer rings

### ECharts Viz Layer (option object, rendering viz settings, styles)

**Labels** [2-3 days]
- [x] conditionally combine slice name with percent in label
    - [x] add viz setting for this, compute a sensible default
- [x] update label rotation (might depend on ring level)
- [x] re-introduce dimension formatting to echarts code for middle & outer slices
- [x] dynamic font sizing (depends on canvas size, rings)
- [x] update `getIsLabelVisible` to account for label rotation, number of rings

**Colors** [1 day]
- [x] get light/dark variants from brand color to use in middle & outer slices
- [x] ~alternative logic for white-labeled / embedded colors?~

**Styles** [1-2 days]
- [x] update inner/outer radius logic (depends on rings)
- [x] apply minimum slice size adjust to middle & outer rings
- [x] update slice border width logic

**Total** [1-2 days]
- [x] only show sub-total for sub-slice on hover
- [x] ~dynamic font size depending on rings + canvas size~

**Tooltip/Hover/Click** [2-3 days]
- [x] update hover chart events so tooltip knows which slices to use
- [x] update tooltip UI
- [x] update legend hover events
- [x] update click event to return correct value
- [x] update tooltip UI for "other" slices

### Viz Settings Sidebar UI [3 days]
- [x] move measure to top
- [x] create parent component to handle all of `pie.dimension`, `pie.middle_dimension`, `pie.outer_dimension`, `pie.rows`, & `pie.sort_rows` settings
    - [x] render dropdown menus for selecting `pie.dimension`, `pie.middle_dimension`, `pie.outer_dimension`
        - [x] render `Add ring` button and modify settings/UI appropriately
    - [x] rerender/re-wire `ChartSettingOrderedSimple` and `SliceNameWidget` components for `pie.rows` setting 
    - [x] use dnd-kit to support re-ordering rings, update settings appropriately
    
### Viz Settings Computations  [1 day]
- [x] compute suitable defaults based on query results, re-use in static viz
- [x] update definition of when pie/sunburst is sensible (collab with Conor on this)

### Testing [2-3 days]
- [x] loki static viz tests
- [x] e2e tests

### Bugs
- [x] #47869
- [x] #47776
- [x] #47867
- [x] #47775
- [x] #47931
- [x] field name remapping from admin settings doesn’t work for non-inner slice
- [x] metric value should be aggregated for click actions
- [x] minimum slice percentage setting should be based on parent slice
- [x] total value text should be truncated or hidden
- [x] ~latitude/longitude don't work as metric values~
