### ISSUE TITLE
[Epic] Serialization fixes

### ISSUE THREAD

**Issue by piranha** [metabase/metabase#47221]
It's a result of working on many serialization issues and a [post-mortem](https://www.notion.so/metabase/Serialization-too-many-bugs-over-time-17598bd6e30a4bf1929e9b13c3d8ea5a) on those.

```[tasklist]
### More transparent execution
- [x] #43068 (sub-epic)
- [ ] #45371
- [ ] #45225
- [ ] https://github.com/metabase/metabase/issues/47223
- [ ] https://github.com/metabase/metabase/issues/47222
- [ ] #46039
- [ ] https://github.com/metabase/metabase/issues/47467
```
