### ISSUE TITLE
[Epic] Sidesheets

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#47243]
```[tasklist]
### Tasks
- [ ] Basic sidesheet components (#47100)
- [ ] Question info sidesheet
- [ ] Question settings sidesheet
- [ ] Dashboard settings sidesheet
- [ ] Dashboard info sidesheet
```

**Comment by iethree** [comment]
duplicate of https://github.com/metabase/metabase/issues/42527
