### ISSUE TITLE
[Epic] Search in selection in entity picker

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#47281]
### Links
- [Product doc](https://www.notion.so/metabase/Search-in-selection-in-entity-picker-e4d830a6a35a416abb135e103de1d452)
- [Figma](https://www.figma.com/design/06jovUhXOrsRO8FYZi7G1d/Data-picker-improvements?node-id=6337-13756&t=ZNdlYTiiKu4u3CCl-0)
- Testing plan: #47282
- Feature branch: `entity-picker-scoped-search`
  - PR: #47755
- Links:
  - Prototype: #46518
  - [Slack (design exploration & prototype)](https://metaboat.slack.com/archives/C0645JP1W81/p1722430559770769)
  - [Slack (alternative suggestion)](https://metaboat.slack.com/archives/C0645JP1W81/p1724169658897609)
  - #47182

### Milestone 1

```[tasklist]
### Frontend
- [ ] https://github.com/metabase/metabase/issues/47288
- [ ] https://github.com/metabase/metabase/issues/47502
- [ ] https://github.com/metabase/metabase/issues/47454
- [ ] https://github.com/metabase/metabase/issues/47289
- [ ] https://github.com/metabase/metabase/issues/47290
- [ ] https://github.com/metabase/metabase/issues/47292
- [ ] https://github.com/metabase/metabase/issues/47291
- [ ] https://github.com/metabase/metabase/pull/48122
- [ ] https://github.com/metabase/metabase/issues/47182
```
