### ISSUE TITLE
[Epic] Notification: Simple text

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#47438]
**Links**
- product doc: https://www.notion.so/metabase/Simple-text-notification-modularize-notification-triggers-migrate-3-transactional-emails-to-new-ar-8adf797c8c9d46139209a4c14d3b5917?pvs=4
- eng doc: https://www.notion.so/metabase/Simple-text-notification-74beda71982e4d2cab62efeb5b7f3734?pvs=4
- feature branch: `notification-simple-text` 

```[tasklist]
### Milestone 1: Infrastructure
- [x] New table: notification + notification_subscription
- [x] New module: notification + system event notification
- [x] New table: notification_handler, notification_recipient
- [x] New table: channel_template
- [x] Update email channel to render system-event notification
- [x] Send notification async
- [x] Event hydration
```

PR: https://github.com/metabase/metabase/pull/47857

```[tasklist]
### Milestone 2: Migrate transactional emails
- [x] You're invited
- [x] Alert created
- [x] Slack token error
```
PR: https://github.com/metabase/metabase/pull/48392

```[tasklist]
### Milestone 3: Misc
- [x] Channel Retry
- [x] TaskHistory tracking
- [x] Serdes + copy (no serdes)
- [x] Auditing (deferred until we have the APIs)
```
PR: https://github.com/metabase/metabase/pull/48437
