### ISSUE TITLE
[SDK] Improvements for Create/Modify Question

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#47536]
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/47448
- [ ] https://github.com/metabase/metabase/issues/47464
- [ ] https://github.com/metabase/metabase/issues/47535
- [ ] https://github.com/metabase/metabase/issues/47537
- [ ] https://github.com/metabase/metabase/issues/47347
- [ ] https://github.com/metabase/metabase/issues/47344
- [ ] https://github.com/metabase/metabase/issues/47559
- [ ] https://github.com/metabase/metabase/issues/47560
- [ ] https://github.com/metabase/metabase/issues/47561
- [ ] https://github.com/metabase/metabase/issues/47562
```

**Comment by oisincoveney** [comment]
Moved all items to https://github.com/metabase/metabase/issues/47842
