### ISSUE TITLE
[Epic] Remove low-hanging fruit console errors visible in the embedding sdk

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#47655]
Let's aim to eliminate the visible console errors present in the embedding sdk. This is usually caused by React errors in the main Metabase app's components, which is especially visible for embedding sdk users.

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/47656
- [ ] https://github.com/metabase/metabase/issues/48496
- [ ] https://github.com/metabase/metabase/pull/48764
- [ ] https://github.com/metabase/metabase/pull/48770
```

### Screenshots

When using create-react-app and installing the embedding SDK via npm (which uses our production bundle), the React errors still appears on the host application.

![Image](https://github.com/user-attachments/assets/263168e5-24f8-487d-83e7-a7c20575fd94)

**Comment by heypoom** [comment]
Paused to prioritize working on important SDK polishing/improvements.
