### ISSUE TITLE
Handle settings set via environment variables

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#47768]
```[tasklist]
### Tasks
- [ ] `enable-embedding` (old setting)
- [ ] `enable-embedding-sdk`
- [ ] `enable-embedding-static`
- [ ] `enable-embedding-interactive`
- [ ] `embedding-app-origin` (old setting)
- [ ] `embedding-app-origins-sdk`
- [ ] `embedding-app-origins-interactive`
```
