### ISSUE TITLE
[Epic] Title

### ISSUE THREAD

**Issue by romeovs** [metabase/metabase#47777]
**Links**
- [product doc](https://www.notion.so/metabase/Metrics-page-part-2-de5ca5fcc8a24d8499d167a74137feac)
- [tech doc](https://www.notion.so/Tech-Doc-Allow-users-to-view-all-metrics-in-one-place-5b39d90e8df849909302fab389e15097?pvs=24)

**Implementation Plan**

### Milestone 1
Implemented in https://github.com/metabase/metabase/issues/46956

### Milestone 2 — FE+BE

```[tasklist]
- [ ] [BE] add `sort` and `sort_order` to `/api/search`  OR build a separate endpoint for metrics
- [ ] [BE] support permission check to show Edit definition in (…)
- [ ] Implement pagination on the “Browse metrics” page
```

### Milestone 3 — FE

Show the last value of the metric timeseries or the value of a scalar metric in the table on the “Browse metrics” page

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/47603
- [ ] https://github.com/metabase/metabase/issues/47726
```

### Milestone 4 — BE+FE
```[tasklist]
- [ ] BE: allow to change granularity and filter for metrics
- [ ] Allow to choose granularity and filter to calculate the value — in case of error not show the results
```

### Milestone 5 — BE+FE
```[tasklist]
- [ ] [BE] return metric data source name and data source type in search results
- [ ] Show data source name and type icon
```

### Milestone 6 — BE+FE
```[tasklist]
- [ ] Add text search input to the Browse metrics page
- [ ] BE] Allow filtering by collections and data source ids in /api/search
- [ ] Add filtering dropdowns for source and collection
```

### Milestone 7 — BE+FE
```[tasklist]
- [ ] Sparklines — possibly reuse or customize current line chart implementation
```
