### ISSUE TITLE
[Epic] Make query builder UI controls more predictable

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#47911]
**Links**
- product doc: https://www.notion.so/metabase/Make-query-builder-UI-controls-more-predictable-6fd99a110a954c2fb3fba8d8a8c24ae5
- feature branch: `qb-predictable`
- testing plan - ML1 changes only existing functionality, so no new tests required, ML2 requires a new testing plan

```[tasklist]
### Actual Milestone
- [ ] https://github.com/metabase/metabase/pull/51651
- [ ] https://github.com/metabase/metabase/pull/51650
- [ ] https://github.com/metabase/metabase/pull/51670
- [ ] https://github.com/metabase/metabase/pull/51666
- [ ] https://github.com/metabase/metabase/pull/51655
- [ ] https://github.com/metabase/metabase/pull/51671
- [ ] https://github.com/metabase/metabase/pull/51674
- [ ] https://github.com/metabase/metabase/pull/51903
- [ ] https://github.com/metabase/metabase/pull/51905
```

### Abandoned

```[tasklist]
### Milestone 1 - Abandoned
- [x] Change Last to Previous
- [x] Change the icon for the preview buttons to the eye icon
- [x] Add View the SQL / Hide the SQL text to the SQL preview button instead of the tooltip
- [x] Rename Visualization to Visualization type and add Settings text to the viz settings button
- [x] Add Results and Visualization texts to the viz switch
- [x] Change the visual style of the buttons so that they all look active instead of 3 active ones
- [x] sort the buttons in the order of the blocks they will add
- [x] Show small Join data and Custom column buttons when there is an aggregation without breakouts in the last query stage
```

```[tasklist]
### Milestone 2 - Abandoned
- [x] Convert ChartSettinsg to TS
- [ ] https://github.com/metabase/metabase/issues/50027
- [ ] https://github.com/metabase/metabase/issues/50026
- [ ] https://github.com/metabase/metabase/issues/50262
- [ ] https://github.com/metabase/metabase/issues/50265
- [ ] https://github.com/metabase/metabase/issues/50358
- [ ] https://github.com/metabase/metabase/issues/50362
- [x] hide chart settings button in results view
- [ ] https://github.com/metabase/metabase/issues/50025
- [ ] https://github.com/metabase/metabase/issues/50263
- [ ] https://github.com/metabase/metabase/issues/50451
- [ ] https://github.com/metabase/metabase/issues/50452
- [ ] button height problem
```
