### ISSUE TITLE
Permissions admin panel changes

### ISSUE THREAD

**Issue by dpsutton** [metabase/metabase#48083]
```[tasklist]
### Tasks
- [x] Allow `Query builder and native` to be an option at the schema-level
- [x] Allow `Query builder and native` to be an option at the tabel-level
- [x] Update permissions help copy to reflect changes
- [x] Prevent various changes like sandboxing / blocking tables dropping native permissions from all tables/schemas in db
- [x] Remove warning UI that tells users w/ a blocked table that native permissions are not available for entire db
- [x] Fix existing E2E tests
- [x] Add test coverage
- [ ] update the permissions editor to only allow "Query builder and native" for supported databases
```
