### ISSUE TITLE
[Epic] Table-level permissions for native queries

### ISSUE THREAD

**Issue by piranha** [metabase/metabase#48080]
**Links**
- [product doc](https://github.com/metabase/metabase/issues/new?assignees=&labels=.Epic&projects=&template=epic.md&title=%5BEpic%5D+Title)
- [tech doc](https://www.notion.so/metabase/Tech-Doc-Table-level-block-for-native-queries-08e279f3eaca4fcdb2276f1f490483a2)
- [fe tech doc](https://www.notion.so/metabase/Mini-tech-doc-Allow-table-level-blocking-on-the-FE-10a69354c90180d1b147e0a4ded2d343)
- [Slack thread](https://metaboat.slack.com/archives/C06V3JMECH2/p1727117590072569) for more context
- [Meeting notes](https://www.notion.so/metabase/Focus-room-native-query-table-level-permissions-10c69354c901808ab67dd9d25c8b3221) for even more context

```[tasklist]
### Front-end
- [ ] Check native queries via backend permission system
- [ ] https://github.com/metabase/metabase/issues/48083
```

```[tasklist]
### Back-end
- [ ] https://github.com/metabase/metabase/issues/48110
- [x] Block queries on un-synced tables/views when any table-level blocks are set
- [x] Check perms when saving a native question
- [x] Ensure that table-level native perms get cleared on downgrade
- [ ] Block setting table-level native query perms on unsupported DBs
- [ ] https://github.com/metabase/macaw/pull/105
- [ ] https://github.com/metabase/metabase/pull/48990
- [ ] https://github.com/metabase/metabase/pull/49078
- [ ] https://github.com/metabase/macaw/pull/107
```
