### ISSUE TITLE
[Epic] Visualizer

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#48280]
**Links**
- [product doc](https://www.notion.so/metabase/Create-the-Visualizer-for-easier-exploration-and-crafting-charts-a1273d1be0414d43b2e425511e36ba08#11369354c9018002a8c4f2450e169a5a) 
- [eng doc](https://www.notion.so/metabase/Visualizer-Tech-Design-55f42e7f881349a7bde2b161266fbd30?d=10669354c9018010b8d3001c140c562a#29ed58e7860b4c878b59405ccc589c25)
- branch: `feature-visualizer`

**Implementation Plan**

***Milestone 0.1***

- [x] Create visualizer page accessible from New -> Visualizer
- [x] Add the Data Importer stub: search input with list of results that calls the existing search endpoint
- [x] Add the Data Manager which shows questions selected in the Data Importer stub
- [x] Single dataset Funnel chart
  - [x] Render the Canvas that supports only Funnel chart and 1 dataset (as a regular funnel question)
  - [x] Implement Dimension/Metric selection via DnD from Data Manager
  - [x] Support funnel steps reordering via DnD
- [ ] N-scalar datasets Funnel chart
  - [ ] Implement data transformation from N-scalars into a single dataset to match API of the Funnel chart
  - [ ] Update Data Manager UI <> DnD to work sensibly in this case
