### ISSUE TITLE
[MS2] Better Onboarding: Expand upload CSV permissions to non-admins

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#48325]
## Links
- [Product doc](https://www.notion.so/metabase/Better-Onboarding-via-first-time-UX-7c76eef94d414bb0a864d7cc786229f2)
- [Figma designs](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6290-2701&node-type=canvas&m=dev)
    - [Main navigation updates](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6297-33793&m=dev)
    - [Add data section](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6290-2723&m=dev)
- Feature branch: `better-onboarding-ux-ms2`
---
### Implementation Plan
Expand the permission scope for **upload CVSs only** to any non-admin who has a curate collection permissions _in the root (Our analytics) collection_. This should be a rather small PR as the majority of visual changes have already been implemented in #48335

> [!CAUTION]
> Keep an eye on the scenario in which a user has root collection write permissions, but doesn't have data permissions for a database for which uploads are enabled.

```[tasklist]
## Checklist
- [x] MS 2.1: Expand "upload CSV" permissions to non-admins
- [x] MS 2.2: Cover extensively with tests
- [x] MS 2.3: Remove the Metabase _learn_ link
```

### Testing plan
Everything should still work the same for admins, so no new tests are needed. We only need to make sure the existing ones are not broken.

For non-admins:
#### "Add database" button
- [x] Should never render

#### "Upload a spreadsheet" button
- [x] Should not render if a user does not have "curate" permissions for Root Collection
- [x] Should not render if a user does not have data access
- [x] Should render if a user has "curate" permissions for Root Collection AND
    - [x] has data access to at least one database **if admins didn't enable uploads** OR
    - [x] has permissions to upload specifically to the database for which **uploads are enabled**
