### ISSUE TITLE
[MS1] Better Onboarding: Educational Section in the Main Sidebar

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#48335]
## Links
- [Product doc](https://www.notion.so/metabase/Better-Onboarding-via-first-time-UX-7c76eef94d414bb0a864d7cc786229f2)
- [Figma designs](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6290-2701&node-type=canvas&m=dev)
    - [Main navigation updates](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6297-33793&m=dev)
    - [Add data section](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6290-2723&m=dev)
- Feature branch: `better-onboarding-ux-ms1`

### Implementation Plan
Introduce the new onboarding (footer) section in the main navigation sidebar. To goal is to help admins set up their instances faster by prompting them to (1) add their own database and/or (2) upload CSV. We're also making the link to Metabase Learn content more prominent.

> [!Important]
> In this phase we're making the "Add data" section available to **admins only**!

```[tasklist]
## Checklist
- [x] MS 1.1: Add visual elements
- [x] MS 1.2: Logic (Business and Permissions)
- [x] MS 1.3: Simple event schema analytics
- [x] MS 1.4: Tests
- [ ] MS 1.5: Final design polish (optional)
```

```[tasklist]
### Add database
- [x] Allow only admins to see this button
- [x] Remove the existing "Add your own data button"
```

```[tasklist]
### Upload CSV Button
- [x] Allow only admins to see and use this
- [x] Upload to "Our analytics" only
- [x] Trigger the upload modal
- [x] Upload types: create, append, replace
- [x] Remove the existing "Upload CSV" (for DWH) button
```
