### ISSUE TITLE
[Epic] Tool to migrate questions into dashboards

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#48364]
[Product doc](https://www.notion.so/metabase/Tool-to-migrate-questions-into-dashboards-11569354c90180b08c4af2662aaf34a8)

- [ ] BE endpoint to get movable questions
- [ ] BE endpoint to move questions
- [ ] FE component to move questions
- [ ] FE callout using the new key-value pair
