### ISSUE TITLE
[MS1] Admin Onboarding Checklist

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#48387]
## Links
- [Product doc](https://www.notion.so/metabase/Better-Onboarding-via-first-time-UX-7c76eef94d414bb0a864d7cc786229f2)
- [Figma designs](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6290-2701&node-type=canvas&m=dev)
    - [Admin view](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6364-30843&m=dev)
- Feature branch: `onboarding-checklist-admins`

### Implementation Plan
Introduce a new page/route dedicated to better onboarding in the form of a checklist. "How to use Metabase" link should open this page from the main sidebar.

```[tasklist]
### Checklist
- [x] New item in the sidebar
- [x] New (admin guarded) route
- [x] Admin view
- [x] Tailored accordion component
- [x] Remember last visited accordion item
- [x] Smooth scroll opened item into view
- [x] Analytics
```

```[tasklist]
### Potential follow-ups (will be converted to individual sub-issues)
- [ ] Make user control whether or not to show the "How to use Metabase" link, rather than the logic being time-based
- [ ] Get rid of CSS accordion hacks
- [ ] Use Loom instead of YouTube for the tutorial videos?
```
