### ISSUE TITLE
[Epic] Select All follow-ups

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#48394]
Product doc https://www.notion.so/metabase/Select-All-follow-ups-11569354c90180acbf3fff813e26b524
Figma https://www.figma.com/design/pq7Dv7P1lFfXCjI7Wbk8MQ/maz-filters-beautification-idea-sep-2024?node-id=14-262&node-type=section&t=KCBCEY17JahJUw4c-0

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/48398
- [ ] https://github.com/metabase/metabase/issues/48395
- [ ] https://github.com/metabase/metabase/issues/48408
```
