### ISSUE TITLE
[Epic] Alert UI Polish

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#48430]
A collection of issues and adjustments found with the Alert UI after the addition of webhooks. These aren't regressions, but situations that may be more common now that there is a 3rd notification type (Email, Slack, and Webhook)

- [x] https://github.com/metabase/metabase/issues/48428
- [x] https://github.com/metabase/metabase/issues/48407
- [x] https://github.com/metabase/metabase/issues/48406
- [x] https://github.com/metabase/metabase/issues/48402
- [x] #48751
- [x] #48803
