### ISSUE TITLE
[Epic] Title

### ISSUE THREAD

**Issue by romeovs** [metabase/metabase#48447]
[product doc](https://www.notion.so/metabase/Metrics-v2-follow-ups-11569354c90180d38cdcd1b042f17fe4)

## Implementation Plan

```[tasklist]
### Milestone 1: FE
- [ ] Change the texts to be the same in the empty state of the Metrics page and the Metric editor
- [ ] Change texts from "Basic Metrics" and "Common Metrics" to "Summaries" and "Metrics” in the Summarize block in the notebook editor and the Summarize sidebar in the chill mode
- [ ] Implement a button to create a new metric in the empty state of the Metrics page
- [ ] Show metric name as the column name in the resulting table (like Revenue instead of Sum of Total)
- [ ] https://github.com/metabase/metabase/issues/47058
```

```[tasklist]
## Milestone 2: BE
- [ ] https://github.com/metabase/metabase/issues/48192
- [ ] https://github.com/metabase/metabase/issues/44210
- [ ] https://github.com/metabase/metabase/issues/48277
```
