### ISSUE TITLE
[Epic] Native query drill

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#48466]
```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/48232
- [ ] https://github.com/metabase/metabase/pull/48459
- [ ] https://github.com/metabase/metabase/pull/48463
- [ ] https://github.com/metabase/metabase/pull/48482
- [ ] https://github.com/metabase/metabase/issues/48469
```
