### ISSUE TITLE
[Epic] Compare UI follow-ons part 2

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#48533]
Product doc https://www.notion.so/metabase/Compare-UI-follow-ons-part-2-13ff2cab0d714b58904ea038ad0ae843

#### Milestone 1 - Time over time comparison UI changes

Change the popover + disallow nesting offset calls.

```[tasklist]
- [ ] Time over time comparison UI
- [ ] [Testing plan] Time over time comparison UI
```

#### Milestone 2 - visualization settings

```[tasklist]
- [ ] Set viz settings for newly created columns
- [ ] [Testing plan] Set viz settings for newly created columns
```

...
