### ISSUE TITLE
[Epic] Improve SDK npm release process

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#48727]
**Links**
- [product doc](https://www.notion.so/metabase/Improve-npm-release-process-11e69354c901808687bcfb8368fd0327)

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/48728
- [ ] https://github.com/metabase/metabase/issues/48822
- [ ] https://github.com/metabase/metabase/issues/48974
- [ ] https://github.com/metabase/metabase/issues/48844
- [ ] https://github.com/metabase/metabase/pull/49074
- [ ] https://github.com/metabase/metabase/pull/49083
```
