### ISSUE TITLE
[Epic] Content Verification

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#48911]
**Links**
- Product Doc: [link](https://www.notion.so/metabase/Evolve-content-verification-and-deprecation-03e20f5c0cad4323be671423a1b473ce)

**Implementation Plan**
Implementation plan is largely extending the current verification system to Dashboards, extending it to include content deprecation, then incorporation entity health. Each milestone should be mergable (and shippable?) independently.

***Milestone 1: Verified Dashboards***
- [x] #48954
- [x] #49188
- [x] #49398

***Milestone 2: Add Reasons + new Statuses to Entities***
- [ ] FE: Build verification popover
- [ ] #49295
- [ ] New statuses to moderation reviews: `"neutral"` `"expired"` `"flagged"`
- [ ] #49628
- [ ] Event tracking

***Milestone 3: Moderation Review Expiration***
- [ ] FE: send expiration
- [ ] BE: Add expiration to moderation statuses
- [ ] BE: Add 'cron job' to mark moderation statuses as expired
- [ ] BE: Add notification warning for moderation review expiration

***Milestone 4: Health Status***
- [ ] BE: Figure out persistence for Health Status (new table probably)
- [ ] BE: Add Health status propogation
- [ ] FE: Display Health of Entities

***Milestone 5: Verification Notifications***
- [ ] BE: Add boolean "has_warned" column to `moderation_status`
    - Used for sending emails.
- [ ] BE: Send Emails on verification expiration
    - to the users who have edited the card / verified it
