### ISSUE TITLE
[Epic] Remove Tippy

### ISSUE THREAD

**Issue by npfitz** [metabase/metabase#48928]
**Description**
Simple Epic to track migrating components away from Tippy in favor of the `<Popover>` component from Mantine.

- [ ] actions/containers/ActionCreator/FormCreator/FieldSettingsPopover.tsx
- [ ] actions/containers/ActionCreator/FormCreator/OptionEditor.tsx
- [ ] parameters/components/ParameterTargetWidget.jsx
- [ ] core/components/AccordionList/AccordionList.unit.spec.js
- [ ] core/components/Select/Select.tsx
- [ ] core/components/DateWidget/DateWidget.tsx
- [ ] core/components/ColorPicker/ColorPicker.tsx
- [ ] core/components/ColorRangeSelector/ColorRangeSelector.tsx
- [ ] core/components/ColorSelector/ColorSelector.tsx
- [ ] core/components/AutocompleteInput/AutocompleteInput.tsx
- [ ] core/components/Tooltip/Tooltip.tsx
- [ ] core/components/TabButton/TabButton.tsx
- [ ] nav/containers/MainNavbar/MainNavbarContainer/MainNavbarView.tsx
- [ ] visualizations/visualizations/LinkViz/LinkViz.tsx
- [ ] visualizations/components/ChartSettingsWidgetPopover.tsx
- [ ] visualizations/components/legend/Legend.jsx
- [ ] visualizations/components/ClickActions/ClickActionsPopover.styled.tsx
- [ ] visualizations/components/ChartSettingsWidget.tsx
- [ ] visualizations/components/skeletons/ChartSkeleton/ChartSkeleton.unit.spec.tsx
- [ ] containers/ItemSelect.jsx
- [ ] query_builder/components/view/QuestionRowCount/QuestionRowCount.tsx
- [ ] query_builder/components/NativeQueryEditor/RightClickPopover/RightClickPopover.tsx
- [ ] query_builder/components/SelectionModule.jsx
- [ ] query_builder/components/template_tags/SnippetSidebar/SnippetSidebar.jsx
- [ ] query_builder/components/expressions/ExpressionEditorHelpText/ExpressionEditorHelpText.tsx
- [ ] query_builder/components/DataSelector/DataSelector.jsx
- [ ] search/components/DropdownSidebarFilter/DropdownSidebarFilter.tsx
- [ ] public/containers/PublicOrEmbeddedDashboard/PublicOrEmbeddedDashboardView.stories.tsx
- [ ] admin/permissions/components/PermissionsSelect/PermissionsSelect.jsx
- [ ] admin/permissions/components/ToolbarUpsell/ToolbarUpsell.tsx
- [ ] admin/datamodel/metadata/components/FieldRemappingSettings/FieldRemappingSettings.jsx
- [ ] admin/datamodel/metadata/components/MetadataTableColumnList/MetadataTableColumnList.tsx
- [ ] admin/datamodel/components/DimensionList/DimensionList.jsx
- [ ] admin/datamodel/components/FilterPopover/FilterPopoverFooter.tsx
- [ ] admin/datamodel/components/filters/pickers/LegacyDatePicker/DatePicker.jsx
- [ ] admin/datamodel/components/filters/pickers/SelectPicker.jsx
- [ ] admin/datamodel/components/filters/pickers/DatePicker/CurrentPicker/CurrentPicker.tsx
- [ ] admin/datamodel/components/filters/pickers/DefaultPicker/DefaultPicker.tsx
- [ ] admin/datamodel/components/ObjectActionSelect.jsx
- [ ] admin/settings/components/widgets/ModelCachingScheduleWidget/CronExpressionInput.tsx
- [ ] admin/settings/components/widgets/GroupMappingsWidget/GroupSelect/GroupSelect.tsx
- [ ] admin/settings/components/ApiKeys/SecretKeyModal.tsx
- [ ] admin/databases/components/DatabaseEditApp/Sidebar/ModelCachingControl/ModelCachingControl.tsx
- [ ] admin/people/components/GroupsListing.jsx
- [ ] admin/people/components/AddMemberRow.jsx
- [ ] admin/people/components/MembershipSelect/MembershipSelect.tsx
- [ ] components/TokenField/TokenField.tsx
- [ ] components/Popover/TippyPopover.tsx
- [ ] components/PopoverWithTrigger/PopoverWithTrigger.jsx
- [ ] components/PopoverWithTrigger/ControlledPopoverWithTrigger.tsx
- [ ] dashboard/components/DashCard/DashCardParameterMapper/DashCardCardParameterMapperButton.tsx
- [ ] dashboard/components/ClickBehaviorSidebar/LinkOptions/ValuesYouCanReference.jsx
