### ISSUE TITLE
[Epic] SDK Polishing - v51

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#49080]
Notion Docs: [Customer Feedback (Internal)](https://www.notion.so/metabase/SDK-Customer-Feedback-Oct-26-12a69354c90180a38713e92076d8161b?pvs=4)

***Bugs***
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/47563
- [ ] https://github.com/metabase/metabase/issues/48788
- [ ] https://github.com/metabase/metabase/issues/48789
- [ ] https://github.com/metabase/metabase/issues/48925
- [ ] https://github.com/metabase/metabase/issues/48933
- [ ] https://github.com/metabase/metabase/issues/49307
- [ ] https://github.com/metabase/metabase/issues/49081
- [ ] https://github.com/metabase/metabase/issues/49082
- [ ] https://github.com/metabase/metabase/issues/49345
- [ ] https://github.com/metabase/metabase/issues/49346
- [ ] https://github.com/metabase/metabase/issues/49466
- [ ] https://github.com/metabase/metabase/issues/49581
```

***Feature Request***
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/49194
- [ ] https://github.com/metabase/metabase/issues/49229
- [ ] https://github.com/metabase/metabase/issues/49232
- [ ] https://github.com/metabase/metabase/issues/49193
- [ ] https://github.com/metabase/metabase/issues/49325
- [ ] Callbacks / Customization for Table Visualization Data
- [ ] Customize Record Detail view
- [ ] https://github.com/metabase/metabase/issues/49560
```
