### ISSUE TITLE
[Mini Epic] Chart Axes / Display Settings

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#49082]
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/48929
- [ ] https://github.com/metabase/metabase/pull/48941
- [ ] https://github.com/metabase/metabase/pull/48994
- [ ] https://github.com/metabase/metabase/pull/48837
- [ ] Separate settings from visualization in `ChartSettings`
- [ ] PoC of Chart Settings
```
