### ISSUE TITLE
[Testing Plan] Admin Onboarding Checklist

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#49092]
# Testing plan for #48387

## Admin onboarding checklist
We are creating this view for admins only, which makes it easier from the permissions standpoint. However, we should be mindful about the different app settings and the types of instances.

### Dimensions
- User type
    - Admin only
- Instance type
    - Hosted
    - Self-hosted
- License
    - OSS
    - Started
    - Pro
- Environment that Metabase runs in
    - "Regular"
    - Embedding (full app, sdk)
    - On a subpath
- Settings
    - Whitelabelling
        - Show Metabase links?
        - Custom company name?
    - x-rays
        - enabled
        - disabled
    - `example-dashboard-id`
        - available
        - not available
- Analytics
    - enabled
    - disabled
---

### Actions
```[tasklist]
#### Main navigation sidebar
- [x] Show "How to use Metabase" menu item below "Home" for admins only
- [x] Show "How to use Metabase" menu item only for instances that are <= 30 days old
- [x] **Do not show** "How to use Metabase" menu item if whitelabelling is enabled and there is a custom company name
- [x] **Do not show** "How to use Metabase" menu item if the app is embedded
- [x] Clicking on "How to use Metabase" item leads to `/getting-started` page
- [x] Guard the `/getting-started` route if non-admin navigates directly to it
```

```[tasklist]
#### Analytics (Snowplow)
- [x] Track "How to use Metabase" sidebar item click
- [x] Make sure the default opened accordion item on `/getting-started` page load doesn't send Snowplow event
- [x] Track individual checklist item clicks when they open
- [x] Track CTAs (primary or secondary buttons) within an individual checklist item
```

## Checklist page (`/getting-started`)
Has four sections:
  1. Set up your Metabase
  2. Start visualizing your data
  3. Get email updates and alerts
  4. Get the most out of Metabase

```[tasklist]
#### General
- [x] The first accordion item ("Connect to your database") opens by default on the first page load
- [x] Videos do not auto play
- [x] Videos stop playing when the item is collapsed (manually tested!)
- [x] It should be possible to play videos in full screen
- [x] **Show Metabase links enabled**: links are present in the copy, and they lead to the Metabase documentation
- [x] **Show Metabase links disabled**: just the copy exists; no links whatsoever
- [x] Items scroll into view when expanded
```

## 1. _Set up your Metabase_ section
Has two items:
1. Connect to your database
2. Invite people

```[tasklist]
#### 1.1 *Connect to your database* item
- [x] CTA: "Add database" button that leads to `/admin/databases/create`
```

```[tasklist]
#### 1.2 *Invite people* item
- [x] Starter/Pro/Enterprise copy: "Don't be shy with invites. Metabase Starter plan includes 5 users, and Pro includes 10 users without the need to pay additionally."
- [x] OSS copy: "Don't be shy with invites. Metabase makes self-service analytics easy."
- [x] Primary CTA: "Invite people" button that leads to `/admin/people`
- [x] Secondary CTA: "Set up Single Sign-on" button that leads to `/admin/settings/authentication`
```

## 2. _Start visualizing your data_ section
Has four items:
1. Create automatic dashboards
2. Make an interactive chart with the query builder
3. Query with SQL
4. Create and share a dashboard

```[tasklist]
#### 2.1 *Create automatic dashboards* item
- [x] **x-rays enabled** copy: "Hover over a table and click the yellow lightning bolt ⚡️. Metabase will create a bunch of charts based on that data and arrange them on a dashboard."
- [x] **x-rays disabled** copy: "You need to enable this feature first." (maybe link to the general settings?)
- [x] **x-rays enabled** cta: "Browse data" button that leads to `/browse/databases`
- [x] **x-rays disabled**: no cta
```

```[tasklist]
#### 2.2 *Make an interactive chart with the query builder* item
- [x] CTA: "New question" button that opens a new (notebook) **question** page
```

```[tasklist]
#### 2.3 *Query with SQL* item
- [x] CTA: "New native query" button that opens a new (native) **question** page
```

```[tasklist]
#### 2.4 *Create and filter a dashboard* item
- [x] CTA: "Edit a sample dashboard" button that opens `/dashboard/{example-dashboard-id}` link
- [x] If the `example-dashboard-id` is not present in settings (_Example_ collection archived, deleted, or the dashboard itself is missing) **do not show the CTA**
```

## 3. _Get email updates and alerts_ section

Has two items:
1. Get dashboard updates by email
2. Get alerts when metrics behave unexpectedly

```[tasklist]
#### 3.1 *Get dashboard updates by email* item
- [x] **self-hosted**: Prompt to set up email and Slack first
- [x] email link goes to `/admin/settings/email/smtp`
- [x] Slack link goes to `/admin/settings/notifications`
- [x] **hosted**: Do not show email/Slack setup links
- [x] CTA: "Set up subscriptions for a sample dashboard" button that opens `/dashboard/{example-dashboard-id}` link
- [x] If the `example-dashboard-id` is not present in settings (_Example_ collection archived, deleted, or the dashboard itself is missing) **do not show the CTA**
```

```[tasklist]
#### 3.2 *Get alerts when metrics behave unexpectedly* item
- [x] **self-hosted**: Prompt to set up email and Slack first
- [x] **hosted**: Do not show email/Slack setup links
- [x] CTA: "Set up alert for a sample question" button that opens `/question/12` from Example collection[^1]
- [x] If the `example-dashboard-id` is not present in settings, do not display the CTA for the example question
```

## 3. _Get the most out of Metabase_ section
Has two sub-sections:
1. Learn more CTA
2. Help

```[tasklist]
- [x] Do not render "learn more" section if Metabase whitelabelling is turned on with "show Metabase links" set to false
- [x] "Click here to continue learning" link leads to the YouTube playlist
- [x] Show the "help" section only when the token is activated (this automatically excludes OSS instances)
```

[^1]: It is unclear what do to if this question doesn't exist, or how to make sure the id is correct.
