### ISSUE TITLE
[T1] Add Data discoverability: "Add database" button in the main navbar

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#49499]
## Links
[Product doc](https://www.notion.so/metabase/Better-Onboarding-pt-2-Add-Data-discoverability-12769354c90180fb9579f11ce55e7ef2?pvs=4#12769354c9018072ad59ffd9a425d6e3)
Figma
- [+Add button](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6972-13606&m=dev)
- [Add database button](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6972-13607&m=dev)
Feature branch: TBD

## Implementation Plan
1. Implement "Add database" button in a main sidebar below the "Browse" section
2. Implement "Add database" _card_ in a `/browse/databases` page

### Testing Plan
```[tasklist]
#### "Add database" button
- [x] Should not render for regular users
- [x] Should render for admins
- [x] Should render only when no additional database has been added
- [x] Should not render for DWH instances
- [x] Make sure Snowplow events are triggered on click
```

```[tasklist]
#### "Add database" card
- [x] should not render for regular users
- [x] should render for admins
- [x] should render when no databases exist
- [x] Make sure Snowplow events are triggered on click
```
