### ISSUE TITLE
[T2] Add Data Discoverability: Easy-to-discover "Upload CSV" button

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#49500]
## Links
- [Product doc](https://www.notion.so/metabase/Better-Onboarding-pt-2-Add-Data-discoverability-12769354c90180fb9579f11ce55e7ef2?pvs=4#13469354c90180789b26caedec2363e7)
- [Figma](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=7095-37060&m=dev)
- Feature branch: `t2-add-data-upload-csv`
- Previous implementation: https://github.com/metabase/metabase/pull/43511
## Implementation Plan
Bring back the "Upload CSV" button in the main menu for the users with Metabase Storage (DWH) only.

```[tasklist]
### Testing Plan
- [x] Make sure the button doesn't render on instances without DWH attached
- [x] DWH attached: Make sure the button renders for admins
- [x] DWH attached: Make sure the button renders for non-admins who have sufficient permissions (root collection curate permission + `canUpload` on the DWH)
```
