### ISSUE TITLE
[Epic] Improve InteractiveQuestion and InteractiveDashboard sdk component (Part 1)

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#49713]
**Links**
- product docs:
- [Improvements to Question and Dashboard SDK components](https://www.notion.so/metabase/Improvements-to-Question-and-Dashboard-SDK-components-12469354c90180acbdbcdb8cfeecc455?pvs=4)
- [Make low-hanging fruit improvements to Shoppy](https://www.notion.so/metabase/Make-low-hanging-fruit-improvements-to-Shoppy-12a69354c9018011be49edf18852c7c0?pvs=4)
- eng doc: [improving the question component’s querying experience for embedding sdk](https://www.notion.so/metabase/Tech-Improving-the-question-component-s-querying-experience-for-embedding-sdk-13169354c901802582a8ca9389c544bd?pvs=4)

***Milestone 1***
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/pull/49672
- [ ] https://github.com/metabase/metabase/issues/49716
- [ ] https://github.com/metabase/shoppy/issues/79
- [ ] https://github.com/metabase/metabase/issues/49712
- [ ] https://github.com/metabase/metabase/issues/45766
- [ ] https://github.com/metabase/metabase/issues/49752
- [ ] https://github.com/metabase/metabase/issues/47559
```

***Milestone 2***
```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/49717
- [ ] https://github.com/metabase/metabase/issues/49715
- [ ] https://github.com/metabase/metabase/issues/49718
- [ ] https://github.com/metabase/metabase/issues/50082
- [ ] https://github.com/metabase/metabase/issues/50008
- [ ] https://github.com/metabase/shoppy/issues/85
- [ ] https://github.com/metabase/metabase/issues/47560
```

***Milestone 3***
```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/49719
- [ ] https://github.com/metabase/metabase/issues/49720
- [ ] https://github.com/metabase/metabase/issues/49742
- [ ] https://github.com/metabase/metabase/issues/49743
- [ ] https://github.com/metabase/metabase/pull/50506
- [ ] https://github.com/metabase/metabase/pull/50226
- [ ] https://github.com/metabase/metabase/pull/50401
- [ ] https://github.com/metabase/metabase/pull/50039
- [ ] https://github.com/metabase/metabase/pull/50509
- [ ] https://github.com/metabase/metabase/pull/50522
```

***Related Epics***
- Moved tasks that can be done after the GA release to a separate epic: https://github.com/metabase/metabase/issues/50393
