### ISSUE TITLE
[Epic] Better Onboarding Follow-Ups

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#49788]
## Links
- [product doc](https://www.notion.so/metabase/Better-Onboarding-pt-3-iterations-13469354c90180bebbdfe315a42552de)
- [Figma](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?t=I1qrCjvYrz7lIJlz-0)

```[tasklist]
- [x] Better placement for the checklist when the sidebar is closed (#50368)
- [x] Tweak/replace the video content (#50367)
- [x] Fix the help section ([product spec](https://www.notion.so/metabase/Better-Onboarding-pt-3-iterations-13469354c90180bebbdfe315a42552de?pvs=4#13469354c90181b68873fc5a57dd142c)) #50579
- [x] Replace the "data stack" image ([product spec](https://www.notion.so/metabase/Better-Onboarding-pt-3-iterations-13469354c90180bebbdfe315a42552de?pvs=4#14269354c90180d9ba2dc496bb125fba)) #50579
```
