### ISSUE TITLE
[Epic] Polish the SDK for GA

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#50002]
**Links**
- product doc: https://www.notion.so/metabase/Polish-the-SDK-for-GA-13869354c90180da932cf9f78207f2c6

***API Breaking Changes***
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/48870
``` 

***Bugs***
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/49466
- [ ] https://github.com/metabase/metabase/issues/49581
``` 

**UX Improvements**
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/49711
- [ ] https://github.com/metabase/metabase/issues/47562
- [ ] https://github.com/metabase/metabase/issues/47564
- [ ] https://github.com/metabase/metabase/issues/45766
``` 

**Theming improvements**
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/47559
- [ ] https://github.com/metabase/metabase/issues/45764
- [ ] https://github.com/metabase/metabase/issues/47560
- [ ] https://github.com/metabase/metabase/issues/47567
- [ ] https://github.com/metabase/metabase/issues/48920
```

**Developer Experience**
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/49620
```

**Ugly console & terminal errors**
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/49655
- [ ] https://github.com/metabase/metabase/issues/48498
- [ ] https://github.com/metabase/metabase/issues/48497
- [ ] https://github.com/metabase/metabase/issues/48499
``` 

**Documentation**
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/49762
```

***Related Epics***
- https://github.com/metabase/metabase/issues/49713
