### ISSUE TITLE
Questions in Dashboards - Milestone 2 - Required

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#50173]
note: milestone 2 is required for the minimum-shippable version of questions in dashobards

```[tasklist]
### Milestone 2
- [ ] https://github.com/metabase/metabase/issues/51169
- [x] Refine save-your-changes confirmation dialog (ask Maz) - Sloan working on this now...
- [x] FE: Try to de-duplicate dashboard GET requests (Sloan on it)
- [x] get rid of extra breadcrumb api requests now that dashboards are hydrated on cards (Sloan on it)
- [x] update restored card toast to link to containing dashboard instead of collection for dashboard cards
- [x] update legacy DataSelector to support questions saved in dashboards
- [x] Adjust initialDashboardId calculation
- [ ] https://github.com/metabase/metabase/issues/51346
- [x] ensure old-data picker can handle (embedding added it back) (Arakaki talk to Alberto) - nothing to resolve here
- [x] Update `useRootCollectionPickerItems` to account for passed in `models` (Nick on it)
```
