### ISSUE TITLE
Questions in Dashboards - Milestone 1

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#50172]
```[tasklist]
### Milestone 1
- [x] Create dashboard questions
- [x] Update dashboard questions
- [x] Remove dashboard questions
- [x] Archiving dashboard / permanently deleting dashboards
- [x] Duplicating dashboards w/ dashboard questions
- [x] Dedicated dashboard question page
- [x] Exclude dashboard questions from stale items
- [x] Allow hiding OR showing dashboard questions in search
- [x] Update question picker to show dashboards + dashboard questions
- [x] Add e2e tests
- [x] BE - Integrate trash and revision history for dashboard questions
- [x] BE - autoplace cards on their dashboard when they're created, moved, etc.
- [x] BE: fix autoplace runtime error
- [x] BE: why are dashboard questions appearing in the trash while unarchived?
- [x] BE: duplicating a dashboard doubles its DQs
- [x] BE: autoplace cards on unarchive
- [x] BE: archived DQs still appear on their dashboards
- [x] BE: add context to "invalid dashboard question" errors
- [x] In the question sidesheet, Saved In should refer to the dashboard when it is saved there
- [x] Move standalone questions into dashboards
- [x] Bug: creating a new collection in the entity picker when a dashboard is selected looks like a collection in the dashboard
- [x] Resolve the "add series" feature - dont show series from cards in other dashboards
- [x] FE: fix e2e tests
- [x] FE: fix frontend type check
- [x] FE: fix frontend unit tests
- [x] Make sure the testing plan is satisfied
- [x] FE: fix state propagation in the query builder header
- [x] Add unit tests for collection breadcrumb changes
- [x] Save questions directly to a dashboard that is not in our analytics
- [x] have FE use the bulk cards in dashboard check
```
[Milestone 1 todo doc](https://www.notion.so/metabase/What-s-left-for-Cards-in-Dashboard-to-be-merge-ready-13469354c901801b8636dd466dff06e3)
