### ISSUE TITLE
Questions in Dashboards - Milestone 3 - Polish - after the tool to bulk migrate questions into dashboards

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#50176]
Follow-ups to be done after 52
```[tasklist]
### Milestone 3
- [ ] https://github.com/metabase/metabase/issues/51237
- [ ] [BE] Usage analytics should have all questions inside dashboards (Arakaki will work on this when the tool to migrate questions is done)
- [ ] [BE] Improve revision history copy, "dashboard-internal" in copy is weird (https://metaboat.slack.com/archives/C06RM2GEP5Z/p1736888437835159?thread_ts=1736888123.270439&cid=C06RM2GEP5Z
- [ ] [BE] X-raying a table should create dashboard questions instead of standalone questions
- [ ] [FE] Placeholder cards should allow creating a new question or selecting an existing question
- [ ] [FE] When creating a question in the dashboard edit mode, let the user pick the tab to save it
- [ ] [FE] Users should not be able to save to another dashboard when starting dashboard creation flow from a specific dashboard
- [ ] [FE] User analytics dashboard shouldn't show in the recents tab of collection picker (https://www.notion.so/metabase/It-might-be-unclear-to-the-user-why-Usage-analytics-dashboards-can-t-be-selected-15969354c9018091bc29c8ebb7286600?pvs=4)
- [x] [FE] Source breadcrumbs for dashboard questions based on modals looks bad (https://metaboat.slack.com/archives/C01LQQ2UW03/p1736883192626749
- [x] [FE] Notebook editor showing dashboard name should be a clickable link
- [x] [FE] Confirm move to new dashboard modal is missing `?` (https://metaboat.slack.com/archives/C06RM2GEP5Z/p1736885060785059)
- [x] [FE] Tentative: scroll to question position when adding it to the dashboard
- [x] [FE] Collection picker should allow creating a dashboard on the fly (https://www.figma.com/design/JIHSbaYBdXjkaNSivUG76T/Enable-saving-questions-directly-to-dashboards-and-make-this-the-default-path?node-id=1181-3599&node-type=frame&t=Ve7Mnl2UFiwn0LB4-11)
- [x] [FE] pressing escape twice does not close both the "Select a collection or dashboard” and "Save new question” modal (https://www.notion.so/metabase/P3-pressing-escape-twice-does-not-close-both-the-Select-a-collection-or-dashboard-and-Save-new-q-15969354c901807d8d3fe01274982bd3?pvs=4)
- [x] [FE] When duplicating a question, if the user edits the name, the name input field stays red although there isn't an error (https://www.loom.com/share/c589e607da574376b2230790fc376a21?sid=6da820d2-ea98-4cec-a818-6c388c9ef0de)
```
