### ISSUE TITLE
[Epic] Support language localization in static embedding

### ISSUE THREAD

**Issue by WiNloSt** [metabase/metabase#50182]
**Links**
- [product doc](https://www.notion.so/metabase/Support-language-localization-in-static-embedding-0307665e3008435d9bb2b3fff8148d7d)
- [Original issue](https://github.com/metabase/metabase/issues/8490)

```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/49531
- [ ] https://github.com/metabase/metabase/issues/50199
- [ ] https://github.com/metabase/metabase/issues/50313
- [ ] Write E2E tests for result downloads using user date locale
- [ ] https://github.com/metabase/metabase/pull/51002
- [ ] https://github.com/metabase/metabase/pull/51456
```
