### ISSUE TITLE
Search Index kept up-to-date

### ISSUE THREAD

**Issue by crisptrutski** [metabase/metabase#50204]
```[tasklist]
### Tasks
- [x] Fix tests in CI
- [x] Don't blow away the index for restarts (i.e. schema hasn't changed)
- [ ] Enable for indexed-entity (requires Toucan2 fix)
- [ ] Find another solution than using an after-update hook (e.g. decorating toucan2/update!)
- [ ] Test performance impact (not sure how best to do this, wide scope)
- [ ] Test capturing the cascading deletion flow
- [ ] Automatic data-flow for fields coming from sub-selects
- [ ] Backpressure so we can regulate the load we create on CPU/io
```

**Comment by crisptrutski** [comment]
Toucan2 related issues:

1. Adding after-update hooks causes extra queries and updates to the database.
  - Potentially work around is to use the before update instead, as we add a delay, and the update is idempotent.
2. Adding after-update hooks can cause the return value of `update!` statements to change (from count to a vector)
  - This one is a blocker for indexed-entity, and perhaps future search-models too.

**Comment by crisptrutski** [comment]
Re: smarter bootstrapping

Idea: have another metadata table with version number, schema checksum, last indexed.

Can also make it point directly as `search_index_<uuid>` and use the metadata + atom to track it.
