### ISSUE TITLE
[Epic] Remove inline temporal bucketing from exclude date filter expressions

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#50238]
There are 4 exclude date filters that use temporal buckets:
- `hour-of-day`: `["!=", ["field", 1, {"temporal-unit": "hour-of-day"}], 10]` // excludes 10AM
- `day-of-week`: `["!=", ["field", 1, {"temporal-unit": "day-of-week"}], "2024-11-19"]` // excludes Tuesday because `2024-11-19` is Tuesday
- `month-of-year`: `["!=", ["field", 1, {"temporal-unit": "month-of-year"}], "2024-11-19"]` // excludes November
- `quarter-of-year`: `["!=", ["field", 1, {"temporal-unit": "quarter-of-year"}], "2024-11-19"]` // excludes Q4

We can achieve the same using expressions:
- `hour-of-day`: `["!=", ["get-hour", ["field", 1, null]], 10]` // excludes 10AM
- `day-of-week`: `["!=", ["get-iso-day-of-week", ["field", 1, null]], 2]` // excludes Tuesday
- `month-of-year`: `["!=", ["get-month", ["field", 1, null]], 11]` // excludes November
- `quarter-of-year`: `["!=", ["get-quarter", ["field", 1, null]], 3]` // excludes Q3

Note that I used a non-existing `get-iso-day-of-week` instead of `get-day-of-week` because I don't want these filters to break when someone changes the `start-of-week` setting. `get-iso-day-of-week`  should return 1-7, where 1 is Monday, 7 is Sunday.

```[tasklist]
- [ ] https://github.com/metabase/metabase/issues/50424
- [ ] https://github.com/metabase/metabase/issues/50574
- [ ] https://github.com/metabase/metabase/issues/50670
- [ ] https://github.com/metabase/metabase/pull/50752
- [ ] https://github.com/metabase/metabase/pull/50765
- [ ] https://github.com/metabase/metabase/pull/50888
- [ ] https://github.com/metabase/metabase/pull/50953
- [ ] https://github.com/metabase/metabase/pull/50957
- [ ] https://github.com/metabase/metabase/issues/50920
- [ ] https://github.com/metabase/metabase/issues/50958
```
