### ISSUE TITLE
[Epic] Native editor revamp

### ISSUE THREAD

**Issue by romeovs** [metabase/metabase#50249]
### Links

- [product doc](https://www.notion.so/metabase/Native-editor-revamp-5a4b32bca82646fbb2d6ae455c674602)
- [tech doc](https://www.notion.so/metabase/Tech-doc-Native-editor-revamp-14569354c90180a0846cd5451992cc1c)
- [testing plan](https://www.notion.so/metabase/Testing-plan-Native-editor-revamp-14569354c901803bac92ecb07764e373)
- feature branch: `native-editor-revamp`
- issue links:
  - https://github.com/metabase/metabase/issues/45681
  - https://github.com/metabase/metabase/issues/12520
  - https://github.com/metabase/metabase/issues/16013
  - https://github.com/metabase/metabase/issues/3885
  - https://github.com/metabase/metabase/issues/13693
  - https://github.com/metabase/metabase/issues/48712
  - https://github.com/metabase/metabase/issues/4469
  - https://github.com/metabase/metabase/issues/4587
  - https://github.com/metabase/metabase/issues/26218

### Implementation Plan

```[tasklist]
#### Milestone 1: Research if replacing ACE with CodeMirror 6 is a good idea
- [ ] https://github.com/metabase/metabase/issues/50257
- [ ] https://github.com/metabase/metabase/issues/51090
- [ ] https://github.com/metabase/metabase/issues/51493
- [ ] https://github.com/metabase/metabase/issues/52585
```

```[tasklist]
#### Milestone 2: BE issues
- [ ] https://github.com/metabase/metabase/issues/26218
- [ ] https://github.com/metabase/metabase/issues/16013
- [ ] https://github.com/metabase/metabase/issues/45681
- [ ] https://github.com/metabase/metabase/issues/13693
```

```[tasklist]
#### Milestone 3: FE improvements
- [ ] Allow changing query text size
- [ ] Show database type so the user would know which syntax to use
- [ ] Add a user preference for autoformat settings (ie. tabs vs spaces, number of spaces)
- [ ] Add dark theme
- [ ] Add a user preference for uppercase vs lowercase keywords 
```

```[tasklist]
#### Milestone 4: Revamp data reference
- [ ] Implement preloading and pagination to make it loading faster 
- [ ] Allow to search for connected questions
- [ ] Show tables, columns, models, metrics, questions in tabs so they would be accessible without scrolling
- [ ] Implement click-to-insert button for data reference entries
- [ ] Show table and column descriptions on hover as in other places
- [ ] Update the UI to make it consistent with the new style of the data entry lists 
- [ ] Allow to search in the data reference
```
