### ISSUE TITLE
Search Index testing

### ISSUE THREAD

**Issue by crisptrutski** [metabase/metabase#50261]
```[tasklist]
### Tasks
- [x] 1 per ranker showing it overpowering a draw on others
- [x] Testing that given rankers and filters are enabled (only) for related premium features.
- [x] Test populating the index for all the models and all the cases of their columns
- [x] Test reindex worker
- [x] Test realtime update worker
- [x] Get API tests running against New Search
- [x] Get e2e tests running against New Search
```

```[tasklist]
### Anecdotal scenarios
- [x] [Accounts](https://metaboat.slack.com/archives/C072YM78NGK/p1731616354121189) - verified works, text ranking, and views
- [x] Gather anecdotes from stats complaints
```
