### ISSUE TITLE
[Epic] Migrate entity framework loaders to RTK Query

### ISSUE THREAD

**Issue by kamilmielnik** [metabase/metabase#50317]
### Links
- Eng doc: [[Tech] Migrate entity framework loaders to RTK Query](https://www.notion.so/metabase/Tech-Migrate-entity-framework-loaders-to-RTK-Query-14369354c90180ecadc2d1f1a5dba6e0)
- Feature branches: `master` (early feedback could be invaluable)
- Issue links: 
  - #40788
  - old PR for reference: #50327

### Implementation Plan

```[tasklist]
### Milestone 1 - `EntityObjectLoader`
- [ ] https://github.com/metabase/metabase/issues/44491
- [ ] https://github.com/metabase/metabase/issues/50323
- [ ] https://github.com/metabase/metabase/issues/50873
- [ ] https://github.com/metabase/metabase/issues/51041
- [ ] https://github.com/metabase/metabase/issues/51213
- [ ] https://github.com/metabase/metabase/issues/51050
- [ ] https://github.com/metabase/metabase/issues/50322
- [ ] https://github.com/metabase/metabase/pull/51281
- [ ] https://github.com/metabase/metabase/pull/51333
```

```[tasklist]
### Milestone 2 - `EntityListLoader`
- [ ] https://github.com/metabase/metabase/issues/44492
- [ ] https://github.com/metabase/metabase/issues/50324
- [ ] https://github.com/metabase/metabase/issues/51215
- [ ] https://github.com/metabase/metabase/issues/50325
```

**Comment by kamilmielnik** [comment]
Done
