### ISSUE TITLE
[Epic] Adjust Embedding SDK's API surface before GA

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#50395]
**Links**
- [product doc](https://www.notion.so/metabase/Review-SDK-API-surface-and-adjust-as-needed-13b69354c9018027bba3d58b8db5ff5f?pvs=4)
- [eng doc](https://www.notion.so/metabase/Tech-Review-SDK-s-API-surface-and-propose-adjustments-13e69354c90180a7974fe78c1afce3a1?pvs=4)

**Implementation Plan**

***Milestone 1***
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/50563
- [ ] https://github.com/metabase/metabase/issues/50495
- [ ] https://github.com/metabase/metabase/issues/50005
- [ ] https://github.com/metabase/metabase/issues/50492
- [ ] https://github.com/metabase/metabase/issues/50491
- [ ] https://github.com/metabase/metabase/issues/50490
- [ ] https://github.com/metabase/metabase/issues/50487
- [ ] https://github.com/metabase/metabase/issues/50505
- [ ] https://github.com/metabase/metabase/issues/50493
- [ ] https://github.com/metabase/metabase/issues/50489
- [ ] https://github.com/metabase/metabase/issues/50486
- [ ] https://github.com/metabase/metabase/issues/50396
- [ ] https://github.com/metabase/metabase/issues/50567
```

**Comment by heypoom** [comment]
Closing epic as every PR here is merged. Note that we're pending the backports to 51, as all SDK releases uses the 51 branch.
