### ISSUE TITLE
[Epic] Improve InteractiveQuestion and InteractiveDashboard sdk component (Part 2)

### ISSUE THREAD

**Issue by heypoom** [metabase/metabase#50393]
These are non-blocking improvements or features for InteractiveQuestion and InteractiveDashboard that can be done after the GA release. They do not cause breaking changes in the API.

**Links**
- product docs:
- [Improvements to Question and Dashboard SDK components](https://www.notion.so/metabase/Improvements-to-Question-and-Dashboard-SDK-components-12469354c90180acbdbcdb8cfeecc455?pvs=4)
- [Make low-hanging fruit improvements to Shoppy](https://www.notion.so/metabase/Make-low-hanging-fruit-improvements-to-Shoppy-12a69354c9018011be49edf18852c7c0?pvs=4)
- eng doc: [improving the question component’s querying experience for embedding sdk](https://www.notion.so/metabase/Tech-Improving-the-question-component-s-querying-experience-for-embedding-sdk-13169354c901802582a8ca9389c544bd?pvs=4)

**Milestone 1**
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/49902
- [ ] https://github.com/metabase/metabase/issues/50456
- [ ] https://github.com/metabase/metabase/issues/50007
```

**Polish Interactive Question**
```[tasklist]
### Tasks
- [ ] https://github.com/metabase/metabase/issues/50999
- [x] Change ChartSettingsDropdown `Nonsensible` label to `Other charts`
- [x] Ensure that only the notebook editor _or_ the toolbar is visible
- [x] Make sure visualization height is 100% when used in InteractiveDashboard
- [x] Provide style props for Filter, Summarize, and Breakout pickers
- [x] Change `Question` to `Exploration` in the Interactive Question save modal
```

Related Epics:
- https://github.com/metabase/metabase/issues/51810

**Comment by heypoom** [comment]
@NevRA reviewed and closed 2 issues from this epic, and moved https://github.com/metabase/metabase/issues/49831 to another epic.
