### ISSUE TITLE
Non-admin Onboarding Checklist

### ISSUE THREAD

**Issue by nemanjaglumac** [metabase/metabase#50576]
## Links
- [Product doc](https://www.notion.so/metabase/Better-Onboarding-pt-3-iterations-13469354c90180bebbdfe315a42552de?pvs=4#13469354c90181f695f4fd9bc7757ec2)
- [Figma](https://www.figma.com/design/1QmQUlWK7jACc1oxOfIzxE/Better-onboarding?node-id=6364-30904&t=jkz5hUBlbVM4A8Jw-1)

## The task
Create a non-admin version of the onboarding checklist.

```[tasklist]
- [x] Update the link visibility
- [x] Do not show CTAs for non-admins
- [x] Do not show the "setup" section to non-admins
```
