### ISSUE TITLE
[Epic] Use If as an alias to Case custom expression function

### ISSUE THREAD

**Issue by ranquild** [metabase/metabase#50698]
**Links**

- [Product doc](https://www.notion.so/metabase/Use-If-as-an-alias-to-Case-custom-expression-function-14669354c901807884acf4a950dbf843)

**Implementation Plan**

```[tasklist]
- [ ] https://github.com/metabase/metabase/pull/51069
- [ ] https://github.com/metabase/metabase/pull/50702
- [ ] https://github.com/metabase/metabase/pull/51245
```

**Testing Plan**

- [ ] data type - string, number
- [ ] clase type - custom column, filter, aggregation
- [ ] expression editor - create/read/update
