### ISSUE TITLE
Admin Settings Facelift - Milestone 1

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#50758]
```[tasklist]
### Milestone 1: Refactor existing settings
- [ ] setup RTK to handle settings
- [ ] https://github.com/metabase/metabase/issues/47566
- [ ] Update settings sidebar to use react components instead of data structure
- [ ] Update settings header to use react components instead of data structure
- [ ] basic mantine settings components
- [ ] convert settings to use mantine components and hooks
- [ ] update SettingsEditor component
```
