### ISSUE TITLE
Admin Settings Facelift - Milestone 2

### ISSUE THREAD

**Issue by iethree** [metabase/metabase#50759]
```[tasklist]
### Milestone 2: Implement new settings design
- [ ] new shared UI components
- [ ] update settings top nav design
- [ ] update settings sidebar design
- [ ] update settings pages designs
```
