### ISSUE TITLE
[Epic] [Notification] Alert improvement

### ISSUE THREAD

**Issue by qnkhuat** [metabase/metabase#50766]
### Links

* [product doc](https://www.notion.so/metabase/Alerts-improvements-in-the-new-notifications-architecture-239360679aeb4ea0b26e74fba1725db9?pvs=4)
* technical design doc:
  * [migrate alert to notification](https://www.notion.so/metabase/Migrate-alert-to-notification-14b69354c901801789c6dc34eb12bdc5?pvs=4)
  * [notification API](https://www.notion.so/metabase/Notification-api-14969354c90180ce9e8de76a79cc0a49?pvs=4)
* [testing plan](LINK_TO_TESTING_PLAN)
* feature branch: `a_brave_new_alert`
* issue links:

## Migrate alerts to new schema + Notifications REST API

- [X] [https://github.com/metabase/metabase/pull/51120](https://github.com/metabase/metabase/pull/51120)
- [X] [https://github.com/metabase/metabase/pull/50770](https://github.com/metabase/metabase/pull/50770)
- [X] [https://github.com/metabase/metabase/pull/51267](https://github.com/metabase/metabase/pull/51267)
- [X] [https://github.com/metabase/metabase/pull/50724](https://github.com/metabase/metabase/pull/50724)
- [x] [https://github.com/metabase/metabase/pull/52431](https://github.com/metabase/metabase/pull/52431)
- [X] [https://github.com/metabase/metabase/pull/51120](https://github.com/metabase/metabase/pull/51120)
- [X] [https://github.com/metabase/metabase/pull/51688](https://github.com/metabase/metabase/pull/51688)

## Notification Management

- [X] [https://github.com/metabase/metabase/pull/51267](https://github.com/metabase/metabase/pull/51267)
- [X] [https://github.com/metabase/metabase/pull/51649](https://github.com/metabase/metabase/pull/51649)
- [X] [https://github.com/metabase/metabase/pull/51688](https://github.com/metabase/metabase/pull/51688)
- [ ] [https://github.com/metabase/metabase/pull/52494](https://github.com/metabase/metabase/pull/52494)
- [X] [https://github.com/metabase/metabase/pull/51561](https://github.com/metabase/metabase/pull/51561)
- [x] [https://github.com/metabase/metabase/pull/52109](https://github.com/metabase/metabase/pull/52109)
- [X] [https://github.com/metabase/metabase/pull/52193](https://github.com/metabase/metabase/pull/52193)
- [ ] [https://github.com/metabase/metabase/pull/51852](https://github.com/metabase/metabase/pull/51852)

## Polishing

- [ ] [https://github.com/metabase/metabase/pull/52012](https://github.com/metabase/metabase/pull/52012)
- [X] [https://github.com/metabase/metabase/pull/52078](https://github.com/metabase/metabase/pull/52078)

**Comment by oliviertassinari** [comment]
> Notifications menu with separate entry points for Alerts & Subscriptions

Yes, please! This UX is such a regression compared to before. Alert under Sharing? Lol what

<img width="399" alt="Image" src="https://github.com/user-attachments/assets/b12f7059-3025-4a97-8f7a-a1b4cb16ec55" />

v0.51.6.5

**Comment by fcalvet** [comment]
This caused quite some confusion here as well. No mention in the release notes ?

**Comment by mazameli** [comment]
> Yes, please! This UX is such a regression compared to before. Alert under Sharing? Lol what

@oliviertassinari Agreed — we're fixing this.
