### ISSUE TITLE
[Epic] Sankey Chart v53+

### ISSUE THREAD

**Issue by alxnddr** [metabase/metabase#50833]
## Description

Sankey chart v53+ scope: more visualization settings and support of the other data shape.

- v52 epic: https://github.com/metabase/metabase/issues/29671

## Bug bash

- [ ] Improve color selection algorithm [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524558853679)
- [ ] Improve organization of sankey viz settings in the sidebar [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731524936022419) — **input required**
- [ ] Hide align options when they would not change anything on a given dataset [(link)](https://metaboat.slack.com/archives/C080R5Y30G2/p1731525811819019)

### Milestone 1: Simple customization [1-3 days]

- [ ] Additional tooltip metrics

### Milestone 2: Simple customization [2-5 days]
- [ ] Support reordering via settings sidebar and DnD

### Milestone 3: Suitable Shape #2 from the product doc [1 week]
- [ ] Implement data settings for the [second suitable data shape](https://www.notion.so/metabase/Offer-new-viz-type-Sankey-chart-ebc7f49acbf740249115f65d017e8bf6?pvs=4#11269354c90180d0b14ae0b697dd6904)
- [ ] Implement data transformation
- [ ] Update color assignments
