### ISSUE TITLE
[Epic] Make full-text search default on all instances

### ISSUE THREAD

**Issue by luizarakaki** [metabase/metabase#50927]
### Now
- [x] Programmatically create the index table based on specs (not engine dependent)
- [x] Basic H2 support
- [x] [Co-ordinate index creation and rotation between instances
](https://github.com/metabase/metabase/issues/51279)
- [ ] Define observability metrics and implement them in Prometheus

### To remove old search code
- [x] [Get e2e tests running against New Search](https://github.com/metabase/metabase/pull/50558)
- [ ] MySQL to support the new search index
- [x] Make search possible for models with composite primary key

### After (handed-over to Admin/Webapp)
- [x] [unit test] Test capturing the cascading deletion flow
- [ ] ~~Get H2 ranking on par with Old Search  (then we can remove old search)~~
- [ ] Test performance impact (not sure how best to do this, wide scope)
- [ ] If we need to improve performance, find a lighter way to add hooks to toucan2.
- [ ] Backpressure so we can regulate the load we create on CPU/io
- [ ] Soft-delete search index metadata

### Maybe
- [ ] ~~Automatic data-flow for fields coming from sub-selects[^1]~~
- [ ] Trigger a indexed-entity sync when the Model is updated

[^1]: Stale "dashboard counts", we don't update the index when a card is added to a new dashboard as the relationship is not a regular join.
