### ISSUE TITLE
[Epic] Migrate querying components to CSS from emotion

### ISSUE THREAD

**Issue by uladzimirdev** [metabase/metabase#50983]
### Links
- issue links: [notion](https://www.notion.so/metabase/FE-tech-projects-13f69354c90180b1bd16ca6e51ae8482#13f69354c901802cab6ac803e6d56027)

### Implementation Plan

```[tasklist]
#### Migrate `query_builder` folder to css modules
- [ ] https://github.com/metabase/metabase/pull/50861
- [ ] https://github.com/metabase/metabase/pull/50912
- [ ] https://github.com/metabase/metabase/pull/50911
- [ ] https://github.com/metabase/metabase/pull/50909
- [ ] https://github.com/metabase/metabase/pull/50907
- [ ] https://github.com/metabase/metabase/pull/50864
- [ ] https://github.com/metabase/metabase/pull/51137
- [ ] https://github.com/metabase/metabase/pull/51136
- [ ] https://github.com/metabase/metabase/pull/51219
- [ ] https://github.com/metabase/metabase/pull/51220
```

```[tasklist]
#### Migrate `querying` folder to css modules
- [ ] https://github.com/metabase/metabase/pull/51427
- [ ] https://github.com/metabase/metabase/pull/51430
```

```[tasklist]
#### Followups
- [ ] https://github.com/metabase/metabase/issues/50985
- [ ] https://github.com/metabase/metabase/pull/51542
```
