### ISSUE TITLE
Add ChartSettings button to InteractiveQuestion

### ISSUE THREAD

**Issue by oisincoveney** [metabase/metabase#50999]
https://github.com/metabase/metabase/pull/51154 is blocked until I get, at least, `ChartSettingSelect` in. I want to get  `ChartSettingOrderedItems` with this because they need to have the same styles so it doesn't look disjointed on the core app.

The other ones are optional in terms of features, but are important for polish and theming

```[tasklist]
### Tasks
- [ ] #50998
- [ ] #50994
- [ ] https://github.com/metabase/metabase/pull/51000
- [ ] https://github.com/metabase/metabase/pull/51162
- [ ] https://github.com/metabase/metabase/pull/51210
- [ ] https://github.com/metabase/metabase/pull/51165
- [ ] https://github.com/metabase/metabase/pull/51223
- [ ] #50977
- [ ] https://github.com/metabase/metabase/pull/51332
- [ ] https://github.com/metabase/metabase/pull/51154
- [ ] #50976
```
