### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by rafpaf** [metabase/metabase#51260]
- [ ]  Add ability to link to an arbitrary tab in a sidesheet (this will be needed for the model detail link)
- [ ]  Remove existing model detail pages, links to them, and any related tests or utilities
- [ ]  Add fields to model sidesheet, above the entity id card
- [ ]  Add actions to model sidesheet
- [ ]  Add a relationships tab with a “used by” card and a “relationships” card
