### ISSUE TITLE
[Epic] Dismissible collection clean up banner

### ISSUE THREAD

**Issue by sloansparger** [metabase/metabase#51419]
### Links

- [product doc](LINK_TO_PRODUCT_DOC)
- [technical design doc](LINK_TO_TECHNICAL_DESIGN_DOC)
- [testing plan](LINK_TO_TESTING_PLAN)
- feature branch: `BRANCH_NAME`
- issue links: _related issues, if any_

### Implementation Plan

```[tasklist]
#### Milestone 1 - Basic solution (Backport to 52)
- [ ] BE - Create a global user settings for dismissing the collection clean up banner
- [ ] FE - Dismiss all modals once if the user acknowledges/dismisses a single banner
```

```[tasklist]
#### [IN DEFINITION] Milestone 2 - Better solution (Ship 53+) 
- [ ] BE + FE - Remove global user setting
- [ ] BE - Ship the KV store w/ basic schema (strings, numbers, booleans for v1 - we can think about more complex data later)
- [ ] ...TBD
```
