### ISSUE TITLE
Sync refactoring

### ISSUE THREAD

**Issue by camsaul** [metabase/metabase#5679]
I'm wary of creating meta issues like this because they tend to take on a life of their own and never get closed but I wanted a place to list all the other things to do with sync refactoring without having to stuff them all into a single PR

Here's my TODO list

- [x] Separate scheduling for sync/analysis and caching FieldValues (#4262, #5381 (?))
- [x] Versioning for Fingerprints and a way to make sure relevant fields are re-fingerprinted when needed  (PR #5721 )
- [x] Wire up UI and new API endpoints for the separate scheduling (PR #5464)
- [x] For fingerprinting, just grab complete rows from a table and do all fingerprints for that table instead of doing each column one-at-a-time (PR #5748)
- [x] Add "on-demand" option for caching Field Values. Basically this is the same as "never" but we should update FieldValues for appropriate Fields whenever someone adds a new filter widget to a dashboard. Need new DB flag as well as logic when Dashboards are saved. Also applies to SQL queries with Field Filter widgets (PR: #5830)
- [x] Add per-table/per-field controls to manually trigger caching Field Values. ~@kdoh or @mazameli to provide designs~ Edit: Designs are below. Issue #5381 (?)
- [ ] Don't update table row counts every time metadata sync is done

### Follow-On TODO Possibilities:

- [x] We can probably take out the `table-rows-sample` method entirely :D
- [ ] Make sure we don't pass fingerprints along in endpoints that don't need them (payload size optimization). Especially table metadata since that has the potential to be huge as it is. Also dictionaries aren't free 
- [ ] Should we save FieldValues for Fields with 0 values? Probably not 
- [ ] Hitting "Rescan Field Values" in admin panel logs tons of perms checks. We can skip perms checking since the endpoint is admin only; probably just need to unbind `current-user-perms-set`
- [ ] Reörganize sync tests to match the new sync namespace structure. Currently tests are mostly left untouched as proof the changes didn't break things but as a result there is no clear correlation between where sync code lives and where their tests live (#5636)
- [ ] Change classifiers to return confidence vectors and make changes with highest confidence
- [ ] Remove RawTable/RawColumn from the DB (do this later, in perhaps in 27 or so so as to let people revert without issue)
- [ ] Bug: Filter Field Dropdown list never gets refreshed (#4542). I believe this is already fixed but we could use an extra test to make sure it is.

**Comment by mazameli** [comment]
@camsaul here's what we're thinking for per-field scanning. This would be on the new field options page, e.g. `/admin/datamodel/database/1/table/2/3`

![scan field values](https://user-images.githubusercontent.com/2223916/29681857-e6292d5c-88bd-11e7-817b-16ff767af786.png)

Clicking on the red button should result in a confirmation modal just like it does when you attempt to clear cache values on the database page. Clicking the scan button should result in the same green `scan triggered` state as the corresponding button in the database section.

**Comment by mazameli** [comment]
For per-table scanning, this is a transitional/temporary solution to tide us over until we rework the design for the data model page, so these designs rely heavily on existing patterns and elements that already exist in the admin panel.

First, we'll have to add a button in top right to go to a new table settings page. It's a button instead of an icon because we currently don't use icon action buttons in the top-right in the admin panel the way we do in "user land." This space is currently being taken up by the "show original schema" toggle, so this will also require moving that toggle to the same row as the "columns" heading, midway down the page.

![table-settings-button](https://user-images.githubusercontent.com/2223916/29682820-3f615c2a-88c1-11e7-8af1-a80b542ef305.png)

Ideally, the "show original schema" toggle would only swap out the columns section of the page, rather than the whole page (which is what it currently does):

![show-original-schema](https://user-images.githubusercontent.com/2223916/29683306-b7c1dd7e-88c2-11e7-8507-30921d1b1d83.png)

The new table settings page for now will be pretty sparse, and is just a copy/pasta of the new field settings pages. This will give us a space to put other advanced, per-table options in the future. Note that this mockup has some places where it refers to "field" instead of "table;" that's because I took a screenshot of the current field page and just doctored over it.

Presumably, the "Visibility" dropdown's settings should be "Queryable" and "Hidden" to map to that same setting on the main data model page. The descriptive text below the heading should probably read something more like, "Whether this table should be visible throughout Metabase or not."

The scan buttons at the bottom of this page should follow the pattern of the ones depicted in the per-field scanning designs in the above comment:

![table-settings-page](https://user-images.githubusercontent.com/2223916/29683229-760c3a50-88c2-11e7-9c62-cd13d00bff01.png)

**Comment by camsaul** [comment]
Closing this out since all the big check boxes have been ticked off and I have other open issues for non-critical follow-on stuff like reörganizing tests to match the new code structure
