### ISSUE TITLE
Lots of small polish items for collections 2.0

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#7836]
Will add more items to this issue as I find them. The branch this is all currently based on is `item-type-filters`

### Shit that feels off with a clear solution
- [ ] Search results filter tabs should not include "everything," should default to Dashboards, and should also have a Collections tab. Results will no longer need type headings.

- [ ] If a collection has no sub-collections, but does have saved unpinned items, it would be nice if the `new collection` button/link floated to the right of the list of saved items so that the list can be flush-left with the page title and first pinned item.

### Other
- [ ] It would be really awesome to implement entity menus for saved questions and dashboards

### Resolved
- [x] It appears we lost the empty state illustration for collections - @kdoh
- [x] When a collection only has pinned items and sub-collections, the "drag here to un-pin" landing zone's area and text looks weird
- [x] Clicking on a pulse in a collection goes to e.g. `/pulse/#2` (the old pulses listing page) instead of `/pulse/2` (that pulse's edit form). https://github.com/metabase/metabase/issues/7790
- [x] Moved/archived toast notification should look more like the toast that you get when saving an x-ray: some kind of corresponding icon on the left, and the `undo` link in blue
- [x] Personal collections should not be listed in the full collections permissions grid
- [x]  When creating a new dashboard on question save, the question is not saved in the new dashboard #8007
- [x]  Saving X-Rays and Database addition require a hard refresh #8006
- [x] In the full view collections permissions grid, we should no longer fade out the opacity of any of the cells in the grid. (We used to do this to highlight the current collection, but the new default permission view makes that irrelevant IMO.)
- [x] Sub-collections should have a highlight state when you're dragging an item on top of one to move something into it.
- [x] Saved questions that are saved in the "our analytics" root collection don't have a label on their detail page to show where they're saved - @kdoh 
- [x] Dashboards should have a link to the collection they're saved in, just like saved questions do. https://github.com/metabase/metabase/issues/7518 - @kdoh
- [x] When I click on a collection from the home page, my view isn't scrolled to the top of the window. 
- [x]  ~~There's no way to get out of the collections permissions full-screen modal (it used to have an X in the top-right: ~~ We talked about this and decided its not really an issue since the "modal" doesn't take over the full screen like it used to. Its more like a page now.
- [x] Breadcrumbs should probably have a hover state treatment to show they're clickable
- [x] After I create a new dashboard I should be taken to its detail view. Otherwise, if I'm somewhere else like on a question page or the data reference, it currently creates the dashboard wherever I told it to, but it leaves me on the current view, which is confusing.
- [x] Settle on an icon for Account-Settings/Admin/Logs/About/Sign-out that we like more than the person silhouette icon
- [x] When clicking on any of the filter tabs, the search term is dropped, so every item of the filtered type in the whole instance is shown.
- [x] Bug: Users without curate bit are being shown the "New Collection" button
- [x] Bug: if a saved question etc. in a collection is at the bottom of a list in a browser window that has to scroll to show the item, the click target for that item is really funky.
- [x] When creating a new pulse, if the user clicks `Cancel` they should not be taken to `/collection/undefined`. Ideally they'd be taken back to wherever they were when they first had clicked `New pulse`
- [x] We should hide or kill the collection color selection in the new collection modal
- [x] The `edit collection` modal should be the same type of modal as the `create collection` modal
- [x] Saved questions' icons should be a representation of their visualization type instead of the beaker icon
- [x] After archiving a collection, the user should be redirected to the parent collection instead of the home page
- [x] After creating a new collection, the user should stay at the current collection rather than being redirected inside of the new collection. (That way they can put items from the current collection into the new collection right away, which is presumably why they created the new collection in the first place.)
- [x] I think the vertical spacing between sub-collections in a list could be tightened up
- [x] ~~Consider bringing the `…` menu for saved items right next to their titles. (It could be always visible, but very faint until the item's row is hovered on. That could prevent the icon from feeling like it's popping in and out as you move over the items.)~~
- [x] After clicking on `New pulse` the entity menu should close itself.
- [x] The pulse creation forms and the setup flow forms should have a white background color:
- [x] The sign up form no longer has first and last name side by side:
- [x] Schema listing shouldn't have x-rays and data reference links for now
![screen shot 2018-07-10 at 4 46 36 pm](https://user-images.githubusercontent.com/107439/42543504-0a4a3fc4-8461-11e8-92b0-119dba33152f.png)

- [x] Collection titles shouldn't collide with items saved in the collection (fixed width plus wrapping?):
- [x] If the only thing in a collection is a pinned item or a subcollection, we shouldn't show this funky: empty state for the saved items area.
- [x] The bottom of lists of saved items should have some margin below it.
- [x] The label for the current collection I'm in doesn't need to be a link
- [x] The New Item button shouldn't float above the initials dropdown menu.
- [x] The `Collections` label shouldn't show up if there aren't any collections (already called out in #7797).
- [x] The empty collection illustration should be centered on the page (also mentioned already in #7797)

**Comment by MarkRx** [comment]
In saved items the panel on the left should still show up even after drilling into a collection.

**Comment by camsaul** [comment]
User initials circle doesn't match color when switching to admin panel

![image](https://user-images.githubusercontent.com/1455846/41366430-ecdcabdc-6ef0-11e8-9a72-a76b46d178d9.png)

**Comment by camsaul** [comment]
it’s weird that the nav bar for admin is just slightly bigger than non-admin and it jumps in size when I enter admin mode

it would look nicer if they were the same height IMO

**Comment by camsaul** [comment]
exiting admin panel is broken

https://github.com/metabase/metabase/issues/7868

**Comment by camsaul** [comment]
exiting question is broken

#7869

**Comment by kdoh** [comment]
> When clicking on any of the filter tabs, the search term is dropped, so every item of the filtered type in the whole instance is shown.

15e4aed

**Comment by kdoh** [comment]
> The edit collection modal should be the same type of modal as the create collection modal

11eb42f

**Comment by kdoh** [comment]
> Breadcrumbs should probably have a hover state treatment to show they're clickable

088f129

**Comment by kdoh** [comment]
> After archiving a collection, the user should be redirected to the parent collection instead of the home page

bad19fb

**Comment by kdoh** [comment]
> When creating a new pulse, if the user clicks Cancel they should not be taken to /collection/undefined. Ideally they'd be taken back to wherever they were when they first had clicked New pulse

069ad78

**Comment by kdoh** [comment]
>  Saved questions' icons should be a representation of their visualization type instead of the beaker icon
8fc4b90

**Comment by kdoh** [comment]
> The sign up form no longer has first and last name side by side:
https://github.com/metabase/metabase/pull/8017

**Comment by kdoh** [comment]
>  Bug: if a saved question etc. in a collection is at the bottom of a list in a browser window that has to scroll to show the item, the click target for that item is really funky.
>  Bug: Users without curate bit are being shown the "New Collection" button

https://github.com/metabase/metabase/pull/8020

**Comment by kdoh** [comment]
> After I create a new dashboard I should be taken to its detail view. Otherwise, if I'm somewhere else like on a question page or the data reference, it currently creates the dashboard wherever I told it to, but it leaves me on the current view, which is confusing.

https://github.com/metabase/metabase/pull/8021

**Comment by kdoh** [comment]
> After clicking on New pulse the entity menu should close itself.

https://github.com/metabase/metabase/pull/8022

**Comment by mazameli** [comment]
When I click on a collection from the home page, my view isn't scrolled to the top of the window. (I'll add this to the checklist.)

![scroll-me](https://user-images.githubusercontent.com/2223916/42591725-6718696a-84fc-11e8-89a3-e196ebb84c96.gif)

**Comment by mazameli** [comment]
Here's what I meant by `Dashboards should have a link to the collection they're saved in, just like saved questions do.` I also think that this badge, both for saved questions as well dashboards, should ignore the old collection color and just always be the `brand` color since we've removed the ability to set/edit collection colors.

![dashboard-collection-label](https://user-images.githubusercontent.com/2223916/42651122-4c354cae-85c3-11e8-8f43-e826208c879d.png)

**Comment by mazameli** [comment]
Clicking on a pulse in a collection goes to e.g. `/pulse/#2` (the old pulses listing page) instead of `/pulse/2` (that pulse's edit form).

**Comment by mazameli** [comment]
> It appears we lost the empty state illustration for collections

This is fixed in master.

**Comment by mazameli** [comment]
Closing this and spinning off remaining open things into https://github.com/metabase/metabase/issues/10239 and https://github.com/metabase/metabase/issues/10240
