### ISSUE TITLE
Popover scrolling master issue

### ISSUE THREAD

**Issue by mazameli** [metabase/metabase#8377]
There have been a number of issues reported related to popovers not scrolling and being cut off when then browser window is short. We can add others here as they crop up.

- [x] https://github.com/metabase/metabase/issues/8296 Visualization dropdown is cut off
- [x] https://github.com/metabase/metabase/issues/8370 Can't scroll in table/DB list (I just reproduced this in 0.30.1)
- [ ] https://github.com/metabase/metabase/issues/8281 Drill-through popover isn't scrollable
- [x] https://github.com/metabase/metabase/issues/6844 Dashboard filter field mapping popover cut off

**Comment by jornh** [comment]
With #8296 resolved in 0.30.2 I’m wondering how many of these got squashed as well?  All?

**Comment by mazameli** [comment]
@jornh #8370 and #8281 still seem present on master unfortunately.
