### ISSUE TITLE
Frontend Cleanup

### ISSUE THREAD

**Issue by tlrobinson** [metabase/metabase#927]
This is an ongoing issue used to track various things we can do to cleanup the frontend.

General:
- [x] remove Angular #2495
- [x] decide on a folder structure for components directory
- [x] move the FE up a few levels? `resources/frontend_client/app/...` seems vestigial at this point.
- [ ] TESTS!

JS:
- [ ] Consolidate / clean up query lib (see #4775):
  * metabase/lib/query
  * metabase/lib/query_time
  * metabase/lib/schema_metadata
  * metabase/lib/types
  * metabase/lib/query/*
  * metabase/meta/*
  * Make sure we're generating MBQL-98 compliant queries (fix warnings in backend logs). e.g. order-by clauses with aggregate clause references
- [ ] Consolidate metadata loading / redux reducers / actions / selectors (see #4775)
  * metabase/redux/metadata
  * metabase/qb/*
  * metabase/admin/datamodel/*
  * ?
- [x] Enable other eslint rules
  - standardize on let > var, and use const where applicable?
- [ ] remove deprecated MBQL clauses. regexes:
  - `\["(fk->|datetime-field|asc|desc)", \d+`
- [x] replace imports ending in `.jsx`
- [ ] remove circular dependencies, especially `metabase-lib` depending on `metabase`
- [x] Enable `prettier` on entire codebase
  - we should have an opinion on single vs double quotes in JS and enforce it (#965)
- [ ] Remove dead JavaScript (started on #948)
- [ ] More code splitting #4665
- [x] ensure consistent use of PropTypes in React components (#963)
- [x] unused constants in core.js (#2912)
- [ ] standardize admin settings update patterns / code (#2850)
- [ ] Rework [`sql_behaviour.js`]
- [x] Rename query builder modules to match CamelCased component names (#923)
- [x] Remove references to "corvus", "cv", etc (#923)
- [x] Enable `no-unused-vars` eslint rule, remove unused variables (#923)
- [x] Remove JQuery
- [x] Explicitly declare all dependencies (React, underscore, angular, angular modules?)
- [x] convert all react components that can be converted to es6 class syntax (#1192)
- [x] nuke .react.js in favor of .jsx  (seems like the standard these days)
- [x] Remove use of deprecated React.addons.classSet (#929) (https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/ace/sql_behaviour.js) to use AmE spelling ("behavior")

CSS:
- [x] Remove dead CSS (#1234)
- [ ] nuke the whole "NewForm / Form-new" scoping business now that we've converted all the forms"
- [ ] make sure we're following the BEM classname syntax properly in all instances.
- [ ] Replace "grey" with "gray" (["gray" is the American spelling](http://grammarist.com/spelling/gray-grey/))
- [ ] look for CSS that redefines or uses base css values and use those classes instead
- [ ] burn all the CSS with :fire:  and use Radium / JS based styles ??

⬇️  Please click the 👍 reaction instead of leaving a `+1` or 👍  comment

**Comment by camsaul** [comment]
Is #2495 part of this 😱

**Comment by camsaul** [comment]
🚿

**Comment by salsakran** [comment]
how much of this is still relevant @tlrobinson ?

**Comment by tlrobinson** [comment]
I checked off a couple more things in the JS section, the rest are still relevant-ish. The main thing is deciding which set of ESLint rules to use and migrate to it. I'm leaning towards AirBnB's style guide + ESLint rules (https://github.com/airbnb/javascript) mostly because it's more popular and less offensive to me than "Standard" (http://standardjs.com/)

Not sure about the CSS ones. @kdoh?

**Comment by lewisl9029** [comment]
RE:  standardize on let > var, and use const where applicable?

Might make more sense to default to const instead of let or var. Reassignment really should be the special case here, if it's ever needed at all.

**Comment by tlrobinson** [comment]
Yeah, that's generally what @kdoh and I have started doing. Also it's enforced by the AirBnB ESLint preset https://github.com/airbnb/javascript#references--prefer-const

**Comment by camsaul** [comment]
this has been open 2 years is it finished yet slash can we close this?

**Comment by camsaul** [comment]
Did #3444 resolve this?

**Comment by salsakran** [comment]
@camsaul nope, "This is an ongoing issue"

The issue isn't meant to be finished or closed as it. That's a separate statement of whether this sort of omnibus issue is appropriate given how we organize things, which is a separate concern.

**Comment by camsaul** [comment]
@metabase/core-developers what's the status of this? It's been 4 years. Can we break this out into actionable items and close this?

**Comment by tlrobinson** [comment]
My current wishlist:

1. nuke enzyme e2e tests, replace with cypress tests
2. make `metabase-lib` completely standalone, no references to modules inside `metabase` (enforced via CI)
3. start extracting a basic component library into `metabase-ui` which is also completely standalone, no references to modules inside `metabase`, and uses an idiomatic/consistent method of styling (and skinnable for data apps?)
4. upgrade to React 16 (and probably latest Webpack, Babel, etc)
5. nuke Flow in favor of TypeScript

**Comment by the-mann** [comment]
@tlrobinson Is there anything resembling a consensus on moving from Flow to TypeScript? I am working on a fork of this lovely project, and I'd like to know whether or not I should hold of on typing until we switch over

**Comment by flamber** [comment]
@the-mann There's no timeline on any of the above ideas - or if they will even be implemented.

**Comment by gusaiani** [comment]
Applicable improvements will be handled in other issues.
